### ISSUE TITLE
Error occurs when enabling editor.renameOnType, for HTML tag.

### ISSUE THREAD

**Issue by jinyongp** [microsoft/vscode#101511]
- VSCode Version: 1.46.1
- OS Version: Ubuntu Budgie 20.04

Steps to Reproduce:

1. Enable editor.renameOnType option.
![image](https://user-images.githubusercontent.com/21158729/86256757-a8b36e80-bbf3-11ea-8be6-a7715baef2ce.png)

2. Create any html tag using emmet. (span `tab` -> `<span></span>`)
3. __Undo__.
4. Some characters turn red like below.
![image](https://user-images.githubusercontent.com/21158729/86255744-75bcab00-bbf2-11ea-8770-d20964dca31f.png)
5. Type any key. Something will happen.
![image](https://user-images.githubusercontent.com/21158729/86256665-8f122700-bbf3-11ea-826b-713362d391ac.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Fixed by 362e49228c8ba5ae1d267f2789a474129e8c37ca

**Comment by abhijit-hota** [comment]
> Fixed by [362e492](https://github.com/microsoft/vscode/commit/362e49228c8ba5ae1d267f2789a474129e8c37ca)

I'm sorry but I still face the issue in the latest update of VS Code.
Guess I'll just disable the feature for now. Thanks for your time.

**Comment by aeschli** [comment]
@abhijit-hota What version are you? The fix is in the latest insiders or in the next stable (1.49.0)

**Comment by abhijit-hota** [comment]
@aeschli 

> On what version are you? 
As I've mentioned in #106056 , I'm using `1.48.2`.

> The fix is in the latest insiders or in the next stable (1.49.0)
I see. I guess the version's not available for my system yet. 

![image](https://user-images.githubusercontent.com/8116174/92238566-27b87200-eed7-11ea-8e8a-ee01b0bf4b32.png)
