### ISSUE TITLE
If a debug adapter fails to send a `terminated` event, VS Code gets stuck in debug mode

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#102037]
See: https://github.com/microsoft/vscode/issues/100368#issuecomment-654354230 VS Code can get stuck in a state where it thinks a debug session is going, but trying to end the session results in an error "No debug adapter, cannot send 'terminate'".

Might only happen with multiple parent/child sessions. Can be reproed perfectly by commenting out the two `dap.terminated()` calls in `binder.ts` within js-debug.

**Comment by isidorn** [comment]
Thanks for creating this. I acknowledge that VS Code relies on the adapter sending a terminate event to nicely dispose the debug session and thus end the debug mode.

What we could do to improve this:
- [ ] Pressing the red stop button by the user should always terminate the session, even if the terminate can not be sent

I am open for other ideas to improve this.

Unassigning you Connor since I can tackle this on the VS Code side. Just let me know if you have additional ideas here.

**Comment by connor4312** [comment]
> Pressing the red stop button by the user should always terminate the session, even if the terminate can not be sent

In the case when the debug adapter already stopped, I think this is good behavior

**Comment by isidorn** [comment]
@connor4312 I have pushed a potential fix for this.
In case the user hits the stop or disconnect we fire a "fake" terminated event to clear out all the state.
Since I could not reproduce this issue reliably I would ask you to try it out since you mentioned that you have good repro steps. So can you please try it out and let me know how it goes?
Thanks!

**Comment by connor4312** [comment]
Thanks! Using it for the last week (and in particular looking into a self-host issue where this happened 100% of the time) think this is a good change. It's still a problem in the debug adapter but VS Code no longer gets stuck in the bad state.

**Comment by isidorn** [comment]
Great, thanks for letting me know.
