### ISSUE TITLE
Upgrading from 1.46 to 1.47 causes breakpoints in Node app to be unbound

### ISSUE THREAD

**Issue by nynj** [microsoft/vscode#102253]
- VSCode Version: 1.47
- OS Version: Windows 10

Steps to Reproduce:

1. In 1.46 run typescript/node app in debug mode with breakpoint set in program file (e.g. test.js)
2. Execution pauses in program file at breakpoint
3. Upgrade to 1.47
4. Same execution does not pause, during execution breakpoint disc is grey instead of red and hovers as "breakpoint unbound"
5. Downgrade by reinstalling 1.46
6. Breakpoint works again

Does this issue occur when all extensions are disabled?: Unknown, I already downgraded to 1.46

**Comment by connor4312** [comment]
@nynj are you using Node 8? If so, this may be what you're running into: https://github.com/microsoft/vscode/issues/102166#issuecomment-657138385

**Comment by decyph** [comment]
Im running into the same issues as @nynj

- VSCode Version: 1.47
- OS Version: macOS Catalina 10.15.5
- Downgrading to 1.46 fixes the issue

**Comment by connor4312** [comment]
@decyph Can you please collect a trace log using these instructions?

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

As a temporary workaround you can set `debug.javascript.usePreview: false` to use the old debugger.

**Comment by nynj** [comment]
Node 14.3.0

**Comment by connor4312** [comment]
Okay, thanks. Can you capture a log using the instructions above?

**Comment by decyph** [comment]
@connor4312 this what you need?
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/4907896/vscode-debugadapter-0.json.gz)

**Comment by connor4312** [comment]
@decyph it looks like your webRoot is currently set to your workspace at

```
"/Users/christian.castillo/Projects/vue-sandbox"
```

But it should be 

```
"/Users/christian.castillo/Projects/vue-sandbox/myProject"
```

So setting `webRoot: "${workspaceFolder}/my-project"` should fix the issue.

The previous debugger had lots of trouble with Vue in general. We reworked how Vue projects work in this debugger (mainly in https://github.com/microsoft/vscode-js-debug/commit/2f3c93a08df0ceb09eda86251d0309d34bfb26ef) so some config changes _can_ be needed for Vue projects specifically.

**Comment by decyph** [comment]
@connor4312 , my project folder is actually called "my-project" so I updated webRoot to look like this:

`"webRoot": "${workspaceFolder}/my-project"`

but, i'm still having the same issues with debugging.

here's the log also:
[vscode-debugadapter-2.json.gz](https://github.com/microsoft/vscode/files/4907916/vscode-debugadapter-2.json.gz)

**Comment by connor4312** [comment]
In the log you sent it looks like you successfully paused at the breakpoint 9 seconds into the debug session. Is there another issue you're referring to?

**Comment by decyph** [comment]
The problem is that its not stopping at the correct spot. 

![image](https://user-images.githubusercontent.com/1654333/87237509-186fe900-c3ac-11ea-9e34-ca56ee829adf.png)

i'm trying to add a breakpoint on line 43, but keeps selecting line 40 instead. If I try to select 43 again, it gives me "Unbound breakpoint"

**Comment by connor4312** [comment]
Okay, thanks for that information. That means it's some kind of issue. It may be with Vue, or with the debugger.

It looks like it's some hello-world app -- is it possible for you to push that to a repo for me to look into further?

**Comment by decyph** [comment]
@connor4312 https://github.com/decyph/vscode-issue-102253

**Comment by connor4312** [comment]
It seems that `lang="ts"` removes the device we rely upon to figure out which among the generated Vue files is the one we're after, and there is no other apparent way to figure it out. I will update the issue I have on Vue. There's no action we can take in js-debug with your configuration at the moment; the generated code paths are indistinguishable from the 'real' one.

**Comment by nynj** [comment]
I'll try to, although I'm trying to get some work done and can't upgrade right now.

**Comment by ervinoro** [comment]
I'm facing the same issue ("breakpoint unbound" in 1.47; fixed by downgrading to 1.46) with a Next.js react app.

`debug.javascript.usePreview: false` fixes the issue.

Node: v14.4.0
macOS: 10.15.5

Adding the debugger; instruction does not break either.

**Comment by connor4312** [comment]
@ervinoro this is because setting NODE_OPTIONS overwrites the bootloader that js-debug uses to set up debugging. You can just omit that line and everything will work 🙂

**Comment by nynj** [comment]
I have emailed the trace to connor@xbox.com

I was able to duplicate this issue with a brand new node project, after copying in the launch.json file (also tsconfig from other proj).  It seems to be adding the launch.json that reveals the issue. I can do a breakpoint stop fine when manually choosing Node run task, but once I add launch.json and run, breakpoints go unbound.
[nodetest.zip](https://github.com/microsoft/vscode/files/4909938/nodetest.zip)

**Comment by connor4312** [comment]
Beautiful, thanks for the reproduction steps. It appears that the problem is this line in your tsconfig:

```
    "sourceRoot":"C:\\nodetest",	
```

This causes the generated sourcemaps to have

```
"sourceRoot":"C:/nodetest/","sources":["app.ts"]
```

Which says that the app.ts source file is in C:/nodetest/app.ts, where it's actually C:/nodetest/src/app.ts. Removing that line fixes the issue on my machine. If you need to keep it, then it should be set to `C:/nodetest/src`.

Also, just a tip for general setup -- the most common issue behind breakpoints not binding is js-debug thinking that the source file is in the wrong place on your disk. The trick I use, rather than going through logs, is adding a `debugger;` statement in my code. This will cause VS Code to open the file/path it thinks is where the source file is, which can hint at what's wrong in my build setup or launch configuration.

Given this is the problem in your real setup as well, things seem to be working as intended. Let me know if you hit other issues.

**Comment by nynj** [comment]
OK, thank you. Any idea why this was not an issue in 1.46 but is in 1.47?

**Comment by connor4312** [comment]
Sourcemap handling in the new debugger is different than the old one -- more correct/compliant in general. There might have been some reconciliation/fuzzy matching happening in the old debugger that the new one doesn't do. Or even a 'bug' that allowed this scenario to work before, e.g. not considering absolute paths. I would have to dig into that.

**Comment by connor4312** [comment]
A fix for this issue has now been released in VS Code 1.47.2. If you previously had to opt-out of the new debugger, you should be safe to turn it back on. Thanks again for the report!

**Comment by nynj** [comment]
Few updates here:
- I upgraded to 1.47.2 . There is no difference from 1.47.1 in my ability to use breakpoints with the setup from my original report
- With 1.47.2 installed I tried your suggestion of changing tsconfig to `"sourceRoot":"C:/nodetest/src"`. Breakpoints are still unbound.  I also tried `C:\\nodetest\\src` just to see if that helped, it didn't. So as of now I am unable to use debugging breakpoints for my projects.

**Comment by connor4312** [comment]
Ok, thanks for the update. Would you mind collecting a trace log again with these fixes in place?

**Comment by nynj** [comment]
I have significantly pared down my example app, and still have issues with unbound debug. Here's a clue: if I comment out everything in launch.json, I can manually choose to Run And Debug using Node when I hit F5. This method of running hits the breakpoint, so it seems to be related to my `launch.json`. I also decided to delete content of `launch.json` and use the Add Configuration to make sure there was nothing wrong with that.  Creating a new "Node / Launch Program" file has the same issue, no breakpoint stops (although it creates a config with type "pwa-node" instead of my old "node".

I will email the trace again.
[nodetest (2).zip](https://github.com/microsoft/vscode/files/5009279/nodetest.2.zip)

**Comment by connor4312** [comment]
@nynj it looks like source maps are not turned on in the log/sample you sent. Setting `sourceMap: true` in the tsconfig will fix it.
