### ISSUE TITLE
Dropdown base font-size increased on Insiders

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#103185]
Issue Type: <b>Bug</b>

See debug viewlet and terminal dropdown:

![image](https://user-images.githubusercontent.com/35271042/88317630-65b65980-ccce-11ea-9008-df65f13e6306.png)

Compared to Stable:

![image](https://user-images.githubusercontent.com/35271042/88317671-78309300-ccce-11ea-85ce-650419fa253c.png)

VS Code version: Code - Insiders 1.48.0-insider (8c426f9f3b6b18935cc6c2ec8aa6d45ccd88021e, 2020-07-23T05:40:23.559Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|-psn_0_4240395 --enable-proposed-api miguelsolorio.vscode-fluent-icons --crash-reporter-id 6c893641-26cf-4adf-abbc-7a4135b893c1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-track-build-errors|aes|0.0.2
mock-debug|and|0.42.1
markdown-checkbox|bie|0.1.3
vscode-opennewinstance|chr|0.0.7
vscode-eslint|dba|2.1.8
pug-formatter|duc|0.6.0
gitlens|eam|10.2.2
prettier-vscode|esb|5.1.3
vscode-open-in-github|fab|1.2.3
vscode-pull-request-github|Git|0.18.1
todo-tree|Gru|0.0.178
all-symbol-kinds|jri|0.0.1
vscode-colorize|kam|0.8.17
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.1.17
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.9.0
vscode-azureappservice|ms-|0.17.0
vscode-azurestaticwebapps|ms-|0.2.0
python|ms-|2020.8.95714-dev
vscode-pylance|ms-|2020.7.3
remote-containers|ms-|0.128.0
remote-ssh-edit-nightly|ms-|2020.7.22500
remote-ssh-nightly|ms-|2020.7.22500
remote-wsl|ms-|0.44.4
azure-account|ms-|0.9.1
hexeditor|ms-|1.1.0
vscode-github-issue-notebooks|ms-|0.0.35
vscode-markdown-notebook|ms-|0.0.10
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.9
vetur|oct|0.25.0
LiveServer|rit|5.6.1
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.0.1
enumerator|swi|0.0.6
sass-indented|syl|1.8.9
ms-teams-vscode-extension|Tea|1.0.3
sort-lines|Tyr|1.9.0

(3 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
@misolori is it possible to create a minimal example with the `<select>` tag , seems like we are falling back to the default font size `13.3333px` but without minimal repro will be hard to get any help from upstream.

**Comment by misolori** [comment]
So my Chrome just updated to `Version 85.0.4183.38 (Official Build) beta (64-bit)` and now I can't reproduce this:

![image](https://user-images.githubusercontent.com/35271042/88336749-64932580-ccea-11ea-850d-0bc61d41767e.png)

Not sure if this helps?

**Comment by deepak1556** [comment]
thats helpful to know that this is an upstream issue which got fixed eventually :)

Once we have a repro, we could then track down the actual upstream issue.

**Comment by nrayburn-tech** [comment]
Most likely related to the chromium form elements re-work?  https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html

A few screenshots from different versions of Google Chrome.  81 has the 11px size, 83, and 85 have the 13.33px size.
81
![81](https://user-images.githubusercontent.com/52075362/88345418-86e96b00-cd0b-11ea-9f74-0c629ff95a98.png)
83
![83](https://user-images.githubusercontent.com/52075362/88345420-86e96b00-cd0b-11ea-84e1-01e8a0ff3026.png)
85
![85](https://user-images.githubusercontent.com/52075362/88345422-87820180-cd0b-11ea-87f9-e08db3e3af0b.png)

**Comment by deepak1556** [comment]
Oh interesting, that certainly looks related.

**Comment by deepak1556** [comment]
@misolori are you sure its fixed in Chrome 85 ?

I just tested canary and my numbers match @nrayburn-tech comment, it always defaults to `13.3333px`

**Comment by misolori** [comment]
@deepak1556 I was wrong (was testing out local changes), 85 + 86 still show the default `13.333px` font size

**Comment by bpasero** [comment]
I also think that we "lost" the round style it used to have:

![image](https://user-images.githubusercontent.com/900690/91458447-d4ff0a80-e885-11ea-8879-d7a59fb57794.png)

vs.

![image](https://user-images.githubusercontent.com/900690/91458461-d9c3be80-e885-11ea-9c3b-38b1b7992b7f.png)

But maybe that is intentional. I see the same design in Chrome web.

**Comment by nrayburn-tech** [comment]
Looks like the border-radius went from 5px to 0px as the default.
I don’t think Chrome is changing back, so should the styling be added into a style sheet for the dropdown in vscode?

**Comment by bpasero** [comment]
Not sure why we would want to change the default Chrome picked, before we also just relied on the browser's default and now the look is aligned with Windows it seems.

**Comment by bpasero** [comment]
Hm, I think in case of the debug dropdown though it causes a bit of glitch:

![image](https://user-images.githubusercontent.com/900690/91460891-ab93ae00-e888-11ea-8257-1107f91d9b6a.png)

//cc @isidorn

**Comment by bpasero** [comment]
Related: https://github.com/electron/electron/issues/24317

**Comment by isidorn** [comment]
@bpasero I think there is a bit of css for the debug dropdown to align it well with the play button on the left..

**Comment by octref** [comment]
11px aligns with `TERMINAL | PROBLEMS | OUTPUT` etc and the icon much better than the new default.

![image](https://user-images.githubusercontent.com/4033249/92987273-9dce6180-f4f3-11ea-9e97-53891afe9b0f.png)

13.33 px looks very out of place. it aligns neither with text to its left or icon to its right.

![image](https://user-images.githubusercontent.com/4033249/92987283-aa52ba00-f4f3-11ea-9d8b-e1d176fbebbe.png)

**Comment by bpasero** [comment]
@misolori do you want to make a PR for how you think it should look like? To be honest, we did not get any substantial numbrer of user complaints so far, so maybe we just leave it?

**Comment by misolori** [comment]
@bpasero I'll create a PR for it, personally not a fan of the larger font-size and prefer the rounded corners on mac to match the context menu edges:

![image](https://user-images.githubusercontent.com/35271042/93944570-f4088500-fce9-11ea-9d26-119fb1ad4334.png)

**Comment by bpasero** [comment]
**Verification:**
* test on Windows, macOS and Linux
* verify the dropdown (e.g. in output panel or debug viewlet) looks OK after this change and the font size is not too small
