### ISSUE TITLE
start debug multi folder workspace startup dialog

### ISSUE THREAD

**Issue by rvanbree** [microsoft/vscode#103261]
Issue Type: <b>Bug</b>

Dialog pops up when debugging starts:
'${workspaceFolder}' can not be resolved in a multi folder workspace. Scope this variable using ':' and a workspace folder name.

VS Code version: Code 1.47.2 (17299e413d5590b14ab0340ea477cdd86ff13daf, 2020-07-15T18:18:50.054Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
vscode-eslint|dba|2.1.8
githistory|don|0.6.8
json-tools|eri|1.0.2
docthis|joe|0.7.1
git-graph|mhu|1.24.0
vscode-docker|ms-|1.4.1
js-debug-nightly|ms-|2020.7.2317
sqltools|mtx|0.22.11
sqltools-driver-mysql|mtx|0.1.0
vscode-graphql|Pri|0.2.14
vscode-icons|vsc|10.2.0
material-theme|zhu|3.8.5

(1 theme extensions excluded)

</details>

**Comment by weinand** [comment]
If possible, please share your launch config us.

**Comment by AskAlice** [comment]
see: #103099 and #94725 

This is in the same workspace config, i am only sharing what is necessary
```json
"folders": [
    {
      "name": "React",
      "path": "app"
    },
    {
      "name": "apollo",
      "path": "../backend-redacted"
    },
    {
      "name": "Deployment",
      "path": "../.."
    },
    {
      "name": "redacted",
      "path": "../../../.."
    }
  ],
```

```json
"launch": {
    "configurations": [
      {
        "name": "React: Chrome",
        "type": "chrome",
        "request": "launch",
        "url": "http://localhost:3000",
        "webRoot": "${workspaceFolder:React}/src",
        "sourceMapPathOverrides": {
          "webpack:///src/*": "${webRoot}/*"
        },
        "presentation": {
          "hidden": false,
          "group": "React",
          "order": 1
        }
      },
      {
        "name": "React: Debug Unit Tests",
        "type": "node",
        "request": "launch",
        "cwd": "${workspaceFolder:React}",
        "runtimeExecutable": "${workspaceFolder:React}/node_modules/.bin/react-scripts",
        "args": [
          "test",
          "--runInBand",
          "--no-cache",
          "--watchAll=false",
          "--env=jsdom"
        ],
        "protocol": "inspector",
        "console": "integratedTerminal",
        "internalConsoleOptions": "neverOpen",
        "env": {
          "CI": "true"
        },
        "skipFiles": [
          "<node_internals>/**/*.js",
          "${workspaceFolder:React}/node_modules/**/*.js",
          "${workspaceFolder:React}node_modules\\**\\*.js",
          "<node_internals>/**/*.js"
        ],
        "disableOptimisticBPs": true,
        "presentation": {
          "hidden": false,
          "group": "React",
          "order": 1
        }
      },
      {
        "name": "apollo-server",
        "trace": "verbose",
        "type": "node",
        "request": "launch",
        "cwd": "${workspaceFolder:apollo}",
        "runtimeExecutable": "${workspaceFolder:apollo}/node_modules/.bin/ts-node-dev",
        "args": [
          "--respawn",
          "--inspect",
          "--inspect-brk=9229",
          "--transpileOnly",
          "--ignore-watch=node_modules",
          "./src/server.ts"
        ],
        "protocol": "inspector",
        "console": "integratedTerminal",
        "internalConsoleOptions": "neverOpen",
        "env": {
          "CI": "true"
        },
        "skipFiles": [
          "<node_internals>/**/*.js",
          "${workspaceFolder:apollo}/node_modules/**/*.js",
          "${workspaceFolder:apollo}node_modules\\**\\*.js",
          "<node_internals>/**/*.js"
        ],
        "disableOptimisticBPs": true,
        "presentation": {
          "hidden": false,
          "group": "apollo-server",
          "order": 1
        },
        "port": 9229,
        "restart": true
      }
    ],
    "compounds": [
      {
        "name": "Full Stack Debugging",
        "configurations": [
          "React: Chrome",
          "apollo-server"
        ],
        "presentation": {
          "hidden": false,
          "group": "all",
          "order": 10
        }
      }
    ]
  }
```

**Comment by connor4312** [comment]
Please try setting your launch `"type": "pwa-node",` instead of node and `"type": "pwa-chrome", instead of chrome -- we've made improvements here.

**Comment by rvanbree** [comment]
I tried that. No change,  I still get the same error/warning dialog.

**Comment by rvanbree** [comment]
{

  "version": "0.2.0",

  "configurations": [

    {

      "type": "pwa-node",

      "request": "launch",

      "name": "Launch via NPM",

      "runtimeExecutable": "npm",

      "console": "integratedTerminal",

      "runtimeArgs": [

        "run-script",

        "start:dev"

      ],

      "skipFiles": [

        "<node_internals>/**"

      ]

    },

    {

      "type": "pwa-node",

      "request": "launch",

      "name": "Launch Vital-Signs-Service",

      "program": "${workspaceFolder}/server.js",

      "envFile": "${workspaceFolder}/.env",

      "console": "integratedTerminal",

      "args": [

        "--inspect=9229",

        "--runInBand",

        "--config",

        "--require tsconfig-paths/register",

        "--require dotenv/config"

      ],

      "skipFiles": [

        "<node_internals>/**"

      ]

    },

    {

      "type": "node",

      "request": "launch",

      "name": "Debug Jest Tests",

      "cwd": "${workspaceFolder}",

      "envFile": "${workspaceFolder}/.env",

      "args": [

        "--inspect-brk",

        "${workspaceRoot}/node_modules/.bin/jest",

        "--runInBand",

        "--config",

        "${workspaceRoot}/jest.config.js"

      ],

      "windows": {

        "args": [

          "--inspect-brk",

          "${workspaceRoot}/node_modules/jest/bin/jest.js",

          "--runInBand",

          "--config",

          "${workspaceRoot}/jest.config.js"

        ]

      },

      "console": "integratedTerminal",

      "internalConsoleOptions": "neverOpen"

    },

    {

      "type": "node",

      "request": "attach",

      "name": "Debug Attach VSS 9229",

      "protocol": "inspector",

      "port": 9229,

      "restart": true,

      "localRoot": "${workspaceFolder}",

      "remoteRoot": ".",

      "sourceMaps": true

    },

    {

      "type": "node",

      "request": "launch",

      "name": "Jest Current File",

      "program": "${workspaceFolder}/node_modules/.bin/jest",

      "args": [

        "${fileBasenameNoExtension}",

        "--config",

        "jest.config.js"

      ],

      "console": "integratedTerminal",

      "internalConsoleOptions": "neverOpen",

      "disableOptimisticBPs": true,

      "windows": {

        "program": "${workspaceFolder}/node_modules/jest/bin/jest",

      }

    }

  ]

}

**Comment by connor4312** [comment]
@rvanbree if you have that in your workspace config, then that's expected, since the workspaceFolders you have aren't scoped to a single folder.

**Comment by rvanbree** [comment]
No that was launch.json. sorry

**Comment by rvanbree** [comment]
I am not sure what you want??? My launch.json was sent. the
workspace.code-workspace just has files/folders listed.

**Comment by AskAlice** [comment]
@rvanbree if you're using ${workspaceFolder} you need to specify a folder name. 
see: https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-launch-configurations
It depends on your  "folders" directive: https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file-schema

**Comment by AskAlice** [comment]
@connor4312 `pwa-node` executes, but
`"protocol": "inspector",` seems deprecated, and 
`"console": "integratedTerminal",`  seems to only run one command which spawns a CMD window completely detached from the integrated terminal (equivalent as writing `&&` in a unix terminal)

```${env:CI}='true'; ${env:NODE_OPTIONS}='--require "c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" '; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.20804-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"fileCallback":"C:\\Users\\alice\\AppData\\Local\\Temp\\node-debug-callback-3ac9abe1b0df0127"}'; & 'C:\Users\alice\[redacted]\[redacted]\[redacted]\[redacted]\[redacted]\[redacted]/node_modules/.bin/ts-node-dev' '--respawn' '--inspect' '--inspect-brk=9229' '--transpileOnly' '--ignore-watch=node_modules' './src/server.ts'
```

**Comment by rvanbree** [comment]
integratedTerminal opens an integrated terminal that shows the logging and
console.log print statements.

**Comment by connor4312** [comment]
@AskAlice thanks for the update! Indeed, we released a [new debugger](https://github.com/microsoft/vscode-js-debug/) in the most recent VS Code update. By default the old debuggers will redirect to the new debugger _after_ resolving config, but in multi-root workspaces we sometimes need the config resolution to go to the new debugger for config resolution step, which is what `pwa-node` does.

Some things are deprecated as you noticed -- we no longer support Node < 7, so dropped the protocol, and don't need a specific port to attach. We filter out --inspect-brk automatically if given in the runtimeArguments (where it's usually placed for Node to consume) but don't do that in the program `args` to avoid causing issues there.

>  seems to only run one command which spawns a CMD window completely detached from the integrated terminal 

This is unexpected, I'll look at that...

**Comment by AskAlice** [comment]
@connor4312 this is probably related to the above 
https://github.com/microsoft/vscode/issues/103099#issuecomment-665195383

**Comment by rvanbree** [comment]
@AskAlice  : Adding the {workspacefolder:folder} does not help - I still get the dialog twice... hmmmm?

**Comment by AskAlice** [comment]
@rvanbre is that a workspace configuration? it looks more like a launch.json in a `.vscode` folder

**Comment by rvanbree** [comment]
projectX.code-workspace has a folders json array { "folders":[ "path": {"some-folder"}, ...]};

**Comment by rvanbree** [comment]
Ha! I figured it out!
I was not seeing output from the logger so I used the
"console":"IntegratedTerminal" and that caused the weird error dialog to
display.

I am now using "outputCapture":"std"

winner!

**Comment by connor4312** [comment]
That's... interesting. Variable resolution happens independently of what console it's running in. Any chance you can take a screenshot of the "weird error" dialog you were seeing?

**Comment by adammahon** [comment]
Just an FYI, this seems to occur when using the `"debug.node.autoAttach": "on"` setting. Which is a problem since using `autoAttach: on` means no launch.json file exists.

**Comment by connor4312** [comment]
@adammahon you're seeing https://github.com/microsoft/vscode/issues/103099
