### ISSUE TITLE
WebWorker extension host never starts on OSS, preventing debugging

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#103873]
@rebornix noticed that extension debugging on OSS with the webworker extension host enabled does not work.

I traced it to this promise never resolving

https://github.com/microsoft/vscode/blob/83e542bd07927497c2af4da573b6af98b18bcb48/src/vs/workbench/contrib/debug/browser/debugService.ts#L272

Down to the `_proxy` never being resolved for the webworker extension host

https://github.com/microsoft/vscode/blob/83e542bd07927497c2af4da573b6af98b18bcb48/src/vs/workbench/services/extensions/common/extensionHostManager.ts#L125

To reproduce:

1. Run OSS with the web worker extension host turned on
1. Try to debug any project/any language
1. You get an "activating extensions" spinner for a bit, but nothing happens

**Comment by alexdima** [comment]
Sorry about that!

Fixed via f3b79b0d36919289eb79158aad68be88b23c16dc

**Comment by connor4312** [comment]
I still see this happening on today's Insiders.

but removing -important since the web worker is not yet public consumption, and disabling the web worker extension host allows for debugging to work.

**Comment by alexdima** [comment]
@connor4312 I cannot reproduce. Here is what I am doing:
* configure `"extensions.webWorker": true`
* create a file `test.js` with the content `console.log(`hello world!`);`
* put a breakpoint on the console statement
* press F5

I notice that the breakpoint is hit:
![Kapture 2020-08-07 at 17 47 34](https://user-images.githubusercontent.com/5047891/89663659-27c45280-d8d6-11ea-8928-6474b615810c.gif)

**Comment by connor4312** [comment]
Oh, my bad, I mentally conflated this and https://github.com/microsoft/vscode/issues/104004.

Things work here!
