### ISSUE TITLE
Strange custom dropdown behavior

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#104411]
- Focus a custom dropdown
  - On Mac, this is only the settings dropdown
  - On windows, any dropdown
    - Doesn't repro with the output or terminal dropdowns, probably because we move focus after closing them
- Press enter to open it
- Press enter again to close it
- It blinks and stays open

---

Even weirder

- Focus the custom dropdown
- Press space to open it
- You get the native dropdown (in settings editor, you can tell because the enum descriptions don't show up)
- Close it
- Press enter to open it
- You get the custom dropdown

**Comment by roblourens** [comment]
I think this is from https://github.com/microsoft/vscode/issues/103496

When I press enter and the dropdown is open, it is closed by keydown here:
https://github.com/Microsoft/vscode/blob/roblou/settings-list/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L749

Then reopened by keyup at https://github.com/microsoft/vscode/commit/1a2a371c487d29b6dec33579c5f106f53a9d7fb7

**Comment by isidorn** [comment]
@roblourens thanks for filling this and yes I can repro.
Reverting my commit fixes this issue.
We should include this in the july release.

**Comment by isidorn** [comment]
Fixed via https://github.com/microsoft/vscode/pull/104416

**Comment by roblourens** [comment]
Needs fix in master too

**Comment by isidorn** [comment]
@roblourens I pushed a fix to master, just did not link it here.
https://github.com/microsoft/vscode/commit/8a57c4cef7f55dd9b542e20b7a561351126cf2ff

**Comment by roblourens** [comment]
I thought it wasn't fixed for me in master yesterday after syncing, but I must have done something wrong
