### ISSUE TITLE
1.48.1 is missing from apt repository

### ISSUE THREAD

**Issue by fastcat** [microsoft/vscode#105316]
Issue Type: <b>Bug</b>

1. `sudo apt update`
2. `apt policy code`
3. Expect to see 1.48.1 available
4. Only 1.48.0 is available

VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.7.0-2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 3473)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.08GB (22.40GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.3.1
markdown-preview-github-styles|bie|0.1.6
bracket-pair-colorizer-2|Coe|0.2.0
systemd-unit-file|coo|1.0.6
vscode-markdownlint|Dav|0.36.3
xml|Dot|2.5.1
EditorConfig|Edi|0.15.1
go|gol|0.16.1
vscode-systemd-support|han|0.1.1
vscode-peacock|joh|3.8.0
bash-ide-vscode|mad|1.11.0
python|ms-|2020.8.103604
vscode-yaml|red|0.10.0
bash-debug|rog|0.3.9
vscode-workspace-switcher|sad|1.15.3
code-spell-checker|str|1.9.0
html-preview-vscode|tht|0.2.5
reflow-paragraph|Tro|1.3.0

(1 theme extensions excluded)

</details>

https://packages.microsoft.com/repos/vscode/pool/main/c/code/ -- can see that 1.48.1 is missing there

Front page download links _do_ provide 1.48.1 package.

**Comment by mumeiyamibito** [comment]
I have the same issue.

The gear mark in pane notified me of the update, but it doesn't seem to have the latest package in the repository. I'm worried about this notice and I can't get to work!

**Comment by zgoda** [comment]
This happens with almost every update.

**Comment by Tyriar** [comment]
This was fixed https://github.com/microsoft/vscode/issues/105289, background on this one is that the repo service we consume deprecated an API and didn't manage to fix it before I disappeared on vacation for a week (and I only had permissions for something required). @zgoda fwiw this issue was special, the typical problem that occurs is related to the service not synchronizing metadata correctly after we publish.

**Comment by fastcat** [comment]
@Tyriar Thank you for the update, but unfortunately, unlike the insiders issue, the stable version is not actually fixed -- still only 1.48.0 is available

**Comment by strigona-worksight** [comment]
I'm in the same boat - I have not received the update through apt.

**Comment by strigona-worksight** [comment]
Update just came through :)
