### ISSUE TITLE
Trailing comma warning from Code's default settings.json & workspaceSettings.json

### ISSUE THREAD

**Issue by TheWyo** [microsoft/vscode#105414]
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Use JSON settings editor & split JSON editor view
2. Open Settings (User settings vs workspace settings view will trigger the respective warning)
3. Warnings now stuck in Problems pane till VS Code is reloaded

![Screenshot](https://user-images.githubusercontent.com/1192064/91301052-30ed6480-e79c-11ea-9c23-1fd19143dac2.jpg)

Mentioned by someone in #103009, but couldn't find a separate issue raised as requested.
Identical to #80419.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Fixed by 81204145b50ac6fa27d1e00e2b53c811ab0524f9

**Comment by sachish12** [comment]
I am also getting same error. I have tried everything but cannot fixed it.

**Comment by aeschli** [comment]
I still get the trailing comma error when opening the default settings.
