### ISSUE TITLE
`find all references` not working with `export * as`

### ISSUE THREAD

**Issue by AlexanderMann** [microsoft/vscode#106419]
Issue Type: <b>Bug</b>

Issues with Typescript's `export * as` functionality, and `find all references`.

### `a/b.ts`
```ts
export interface Foo {
  bar: string;
}
```

### `a/index.ts`
```ts
export * as MyTypes from './b';
```

### `c.ts`
```ts
import { MyTypes } from './a';

interface MoreFoo extends MyTypes.Foo {
  baz: string;
}
```

## To reproduce

With the above file structure, if you `find all references` of `Foo` inside of `c.ts`, you will only see the declaration in `b.ts`, not the usage inside `c.ts`.

If you change the `import {MyTypes} from './a'` to `import * as MyTypes from './a/b'`, `find all references works as expected.

## Of Note

We were able to reproduce this on our team on a number of different team members' boxes, all after having refreshed VSCode, and all after having run `npm ci` etc.

## Versions

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:08:29.692Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 11, 11|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|-psn_0_16002882|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.16.8
quitcontrol-vscode|art|3.1.3
spellright|ban|3.0.52
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.8
graphviz-preview|EFa|1.3.3
prettier-vscode|esb|5.6.0
terraform|has|2.2.3
vscode-phpfmt|kok|1.0.30
rainbow-csv|mec|1.7.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.5.0
python|ms-|2020.8.108011
vscode-typescript-tslint-plugin|ms-|1.2.3
vscode-yaml|red|0.10.1
rust|rus|0.7.8
markdown-pdf|yza|1.4.4

</details>

**Comment by mjbvz** [comment]
Here's in VS Code insiders (1.49) with TypeScript 4.0.2:

<img width="1277" alt="Screen Shot 2020-09-10 at 2 14 24 PM" src="https://user-images.githubusercontent.com/12821956/92807704-faa10f00-f36f-11ea-8345-689d052c0e57.png">

Seems correct

**Comment by AlexanderMann** [comment]
Well, that's a bummer. I'm wondering if this is an issue with TS 3.9.7 (what we're using locally). Will dig a bit more and report back.

**Comment by AlexanderMann** [comment]
Okayyyyyy so fun times, but this appears to work on Insiders. @mjbvz not sure if that's a clue for you as to what might be up here, but that was definitely shocking. @timbotnik can provide more info

**Comment by mjbvz** [comment]
Sounds like we already fixed the bug then :)

**Comment by timbotnik** [comment]
Seems like still broken in today's 1.49.0 (non-insider) build.  I noticed if I use the alternative syntax it works as expected:
```js
import * as MyTypes from './b';
export { MyTypes };
```

**Comment by mjbvz** [comment]
Are you using TypeScript 4.0.2?

**Comment by timbotnik** [comment]
TS 3.9.7 (edited my msg above)

**Comment by mjbvz** [comment]
It sounds like TS 4.0.2 (which is the default TypeScript version in VS Code 1.49) already fixed the problem
