### ISSUE TITLE
after vs code update, ng serve command doesn't work anymore in vs code terminal

### ISSUE THREAD

**Issue by narem81** [microsoft/vscode#106631]
I closed VS Code as usual after a daywork and I noticed the update bar. When I opened it the day after I found this problem. 
I tried to run ng serve command out of vs code, in a windows command line and also in git bash and it works without any problems.

The error message is the following:

 ng serve
93% after chunk asset optimization SourceMapDevToolPlugin vendor.js generate SourceMap
<--- Last few GCs --->

[7912:000001FF78FA51B0]   138105 ms: Mark-sweep 2033.1 (2064.9) -> 2027.8 (2079.6) MB, 415.9 / 0.1 ms  (average mu = 0.101, current mu = 0.018) allocation failure scavenge might not succeed
[7912:000001FF78FA51B0]   138546 ms: Mark-sweep 2040.2 (2079.6) -> 2036.3 (2066.6) MB, 422.4 / 0.0 ms  (+ 0.1 ms in 198 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 441 ms) (average mu = 0.073, current mu = 0.043) all

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF79F41CEDF v8::internal::wasm::DisjointAllocationPool::~DisjointAllocationPool+74383
 2: 00007FF79F3C5A16 v8::base::CPU::has_sse+62326
 3: 00007FF79F3C68B6 v8::base::CPU::has_sse+66070
 4: 00007FF79FC2BBDE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF79FC10DA4 v8::SharedArrayBuffer::Externalize+772
 6: 00007FF79FACFF7C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1452
 7: 00007FF79FADB53A v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
 8: 00007FF79FAD8461 v8::internal::Heap::PageFlagsAreConsistent+3233
 9: 00007FF79FACD665 v8::internal::Heap::CollectGarbage+1413
10: 00007FF79FACBD15 v8::internal::Heap::AllocateExternalBackingStore+1397
11: 00007FF79FAECD4F v8::internal::Factory::NewFillerObject+191
12: 00007FF79F830E01 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1409
13: 00007FF79FCB348D v8::internal::SetupIsolateDelegate::SetupHeap+465869
14: 000002F676287F8D

**Comment by narem81** [comment]
I have already set the node_options environment variable with value --max_old_space_size=8192.
This didn't solve the problem.

**Comment by benoitbzl** [comment]
Hello. I am experiencing the same issue from the windows CMD integrated shell of the VS Code version 1.49 (August 2020). My windows environment defines NODE_OPTIONS=--max_old_space_size=8192, but this env variable is removed by the integrated shell.

**Comment by connor4312** [comment]
thanks for the issue -- can you try setting the `debug.javascript.usePreviewAutoAttach` to false, and then relaunching your terminal/reloading VS Code?

**Comment by connor4312** [comment]
This'll be fixed in the next release

**Comment by narem81** [comment]
> debug.javascript.usePreviewAutoAttach

I set this to my settings.json... the problem still persists.

**Comment by connor4312** [comment]
Did you relaunch your terminal or reload VS Code after doing so?

**Comment by narem81** [comment]
I have set this option to false in workspace and also in user. After that I deleted the terminal, closed vs code, I did reopen it and then reopen terminal. Therefore i ran ng serve command and... same problem

**Comment by connor4312** [comment]
What's the value of the NODE_OPTIONS environment variable in the terminal? (e.g. `echo NODE_OPTIONS` or `echo $env:NODE_OPTIONS`, depending on your shell)

**Comment by narem81** [comment]
![image](https://user-images.githubusercontent.com/12350609/93113144-1b8f9a00-f6b9-11ea-805b-63128ed126f2.png)

**Comment by narem81** [comment]
I use git bash
I tried echo NODE_OPTIONS and echo $env:NODE_OPTIONS inside the built in terminal , nothing has appeared

**Comment by connor4312** [comment]
Okay. cc @Tyriar  -- it looks like we cleared the environment variable mutations made in js-debug, but narem reports the environment variable is empty after doing so. Can you help investigate?

**Comment by narem81** [comment]
Thank you very much for your support. It would be very useful to have this functionalty again.
Please, could you reopen this issue since it has not been solved yet?

**Comment by narem81** [comment]
I would let you notice that, If I run the **_ng serve_** command inside a Javascript Debug Terminal , it works whithout any problems. 
Just for your information, It could be significant for the solution.

**Comment by Tyriar** [comment]
> it looks like we cleared the environment variable mutations made in js-debug, but narem reports the environment variable is empty after doing so.

@connor4312 not sure I'm understanding the problem here, isn't `NODE_OPTIONS` meant to be empty if js-debug cleared the mutations?

**Comment by connor4312** [comment]
It looked like they had set NODE_OPTIONS in their user/global environment variables

**Comment by Tyriar** [comment]
I can't repro this. Here's what I tried specifically which I think captured the problem:

1. Create an env var, set to "foo"
2. Launch VS Code
3. Run an extension command that updates the env var to "bar"
4. Relaunch terminal, it's set to "bar"
5. Run an extension command that clears the env collection
6. Relaunch terminal, it's set to "foo"

**Comment by benoitbzl** [comment]
Hello, the problem still exists (at least for Windows environment) for latest version of VS Code. Please reopen the issue.
Here is a repro (for Windows).
From a Windows CMD:
- set the node option env variable:
- from this CMS, start vscode

> set NODE_OPTIONS=--max-old-space-size=5120
> code .

From VS code, start the integrated command line terminal, configured to start a Windows CMD process (regular command line, not a js-debug one). My setting defines the option:
- "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe"

From this integrated terminal, list the env variables:
>set

The env variable NODE_OPTIONS has been removed

**Comment by mpk** [comment]
I have the same issue with NODE_OPTIONS environment variable. It's set as a system environment variable, but when I run `dir env:` in the integrated PowerShell in VSCode to list the variables, it's missing.

I think the issue is in Electron, which [strips almost all NODE_OPTIONS flags](https://github.com/electron/electron/blob/94381cda493ceccb457e7714030074d45124f408/docs/api/environment-variables.md#node_options) in packaged apps. When I set "allowed" node option, such as `--max-http-header-size`, I was able to see it in the integrated terminal.

My environment:
```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```
