### ISSUE TITLE
Problem in settings sync

### ISSUE THREAD

**Issue by Krrishdhaneja** [microsoft/vscode#106857]
- VSCode Version:1.49.0
- OS Version:windows 10 pro

Steps to Reproduce:

1.I enabled settings sync
2.but it was not working and didn't sync my extensions

**Comment by sandy081** [comment]
Can you please elaborate on what is not working? Are there any errors?

Can you please troubleshoot using the Settings Sync log available in Output View?

**Comment by Krrishdhaneja** [comment]
Actually the extensions were not syncing when I reinstalled vscode . I have to manually install them.
So , this is the problem

**Comment by sandy081** [comment]
Can you please provide the steps to repro?

**Comment by gouletjg** [comment]
I think I am having the same issue. I can create a new issue if preferred.

Steps to reproduce:

1. Activate settings sync (the built in VSCode feature, not the extension).
2. Check the logs. All "json" settings appear to sync properly (and I have yet to notice otherwise).
3. See below for logs.

I can provide additional logs or details if needed. 

```
[2020-09-27 18:19:19.730] [userDataSync] [info] Sync done. Took 43ms
[2020-09-27 18:20:09.952] [userDataSync] [info] Auto Sync: Triggered by Activity
[2020-09-27 18:20:09.998] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-09-27 18:20:10.005] [userDataSync] [info] Keybindings: No changes found during synchronizing keybindings.
[2020-09-27 18:20:10.010] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-09-27 18:20:10.021] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-09-27 18:20:10.024] [userDataSync] [error] TypeError: Cannot read property 'content' of null
    at E (file:///C:/Users/jgoul/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:451:45)
    at e.generateSyncPreview (file:///C:/Users/jgoul/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:452:542)
    at e.doGenerateSyncResourcePreview (file:///C:/Users/jgoul/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:444:543)
[2020-09-27 18:20:10.024] [userDataSync] [error] extensions: Cannot read property 'content' of null
[2020-09-27 18:20:10.024] [userDataSync] [info] Sync done. Took 38ms
```

**Comment by sandy081** [comment]
- Can you please run the command `Settings Sync: Open Local Backups Folder`.
- In the opened folder go to `extension` folder and there will be a file named `lastSyncextensions.json`
- Can you please provide us the content of this file?

**Comment by gouletjg** [comment]
Sorry this took so long. This is the only line in 'lastSyncextensions.json':

```
{"ref":"0","content":null,"skippedExtensions":[]}
```

**Comment by ethanmay** [comment]
I am also getting this error, with the same output that @gouletjg described.

**Comment by sandy081** [comment]
To verify:

- Turn on Settings Sync
- Run the command `Settings Sync: Open Local Backups Folder`  and go to `extension` folder and open `lastSyncextensions.json` file.
- Replace the contents of the file with following
```
{"ref":"0","content":null,"skippedExtensions":[]}
```
- Make sure Settings Sync log in output view does not show any errors and sync extensions correctly.

**Comment by Krrishdhaneja** [comment]
@sandy081 would be trying this

**Comment by Krrishdhaneja** [comment]
It is not working till now 
this is the same Version 92192ba
![image](https://user-images.githubusercontent.com/65185487/101134864-03cd0f80-3631-11eb-95cc-68dcbcb64b7d.png)
and still my extensions are not coming.

**Comment by Krrishdhaneja** [comment]
this is what i found in lastSyncextensions.json
{"ref":"34cecabe-a485-4237-b550-a521e572555c","content":"{\"version\":5,\"machineId\":\"8b0c6eaa-a5f2-4274-8653-6edc2e3d7447\",\"content\":\"[{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.bat\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.clojure\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.coffeescript\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.configuration-editing\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.cpp\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.csharp\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.css\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.css-language-features\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.debug-auto-launch\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.debug-server-ready\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.docker\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.emmet\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.extension-editing\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.fsharp\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.git\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.git-ui\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.github\\\"},\\\"version\\\":\\\"0.0.1\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.github-authentication\\\"},\\\"version\\\":\\\"0.0.1\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.go\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.groovy\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.grunt\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.gulp\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.handlebars\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.hlsl\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.html\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.html-language-features\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.image-preview\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.ini\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.jake\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.java\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.javascript\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.json\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.json-language-features\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.less\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.log\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.lua\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.make\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.markdown\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.markdown-language-features\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.merge-conflict\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.microsoft-authentication\\\"},\\\"version\\\":\\\"0.0.1\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"ms-vscode.js-debug\\\",\\\"uuid\\\":\\\"25629058-ddac-4e17-abba-74678e126c5d\\\"},\\\"version\\\":\\\"1.51.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"ms-vscode.js-debug-companion\\\",\\\"uuid\\\":\\\"99cb0b7f-7354-4278-b8da-6cc79972169d\\\"},\\\"version\\\":\\\"1.0.8\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"ms-vscode.node-debug\\\",\\\"uuid\\\":\\\"b6ded8fb-a0a0-4c1c-acbd-ab2a3bc995a6\\\"},\\\"version\\\":\\\"1.44.14\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"ms-vscode.node-debug2\\\",\\\"uuid\\\":\\\"36d19e17-7569-4841-a001-947eb18602b2\\\"},\\\"version\\\":\\\"1.42.5\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"ms-vscode.references-view\\\",\\\"uuid\\\":\\\"dc489f46-520d-4556-ae85-1f9eab3c412d\\\"},\\\"version\\\":\\\"0.0.71\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"ms-vscode.vscode-js-profile-table\\\",\\\"uuid\\\":\\\"7e52b41b-71ad-457b-ab7e-0620f1fc4feb\\\"},\\\"version\\\":\\\"0.0.11\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.npm\\\"},\\\"version\\\":\\\"1.0.1\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.objective-c\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.perl\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.php\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.php-language-features\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.powershell\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.pug\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.python\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.r\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.razor\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.ruby\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.rust\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.scss\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.search-result\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.shaderlab\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.shellscript\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.sql\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.swift\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.theme-abyss\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.theme-defaults\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.theme-kimbie-dark\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.theme-monokai\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.theme-monokai-dimmed\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.theme-quietlight\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.theme-red\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.vscode-theme-seti\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.theme-solarized-dark\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.theme-solarized-light\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.theme-tomorrow-night-blue\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.typescript\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.typescript-language-features\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.vb\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.xml\\\"},\\\"version\\\":\\\"1.0.0\\\"},{\\\"identifier\\\":{\\\"id\\\":\\\"vscode.yaml\\\"},\\\"version\\\":\\\"1.0.0\\\"}]\"}","skippedExtensions":[]}

**Comment by Krrishdhaneja** [comment]
and these are all the extensions i was having but still it wasn't syncing it

**Comment by Krrishdhaneja** [comment]
and this is the log of settings sync 
[2020-12-04 13:05:32.322] [userDataSync] [info] Using settings sync service https://vscode-sync-insiders.trafficmanager.net/
[2020-12-04 13:05:32.322] [userDataSync] [info] Auto Sync is enabled.
[2020-12-04 13:05:32.322] [userDataSync] [info] Auto Sync: Suspended until auth token is available.
[2020-12-04 13:05:34.758] [userDataSync] [info] Auto Sync: Started
[2020-12-04 13:05:34.758] [userDataSync] [info] Auto Sync: Triggered by Interval
[2020-12-04 13:05:36.220] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-12-04 13:05:36.248] [userDataSync] [info] Keybindings: Skipped synchronizing keybindings as it is disabled.
[2020-12-04 13:05:36.268] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-12-04 13:05:36.811] [userDataSync] [info] GlobalState: Updated remote ui state
[2020-12-04 13:05:36.821] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2020-12-04 13:05:37.043] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-12-04 13:05:37.045] [userDataSync] [info] Sync done. Took 1123ms
[2020-12-04 13:05:39.892] [userDataSync] [info] Auto Sync: Triggered by Activity
[2020-12-04 13:05:40.212] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-12-04 13:05:40.219] [userDataSync] [info] Keybindings: Skipped synchronizing keybindings as it is disabled.
[2020-12-04 13:05:40.230] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-12-04 13:05:40.583] [userDataSync] [info] GlobalState: Updated remote ui state
[2020-12-04 13:05:40.592] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2020-12-04 13:05:40.711] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-12-04 13:05:40.713] [userDataSync] [info] Sync done. Took 532ms
[2020-12-04 13:05:47.578] [userDataSync] [info] Auto Sync: Triggered by Activity
[2020-12-04 13:05:47.925] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-12-04 13:05:47.940] [userDataSync] [info] Keybindings: Skipped synchronizing keybindings as it is disabled.
[2020-12-04 13:05:47.957] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-12-04 13:05:48.063] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-12-04 13:05:48.174] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-12-04 13:05:48.176] [userDataSync] [info] Sync done. Took 305ms

**Comment by Krrishdhaneja** [comment]
@sandy081 ?

**Comment by sandy081** [comment]
Can you please explain more about

 > and still my extensions are not coming.

Can you please install / uninstall an extension and check if it is syncing in your another VS Code instance? Also provide settings sync log while doing this operation.

**Comment by Krrishdhaneja** [comment]
On non-insiders version you are talking about @sandy081 ?

**Comment by sandy081** [comment]
> On non-insiders version you are talking about @sandy081 ?

Not sure if I understand this question.

**Comment by Krrishdhaneja** [comment]
I am asking that should i try syncing of extensions on Normal VS code

**Comment by sandy081** [comment]
Please try syncing between two insiders instances.

**Comment by Krrishdhaneja** [comment]
Ok got it.

**Comment by Krrishdhaneja** [comment]
this is the log 
[2020-12-05 12:14:12.112] [userDataSync] [info] Using settings sync service https://vscode-sync-insiders.trafficmanager.net/
[2020-12-05 12:14:12.112] [userDataSync] [info] Auto Sync is enabled.
[2020-12-05 12:14:12.112] [userDataSync] [info] Auto Sync: Suspended until auth token is available.
[2020-12-05 12:14:20.035] [userDataSync] [info] Auto Sync: Started
[2020-12-05 12:14:20.035] [userDataSync] [info] Auto Sync: Triggered by Interval
[2020-12-05 12:14:21.869] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-12-05 12:14:21.872] [userDataSync] [info] Keybindings: Skipped synchronizing keybindings as it is disabled.
[2020-12-05 12:14:21.877] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-12-05 12:14:23.807] [userDataSync] [info] GlobalState: Updated remote ui state
[2020-12-05 12:14:23.815] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2020-12-05 12:14:24.201] [userDataSync] [info] Extensions: Updated remote extensions
[2020-12-05 12:14:24.207] [userDataSync] [info] Extensions: Updated last synchronized extensions
[2020-12-05 12:14:24.210] [userDataSync] [info] Sync done. Took 2370ms
[2020-12-05 12:14:26.905] [userDataSync] [info] Auto Sync: Triggered by Activity
[2020-12-05 12:14:27.149] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-12-05 12:14:27.152] [userDataSync] [info] Keybindings: Skipped synchronizing keybindings as it is disabled.
[2020-12-05 12:14:27.154] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-12-05 12:14:27.184] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-12-05 12:14:27.297] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-12-05 12:14:27.299] [userDataSync] [info] Sync done. Took 158ms
[2020-12-05 12:14:42.636] [userDataSync] [info] Auto Sync: Triggered by Activity
[2020-12-05 12:14:42.855] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-12-05 12:14:42.857] [userDataSync] [info] Keybindings: Skipped synchronizing keybindings as it is disabled.
[2020-12-05 12:14:42.860] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-12-05 12:14:42.872] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-12-05 12:14:42.957] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-12-05 12:14:42.958] [userDataSync] [info] Sync done. Took 111ms
[2020-12-05 12:14:56.157] [userDataSync] [info] Auto Sync: Disabled.
[2020-12-05 12:14:56.157] [userDataSync] [info] Auto Sync: Stopped
[2020-12-05 12:14:56.169] [userDataSync] [info] Did reset the local sync state.
[2020-12-05 12:15:04.159] [userDataSync] [info] Did reset the local sync state.
[2020-12-05 12:15:04.405] [userDataSync] [info] Keybindings: Skipped synchronizing keybindings as it is disabled.
[2020-12-05 12:15:05.555] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-12-05 12:15:05.569] [userDataSync] [info] Settings: Updated last synchronized settings
[2020-12-05 12:15:05.570] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-12-05 12:15:05.580] [userDataSync] [info] Snippets: Updated last synchronized snippets
[2020-12-05 12:15:05.582] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-12-05 12:15:05.588] [userDataSync] [info] GlobalState: Updated last synchronized ui state
[2020-12-05 12:15:05.591] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-12-05 12:15:05.597] [userDataSync] [info] Extensions: Updated last synchronized extensions
[2020-12-05 12:15:05.607] [userDataSync] [info] Auto Sync: Started
[2020-12-05 12:15:05.607] [userDataSync] [info] Auto Sync: Triggered by Interval
[2020-12-05 12:15:05.864] [userDataSync] [info] Settings: No changes found during synchronizing settings.
[2020-12-05 12:15:05.867] [userDataSync] [info] Keybindings: Skipped synchronizing keybindings as it is disabled.
[2020-12-05 12:15:05.886] [userDataSync] [info] Snippets: No changes found during synchronizing snippets.
[2020-12-05 12:15:05.914] [userDataSync] [info] GlobalState: No changes found during synchronizing ui state.
[2020-12-05 12:15:06.025] [userDataSync] [info] Extensions: No changes found during synchronizing extensions.
[2020-12-05 12:15:06.027] [userDataSync] [info] Sync done. Took 186ms

**Comment by Krrishdhaneja** [comment]
@sandy081 ?

**Comment by alevinetx** [comment]
I see this is closed, and was claimed to have been resolved in a recent Insiders.  I'm still running 1.51.1, and I see that my extensions weren't actually stored, and my keyboard shortcuts haven't been updated locally to match what was originally stored.  In fact, the most recent sync shows it went the other way (local -> remote).  

I thought there would be some way to indicate which way to manage a sync (restore to local, overwrite remote, etc), but I don't see that if it's available.  

I also don't see any way to (easily) update from an older sync.  It opens up a diff viewer, but the local version is read-only and there's no merge management, only a "view prev/next diff" navigation.

As there's no easy way to pull settings from "machine 2" to "current machine", it would also be useful if it was possible to change the machine id value without having to edit the state.vscdb meta-data and fields, vs wiping everything in the locally stored configuration ("make this machine now known as this older machine").

Unfortunately, I don't have the original install available -- this was a new install over a wiped system.   It took a lot of work to figure out where to find the right older machine id and set it properly.   It would be useful to be able to see the machine id associated with synced machines.

**Comment by sandy081** [comment]
> [2020-12-05 12:14:24.201] [userDataSync] [info] Extensions: Updated remote extensions
[2020-12-05 12:14:24.207] [userDataSync] [info] Extensions: Updated last synchronized extensions

@Krrishdhaneja From the logs, it seems the reported issue is fixed because extensions are getting synchronised now.
If you are facing different or new issues, I would recommend to file a separate issue with required info and steps to reproduce.

@alevinetx Since this issue is fixed and closed, please file a separate issue for your requirements so that they can be discussed and a proper action is taken.

**Comment by Krrishdhaneja** [comment]
No, it is not fixed yet @sandy081 because I didn't get my extensions, I was having many like Babel, C#, C/C++, Pylance, Python etc.
And what I got is not even 1 extension of these.

**Comment by sandy081** [comment]
May I know where were you (which instance of VS Code is it VS Code stable or insiders) having these extensions (Babel, C#, C/C++, Pylance, Python)?

**Comment by Krrishdhaneja** [comment]
It is insiders.

**Comment by Krrishdhaneja** [comment]
@sandy081 ?

**Comment by Krrishdhaneja** [comment]
I reinstalled insiders version again in order to check sync and it didn’t worked.

**Comment by sandy081** [comment]
Please correct me if I am wrong - You are syncing your Insiders and you are not getting your extensions ? If so may I know and confirm if you synced those extensions at all? You can do following to check that

- Open Synced Data View using command (Settings Sync: Show Synced Data)
- It opens **Synced Data (Remote)** view in the side bar
- In that view, click on first Extensions entry and click on `extensions.json` entry. It opens a diff editor. 
- On the left hand side of the diff editor, please see if the extensions you wanted are listed or not?

**Comment by alevinetx** [comment]
I would have originally created a new ticket, but it sounded like this wasn't actually resolved.    I'm waiting to see if it is indeed, and then I'll open a new issue with what's remaining.
