### ISSUE TITLE
vscode-css-languageservice/test/pathCompletionFixtures/src/data/foo.asar fails the compilation

### ISSUE THREAD

**Issue by PF4Public** [microsoft/vscode#108016]
- VSCode Version: latest
- OS Version: linux

Steps to Reproduce:

1. `cd extensions/css-language-features/server/ && yarn install`

Result:
```
$ cd server && yarn install
yarn install v1.22.4
warning ../../package.json: No license field
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error https://registry.yarnpkg.com/vscode-css-languageservice/-/vscode-css-languageservice-4.3.4.tgz: Extracti
ng tar content of undefined failed, the file appears to be corrupt: "Invalid package /var/tmp/portage/app-edit
ors/vscode-9999/homedir/.cache/yarn/v6/npm-vscode-css-languageservice-4.3.4-8d8711b31f2b561f78c32e8c85a8584b0b
6dc43b-integrity/node_modules/vscode-css-languageservice/test/pathCompletionFixtures/src/data/foo.asar"

```

`--skip-integrity-check` does not help.

I think, there was no such error with versions 1.49.2 (and probably 1.49.3) and older.

Does this issue occur when all extensions are disabled?: N/A

**Comment by aeschli** [comment]
You were right, https://github.com/microsoft/vscode-css-languageservice/commit/a5de5fa48be47a3b0c2cd10f449d843c5f98373f was the cause.
Published vscode-css-languageservice@4.3.5

**Comment by PF4Public** [comment]
Thanks @aeschli 
But without bumping it in this repo, it will still pull in 4.3.4 and fail.

**Comment by aeschli** [comment]
done: 362da0a14da717f565383fb7eb27b38d8658f251

**Comment by PF4Public** [comment]
Thanks @aeschli 
Haven't you forgot ;) https://github.com/microsoft/vscode/blob/795b0dba8d85e0f95f9ffd08a25208af940bfedc/extensions/html-language-features/server/package.json#L12

**Comment by aeschli** [comment]
Thanks, will update.

**Comment by PF4Public** [comment]
Thanks @aeschli it compiles fine now.

I have inspected [a build log](https://github.com/microsoft/vscode/runs/1248370976) after 362da0a, which should fail, but that action on GitHub in this repository finished successfully:
```
Installing dependencies in extensions/html-language-features...
$ yarn --frozen-lockfile
yarn install v1.22.5
warning ../package.json: No license field
[1/5] Validating package.json...
warning html-language-features@1.0.0: The engine "vscode" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
warning vscode-extension-telemetry@0.1.1: The engine "vscode" appears to be invalid.
warning vscode-languageclient@7.0.0-next.5.1: The engine "vscode" appears to be invalid.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ cd server && yarn install
yarn install v1.22.5
warning ../../package.json: No license field
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
```

I assume, that because of that, this issue was not caught immediately by GitHub actions.

How could this be so that on my system it fails due to `.npmignore`, but on GitHub actions this never happens?

**Comment by aeschli** [comment]
To verify check that the published vscode-css-languageservice module (https://unpkg.com/browse/vscode-css-languageservice/) does not contain the `test` folder

**Comment by PF4Public** [comment]
> does not contain the `test` folder

True, but https://unpkg.com/browse/vscode-css-languageservice@4.3.4/ has it.
