### ISSUE TITLE
Unbound breakpoint for Node.js app running in a Docker container

### ISSUE THREAD

**Issue by ShocKwav3** [microsoft/vscode#108418]
I have been having very very hard time to setup VSCode debugger for a project in a docker container(locally) ran using babel-node. The debugger attaches fine but whenever I set a breakpoint, it goes grey holo circle and says "Unbound breakpoint". One thing to mention is, if I start the server with `--inspect-brk` then, the server does wait on first line and when I connect the debugger, I can step through!

I understand that this might be a source mapping issue but I have setup the necessary configs for that and the issue still persists. I have setup a minimal project in a repository(links below) for this.

I have looked through the web trying different configs, reading VSCode documentations and explored issues on this repository but nothing came any close to fix this. I have also tried the old debugger and I still get same issue. I would highly appreciate if someone could take a kind look on this.

### Here are the relevant configurations:
**Dockerfile:**
```FROM node:12
WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn install
COPY . .
```
**Docker compose**
```
version: '3'
services:
  server:
    image: babel-node-test-image
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - servernet
    command: ["yarn", "start"]
    tty: true
networks:
  servernet:
```

**.babelrc:**

```
{
    "presets": [
        "@babel/preset-env"
    ],
    "sourceMaps": "inline",
    "retainLines": true
}

```

**launch.json:**

```
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Debug docker app",
            "port": 9229,
            "restart": true,
            "trace": true,
            "address": "localhost",
            "localRoot": "${workspaceFolder}/src",
            "remoteRoot": "/usr/src/app/src",
            "protocol": "inspector",
            "sourceMaps": true,
            "smartStep": true
          }
    ]
}
```

**Command to start the server:** `nodemon --exec babel-node --inspect=0.0.0.0 src/app.js`

- VSCode Version: Latest
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Add the above configurations
2. Attach and try to set breakpoint

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Please grab some logs

/jsDebugLogs

**Comment by ShocKwav3** [comment]
@connor4312 Thank you for the response. I have sent the log files to you through the email address you provided.

**Comment by connor4312** [comment]
Thanks for the logs @ShocKwav3.

Can you try adding `resolveSourceMapLocations: null` in your launch.json and let me know if that changes anything?

**Comment by ShocKwav3** [comment]
Hi,

I have added resolveSourceMapLocations: null, but still the same issue
persists. Point to note that, resolveSourceMapLocations was underlined and
the editor said it's not allowed.
I see the following in the debug console:

Verbose logs are written to:
/tmp/vscode-debugadapter-0.json.gz
Could not read source map for
file:///usr/src/app/node_modules/@babel/parser/lib/index.js: ENOENT: no
such file or directory, open
'/usr/src/app/node_modules/@babel/parser/lib/index.js.map'
app is listening to port 3000

I have attached the log file with the email for your convenience.

Best regards,
Feroj/ShocKwav3

**Comment by ShocKwav3** [comment]
@connor4312 any update on this?

**Comment by connor4312** [comment]
Thanks for the logs, I believe this should be fixed in the linked commit. Please give the next [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) a spin and let me know if it works for you.

**Comment by ShocKwav3** [comment]
Hi,

The nightly build worked, mostly! Thank you for the fix.
A minor issue still persists. The debugger is able to set breakpoints in
most of the places, except some lines. For example, same file but different
lines, and it seems mostly the code where my application is going
through configurations, before initiating the server. The line where I
initiate the server does work, but for me this is not a big issue but you
might want to take a look.

Another, bigger, issue, even after setting "skipFiles" the debugger still
goes to node modules code. My config is following:
"skipFiles": [
"${workspaceFolder}/node_modules/**/*.js",
"/usr/src/app/home_automation_server/node_modules/**/*.js",
"<node_internals>/**/*.js"
],
I have attached the logs from two different projects.
vscode-debugadapter-7.json.gz contains both issues
while vscode-debugadapter-0.json.gz contains the first one regarding
breakpoints.

**Comment by connor4312** [comment]
The line issue _could_ be something that babel is doing. Without seeing the code and the sourcemap (which you can send over if you're able) it's hard to tell what could be happening.

Email attachments to Github issue replies don't appear, please share the logs on github.com if you're able. Thanks!
