### ISSUE TITLE
[1031/181118.450:ERROR:registration_protocol_win.cc(103)] CreateFile: 系统找不到指定的文件。 (0x2)

### ISSUE THREAD

**Issue by Waysma** [microsoft/vscode#109782]
Issue Type: <b>Bug</b>

same bug as in gitignore bug (debug.log) #105161
https://github.com/microsoft/vscode/issues/105161

happens again in 1.50.1

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (27.66GB free)|
|Process Argv|--crash-reporter-id 6b4c2c37-414b-497e-a4ea-9b3ebff62a26|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
language-gas-x86|bas|0.0.2
cpptools|ms-|1.0.1

</details>

**Comment by weinand** [comment]
#105161 has been fixed in VS Code 1.49.

Please provide details of the issue you are seeing.

**Comment by Waysma** [comment]
it happens when I operate as follows(no exceptions):

1. click VScode via in start menu for the first time;//nothing wrong
           then use the command "code -a .\" to add some folder to the workspace
![OK](https://user-images.githubusercontent.com/26728343/97802099-278ce680-1c7c-11eb-9918-da3c66f3940a.PNG)


2. click VScode via in start menu again to open another instance;
           then use the command "code -a .\" to add a folder, it did add some thing, and gave the error message too
![NG](https://user-images.githubusercontent.com/26728343/97802125-44c1b500-1c7c-11eb-893f-f810215e8142.PNG)

I updated from 1.42.1, which nothing wrong happens with the same operations

**Comment by Waysma** [comment]
> #105161 has been fixed in VS Code 1.49.
> 
> Please provide details of the issue you are seeing.

it happens when I operate as follows(no exceptions):

1. click VScode via start menu for the first time;//nothing wrong
           then use the command "code -a .\" to add some folder to the workspace
![OK](https://user-images.githubusercontent.com/26728343/97802099-278ce680-1c7c-11eb-9918-da3c66f3940a.PNG)


2. click VScode via start menu again to open another instance;
           then use the command "code -a .\" to add a folder, it did add some thing, and gave the error message too
![NG](https://user-images.githubusercontent.com/26728343/97802125-44c1b500-1c7c-11eb-893f-f810215e8142.PNG)

I updated from 1.42.1, which nothing wrong happens with the same operations

**Comment by deepak1556** [comment]
The error message is from crash reporter initialization which you can ignore, is there any impact on vscode behavior due to this message, if not we can close this issue.

**Comment by Waysma** [comment]
hopefully be fixed in next release，anyway.

**Comment by CxRes** [comment]
I can report this is still occurring with 1.51.0 when using system setup and starting vscode with non-admin privileges. Please reopen!

**Comment by jordankkk** [comment]
debug.log still randomly create with vscode latest version (user installer) 

`[1111/084216.172:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)`

**Comment by XsongyangX** [comment]
I have a similar problem.
```
Song@LAPTOP-USBSGSDO MINGW64 ~/Documents/UDEM/ift6113/project/skinning_cor/Skinning with COR (master)      
$ code test.txt
[1128/195022.430:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
```

**Comment by lengthmin** [comment]
latest insiders version, also have this problem

A file named "debug.log" was generated in `$(pwd)`

**Comment by ruifortes** [comment]
I'm pretty sure this fix would take forever this if it wasn't Microsoft.... and the time was proportional to the available resources :-\

**Comment by Rob4226** [comment]
I have had this same issue for a while also. Inside every single directory of every single project a `debug.log` file gets created containing:
```sh
[1202/222752.856:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[1202/222753.192:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[1202/235330.481:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
[1202/235334.513:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)
```
This same thing happened a few months back in a release but it was fixed...But now in the last release or two it is back and really annoying. Is there anyway to stop it? Thank you.

**Comment by deepak1556** [comment]
I unable to repro the situation where debug.log file is generated, have tried 

* Latest stable both system and user install
* Latest insiders both system and user install

I was able to repro the log https://github.com/microsoft/vscode/issues/109782#issuecomment-720083009 but that is harmless as I mentioned before.

Closing, can reopen if there is a repro for `debug.log` issue

**Comment by CxRes** [comment]
Just because you cannot reproduce this does not mean the bug has gone away! It just disregards what multiple users are reporting.

The problem in the first place is that message is so cryptic that no one except the one who wrote the code can know what it means. So how do you expect that ordinary users can provide a reproduction?

**Comment by deepak1556** [comment]
When we fixed https://github.com/microsoft/vscode/issues/105191, we had removed the capability for our production builds to log to disk by default. After a while there was issue about `debug.log` files generated https://github.com/microsoft/vscode/issues/108886, this turned out to be an issue with chrome https://bugs.chromium.org/p/chromium/issues/detail?id=1138853 . Although vscode fixed the first issue, the second issue has a way to leak into all electron apps based on chromium. We landed a fix in electron https://github.com/electron/electron/pull/26250 to prevent this, but apps that have not picked up the fix would still be affected. So I am sure vscode is not the one generating the logs atleast on latest releases. 

If it does, I would like a repro to investigate further for any meaningful solution. I am not closing the issue as no-fix, I just can't work on it without a repro. Thanks for your understanding.
