### ISSUE TITLE
Safari: terminal focus context key not updated after hide

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#109765]
Issue Type: <b>Bug</b>

* Open web in Safari on macOS
* Open text editor, `cmd+a` works 
* Open terminal, `cmd+a` select all text in the terminal
* `cmd+j` to hide the terminal
* In the text editor, move cursor, and then press `cmd+a`, nothing happens

Toggle keyboard shortcuts troubleshooting, `cmd+a` runs terminal actions, I think `terminalFocus` is still true in this case.

VS Code version: Code - Insiders 1.51.0-insider (2d8bbc6976748c4b0c5e84be541674b89b9d91e4, 2020-10-30T05:55:22.238Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.16GB free)|
|Process Argv|-psn_0_2118149 --enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.2
tsl-problem-matcher|eam|0.3.1
vscode-pull-request-github-insiders|Git|2020.10.42661
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.1.17
vscode-docker|ms-|1.7.0
vscode-language-pack-zh-hans|MS-|1.51.1
dotnet-interactive-vscode|ms-|1.0.152203
vscode-dotnet-runtime|ms-|0.1.2
python|ms-|2020.10.332292344
remote-containers|ms-|0.148.0
remote-ssh-edit-nightly|ms-|2020.10.29700
remote-ssh-nightly|ms-|2020.10.29700
hexeditor|ms-|1.3.0
js-debug-nightly|ms-|2020.10.2917
powershell-preview|ms-|2020.9.0
vscode-github-issue-notebooks|ms-|0.0.57
vscode-markdown-notebook|ms-|0.0.13
vscode-notebook-history|ms-|0.0.1
vsliveshare|ms-|1.1.0-dev
vsonline|ms-|1.0.3073
debugger-for-chrome|msj|4.12.11
toggle|reb|0.0.1
java|red|0.69.0
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
rust|rus|0.7.8
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.6.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.25.0
vscode-maven|vsc|0.25.0
notebook-editing|vsc|1.0.0

(5 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
@Tyriar we fixed similar issues for settings editor before (for both safari and firefox) by https://github.com/microsoft/vscode/commit/06cbe30f69581788032b6ed14e518c0e32952518 , you may want to do similar fixes.

**Comment by rebornix** [comment]
@Tyriar I tested below hack can fix this issue, though it's a misuse of `notifyFindWidgetFocusChanged`. We can probably add a new method `refreshFocusState` to update the focus state based on active DOM element.
 

```diff
			this._register(this.onDidChangeBodyVisibility(visible => {
			if (visible) {
				const hadTerminals = !!this._terminalService.terminalTabs.length;
				if (this._terminalsInitialized) {
					if (!hadTerminals) {
						this._terminalService.createTerminal();
					}
				} else {
					this._terminalsInitialized = true;
					this._terminalService.initializeTerminals();
				}

				this._updateTheme();
				if (hadTerminals) {
					this._terminalService.getActiveTab()?.setVisible(visible);
				} else {
					// TODO@Tyriar - this call seems unnecessary
					this.layoutBody(this._bodyDimensions.height, this._bodyDimensions.width);
				}
			} else {
				this._terminalService.getActiveTab()?.setVisible(false);
+				this._terminalService.terminalInstances.forEach(instance => {
+					instance.notifyFindWidgetFocusChanged(false);
+				});
			}
		}));
```

I'd love to see the fix coming as it's blocking me now dogfooding web on Safari.

**Comment by RMacfarlane** [comment]
Hmm, I'm still seeing the original issue with the steps above
