### ISSUE TITLE
Open New External Terminal in remote - containers

### ISSUE THREAD

**Issue by oliverpool** [microsoft/vscode#110050]
- VSCode Version: 1.45.1
- Local OS Version: Arch Linux
- Remote OS Version: N/A
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open a dev container (docker)
2. Launch `Open New External Terminal` command

Expected behavior:
3. my external terminal opens (or at least some error message)

Actual behavior:
3. nothing happens (I can see `CommandService#executeCommand workbench.action.terminal.openNativeConsole` when running in `--verbose` mode)

Does this issue occur when you try this locally?: No, everything works fine when the container is disabled

**Comment by jaywhy13** [comment]
I'm also having this issue. I'd love to access an external terminal because there are several tools outside my container I typically want access to. This forces me to use an extra terminal outside of VS Code. I try "Open New External Terminal" and nothing happens. I don't see any logs.

**Comment by vitexikora** [comment]
Just started happening to me with VSC 1.57.0

**Comment by wryrye** [comment]
> Just started happening to me with VSC 1.57.0

Same

**Comment by Tyriar** [comment]
The issue in 1.57.0 is fixed in the upcoming 1.57.1 here: https://github.com/microsoft/vscode/issues/125985

**Comment by the-vampiire** [comment]
@Tyriar i am still unable to have this working. I have a devcontainer workspace running. However, when I select "open external terminal" it only opens the local dir.

Is there a way to open a connection to the devcontainer workspace? i [posted on SO](https://stackoverflow.com/questions/70371450/how-to-attach-an-external-terminal-to-devcontainer) with a screenshot and example usage. 

any advice would be appreciated.

**Comment by Tyriar** [comment]
This correctly opens a local terminal now. There's no plan to allow it to connect to the remote, this would need to be a feature in the ssh/containers extensions.

**Comment by the-vampiire** [comment]
@Tyriar thank you for the info. Do you happen to know what VSCode sets in terms of env vars and other settings for the integrated terminal session? Or where I can find those details?

If i know what its doing I can write a script to replicate it when I open from iterm. Thanks in advance

**Comment by Tyriar** [comment]
I know for local but I'm guessing you care more about the remote variables. You could run `env` and diff your environments to see what the difference is. You could also write an extension that does what you're after, I write a Windows Terminal Integration extension which supports opening the terminal for the various remote connections which is here for reference: https://github.com/Tyriar/vscode-windows-terminal

**Comment by the-vampiire** [comment]
cheers man thank you

**Comment by the-vampiire** [comment]
hey man its been a while but finally got some time to sort this out. think i came up with a relatively simple solution in case someone else has the same need

> 1. add a `postStartCommand` to `.devcontainer/devcontainer.json`

this will capture the env (as configured by vscode/devcontainer ext) and store it in an env file. every time the  dev container starts it has a slightly different env so we use this lifecycle hook to always have the current values.

```json
"postStartCommand": "printenv > .devcontainer/container.env"
```

- **note you will need to rebuild the container for this to take effect**
- afterwards every "open/reopen in container" usage will cause this hook to trigger and refresh the env file

> 2. run the following command **in the project dir you want to connect to** from your external terminal

this will exec into the container using the devcontainer env file ensuring the external terminal session has the same env as using the integrated terminal

```sh
docker exec -it --env-file="$(pwd)/.devcontainer/container.env" \
  $(docker ps --filter "name=$(basename $(pwd))_devcontainer_app" --format "{{.ID}}") \
  zsh
```

- this assumes your workspace container has the service name `app` (in the `.devcontainer/docker-compose.yml` file) if not then adjust the suffix `_devcontainer_app` as needed to match
- set whatever shell you prefer at the end there if you dont use zsh

hope this helps someone else. cheers

**Comment by the-vampiire** [comment]
to make this a bit more ergonomic set the following alias in your local shell profile (making adjustments as described above):

```sh
alias devcontainer='docker exec -it -w /workspace --env-file="$(pwd)/.devcontainer/container.env" $(docker ps --filter "name=$(basename $(pwd))_devcontainer_app" --format "{{.ID}}") zsh'
```

> usage from external terminal

1. in vscode open the project in the devcontainer
2. open your external terminal

```sh
cd <project dir>
devcontainer
```
