### ISSUE TITLE
The Delete Permanently option is gone for Shift Right Clicking

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#110775]
- VSCode Version: _**1.51.1 zip 64 bit**_
- OS Version: **_Windows 10 Enterprise_**

Steps to Reproduce:

1.  In previous versions, e.g., `1.50.1` From the Explorer, **press** & **hold** <kbd>SHIFT</kbd>, then **right click** on a file or a folder. It shows up a pop up as below. You can see there is a `Delete Permanently` option.
![image](https://user-images.githubusercontent.com/19678455/99342960-dc1c3e80-28f1-11eb-97e3-bf63f4d1539f.png)

2. But in `1.51.1`, do the same, Now you don't see the `Delete Permanently` option, just the normal `Delete`, i.e., the same effect as without **press** & **hold** <kbd>SHIFT</kbd>. 👀
![image](https://user-images.githubusercontent.com/19678455/99343403-a9bf1100-28f2-11eb-92be-5995974efafe.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
You can still hold the <kbd>Alt</kbd> key to show the Delete Permanently menu item.

Not sure if it's an intended change, relates to #109062, changed in ff805b3, this line was gone:

https://github.com/microsoft/vscode/blob/ff21e848ed7f54fe1bf5da69f888c5a434d7a0cc/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L34

**Comment by cateyes99** [comment]
Right. but there is still a problem with <kbd>Alt</kbd> though. As long as u release <kbd>Alt</kbd>, the Popup disappears, that isn't very convenient. Previously, with <kbd>Shift</kbd>, after release the key, the Popup remains there. By the way <kbd>Shift</kbd> makes more sense than <kbd>Alt</kbd>, since it only offers the difference of the `Delete Permanently` option from the normal `Delete` option. So <kbd>Shift</kbd> is consistent with this: when u click <kbd>Delete</kbd> while **pressing** & **holding** <kbd>Shift</kbd>, then it offers u `Delete Permanently`.

**Comment by yume-chan** [comment]
> As long as u release Alt, the Popup disappears

It seems that because I have `window.customMenuBarAltFocus: false` so this doesn't happen to me. I suggest you file a separate issue on this.

**Comment by isidorn** [comment]
Thanks for reporting this. I have pushed a fix for this and you can check it out with vscode insdiers from tomorrow.

**Comment by rzhao271** [comment]
@isidorn I don't see the change, still.
I tried with both `window.customMenuBarAltFocus` enabled and disabled, and holding down shift while right-clicking still shows only "Delete"

Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
@rzhao271 good catch, thanks, let's reopen this
