### ISSUE TITLE
Automatically set the filename when downloading by the remote ssh extension

### ISSUE THREAD

**Issue by miladmozafari** [microsoft/vscode#111108]
These days, I am using the remote ssh extension a lot because of teleworking. However, when I want to download a file (right-click on a file, then click on download) the filename field is empty and I have to put the name manually.

I was not sure if this is a bug or a missing feature but I decided to post it as a feature request. I hope it will be fixed soon.

**Comment by isidorn** [comment]
This should be fixed in the latest insiders
Fixed by @alexr00 
Dup of https://github.com/microsoft/vscode-remote-release/issues/2536

**Comment by whyisyoung** [comment]
I still have this issue and I'm using 1.15.1 (the latest version) on Mac OS 10.15.7.

**Comment by isidorn** [comment]
Yeah you need to use insiders, or wait for newer stable in 2 weeks

**Comment by whyisyoung** [comment]
> Yeah you need to use insiders, or wait for newer stable in 2 weeks

I see. Thanks for the heads up!
