### ISSUE TITLE
Double tooltip

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111756]
* safari (maybe only safari)
* open repo in codespaces
* hover of an issue in the GH view
* :bug: there are double tooltips

<img width="628" alt="Screenshot 2020-12-02 at 14 05 44" src="https://user-images.githubusercontent.com/1794099/100902537-4245bb80-34c5-11eb-82fc-68c46fb65e05.png">

**Comment by alexr00** [comment]
Does not occur in Edge, Firefox, or Chrome.

**Comment by alexr00** [comment]
@jrieken I pushed a potential fix for this two weeks ago. Since it's already in insiders can you see if it still repros in Safari?

**Comment by jrieken** [comment]
Still seeing it on a codespace with `4a875e23d20b64504a818834f3fa4c40adb8d480`

<img width="522" alt="Screenshot 2020-12-24 at 13 25 47" src="https://user-images.githubusercontent.com/1794099/103088582-8a02c300-45eb-11eb-8b94-e35412e2c863.png">

**Comment by alexr00** [comment]
Thanks for testing. I currently set `title` to `''` and also call `removeAttribute('title')`. I don't want to keep fumbling blindly for a solution. Let's debug in January.

**Comment by bpasero** [comment]
I think https://stackoverflow.com/questions/20974276/prevent-safari-from-showing-tooltip-when-text-overflow-is-hidden-with-ellipsis applies here.

**Comment by alexr00** [comment]
Will try out that CSS rule for April.

**Comment by alexr00** [comment]
@jrieken I have added the potential CSS fix from Ben's link. Could you try this out in insiders again when you have a chance?

**Comment by alexr00** [comment]
There's a problem with this fix. Trying again...

**Comment by alexr00** [comment]
@jrieken could you try to verify this again? Sorry about all the requests to keep checking this.

**Comment by jrieken** [comment]
👍 looks good on a codespace using insiders: 0310f02dc5d834bb3a7cc421ea5374aec8d011f1

**Comment by alexr00** [comment]
🎉great news, thanks!

@sandy081 FYI since I know you have been looking at using the custom hover in other places. It might be good to test it on Safari.
