### ISSUE TITLE
after staging changes, the whole tree expands

### ISSUE THREAD

**Issue by KanomiDim** [microsoft/vscode#112487]
Issue Type: <b>Bug</b>

Started after the last vscode update - after staging changes, the whole tree expand in the "Source Control" tab.

Moreover, if moving to the "Explorer" tab and then going back to "Source Control", the tree expands again.

So annoying :(

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2276M  CPU @ 2.80GHz (12 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (55.26GB free)|
|Process Argv|--crash-reporter-id 640fcf78-529a-4c79-9a36-08fa575e88d1|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
gitlens|eam|11.0.6
todo-tree|Gru|0.0.192
nsis|idl|3.36.0
nsl-assembler|idl|1.2.0
compare-folders|mos|0.19.0
cpptools|ms-|1.1.3
vscode-xml|red|0.14.0

</details>

**Comment by john-larson** [comment]
It happens after every commit.

**Comment by eamodio** [comment]
@KanomiDim @john-larson You are still seeing this on 1.52.1? I was seeing this myself over the holiday break, but I can no longer reproduce it.

**Comment by john-larson** [comment]
@eamodio Yes, I still see it on 1.52.1.

**Comment by eamodio** [comment]
Ah, thanks -- I misread this and thought it was the opposite issue I was seeing over break. I see the behavior you are describing now. The scm view isn't always honoring your expand/collapsed state.

**Comment by eamodio** [comment]
@KanomiDim I've fixed the issue where it auto-collapses on stage/unstage.

As for:
> Moreover, if moving to the "Explorer" tab and then going back to "Source Control", the tree expands again.

That is caused by the `scm.autoReveal` setting which reveals the active editor in the SCM view. If you turn that off, you should see that behavior stop.

**Comment by sirpy** [comment]
@eamodio this shouldnt be closed
i've switched off ALL auto reveal settings, but it still happens

**Comment by eamodio** [comment]
I'm not sure my change made it in to today's insiders build, so in order to test it you'll need to wait until tomorrow. And the fix and the autoReveal change should fully resolve it.

**Comment by pdrgnclvs** [comment]
@eamodio, on the latest insiders build (I'm Portuguese so at least in my timezone)...

![image](https://user-images.githubusercontent.com/46295920/104565166-c8682c80-5643-11eb-833d-46cbd9572cea.png)

And yep, there it is 💪

![code-fixed](https://user-images.githubusercontent.com/46295920/104565372-1b41e400-5644-11eb-8963-c699ab1fa08f.gif)

It was getting pretty dangerous to commit anything, even a single line sometimes 😅

BTW, I'm really sorry if my response re-opened the issue or something, I promised to keep you updated on the duplicate issue and I'm just confirming that it is fixed 😉

**Comment by eamodio** [comment]
Awesome - thank you!

**Comment by KanomiDim** [comment]
still happening to me in the latest version of vs code (1.52.1)

@pdrgnclvs what you showed here isn't relevant because you are not in the right "View Mode"

![image](https://user-images.githubusercontent.com/68009729/105341046-51083f00-5be7-11eb-84c7-bb6c8d78a12c.png)

**Comment by KanomiDim** [comment]
Just to demonstrate the bug - in the source control when you are in the Tree View Mode, try to stage something like that:

![image](https://user-images.githubusercontent.com/68009729/105341635-020ed980-5be8-11eb-9ab6-a440cf6fa413.png)


and then the whole tree under "Changes" & "Staged Changes" is gonna expand again:

![image](https://user-images.githubusercontent.com/68009729/105341972-6893f780-5be8-11eb-9fa0-dd18b18319ef.png)

**Comment by pdrgnclvs** [comment]
@KanomiDim, what I showed here _is_ relevant because in my case it didn't EXPAND but instead COLLAPSE all of them, meaning that the problem could be tied to the way it managed the "expand/collapse" state in both view modes 😉

However, the problem both you and I have in stable appears to be fixed as of the latest insiders edition, which means that it will soon be in the next stable 💪
