### ISSUE TITLE
vscode.workspace.openTunnel stuck for codespaces

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#112774]
- VSCode Version: master, but not sure when did this start.
- OS Version: Windows 10.0.19042 Build 19042

Steps to Reproduce:

1. When connected to a codespace, in a UI extension, do 'await vscode.workspace.openTunnel()'.
2. openTunnel never returns.

Does this issue occur when all extensions are disabled?: N/A

**Comment by alexr00** [comment]
Which extension is `openTunnel` being called from?

**Comment by xisui-MSFT** [comment]
> Which extension is `openTunnel` being called from?

Not sure what you meant? Since I wrote in the description `in a UI extension, do 'await vscode.workspace.openTunnel()'`...

**Comment by alexr00** [comment]
Which UI extension?

**Comment by xisui-MSFT** [comment]
> Which UI extension?

ms-vscode.azure-sphere-tools-ui

**Comment by alexr00** [comment]
Thanks! If you open the dev tools (command palette -> Developer: Toggle Developer tools) are there any errors in console there?

**Comment by xisui-MSFT** [comment]
Yes there is an error:

ERR Cannot read property 'remoteAddress' of undefined: TypeError: Cannot read property 'remoteAddress' of undefined
    at file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5336:662
    at async forward (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5331:222)
    at async file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:8128:124
    at async Promise.all (index 0)
    at async A.forwardCandidates (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:8127:688)
    at async A.handleCandidateUpdate (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:8128:466)

FYI the actual function call is in our code is `await vscode.workspace.openTunnel({ remoteAddress: { port: workspacePort, host: 'localhost' } });`

**Comment by alexr00** [comment]
This sounds like something I fixed recently (4804bbcdff70b2905053bea0c8aaa19b50e0e631). Can you grab the latest Insiders build and try with that?

**Comment by xisui-MSFT** [comment]
I tried latest insiders (1.53.0-insider, a48ef56f), openTunnel still doesn't return, and there is no error message anymore in console.

**Comment by xisui-MSFT** [comment]
@alexr00 Hi, is there any update on this?

**Comment by alexr00** [comment]
Finally an update for you: It seems that this issue only happens in certain circumstances, but when it does, it happens 100% of the time. It is an issue with Codespaces, so I have created an issue with them. However, that issue repo isn't public, so I can't link the issue here. I'm sorry I can't provided clearer next steps, but we'll just have to wait for the fix from Codespaces.
