### ISSUE TITLE
Microsoft sign in lost on every restart

### ISSUE THREAD

**Issue by clementhervy** [microsoft/vscode#115416]
- VSCode Version: 1.52.1
- OS Version: Windows 10 19042.746

Steps to Reproduce:

1. Turn on settings sync, sign in with Microsoft account and wait for settings to synchronize
2. Exit VS Code
3. Start VS Code
4. Accounts menu says "You are not signed in to any accounts". 

Signing-in in itself seems fine, it's just that I have to do it again every time I start VS Code.

This might have started some time in the last couple of weeks when Microsoft sign-in had problems, but I am not sure.

Does this issue occur when all extensions are disabled?: Yes

**Comment by clementhervy** [comment]
Problem persists on 1.53.0.

**Comment by clementhervy** [comment]
Problem persists on 1.53.1.

**Comment by patrickquijano** [comment]
I also have this problem. I am using Ubuntu 20.04 and every time I restart my VS Code, it will show "**You are not signed in to any accounts**"
![image](https://user-images.githubusercontent.com/6316829/107591437-9f888680-6c45-11eb-9a84-dbd5488d416a.png)

**Comment by clementhervy** [comment]
Problem persists on 1.53.2.

**Comment by Ruzo** [comment]
Same for Windows 10 - version 1.54.0-insider

**Comment by Ruzo** [comment]
When I logged out of my Windows account and chose Github for my settings sync instead, the problem went away.

**Comment by clementhervy** [comment]
It seems fixed as of now, with version 1.55.1. Settings sync keeps its logged-in state.

**Comment by RMacfarlane** [comment]
This corresponds with an update we made to a library for storing secrets, so am going to close this as fixed. Thanks for your patience and updates.

**Comment by sapinder-pal** [comment]
I'm facing this problem on my Linux machine. The issue persists even if I sign in with Github.
```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.0-73-generic
```
