### ISSUE TITLE
Cannot login to github.com

### ISSUE THREAD

**Issue by jsamr** [microsoft/vscode#115918]
Issue Type: <b>Bug</b>

An extension (Gitlens) offers to signin to Github for maximum integration. The authentication process fails with my default browser (firefox) as, I believe, I am using a container for github.com. So I try to login by pressing the "Signing in to github.com..." button in the bottom blue bar. I paste the personal access token generated from github.com in the top input, press enter... and nothing happens. I tried to provide all authorizations to this token, nothing changed.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:56:04.185Z)
OS version: Linux x64 5.9.16-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz (8 x 1692)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.28GB (19.15GB free)|
|Process Argv|/home/jsamr/Programmation/@native-html/core --no-sandbox --crash-reporter-id 6d013abf-4aac-4f80-8ea7-3e1165aae182|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|2.2.2
vsc-prolog|art|0.8.23
asciidoctor-vscode|asc|2.8.7
spellright|ban|3.0.56
troff|ban|1.0.22
god|bas|0.0.99
toml|be5|0.5.1
vscode-raml|blz|3.0.1
vscode-jq-playground|dav|3.2.6
vscode-eslint|dba|2.1.14
i3|dca|0.0.1
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
zsh-completion-script|dua|1.0.0
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.1
vscode-todo-plus|fab|4.18.2
php-debug|fel|1.14.8
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
shell-format|fox|7.0.1
vscode-flow-ide|gca|1.2.0
vscode-pull-request-github|Git|0.23.0
rest-client|hum|0.24.4
vscode-lisp-formatter|imj|1.1.3
latex-workshop|Jam|8.15.0
jq-syntax-highlighting|jq-|0.0.2
restructuredtext|lex|142.0.0
autoconf|mae|0.1.0
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.9.1
remote-containers|ms-|0.158.0
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.32.0
jq-vscode|pet|0.1.1
polacode|pnp|0.3.4
quicktype|qui|12.0.46
vscode-xml|red|0.15.0
preview-vscode|sea|2.2.5
markdown-preview-enhanced|shd|0.5.16
mdx|sil|0.1.0
rewrap|stk|1.13.0
shellcheck|tim|0.13.1
org-mode|too|0.5.0
vscodeintellicode|Vis|1.2.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by RMacfarlane** [comment]
@jsamr Can you open the output panel and choose "GitHub Authentication" from the dropdown and paste the content from there?

**Comment by ralexrdz** [comment]
> @jsamr Can you open the output panel and choose "GitHub Authentication" from the dropdown and paste the content from there?

Same issue: here is my output
```
[Info  - 23:29:25.957] Logging in...
[Info  - 23:30:29.103] Treating input as token
[Info  - 23:31:25.793] Treating input as token
[Info  - 23:38:30.911] Treating input as token
```

**Comment by RMacfarlane** [comment]
@ralexrdz Is what you're pasting the complete output from the auth page?

![Screen Shot 2021-02-22 at 3 45 39 PM](https://user-images.githubusercontent.com/3672607/108784879-2599ac80-7525-11eb-99f9-63d667fbd5dc.png)

I checked in a possible fix, it would be great if you could try the [insiders](https://code.visualstudio.com/insiders/) build of VSCode tomorrow to see if that addresses the issue

**Comment by ralexrdz** [comment]
> @ralexrdz Is what you're pasting the complete output from the auth page?
> 
> ![Screen Shot 2021-02-22 at 3 45 39 PM](https://user-images.githubusercontent.com/3672607/108784879-2599ac80-7525-11eb-99f9-63d667fbd5dc.png)
> 
> I checked in a possible fix, it would be great if you could try the [insiders](https://code.visualstudio.com/insiders/) build of VSCode tomorrow to see if that addresses the issue

Yes it was the complete log from Output > Github Authentication

Here is also the one from Visual Studio LiveShare

```
[Command:Object I] SessionContext: Status update from "SigninCheckStarting" to "SilentNativeLoginStarting".
[github V] Attempting to load session - login = false
[Contact.Manager I] registerContactProvider-> serviceId:git
[Contact.Service V] _Initialize:git
[Contact.Service V] Request 'initialize' serviceId:git
[Contact.Manager I] registerContactProvider-> serviceId:selfInvite
[Contact.Service V] _Initialize:selfInvite
[Contact.Service V] Request 'initialize' serviceId:selfInvite
[github W] Failed to load session
[Client.Rpc.SessionContext V] < sessionContext.getServiceNames()
[Command:Object I] SessionContext: Status update from "SilentNativeLoginStarting" to "SigninCheckCompleted".
[Client I] "Planned sessions are disabled, state: SignedOut
[Command:Object I] SessionContext: State update from "SigningIn" (AttemptSignIn) to "SignedOut" (SignOut).
[Contact.Manager V] ->loadRecentCollaborators:onStateChanged
[Contact.Manager V] SelfInviteProvider-> status:false
[Contact.Service V] onNotified-> serviceId:selfInvite name:suggestedUsers
[Contact.Manager I] onSuggestedUsersUpdate-> serviceId:selfInvite count:0
[Contact.Manager V] ->updateSuggestedUsers
[Command:Object I] Decorator: Authentication Completed Failed (82ms abs=69ms pre=-31ms post=100)
[Contact.Manager V] suggest contacts from provider:selfInvite ids: emails:
[Command:Object I] Decorator: SessionStateTransitions Completed Failed (84ms abs=2ms pre=2ms post=0)
[Command:Object I] Decorator: Validation Completed Failed (86ms abs=2ms pre=0ms post=2)
[Contact.Manager V] ->updateRecentContacts -> count:0
[Contact.Manager I] <- updateSuggestedUsers count:0
[Command:Object I] Decorator: TelemetryStatus Completed Failed (87ms abs=1ms pre=0ms post=1)
[Command:Object E] Command [Signing in]: ExplicitSignIn Non Blocking Failure: Authentication check returned false. (1704ms)
[Command:Object E] Error: Authentication check returned false.
	at AuthenticationCommandDecorator.invoke [PATH]/extension-prod.js:18965:31)
	at processTicksAndRejections [PATH]/task_queues.js:97:5)
	at async MetaProfilingCommandDecorator.invoke [PATH]/extension-prod.js:19254:22)
	at async SessionStateTransitionsCommandDecorator.invoke [PATH]/extension-prod.js:19416:22)
	at async MetaProfilingCommandDecorator.invoke [PATH]/extension-prod.js:19254:22)
	at async ValidationCommandDecorator.invoke [PATH]/extension-prod.js:19778:18)
	at async MetaProfilingCommandDecorator.invoke [PATH]/extension-prod.js:19254:22)
	at async TelemetryStatusCommandDecorator.invoke [PATH]/extension-prod.js:19725:22)
	at async MetaProfilingCommandDecorator.invoke [PATH]/extension-prod.js:19254:22)
	at async TelemetryCommandDecorator.invoke [PATH]/extension-prod.js:19584:22)
	at async MetaProfilingCommandDecorator.invoke [PATH]/extension-prod.js:19254:22)
	at async ErrorNotificationCommandDecorator.invoke [PATH]/extension-prod.js:19165:22)
	at async MetaProfilingCommandDecorator.invoke [PATH]/extension-prod.js:19254:22)
	at async CancellationDecorator.invoke [PATH]/extension-prod.js:19089:18)
	at async MetaProfilingCommandDecorator.invoke [PATH]/extension-prod.js:19254:22)
	at async [PATH]/extension-prod.js:7585:24
	at async b._executeContributedCommand [PATH]/extensionHostProcess.js:86:88509)
[Command:Object I] Decorator: Telemetry Completed Failed (1708ms abs=1621ms pre=5ms post=1616)
[Command:Object I] Decorator: ErrorNotification Completed Success (1708ms abs=0ms pre=0ms post=0)
[Contact.Manager V] <-updateRecentContacts
[Command:Object I] Decorator: CancellationDecorator Completed Success (1708ms abs=0ms pre=0ms post=0)
[Client.Rpc.SessionContext V] > sessionContext.getServiceNames() succeeded t:1638.0
[Contact.Manager I] registerContactProvider-> serviceId:LivesharePresence
[Contact.Service V] _Initialize:LivesharePresence
[Contact.Service V] Request 'initialize' serviceId:LivesharePresence
[Client.Rpc.Contact V] < contactService-LivesharePresence.request()
[Hub.Connection V] < hubConnection.getIsConnected()
[Client.Rpc.Contact V] > contactService-LivesharePresence.request() succeeded t:272.0
```

**Comment by RMacfarlane** [comment]
@ralexrdz or @jsamr Could you try today's [VSCode Insider's](https://code.visualstudio.com/insiders/) to see if this issue still repros? Thanks!

**Comment by ralexrdz** [comment]
Just installed  insiders new `.deb` Still showing same as yesterday 
```
$ code -v
1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64
```

**Comment by RMacfarlane** [comment]
@ralexrdz Hmm, the insider's cmd should be `code-insiders` and should be version 1.54.0.

Confirmed as fixed in https://github.com/microsoft/vscode/issues/117377

**Comment by ralexrdz** [comment]
> @ralexrdz Hmm, the insider's cmd should be `code-insiders` and should be version 1.54.0.
> 
> Confirmed as fixed in #117377

Still not working testing with new code-insiders 
```
1.54.0-insider
9ecd3fc3022e8c154aff868f74bd5d77f7d4a2ea
x64
```
I'm not even getting a browser prompt. The usual workaournd before was accessing this url in the browser, getting a token, clicking the singing to github button at the bottom and pasting the token. But is still not working.
`https://insiders.liveshare.vsengsaas.visualstudio.com/auth/`

Maybe is a different url now?

**Comment by RMacfarlane** [comment]
@ralexrdz Can you share your repro steps? You're using the LiveShare extension to sign in?

**Comment by TylerLeonhardt** [comment]
Hi all 👋

I recently gained ownership of the GitHub auth feature and so I'm getting ramped up!

It's been few versions now... Can you confirm if you're still seeing this issue?

Thanks!
