### ISSUE TITLE
[FEAT] Ehmm, support compose key on linux?

### ISSUE THREAD

**Issue by quenbyako** [microsoft/vscode#116657]
Soooo, this feature is i think REALLY useless (cause, you know, who needs this) but... Well i want to use [compose key](https://en.wikipedia.org/wiki/Compose_key) in vscode :rofl: 

Why? i don't know, this is really cool feature!!! I çán write stúff like these symbols and don't lookup in unicode lists!

I tried out, basic electron input, firefox, chrome, other apps include gtk- and qt-based and even native wayland supports this feature, so i hope that implement this one could be not too hard. What do you think about it?

**Comment by quenbyako** [comment]
Edit: or _maybe_ support compose key on all platforms? :thinking: :thinking: :thinking: :thinking: 

Cause 1) why not 2) xorg is just specific platform one of many 3) most of platforms one way or another has this feature like osx but just has another name

**Comment by IllusionMH** [comment]
Looks like duplicate of #106725 actually.

Do you have this key working in latest versions of Chrome?

**Comment by quenbyako** [comment]
@IllusionMH chrome 88.0.4324.150, compose key works perfectly well

As well as chromium, 88 stable, works too. (even i use firefox lol)

**Comment by quenbyako** [comment]
Also, as i see in [this chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1129424) @alexdima and @epeios-q37, you guys might be interested in, so this issue already is fixed, but since i don't work with js and electron (flutter in my heart, sry), looks like electron 9.4.3+ [uses chromium 83+](https://github.com/electron/electron/blob/ca82414364002efa665ffa7427e267adf76ed1f3/DEPS#L15) (or am i wrong?). But chromium issue says that compose key was buggey in more fresh versions than 83.

Even if i'm wrong, maybe it's better to implement independent compose key functionality? for each platform)

**Comment by alexdima** [comment]
Let's track in #106725 . The Chromium issue is still "Untriaged (Open)". This [might have been fixed in Chromium 89](https://bugs.chromium.org/p/chromium/issues/detail?id=1129424#c14), but VS Code is still on Chromium 87. So the fix will eventually make its way to us once we adopt a newer Electron version.

**Comment by quenbyako** [comment]
@alexdima any resolve timings? like in next update, or when electron major update?

**Comment by quenbyako** [comment]
@alexdima cancel that, looks like this feature works already, i fully restarted my pc and compose key worked in vscode too!

Thanks again
