### ISSUE TITLE
vscode.executeDefinitionProvider returns vscode.Location that contains bad vscode.Uri instance

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/vscode#118085]
- VS Code Version: 1.53.2
- OS Version: Windows 10 20H2

Steps to Reproduce:
I am developing an extension using the built-in command `vscode.executeDefinitionProvider`, with the microsoft cpp-tool and trying to get the file path of the included file. However, I found that the uri returns from this command cannot be used as an arguement to a second call to this same command. After some debugging, it seems that the uri returns from this command is missing some properties.
1. The following code
```ts
function getDefinition(uri: vscode.Uri, position: vscode.Position)
{
    return vscode.commands.executeCommand("vscode.executeDefinitionProvider", uri, position) as Thenable<(vscode.Location | vscode.LocationLink)[]>;
}
function getCurrentUri()
{
    return vscode.window.activeTextEditor?.document.uri;
}
function getFileUri(definition: (vscode.Location | vscode.LocationLink)[])
{
    return (definition[0] as vscode.Location).uri;
}

async function test()
{
    const uri = getCurrentUri()!;
    const pos = new vscode.Position(0, 10); //the position of an include statement
    const includeDefinition = await getDefinition(uri, pos);   //ok, but returns a bad vscode.Location, which contains a bad vscode.Uri
    const uri2 = getFileUri(includeDefinition);

    const pos2 = new vscode.Position(8, 10); //the position of another include statement
    const definition2 = await getDefinition(uri2, pos2); //fails here
}
```
2. Run the extension with this test cpp file, this is where the `Position(0, 10)` comes from.
```cpp
#include <utility> 
```
And in the `<utility>` there is a `#include <yvals_core.h>` on `Position(8, 10)` if you are on windows with visual studio, 

If I manually opens `<utility>`, the good uri returned from `getCurrentUri()` is like this
```
g {scheme: 'file', authority: '', path: '/C:/Program Files (x86)/Microsoft Visual Studi…ity/VC/Tools/MSVC/14.28.29333/include/utility', query: '', fragment: '', …}
_formatted:'file:///c%3A/Program%20Files%20%28x86%29/Microsoft%20Visual%20Studio/2019/Community/VC/Tools/MSVC/14.28.29333/include/utility'
_fsPath:'c:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\include\\utility'
authority:''
fragment:''
fsPath (get):ƒ fsPath(){return this._fsPath||(this._fsPath=s(this,!1)),this._fsPath}
path:'/C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/include/utility'
query:''
scheme:'file'
```

The uri returned by the command (aka `uri2` in the code) is like this
```
g {scheme: 'file', authority: '', path: '/C:/Program Files (x86)/Microsoft Visual Studi…ity/VC/Tools/MSVC/14.28.29333/include/utility', query: '', fragment: '', …}
_formatted:undefined
_fsPath:null
authority:''
fragment:''
fsPath (get):ƒ fsPath(){return this._fsPath||(this._fsPath=s(this,!1)),this._fsPath}
path:'/C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/include/utility'
query:''
scheme:'file'
```
which cause the second call fails.

I think this issue is likely be caused by vscode internal api itself rather than the cpp-tool.

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
I didn't reproduce but I can see where the flaw is

**Comment by HO-COOH** [comment]
Haven't tried compiling it but I found a workaround for now, that call `vscode.workspace.openTextDocument()` first, then get the `uri` from the returned `Thenable<TextDocument>` would results a good normal uri instance

**Comment by mjbvz** [comment]
I believe I verified this by checking with `instanceof vscode.Uri` and looking at the internal properties of the returned URI

@HO-COOH Please also give the latest insiders build a try and confirm that this issue is fixed

**Comment by HO-COOH** [comment]
@mjbvz @jrieken It's still the same. I am on version `1.55.0-insider`. From what I learned [here](https://github.com/microsoft/vscode-cpptools/issues/7124), the extension should return the right `vscode.Uri` when the call `executeCommand("vscode.executeDefinitionProvider", uri, position)` providing `uri` is currently shown in the window, which is the case here. But the `uri2` in my issue is still missing those fields.
