### ISSUE TITLE
terminal quotes dropped paths, stops evaluation of escape \

### ISSUE THREAD

**Issue by DaleStanbrough** [microsoft/vscode#118142]
Issue Type: <b>Bug</b>

on macOS

1. have a directory with spaces in the path name.
2. open the associated folder in the Finder
3. open visual studio terminal, and type 'cd ' (without quotes) 
4. drag the proxy icon from the finder window into the terminal (which is transformed into a text path).

VS will wrap the dropped path in quotes preventing special processing of escaped spaces in the path.

example shown below.

➜  ~ cd '/Users/dale/Sync\ services/Sync/2021\ -\ s1/APT/project'.
cd: no such file or directory: /Users/dale/Sync\ services/Sync/2021\ -\ s1/APT/project

...and then manually copy the path without quotes, and it works aok.

➜  ~ cd /Users/dale/Sync\ services/Sync/2021\ -\ s1/APT/project
➜  project 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by DaleStanbrough** [comment]
➜  ~ cd '/Users/dale/Sync\ services/Sync/2021\ -\ s1/APT/project'
cd: no such file or directory: /Users/dale/Sync\ services/Sync/2021\ -\ s1/APT/project
➜  ~ 

Problem still exists...

Version: 1.54.0-insider (Universal)
Commit: 42e27fe5cdc58539dad9867970326a297eb8cacf
Date: 2021-03-02T19:09:42.206Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

**Comment by DaleStanbrough** [comment]
This is indeed a duplicate of the other reports. 

I'll close this off now.
