### ISSUE TITLE
Elements in args-list does not update when restarting debug session

### ISSUE THREAD

**Issue by xerosugar** [microsoft/vscode#118196]
Issue Type: <b>Bug</b>

- Create a launch.js for a node.js script.
- Set an args-field, like this in your launch.json:
    "args": ["--update", "filename.json", "filename2.json"]
- Set a breakpoint somewhere in your js-script.
- Run the debug-session, let VS Code stop at the breakpoint.
- Now, make a change to the update the args-list:
    "args": ["--update", "someOtherFile.json", "filename2.json"]
- Restart the debug-session (Ctrl+Shift+F5)
- The script still uses the old parameter-list.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (23.69GB free)|
|Process Argv|--crash-reporter-id 4f8c59a8-5f72-44b3-a421-86f3d9ddce35|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.3
xml|Dot|2.5.1
haxe-hl|Hax|1.1.1
template-string-converter|meg|0.4.7
prettify-json|moh|0.0.3
vscode-docker|ms-|1.10.0
remote-wsl|ms-|0.53.4
cmake-tools|ms-|1.6.0
vscode-js-profile-flame|ms-|0.0.14
vshaxe|nad|2.22.1
lime-vscode-extension|ope|1.4.2
cmake|twx|0.0.17
hxcpp-debugger|vsh|1.2.4
gitblame|wad|6.0.2
codedox|wig|1.3.1
propertylist|zho|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by isidorn** [comment]
I can reproduce this.
The issue is that the js-debug `supportsRestartRequest`. So we let the js-debug handle the restart. Even if there are changes in the configuration.

@connor4312 @weinand I am not sure what is the right behaviour here.
If a change happened to the launch configuration should VS Code disconnect and start the debug session again ignoring the `supportsRestartRequest`? Or should js-debug handle configuration changes as part of its `restart`?
Let me know what you think.

**Comment by weinand** [comment]
Today the spec of the DAP `restart` request doesn't say anything about changed launch configurations.
But we could add an optional argument to the `restart` request so that an implementation has easy access to it.

I suggest that we create a DAP feature request in the CAP's repo. 

@connor4312 @isidorn what do you think?

**Comment by isidorn** [comment]
@weinand this sounds good to me
Let me know if you would like me to create a DAP feature request in the DAP repo.
Also let's see what @connor4312 thinks about this

**Comment by connor4312** [comment]
That sounds good to me

**Comment by weinand** [comment]
@isidorn could you please create a DAP feature request in https://github.com/Microsoft/debug-adapter-protocol/issues

**Comment by isidorn** [comment]
Created https://github.com/microsoft/debug-adapter-protocol/issues/180
Once we add that I can adopt it in VS Code, and then @connor4312 can adopt it in js-debug.

**Comment by isidorn** [comment]
I hate you bot!

**Comment by weinand** [comment]
@isidorn Now the `restart` request takes an argument for the "launch" or "attach" configuration.
Please update VS Code accordingly.

**Comment by isidorn** [comment]
@weinand great, I can look into this.

**Comment by isidorn** [comment]
I have pushed a change such that VS Code will send the configuration as part of the `restart` request. I send a resolved configuration, not the exact one that is in the launch configuration.
I can easily change that I send the exact one in `launch.json`.
Here's an example of what I would send

Assigning this item to you @connor4312 so you can look into adopting it on the js-debug side.
Also let me know if you would like me to change something on the client side. Thanks

![Screenshot 2021-04-16 at 15 31 58](https://user-images.githubusercontent.com/1926584/115031921-02f29700-9ec9-11eb-871c-269378016ae3.png)

**Comment by weinand** [comment]
@isidorn yes, sending the resolved configuration is correct (since that is the same what a DA sees in the "launch" or "attach" requests when it does **not** implement DAP's "restart" request).

(and it goes without saying that the resolved configuration must be based on the most recent launch config on disk...)

**Comment by connor4312** [comment]
It looks like for js-debug, restart is always being dispatched to the child session, so there's no configuration to re-read. Should restarting via the toolbar go to the root session like stop/detach does?

**Comment by isidorn** [comment]
@connor4312 yes this makes sense, I have pushed a change to tackle this.
So now restart, stop and disconnect are aligned, they always send to the parent session.

**Comment by connor4312** [comment]
Ok, great. I'll tackle this next iteration.

**Comment by aeschli** [comment]
Following the steps from the description, I still see the old parameters after the restart.
- index.js: `console.log(JSON.stringify(process.argv));`
- launch config
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Launch Program",
            "args": ["--update", "someFile.json", "filename2.json"],
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\index.js"
        }
    ]
}
````
- set breakpoint in index.js, hit the breakpoint, change the `args`, restart (Ctrl+Shift+F5), finish the program, the first args are printed.

**Comment by connor4312** [comment]
It looks like ctrl+shift+f5 sends the restart to the child session which does not cause the launch.json to be re-evaluated

**Comment by isidorn** [comment]
@connor4312 aha because we do not have a correlation  between the child session and the launch.json configuration. Is this something that could be handled on the js-debug side, or we have to handle it in VS Code?

**Comment by connor4312** [comment]
Maybe it would be more sustainable to introduce a new concept in DAP, like `supportsForwardParentLifecycle` that would instruct the editor to send all stop/disconnect/restarts to the parent session?

**Comment by isidorn** [comment]
Sounds a bit funky 😊 
@weinand thoughts?

**Comment by connor4312** [comment]
Yea, it's not really a 'capability', but some mechanism to request the client to forward lifecycle requests to the parent session. Remember for this case VS Code _must_ initiate the restart on the parent since it needs to re-read the debug configuration for us. Would have to think about naming for it.

**Comment by connor4312** [comment]
Thinking some more, I don't believe `supportsLifecycle` would be a terrible flag, as a default-true capability to indicate that a session doesn't independently manage its own lifecycle, implying it is instead a component of its parent..

**Comment by weinand** [comment]
@connor4312 @isidorn since parent/child relations between debug sessions are not part of the DAP, I think the `supportsLifecycle` flag is more an option on the `startDebugging` extension API, right?

Name suggestion: `manageByParent`

**Comment by isidorn** [comment]
Yeah I think it would belong under the `DebugSessionOptions` in the `startDebugging` API since we already have parent child session flags there like `parentSession` and `compact`.

**Comment by connor4312** [comment]
Sounds good to me

**Comment by weinand** [comment]
I'll add the `manageByParent` property to the `DebugSessionOptions` in July.

**Comment by weinand** [comment]
@isidorn a new flag `lifecycleManagedByParent` is now available on `IDebugSessionOptions` passed into `DebugService.startDebugging`.

**Comment by isidorn** [comment]
@weinand thanks for adding the flag.

Since the flag's name if `lifecycleManagedByParent` I think it means that all the `disconnect` and `restart` requests are actually sent to the parent session? I do not think this flag would affect any other requests, correct?

**Comment by weinand** [comment]
@isidorn yes, only if `lifecycleManagedByParent` is true, `disconnect` and `restart` requests are sent to the parent session.

@connor4312 that's OK with you?

**Comment by isidorn** [comment]
I pushed a change that the debugSession now respects `lifecycleManagedByParent` for `disconnect`, `terminate` and `restart` requests.

Leaving this issue open so @connor4312 can pass the `lifecycleManagedByParent` flag when calling the `startDebugging` API.

**Comment by weinand** [comment]
@connor4312 are you planning to add support for `lifecycleManagedByParent` to js-debug in this milestone?
If yes, I would create a test item for #128058.

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/commit/f6635d9f7dd43671a17524b2f208e132527d601a

**Comment by weinand** [comment]
@connor4312 yes, please mark https://github.com/microsoft/vscode/issues/128058 as verified.

**Comment by weinand** [comment]
Verified that this works fine now.
