### ISSUE TITLE
scroll scm is very very slow

### ISSUE THREAD

**Issue by FernandoMiguel** [microsoft/vscode#118195]
Issue Type: <b>Performance Issue</b>

I have a large number or repos open in the scm repository list.
when i toggle between closed and expanded,
the expanded view is painfully slow to scroll, it lags and jumps view, making it hard to go to a specific one.
this was much faster in the previous release.

Version: 1.55.0-insider
Commit: 567b82a0f9c31bd463af64997997730c5d0173cc
Date: 2021-03-05T05:22:04.953Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

VS Code version: Code - Insiders 1.55.0-insider (567b82a0f9c31bd463af64997997730c5d0173cc, 2021-03-05T05:22:04.953Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|work/CM work/DI2Infrastructure work/DS9 work/SRE work/TF-Modules work/azuredevops work/datagenic work/gitlab work/terraform-provider|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   131	 35757	code-insiders main
    0	    82	 35760	   gpu-process
    0	    33	 35761	   utility
    0	   246	 35763	   window (Untitled (Workspace))
    0	   164	 35766	     extensionHost
    0	    16	 35877	       /Users/fernando/.vscode-insiders/extensions/hashicorp.terraform-2.7.0/lsp/terraform-ls serve
    0	    16	 35879	       /Users/fernando/.vscode-insiders/extensions/hashicorp.terraform-2.7.0/lsp/terraform-ls serve
    0	    16	 35880	       /Users/fernando/.vscode-insiders/extensions/hashicorp.terraform-2.7.0/lsp/terraform-ls serve
    0	    16	 35881	       /Users/fernando/.vscode-insiders/extensions/hashicorp.terraform-2.7.0/lsp/terraform-ls serve
    0	    16	 35882	       /Users/fernando/.vscode-insiders/extensions/hashicorp.terraform-2.7.0/lsp/terraform-ls serve
    0	    16	 35883	       /Users/fernando/.vscode-insiders/extensions/hashicorp.terraform-2.7.0/lsp/terraform-ls serve
    0	    16	 35884	       /Users/fernando/.vscode-insiders/extensions/hashicorp.terraform-2.7.0/lsp/terraform-ls serve
    0	    16	 35885	       /Users/fernando/.vscode-insiders/extensions/hashicorp.terraform-2.7.0/lsp/terraform-ls serve
    0	    16	 35886	       /Users/fernando/.vscode-insiders/extensions/hashicorp.terraform-2.7.0/lsp/terraform-ls serve
    0	    33	 35767	     watcherService
    0	    33	 35821	     searchService
    0	    98	 35764	   shared-process
    0	    33	 35765	     ptyHost
    0	    33	 36072	       /usr/local/bin/bash -l
    0	     0	 40953	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    49	 40951	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

</details>
<details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
markdown-toc|Ala|1.5.6
inline-hasher|ale|1.1.0
spellright|ban|3.0.56
git-temporal-vscode|bee|1.0.0
better-toml|bun|0.3.2
hadolint|exi|1.0.1
terraform|has|2.7.0
markdown-shortcuts|mdi|0.12.0
azure-pipelines|ms-|1.183.0
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.10.0
azure-account|ms-|0.9.6
azurecli|ms-|0.5.0
vscode-yaml-sort|Pas|3.3.0
errorlens|Phi|1.1.3
git-file-history|pom|1.0.1
vscode-yaml|red|0.16.0
vscode-gitweblinks|red|2.3.0
vscode-nginx|sha|0.6.0
shellcheck|tim|0.13.2
azure-devops-yaml-pipeline-validator|Tom|1.7.0
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.1.0
jinja|who|0.0.8
json|Zai|2.0.2

</details>

**Comment by gjsjohnmurray** [comment]
Please check whether it is also slow after you run the command to reload with all extensions disabled.

**Comment by FernandoMiguel** [comment]
attached a screen recording @gjsjohnmurray  with extensions disabled.

`$ code --disable-extensions`

https://user-images.githubusercontent.com/168366/110158013-c8351380-7de0-11eb-8479-5d4c31ed18dd.mov

you should be able to see how sluguish it behaves when scm are expanded

**Comment by eamodio** [comment]
@joaomoreno I haven't dug into this, but do you think this is just list rendering related? Or something more specific to SCM?

**Comment by deepak1556** [comment]
Can you attach the profile following these steps,

* Open window devtools from command palette
* Go to performance tab
* Click start profiling and reload page icon
* Perform actions that cause the slowdown
* Download the profile

**Comment by FernandoMiguel** [comment]
not sure if the profile will contain sensitive data.
is there a way to securely share it?

**Comment by deepak1556** [comment]
It will be just cpu profile of the javascript code in the vscode app and will not contain sensitive information related to your workspace.

**Comment by FernandoMiguel** [comment]
[Profile-20210309T114158.json.zip](https://github.com/microsoft/vscode/files/6110796/Profile-20210309T114158.json.zip)
zipped since json is not allowed

**Comment by eamodio** [comment]
@FernandoMiguel is this a regression? Did you see the same behavior prior to 1.55 or 1.54?

**Comment by FernandoMiguel** [comment]
It started shortly after the collapse repo feature of came out to insiders

**Comment by FernandoMiguel** [comment]
Before that feature was really smooth

**Comment by eamodio** [comment]
I've pushed a "fix" that significantly improves the scrolling performance, but we still seem to be doing a lot of work as we scroll. @joaomoreno do you have any suggestions for reducing that?

While investigating this, I also fixed a listener leak as part of this too: https://github.com/microsoft/vscode/commit/7a9e144ee1514ee888d63b2edbbef83626a0bfaa

**Comment by FernandoMiguel** [comment]
I've updated to
```
Version: 1.55.0-insider
Commit: 9b2ee7fb7d970b9a628fdb3545bdd01d67078d16
Date: 2021-03-11T05:15:23.749Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

and it's much better. still not smooth, there is some janky, but it's tolerable, unlike before.
thank you for the fix.
i'll eagerly await for further improvement
