### ISSUE TITLE
pty host not responding after prompt-toolkit exits

### ISSUE THREAD

**Issue by Stax124** [microsoft/vscode#119126]
Issue Type: <b>Bug</b>

**requirements: Python 3.8.7, prompt-toolkit==3.0.17**

If terminal is closed before prompt-toolkit manually recieves sys.exit(), pty host will not be launched properly and you must wait for 'pty host is unresponsive: reload ?' dialog

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.96GB free)|
|Process Argv|--crash-reporter-id 277fa239-d0f5-431c-a59e-26d44af31f56|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-sqlite|ale|0.11.1
al-toolbox|Bar|2.0.8
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.39.0
gitlens|eam|11.3.0
prettier-vscode|esb|6.3.0
vscode-pull-request-github|Git|0.24.0
discord-vscode|icr|5.4.0
polacode-2019|jef|0.5.2
markdown-toc|jof|1.4.0
python|ms-|2021.3.658691958
vscode-pylance|ms-|2021.3.1
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.5
vscode-remote-extensionpack|ms-|0.20.0
vscode-typescript-next|ms-|4.3.20210315
vsliveshare|ms-|1.0.3968
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.5.0
LiveServer|rit|5.6.1
color-manager|roy|0.6.2
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.2.0
material-theme|zhu|3.9.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vscoresta800cf:30276762
vspre833:30267464
vsdfh931:30275552

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by Stax124** [comment]
Still persists
![image](https://user-images.githubusercontent.com/60222162/113104830-42e72800-9201-11eb-9702-2e8597bc75d1.png)
