### ISSUE TITLE
blurry terminal

### ISSUE THREAD

**Issue by luwol03** [microsoft/vscode#120083]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. just open vscode
2. open integrated terminal

![image](https://user-images.githubusercontent.com/60048565/112810302-2a4d0580-907b-11eb-802a-6cf3976cf7f5.png)
![image](https://user-images.githubusercontent.com/60048565/112810894-cc6ced80-907b-11eb-95d1-a0acd744206c.png)

This happens not only on the git bash. Also on the windows cmd or powershell.

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.55.0-insider (d06d2f1d6245ce00b1c36a9cd81a9087d225173e, 2021-03-26T14:01:14.867Z)
OS version: Windows x64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.68GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/luwol03/Desktop/Developement/vocascan/vocascan-desktop --crash-reporter-id 6cdb17d6-ef23-4369-9269-ab3fda79e7ef|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
wslfolderdoc:30278405
vsc_aa:30263845
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfilebuttoncf:30280635
vshan820:30276952
vscoregs2cf2:30281057

```

</details>

**Comment by Tyriar** [comment]
Can you share your settings.json as well as open devtools (Help > Toggle Developer Tools) and type `window.devicePixelRatio` in the console?

**Comment by luwol03** [comment]
Thats strange. If I remove all my settings in the `settings.json` (leave only `{}`) the terminal is showing fine. Also if I revert it back to my settings the termianal is still fine. But if I restart. Same issue, terminal is blurry. And if I restart without any settings blurry terminal. 

![image](https://user-images.githubusercontent.com/60048565/112816201-726f2680-9081-11eb-87ad-3f0025086867.png)

**Comment by Tyriar** [comment]
Strange, I haven't seen this reported before and not really sure what would be causing it. Resizing the terminal by dragging the panel would probably also fix the issue in the same way.

**Comment by luwol03** [comment]
no, resizing does not fix it.

**Comment by luwol03** [comment]
I used the unistaller and reinstalled vscode-insiders. Same issue. Is there a way to get older vscode-inders builds?

**Comment by luwol03** [comment]
I still have this problem. Any idea how I can fix or debug this? I tried to fresh install it on my pc but it didn't fixed it.

**Comment by luwol03** [comment]
Since the following version, an reload doesn't fix the bug temporaerly. So for now the only fix for me is to remove and paste again all config.
```
Version: 1.56.0-insider (user setup)
Commit: 0310f02dc5d834bb3a7cc421ea5374aec8d011f1
Date: 2021-04-23T05:13:46.805Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
```

**Comment by Tyriar** [comment]
The input issue should be fixed in today's build, it was related to the Electron 12 update.

**Comment by luwol03** [comment]
> The input issue should be fixed in today's build, it was related to the Electron 12 update. 

Hello, thank you very much for taking care of it. Unfortunately, the problem is not fixed. Now I can write and fix it with a reload of the window again. It's back to the way it was at the beginning.

I have this version installed. 5080d21c0b538b996c83fb7b14a746f656eaef15

**Comment by Tyriar** [comment]
Looks like some GPU issue on your machine. One of these should fix it:

- Launching with `code --disable-gpu`
- Setting `"terminal.integrated.gpuAcceleration": "off"`

**Comment by luwol03** [comment]
Thank you so much, you have saved my favorite editor :D
Now it works fine.
