### ISSUE TITLE
Terminal webgl renderer oh-my-posh prompt issues 

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#120129]
Below are 3 screenshots from vscode and windows terminal. You can see with the webgl renderer there are strange vertical lines that break the flow. And in both the webgl and canvas, the text isn't vertically aligned properly either. Whereas, Windows Terminal looks the best (only very minor vertical line artifacts).

VS Code webgl renderer

![image](https://user-images.githubusercontent.com/641685/112893996-55e6e480-90a9-11eb-9e35-75bf38204ba9.png)

VS Code canvas renderer

![image](https://user-images.githubusercontent.com/641685/112894067-67c88780-90a9-11eb-9798-21786454a362.png)

Windows Terminal

![image](https://user-images.githubusercontent.com/641685/112894129-7adb5780-90a9-11eb-8d58-80b8c06afa64.png)

**Comment by Tyriar** [comment]
What I suspect is happening here is that the more clever glyph boundary detection in the webgl renderer where we render the character with a margin and then find its bounding box is biting us because the darker lines are not exactly the same color as the actual background. I wonder if we should hardcode for these particular powerlines characters to explicitly drop that line.

**Comment by Mellbourn** [comment]
@eamodio I also experience new problems with vertical lines that break the flow. So I 100% agree that there is a VSCode bug to fix here.

However, I don't see the vertical alignment problem. Are you using Nerd Fonts? Some Nerd Fonts have problems with vertical centering. Delugia (a Nerd Font version of Cascadia Code) recently made a patch release to repair centering (https://github.com/adam7/delugia-code/issues/53 and https://github.com/adam7/delugia-code/pull/55 go into a lot of detail). The `Book` version of Delugia would also let you use full-width glyphs (2 characters), I notice that your git branch icon is a cramped one character width.

**Comment by Tyriar** [comment]
In xterm.js demo

Dom:

![dom](https://user-images.githubusercontent.com/2193314/113364054-63010f00-9307-11eb-9398-31a881fc05a1.png)

Canvas:

![canvas](https://user-images.githubusercontent.com/2193314/113364064-67c5c300-9307-11eb-955f-91445fe0fdee.png)

Webgl:

![webgl](https://user-images.githubusercontent.com/2193314/113364072-6b594a00-9307-11eb-914f-656dc5569442.png)

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/3278

**Comment by Tyriar** [comment]
Fix looking good, should be able to merge tomorrow: https://github.com/xtermjs/xterm.js/pull/3279

**Comment by Mellbourn** [comment]
It now looks perfect with GPU in Insiders!

<img width="294" alt="Delugia Nerd Font Book shown using fixed GPU rendering" src="https://user-images.githubusercontent.com/1785727/113413337-bda77300-93ba-11eb-881d-7c65ad077728.png">

**Comment by Tyriar** [comment]
@Mellbourn good to hear 😃 the alignment is even fixed on canvas too so it should just as good there as well.

**Comment by Mellbourn** [comment]
In Insiders, `renderType` is removed, so, as you say, you can't force it explicitly. If I set `terminal.integrated.gpuAcceleration` to `off`, I get this:
<img width="294" alt="Delugia Nerd Font Book gpuAcceleration off" src="https://user-images.githubusercontent.com/1785727/113454493-aa22f900-9408-11eb-8b6f-d195fc47d487.png">
Here there is still a vertical line. Also, the double width Nerd Fonts glyphs looks cut off to single character width.

**Comment by Tyriar** [comment]
The DOM renderer works a little differently, to get cells to align perfectly they are laid our using inline-block and regular rely on the regular flow of the page as opposed to absolute positioning for performance reasons. I wonder if we could take the nerd font glyph ranges and the powerlines glyph ranges, and handle them specially. Positioning absolute won't work but I wonder if we could do some something using `:before { content: '' }` so that it could be positioned absolutely on top of the cell 🤔 

Surprisingly I didn't see the line on my tests, maybe it's only on certain font sizes or something.

**Comment by Tyriar** [comment]
Created https://github.com/xtermjs/xterm.js/issues/3287, I probably won't have time to check it out this release though.

**Comment by karesztrk** [comment]
Finally, its solved in Stable version as well ❤️ Thanks team

**Comment by floh96** [comment]
@Tyriar I'm on vscode insider commit 6bee0f2f3fea9df1ad45344f09b2a139c93b384f and it looks broken again
![Unbenannt](https://user-images.githubusercontent.com/49693964/117484691-bbab7380-af67-11eb-8961-383f0b429056.PNG)
it worked on an older version (unfortunately I don't know the commit but it was a version witch was published shortly after this issue was fixed.
 
![113411464-19bbc880-93b6-11eb-85cb-3cebfe5d36bf](https://user-images.githubusercontent.com/49693964/117484708-c108be00-af67-11eb-96f8-d58789a01b37.png)

**Comment by Tyriar** [comment]
@floh96 do you have a particular large `window.zoomLevel`/`*.fontFamily` and what's `terminal.integrated.gpuAcceleration` set to?

**Comment by floh96** [comment]
@Tyriar window.zoomLevel is 0 font family is 'CaskaydiaCove NF', Consolas, 'Courier New', monospace font size is 16.
I only zoomed for the screenshot. 
terminal.integrated.gpuAcceleration is set to auto

**Comment by Tyriar** [comment]
@floh96 does the problem seem isolated to that font maybe?

**Comment by floh96** [comment]
@Tyriar i chanced the font to FiraMono NF same problem
![Unbenannt](https://user-images.githubusercontent.com/49693964/117489786-5444f200-af6e-11eb-9617-9fb98d997f4d.PNG)

**Comment by floh96** [comment]
@Tyriar friendly ping 😄

**Comment by Tyriar** [comment]
@floh96 not sure what else we could do here unfortunately, without doing something drastic like not actually rendering the glyph but doing it ourselves like in https://github.com/xtermjs/xterm.js/issues/2409

**Comment by floh96** [comment]
@Tyriar okay sad to hear. 
it worked initially for ne so something musst have changed on vscode side.
is there a workaround (using a different renderer for example)?

**Comment by Tyriar** [comment]
@floh96 you could try switching up the gpuAcceleration setting as that drives which renderer is used, it's was fixed at least on my machine in all the renderers

**Comment by floh96** [comment]
@Tyriar thanks for your suggestion unfortunately changing the setting did not fix the issue.
I'm going to subscribe to  https://github.com/xtermjs/xterm.js/issues/2409
