### ISSUE TITLE
Re-enable terminal workspace settings

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121470]
I disabled the settings in https://github.com/microsoft/vscode/pull/121176/commits/c7d26be9a5cc298bf51d7d671417313d147e461c to allow moving forward with the PR. This commit needs to be reverted when workspace trust ships to re-enable the feature. It will be broken in the meantime.

Apologies if you are impacted by this but it can be worked around by bringing the relevant settings to your user settings file.

**Comment by Tyriar** [comment]
A temporary fix was added to re-enable workspace shell settings when `"terminal.integrated.allowWorkspaceConfiguration": true` is set https://github.com/microsoft/vscode/issues/122104

**Comment by RobertCardwell** [comment]
The work-around is not working for me, using VS Code Insiders on Windows 10 with WSL integrated terminal:

1. In settings.json I add the following lines:

```json
{
	"terminal.integrated.allowWorkspaceConfiguration": true,
	// added both the following as I'm not sure which is correct
	"terminal.integrated.env.linux": {
		"TEST_KEY":"foo"
	},
	"terminal.integrated.env.windows": {
		"TEST_KEY":"bah"
	}
}
```

2. Then I open a new terminal and do:

```shell
echo printenv | grep 'TEST_KEY'
```
And there is no result!

**Comment by davidwin** [comment]
The `"terminal.integrated.allowWorkspaceConfiguration": true` workaround isn't working for me either in the stable 1.56 using Remote SSH. I tried changing the setting both in the User and Remote contexts.

**Comment by zendu** [comment]
`"terminal.integrated.defaultProfile.windows": "My Profile"` setting in workspace is ineffective even after configuring `"terminal.integrated.allowWorkspaceConfiguration": true` in user settings.

Version: 1.57.0-insider (user setup)
Commit: fe23c2041f848d6c2f6bd27875112a37bcc82f84
Date: 2021-05-06T05:16:25.564Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by Tyriar** [comment]
@zendu see https://github.com/microsoft/vscode/issues/123133

**Comment by zendu** [comment]
@Tyriar can you point to specific part of #123133 that I should look at? All I see it link to similar issues, your comments and link back to this issue.

**Comment by Tyriar** [comment]
@zendu that issue was fixed 6 days ago, but only in [Insiders](https://code.visualstudio.com/insiders)

**Comment by bluemonkmn** [comment]
I came here to report issues with terminal.integrated.profiles and terminal.integrated.defaultProfile, and it's not clear to me from this what the supposed status of this is. Here's what I have observed in 1.56.2:
1. Setting `"terminal.integrated.defaultProfile.windows": "Command Prompt"` will successfully get the default terminal to be Command Prompt instead of PowerShell.
2. Setting `"terminal.integrated.allowWorkspaceConfiguration": true` Breaks this and causes the default to revert to PowerShell.
3. The only way I can find to force the workspace to drive the terminal back to command prompt is with the old deprecated setting: `"terminal.integrated.shell.windows": "${env:windir}\\System32\\cmd.exe"`

I would expect at least one of the following to work instead of number 3 above:
1. Specify `"terminal.integrated.defaultProfile.windows": "Command Prompt"` in the workspace file,
2. Create a valid `"terminal.integrated.profiles.windows"` block in the workspace file that includes a Command Prompt section, OR
3. Do nothing - if the `"terminal.integrated.defaultProfile.windows"` setting is not valid in the workspace file, VS Code should honor the setting from the settings.json file.

**Comment by Tyriar** [comment]
@bluemonkmn a lot of problems around default profiles was recently fixed in [Insiders](https://code.visualstudio.com/insiders) if you want to give that a spin. Here's the big change that fixed most of the problems https://github.com/microsoft/vscode/pull/123729

**Comment by robcca** [comment]
@Tyriar The injection of environment variables into the shell is still not working (Insiders). These are my settings:

```json
  "terminal.integrated.allowWorkspaceConfiguration": true,
  "terminal.integrated.env.linux": {
    "TEST_KEY": "foo"
  },
  "terminal.integrated.env.windows": {
    "TEST_KEY": "bar"
  },
```

**Comment by Tyriar** [comment]
@robcca `"terminal.integrated.allowWorkspaceConfiguration": true,` only works in user settings, is that the problem?

**Comment by zendu** [comment]
@Tyriar - I continue to see the issue in Insiders. I created a custom terminal profile in workspace settings, but following line shows error and that profile is not used to create terminal.

    "terminal.integrated.defaultProfile.windows": "MyCMD"

Error message in "problems" window of VS Code:
Value is not accepted. Valid values: "PowerShell", "Command Prompt", "Git Bash".

Version: 1.57.0-insider (user setup)
Commit: 45aafeb326d0d3d56cbc9e2932f87e368dbf652d
Date: 2021-05-18T05:14:15.253Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by robcca** [comment]
> @robcca `"terminal.integrated.allowWorkspaceConfiguration": true,` only works in user settings, is that the problem?

No, if I understand your question correctly. Those settings are in the settings.json file in "C:\Users\<user>\AppData\Roaming\Code - Insiders\User" and not the one in in the .vscode folder in the root of my project.

**Comment by hanct** [comment]
I encounter similar issue.  All i hope is that we can set the environment variables for terminal at Workspace level.  I  was hopping nothing need to be set in the user settings.

**Comment by meganrogge** [comment]
Complication reported here https://github.com/microsoft/vscode/issues/125440

**Comment by robcca** [comment]
> Marking this as verified bc complication and the fix are tracked here #125440.

Why is the issue closed? The problem still exists and I can't see the relevance of #125440.

**Comment by Tyriar** [comment]
@robcca it's closed because workspace terminal settings now works in Insiders, if it does not for you please provide more information

**Comment by robcca** [comment]
> @robcca it's closed because workspace terminal settings now works in Insiders, if it does not for you please provide more information

The situation is the same as I described in a [previous comment ](https://github.com/microsoft/vscode/issues/121470#issuecomment-841743095), although I see that "terminal.integrated.allowWorkspaceConfiguration": true is greyed-out since you removed it and made it the default behaqviour. The environment variable that I added in settings.json does not appear in the WSL Ubuntu 20.04 inline terminal (my default) but does appear in the environment of, say, Git Bash and every other non-WSL inline terminal.
