### ISSUE TITLE
ts js server dead 5 times

### ISSUE THREAD

**Issue by LOLBRUHNICE** [microsoft/vscode#121588]
Issue Type: <b>Bug</b>

open vscode then it occured

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.88GB (12.20GB free)|
|Process Argv|--crash-reporter-id e9d81545-fec8-48d4-990e-65c9ed79faa7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|2.3.0
vscode-database|baj|2.2.3
color-info|bie|0.5.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.20
prettier-vscode|esb|6.3.2
auto-rename-tag|for|0.1.6
vscode-yarn|gam|1.7.1
cloudcode|goo|1.10.0
vscode-env|Iro|0.1.0
vscode-colorize|kam|0.11.0
node-module-intellisense|lei|1.5.0
vscode-typescript-next|ms-|4.3.20210417
vscode-extension-auto-import|Nuc|1.4.3
vetur|oct|0.33.1
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.6.0
vscode-css-peek|pra|4.1.3
autoimport|ste|1.5.4
tabnine-vscode|Tab|3.4.2
vscode-import-cost|wix|2.15.0
material-theme|zhu|3.10.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30286882

```

</details>

**Comment by LOLBRUHNICE** [comment]
I didnt know any other info as it just happen when I open vscode sometimes,it just happen randomly

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also try to provide info about what seems to trigger the issue

**Comment by LOLBRUHNICE** [comment]
after i updated the vscode to latest version, it looks like didn't reproduce anymore

**Comment by LOLBRUHNICE** [comment]
should be fixed now

**Comment by LohitakshTrehan** [comment]
Issue still prevalent
https://github.com/microsoft/vscode/issues/123392#issue-881961204
