### ISSUE TITLE
Using "Reopen Editor With..." on a notebook doesn't fully close the notebook editor.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#121777]
- VS Code Version: Stable
- OS Version: Windows

Steps to Reproduce:

1. Install the .NET Interactive extension `ms-dotnettools.dotnet-interactive-vscode`
2. Install the Jupyter extension `ms-toolsai.jupyter`.
3. Open an existing `.ipynb` file with the Jupyter (preview) editor.
4. Right-click the editor tab and "Reopen Editor With..." and select ".NET Interactive Jupyter".
5. Repeat step 4 but select Jupyter (preview) again.

Result:
Depending on how fast things happen, at some point VS Code will fail to reopen the notebook and say that it can't open view type X because view type Y already exists.

Does this issue occur when all extensions are disabled?: N/A

**Comment by jrieken** [comment]
>  that it can't open view type X because view type Y already exists.

Yes - we don't support to open the same file multiple times for different view types. That is a limitation in how we have implemented things - everything gets identified by uri, nut by the [uri,type]-tuple. With this limitation there are two options

1. don't allow to create another notebook with different viewType (as today)
2. dispose/close the conflicting notebook when another notebook comes along

Both aren't ideal, option (1) was the easiest to implement because option (2) means all editors etc need to react too. This means the reference-counting contract is violated (the model is disposed despite them holding a reference) and funny scenarios would happen: split an editor, in one editor do reopen-with, the second editor must now close...

We are aware of this limitation but I our thinking is that content providers are shared across extensions, e.g there would be a "base extension" that only implements read/writing of ipynb-files

**Comment by DonJayamanne** [comment]
@brettfo out of curiosity, why would one want to open an ipynb file with the .Net version?
Why not use the Jupyter ipynb provider?

**Comment by brettfo** [comment]
This is no longer an issue for .NET Interactive as we've completely removed our custom .ipynb handling, but the underlying bug is still interesting.

> why would one want to...

They almost certainly wouldn't, but VS Code doesn't know the difference between .NET and Python .ipynb files and it seems to open any given file with the last-used editor, so if a user last had a .ipynb open in .NET doing .NET things then tried to open a Python .ipynb, the .NET editor would have been auto-selected, and that's obviously not correct so they would want to "Reopen With...".  The inverse is also true; if they last were editing Python notebooks then opened a .NET one, the Jupyter (Python) editor would be selected and they'd likely want to "Reopen With...".

**Comment by jrieken** [comment]
Closing this as we don't support to open a notebook (same URI) with different serializers
