### ISSUE TITLE
terminal.integrated.splitCwd="inherited" is not working on mac/linux

### ISSUE THREAD

**Issue by tchkreddy** [microsoft/vscode#121705]
Issue Type: <b>Bug</b>

This seems to have broken recently.

1. Open an integrated terminal
2. Switch to another directory
3. Split the terminal
Expected: New split terminal opens in the directory switched to at #2
Actual: It opens in the original directory #1

terminal.integrated.splitCwd is at default (=inherited). Explicitly added in JSON. No effect

Mac OS BigSur.

VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 601e5aac-44e5-4054-a502-909a84d91473|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
git-diff-and-merge-tool|dav|1.0.4
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
gitlens|eam|11.4.1
filter-lines|ear|0.2.0
vscode-open-in-application|fab|1.0.6
code-runner|for|0.11.3
fontsize-shortcuts|fos|1.5.0
gc-excelviewer|Gra|3.0.41
beautify|Hoo|1.5.0
rest-client|hum|0.24.5
vscode-edit-csv|jan|0.5.8
json2csv|kha|0.0.1
rainbow-csv|mec|1.8.1
git-graph|mhu|1.30.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.6.0
vscode-data-preview|Ran|2.3.0
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.3
now-vscode|Ser|1.5.0
html-preview-vscode|tht|0.2.5
todo-list|Tza|1.6.0
vscodeintellicode|Vis|1.2.12
better-align|wwm|1.1.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by tchkreddy** [comment]
Effectively, on macOS too, inherited is behaving like initial.

If I open terminal from a folder, let's say using "Open in Terminal" from the sidebar/git repos etc, change the directory and do a split terminal, the new terminal opens in the original directory  (like expected with initial)

**Comment by furai** [comment]
For me on top of that - the default keyboard shortcut for splitting terminals stopped working.

**Comment by coffenbacher** [comment]
Terminal splitting is stopped working for me as well on

Version: 1.56.0-insider
Commit: 23a2409675bc1bde94f3532bc7c5826a6e99e4b6
Date: 2021-04-21T05:13:27.110Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-48-generic snap

**Comment by furai** [comment]
Seems to have been fixed in latest insiders.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by coffenbacher** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

My terminal splitting is confirmed fixed, thanks :+1: not sure about OP's issue

**Comment by tchkreddy** [comment]
I tried in insider's build latest - 1.56.0-insider
but the issue persists.

Just to be sure, tried with default zsh and bash as well.
"terminal.integrated.splitCwd": "inherited",

1. opened terminal - it opened in ~
2. cd Desktop
3. Split terminal - it opned in ~ again.

**Comment by furai** [comment]
> I tried in insider's build latest - 1.56.0-insider
> but the issue persists.
> 
> Just to be sure, tried with default zsh and bash as well.
> "terminal.integrated.splitCwd": "inherited",
> 
>     1. opened terminal - it opened in ~
> 
>     2. cd Desktop
> 
>     3. Split terminal - it opned in ~ again.

I can confirm, inherit option does not work (on Version: 1.56.0-insider; Commit: 0310f02dc5d834bb3a7cc421ea5374aec8d011f1; OS: Linux x64 5.11.16-051116-generic).

**Comment by tchkreddy** [comment]
How do i get this fix immediately, at-least on insiders?

**Comment by Tyriar** [comment]
It'll be out this afternoon or tomorrow in Insiders

**Comment by tchkreddy** [comment]
I'm currently on a higher commit but the issue reproduces

Version: 1.56.0-insider
Commit: a348d103d1256a06a2c9b3f9b406298a9fef6898
Date: 2021-04-30T05:11:52.711Z (1 hr ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64

Uploading Screen Recording 2021-04-30 at 12.37.44 PM.mov…

 20.3.0

**Comment by tchkreddy** [comment]
https://user-images.githubusercontent.com/7251057/116662608-9d67d580-a9b3-11eb-8147-82330decfa1b.mov

**Comment by Tyriar** [comment]
@tchkreddy hmm that exact repro works fine for me. Do you see any errors in the either devtools console (Help > Toggle Developer Tools) or in the shared process console (F1, Toggle Shared Process)?

**Comment by tchkreddy** [comment]
None in Shared Process console, but these in Dev Tools. Not sure if they are related
![image](https://user-images.githubusercontent.com/7251057/116694856-67d7e200-a9dd-11eb-9221-b13e8fec738d.png)

**Comment by Tyriar** [comment]
That's not related 🤔 

Could you capture a trace log of the split, it will give us the exact values used to create the terminal, perhaps the `cwd` is set to something invalid or something https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging

**Comment by Tyriar** [comment]
Cannot repro the issue on Insiders again, closing.

**Comment by mjbvz** [comment]
I am also seeing this on MacOS

Steps:
1. On MacOS
2. With `"terminal.integrated.splitCwd": "inherited"` (the default)
1. Open a new terminal
2. `cd node_modules`
3. Split (either using button or shortcut)
4. 🐛 New terminal is still in the root of the project

Here are the logs

<img width="1759" alt="Screen Shot 2021-06-03 at 5 11 08 PM" src="https://user-images.githubusercontent.com/12821956/120727164-b40bbb80-c48e-11eb-81aa-d69099b35d59.png">

**Comment by Tyriar** [comment]
Split command/keybinding works, the tab button doesn't. This is probably splitInstance not supporting it properly

**Comment by mradcliffe** [comment]
> Split command/keybinding works, the tab button doesn't. This is probably splitInstance not supporting it properly

Following-up that with 1.59.0 (July Update) on MacOS, the split command/keybinding and context menu split workaround no longer respects `terminal.integrated.splitCwd` as `workspaceRoot` when choosing from the "Select current working directory for new terminal" palette drop-down option. This happens with either `terminal.integrated.tabs.enabled` as true or false or whether `terminal.integrated.defaultLocation` is `view` or `editor`.

Now Split always starts in the working directory the initial terminal was opened in.

**Comment by MateusMarcuzzo** [comment]
I am also having the same Issue on the most recent version of vscode (1.59)

I'm using Ubuntu

**Comment by eclipseo** [comment]
> It'll be out this afternoon or tomorrow in Insiders

Any news regarding this issue? The last inisders doesn't seem to have the fix, worse the keybinding method doesn't work anymore.
