### ISSUE TITLE
Lots of errors printed when running integration tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#121710]
```
[3085:0420/082748.525181:INFO:CONSOLE(78)] "Error: Unable to read file '/Users/bpasero/Development/Microsoft/monaco/extensions/markdown-language-features/notebook-out/index.js' (Error: Unable to resolve non-existing file '/Users/bpasero/Development/Microsoft/monaco/extensions/markdown-language-features/notebook-out/index.js')", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/webview/browser/resourceLoading.js (78)
[3085:0420/082748.525226:INFO:CONSOLE(78)] "Error: Unable to read file '/Users/bpasero/Development/Microsoft/monaco/extensions/notebook-markdown-extensions/notebook-out/katex.js' (Error: Unable to resolve non-existing file '/Users/bpasero/Development/Microsoft/monaco/extensions/notebook-markdown-extensions/notebook-out/katex.js')", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/webview/browser/resourceLoading.js (78)
[3085:0420/082748.525245:INFO:CONSOLE(78)] "Error: Unable to read file '/Users/bpasero/Development/Microsoft/monaco/extensions/notebook-markdown-extensions/notebook-out/emoji.js' (Error: Unable to resolve non-existing file '/Users/bpasero/Development/Microsoft/monaco/extensions/notebook-markdown-extensions/notebook-out/emoji.js')", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/webview/browser/resourceLoading.js (78)
[3085:0420/082748.532076:INFO:CONSOLE(78)] "Error: Unable to read file '/Users/bpasero/Development/Microsoft/monaco/extensions/markdown-language-features/notebook-out/index.js' (Error: Unable to resolve non-existing file '/Users/bpasero/Development/Microsoft/monaco/extensions/markdown-language-features/notebook-out/index.js')", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/webview/browser/resourceLoading.js (78)
[3085:0420/082748.534350:INFO:CONSOLE(78)] "Error: Unable to read file '/Users/bpasero/Development/Microsoft/monaco/extensions/notebook-markdown-extensions/notebook-out/katex.js' (Error: Unable to resolve non-existing file '/Users/bpasero/Development/Microsoft/monaco/extensions/notebook-markdown-extensions/notebook-out/katex.js')", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/webview/browser/resourceLoading.js (78)
[3085:0420/082748.536220:INFO:CONSOLE(78)] "Error: Unable to read file '/Users/bpasero/Development/Microsoft/monaco/extensions/notebook-markdown-extensions/notebook-out/emoji.js' (Error: Unable to resolve non-existing file '/Users/bpasero/Development/Microsoft/monaco/extensions/notebook-markdown-extensions/notebook-out/emoji.js')", source: file:///Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/webview/browser/resourceLoading.js (78)
```

**Comment by bpasero** [comment]
This makes it very hard for me to use notebooks running out of sources with all the errors printed:

![image](https://user-images.githubusercontent.com/900690/115826562-64f05680-a40b-11eb-83a1-e01017f3378e.png)

I feel there is something missing from the extensions compile task here:

https://github.com/microsoft/vscode/blob/9bacf617b24b948e8d109e19756a1721d287be85/build/gulpfile.extensions.js#L33-L33

**Comment by mjbvz** [comment]
Duplicate of #120213

**Comment by bpasero** [comment]
I see this without running tests, just by running out of sources.

**Comment by mjbvz** [comment]
How are you building VS Code?

**Comment by mjbvz** [comment]
This also may have been fixed by 6d308e6293e25e14b631c3b61d33ba7a8d4dc4ac

I have not been able to reproduce it locally after building with `yarn run watch` and then running the tests with `./scripts/test-integration.sh`

**Comment by bpasero** [comment]
@mjbvz I still reproduce this, steps:
* macOS (ARM)
* `git clean -xfd`
* `yarn`
* `yarn gulp mixin-server`
* hit `Cmd+Shift+B` in VSCode to trigger default build tasks (maybe this is the problem?)
* `scripts/test-integration.sh`

![image](https://user-images.githubusercontent.com/900690/116194570-4c48af00-a731-11eb-892e-5d122afbe6ab.png)

**Comment by mjbvz** [comment]
Ah thanks. I always use `yarn watch` to build so don't see this. Update the task to also build the extension media

**Comment by bpasero** [comment]
@mjbvz thanks, but why exactly does this need a third build task and cannot be run as part of the second one? 

![image](https://user-images.githubusercontent.com/900690/116352796-06095380-a7f6-11eb-85a1-79fae2c4657a.png)
