### ISSUE TITLE
Untyped escape codes appear in terminal (IRB)

### ISSUE THREAD

**Issue by Brian-Demon** [microsoft/vscode#122485]
- VS Code Version: 1.55
- OS Version: Windows 10 (WSL2 on Debian)

Steps to Reproduce:

1. When I open an IRB session on the terminal I see what appear to be ansi escape codes

Does this issue occur when all extensions are disabled?: Uncertain, this dev flow requires WSL extension.  However, this occurs when only this extension is running.

![Capture](https://user-images.githubusercontent.com/74803363/116330025-41723680-a792-11eb-8519-c5b76eba766e.PNG)

**Comment by meganrogge** [comment]
try setting `terminal.integrated.localEchoLatency` to -1

**Comment by Brian-Demon** [comment]
Thank you for your quick response!

The issue persists after setting `terminal.integrated.localEchoLatency` to -1

**Comment by Brian-Demon** [comment]
Additional info:

When I'm in a Live Share and the sharee gives read/write access to a terminal they created, the terminal starts to experience the same problems but goes away when it goes back to a read only terminal.  When I'm working locally by myself (not Live Share) it happens by default.

**Comment by KyleRAnderson** [comment]
I was just about to open a new issue when I found this one. Here's some of what I've observed, hopefully it helps.

## Behaviour

**The problem in a WSL 2 distro**
https://user-images.githubusercontent.com/22606608/116765514-88129b80-a9f3-11eb-99a0-b20aeb29102c.mp4

**The lack of a problem in a WSL 1 distro**
https://user-images.githubusercontent.com/22606608/116765621-138c2c80-a9f4-11eb-8e21-92f503d29dff.mp4

## What I've tried to fix it
- Setting different renderers for the terminal. I've tried manually setting `terminal.integrated.rendererType` to `canvas`, `dom` and `experimentalWebgl` and this occurs on all three.
- Reinstalling VSCode on the distro. 

   Did a simple `mv ~/.vscode-server ~/.vscode-server.backup` and launched VSCode again on that distro to force it to reinstall. The same issue was present afterwards.
- Using `irb` with other terminal applications.

  When using Windows Terminal and the default Ubuntu shell, `irb` renders properly and no strange characters appear. This only happens with the VSCode integrated terminal.
- Using a WSL 1 distro (Ubuntu 18.04).

  Interestingly enough, **this issue seems to be present only with WSL 2 distributions**. I have an Ubuntu 18.04 distro set to WSL 1 and I tried reproducing it there, everything worked fine. Then, I set that distribution's version to WSL 2 (`wsl --set-version Ubuntu-18.04 2`) and tried again, and I was able to reproduce the issue on it. Finally, I set it back to version 1 (`wsl --set-version Ubuntu-18.04 1`) and... no strange characters. Somehow, this is only a problem with WSL 2 distros.
- Disabling local echo for the `irb` program by adding `irb` to `terminal.integrated.localEchoExcludePrograms`.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by KyleRAnderson** [comment]
Just tested it out, I believe this is still an issue in the latest VSCode insiders build.
![image](https://user-images.githubusercontent.com/22606608/116873216-4c3f2800-abe5-11eb-99c1-5689ea74fa69.png)

**Comment by KyleRAnderson** [comment]
Just tested it out on the latest Insiders build, I haven't been able to reproduce it there so it seems that it's been fixed.

**Comment by Brian-Demon** [comment]
Unfortunately I am still having this problem while Live Sharing with someone else. However, when I am not Live Sharing the Insider build does fix the problem. We tried permutations of when both of us are using the Insider Build and  when either person is using any other version along with at least one using the Insider build. The (what appear to be) ansi escape codes appear ONLY when a terminal is set to `read/write` and when in IRB.  The problem does not occur for either person when the terminal is in `read only` and either person is in IRB. Any additional thoughts would be greatly appreciated, thank you.
