### ISSUE TITLE
Azure edge robotics webview not loading

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#123318]
Hello All,
I'm in the Azure Edge Robotics team, maintaining the [VSCode extension for ROS](https://marketplace.visualstudio.com/items?itemName=ms-iot.vscode-ros). We are hitting this issue as well for our [Robot Visualizer](https://github.com/ms-iot/vscode-ros/issues/443). It seems to be related to a move from vscode-resource to https?

For example, we have a workspace rooted at c:\ws\tb, which has sources including stl files.
We convert this to a file URI, then to a webview URI. Before the update, it would look something like:
`vscode-resource://c%3A/ws/tb/src/turtlebot3/turtlebot3_description/meshes/wheels/right_tire.stl`

but now looks like this:

```
https://47c83f32-da7e-4be3-9b90-42735e27223e.vscode-webview-test.com/vscode-resource/file///c%3A/ws/tb/src/turtlebot3/turtlebot3_description/meshes/wheels/right_tire.stl 
```

The `file///` does not look right to me.

_Originally posted by @ooeygui in https://github.com/microsoft/vscode/issues/122951#issuecomment-834551008_

**Comment by mjbvz** [comment]
The uri changes are expected, see https://code.visualstudio.com/updates/v1_56#_service-workers-now-used-to-load-resource-in-webview

I think your extension is hardcoding some assumptions about the result of `asWebviewUri`:
 
https://github.com/ms-iot/vscode-ros/blob/0de53b6d3b3dda1067930cf91a455c1a8928fb5d/src/urdfPreview/preview.ts#L132

I don't know what the line is doing but it will need to be re-written. We only say  that `asWebviewUri` returns something that can be used in webviews, not the specific structure of the results

**Comment by ooeygui** [comment]
@mjbvz Thank you for the doc pointer. I have updated my code, but still am getting file not found. when attempting to load the new URI. We are using a module which makes some assumptions about the URI, so we do have to modify the return value slightly. (internally it composes its own url by combining a prefix path with the passed in one. So we split the path we pass in. I changed this code to https: )

**Comment by mjbvz** [comment]
Please share a branch with your code changes

**Comment by vincentjocodes** [comment]
We are having similar problems. We are not able to load `.png` or  `.svg` from <img> elements from our Angular application. We do not hardcode `vscode-resource` or `vscode-webview-resource` anywhere in our codebase.

**Comment by mjbvz** [comment]
@vincentjocodes  Please share minimal example code that demonstrates the issue

**Comment by mjbvz** [comment]
@ooeygui Sounds like you came up with a code fix on the extension side? Should we close this issue then?

**Comment by mjbvz** [comment]
@glouischandra Is it trying to load the images inside an iframe in the webview? Is the script running in one?

**Comment by glouischandra** [comment]
Its trying to load an image inside the webview, there's no additional iframe within the webview (not sure if this is what you're asking for). The script is injected inside webview's body and the source code is located within the extension project itself, like: https://d80db2d4-a744-4854-98f7-b90d109f8c44.vscode-webview-test.com/vscode-resource/file///Users/..../dist/webview/main.js.

This script is an angular application. Interestingly if I just create the same <img src=".../logo.png"> with the same exact URL that angular generated, ServiceWorker seems to pick it up just fine and downloaded the image.

**Comment by ooeygui** [comment]
We have a code fix in flight which corrects this. I'll be pushing a release today.

**Comment by glouischandra** [comment]
@mjbvz Here's a minimal repro for the angular webview issue: https://github.com/glouischandra/vscode-156-minimal-repo

**Comment by glouischandra** [comment]
@mjbvz any update on the investigation?

**Comment by mjbvz** [comment]
Can you please slim that example down? Looks like there's a lot of stuff about angular and other components in there right now

**Comment by ooeygui** [comment]
We can close this issue now - we released a fix for the ROS VSCode extension.

**Comment by mjbvz** [comment]
Thanks. Let me know if something still doesn't seem to be working correctly on the VS Code side

**Comment by glouischandra** [comment]
@mjbvz will do, I'll file a separate bug once we slim the example down.
