### ISSUE TITLE
vscode freezes every 3-5minutes randomly

### ISSUE THREAD

**Issue by alexbi29** [microsoft/vscode#124723]
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (2 wks ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.5.0

remote ssh to linux host.

only extensions installed: remote-ssh, c/c++

Log (Window) shows this:

```
[2021-05-26 19:46:58.540] [renderer4] [warning] {}
[2021-05-26 19:47:03.024] [renderer4] [warning] {}
[2021-05-26 19:48:00.725] [renderer4] [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7277)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7296)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
...
```

**Comment by dbaeumer** [comment]
@alexdima @jrieken do we still have means to map locations in minified code to un-minified code?

**Comment by jrieken** [comment]
Pretty sure it's this: [_entries](https://github.com/microsoft/vscode/blob/8aff878db2542eea2dfb571c8bb485118bbb3113/src/vs/base/common/map.ts#L500-L500) but I don't know yet how/why

**Comment by alexbi29** [comment]
let me know if i can help debug this. It also seem to happens across platforms - we have some vscode on windows and this issue is there too. Uninstalled all plugins except remote-ssh and it's still happening.

**Comment by jrieken** [comment]
@alexbi29 Can you provide the whole call-stack? Like, I wonder if `...` cut off the actual start of the call-stack

**Comment by alexbi29** [comment]
@jrieken don't think so (see below). Symptoms are: it freezes for like 10-15sec then unfreezes for 2 seconds and then another freeze for 2 seconds and after that it's useable again. Removed all plugins (except remote-ssh) and it is still happening.

[2021-05-28 00:20:55.960] [renderer1] [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7277)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7296)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
[2021-05-28 03:46:40.112] [renderer1] [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7277)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7296)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
[2021-05-28 03:55:07.217] [renderer1] [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7277)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7296)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at l._entries (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)

**Comment by jrieken** [comment]
Can you try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)? I am planning to add some more logging to understand the root case and Insiders would be an easy way for you to report this

**Comment by alexbi29** [comment]
Still getting the same freezes w/ insiders:

`[2021-05-28 17:09:10.464] [renderer1] [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7277)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7296)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
    at _entries.next (<anonymous>)
    at r._entries (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62:7383)
`

**Comment by jrieken** [comment]
Ok, thanks for checking. I have pushed some logging an tomorrows (June 1st) insiders should be printing a message/trace like this `potential CYCLE detected`. Please check the console for that - it likely won't freeze anymore

**Comment by worstpractice** [comment]
@jrieken I'm having the same issue currently, on Windows 10.

I'm on latest stable of everything (AFAIK) on this machine.

**Comment by jrieken** [comment]
ping to check the console for the `potential CYCLE detected` message and its trace

**Comment by alexbi29** [comment]
Freeze just happened again, but log is different this time. May not be related:
`
[2021-06-02 14:17:59.643] [renderer1] [warning] {}
[2021-06-02 14:18:50.556] [renderer1] [info] [remote-connection][ExtensionHost][f166f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-06-02 14:18:50.556] [renderer1] [info] [remote-connection][ExtensionHost][f166f…][reconnect] resolving connection...
[2021-06-02 14:18:50.556] [renderer1] [info] [remote-connection][ExtensionHost][f166f…][reconnect] connecting to 127.0.0.1:58774...
[2021-06-02 14:18:50.739] [renderer1] [info] [remote-connection][ExtensionHost][f166f…][reconnect] reconnected!
`

Also see bunch of errors in "Log (Remote Extension Host)":
`
[2021-06-02 13:17:09.131] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-06-02 13:17:09.132] [exthost] [error] Canceled: Canceled
	at FoldingRangeProvider.<anonymous> (/home/user/.vscode-server-insiders/extensions/ms-vscode.cpptools-1.4.0/dist/main.js:35700:23)
	at Generator.next (<anonymous>)
	at fulfilled (/home/user/.vscode-server-insiders/extensions/ms-vscode.cpptools-1.4.0/dist/main.js:35674:58)
	at runMicrotasks (<anonymous>)
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
[2021-06-02 13:19:09.061] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-06-02 13:19:09.061] [exthost] [error] Canceled: Canceled
	at FoldingRangeProvider.<anonymous> (/home/user/.vscode-server-insiders/extensions/ms-vscode.cpptools-1.4.0/dist/main.js:35700:23)
	at Generator.next (<anonymous>)
	at fulfilled (/home/user/.vscode-server-insiders/extensions/ms-vscode.cpptools-1.4.0/dist/main.js:35674:58)
`

**Comment by alexbi29** [comment]
It's happening again. Uninstalled all plugins (went to remote server and deleted .vscode-server/caches).
Don't see any logs in Log (Window) anymore. If "unresponsive window" pops up then i see this in "Log (Main)":
[2021-06-02 15:16:42.577] [main] [error] CodeWindow: detected unresponsive

Freezes are still 15-20 seconds, unfreeze for 2-3 sec and then another freeze for 2-3.

One thing that stands out - it _only_ happens right after i do a build (through tasks.json that really just calls bazel build) and click on one of the syntax errors from gcc to go to file/line.

Here's task that builds:
`
		{
			"label": "build all",
			"type": "shell",
			"command": "bazel build ...",
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
`

**Comment by jrieken** [comment]
> One thing that stands out - it only happens right after i do a build (through tasks.json that really just calls bazel build)

Oh, that good news. If it reproduces consistently, than please try to profile the renderer process. E.g start profiling, do whatever causes the freeze, stop profiling

--- 

Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.


https://user-images.githubusercontent.com/1794099/120606621-a97e0180-c44f-11eb-8e32-9fdafdc949ec.mov

**Comment by alexbi29** [comment]
@jrieken here it is
[CPU-20210603T144656.cpuprofile.zip](https://github.com/microsoft/vscode/files/6593688/CPU-20210603T144656.cpuprofile.zip)

**Comment by jrieken** [comment]
@alexbi29 with what version of VS Code is that happening? Are you still on insiders?

**Comment by jrieken** [comment]
After looking at the CPU profile, I am making a qualified guess and I say this is due to a file watching, e.g receiving a very, very large file event. The first plateau is receiving via IPC and the second plateau is `FileChangesEvent > getAdded() > getOfType() > TenarySearchTree > iterator > _entries`. The seems to eagerly retrieve all items from the change event and assuming the event is huge that will take a long time.

_the two plateaus, note that hight represent call stack depth, not CPU load_

<img width="704" alt="Screen Shot 2021-06-04 at 12 45 20" src="https://user-images.githubusercontent.com/1794099/120790803-b1af6d00-c533-11eb-8f96-d5a04b8a4509.png">


_calls to `_entries`_
<img width="471" alt="Screen Shot 2021-06-04 at 12 45 41" src="https://user-images.githubusercontent.com/1794099/120790804-b2480380-c533-11eb-9731-6b736343fa8d.png">

**Comment by jrieken** [comment]
I can work on a change to make `_entries` not use recursion anymore (to prevent the stack overflow) but it seems we shouldn't get so far...

Also adding @isidorn because `FileChangesEvent#getAdded` and friends are deprecated.

**Comment by jrieken** [comment]
> I can work on a change to make _entries not use recursion anymore (to prevent the stack overflow) but it seems we shouldn't get so far...

@alexbi29 Just to double & triple [check that](https://github.com/microsoft/vscode/issues/124723#issuecomment-854604203) that you use insiders. That has a breaker for an endless loop (in case the underlying tree structure is bad) but it actually seems to caused by pure overload...

**Comment by isidorn** [comment]
Tried to get out of using `getAdded` in the explorer but I think I could not fully do it (e.g not using it caused a performance problem in the explorer). More details here https://github.com/microsoft/vscode/issues/108165 I can also refresh my memory...

**Comment by bpasero** [comment]
I see 2 solutions:
* we get rid of the users of the deprecated methods
* we keep an array of file change events specifically for the `getUpdated` and `getAdded` that does not use the ternary search tree at all

I think we can optimize the ternary search tree but I also think that it is not the best data structure for the deprecated methods.

Thoughts?

**Comment by jrieken** [comment]
> Thoughts?

We can optimize the TST further or move off the deprecated functions but the majority of the time is actually not spend there. The first plateau is much longer and based on my understanding that just receiving data. So, I believe we should be pragmatic and the watcher process should simply not shuffle so much data into the renderer. Ideally, we can reproduce or debug or log to know how many events are send but I'd say at a certain limit we should just drop further events

**Comment by bpasero** [comment]
Yeah, the file watcher is a source of unlimited events as there is no debouncing going on and we never know how many file events are generated. At least this is running in a child process for that reason to take work off the renderer but it is true that data is still just sent into the renderer without bounds.

We can add some debouncing and throttling I guess, though finding the right number that does not cause the UI to react slow on file events is the challenge I guess. Not sure if the extension host has similar IPC debouncing @alexdima ?

**Comment by alexdima** [comment]
> Not sure if the extension host has similar IPC debouncing @alexdima ?

No debouncing for throttling reasons implemented.

**Comment by alexbi29** [comment]
@jrieken what i used to repro the issue:
Version: 1.57.0-insider (Universal)
Commit: a62df5d6c53e844bfdc50694f943c3f34b6ff50e
Date: 2021-06-03T17:36:36.265Z (22 hrs ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

it's reproducible every time i compile the code (run that task).

**Comment by jrieken** [comment]
@alexbi29 Thanks for clarifying

> it's reproducible every time i compile the code (run that task).

This would be a good change to count and log the number of file events during a period of time

**Comment by alexbi29** [comment]
@jrieken it's amazing how fast you guys move, was at msft some time ago and this kind of thing would take forever.

**Comment by alexbi29** [comment]
@bpasero I do have exclude set up, so it should not be parsing those. I suspect there's some issue in vscode related to the way bazel works w/ symlinks. I see some other inconsistencies in code browsing: when clicking on "go to definition" files are opened  from ~/.cache/bazel/... instead of workspace folders (but directly opening a file w/ command-p open it from workspace location second time). Workspace has bazel-<project> name where it stores all deps (those are simlinks in bazel) and I use multi-root workspace to link to it.
E.g.:
`
	"folders": [
		{
			"name": "nts-engine",
			"path": "../"
		},
		{
			"name": "deps",
			"path": "../bazel-engine/external/deps/source"
		}
	],
	"settings": {
		"files.exclude": {
			"**/.git": true,
			"**/__pycache__": true,
			"**/bazel-*": true,
			"vendor/": true,
			"**/bin/": true
		},
...
        }
`

**Comment by bpasero** [comment]
@alexbi29 if you run VSCode with `--verbose`, we log every file watcher file event that we encounter with the full path. This would be a way to figure out if the exclude pattern uses a different path than the ones we actually encounter, can you try?

**Comment by jrieken** [comment]
> Tried to get out of using getAdded in the explorer but I think I could not fully do it (e.g not using it caused a performance problem in the explorer). More details here #108165 I can also refresh my memory...

Looking at how you use `getAdded`: Would it make sense to retrieve the changes one by one through an iterator and not as wholesome array? It seem that you only set a boolean ([`shouldRefresh`](https://github.com/microsoft/vscode/blob/f7ffe364a770f7a08523a9df4529a6e64fbe3402/src/vs/workbench/contrib/files/browser/explorerService.ts#L80)) and that don't actually need all changed/added files at once

**Comment by jrieken** [comment]
fyi @bpasero it seems that [getUpdated](https://github.com/microsoft/vscode/blob/466dd4e490e5c27b95f5451673f0dd5c8f0a2c99/src/vs/platform/files/common/files.ts#L784-L784) is unused and ready for removal

**Comment by bpasero** [comment]
@jrieken done, I think in my usage here:

https://github.com/microsoft/vscode/blob/903e219ccb8f8a0bccf8ffce33b79cb66bd9a4f4/src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts#L75-L78

I could also use a iterator approach if that helps.

**Comment by jrieken** [comment]
> I could also use a iterator approach if that helps.

I don't see an "early return" condition as in the explorer so I don't think so. Tho, maybe the text editor view state knows what it is looking for and than things can be turned around

**Comment by jrieken** [comment]
It only allows to change the API to return an iterable but it doesn't help with this performance issue

**Comment by bpasero** [comment]
Yeah I would still add some debouncing on the event creation side in any case.

**Comment by jrieken** [comment]
I have pushed a change to avoid recursion when iterating over the TST. This should prevent the stack overflow due to too much data. The default call stack size is `11384` which means we are facing path more segments than that...

**Comment by bpasero** [comment]
@alexbi29 is your project open source, is there a way for me to replay your steps to see it hang?

**Comment by bpasero** [comment]
Pushed a change to iterate over the ternary search tree and avoid having to create an array. 

@isidorn please review https://github.com/microsoft/vscode/commit/a0a9141869093495444eb4c107da6f5c173d456d#diff-20f01ca14a8b2d9406b1c703845f3d86d3909a8451226b32bf2f9d382f196ce0

**Comment by isidorn** [comment]
@bpasero the change looks good, thanks for doing it 👍

**Comment by alexbi29** [comment]
Sorry for the delay. Enabled --verbose on the most recent insiders.
I see tons of events that add tons (~100-500k) of files after each compilation (event if it does not lead to any changes):
`
..........

[2021-06-11 09:48:43.607] [remoteagent] [trace] [File Watcher (nsfw)]  >> normalized [ADDED] /home/user/src/vertex/bazel-vertex/.vscode
[2021-06-11 09:48:43.607] [remoteagent] [trace] [File Watcher (nsfw)]  >> normalized [ADDED] /home/user/src/vertex/bazel-vertex/alpha
[2021-06-11 09:48:43.607] [remoteagent] [trace] [File Watcher (nsfw)]  >> normalized [ADDED] /home/user/src/vertex/bazel-vertex/bin
[2021-06-11 09:48:43.607] [remoteagent] [trace] [File Watcher (nsfw)]  >> normalized [ADDED] /home/user/src/vertex/bazel-vertex/blogAnalyzer
[2021-06-11 09:48:43.607] [remoteagent] [trace] [File Watcher (nsfw)]  >> normalized [ADDED] /home/user/src/vertex/bazel-vertex/cdef
....
[2021-06-11 10:05:59.117] [remoteagent] [trace] [File Watcher (nsfw)]  >> normalized [ADDED] /home/user/src/vertex/bazel-vertex/external/vendor/packages
[2021-06-11 10:05:59.117] [remoteagent] [trace] [File Watcher (nsfw)]  >> normalized [ADDED] /home/user/src/vertex/bazel-vertex/external/vendor/version
[2021-06-11 10:05:59.117] [remoteagent] [trace] [File Watcher (nsfw)]  >> normalized [CHANGED] /home/user/src/vertex/bazel-out/_tmp/actions
[2021-06-11 10:05:59.117] [remoteagent] [trace] [File Watcher (nsfw)]  >> normalized [CHANGED] /home/user/src/vertex/bazel-out/volatile-status.txt
[2021-06-11 10:05:59.117] [remoteagent] [trace] [File Watcher (nsfw)]  >> normalized [CHANGED] /home/user/src/vertex/bazel-out/stable-status.txt

`

bazel-vertex is created by bazel (https://bazel.build/), looks like it changes somehow every time i run compilation (even if it does not lead to any changes).

Structurally bazel-vertex is a symlink to bazel cache, but I don't see symlink change across compilations:
/home/user/src/vertex/bazel-vertex -> /home/user/.cache/bazel/_bazel_user/785163ba30938911fdd6b18addc8a2e5/execroot/__main__

It's likely that bazel first cleans up everything in current dir (and deletes bazel-vertex simlink) and then re-creates it. Even though underlying structure does not change vscode removes and then re-adds all files there).

**Comment by bpasero** [comment]
@alexbi29 is the performance any better with todays insider build where some fixes already went in?

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
You need to configure the excludes via `files.watcherExclude`. I think our rationale initially was that `files.exclude` is only for the explorer and should not tamper with the watcher because a lot of things on top of the watcher might rely on file events being emitted properly. 

In your case, if you configure `files.watcherExclude` with those patterns it should probably be fine.

I will take a look at reproducing the hang with your instructions. Do you have a boilerplate for me to get to the build step to reproduce?

**Comment by alexbi29** [comment]
Thanks, will try files.watcherExclude now!
hmhm, you might be able to get away w/ simpler repro. Just mv some large folder to project dir and watcher should pick it up and lock vscode?

**Comment by bpasero** [comment]
@alexbi29 having a real world sample like yours would be nice, can you provide this info or is it a closed source project?

**Comment by bpasero** [comment]
@alexbi29 actually meanwhile I was able to setup `bazel` and I am compiling the examples from `bazel-vertex` and I see a couple of thousand file events emitted. That is not a lot though and does not result in any slowness in my system. Maybe you do something different.

Since you once created a CPU profile with the older version of VSCode, I am curious if you could do another trace based on this version of VSCode to compare it: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
I cannot really wrap my head around what best to do here...

**Throttle on the watcher side**
* this will not prevent a custom file system provider with spamming us with events, we can only fix it for our file watcher
* we have no way of knowing whether the renderer is ready to accept more file events, so we can only implement a stupid timeout based solution that is very static and wouldn't adapt to the renderer process
* for Windows we actually have a C# implementation that I don't really want to get into because it means to implement throttling there as well, aka we end up with 2 implementations in JS (Linux, macOS) and C# (Windows)

**Throttle in the renderer**
* this will not prevent large chunks of data being sent via IPC
* this would again be a relatively simple timeout based solution without knowing exactly whether the renderer is under heavy load or not

I tend towards just implementing the throttling in the renderer. But imho the only real solution and way out here is to change the watcher fundamentally away from a push model to a model where clients register the paths they are interested in and then we would only send those changes over the wire and would only build ternary search trees for those. Clients would not be able to register a watcher for `*.*` but would have to be specific, maybe at least indicate the file extension and root folder they are interested in.

**Comment by bpasero** [comment]
I pushed a change to throttle file events with some heuristics:
* any resource that we explicitly watch (via `IFileService#watch`) remains unthrottled because that is a good way of using the API (similar to https://github.com/microsoft/vscode/issues/126809)
* any client of the raw changes (e.g. extension host) is unthrottled, to keep existing runtime behaviour for extensions
* any change event that is not explicitly watched, may be throttled with the following rules:
  * max `500` change events at once
  * `200ms` delay before dealing with the next `500` events
  * a max cap of `30000` events (this is `12s` to catch up if full)

A warning is printed to the log in case the buffer is full and a trace message is printed if the watcher is busy catching up. I originally thought about making this more user visible, e.g. via progress message in the status bar, but I think that would be overkill.

Opened https://github.com/microsoft/vscode/issues/126809 for a overall better API for file watching in general.

**Comment by alexbi29** [comment]
sorry for being MIA. It's not open source project, unfortunately.
i still see slowdowns every time bazel compiles the code.
Things to note: in my case bazel-<project> folder contains a lot of files (500k++) - bazel pulls all project dependencies this way. Even though nothing is changed, deletion and re-creation of that symlink make vscode think it's new dir and causes it to rescan it.
One solution could be to traverse symlinks and use these as keys to avoid sending the same data over and over again if symlink is updated.

**Comment by bpasero** [comment]
@alexbi29 oh wow, this is good information. To clarify, the file system you are connected to is a SSH linux machine right? I wonder if you are seeing https://github.com/microsoft/vscode/issues/3998 possibly, which is another file watcher related performance issue.

**Comment by alexbi29** [comment]
I'm connected to linux box w/ "remote - ssh" plugin - the killer feature of vscode.
The slowdown though is on UI side of vscode.

i read through that bug. Looks like files.watcherExclude has a bug, b/c adding '**/**': true fixed it, even though i had it set up like this before (which should have taken care of bazel-*:
		"files.watcherExclude": {
			"**/.git": true,
			"**/__pycache__/": true,
			"**/mypy_cache/": true,
			"**/bazel-*": true,
			"vendor/": true,
			"**/bin/": true
		},

**Comment by bpasero** [comment]
For exclude patterns I typically recommend to use `**`, so for example `**/pycache/**` should also work.

**Comment by alexbi29** [comment]
That's what i'm using, github formatter killed **:
`
added:  '**/**': true
`
was:
`
		"files.watcherExclude": {
			"**/.git": true,
			"**/__pycache__/": true,
			"**/mypy_cache/": true,
			"**/bazel-*": true,
			"vendor/": true,
			"**/bin/": true
		}
`
