### ISSUE TITLE
Window trust with empty workspaces 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#124824]
- open an new empty window
- hover over the restriction info in the status bar says: 

> Restricted mode: Some features are disabled because this __window__ is not trusted.

- click on it
- the tab title says 'Workspace Trust` (IMO this should become Restricted Mode, also with workspaces)
![image](https://user-images.githubusercontent.com/6461412/119961152-05efa580-bfa6-11eb-9a38-6d7792f8f023.png)

- The section mentions 'In trusted window'. Good, (but should be capitalized: `Trusted Window` )
- It also mentions`16 workspace settings are not applied`. That's strange, how can there be workspace settings. Click on the link, there are no workspace settings . Also when I go to the settings page there are no workspace settings
- trust the window, reload the window, the window is restricted again

- open a new window (restricted) , use `Add folder to workspace`, choose a folder that is trusted : the window is now suddenly unrestricted

If the restrictedness is a property of the window, then the window should keep its restricted state across reloads and operations.
If the restrictedness is a property of the workspace, then it's strange that an empty window is restricted.

The loose files brought us in the direction of restricted windows. I personally like the concept. It's similar to 'Private browsing window' on browsers. But has different traits than 'restricted workspaces'.
- 'restrictedness' is a window property and does not change
-  users can decide to open the same folder in restricted mode and in unrestricted mode. the recent history entries would reflect that. You could see the same input once with and without the `[Restricted]` tag.
- we can add a top level menu `File` entry `New Restricted Window`

- On 'Open Folder' we can still deduct based on the folder/workspace path whether to open a restricted or a normal window. But IMO that needs to be decided 'before' the window is opened (or before the window starts the ext host)

**Comment by sbatten** [comment]
I think the only remaining item to fix here is the capitalization.

**Comment by lszomoru** [comment]
Workspace trust editor capitalisation fixed with 67565c0ffcfa7adcf4fe565e26c6600d03d73f91

**Comment by lszomoru** [comment]
I have moved the throughs around `restricted mode` to #126050.

**Comment by rzhao271** [comment]
I still see the following

>open a new window (restricted) , use Add folder to workspace, choose a folder that is trusted : the window is now suddenly unrestricted

I'm assuming more discussion on this is being tracked in #126050

The other parts LGTM
