### ISSUE TITLE
Relative paths not opened correctly via CLI

### ISSUE THREAD

**Issue by nolanbconaway** [microsoft/vscode#125136]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.56.2
- OS Version: macos big sur

I am unable to find any record of someone else having this problem! Can someone point me to how I can start to debug this issue?

Steps to Reproduce:

1. Make a file with some text in it:

```
$ echo 'test' > file.txt
```

2. When using a relative path, the file opened is blank: 

```
$ code file.txt 
```

3. When opened using an absolute path, the text is correctly rendered:

```
$ code $(pwd)/file.txt
```

One hint is that when i edit the file (after opening with a relative path), vscode displays this error:

![image](https://user-images.githubusercontent.com/1770896/120363775-8a119800-c2da-11eb-8f99-e72392b900a8.png)

Presumably, the code CLI is not using the cwd to open the relative path, and is assuming file.txt is a file in the filesystem root.

I know this is super weird and am very eager to debug! Has anyone seen anything like this before? I have already tried disabling extensions, looking into logfiles etc.

**Comment by bpasero** [comment]
@nolanbconaway do you by chance have a `VSCODE_CWD` environment defined?

**Comment by nolanbconaway** [comment]
Aha! I do! How did that get set?!

**Comment by bpasero** [comment]
@nolanbconaway I would like to understand how this variable can end up in your terminal environment. We do set it from application code here:

https://github.com/microsoft/vscode/blob/e475cf038bc285025ceece69702af11f9e200598/src/bootstrap-node.js#L25-L25

If you have any clues how you got there, please let me know. Also: I assume you are not using the integrated terminal right?

//cc @Tyriar @meganrogge for terminal experts, maybe you have an idea how something we write from JavaScript can end up in the terminal environment.

**Comment by Tyriar** [comment]
The terminal environment code is a little complex, but except for cases like `strictEnv` being set for extension terminals or `$VSCODE_CWD` getting contributed via an extension, this variable is meant to be sanitized in the terminal's process:

https://github.com/Microsoft/vscode/blob/1248ddadb8ce4fa9954993a42706ad51b637e579/src/vs/base/common/processes.ts#L104-L126

**Comment by bpasero** [comment]
@Tyriar yeah I was also thinking that any `VSCODE_` prefixed environment variable would not make it to the integrated terminal, but would be good to ensure we have not regressed.

However, here I actually think, people use the external (OS) terminal and still see `VSCODE_CWD` set, which I cannot explain how that can happen from a process launched by the terminal.

**Comment by nolanbconaway** [comment]
Can confirm! This issue concerned using an external terminal to launch a vscode window!

**Comment by bpasero** [comment]
@nolanbconaway is it at all reproducible for you somehow?

**Comment by Tyriar** [comment]
I see we only sanitize the external terminal env on Windows.

**Comment by nolanbconaway** [comment]
I think so! If I remove the unset from my zsh profile then the issue arises again, so it's reproducible in that respect. Is that what you mean?

**Comment by bpasero** [comment]
@nolanbconaway how do you open terminals for using them? via a command VSCode provides or via Finder/Dock?

**Comment by nolanbconaway** [comment]
@bpasero Usually the Finder/Dock variety (specifically, entering the letter "t" into spotlight and hitting enter without looking).

**Comment by bpasero** [comment]
@nolanbconaway I cannot explain this issue then. If you are always opening terminals from the dock, none of the environment variables that VSCode defines should be there.

Here is what I think can happen (correct me if you do something different):
* you open VSCode (either dock or terminal, doesn't matter)
* at one point you open a external terminal from VSCode (through some command or action)
* you type `code file.txt` in that new terminal
* it fails to recognise the current working directory
* if now you open a terminal using dock or finder and try the same (`code file.txt`) it works

**Comment by nolanbconaway** [comment]
That all sounds right (I do sometimes open terminals from vscode!), except the issue arises even when the terminal is opened externally (via FInder).

My immediate issue has been patched (via unset in zsh profile) and I'm alright to drop the concern if this is likely to be something extremely specific to my setup!

**Comment by bpasero** [comment]
> the issue arises even when the terminal is opened externally (via Finder)

I cannot explain that. A terminal that is opened via finder can only contain environment variables as configured by startup scripts (`.zshrc` et al) to my knowledge. But happy to learn how this can happen otherwise...

**Comment by nolanbconaway** [comment]
Ok cool! I'm running some grep -r to see if anyone else might be sneakily setting this variable. Thanks for all your help!

**Comment by tg90nor** [comment]
I started seeing this issue after upgrading to MacOS big sur. Even when vscode is not running, the $VSCODE_ env variables are set when I open a new terminal from the dock

**Comment by tg90nor** [comment]
I think I figured out the cause of this for me at least. I have zsh set up to auto load tmux. so when a integrated terminal in vscode is launched it creates a tmux session and the env from that somehow leaks into other tmux sessions. I just disabled tmux auto loading and the problem disappeared.

**Comment by tg90nor** [comment]
Do you by any chance use tmux inside the integrated terminal in vscode @nolanbconaway ?

**Comment by nolanbconaway** [comment]
I do not!

**Comment by bpasero** [comment]
@Tyriar maybe this is a red herring, in my testing when I run the command to open an external terminal, I do not see any of VSCodes environment variables appearing.

Meanwhile I pushed https://github.com/microsoft/vscode/commit/3759d871b643bda3be854bb35d36a1063f859a39 to make sure we never `process.chdir` on macOS/Linux, so this issue should not be present anymore.

**Comment by TylerLeonhardt** [comment]
@meganrogge @Tyriar are the verification steps in the original issue still valid/could you give some?

**Comment by meganrogge** [comment]
Yes the verification steps in the original issue are still valid @TylerLeonhardt

**Comment by meganrogge** [comment]
to verify, 
- close vscode
- open an external terminal and modify an environment variable in a repo directory starting with `VSCODE_` for example. 
- open vscode and launch an external terminal from that same repo
- confirm that the environment variable you set is not present
