### ISSUE TITLE
macOS: windows no longer open in fullscreen properly anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#125122]
Steps to Reproduce:

1. be in a fullscreen window
2. `Ctrl+R`
3. select an entry and hold `Cmd` key

=> 🐛  a new window opens but not fullscreen

//cc @sandy081

**Comment by bpasero** [comment]
@deepak1556 I cannot reproduce with Electron 12.0.4 so this seems like a regression with our Electron updates. Can you please advise?

**Comment by bpasero** [comment]
I cannot reproduce in `12.0.8` so it can only be https://github.com/electron/electron/pull/29235 or https://github.com/electron/electron/pull/29226

**Comment by bpasero** [comment]
Pushed a workaround to open in fullscreen but there is still an issue that the window does not seem to create a space on the desktop.

**Comment by intellild** [comment]
Seems I hit github's bug
I synced the main branch to my fork and it shows that I pushed a commit referenced this issue
Please ignore it

**Comment by ryenus** [comment]
One more case with native tabs on macOS:

```
	"window.nativeTabs": true,
	"window.titleBarStyle": "native",
```

1. Open vscode as a normal window on Desktop
2. Press <kbd>Cmd + Option + F</kbd> to make it fullscreen with its own Space
3. Press <kbd>Cmd + Option + N</kbd> to open a new window
4. With 1.56, the new window would just open as a native tab, merged with existing vscode window, but with 1.57.0 there're several issues:
   a. the native tab disappears, leaving only the black background
   b. a separate blank Space is created without anything there, just the black background.

If the step 2 above is skipped, the new window opens just fine on the Desktop, merged with the existing one.

**Comment by ryenus** [comment]
> One more case with native tabs on macOS:
> 
> ```
> 	"window.nativeTabs": true,
> 	"window.titleBarStyle": "native",
> ```
> 
> 1. Open vscode as a normal window on Desktop
> 2. Press Cmd + Option + F to make it fullscreen with its own Space
> 3. Press Cmd + Option + N to open a new window
> 4. With 1.56, the new window would just open as a native tab, merged with existing vscode window, but with 1.57.0 there're several issues:
>    a. the native tab disappears, leaving only the black background
>    b. a separate blank Space is created without anything there, just the black background.
> 
> If the step 2 above is skipped, the new window opens just fine on the Desktop, merged with the existing one.

@deepak1556 The above issue still exists after https://github.com/microsoft/vscode/commit/3caebff71e514ece73b125468881d102e767ee4d

And the same with the latest [main branch at time of writing this](https://github.com/microsoft/vscode/commit/1750b2b231b).

**Comment by deepak1556** [comment]
@ryenus thanks for checking, can you extract it to a new issue. The original issue reported here is fixed with the latest insiders.

**Comment by deepak1556** [comment]
@ryenus I just tried yours steps and unable to reproduce the issue. Can you check if I am missing anything.

![recording](https://user-images.githubusercontent.com/964386/123414953-63592100-d569-11eb-83b2-4eb236c513d0.gif)
