### ISSUE TITLE
[Extension Host] extension activation failed TypeError

### ISSUE THREAD

**Issue by mage1k99** [microsoft/vscode#125381]
Does this issue occur when all extensions are disabled?: No
Reason for issue : Recent update for jupyter extension (v2021.6.902307158)

- VS Code Version: 1.57.0-insider
- OS Version: Windows 10 (10.0.199042)
```
Version: 1.57.0-insider (user setup)
Commit: c324c61ad572be43a8696780e1aba3c1a2c46eee
Date: 2021-06-02T17:38:06.137Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```
Steps to Reproduce:

1. Installed the recent insiders update.
2. Python extension is not working anymore causing extension host to fail
3. When Inspecting console, found that its due to python extension by microsoft which includes jupyter notebook extension
4. Here is the logs
```log
Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
onDidChangeNotification @ workbench.desktop.main.js:741
(anonymous) @ workbench.desktop.main.js:741
fire @ workbench.desktop.main.js:60
addNotification @ workbench.desktop.main.js:741
notify @ workbench.desktop.main.js:1871
(anonymous) @ workbench.desktop.main.js:1824
_showMessage @ workbench.desktop.main.js:1824
$showMessage @ workbench.desktop.main.js:1824
_doInvokeHandler @ workbench.desktop.main.js:1831
_invokeHandler @ workbench.desktop.main.js:1831
_receiveRequest @ workbench.desktop.main.js:1831
_receiveOneMessage @ workbench.desktop.main.js:1831
(anonymous) @ workbench.desktop.main.js:1831
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
D @ workbench.desktop.main.js:2927
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188

workbench.desktop.main.js:62 [Extension Host] extension activation failed TypeError: this.vscodeNotebook.onDidOpenNotebookDocument is not a function
	at new E (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:90:287467)
	at Object.t.resolveInstance (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:263462)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262667
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:263232)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262667
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:263232)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262667
	at Object.t.resolve (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262930)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:254027
	at e._get (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:253793)
	at e.get (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:252505)
	at e.dynamicValue (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:265671)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262156
	at c (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:261202)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262096
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:261615
	at Array.map (<anonymous>)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:261587
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:263232)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262667
	at Object.t.resolve (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262930)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:254027
	at e._get (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:253793)
	at e.get (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:252505)
	at a.get (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:90:516226)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:246130
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:37:826464
	at async t.activate (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:37:826151)
	at async Promise.all (index 0)
	at async Promise.all (index 101)
	at async Promise.all (index 1) (at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:37:826983)
```

**Comment by rebornix** [comment]
@mage1k99 does it work after another window reload?

**Comment by mage1k99** [comment]
no it does not, even after reload.

It only works on older versions of jupyter extension

**Comment by mage1k99** [comment]
Recent update for jupyter extension (v2021.6.902307158) causes the issue.

**Comment by mage1k99** [comment]
Hey recently updated to newer version. which ends with commit [ad2a5](20df87725d3ce4a501187f0240c2f159aa0ad2a5).

```log
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at p._tryExecuteCommand (file:///D:/Users/Mag/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///D:/Users/Mag/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}
```

**Comment by espenfjo** [comment]
I'm getting the same. 

```
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at p._tryExecuteCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}```

MacOS, Python3.9, Pylance, daily channels on everything.

**Comment by espenfjo** [comment]
Some logs from the `Python` output.

```
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotification'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'AlwaysDisplayTestExplorer - experiment'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - control'
User belongs to experiment group 'CustomEditorSupport - control'
Python interpreter path: /usr/bin/python3
Starting Pylance language server.
Error 2021-06-03 20:38:02: Starting language server, Class name = r, completed in 1ms, has a falsy return value, , Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:78:180756)
    at new a (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:178815)
    at new y (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:446239)
    at r.startLanguageServer (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:240168)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error 2021-06-03 20:38:02: Failed to start language server, Class name = r, completed in 322ms, has a falsy return value, Arg 1: <Uri:/Users/xxxx/Sources/pyyaledoorman/pyyaledoorman/device.py>, Arg 2: {"sysPrefix":"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8","envType":"Unknown","envName":"","envPath":"","path":"/usr/bin/python3","architecture":3,"sysVersion":"3.8.2 (default, Apr  8 2021, 23:19:18) \n[Clang 12.0.5 (clang-1205.0.22.9)]","version":{"raw":"3.8.2","major":3,"minor":8,"patch":2,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.8.2 64-bit"}, Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:78:180756)
    at new a (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:178815)
    at new y (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:446239)
    at r.startLanguageServer (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:240168)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error 2021-06-03 20:38:02: TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:78:180756)
    at new a (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:178815)
    at new y (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:446239)
    at r.startLanguageServer (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:240168)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-03 20:38:02: Failed to activate language server, Class name = a, completed in 324ms, has a falsy return value, Arg 1: <Uri:/Users/xxxx/Sources/pyyaledoorman/pyyaledoorman/device.py>, Arg 2: {"sysPrefix":"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8","envType":"Unknown","envName":"","envPath":"","path":"/usr/bin/python3","architecture":3,"sysVersion":"3.8.2 (default, Apr  8 2021, 23:19:18) \n[Clang 12.0.5 (clang-1205.0.22.9)]","version":{"raw":"3.8.2","major":3,"minor":8,"patch":2,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.8.2 64-bit"}, Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:78:180756)
    at new a (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:178815)
    at new y (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:9:446239)
    at r.startLanguageServer (/Users/xxxx/.vscode-insiders/extensions/ms-python.python-2021.6.897246044-dev/out/client/extension.js:59:240168)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
> conda --version
```

**Comment by espenfjo** [comment]
Seems like the python extension is currently broken. Maybe because of ac05ae7b6f069ed696d435ec3146219d28478420 thats not taken into account yet.

**Comment by espenfjo** [comment]
Seems to already be fixed in the python extension in https://github.com/microsoft/vscode-python/commit/cd8f4d3b5c8b842dba373470734dd7d02a393680

**Comment by rebornix** [comment]
Fixed in extensions.

**Comment by mage1k99** [comment]
Still not working, updated just now commit : [64015](387e2f39ebbbf50d4b488f900b2a745972764015)

Uninstalled and installed python, pylance, intellicode

### Python extension log
```
We encountered an issue starting the language server. Reverting to Jedi language engine. Check the Python output panel for details.
Error 2021-06-04 12:18:20: Failed to activate language server, Class name = a, completed in 2ms, has a falsy return value, Arg 1: <Uri:d:\Documents\fossfreaks\0saa\saalocal\.vscode\settings.json>, Arg 2: {"architecture":3,"path":"d:\\Documents\\fossfreaks\\0saa\\saalocal\\venv\\Scripts\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.2","major":3,"minor":8,"patch":2,"prerelease":[],"build":[],"version":"3.8.2"},"sysVersion":"3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]","sysPrefix":"d:\\Documents\\fossfreaks\\0saa\\saalocal\\venv","fileHash":"659f08a3a5adbb3789875ea46aeb329c21134c552bd75abcf9ffde8cc710f444902f78301e296a215ccf071fbd9b94f1567caa9b47d6985c3006775282d97e9d","envName":"venv","type":"Venv","displayName":"Python 3.8.2 64-bit ('venv')"}, Return Value: undefined [TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
	at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\Mag\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:78:180874)
	at new a (c:\Users\Mag\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:183978)
	at new t.NotebookMiddlewareAddon (c:\Users\Mag\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:178815)
	at new y (c:\Users\Mag\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:440208)
	at r.startLanguageServer (c:\Users\Mag\.vscode-insiders\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:240168)] {
  vslsStack: [ CallSite {}, CallSite {}, CallSite {}, CallSite {}, CallSite {} ]
}

```

### Intellisense logs

```
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at p._tryExecuteCommand (file:///D:/Users/Mag/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3360)
    at file:///D:/Users/Mag/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1809:3241
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error while activating Python: {}
```

**Comment by mage1k99** [comment]
Installing Insiders version of python fixes
