### ISSUE TITLE
Mac OS System Keyboard Shortcuts Occasionally Ignored

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#125932]
Issue Type: <b>Bug</b>

VSCode windows that have been open for an extended period of time will occasionally stop responding to system keyboard shortcuts on Mac OS such as command+m for minimizing windows. While this is happening other windows may be unaffected and I can still perform the commands via the menu-bar. 

VS Code version: Code 1.56.2 (Universal) (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.04GB free)|
|Process Argv|--crash-reporter-id ed50f89e-497f-43cd-86f3-a73119f730ed|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.1.0
vscode-css-modules|cli|0.2.3
vscode-eslint|dba|2.1.20
vscode-dash|dee|2.4.0
find-related|eam|0.9.0
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.4.0
vscode-open-in-application|fab|1.0.6
vscode-firefox-debug|fir|2.9.4
vscode-jest-runner|fir|0.4.39
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.26.0
go|gol|0.25.1
vscode-env|Iro|0.1.0
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|1.6.4
graphql-for-vscode|kum|1.15.3
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.10.0
vscode-pylance|ms-|2021.6.1
jupyter|ms-|2021.6.832593372
cpptools|ms-|1.4.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4360
debugger-for-chrome|msj|4.12.12
mdx|sil|0.1.0
vscode-quick-scope|ska|0.2.0
reveal|smu|1.2.7
swdc-vscode|sof|2.5.15
vscode-stylelint|sty|0.86.0
sass-indented|syl|1.8.16
jest-snapshot-language-support|tle|1.1.1
vscode-terminal-here|Tyr|0.2.4
vscodeintellicode|Vis|1.2.14
vim|vsc|1.21.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.14

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517:30312825

```

</details>

**Comment by alexdima** [comment]
@deepak1556 `cmd+m` is not handled by us in JS at all. It is all handled directly by the OS / Electron.

**Comment by trevoryao** [comment]
having the same issue on mac on version 1.60.0 running macOs 11.5.2 with i9-9980HK @ 2.4 GHz.

**Comment by teki** [comment]
I think VS Code stops processing all MacOS menu shortcuts. For me this manifests by ctrl+space stopping to show the emoji picker. But when in this state cmd+m stops working too.

My guess is that events are not reaching the system toolbar.

I don't know how this is handled, but have the same issue with Google Docs in Chrome. In the document editor the emoji picker regularly stops working, but it keeps working in the comment input box. So maybe js somehow stop propagating this events. (like they don't match some built in keyboard shortcut table and they are just stopped before reaching the system toolbars)

**Comment by alexdima** [comment]
On my machine, <kbd>cmd</kbd>+<kbd>M</kbd> works. Here is what I see:
```
[info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
[info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
[info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: KeyM, keyCode: 77, key: m
[info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: KeyM, keyCode: 43 ('M')
[info] [KeybindingService]: | Resolving meta+[KeyM]
[info] [KeybindingService]: \ No keybinding entries.
```

I am assuming this works because "No keybinding entries." is printed. That means there are no keybindings assigned to <kbd>cmd</kbd>+<kbd>M</kbd>, so on our side we don't call `e.preventDefault()` or `e.stopPropagation()`, and then the even reaches Electron, who can act on it and minimize the window.

When <kbd>cmd</kbd>+<kbd>M</kbd> is not working for you, could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding.
* check what VS Code detects and what command is invoked.

Feel free to paste here the output.

**Comment by teki** [comment]
@alexdima  I have this in the log:
```
[2021-09-06 19:05:10.223] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: MetaLeft, keyCode: 91, key: Meta
[2021-09-06 19:05:10.224] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: MetaLeft, keyCode: 57 ('Meta')
[2021-09-06 19:05:10.224] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-09-06 19:05:10.870] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [meta], code: KeyM, keyCode: 77, key: m
[2021-09-06 19:05:10.870] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [meta], code: KeyM, keyCode: 43 ('M')
[2021-09-06 19:05:10.871] [renderer1] [info] [KeybindingService]: | Resolving meta+[KeyM]
[2021-09-06 19:05:10.871] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
[2021-09-06 19:05:11.372] [renderer1] [info] [KeybindingService]: + Storing single modifier for possible chord meta.
[2021-09-06 19:05:11.674] [renderer1] [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```
The window is not hiding.

**Comment by alexdima** [comment]
Thanks for answering so quickly. Form our (JS) keybindings system, I can confirm that we see the keyboard event, and we do nothing with it. That is the same like on my mac, where it is working. That is what makes me believe this is an Electron issue.

I think the OP mentions that going to Window > Minimize works for them, does it also work for you? 

On my machine, when I press <kbd>cmd</kbd>+<kbd>M</kbd> I can see that the Window entry in the menu-bar gets briefly highlighted. Do you see that highlight?

**Comment by teki** [comment]
No it does not. I have to select the menu bar, then shortcuts work.

The shortcuts work when a native MacOS menu is displayed. Ex: when I click on the "More Actions ..." button in the top right corner. That brings up a native MacOS menu, CMD+M will then minimize the app.

In the meantime I got an update and it works now. The problem will likely come back later.

**Comment by diminutivesloop** [comment]
I also haven't noticed this anymore recently, so it may have been resolved by an update.

**Comment by trevoryao** [comment]
@diminutivesloop What is your version? I am having the issue still on version 1.60.0, which is the latest public release.

**Comment by diminutivesloop** [comment]
@trevoryao 1.60.0. It's certainly possible it's happened and I've just forgot.

**Comment by diminutivesloop** [comment]
Just happened again for me on 1.62.2.
