### ISSUE TITLE
Jumps to start of cell on execution

### ISSUE THREAD

**Issue by kuelumbus** [microsoft/vscode#126259]
## Environment data

Version: 1.58.0-insider
Commit: e1161be26874f0d39a5b9cdeb2c5fbfd4f83bb80
Date: 2021-06-14T05:13:48.044Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-74-generic snap

-   Jupyter Extension version (available under the Extensions sidebar): v2021.7.935223353
-   Python Extension version (available under the Extensions sidebar): v2021.7.922878407-dev
-   OS (Windows | Mac | Linux distro) and version: L
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry
-   Jupyter server running: Remote

## Expected behaviour

After the execution has finished, the window position jumps to the start of the executed cell. Would be great if you can deactivate this.

## Actual behaviour

![jump](https://user-images.githubusercontent.com/44866753/121910063-84fe1100-ccfc-11eb-8329-911283580f98.gif)

## Steps to reproduce:

<details>

<p>

```































































































print('a')
```

</p>
</details>

**Comment by kuelumbus** [comment]
"Deselecting" the cell (press ESC when cursor is in a cell) also jumps to the beginning of the cell.

**Comment by roblourens** [comment]
Why does the editor lose focus after executing the cell in jupyter but not github-issues, is the extension forcing that?

**Comment by roblourens** [comment]
What I fixed

- Put the cursor at the bottom of a long cell where the top of the cell is out of the viewport
- Press esc
- The notebook should not scroll up to the top of the cell

**Comment by kuelumbus** [comment]
This is not fixed for me. It still jumps to the beginning of the cell. 

Version: 1.58.0-insider
Commit: d54f7e1f6c1290fe27e2397eca509d0e0728272e
Date: 2021-06-22T07:15:45.422Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.109-26091-g577602338376

**Comment by roblourens** [comment]
The specific thing I fixed is fixed for me. What I see in jupyter is that when I execute a cell, the editor loses focus and jumps to the bottom (not the top) of the cell. Is jupyter doing something special when I execute a cell @DonJayamanne?

**Comment by kuelumbus** [comment]
For me, it sometimes jumps to the bottom and sometimes to the top of the cell now. Would be great if this can be fixed/deactivated.

**Comment by IanMatthewHuff** [comment]
@kuelumbus If you don't mind what are you using to trigger the execution? Currently when I'm at the bottom of a super long cell, then ctrl+enter executes the cell, and drops the output to the bottom. But shift-enter, executes, selects the next cell, but then jumps the viewport to the top of the previously selected cell. I'm also seeing some odd viewport placement when moving up in the cells list from a previous cell to a really long cell like the one you have.

**Comment by roblourens** [comment]
> Currently when I'm at the bottom of a super long cell, then ctrl+enter executes the cell, and drops the output to the bottom

I see that in jupyter but not github-issues, so can you help me figure out if the jupyter extension is doing different here?

**Comment by kuelumbus** [comment]
@IanMatthewHuff  Seems ctrl + enter, shift + enter, alt +enter, super + enter jump mostly to the bottom (sometimes to top if no output or if the top of the cell is visible?). BTW, which shortcut should I use?

Why is there repositioning at all? For example, if I execute long notebooks with `run all`, I see wild jumps.

**Comment by IanMatthewHuff** [comment]
@roblourens Yup. I'll reactivate and assign to myself. Will look into it this morning.

**Comment by roblourens** [comment]
We also try to reveal the cell when it gets executed, it's possible that we don't do the right thing there

**Comment by kuelumbus** [comment]
I still see jumps after the executions finish. Is there anything I can do to deactivate this?

**Comment by roblourens** [comment]
The remaining issue is just from us trying to reveal as much of the cell/range as possible when executing, https://github.com/microsoft/vscode/commit/b95cde5113a65d9e54438819563467d336d7de0c

@rebornix why move my view when I execute a cell?

**Comment by rebornix** [comment]
@roblourens  we wanted that for interactive window but apparently I didn't check that new flag.
