### ISSUE TITLE
Terminal Scroll Issue

### ISSUE THREAD

**Issue by AmericanY** [microsoft/vscode#126709]
Hello,

if i did ran a code within the terminal and scrolled up to view some output and then re-ran the code again, I noticed that i need to scroll down each time!

How can i let vscode scroll to end of output each time ?

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by AmericanY** [comment]
@meganrogge Thanks for your reply.

Here's my current VSCode version:

```
Version: 1.58.0 (system setup)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:55.083Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

The issue still exist. do i really need to install the insiders build ?

**Comment by AmericanY** [comment]
any update please?
