### ISSUE TITLE
Termial editor tab icon does not render initially

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#127109]
Steps to Reproduce:
1. Create a terminal editor
2. Realize there's no icon
3. Open a regular terminal
4. 🎉 Icon appears

![recording (2)](https://user-images.githubusercontent.com/4544166/123329446-d0899980-d50a-11eb-8ecf-e650f7937c21.gif)

**Comment by Tyriar** [comment]
I think this is already fixed, correct me if I'm wrong

**Comment by lramos15** [comment]
This is not fixed, you can see in my gif I build from sources. I just built from sources again and it still repros.

**Comment by Tyriar** [comment]
Works for me after pull:

![recording (18)](https://user-images.githubusercontent.com/2193314/123337650-61a54400-d4fc-11eb-889c-8d118daf0f8d.gif)

There was this exact issue before but I fixed it in https://github.com/microsoft/vscode/commit/73f7d4d96507f4d25eddcfc70b3dd0d38998fa6a#diff-f1883fa148c75292499e7150b63a75610d76d58bb20cefff0213d1f5ec6b88fc, are you sure you pulled? @meganrogge have you seen this happen?

**Comment by lramos15** [comment]
It happens less often, but still happens. Try these steps
1. Open a terminal editor
2. Close it
3. Cmd + q to hot exit
4. Restart OSS 
5. open the terminal editor again
6. 🐛 No icon

Something else I noticed is that if you quit with a terminal editor open, it won't restore but you'll see the tab flash briefly on screen before closing.

**Comment by Tyriar** [comment]
Can repro now, thanks 👍

**Comment by Tyriar** [comment]
@meganrogge I think this is happening because TerminalService's init is lazy now so for the first time it's possible to have terminal(s) without TerminalService being initialized. This seems pretty bad, I'll have a think about how to make sure it gets initialized.

**Comment by Tyriar** [comment]
Actually scratch that, it's happening because the terminal's icon isn't set when the styles are updating. Investigation more...
