### ISSUE TITLE
Tasks dependson/presentation group order

### ISSUE THREAD

**Issue by roa-nyx** [microsoft/vscode#128500]
Issue Type: <b>Bug</b>

Create a task that depends on two other tasks:

```
{
    "label": "main-task",
    "dependsOn": [
        "subtask-a",
        "subtask-b"
    ],
    "problemMatcher": []
}
```

Create two shell tasks `subtask-a`, `subtask-b`. In my case these are long-running tasks but I don't think that matters.

In both subtasks add the following:

```
"presentation": {
    "group": "main-task"
}
```

Run the `main-task` task.

Doing this opens both subtasks side by side. Up until v1.58.0 this would place the first subtask on the left panel, and the second subtask on the right. However since v1.58.0 this now places them in reverse order.

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (3.52GB free)|
|Process Argv|--crash-reporter-id 4f0cfeed-1899-4534-99dc-3679fb8c95af|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
numbered-bookmarks|ale|8.1.0
ue4-snippets|CAP|2.0.1
gitlens|eam|11.5.1
tsl-problem-matcher|eam|0.4.0
url-encode|fle|1.1.0
vscode-edit-csv|jan|0.6.0
docomment|k--|0.1.20
csharp|ms-|1.23.12
python|ms-|2021.6.944021595
jupyter|ms-|2021.8.1013163132
cpptools|ms-|1.5.1
hexeditor|ms-|1.7.1
vsliveshare|ms-|1.0.4531
debugger-for-chrome|msj|4.12.12
docthis|oou|0.8.2
vscode-gitignore-generator|pio|1.0.3
partial-diff|ryu|1.4.3

</details>

**Comment by roa-nyx** [comment]
FYI: I saw 1.58.1 was released. I updated to that, and I'm still seeing the same issue.

**Comment by roa-nyx** [comment]
Today I tried again and it worked.

Maybe the order is now determined by a race condition of some sort?

**Comment by alexr00** [comment]
@Tyriar or @meganrogge maybe you can help with this.

In tasks with a split terminal, first terminal A is created using `ITerminalService.createTerminal`.
Then, very shortly after the terminal is split using `ITerminalService.splitInstance`. 

It seem that in the past, `splitInstance` would cause the new terminal to be to the right, but now, the new terminal is to the left.

**Comment by meganrogge** [comment]
@alexr00 this was a bug and is resolved in Insider's. @roa-nyx can you pls confirm this is resolved in Insider's?

**Comment by roa-nyx** [comment]
@meganrogge apologies but since July 15th I have not been able to reproduce this issue.

If it is a race condition maybe something changed/cached/settled and now the race is in favour of the correct order?

**Comment by alexr00** [comment]
@meganrogge I think I'm still seeing it in insiders every time I run the "VS Code - Build" task. I confirmed that first terminal created ends up on the right, not the left.

**Comment by meganrogge** [comment]
ok will investigate thanks

**Comment by meganrogge** [comment]
do you expect the extension task to be on the right?

![tasks](https://user-images.githubusercontent.com/29464607/128208099-d398cb7f-f741-4f93-80a8-2ba161024f9f.PNG)

**Comment by alexr00** [comment]
Yes, I just tested it out with 1.55 and confirmed that the extension task was on the right.

**Comment by meganrogge** [comment]
I just pushed changes which combine the `splitInstance`/ `createTerminal ` functions, which seems to have resolved what must have been a timing issue here. In OSS off of main, I see the extension terminal on the right

![recording (52)](https://user-images.githubusercontent.com/29464607/128214108-a562bc61-ecfd-4b87-a8ad-e61421a55217.gif)

**Comment by meganrogge** [comment]
fixed with https://github.com/microsoft/vscode/commit/62ace4e10b797fdc5de8aefadd501144a87d35a9
