### ISSUE TITLE
DAP ContinuedEvent with allThreadsContinued=true causes selected debug session to change

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#128744]
When sending a `ContinuedEvent` with `allThreadsContinued=true`, the selected debug session resets to the first one. This does not happen without `allThreadsContinued=true`.

![Jul-15-2021 12-44-08](https://user-images.githubusercontent.com/1078012/125782700-bf579204-9119-44c7-a8b0-a5a19f66c884.gif)

To repro:

- Clone MockDebug
- Add `response.body.supportsRestartRequest = true;` in `initializeRequest`
- Implement a `restartRequest` that sends a `ContinuedEvent` with `allThreadsContinued=true`:
    ```ts
    protected async restartRequest(response: DebugProtocol.RestartResponse, args: DebugProtocol.RestartArguments) {
    	this.sendResponse(response);
    	this.sendEvent(new ContinuedEvent(0, true));
    }
    ```
- Run the project
- Create a second launch config:
    ```js
    "configurations": [
    	{
    		"type": "mock",
    		"request": "launch",
    		"name": "Debug readme.md 1",
    		"program": "${workspaceFolder}/readme.md",
    		"stopOnEntry": true,
    		"trace": false
    	},
    	{
    		"type": "mock",
    		"request": "launch",
    		"name": "Debug readme.md 2",
    		"program": "${workspaceFolder}/readme.md",
    		"stopOnEntry": true,
    		"trace": false
    	}
    ]
    ```
- Start both launch configurations (this can be done one at a time)
- Select the second debug session in the debug toolbar
- Click the Restart button
- Note that the dropdown has reverted to the first session

**Comment by isidorn** [comment]
@DanTup I pushed a potential fix for this. Can you please try it out with VS Code insiders from tomorrow? thank you very much!

**Comment by DanTup** [comment]
@isidorn did the Insiders build today get delayed? I still see the issue, but it looks like current insiders is still only 7c25c174726ab969db3f99058cdf24bcfae1cfbe from around 36 hours ago.

**Comment by isidorn** [comment]
@DanTup I am not sure if that insiders had my fix. If it is not a problem can you try it with today's insiders (which I am sure has my change)?

**Comment by DanTup** [comment]
@isidorn sorry for the delay, I've been OOO. Unfortunately this still repros in:

```
Version: 1.60.0-insider
Commit: 44568e5947efa4811419e529e80fb14b7554cf61
Date: 2021-08-23T10:42:53.526Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

![Aug-23-2021 16-20-19](https://user-images.githubusercontent.com/1078012/130473167-1134a85b-1f47-408e-8b47-e9ebe8c75fe6.gif)

**Comment by isidorn** [comment]
No problem, let's reopen and I can investigate

**Comment by DanTup** [comment]
I'm not sure I understand. The behaviour differs between `allThreadsContinued=true` and `allThreadsContinued=false` even though that doesn't make any difference to any behaviour here. Also some of the debug toolbar functionality (restart, stop, hot reload) does not require a stopped session, so changing the active session when using them based on whether the session was stopped or not seems odd.
