### ISSUE TITLE
ctrl+shift+c not working with "Terminals in the editor area"

### ISSUE THREAD

**Issue by FindDefinition** [microsoft/vscode#128722]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.58.1
- OS Version:Ubuntu 20.04

Steps to Reproduce:

1. close all integrated terminal
2. open terminals in editor area by command
3. use ctrl+shift+c to copy content in that terminal

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by arunn** [comment]
@meganrogge It doesn't seem to be working in insiders build either.

**Comment by FindDefinition** [comment]
@meganrogge This bug still exists in vscode 1.59.0.
To reproduce this bug, we need to close all terminals opened in classic location.

**Comment by meganrogge** [comment]
very specific way to repro:
- create terminal editor with command, having never opened a terminal in the panel
- select text in the terminal editor -> `ctrl + shift + c`
- paste -> 🐛 nothing was copied
