### ISSUE TITLE
[Accessibility] Character is not read properly in terminal input after auto-completion

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#131295]
CC @isidorn

Found the following issue in both NVDA and JAWS.

Closely related to [#131090](https://github.com/microsoft/vscode/issues/131090#issuecomment-901131151).

Does this issue occur when all extensions are disabled?: Yes

## System Info

Version: 1.60.0-insider (system setup)
Commit: 89bbd372f459ce72e9c0b60eb3b26b924f64f62d
Date: 2021-08-20T17:51:50.560Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

## Steps to Reproduce

1. Open VSCode with NVDA.
1. Open terminal by pressing Ctrl+`.
1. Type `touch foo.txt` to create a new file.
1. Once the file is created, type `fo` and hit Tab key to auto-complete `foo.txt` in terminal input. [do NOT hit Enter yet]
1. To change the file extension, press left-arrow key to identify ".txt".

* Notes: Focused character is not read as intended. This issue occurs only after auto-completion event is triggered.

In contrast, the following usecase does not cause this issue:

1. Manually type `foo.txt` in terminal and hit left-/right-arrow keys.

* Notes: Focused character is read properly this time.

**Comment by Tyriar** [comment]
I did look into this before and it's kind of difficult because of how it's not a real textarea and we don't know what the actual prompt is. Maybe we could special case left/right to read the character if it resulted in a cursor move or something.

**Comment by Tyriar** [comment]
This is happening because when you hit tab, we clear the backing textarea which is the reason why left/right work sometimes. This is to prevent some weird state and causing a lot of confusion, we just bail out and clear it all together.

After chatting with @meganrogge I think we can move forward on this when we support shell integration (#133084) as that will enable us to know exactly what the prompt input is and we know where the cursor is so we could keep the textarea in sync.

**Comment by Tyriar** [comment]
We would also want to cover other cases like up/down changing the prompt history entry.

**Comment by meganrogge** [comment]
This should work now

**Comment by bhavyaus** [comment]
I'm still seeing incorrect character read-out when I manually type `foo.txt` and use up/down arrows to navigate characters on Windows PowerShell.

**Comment by meganrogge** [comment]
@bhavyaus a gif would be helpful with `terminal.integrated.developer.devMode` enabled pls.
