### ISSUE TITLE
VS Code does NOT print Flutter output in debug console any more on Macbook M1

### ISSUE THREAD

**Issue by tomasbaran** [microsoft/vscode#131543]
The raw DAP event being sent to VS Code:
`{"seq":55493,"type":"event","event":"output","body":{"category":"stdout","output":"I/flutter ( 9042): showing bug\n"}}` and yet the debug console does NOT show it.

For more details, please see: https://github.com/Dart-Code/Dart-Code/issues/3536 

cc @DanTup

**Comment by isidorn** [comment]
@tomasbaran can you please create a fork of [Mock debug](https://github.com/microsoft/vscode-mock-debug) that reproduces this problem?
Was this working in previous stable? Can you reproduce with VS Code insiders https://code.visualstudio.com/insiders/

**Comment by tomasbaran** [comment]
Thanks @isidorn. I can NOT reproduce the issue with VS Code Insiders since it works there as it should. What does it mean for me, please? 

I'm not sure how to do the test with `Mock debug`, can you please tell me step by step how to do it?

**Comment by isidorn** [comment]
@tomasbaran well if it works with VS Code insiders then it seems this issue is already fixed and we can close it. Since next week we will release stable that contains the insiders bits.

As for Mock Debug you just need to clone it and produce output same as flutter. Though @DanTup might be better to do this since he already has experience. However if the issue is fixed in insiders this might not be needed at all.

**Comment by DanTup** [comment]
I'm not really sure how to reproduce (I wouldn't repro even using @tomasbaran's sample in stable Code). The logging is being done from the VS Code extension using a debug adapter tracker, and it shows:

```
{"seq":55493,"type":"event","event":"output","body":{"category":"stdout","output":"I/flutter ( 9042): showing bug\n"}}
```

So it's definitely getting to VS Code. I can't think of what might be going on besides a race or something, although if it doesn't happen in Insiders, that does seem promising - perhaps it's been fixed and will also disappear in the next stable?

**Comment by tomasbaran** [comment]
It's still NOT working correctly. Adding my `flutter doctor -v`

<details>
  <summary>Logs</summary>
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-US)
    • Flutter version 2.2.3 at /Users/tomasbaran/code/flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tomasbaran/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 52B1B8E2-0A95-4737-B3E8-62BB977671D9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
</details>

**Comment by roblourens** [comment]
I looked at the DAP logs and don't see anything unusual. Do you see any errors in the vscode devtools (Help > Toggle Developer tools). Just to get something obvious out of the way, is it possible that you have multiple debug sessions and have selected a different one in the debug console (there would be a dropdown)

If none of that... If I understand correctly, this doesn't repro in a basic Flutter app, only in your project? Are you able to share your project, or reduce your project to something simpler that reproduces the issue?

**Comment by tomasbaran** [comment]
Ok, I got it. I was investigating a bit more. It's a very weird issue. 

PROBLEM:
My project folder is called ambee2. I have it on two computers git cloned from github on macbook air M1 and on iMac 21. iMac is fine, even the macbook M1 was fine until one day it started to showing this issue. 

SOLUTION:
I just rename the project folder to anything, i.e. ambee2.0 and suddenly it works as expected. Also, when I run the original project name ambee2, it works well in google chrome but not on iOS, nor Android.

IDEAS:
I don't know whether there is a cache or something linked to the original ambee2 name or something. I `flutter clean` varios times but that does NOT help, so I'm not sure what's the cause. For me, I'm happy my VSCode finally works once I rename the folder. So, I'll leave it up to you whether you want to close the issue.

**Comment by tomasbaran** [comment]
I found the issue. I'm so sorry about this stupid mistake. I was filtering out a text and forgot about it that's why it didn't show other print outs. I'm ashamed :S
