### ISSUE TITLE
Automatic language detection overrides openTextDocument API language parameter

### ISSUE THREAD

**Issue by ArtemGovorov** [microsoft/vscode#132431]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.60.0
- OS Version: macOS 11.2.3

Despite the fact that we create Untitled text documents using the [`openTextDocument(options?: { language?: string; content?: string; })` function](https://github.com/microsoft/vscode/blob/b55a53add427db20f1ecf7b408327468895a99dd/src/vs/vscode.d.ts#L10769) with `typescript` passed as the language option, automatic detection (incorrectly) switches the language to Dart.

Steps to Reproduce:

1. Install [Quokka extension](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)
2. Run `Quokka.js New Typescript File` command 
3. Paste the following content:

```ts
const arrString = ["asdf", "zdf"];
const arrMixed = ["asdf", 1, {}, "lel"];
const arrOnlyOther = [{}, 1, 45];

function isStringArray(arr: any[]): arr is string[] {
  const nonStringElements = arr.filter(
    (element) => typeof element !== "string"
  );
  return nonStringElements.length === 0;
}

console.table([
  ["arrString", isStringArray(arrString)],
  ["arrMixed", isStringArray(arrMixed)],
  ["arrOnlyOther", isStringArray(arrOnlyOther)],
]);
```

![qb](https://user-images.githubusercontent.com/979966/132178627-69235e81-93c4-41d2-8449-4a00255c64ec.gif)

If I manually create an Untitled file, switch its language to TypeScript and then paste the snippet, it doesn't change the language to Dart. Our expectation would be that the `openTextDocument` API should work the same way.

**Comment by gjsjohnmurray** [comment]
/assign @JacksonKearl

(sorry for previous incorrect assignment)

**Comment by gjsjohnmurray** [comment]
/assign @TylerLeonhardt 

(sorry again for a second incorrect assignment)

**Comment by hediet** [comment]
@gjsjohnmurray no worries, thanks for helping us ❤️

**Comment by infinnie** [comment]
Why should Dart even be detected in this case? It does not even look like Dart.

**Comment by TylerLeonhardt** [comment]
@ArtemGovorov can you try vscode insiders and let me know if it repros there?

**Comment by ArtemGovorov** [comment]
@TylerLeonhardt When the issue was created, it was reproducible in insiders build. Have just tried with the latest insiders `Version: 1.61.0-insider Commit: df115e761ae11cf87ca569ca1824b7257099553a`, and the issue is fixed there.

**Comment by TylerLeonhardt** [comment]
This was fixed late last week I think. Friday or Saturday... so it wouldn't have shown up in insiders until this past Monday. The next recovery stable build (1.60.1) should go out tomorrow and I'd love for you to try that when it comes out

**Comment by TylerLeonhardt** [comment]
1.60.1 was released so this should be fixed now. Can you give it another go?

**Comment by alenakhineika** [comment]
Tried the scenario from https://github.com/microsoft/vscode/issues/132998 and the issue remains in 1.60.1.

**Comment by TylerLeonhardt** [comment]
@alenakhineika can you confirm if this is fixed in [VS Code insiders](https://code.visualstudio.com/insiders)?

**Comment by alenakhineika** [comment]
@TylerLeonhardt in vscode insiders it worked all along, we haven't noticed any issues. Just double-check again works fine.

**Comment by ArtemGovorov** [comment]
@TylerLeonhardt Just checked it as well and:
- it's still not working as expected in 1.60.1;
- it's working as expected in the latest insiders.

![qb](https://user-images.githubusercontent.com/979966/133351412-81471455-cfb3-4b84-8134-02464c195488.gif)

**Comment by TylerLeonhardt** [comment]
Thank you both for confirming!

**Comment by TylerLeonhardt** [comment]
Fixed in #133177
