### ISSUE TITLE
SSH Remote fails to connect

### ISSUE THREAD

**Issue by SferaDev** [microsoft/vscode#132519]
Does this issue occur when all extensions are disabled?: Yes/No (Not applicable, ssh remote is an extension too)

Version: 1.61.0-insider (user setup)
Commit: bb9491d9f2c65510226dcc920a6efbf6501d5943
Date: 2021-09-07T05:17:08.586Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Update to latest insiders build
2. Connect to a SSH Remote Host

Attempts to fix the issue:
- Removing the vscode server from the SSH Host manually
- Rebooting the SSH Host

Works fine:
- Stable channel
- Yesterday's insider build

Details in the output console:

```
[09:50:42.559] Log Level: 2
[09:50:42.572] remote-ssh@0.65.7
[09:50:42.572] win32 x64
[09:50:42.712] SSH Resolver called for "ssh-remote+taris", attempt 1
[09:50:42.713] "remote.SSH.useLocalServer": false
[09:50:42.714] "remote.SSH.showLoginTerminal": true
[09:50:42.714] "remote.SSH.remotePlatform": {"taris":"linux"}
[09:50:42.715] "remote.SSH.path": undefined
[09:50:42.715] "remote.SSH.configFile": undefined
[09:50:42.716] "remote.SSH.useFlock": true
[09:50:42.717] "remote.SSH.lockfilesInTmp": false
[09:50:42.717] "remote.SSH.localServerDownload": auto
[09:50:42.718] "remote.SSH.remoteServerListenOnSocket": false
[09:50:42.718] "remote.SSH.showLoginTerminal": true
[09:50:42.719] "remote.SSH.defaultExtensions": []
[09:50:42.719] "remote.SSH.loglevel": 2
[09:50:42.720] SSH Resolver called for host: taris
[09:50:42.720] Setting up SSH remote "taris"
[09:50:42.731] Using commit id "bb9491d9f2c65510226dcc920a6efbf6501d5943" and quality "insider" for server
[09:50:42.739] Install and start server if needed
[09:50:42.746] Checking ssh with "ssh -V"
[09:50:42.957] > O
[09:50:42.957] > penSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[09:50:42.994] Running script with connection command: ssh -T -D 54394 taris bash
[09:50:42.997] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:51:00.003] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\alexi\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64785)
	at Timeout._onTimeout (c:\Users\alexi\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:413911)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[09:51:00.021] ------
```

Still happening on: 

- 34861b8c8aa76b517f203743ad5b5d72ef5fcd81 (2021-09-08T05:17:18.073Z)
- df115e761ae11cf87ca569ca1824b7257099553a (2021-09-08T17:51:26.439Z)

**Comment by tomaxsas** [comment]
same here after upgrade

**Comment by LFsWang** [comment]
same issue

```
[16:05:45.613] Log Level: 2
[16:05:45.615] remote-ssh@0.65.7
[16:05:45.615] win32 x64
[16:05:45.616] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22415753227d", attempt 1
[16:05:45.617] "remote.SSH.useLocalServer": false
[16:05:45.617] "remote.SSH.showLoginTerminal": false
[16:05:45.617] "remote.SSH.remotePlatform": {"skymizer":"linux","AWS":"linux"}
[16:05:45.617] "remote.SSH.path": undefined
[16:05:45.617] "remote.SSH.configFile": undefined
[16:05:45.617] "remote.SSH.useFlock": true
[16:05:45.618] "remote.SSH.lockfilesInTmp": false
[16:05:45.618] "remote.SSH.localServerDownload": auto
[16:05:45.618] "remote.SSH.remoteServerListenOnSocket": false
[16:05:45.618] "remote.SSH.showLoginTerminal": false
[16:05:45.618] "remote.SSH.defaultExtensions": []
[16:05:45.618] "remote.SSH.loglevel": 2
[16:05:45.618] SSH Resolver called for host: AWS
[16:05:45.618] Setting up SSH remote "AWS"
[16:05:45.634] Using commit id "bb9491d9f2c65510226dcc920a6efbf6501d5943" and quality "insider" for server
[16:05:45.637] Install and start server if needed
[16:05:45.640] Checking ssh with "ssh -V"
[16:05:45.681] > OpenSSH_for_Win
[16:05:45.681] > dows_8.6p1, LibreSSL 3.3.3

[16:05:45.684] Running script with connection command: ssh -T -D 64400 "AWS" bash
[16:05:45.686] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:06:02.692] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\tnst9\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64785)
	at Timeout._onTimeout (c:\Users\tnst9\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:413911)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[16:06:02.695] ------
```

**Comment by ThiefMaster** [comment]
Same thing here. Really annoying. Any workarounds besides installing the non-insiders version?

**Comment by camiant** [comment]
Same here. Waiting for a fix.

**Comment by ThiefMaster** [comment]
As a workaround I copied my installation directory from another computer where I hadn't installed the update yet. At least I can work that way...

**Comment by heath00** [comment]
Same problem here. Installed the release version for now.

**Comment by Krebrov001** [comment]
How can I fix this error?

**Comment by nepvec** [comment]
I have the same problem too.

Version: 1.61.0-insider (user setup)
Commit: 34861b8c8aa76b517f203743ad5b5d72ef5fcd81
Date: 2021-09-08T05:17:18.073Z (6 hrs ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Trace:
```
[07:11:39.707] Log Level: 1
[07:11:39.730] remote-ssh@0.65.7
[07:11:39.730] win32 x64
[07:11:39.779] SSH Resolver called for "ssh-remote+**********", attempt 1
[07:11:39.780] "remote.SSH.useLocalServer": false
[07:11:39.780] "remote.SSH.showLoginTerminal": true
[07:11:39.780] "remote.SSH.remotePlatform": {"**********":"linux"}
[07:11:39.781] "remote.SSH.path": D:\Tools\OpenSSH-Win64\ssh.exe
[07:11:39.781] "remote.SSH.configFile": undefined
[07:11:39.781] "remote.SSH.useFlock": false
[07:11:39.781] "remote.SSH.lockfilesInTmp": false
[07:11:39.782] "remote.SSH.localServerDownload": auto
[07:11:39.782] "remote.SSH.remoteServerListenOnSocket": false
[07:11:39.782] "remote.SSH.showLoginTerminal": true
[07:11:39.782] "remote.SSH.defaultExtensions": []
[07:11:39.782] "remote.SSH.loglevel": 1
[07:11:39.783] SSH Resolver called for host: **********
[07:11:39.783] Setting up SSH remote "**********"
[07:11:39.789] Using commit id "34861b8c8aa76b517f203743ad5b5d72ef5fcd81" and quality "insider" for server
[07:11:39.793] Install and start server if needed
[07:11:39.810] Checking ssh with "D:\Tools\OpenSSH-Win64\ssh.exe -V"
[07:11:40.334] > OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2

[07:11:40.351] Running script with connection command: "D:\Tools\OpenSSH-Win64\ssh.exe" -T -o ClearAllForwardings=true "**********" bash
[07:11:40.359] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[07:12:12.369] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\**********\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64785)
	at Timeout._onTimeout (c:\Users\**********\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:413911)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[07:12:12.375] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"0","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":32589,"timing.preSshTime":580,"timing.scriptTime":32009}}
[07:12:12.380] ------

```

**Comment by rainje** [comment]
Latest insider update does not fix this.

**Comment by camiant** [comment]
> 
> 
> Latest insider update does not fix this.

Yes, indeed... still waiting 👍

**Comment by zulrang** [comment]
Same issue.  Went to insider build because of https://github.com/microsoft/vscode-remote-release/issues/5303.  Can't use either one now.

**Comment by naivelogic** [comment]
> As a workaround I copied my installation directory from another computer where I hadn't installed the update yet. At least I can work that way...

same this works for now, but such an annoying disruption

**Comment by elo1957** [comment]
Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 1052 "pi@192.168.1.68" bash
[15:59:15.192] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:59:32.203] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\osc\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64785)
	at Timeout._onTimeout (c:\Users\osc\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:413911)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)

after updating this morning - 40 student will get bad experience at DTU so Microsoft must do the fix quickly! Waste of time problem

**Comment by ThiefMaster** [comment]
No offense, but why are "40 students" what's effectively a nightly build instead of a stable release?

(but I agree, this should be fixed ASAP, it's annoying to have the "update available" indicator there - I always feel tempted to click it)

**Comment by Krebrov001** [comment]
# I solved this problem, *what worked for me*

### First I uninstalled all the extensions from my Windows client

```
cd %USERPROFILE%\.vscode-insiders
rmdir /s extensions
mkdir extensions
```

### Second I uninstalled all the extensions from my Linux server

```
cd ~/.vscode-server-insiders
rm -rf extensions
mkdir extensions
```

### Third I uninstalled Visual Studio Code from my PC, and reinstalled in again.

### Fourth I installed the Remote Development extensions again in my renewed Visual Studio Code

 * Remote Development
 * Remote - Containers
 * Remote - SSH
 * Remote - SSH: Editing Configuration Files
 * Remote - WSL

**Comment by zulrang** [comment]
Followed the above steps outlined by @Krebrov001 - didn't help.  Same problem.

**Comment by plwalsh** [comment]
That method seems pretty ugly tbh. I've got many extensions installed across both my local host and many remote servers, with a handful of them either enabled or disabled depending on the workspace. Having to reinstall them all just to fix this issue would be a nightmare.

**Comment by dylan-baros** [comment]
Same problem here.

**Comment by Hoernchen** [comment]
It's been broken for days, I guess it's time to abandon insider releases, since there is no easy and convenient way to just grab a older working release.

**Comment by roblourens** [comment]
Sorry for the trouble, I'm looking into this now. Please use the stable build in the meantime

**Comment by roblourens** [comment]
Another workaround, if you have to use Insiders: set `"remote.SSH.useLocalServer": true` (this has to be set explicitly in your settings.json file, even if the checkbox is checked).

This setting may cause other issues on Windows. It's the default on other platforms but not windows

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode-remote-release/issues/5556

**Comment by nepvec** [comment]
> Another workaround, if you have to use Insiders: set `"remote.SSH.useLocalServer": true` (this has to be set explicitly in your settings.json file, even if the checkbox is checked).
> 
> This setting may cause other issues on Windows. It's the default on other platforms but not windows

I confirm this works for me. Thanks!

**Comment by elo1957** [comment]
> > Another workaround, if you have to use Insiders: set `"remote.SSH.useLocalServer": true` (this has to be set explicitly in your settings.json file, even if the checkbox is checked).
> > This setting may cause other issues on Windows. It's the default on other platforms but not windows
> 
> I confirm this works for me. Thanks!

thanks it works also for me

**Comment by anaisbetts** [comment]
It gets you going but it breaks a lot of stuff, like SSH agent (including agent forwarding to git or anything else), looking forward to the fix!

**Comment by Tyriar** [comment]
Can repro the issue by injecting this into test resolver:

```ts
		const writeEmitter = new vscode.EventEmitter<string>();
		let line = '';
		vscode.window.createTerminal({
			name: 'test terminal',
			pty: {
				onDidWrite: writeEmitter.event,
				open: () => writeEmitter.fire('Type and press enter to echo the text\r\n\r\n'),
				close: () => { /* noop*/ },
				handleInput: (data: string) => {
					if (data === '\r') { // Enter
						writeEmitter.fire(`\r\necho: "${line}"\r\n\n`);
						line = '';
						return;
					}
					if (data === '\x7f') { // Backspace
						if (line.length === 0) {
							return;
						}
						line = line.substr(0, line.length - 1);
						// Move cursor backward
						writeEmitter.fire('\x1b[D');
						// Delete character
						writeEmitter.fire('\x1b[P');
						return;
					}
					line += data;
					writeEmitter.fire(data);
				}
			}
		});
```

**Comment by Tyriar** [comment]
PR for recovery release is out: https://github.com/microsoft/vscode/pull/132870

**Comment by roblourens** [comment]
The latest insiders has the fix and it works for me.

**Comment by camiant** [comment]
```
Versione: 1.61.0-insider (user setup)
Commit: 23cffa27b806f9e1733e15d611ec251dcdba2c42
Data: 2021-09-10T17:05:11.199Z
```

Totally working! 🥳

**Comment by zulrang** [comment]
This fix regressed this issue, though: https://github.com/microsoft/vscode-remote-release/issues/5303

**Comment by roblourens** [comment]
That shouldn't be related, I'll continue with you in that thread

**Comment by 1n** [comment]
Does anyone also have the same issue again with the latest insider release on macOS?
```
Version: 1.61.0-insider
Commit: c28c86fcd12e4f8693d6569deadfc740dcf8f55b
Date: 2021-09-20T05:15:38.795Z (5 hrs ago)
```
Can reproduce it when ```"remote.SSH.useLocalServer": false```, however works fine when ```"remote.SSH.useLocalServer": true```.

**Comment by duanehutchins** [comment]
> Does anyone also have the same issue again with the latest insider release on macOS?
> 
> ```
> Version: 1.61.0-insider
> Commit: c28c86fcd12e4f8693d6569deadfc740dcf8f55b
> Date: 2021-09-20T05:15:38.795Z (5 hrs ago)
> ```
> 
> Can reproduce it when `"remote.SSH.useLocalServer": false`, however works fine when `"remote.SSH.useLocalServer": true`.

#133436

**Comment by camiant** [comment]
same issue here: latest release for windows is broken again 😐

```
Version: 1.61.0-insider
Commit: c28c86fcd12e4f8693d6569deadfc740dcf8f55b
```

**Comment by Roy7017** [comment]
@camiant The fix from @roblourens here https://github.com/microsoft/vscode/issues/132519#issuecomment-916224095 works

**Comment by camiant** [comment]
> 
> 
> @camiant The fix from @roblourens here [#132519 (comment)](https://github.com/microsoft/vscode/issues/132519#issuecomment-916224095) works

confirmed! 👍🎉

**Comment by Tyriar** [comment]
A similar bug happened again in yesterday's build but should be fixed in today's https://github.com/microsoft/vscode/issues/133442

**Comment by AfroMonkey** [comment]
Problem persists:

Version: 1.61.0-insider
Commit: 0884da1650baa24994d23d2a3742823c1186e526
Date: 2021-09-10T08:11:07.071Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.14.0-0-MANJARO
Remote - SSH: v0.65.8


```
[12:51:07.552] Log Level: 2
[12:51:07.553] remote-ssh@0.65.8
[12:51:07.553] linux x64
[12:51:07.553] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22444556227d", attempt 1
[12:51:07.554] "remote.SSH.useLocalServer": false
[12:51:07.554] "remote.SSH.showLoginTerminal": false
[12:51:07.554] "remote.SSH.remotePlatform": {}
[12:51:07.554] "remote.SSH.path": undefined
[12:51:07.554] "remote.SSH.configFile": undefined
[12:51:07.554] "remote.SSH.useFlock": true
[12:51:07.554] "remote.SSH.lockfilesInTmp": false
[12:51:07.555] "remote.SSH.localServerDownload": auto
[12:51:07.556] "remote.SSH.remoteServerListenOnSocket": true
[12:51:07.556] "remote.SSH.showLoginTerminal": false
[12:51:07.556] "remote.SSH.defaultExtensions": []
[12:51:07.556] "remote.SSH.loglevel": 2
[12:51:07.557] SSH Resolver called for host: DEV
[12:51:07.557] Setting up SSH remote "DEV"
[12:51:07.564] Using commit id "0884da1650baa24994d23d2a3742823c1186e526" and quality "insider" for server
[12:51:07.567] Install and start server if needed
[12:51:08.963] PATH: /home/moy/.local/share/gem/ruby/3.0.0/bin:/home/moy/.local/bin:/home/moy/bin/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[12:51:08.963] Checking ssh with "ssh -V"
[12:51:08.969] > OpenSSH_8.7p1, OpenSSL 1.1.1l  24 Aug 2021

[12:51:08.971] Running script with connection command: ssh -T -D 40739 -o ConnectTimeout=15 'DEV' bash
[12:51:25.973] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/home/moy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:397167)
	at Timeout._onTimeout (/home/moy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:488075)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[12:51:25.977] ------```

**Comment by Tyriar** [comment]
> 2021-09-10T08:11:07.071Z

@AfroMonkey you're on an 11 day old build?
