### ISSUE TITLE
PATH is incorrect when using macOS and zsh

### ISSUE THREAD

**Issue by reekystive** [microsoft/vscode#133012]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
1.60.0
e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
arm64
```
- OS Version:
```
macOS Big Sur Version 11.5.2 (20G95)
```
- zsh Version:
```
zsh 5.8 (x86_64-apple-darwin20.0)
# I'm also using Oh My Zsh
```

Steps to Reproduce:

1. Open **Terminal.app** and execute `echo $PATH | sed 's/:/\n/g'`
<img width="682" alt="Screen Shot 2021-09-14 at 00 59 35" src="https://user-images.githubusercontent.com/26853900/133126917-ae61cc39-113f-4d29-bf2b-4e5344543cec.png">

2. Open **Visual Studio Code** using `code --disable-extensions`, open Terminal and execute `echo $PATH | sed 's/:/\n/g'`
<img width="893" alt="Screen Shot 2021-09-14 at 00 59 37" src="https://user-images.githubusercontent.com/26853900/133126943-2aa96c03-d218-48d4-8e20-1e7807aac40f.png">

I found this issue because I couldn't use the correct version of vim. In the above screenshots, the path of vim is different.

Related issue: https://github.com/microsoft/vscode/issues/107169

**Comment by jxjj** [comment]
I'm also seeing this issue with different $PATHs in VS Code's Terminal and Terminal.app.

`Terminal.app`:
```sh
➜  ~ echo $PATH | sed 's/:/\n/g'
/Users/james/.rbenv/shims
/opt/homebrew/opt/openssl@1.1/bin
/Users/james/.rbenv/shims
/Users/james/.deno/bin
/Users/james/.composer/vendor/bin
/Users/james/.nvm/versions/node/v14.17.4/bin
/opt/homebrew/opt/openssl@1.1/bin
/opt/homebrew/bin
/opt/homebrew/sbin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Library/Apple/usr/bin
```

`VS Code`:
```sh
➜  ~ echo $PATH | sed 's/:/\n/g'
/Users/james/.rbenv/shims
/Users/james/.deno/bin
/Users/james/.composer/vendor/bin
/Users/james/.nvm/versions/node/v14.17.4/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Library/Apple/usr/bin
/Users/james/.rbenv/shims
/opt/homebrew/bin
/opt/homebrew/sbin
/Users/james/.deno/bin
/Users/james/.composer/vendor/bin
/Users/james/.nvm/versions/node/v14.17.4/bin
```

## My Environment

VS Code version:
```
1.60.1
83bd43bc519d15e50c4272c6cf5c1479df196a4d
arm64
```

MacOS
```
ProductName:    macOS
ProductVersion: 11.6
BuildVersion:   20G165

```

ZSH version
```
zsh 5.8 (x86_64-apple-darwin20.0)
```

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by jxjj** [comment]
Thanks for looking at this, Megan! 

The issue still persists for me this Insider build:
```
Version: 1.61.0-insider (Universal)
Commit: f66a3e06bcb9f000e5dc0ad0040ff9b32fc75c78
Date: 2021-09-14T05:14:54.400Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0
```

<img width="1096" alt="Screen Shot 2021-09-14 at 7 11 29 PM" src="https://user-images.githubusercontent.com/980170/133350152-ab1000a6-1700-4862-91fd-7a7fd25021dc.png">
