### ISSUE TITLE
stepping over breakpoint appears to resume execution fully, vs stepping.

### ISSUE THREAD

**Issue by cdaringe** [Microsoft/vscode#13306]
- VSCode Version: 1.5.3
- OS Version: osx 10.11.6

may be related to ##13096

here, i visually demonstrate (you may want to click to view the GIF in a larger window):

![stepping-over-resumes-execution mov](https://cloud.githubusercontent.com/assets/1003261/19164548/40d29736-8bb5-11e6-89fd-f78e053e9e58.gif)

thanks!

**Comment by cdaringe** [comment]
it's also strange that when execution ends, the debugging bar/context remains. i would expect the debugging bar to disappear when execution finishes.

**Comment by alecl** [comment]
I've been running into this fairly often for months and it's highly frustrating. Anything that can be done to gather more info so it can be addressed?

**Comment by weinand** [comment]
What node.js version are you using?

Some version of node have a bug: see #5822
(which is due to his node bug: nodejs/node#7219)

**Comment by weinand** [comment]
@cdaringe execution of node.js does not stop because of this node bug: nodejs/node#1788

**Comment by alecl** [comment]
Had the same issue in 4.5 and 6.10.1.

**Comment by alecl** [comment]
Bugs in nodejs from 2 years ago. This is madness. Any suggested workaround or version that still works?

**Comment by weinand** [comment]
nodejs/node#7219 should be fixed in recent versions of node.js.

Does it help if you use the 'inspector' protocol (by addig a `"protocol": "inspector"` to your launch configuration?

**Comment by weinand** [comment]
I've just verified that nodejs/node#7219 is fixed in 6.10.2

**Comment by weinand** [comment]
@alecl What VS Code version are you using?

**Comment by alecl** [comment]
Interesting. I updated to 6.10.2 and then found it still happening. I set "smartStep" to false and that seemed to fix it. smartStep is skipping lines of my code that are calling outside code even though I'm NOT stepping into the outside code.

VSCode 1.11.1

**Comment by weinand** [comment]
If you still see the problem in 6.10.2 then it is unrelated to nodejs/node#7219.
Do you have any watch expressions defined? Does the problem disappear if you remove the watches?

**Comment by alecl** [comment]
It still occurs if I remove the watches but I believe the issue is with the smartStep feature being enabled rather than that nodejs termination bug now that I'm on 6.10.2. I'll find/open a new issue for that. Thanks for your help.

**Comment by weinand** [comment]
@cdaringe could you please verify that your problem no longer occurs in VS Code 1.11.x and node.js >= 6.5.0 - thanks!

**Comment by cdaringe** [comment]
confirmed--it's working great! thx!
