### ISSUE TITLE
terminal.integrated.cursorBlinking not working

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#133608]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.60.1
- OS Version: macOS 11.6

Steps to Reproduce:

1. In settings, set `terminal.integrated.cursorBlinking` to `true`
2. Quit and reopen VScode
3. press <kbd>Ctrl + `</kbd> to open the integrated terminal
4. the cursor in the integrated terminal doesn't blink, even though it should

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by ryenus** [comment]
Hi, @meganrogge, 

I just checked and the problem is still present in the latest insider build:

> Version: 1.61.0-insider (Universal)
Commit: 5991e3c4b97eca5568069bf3e0910ab693ad3549
Date: 2021-09-27T05:14:53.754Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

### Steps
1. open the fresh insider build
2. open the integrated terminal, and focus it
3. notice the terminal cursor doesn't blink, this is expected since "terminal.integrated.cursorBlinking" defaults to false
4. open settings, turn on terminal cursor blinking
5. now focus the integrated terminal again, see that the terminal cursor starts blinking
6. run the `exit` command, or press <kbd>ctrl + d</kbd>, RATHER THAN closing the terminal panel
7. **again, open a new integrated terminal, here the terminal cursor DOES NOT blink, even though the setting is still on.**

And the problem is with the last step above, apparently things are different regarding the terminal is whether a new one or not.

**Comment by ryenus** [comment]
@meganrogge Could you please re-open the issue? Thank you!
