### ISSUE TITLE
Source Control bug when creating or changing branch in the workspace

### ISSUE THREAD

**Issue by PollyGlot** [microsoft/vscode#134638]
Working with several projects in a workspace, I create and/or change a branch in one project and it creates and/or changes the branch for every project in the workspace.

https://user-images.githubusercontent.com/3662505/136525323-34b5d888-e06a-426c-a5c6-b039db4001d8.mov

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.61.0
- OS Version: macOS Big Sur 11.5.2

Steps to Reproduce:

1. Open a workspace with several projects
2. Try to create/change branch on one project
3. It will create/change the branch for every project

**Comment by PollyGlot** [comment]
@mattseddon I confirm that disabling `scm.showActionButton` it fixes the problem for me

**Comment by gjsjohnmurray** [comment]
/assign @eamodio

Looks serious enough for a recovery release.

**Comment by zeba0039** [comment]
> Can you try disabling `scm.showActionButton` in your user settings to see if it fixes the problem?

Fixed the problem for me

**Comment by ascentcreative** [comment]
> Not only the focus is shifted but also the texts are moving from one place to another. Check the small mp4 i created: https://user-images.githubusercontent.com/13405649/137311331-230c8b67-2518-4030-91c9-db96b0dd0acf.mp4 By removing `scm.showActionButton`, the problem from the mp4 was removed.

Yep - those issues were fixed for me too by disabling that setting as described. However, I still get the jump in focus of the commit messages - mp4 at https://www.dropbox.com/s/o6hze8reydlftax/Screen%20Recording%202021-10-14%20at%2012.53.51.mov?dl=0

**Comment by lramos15** [comment]
A new version of vs code 1.61.1 has been released, this should fix this issue

**Comment by dkms-its** [comment]
I'm afraid i sill have the "jumping text cursor" issue on 1.61.1 - only disabling showActionButton helps. 

Steps to reproduce:
1) Have multiple git repositories configured in a workspace
2) make changes to some repo that is not the first one in the sidebar list
3) give commit message field the focus
4) stage some files in that repo
5) watch VSCode working (progress bar appearing) and see the cursor jumps to the first commit message field.

**Comment by eyedean** [comment]
@lramos15 it's still happening, though not as crazy as it was.  I created https://github.com/microsoft/vscode/issues/135412 with a screen recording and repro steps.
