### ISSUE TITLE
[html] allow extensions to provide computed custom data

### ISSUE THREAD

**Issue by sijakret** [microsoft/vscode#135459]
Hi,

vscode has a setting `html.customData` (and `css.customData`) which allows [extending the set of html tags known to the internal language service](https://github.com/microsoft/vscode-custom-data).
Currently users need to configure the list of custom-element.json files manually in the settings.
Are there plans to implement an automatic discovery of these files from the installed npm packages?

If not, maybe this could (and should) be done via an extension.
There is a corresponding [contribution point](https://code.visualstudio.com/api/extension-guides/custom-data-extension). However, it seems to be pointing to a static file only. Also, it looks like changes to that file are not monitored so a hacky approach like overwriting some sort of temp schema file does not seem viable as well.
Is there any away for an extension to signal updates to the custom data it is contributing?

If so, a generic extension could provide logic + settings to discover these definitions and expose them to vscode once discovered. I would be happy to implement this. It would streamline consuming web component libraries quite a bit compared to having to manage paths manually in the vscode settings.

This looks like the most relevant thread on the web component side: https://github.com/WICG/webcomponents/issues/776

Side note: Some [libraries](https://github.com/adobe/spectrum-web-components) already ship cusomt-elements.json files. They indicate their presence with a `"customElements"` field in the package.json. It's just that no one seems to pick them up..
![image](https://user-images.githubusercontent.com/16835620/138071489-881cce6a-540b-458f-9b1a-ec096cb6b39f.png)

**Comment by thepassle** [comment]
> They indicate their presence with a "customElements" field in the package.json.

Additionally, if a package uses a package exports map, it may be under:
```json
{
  "exports": {
    "./customElements": "./custom-elements.json"
  }
}
```

**Comment by sijakret** [comment]
The whole domain seems a bit fractured.
There also seems to typescript path via [HTMLElementTagNameMap](https://github.com/microsoft/typescript-lit-html-plugin/issues/5) that allows extending the language service. It is used by https://github.com/mjbvz/vscode-lit-html under the hood. This also works.

I think the main gotcha here is that it only works in template literals in code (*.ts) files. Not sure why but my uneducated guess is it leverages the typescript infrastructure. At least in my case I did not manage to get type completion etc. in a *.html file.

Maybe https://github.com/microsoft/typescript-lit-html-plugin can just be extended so it also works in all html contexts and not just in template literals in code. That would also be an option for projects with typescript I guess..

**Comment by aeschli** [comment]
I'd like to avoid that the HTML server is getting into understanding project configuration files (e.g. `package.json`). There's no single well-established standard and I/we are not experts in a field that quickly progresses.
So having an extension doing would be great.

As you mentioned, extensions can contribute custom data, but only as a static data.

We could extend the `customData` contribution points to take a URL as well. Then extensions can point it to a URL with computed content using a [Text Document Provider](https://code.visualstudio.com/api/extension-guides/virtual-documents#textdocumentcontentprovider).

If you are interested of making that change, I'd be happy to take a PR (for both `css.customData` and `html.customData`)

**Comment by sijakret** [comment]
ok, i think i am doing something wrong, woth both `FileSystemProvider`and `TextDocumentContentProvider` i cant manage to watch for changes in my modified `html-language-features` extension.

If I use `window.showTextDocument()` to open the dynamic doc in the editor it updates fine so this means that the provider as well as the `onDidChangeFile` do work - it updates as expected.
But the extension does not seem to have a way to subscribe to changes in the in memory fs file (again, initial pass is fine, but i cannot detect updates in the `html-language-features`.

Is there any example where an extension subscribes to updates to a virtual doc (or fs-provider file) that is NOT opened by the user in the workspace?

**Comment by sijakret** [comment]
> You create a document with `workspace.openTextDocument(uri)`, and hold a reference to it? `workspace.onDidChangeTextDocument(..)` should be triggered when you fire a change event in the provider. We rely on that in the JSON extension. Can you double check?

I am assuming you are referring to right?
https://github.com/microsoft/vscode/blob/dabc9bdc9db2854b8289e1f154726c00f67a2665/extensions/json-language-features/client/src/jsonClient.ts#L252

I have tried that pattern and it does not fire when I fire `onDidChange` (or `onDidChangeFile` respectively for FileSystemProvider) in the provider. If I deliberately open the virtual document in an editor it does update which leads me to believe my provider is fine...

**Comment by aeschli** [comment]
Here's what I tried https://github.com/aeschli/test-135459
- extension registers a TextDocumentContentProvider and opens a document from it
- extension triggers change events and listens to them

- open the extension
- run the `Test: Foo Content Update` command

![image](https://user-images.githubusercontent.com/6461412/139659142-1a50cce0-5179-4587-9d32-b13bd56f5454.png)

So this looks good, no need to open the document in an editor.
How is your code different?

**Comment by sijakret** [comment]
yes this looks like what I am trying to do.

from looking at it the only difference is

* I don't keep a ref to the opened doc around (html-language-server would need to do that then), but i am pretty sure i tried that at some point
* in my scenario the extension providing the doc and firing the changes and the extension listening for them are not the same, but the workspace is global to all exts so I don't think that really makes a difference.

your example should help me to pin point what I am doing wrong - thanks a lot again!
I will check it later today and get back to you

**Comment by sijakret** [comment]
I think i figured it out.
I had used paths of the shape `my-scheme:data.json` for some reason these don't (fully work)
If I use `my-scheme:/data.json` as the customdata path everything starts to work (including updates).

these are the changes I currently have for `html-language-features`:
https://github.com/sijakret/vscode/commit/b074018c3eb51f1ef5c159826ff3d43ffd1b2f0b

With this I can get an extension that automatically updates schemas to work..

@aeschli please take a look when you find time and let me know if I am on the right track here :)

**Comment by sijakret** [comment]
ping

**Comment by aeschli** [comment]
Can you create a PR?

Some comments:
- To find out if a path is a URL or path make regex match for `schema://`
- `onDidChangeTextDocument` is triggered very often. We need to optimize the check if we are impacted: Use a set and only check for the URI's and workspace paths we got (not the paths inside extensions)

**Comment by sijakret** [comment]
I have created a PR.
This one does not have any changes to `css-language-features` yet.

> * To find out if a path is a URL or path make regex match for `schema://`

Since we don't know the particular scheme beforehand and we also need the uri later on anyhow create one and check for `uri.scheme === 'file' && runtime.fs`. Is that not ok?

> * `onDidChangeTextDocument` is triggered very often. We need to optimize the check if we are impacted: Use a set and only check for the URI's and workspace paths we got (not the paths inside extensions)

I have added a set for the paths contributed from extensions and the ones contributed from workspaces.
Im not sure why we should not consider the paths from the extensions, can you explain?
For my use case I actually particularly care about these since I am contribute a dynamic document via the `customData.html` contribution point.

**Comment by aeschli** [comment]
Currently, `contributes.html.customData` support relative paths: e.g. `./some-data.json`, `myfolder/myfile.json` and we want to continue to support these.
Sending these through `JSON.parse` is not proper, as they are potentially not full URIs and we don't want to rely on the way how `JSON.parse` handles that.

So first check if the provided path is a full uri using : `/^\w[\w\d+.-]*:/.test(path)`. If not, it needs to be joined with the extensionLocation.

Extension resources are supposed to be static resources and we do not support them to change (except in development scenarios, but I don't think we should go there right now).
That does not apply to the URIs that are contributed by extensions. That's handled by your code.

**Comment by sijakret** [comment]
> ..Sending these through `JSON.parse` is not proper, as they are potentially not full URIs and we don't want to rely on the way how `JSON.parse` handles that.
> 
> So first check if the provided path is a full uri using : `/^\w[\w\d+.-]*:/.test(path)`. If not, it needs to be joined with the extensionLocation.

You mean `URI.parse` not `JSON.parse`, right?
![image](https://user-images.githubusercontent.com/16835620/142856710-48e7403c-b3f1-432c-acc9-089c97018d5c.png)

The first thing it does is applying a regex so I wanted to explicitly rely on that logic and seemed like the proper centralized way of handling the url.
If it does not find an explicit scheme it looks like it will fall back to `file`.
![image](https://user-images.githubusercontent.com/16835620/142857204-dc90a44e-353c-4bb6-8386-ea613bd46a7f.png)

Checking for a scheme directly would, of course, be a slightly faster but also a more isolated solution.
let me know what you prefer!

**Comment by aeschli** [comment]
Yes, sorry. `Uri.parse`
Yes, we do not want to rely on that fallback behavior which is not spec'ed. It is not the indented use of `Uri.parse` and eventually a warning will be emitted.

**Comment by aeschli** [comment]
Implemented by #137557

**Comment by sijakret** [comment]
I have created another PR.

without this PR i don't think any previous behavior breaks.
however, it is needed to actually make the feature work.

@aeschli please take a look!

**Comment by aeschli** [comment]
We want to use `runtime.fs.getContent` for extension resources, but `openTextDocument` for resources in the workspace and coming from URIs.
I fixed the issue with 3d8b5674c769c885beee85546625d419ffafc10a

**Comment by sijakret** [comment]
@aeschli I tried the current main branch and unfortunately it is still not working :(
Just because a path customData was contributed by an extension it does not have to be an `fs` path that resides in that extension. I think the whole point here is that the extensions can provide a custom scheme and serve dynamic data.

If you take a look at this debugging session in the screenshot below: Here `customData:/data.json` was provided by the extension (i.e. is in the pathsInExtensions Set) and the extension is installing a TextDocumentProvider to serve a dynamic scheme here.
With the current code the extension can never provide the virtual doc to `html-language-features`. `getContent` will always end up in the `fs..` code path.
![image](https://user-images.githubusercontent.com/16835620/143920284-d831f2e1-6ab7-4488-a3e8-1455a57ead45.png)

Maybe `pathsInExtensions` should be called `pathsProvidedByExtension` because that's what it is i guess..

**Comment by aeschli** [comment]
Ok, one more try... Sorry for that.

**Comment by sijakret** [comment]
now it works - thanks a lot :)

**Comment by aeschli** [comment]
@sijakret Can you verify if all works in tomorrow's build and let me know?

**Comment by sijakret** [comment]
of course. not sure about the schedule though. when should i look for it? will it be posted as a release here in the repo?

**Comment by aeschli** [comment]
You can get the latest VS Code Insiders build here: https://code.visualstudio.com/insiders/
If your extension works with it, then we can mark this issue as verified.

**Comment by sijakret** [comment]
Oh, i did not realize that one is updated daily.
works well - thanks a lot!

**Comment by alexr00** [comment]
What are the steps to verify this?

**Comment by sijakret** [comment]
1. create an extension that
   1. contributes `"html.customData": [ "myScheme:/data.json" ]
   2. contributes a TextDocumentProvider that handles "myScheme"
   3. provides html customData via that scheme
2. the data provided should be picked up by the html language service for tags and attributes etc..

i have an extension that does this let me know if you want to use that to try it.

**Comment by aeschli** [comment]
Marking as verified given that @sijakret has done so with his extension.

@sijakret Glad to try it myself with your extension as well. Is it published already?

**Comment by sijakret** [comment]
@aeschli A preview version is actually ready. I was just unsure about two things:
* should I rely on engine at >= 1.63.0?
* If so the typings are not there yet for it right?

**Comment by aeschli** [comment]
Yes, you add a `"engines": { "vscode": "^1.63.0"}` to avoid strange issues with older versions of VS Code.
What do you mean with typings?

That reminds me, we should update the spec of the extension point and settings.

**Comment by sijakret** [comment]
i made some changes to make the extension also work in vscode.web: https://insiders.vscode.dev/github/sijakret/custom-element-scanner-test this should also work for you i think.

* you need to add "custom-element-scanner" extension (recommended in workspace)
* it adds a new view container on the left, enable automatic mode
* then finds the custom element definitions in the toy project
* if you go to the index.html file language service will know the tags

still a few things i need to figure out and the extension essentially would like to crawl the whole repo for package.json files with a "customElements" field. I will polish it a bit when i get to it but it already kind of get's the job done.

**Comment by sijakret** [comment]
@aeschli one more question came up:
* in which contexts is html-language-features used?
* only in .html files?
* what about markdown files etc..?

**Comment by aeschli** [comment]
All files registered for editors with language id `html` and `handlebars`.

I don't think the Markdown language features do anything smart with HTML. (But you know more than me)
