### ISSUE TITLE
Unable to resolve your shell pops-up instantly

### ISSUE THREAD

**Issue by Jason3S** [microsoft/vscode#136272]
Issue Type: <b>Bug</b>

1. MacOS ?
1. Have VS Code open.
1. Create a new window
1. Open a recent Multi-folder Workspace that had the Terminal Panel open.

The following Error pops up nearly instantly:

![image](https://user-images.githubusercontent.com/3740137/139805366-7164df70-0537-48ef-844c-c3b316e152bf.png)

The `Learn More` link say it should be after 10 seconds.

![image](https://user-images.githubusercontent.com/3740137/139805546-f10839c7-5025-42b2-8cb4-1df721051560.png)

Once it is in this mode, opening any new window will bring up the error.

It happens very fast.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|32.00GB (5.75GB free)|
|Process Argv|--crash-reporter-id 21ae0ece-62a2-4681-a5cf-c687ea23e753|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
ada|Ada|23.0.1
commit-message-editor|ada|0.19.1
alignment|ann|0.3.0
vscode-zipfs|arc|2.3.0
vscode-intelephense-client|bme|1.7.1
better-toml|bun|0.3.2
scala|dal|0.0.5
vscode-jq-playground|dav|4.2.0
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.23
prettier-vscode|esb|9.0.0
vscode-graphql|Gra|0.3.18
mediawiki|jak|2.1.0
latex-workshop|Jam|8.21.1
svg|joc|1.4.13
jq-syntax-highlighting|jq-|0.0.2
language-haskell|jus|3.4.0
vscode-cfml|Kam|0.5.3
linter-gfortran|krv|2.3.0
remotefs|lix|0.0.16
Kotlin|mat|1.7.1
vscode-apache|mrm|1.2.0
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.17.0
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2021.10.3
jupyter|ms-|2021.9.1101343141
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.3
remote-containers|ms-|0.202.5
azure-account|ms-|0.9.9
cpptools|ms-|1.7.1
vsonline|ms-|1.0.3076
vetur|oct|0.35.0
marko|pca|0.4.0
java|red|1.0.0
es6-mocha-snippets|spo|0.2.2
avro|str|0.5.0
code-spell-checker|str|2.0.12
code-spell-checker-dutch|str|0.2.9
code-spell-checker-french-reforme|str|2.0.1
code-spell-checker-german|str|2.0.1
code-spell-checker-norwegian-bokmal|str|0.1.1
code-spell-checker-persian|str|0.1.9
code-spell-checker-portuguese-brazilian|str|2.0.2
code-spell-checker-russian|str|2.0.1
code-spell-checker-spanish|str|2.0.2
code-spell-checker-swedish|str|1.0.1
code-spell-checker-turkish|str|0.1.9
code-spell-checker-ukrainian|str|0.1.10
hunspell|str|0.0.2
vscodeintellicode|Vis|1.2.14
vscode-java-debug|vsc|0.36.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by emunozmultisf** [comment]
I have the same problem with a MacBook Air (M1, 2020) in VSCode 1.62.3. I just downloaded VSCode Insiders (1.63.0-insider) and the bug is fixed.

**Comment by Timmmm** [comment]
#138182 isn't exactly a duplicate of this. You'll still get the popup after a reboot because it genuinely does take longer than 10 seconds to resolve the shell. But that's not because there's something slow in `.bashrc` or `.zsh`. It's because the machine is heavily loaded.
