### ISSUE TITLE
VSCode using a lot of CPU (100%+)

### ISSUE THREAD

**Issue by sacummings91** [microsoft/vscode#136329]
Issue Type: <b>Performance Issue</b>

Working in TS changes are not being picked up by the compiler and whenever I save a file my Code Helper (Renderer) uses more than 100% CPU until it can resolve. This results in a large delay.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id b71d3aa9-5032-4585-9bf5-93ab47133377|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	   115	  4667	code main
    2	    82	  4670	   gpu-process
    0	    16	  4672	   utility
    0	   393	  4673	   window (tsserver.log — frontend)
    0	   213	  4934	     extensionHost
    0	    98	  5213	       electron_node tsserver.js 
    0	   492	  5214	       electron_node tsserver.js 
    0	    33	  5233	         electron_node typingsInstaller.js typesMap.js 
    0	   147	  5239	       electron_node eslintServer.js 
    0	    33	  5261	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=4934
    0	    33	  4935	     watcherService
    0	    82	  4933	   shared-process
    0	    33	  4936	     ptyHost
    0	     0	  5521	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    2	    66	  5519	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (tsserver.log — frontend)
|    Folder (frontend): 555 files
|      File types: tsx(222) ts(133) js(60) json(18) otf(16) woff2(14) png(8)
|                  DS_Store(4) svg(4) ico(3)
|      Conf files: settings.json(1) tasks.json(1) package.json(1)
|                  tsconfig.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.1
vscode-eslint|dba|2.2.2
gitlens|eam|11.6.1
prettier-vscode|esb|9.0.0
go|gol|0.29.0
vscode-styled-components|jpo|1.6.6
atom-keybindings|ms-|3.0.9
vsliveshare|ms-|1.0.5065
vscode-todo-highlight|way|1.0.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by sacummings91** [comment]
I also have logs but not sure what format to share them in

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by sacummings91** [comment]
Using the Start Extension Bisect command does not fix the problem. Performance is still massively degraded with all extensions turned off.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Ok, I think this may have been fixed by our recent upgrade to TypeScript 4.5 then (or an extension was causing the issue)

Let me know if this starts happening on VS Code insiders while using TypeScript 4.5+

**Comment by sacummings91** [comment]
Hey @mjbvz I'm still having the same issues with the Insider build. My Activity monitor and Process explorer below. Experiencing better performance if I use the Extension Bisect but still a bit slow.

<img width="952" alt="Screen Shot 2021-11-03 at 7 01 08 PM" src="https://user-images.githubusercontent.com/29286028/140245077-1972e1f2-5b33-474b-89fb-2ba3a512e361.png">
.
![Screen Shot 2021-11-03 at 6 59 50 PM](https://user-images.githubusercontent.com/29286028/140245085-51b13136-0767-4d00-87c7-767b6ea267ba.png)

**Comment by sacummings91** [comment]
I'm using less extensions too hopefully that helps narrow it down.

![image](https://user-images.githubusercontent.com/29286028/140245634-6446bf8e-5210-43fc-a90a-fa48f924a07c.png)

**Comment by sacummings91** [comment]
Another update. I'm fairly certain it's prettier extension at this point. I was going to file an issue there but theres a few recent ones already and they seem to just get closed without any reason

**Comment by crossjs** [comment]
typescript@4.5.2 make CPU 100%.
after downgrade to typescript@4.4.4, everything is OK.
