### ISSUE TITLE
Unreadable text in Process Explorer

### ISSUE THREAD

**Issue by b3s23love** [microsoft/vscode#136510]
Issue Type: <b>Bug</b>

Steps: It is easy to reproduce the bug. Just open the Help menu and click on the "Open Process Explorer" button. You will see some gibberish text on the top of the columns. You can see it on the screenshot. The columns aren't even resizable! That's quite bad. Could you fix the gibberish text and add resizable columns in the Process Explorer, please? I would really appreciate.

![Screenshot](https://user-images.githubusercontent.com/70533786/140501679-8872a495-eb80-4a8e-ad26-4d1abb08187a.png)

VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:01.379Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (9.39GB free)|
|Process Argv|--crash-reporter-id f667050e-cd55-4c9b-8828-622f51c58fbd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
vscode-language-pack-pl|MS-|1.62.2
cpptools|ms-|1.7.1
markdown-preview-enhanced|shd|0.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis400:30386382
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by IllusionMH** [comment]
Looks like text overflow because of long translation values
![image](https://user-images.githubusercontent.com/1312662/140508171-8e0b0013-9ba6-4127-b397-0c17fb6b8c70.png)

**Comment by JakubDrozd** [comment]
The translation is Polish. Anyway, I would like to have resizable columns.

**Comment by JakubDrozd** [comment]
Add the feature-request label, please.

**Comment by JakubDrozd** [comment]
Task Manager does the resizable columns very good.

**Comment by Tyriar** [comment]
It's labeled as a bug because it's a bug.

**Comment by JakubDrozd** [comment]
But it is also a feature request, because I also want to add resizable columns, like in the Windows Task Manager.

**Comment by Tyriar** [comment]
@JakubDrozd noted, we don't need 2 issues to track it though.

**Comment by JakubDrozd** [comment]
Ok, so just add also the feature-request tag, please.

**Comment by Tyriar** [comment]
We normally only add a single "type label" to issues, you can read about how we manage issues on https://github.com/microsoft/vscode/wiki/Issues-Triaging#categorizing-issues. Please stop spamming, it doesn't impact you how we manage our issues.

**Comment by JakubDrozd** [comment]
Ok, just fix the issue as soon as possible.

**Comment by JakubDrozd** [comment]
HI, I would like to have the issue fixed ASAP.

**Comment by joyceerhl** [comment]
Still reproducible in latest Insiders with Configure Display Language > Polish:

![image](https://user-images.githubusercontent.com/30305945/207196457-a56f812e-99c9-4115-b9da-82d8f77aa133.png)

**Comment by Tyriar** [comment]
This if fixed now 
![image](https://github.com/microsoft/vscode/assets/2193314/c83d7f6c-482c-45ad-92a3-be33d88b9753)
![image](https://github.com/microsoft/vscode/assets/2193314/988fe64a-0756-4a38-91e2-3f3e77dc5c42)

**Comment by aeschli** [comment]
I still see this
![image](https://github.com/microsoft/vscode/assets/6461412/a994341b-4bb0-41dd-89d6-661fa347e41d)


Wersja: 1.86.0-insider (user setup)
Zatwierdzenie: 1091f68d834974d78cd4f9769034b4ae4581ff2a
Data: 2024-01-24T05:36:35.802Z
Elektron: 27.2.3
ElektronBuildId: 26378995
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
System operacyjny: Windows_NT x64 10.0.22635

**Comment by legomushroom** [comment]
Was able to re-confirm on stable 1.95.3 ☺

**Comment by bpasero** [comment]
Fixed as part of the move to floating window.
