### ISSUE TITLE
PowerShell terminal stops searching modules in user path

### ISSUE THREAD

**Issue by gsscoder** [microsoft/vscode#136560]
Hello everyone!

**Does this issue occur when all extensions are disabled?**
Yes, I've done some test. All extensions disabled. All extensions removed. Deep uninstall (using a tool).
No matter what I do, after some restart of the app the issues came back again.
A temporary way to fix is complete uninstall and reinstall.

**VSCode and system info:**
```
Version: 1.62.0 (system setup)
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:23:01.379Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

**Steps to Reproduce:**
It just happens on startup after few time of the last installation.
Open and close VSCode 3-4 times is sufficient to reproduce the issue.

I notice cause posh-git module fails to load:
```
import-module : The specified module 'posh-git' was not loaded because no valid module file was found in any module directory.
At C:\Users\Coder\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:128 char:1
+ import-module posh-git
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (posh-git:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

I see that PowerShell user modules path is not present when printing `$env:PSModulePath`.
From VSCode:
`C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Windows\system32\config\systemprofile\Documents\WindowsPowerShell\Modules;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\`
From outside:
`C:\Users\Coder\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Users\Coder\Documents\WindowsPowerShell\Modules;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\`

If you need any other information, please ask me.

Thank you for excellent work!

Best regards,
Giacomo S. S.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by gsscoder** [comment]
@meganrogge, thanks for replying.

I upgraded to `1.62.2` and the issue disappeared.

The weird thing is that I was experimenting the same problem when using **Developer PowerShell** in Visual Studio and upgrading VS Code fixed Visual Studio too.

Have a nice day.

**Comment by gsscoder** [comment]
Unfortunately the issue is back again and it's still present also with Insiders build.

**Comment by gsscoder** [comment]
I've found a solution. Just set `PSModulePath` in your **settings.json**:
```
    "terminal.integrated.env.windows": {
        "PSModulePath": "C:\\Users\\Coder\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Users\\Coder\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\Tools\\PowerShell\\Modules\\"
    },
```

Set with the content of your `$env:PSModulePath`.
