### ISSUE TITLE
Window crashes frequently when updated the latest version

### ISSUE THREAD

**Issue by Timeless0911** [microsoft/vscode#136929]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: macOS Catalina 10.15.7

After I updated the latest version of VSCODE yesterday, one of my windows crashed frequently and the pop-up window appeared.
![image](https://user-images.githubusercontent.com/50201324/141242983-57758065-8a2f-413c-999d-7c12cf8085c0.png)

Steps to Reproduce:

1. Open a git codebase, and just wait a few minutes;
2. Window crashed and appeared some prompt as above.
3. Only my Monorepo projects with multiple packages will crashed.

**Comment by Timeless0911** [comment]
![image](https://user-images.githubusercontent.com/50201324/141246751-44f393af-645c-4c71-a0b7-a1117eededd5.png)
In the Activity Monitor, you can see that such a process is madly occupying the cpu

**Comment by Timeless0911** [comment]
![image](https://user-images.githubusercontent.com/50201324/141246862-51e0fd7f-c061-4f3d-9d40-99a6a3594895.png)
In the Activity Monitor, you can see that such a process is madly occupying the cpu

**Comment by chrmarti** [comment]
@roblourens Assigning to you since the process is `rg`.

**Comment by roblourens** [comment]
Can you try with the Insiders build of vscode?

**Comment by Timeless0911** [comment]
> Can you try with the Insiders build of vscode? I made a change recently that might help.

The insides build seems to solve this problem. And I try to turn off this setting [Search: Follow Symlinks], it seems to have some effect too.
![image](https://user-images.githubusercontent.com/50201324/141406459-c73d0f58-c44d-4e0a-9969-7a8813570bf5.png)

**Comment by roblourens** [comment]
Great, hopefully it is resolved

**Comment by marcojulioarg** [comment]
Unchecked Follow Symlinks, window still crashing and rq process using too much ram
