### ISSUE TITLE
Clone Repository UI Displacement of "Recent" is extremely annoying

### ISSUE THREAD

**Issue by oborchers** [microsoft/vscode#137357]
- VS Code Version: 1.62.2
- OS Version: 10.14.6 Max

Steps to Reproduce:

1. Open VSCode
2. Click on project

Description:

There is a delay for the `Clone Git Repository...` on the dashboard to appear when the dashboard opens.

If you are switching between several projects during the day, this delay is EXACTLY the amount of time it takes to click on the project you want (minus a few ms). 

Meaning you click on the project and in that EXACT moment `Clone Git Repository` comes along and is like: 
> "NOOO YOU CLICK ON ANOTHER PROJECT MY FRIEND" 

because it pops up and moves all `Recent` projects one row down which is super annoying.

:)

**Comment by oborchers** [comment]
@lszomoru: Thank you! There you go:

https://tenor.com/view/gif-23845575

**Comment by oborchers** [comment]
<div class="tenor-gif-embed" data-postid="23845575" data-share-method="host" data-width="100%" data-aspect-ratio="1.7785714285714287"><a href="https://tenor.com/view/gif-23845575">GIF</a> </div><script type="text/javascript" async src="https://tenor.com/embed.js"></script>

**Comment by oborchers** [comment]
@lszomoru there we go:

https://gfycat.com/unimportantredhummingbird

**Comment by lszomoru** [comment]
Thanks @oborchers. It looks like this has been fixed in `Insiders`. Could you give that a try? Thanks!

**Comment by alexr00** [comment]
I still see some UI instability. Specifically, Open a Walkthrough changes into Clone a Repository:

![Uploading recording (71).gif…]()

**Comment by lszomoru** [comment]
@digitarald, do you by any chance have context on the reason why "Open a Walkthrough" is being replaces with "Clone Git Repository..."?

**Comment by digitarald** [comment]
@lszomoru the reasoning was that this fits contextually with the other options for opening a workspace. "Open a Walkthrough …" is also exposed in the "More …" link on the right.

It seems for some setups it has enough delay to cause accidental clicks. Would you advise to remove it? Another idea is that the link could always be shown but then open git setup guide when vscode-git didn't load.

**Comment by lszomoru** [comment]
@digitarald, while the verifications steps for this issue were focused on the "Clone Git Repository..." command, looking at the screenshot provided above I am seeing several problems that I think we should address: 
1. The "Recent" list is being moved around. 
2. The "Open a Walkthrough..." is being replaced.

Ideally the overall layout of the start screen should stay the same as things load in the background.
