### ISSUE TITLE
Unhandled rejection `undefined` raised when testing an extesion

### ISSUE THREAD

**Issue by macabeus** [microsoft/vscode#138453]
- VS Code Version: `1.62.3`
- OS Version: `macOS Big Sur 11.6`

I'm developing a vscode extension and I notice that in some situations an unhandled rejection with `undefined` error is raised.

This exception always is raised if:
1. a document is opened (`workspace.openTextDocument`)
2. **and** wait for a few seconds (eg: 10 seconds) before finishing a test

```ts
describe('example', () => {
  it('it will fail', async () => {
    await workspace.openTextDocument('/Users/macabeus/foo/index.js')
    await timeout(10000)
  })
})
```

It is bad because a false positive is raised to Jest since it uses [`process.on('unhandledRejection', uncaught)`](https://github.com/facebook/jest/blob/ff701c2f5f693157593ca48cfe11584431783282/packages/jest-circus/src/globalErrorHandlers.ts#L24) to listen for every unhandled rejection - including the ones raised by vscode itself.
No error really happened in my tests, but the test runner will say that an error happened.

**Comment by bpasero** [comment]
Maybe https://github.com/microsoft/vscode/issues/138269

**Comment by macabeus** [comment]
@bpasero Do you know if my vscode version (`1.62.3`) already has this fix?

**Comment by bpasero** [comment]
The fix was pushed to insiders. You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by macabeus** [comment]
@bpasero Yeah, it's the issue.
I ran the same test on Insiders, and I still have the same error. But instead of `undefined`, I had a better-detailed error added by PR #138333:
```
Canceled: Canceled
    at A.reset (/private/var/folders/jm/1lt96gyn7m51jbdhd6t5dq7h0000gn/T/AppTranslocation/5DBCEAB0-4856-46F1-A712-E7ADE7CC31D9/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:534074)
    at /private/var/folders/jm/1lt96gyn7m51jbdhd6t5dq7h0000gn/T/AppTranslocation/5DBCEAB0-4856-46F1-A712-E7ADE7CC31D9/d/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:530729
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {name: 'Canceled', stack: 'Canceled: Canceled
    at A.reset (/private/v…ctions (internal/process/task_queues.js:93:5)', message: 'Canceled'}
```
Despite that issue being closed, it wasn't solved here since Jest is still catching this exception and failing the test.

Is there a better way to fix it?
I can try to help fix it in vscode, but I need more context about what to do to can help.

**Comment by bpasero** [comment]
@mjbvz moving to you, maybe there is a better way than rejecting.
