### ISSUE TITLE
Breakpoints unbound when debugging web extension on Insiders build

### ISSUE THREAD

**Issue by devhawk** [microsoft/vscode#139774]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.64.0-insider (user setup)
Commit: 7b9e5c32a053669d4e72f998e4fa217090c32f59
Date: 2021-12-22T05:15:28.225Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
- OS Version:
Microsoft Windows 10 Pro
10.0.19044 N/A Build 19044

Steps to Reproduce:

1. Open the [helloworld-web-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-web-sample) in Code Insiders. 
2. Set a breakpoint on the `console.log` statement of the `activate` method
3.  Launch the debugger

Expected behavior: debugger breaks at breakpoint
Actual behavior: debugger doesn't break at breakpoint. breakpoint greyed out and hover text reads "Unbound Breakpoint"

**Comment by connor4312** [comment]
Can you please try out the [nightly debugger](https://github.com/microsoft/vscode-js-debug#nightly-extension) and let me know if you experience the same issue there? I put in a fix earlier this iteration which may solve your case.

**Comment by devhawk** [comment]
Nope, still broken. 

More Info:
version v2022.1.717
Released on: 11/12/2019, 20:47:26
Last updated: 1/7/2022, 17:07:53
Identifier: ms-vscode.js-debug-nightly

**Comment by connor4312** [comment]
Thanks this should be fixed on the next Insiders build with js-debug-nightly.

**Comment by devhawk** [comment]
Still not working

Released on 11/12/2019, 20:47:26
Last updated 1/12/2022, 17:07:00
Identifier ms-vscode.js-debug-nightly

**Comment by connor4312** [comment]
The next Insiders build has not yet been released

**Comment by devhawk** [comment]
I'm sorry, I thought you meant it was fixed with the update to the debugger. I will test again when next insiders comes out

**Comment by devhawk** [comment]
Just tested with latest insiders / JS Debug and it worked! 

Insiders:
Version: 1.64.0-insider (user setup)
Commit: 0e435cf51d0e45293a94466fc3b1299ba70fa9b1
Date: 2022-01-13T21:33:48.622Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

JS Debug Nightly:
Released on 11/12/2019, 20:47:26
Last updated 1/13/2022, 17:08:22
Identifier ms-vscode.js-debug-nightly

**Comment by connor4312** [comment]
Thanks for confirming!
