### ISSUE TITLE
Use modern (CSS color level 4) syntax for colors in the color picker

### ISSUE THREAD

**Issue by glen-84** [microsoft/vscode#139840]
When converting colors using the color picker, the old comma-based syntax is used:

![image](https://user-images.githubusercontent.com/261509/147552254-feb09a98-fbee-494c-ba33-7d86ca371349.png)
(it should also show `hsl` here, at the top of the picker, not `rgba`)

Please update the picker to use the modern (CSS color level 4) syntax for colors.

With regard to the exact syntax, I agree with these suggestions from `@mathiasbynens`:

> - consider being opinionated w.r.t. how to represent alpha values. IMHO using percentage notation is most readable, as it clarifies the range: e.g. 70% vs 0.7
> - consider being opinionated about using the deg suffix where applicable, e.g. in the first parameter for hsl() and the last non-alpha parameter for lch(). Again, because this clarifies that the range lies between 0-360.

i.e. Use percentages for alpha, and always include the `deg` suffix.

This also matches the syntax displayed in Chrome developer tools.

**Comment by glen-84** [comment]
@rebornix Please mention the issue that this duplicates. I searched before opening this, and again now, but I can't find one.

**Comment by rebornix** [comment]
I thought there is an easier one but I couldn't find it anymore. Let's use this issue to track CSS color level 4 syntax support.

**Comment by aiday-mar** [comment]
This issue has been fixed since then

![Image](https://github.com/user-attachments/assets/2d3066cd-7f5a-4183-b965-e62716df02f1)

**Comment by lachieh** [comment]
The picker still displays and cycles through the old syntax. I don't think this is resolved.

https://github.com/user-attachments/assets/c27c7f09-1772-4617-a34b-c47917d5d20a

**Comment by aiday-mar** [comment]
Hi thank you for your comment. When you mention the level 4 spec is it the HSL value without commas?

**Comment by T3sT3ro** [comment]
I think it was related to all [Level 4 color syntax forms](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#formal_syntax), which I also find lacking. I am currently looking into the VScode source myself.

To summarize:
- [x] named colors
- [x] hex values
- [x] rgb
- [x] rgba
- [x] hsl
- [x] hsla
- [x] hwb
- [ ] lab
- [ ] lch
- [ ] oklab
- [ ] oklch
- [ ] color

With more and more libraries using oklch/oklab by default, this is becoming more and more important.

Should it go into `/vscode/src/vs/editor/common/languages/defaultDocumentColorsComputer.ts` or the css language server and use the ColorProvider API?
