### ISSUE TITLE
Accept Current Change or Accept Incoming Change... options do not appear in VSCode

### ISSUE THREAD

**Issue by mikeerickson** [microsoft/vscode#141617]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.0 Insiders
- OS Version: macOS 12.0

I am not seeing the "Accept Current Change" or "Accept Incoming Change" when viewing merge conflicts

I am expecting to see this (as defined in VSCode Documentation)
![CleanShot 2022-01-26 at 18 53 25](https://user-images.githubusercontent.com/183153/151283718-81e7de38-c726-410e-9f06-6e96604653a2.png)

But instead I just see this (notice the top bar of choices is gone)

![CleanShot 2022-01-26 at 18 55 29](https://user-images.githubusercontent.com/183153/151283835-2c74e169-44e4-436a-8166-b46a583d0f67.png)

**Comment by zedyuan999** [comment]
In VScode settings  set:
```javascript
// setting.json
"editor.codeLens": true,
```

**Comment by lszomoru** [comment]
@mikeerickson, sorry for not getting back to you on this until now. Are you able to reproduce this issue with the latest version of VS Code? Also, check out [the new 3-way-merge editor](https://code.visualstudio.com/updates/v1_69#_3-way-merge-editor) that is included in the latest release.

**Comment by ingomueller-net** [comment]
I have the same problem. It appeared after the update to 1.70. I have not (knowingly) changed any settings since it last worked. I have tried to add `"editor.codeLens": true,` to the `settings.json` file in the workspace but that did not help. Anything else I can try?

**Comment by mikeerickson** [comment]
Ya, I have yet to find a solution to the problem. I have hoped that the monthly updates would somehow fix the issue; and I have also worked with Insiders version but nothing helps.

**Comment by AprilArcus** [comment]
Also impacted here. It's a shame to lose this feature.

**Comment by geoffgscott** [comment]
+1 to this issue.

Version: 1.70.0 (Universal)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:55.829Z (2 wks ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 20.6.0

**Comment by lszomoru** [comment]
Does setting `git.mergeEditor` to `false` help? Thanks!

**Comment by eskp** [comment]
> Does setting `git.mergeEditor` to `false` help? Thanks!

Yes 👍

**Comment by saikatmahapatra** [comment]
I'm facing the same issue. What is the solution @mikeerickson 

Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by TheScripterX** [comment]
Still facing the same issue. Any news ?

Version : 

![image](https://user-images.githubusercontent.com/45905517/189551761-54cc70dc-c52e-46bf-a31b-7fb2dab834a9.png)

**Comment by lszomoru** [comment]
@saikatmahapatra, @TheScripterX have you tried the step documented [here](https://github.com/microsoft/vscode/issues/141617#issuecomment-1227017830)?

**Comment by ingomueller-net** [comment]
I have finally been able to try out this feature again. Curiously, and after several monthly updates, the merge bar is back were it should be. I have barely used VS code in the past 1-2 months, so I suppose that one of the updates fixed it. I have not made any attempts to fix it myself. In case it helps anybody: I have `git.mergeEditor` set to `true` and it still works (now, after the latest update).

**Comment by saikatmahapatra** [comment]
Yes, its resolved now

**Comment by TheScripterX** [comment]
It's back now 👍  _( I don't know how but it's working )_.

**FYI : @lszomoru**

**Comment by LattVines** [comment]
this is still happening to me. I've tried turning on and off every combination of Code Lens I can find, and it doesn't make a difference. I tried updating VS Code as well. I've followed all suggestions from here: https://stackoverflow.com/questions/47241098/accept-incoming-change-not-appearing-in-vs-code

Nothing works :(

**Comment by lszomoru** [comment]
Closing the issue as looking through the comments this should be resolved. 
In case anyone is still able to reproduce this issue please let me know. Thanks!
