### ISSUE TITLE
Launching VS Code without an internet connection gives a cryptic error message

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14213]
- VSCode Version: Code - Insiders 1.7.0-insider (81445f8c47e550c3bfe683a2079ea8c82e022397, 2016-10-19T08:28:03.050Z)
- OS Version: Linux x64 4.4.0-43-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|terminal-tabs|Tyriar|0.0.6|
|theme-glacier|Tyriar|0.0.10|
|vscode-icontheme-nomo-dark|be5invis|1.1.4|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.0.8|
|git-project-manager|felipecaputo|0.1.15|
|Theme-Wombat|gerane|0.0.2|
|csharp|ms-vscode|1.4.1|
|typescript-javascript-grammar|ms-vscode|0.0.5|
|nova|rebornix|0.0.5|
|sass-indented|robinbentley|1.1.0|
|annotator|ryu1kn|0.10.1|

---

The message should be more user friendly and also only show when the extension panel is open, as that's the only time as a user you would typically care.

![image](https://cloud.githubusercontent.com/assets/2193314/19622875/a5e0a1a2-9869-11e6-84da-2537aa3eeee4.png)

Steps to Reproduce:

1. Launch VS Code without an internet connection

**Comment by joaomoreno** [comment]
Fixed by e73a6143fef1b7bd22c9fdc93b681600e6ccf67c

**Comment by isidorn** [comment]
I still get the same message, but does not happen if I do not open extensions viewlet
