### ISSUE TITLE
MarkdownString with 4 leading spaces is displayed as blank in hover.

### ISSUE THREAD

**Issue by Darshana-Suresh** [microsoft/vscode#142501]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.64
- OS Version: Windows 10

Steps to Reproduce:
I am using HoverProvider interface to show custom hovers on the editor of my vscode extension. For the hover content, I was using MarkdownString with 4 leading spaces for each line to enable syntax coloring. Till version 1.63, this was working fine. But on using vscode version 1.64, hover shows empty tooltip boxes as shown below -
![image](https://user-images.githubusercontent.com/30208571/152965300-0ca455fa-6104-4fad-911c-93d54b0fef9b.png)

Turns out that the issue gets resolved once the leading spaces are removed. But the syntax coloring does not show up if there are no leading spaces - 
![image](https://user-images.githubusercontent.com/30208571/152966016-3e95821d-a08a-4f33-9814-322978778890.png)

Here is the hover output (with 4 leading spaces added) till vscode version 1.63 -
![image](https://user-images.githubusercontent.com/30208571/152966399-e294f393-ca73-45f4-84f6-487eac18bedd.png)

Sample code to reproduce the issue shared here - https://github.com/Darshana-Suresh/hoverprovider-sample/blob/main/src/HoverProvider.ts

**Comment by gjsjohnmurray** [comment]
Might relate to #142445 which is reportedly fixed in the latest Insiders. Can you test with that?

**Comment by Darshana-Suresh** [comment]
> Might relate to #142445 which is reportedly fixed in the latest Insiders. Can you test with that?

I've tested with the latest Insiders version (1.65.0). It doesn't solve the issue.

**Comment by Darshana-Suresh** [comment]
Is it the right way to use 4 leading spaces to enable syntax coloring in MarkdownString? Or should I be doing something else to achieve it?

**Comment by gjsjohnmurray** [comment]
Use a code fence, e.g.

    ```languageId
    // code example
    // More lines
    ```

**Comment by lukaszsamson** [comment]
@mjbvz @gjsjohnmurray this a breaking change for elixir-ls extension, see https://github.com/elixir-lsp/vscode-elixir-ls/issues/233

**Comment by lukaszsamson** [comment]
[LSP specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#markupContent) states that:
> If the format is markdown the content should follow the [GitHub Flavored Markdown Specification](https://github.github.com/gfm/)

and GitHub Flavored Markdown Specification should support intended code blocks, see https://github.github.com/gfm/#indented-code-blocks
