### ISSUE TITLE
Terminal.processId doesn't seem to be working on Windows

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14286]
From @whitecolor in https://github.com/Microsoft/vscode/issues/11919#issuecomment-255731340

> @Tyriar Well I'm not sure how I should demonstate that something wrong here.
> 
> For me `terminal.processId` promise gives the PID value that doesn't exist in processes list at all. The terminal is running.
> 
> ![image](https://cloud.githubusercontent.com/assets/736697/19646311/48000186-9a12-11e6-849b-1cd1736f5076.png)

**Comment by whitecolor** [comment]
Just remind about the issue.

**Comment by whitecolor** [comment]
Also a reminder about the issue. Was planned on Nov.

**Comment by Tyriar** [comment]
After looking more into how the backend works, I believe the PID is likely the winpty agent which wraps the shell. Not sure there's anything that can be done about this.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/Tyriar/node-pty/issues/45

**Comment by Tyriar** [comment]
This should be fixed now in https://github.com/Microsoft/vscode/commit/e6f8ec8bb22ab987adb4e0f1af551a5daf83af83

@whitecolor if you get a chance to test this in the latest Insiders that would be great :smiley:

**Comment by Tyriar** [comment]
To verify on Windows:

1. Clone and run terminal-sample in https://github.com/Microsoft/vscode-extension-samples.git
2. Create a terminal with `terminalTest.createTerminal` and then print the processId to console using `terminalTest.processId`, it should match the process ID in task manager

Please test for cmd.exe and PowerShell terminals.

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.11.0-insider (cc46bbf5b0412e464f89280e828d602fbc06a0f4, 2017-03-31T14:08:17.917Z)
- OS Version: Windows_NT ia32 10.0.14393

Still an issue:

![image](https://cloud.githubusercontent.com/assets/9205389/24560593/38c70f72-15f8-11e7-9ce5-e05fe792a70d.png)

cmd.exe:

![image](https://cloud.githubusercontent.com/assets/9205389/24560760/e3ffa12e-15f8-11e7-9ec7-3226c7f191df.png)

**Comment by Tyriar** [comment]
@chrmarti isn't that's the debug console, not the terminal?

**Comment by Tyriar** [comment]
Ugh, I know why this is still broken https://github.com/Tyriar/node-pty/issues/67
