### ISSUE TITLE
Images missing in Release Notes on vscode.dev in Safari

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#143030]
(initially reported in https://github.com/microsoft/vscode/issues/142490#issuecomment-1035555676 by @osortega)

* in Safari
* open `https://vscode.dev`
* `Help > Release Notes`

<img width="438" alt="image" src="https://user-images.githubusercontent.com/5047891/153910397-c5f2bdf5-6d87-48f8-825a-f80d872963e8.png">

Appears to be caused by CSP errors:

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/5047891/153910478-5e907b3d-9a46-42cc-b6ce-f18f7a4460fa.png">

**Comment by mjbvz** [comment]
Extension pages are also broken. I suspect this is because script are disabled in both of these webviews, however I don't understand why this also ends up breaking other stuff. Both cases work fine on Chrome

**Comment by mjbvz** [comment]
This is caused by this block of code:

https://github.com/microsoft/vscode/blob/c713056c22cffef52422a3d8d9a8151d063e7d99/src/vs/workbench/contrib/webview/browser/pre/main.js#L871

This block was added to work around a different limitation on Safari and removing the if condition causes the iframes never to load. 

---

As part of this investigation, I noticed that the content does sometimes load so it looks like a race condition. After testing, I also determined this happens in Chrome too.

I've opened two bugs to track this:

- https://bugs.chromium.org/p/chromium/issues/detail?id=1297377
- https://bugs.webkit.org/show_bug.cgi?id=236624


The fact that two browsers are flakey here suggests were are doing something crazy, but I don't have enough knowledge to say if we're truly going against the specs. Will see if I can workaround this better, even if that means simply adding another timeout for safari loads

**Comment by rzhao271** [comment]
The release notes don't load at all for me now.
I get the following error in the console:
`Error while parsing the 'sandbox' attribute: 'allow-downloads' is an invalid sandbox flag.`

**Comment by mjbvz** [comment]
Fixed in stable and in 1.65 branch by #144133

**Comment by rzhao271** [comment]
Still seeing a bunch of errors. Not sure if the changes are in, yet. Sent over a log.

**Comment by rzhao271** [comment]
Ok it's good now 🎉
