### ISSUE TITLE
New notebook 'text/plain' renderers doesn't display line breaks

### ISSUE THREAD

**Issue by tvaucher** [microsoft/vscode#143194]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.0-insider (commit `52e65499654de7525e30df3a8228b69320796bf5`)
- OS Version: Monterey 12.2

The new `text/plain` renderer for Notebooks introduced in #142584 (Re #142429) doesn't display line breaks (see attached image). Culprit could be `\n` within HTML div to represent line breaks in https://github.com/microsoft/vscode/blob/main/extensions/notebook-renderers/src/textHelper.ts instead of `< br />`? Also breaks for representing long lists.

Thanks for looking into it.

Insiders:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/8888706/154260741-68f15c77-9c5a-4ec4-aac6-7ee50a8a4fcf.png">

Expected (old renderer in 1.64.2):
<img width="559" alt="image" src="https://user-images.githubusercontent.com/8888706/154260987-5f29e036-26a6-49ad-9c75-0d77d3ba002b.png">

**Comment by jaymegordo** [comment]
+1 same issue, very annoying

**Comment by rebornix** [comment]
@tvaucher @jaymegordo thanks for the quick feedback, it should be fixed in tomorrow's Insiders.

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/876920/154378849-f221d6d8-a930-4b0d-b08e-110851179627.png">

**Comment by amunger** [comment]
I'm still seeing `\n`'s from `repr` output. The series output looks better though
![image](https://user-images.githubusercontent.com/2019016/155626544-da376711-e23b-4382-9008-b11c138564a1.png)
Version: 1.65.0-insider (user setup)
Commit: 3112460dc48ce7e557ea9feeaae04b912164b48b
Date: 2022-02-24T05:15:20.989Z
Electron: 16.0.9
Chromium: 96.0.4664.174
Node.js: 16.9.1
V8: 9.6.180.23-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by rebornix** [comment]
@amunger this is what you get from jupyter lab too

<img width="475" alt="image" src="https://user-images.githubusercontent.com/876920/156253286-e408ddc9-d24d-407d-b904-30debb024474.png">
