### ISSUE TITLE
`readOnly` lazy attributes are not respected

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#143790]
Testing #143572

1. Create a variable with only a getter, so that it contains `readOnly` in its `presentationHint.attributes`
2. Notice double clicking still allows setting it

**Comment by weinand** [comment]
Most likely this is not a specific problem of "lazy" variables...

**Comment by connor4312** [comment]
Looks like that's correct. I fixed this a short while ago in https://github.com/microsoft/vscode/commit/989bb81 but it seems like it regressed.

**Comment by roblourens** [comment]
It seems like js-debug might not be sending a presentationHint on the resolved lazy property. I see 'readonly' and 'lazy' there before it's resolved but not after.

**Comment by weinand** [comment]
Yes, a "lazy" without a setter does not react on double click, so its value cannot be set.

However, if a setter is added, it still does not react on double click.
@connor @roblourens is this a problem of js-debug or VS Code?

**Comment by connor4312** [comment]
yep, will fix in js-debug
