### ISSUE TITLE
Terminal command success decorations still render after running `clear`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#143784]
Testing #143433

1. `cd ..`
2. `clear`
3. :bug: success terminal command decorations are still rendered

![image](https://user-images.githubusercontent.com/30305945/155382546-108f46a2-7066-4583-a470-590e7f71d093.png)

**Comment by meganrogge** [comment]
only reproes sometimes - regression related to the `eraseInDisplay` change that was reverted in `xterm`

**Comment by meganrogge** [comment]
https://github.com/xtermjs/xterm.js/pull/3649/commits/a4fee6d4b5c8dd4f740cdf0b5e221377020c1f34

**Comment by Tyriar** [comment]
I bet I caused this in https://github.com/xtermjs/xterm.js/pull/3654, need `i--` after a splice...

**Comment by Tyriar** [comment]
Upstream fix merged, updating now...

**Comment by paulacamargo25** [comment]
I'm having the same error on macOS.<img width="1346" alt="Screen Shot 2022-02-24 at 9 44 26 AM" src="https://user-images.githubusercontent.com/17892325/155578698-45ed9087-38e7-484c-9ca5-c52b7bfe7670.png">

**Comment by joyceerhl** [comment]
Still seeing this:
![image](https://user-images.githubusercontent.com/30305945/155770269-a0930036-a76f-4059-97cf-7974f0f0d325.png)


Version: 1.65.0-insider (user setup)
Commit: 8440b8f47231147823ba9696913d642e5f2d9d58
Date: 2022-02-25T05:17:33.544Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by meganrogge** [comment]
@joyceerhl if you run `Terminal Clear`, you should see them all gone from the terminal. running `clear` in the terminal only clears the viewport.

**Comment by meganrogge** [comment]
are you scrolling? a gif might be helpful because I cannot reproduce

**Comment by meganrogge** [comment]
![Recording 2022-02-25 at 12 49 34](https://user-images.githubusercontent.com/29464607/155771116-68749f1b-6c51-43d5-b042-dc85a17169d5.gif)

**Comment by meganrogge** [comment]
You might also be seeing https://github.com/microsoft/vscode/issues/75141

**Comment by joyceerhl** [comment]
Oh--I thought running `clear` in the terminal was supposed to clear the decorations too. Seems a little weird that the command decorations would stick around--I would disable the decorations if that is the behavior moving forward since the dots become quite distracting: 
![image](https://user-images.githubusercontent.com/30305945/155772115-0b3bfb60-ba81-4f2a-979c-d4eaa2fa9317.png)

Terminal: Clear does clear out the decorations, btw.

**Comment by meganrogge** [comment]
I don't think we can do anything about `clear` not working as expected in pwsh/windows. @Tyriar can we?

**Comment by Tyriar** [comment]
@meganrogge conpty sends `\x1b[3J`, should we be clearing markers whenever erase in display clears any line?

**Comment by meganrogge** [comment]
I think it would be easy to handle by checking if the command entered was clear or similar (could even do this per shell type since the command name may differ). More complicated and potentially destructive to clear the markers whenever erase in display is called imo. We can test it though.

**Comment by meganrogge** [comment]
Reopening to cover cases like this specially
