### ISSUE TITLE
Text not found in rendered Markdown after filter update

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#143809]
Testing #143437

Steps:
- Have a Markdown cell in edit mode, for example
```markdown
# Markdown cell

Test something
```
- Open the Find widget, make sure "Markdown Source" is unticked and "Rendered Markdown" is ticked:
![image](https://user-images.githubusercontent.com/51720070/155394144-f55d10d9-dd73-4bd2-ad84-f0d95ba5a79e.png)
- Search for "Test something", observe that no results were found (as expected)
- Stop editing the cell, observe that no results are found until the search words are updated

**Comment by rebornix** [comment]
Right now we don't trigger update when markdown preview or outputs are updated.

**Comment by rebornix** [comment]
should be fixed now in Insiders.

**Comment by mjbvz** [comment]
Still seeing this:

![Image](https://user-images.githubusercontent.com/12821956/214434829-ef180074-a7b6-467a-b37e-78bc814d84cc.png)

Looks like the PR never got merged? https://github.com/microsoft/vscode/pull/168367

**Comment by rebornix** [comment]
@mjbvz I missed the failing CI and expected to be auto merged, thanks for catching it.
