### ISSUE TITLE
JS IntelliSense Loading Infinitely

### ISSUE THREAD

**Issue by Zx-EvM** [microsoft/vscode#145309]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.65.2
- OS Version: Windows 10 Pro 21H1 19043.1586

Steps to Reproduce:

1. Open existing JS file or create and save new
2. Look at infinitely loading bar

When I open JS file in VSCode it's never completes IntelliSense loading.

![photo_2022-03-17_22-05-08](https://user-images.githubusercontent.com/20873402/158805872-045b3711-0448-4d39-b041-afa854ee2068.jpg)

Extensions list:
```
13xforever.language-x86-64-assembly
fabiospampinato.vscode-todo-plus
GitHub.github-vscode-theme
golang.go
GrapeCity.gc-excelviewer
icrawl.discord-vscode
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode.vscode-typescript-next
rafamel.subtle-brackets
```

The bug is also reproduced with `code --disable-extensions`

**Comment by Zx-EvM** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

@mjbvz I've installed VSCode Insiders just now for checking purposes. Yes, it's still reproduce in 1.66.0-insider. No extensions installed.

**Comment by Zx-EvM** [comment]
Also tried inside clean Windows 10 VBox machine, all the same

**Comment by mjbvz** [comment]
Can you also please share your user settings

**Comment by Zx-EvM** [comment]
@mjbvz main Windows 10 machine config: https://pastebin.com/F6YgrG5k

VBox Windows 10 pretty clean so config is empty.

**Comment by Zx-EvM** [comment]
Does this bug reproduced for you?

**Comment by mjbvz** [comment]
No, I don't see this in my testing. Can you try collecting the typescript server log of when this happens so I can see if anything stands out there:

Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by Zx-EvM** [comment]
@mjbvz https://pastebin.com/raw/KxW41suD

**Comment by nati-maskens** [comment]
The tsserver at `1.65.2` is **definitely** leaking memory. This is the process invocation:
```
/opt/visual-studio-code/code \
    --ms-enable-electron-run-as-node \
    --max-old-space-size=8192 \
    /opt/visual-studio-code/resources/app/extensions/node_modules/typescript/lib/tsserver.js \
        --useInferredProjectPerProjectRoot \
        --enableTelemetry \
        --cancellationPipeName /tmp/vscode-typescript1000/6b96d5eb10edce778406/tscancellation-938f9057679d25ad026c.tmp* \
        --locale en \
        --noGetErrOnBackgroundUpdate \
        --validateDefaultNpmLocation \
        --useNodeIpc
```
The tsserver logs shows the that certain message `getApplicableRefactors` is never receiving response and always requested to be canceled.
The process is getting abort signal when reaching the configured memory limits (tried 8gb!).
Downgrading to `1.64.2` and the problem disappears.
I think this is a bug.

**Comment by nati-maskens** [comment]
BTW tried also with nightly, same problem.

**Comment by nati-maskens** [comment]
At @Zx-EvM log you can see one example of that `getApplicableRefactors` taking full big 31 seconds 😨

**Comment by Zx-EvM** [comment]
@mjbvz I can confirm that problem disappears in previous 1.64.2

**Comment by kamilorzelek** [comment]
Same problem here. Versio 1.65.2

**Comment by nati-maskens** [comment]
@mjbvz Something is definitely going on here 🙂

**Comment by an-boxbrite** [comment]
I'm also experiencing similar issues in Java for the past few days, most prominently when triggering the "Trigger Suggest" or "Quick Fix..." commands via keybinding (i.e. Ctrl+Space and Alt+Enter respectively). Suggestions/fixes never load (or maybe I just haven't waited long enough). However, suggestions do pop up just fine upon certain context-sensitive keystrokes, such as `.` (period after a reference, to access a member) and `@` to add an annotation.

Attempted workarounds:
- restarting does seem to reset the issue but only temporarily, and I haven't been able to determine what interaction would seem to cause the issue to come back
- downgrading `vscode-java` to 1.3.0, doesn't seem to have any effect (other than the restart, as noted above)
- downgrading VS Code itself to 1.64.2, also doesn't seem to have any effect (other than the restart, as noted above)

Additionally, as mentioned in #144419, code navigation also stops working, seemingly at the same time as the above issues begin, and I did experience the sustained high CPU usage at one point, but that hasn't returned.

Another possibly-related symptom is that the `vscode-java-test` extension seems to crash. It appears in the installed extensions list at the bottom greyed-out and can't be enabled or disabled.

I know these last couple are anecdotal symptoms that don't sound related, however they all began occurring at the same time. Maybe coincidence, but I figured I'd mention them just in case.

**Comment by mjbvz** [comment]
If you aren't @Zx-EvM, open a new issue. @an-boxbrite open an issue against Java


@Zx-EvM Do other IntelliSense features work even though loading is showing?

**Comment by Zx-EvM** [comment]
@mjbvz things like autocompletion you mean? Yes, it works, seems like.

**Comment by nati-maskens** [comment]
Hi @mjbvz! Thanks for watching this issue.
Why should I open a duplicate, if my experience was exactly the same as @Zx-EvM reported?
Is there any lead here: https://github.com/microsoft/vscode/issues/145309#issuecomment-1073862412, I tried to provide a bit "more info"..

**Comment by mjbvz** [comment]
@Zx-EvM Did you have a workspace open when this happens?

**Comment by Zx-EvM** [comment]
@mjbvz no, this issue reproduced when just a single file was opens. Just now I've tried to open js file in workspace (I've opened folder with vscode) and issue not reproduce. New `tsserver.log` in this case: https://pastebin.com/raw/HUjrxg7C

**Comment by mjbvz** [comment]
Should be fixed in next insiders

In this case the issue is only cosmetic: the spinner does not mean extra resources are being user or that IntelliSense is broken. If it's annoying you, try out out the next insiders build

**Comment by cgarrovillo** [comment]
Insiders version doesn't fix this for me, neither does March, or February builds.  January seems to have returned to the way it functioned before.

Let me know how else I can help

**Comment by Zx-EvM** [comment]
@mjbvz I agree with @cgarrovillo

The IntelliSense issue fixed only in 1.67.0-insiders.

Also I've noticed that 1.66 is very poorly loads, it freezes, lags on start etc. Looks the described related to https://github.com/microsoft/vscode/issues/147086

So I prefer now to use insiders build because 1.66 is too poor and annoying experience.

**Comment by lramos15** [comment]
@Zx-EvM Thanks for verifying the fix. Insiders is released once a day with the latest VS Code changes. The entire VS Code team utilizes insiders to test and receive feedback on the latest and greatest features coming to the next full release of VS Code. Being that it is a nightly build it of course may have more bugs than the stable release of VS Code but that's the trade off of being on the bleeding edge. Feel free to continue trying it out and providing feedback on the new things coming to VS Code :)
