### ISSUE TITLE
Terminal fails to render João's name

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#14586]
- open terminal on vscode workspace
- run git log such that it shows an entry from @joaomoreno 
- his name is garbled

![screen shot 2016-10-27 at 11 38 58](https://cloud.githubusercontent.com/assets/1794099/19762404/1a2b331e-9c3a-11e6-8be8-17952f60c8ed.png)

**Comment by joaomoreno** [comment]
![gif](http://i.giphy.com/HyCxJErg9jTCU.gif)

**Comment by Tyriar** [comment]
Hmm, works on Ubuntu.

![image](https://cloud.githubusercontent.com/assets/2193314/19772432/0aa58a08-9c1b-11e6-9ac0-8f05ed26f400.png)

**Comment by matheusrocha89** [comment]
Any updates?

**Comment by Tyriar** [comment]
@matheusrocha89 if for you want to look into this I believe it's an issue specifically on macOS in the upstream project of https://github.com/sourcelair/xterm.js, so first thing to do would be to reproduce it there and then narrow down where the problem is within it.

**Comment by matheusrocha89** [comment]
Ok @Tyriar I will look on this project and see what I can do to help 👍

**Comment by matheusrocha89** [comment]
@Tyriar I tried clone the xterm project and ran the demo on my mac and it worked fine 😕  
![image](https://cloud.githubusercontent.com/assets/3718366/23103507/ca088074-f69a-11e6-9fd6-90ef2ddf40e9.png)

I saw that on `vscode` the xterm dependency is your fork of the project. I will try the demo on your fork to see if it's already fixed in some version that your fork don't have yet.

**Comment by matheusrocha89** [comment]
@Tyriar well, your fork works too 😄  Now I don't know where to search hahaha

**Comment by matheusrocha89** [comment]
I think could be some keybinding on vscode because I use the Mac default keymaps to add these characters on mac. Ex: `option+e, option+c, option+i, option+e`

**Comment by Tyriar** [comment]
@matheusrocha89 hmm, is it an issue with input (alt+e), paste or both?

**Comment by Tyriar** [comment]
@matheusrocha89 this might be the answer for this issue https://github.com/sourcelair/xterm.js/issues/547#issuecomment-280583184

Decoding UTF-8 [here](https://github.com/Microsoft/vscode/blob/69a2afe9d37ccf1ec0a5f72a9dd163e5fc664248/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L468) might fix it.

**Comment by Tyriar** [comment]
I can't repro on my Mac so it must be something to do with the environment. This is what's in my `$LANG` variable which may be relevant: `en_GB.UTF-8`

**Comment by matheusrocha89** [comment]
@Tyriar I didn't try the paste, and I think it's not a problem with the `keybind` too. I had a similar problem on paste when I did on the editor but I use the vim mode and after I configure to use the same clipboard of the system the problem didn't happen anymore.

**Comment by matheusrocha89** [comment]
@Tyriar The link above could be the solution. By the way this is my `locale` output on my mac:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by Tyriar** [comment]
@matheusrocha89 do you have this set in your settings.json?

```
"terminal.integrated.setLocaleVariables": true
```

It's meant to be true by default on Mac which sets `$LANG`.

**Comment by matheusrocha89** [comment]
I didn't override this setting @Tyriar And by default it's true here.
![image](https://cloud.githubusercontent.com/assets/3718366/23106370/32b4fb4a-f6cb-11e6-85d8-8918d0c54e45.png)

**Comment by Tyriar** [comment]
@matheusrocha89 you could try settings `LANG=en_US.UTF-8` and see if that fixes it. Also what system language are you using?

**Comment by matheusrocha89** [comment]
Yes I can try. I am Brazilian but I configured my mac to use English as the primary language.

**Comment by matheusrocha89** [comment]
@Tyriar even with the `en_US.UTF-8` on lang environment variable the problem persist

**Comment by Tyriar** [comment]
Here is the section of code that's meant to fill in the `$LANG` variable, if it's not being set properly then there's likely an issue there under your config https://github.com/Microsoft/vscode/blob/06434144c4eeb8f7fbb87e43bc6c04cabb5c6433/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L618

It might matter if `$LANG` is set when the terminal is initialized, seems like it's likely the cause considering everything.

**Comment by matheusrocha89** [comment]
OMG!!! @Tyriar I fixed

**Comment by matheusrocha89** [comment]
I use the zsh and on the zsh config file I set the LANG env variable, after that it's working now. I think that everybody with this problem should see if this solution. We made it 👏 👏 👏 👏 👏 👏 👏 👏 👏  🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by Tyriar** [comment]
Cool :smiley: 

@jrieken could you check your `$LANG` env variable if you're still reproducing?

**Comment by jrieken** [comment]
I have this

```
jrieken:~/Code/vscode$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by Tyriar** [comment]
Looks like something is probably overriding it in your setup then, maybe in .zshrc?

**Comment by matheusrocha89** [comment]
@jrieken This was the same configuration as mine. And I think it's by default like that, so I set the value on my `zshrc` then every time the file load set the value on `LANG` variable

**Comment by Tyriar** [comment]
I'll see if I can repro it on my mac again, I was trying on bash before.

**Comment by Tyriar** [comment]
Still can't reproduce even if I try zsh (with and without oh-my-zsh), I also can't reproduce it even if I set `terminal.integrated.setLocaleVariables` to `false`, which makes `$LANG=""`

**Comment by matheusrocha89** [comment]
@Tyriar After I set the `$LANG` my problem stopped. I will try remove it and see if I can reproduce again.

**Comment by matheusrocha89** [comment]
@Tyriar I can reproduce, I just remove the line on my zsh and set the `LANG` to `""` then my locale prints:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
I opened the `vscode` again and the problem persist. On my work colleagues here too is the same problem.

**Comment by matheusrocha89** [comment]
There is one thing in common on all of us that are having the problem, by the não `João Moreno` I believe he is Brazilian or Portuguese cause `João` is a very common brazilian or portuguese não `João => John`. And our macs locale have the same value by default.

**Comment by matheusrocha89** [comment]
Also maybe his configuration on `System Preferences` could be the same as mine, 2 languages, and English on top, so this way maybe the locale get's confused even if you set the preference to automatically get the `LANG` on `iTerm`

**Comment by matheusrocha89** [comment]
Yes @Tyriar that's the problem, my language is set to be primary English and secondary the Portuguese but my region is set to Brazil, then when the `O.S` try to set the locale it gets confused because the language is English and the Region Brazil, it will try to set something `en_BR` that doesn't exists, that's why my `LANG` could be empty. The vscode is correct, it's trying to get the `LANG` env but my environment is wrong and doesn't have a value for this variable. This could be fixed in 2 ways, the user set the `LANG` variable like I did since it was my fault change the language to this way or the vscode by default if couldn't find the LANG value set `en_US` as fallback.

**Comment by matheusrocha89** [comment]
@Tyriar what do you think about the fallback?

**Comment by Tyriar** [comment]
Definitely a good idea :+1:

**Comment by Tyriar** [comment]
@jrieken I believe this is fixed in 1.10, could you please verify on your setup?

**Comment by jrieken** [comment]
The garbage is gone but it's still not the proper spelling... Unsure if he changed his name.
![screen shot 2017-02-28 at 09 02 20](https://cloud.githubusercontent.com/assets/1794099/23396573/b7d46c64-fd94-11e6-935e-24c3d184ffb2.png)

**Comment by matheusrocha89** [comment]
@jrieken 🤔  I think he changed his name... Cause on mine it's working:
![image](https://cloud.githubusercontent.com/assets/3718366/23403239/01ce5142-fd8e-11e6-9cb5-6bc73a9536c3.png)

**Comment by Tyriar** [comment]
@jrieken I've noticed he uses both variants, you should be able to find the other one with `git log --author=Moreno`

**Comment by jordanmkasla2009** [comment]
@jrieken @Tyriar , @joaomoreno definitely uses both variants one has an @microsoft.com email while the other has an @joaomoreno.com email

**Comment by joaomoreno** [comment]
This actually works quite nicely here:

![screen shot 2017-03-09 at 09 40 46](https://cloud.githubusercontent.com/assets/22350/23742281/892a4194-04ac-11e7-8c82-93f479c6fc80.png)

My `env` says:

```
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_CTYPE=
```

**Comment by matheusrocha89** [comment]
Great, so the fallback fix the bug right? I think we can close this issue, what do you think @Tyriar

**Comment by Tyriar** [comment]
@matheusrocha89 yes I'll close this off as there haven't been any confirmations it's not working. Thanks again for the PR!
