### ISSUE TITLE
Windows: Can't always resize window

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#146060]
Issue Type: <b>Bug</b>

Occasionally, when attempting to resize the window using the mouse, the window stays locked.

![Recording 2022-03-25 at 16 06 37 (1)](https://user-images.githubusercontent.com/22350/160147742-698b881b-1fdd-433e-84d1-7db0eae2ca94.gif)

VS Code version: Code - Insiders 1.66.0-insider (616cad0638d0c6d436abcf42fb85a8e333b7d705, 2022-03-25T08:25:04.070Z)
OS version: Windows_NT x64 10.0.22581
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (22.71GB free)|
|Process Argv|--crash-reporter-id 1bc8cd37-ce05-4987-927f-0e71eded00eb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.5.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.4.0
vscode-pull-request-github|Git|0.39.2022032409
terraform|has|2.21.0
javascript-notebooks|joa|0.0.2
vscode-pyodide|joy|0.0.11
remote-containers|ms-|0.229.0
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.76.1
azure-account|ms-|0.10.1
vscode-github-issue-notebooks|ms-|0.0.115
vscode-selfhost-test-provider|ms-|0.3.9
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-conventional-commits|viv|1.24.0
gitblame|wad|8.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrt:30405800
pythonvspyt640:30438691
vscscmwlcmt:30428973
vscgsvid1:30433757
pynewfile477:30451556

```

</details>

**Comment by IllusionMH** [comment]
OMG 🤯 That's nasty background and title bar content (sorry for offtopic)
![image](https://user-images.githubusercontent.com/1312662/160167369-e787735d-664f-47f8-aac7-782e1c221e13.png)

**Comment by bpasero** [comment]
Wow! I accept a PR to fix it ;)

**Comment by sbatten** [comment]
It happens every two attempts to resize for me in OSS

**Comment by Spongman** [comment]
what's weird is that when it doesn't work it constrains the mouse cursor to within the bounds of the window.

**Comment by atom0s** [comment]
Have this issue on Windows 10 as well. Can't resize the window at all now since the latest update to the Insider build.

Double-clicking the window title does not work. Resizing attempts on any part of the window for me just lock the mouse to the windows current bounds. The minimize/maximize buttons still work though.

**Comment by deepak1556** [comment]
Fixed with https://github.com/electron/electron/pull/33438

**Comment by hediet** [comment]
I can still reproduce with:

Version: 1.66.0
Commit: Unknown
Date: Unknown
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by deepak1556** [comment]
@hediet is this with OSS or insiders ? Please note, the issue is only addressed in our product builds and not OSS. Issue will be addressed in OSS once we update to `17.3.0` in main branch which is currently pending builds.
