### ISSUE TITLE
"select environment" prompt is not showing before debugging

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#146368]
The C/C++ extension has registered two `DebugConfigurationProvider`, when hitting the `Run and Debug` Button, vscode used to show the "Select environment" prompt to choose between the two providers (the expected behavior):

![image](https://user-images.githubusercontent.com/16143955/160941272-a4f6a41d-9c5a-4ad9-9bff-0f54f896958a.png)

- In VsCode version 1.66.0, when a folder is open, this scenario has changed, the "select environment" prompt is not shown anymore and only one provider will provide the debug options.

-  In VsCode version 1.66.0, when there is no folder open, i.e. in a single file mode, the behavior is as before, i.e. expected bahavior. 

-  In VsCode version 1.66.0-insider, with/without folder open, the behavior is as before, i.e. expected bahavior.

**Comment by sean-mcmanus** [comment]
Doesn't this mean it's fixed in Insiders?

**Comment by elahehrashedi** [comment]
The insider version that the feature was still working is this:
![image](https://user-images.githubusercontent.com/16143955/161144554-9e5cfb58-96fb-47ce-afa1-b89267ceddae.png)

**Comment by elahehrashedi** [comment]
@sean-mcmanus  It is fixed in insider 1.67.0-insiders that came today.

**Comment by weinand** [comment]
I'm not aware of any changes in 1.66 debug that would explain this.
And we (debug) have not fixed anything in the latest Insiders (1.67)

@roblourens are you aware of any changes?

@elahehrashedi which `DebugConfigurationProvider` is missing on Windows?
Do you see the same problem on linux or macOS?

**Comment by sean-mcmanus** [comment]
I'm not able to repro the issue with 1.66 with 1.9.7 of our extension on Windows.

**Comment by sean-mcmanus** [comment]
@elahehrashedi Is C_Cpp.debugShortcut set to true or false? I only see our dropdown when it is true.

**Comment by bobbrow** [comment]
The button is participating in an experiment so it doesn't always appear unless you force the .  I'm actually not able to repro this either, so maybe there's something else going on with your environment @elahehrashedi.

**Comment by elahehrashedi** [comment]
I could repro it only on the release version 1.66.0, So as @bobbrow mentioned it might be my environment variables. If I find the cause of the issue, I will write an update here.

**Comment by roblourens** [comment]
I'm not aware of any relevant changes on my end
