### ISSUE TITLE
Right click menu appears below integrated terminal when peeking a function definition

### ISSUE THREAD

**Issue by Nippius** [microsoft/vscode#146638]
Issue Type: <b>Bug</b>

With the integrated terminal window open:

1. Open a source file (using a C++ file as an example) in the editor
2. Find a function and press F12 to peek the source inline
3. In the embeded result inline right click on piece of text

I'm expecting the right click menu to show above the integrated terminal but instead, it apears bellow the integrated terminal.

Example screenshot:
![image](https://user-images.githubusercontent.com/1528640/161404923-990c4e5b-f063-4787-9132-9f46060e0cb6.png)

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.10GB free)|
|Process Argv|--crash-reporter-id 25d60548-5ff8-4cf8-85a4-5399bcbbaa30|
|Screen Reader|no|
|VM|0%|
</details>

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
fluent-icons|mig|0.0.17
remote-wsl|ms-|0.66.0
cpptools|ms-|1.9.7
powershell|ms-|2021.12.0
platformio-ide|pla|2.4.3
vscode-icons|vsc|11.10.0

(1 theme extensions excluded)

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/"needs-more-info"

**Comment by Nippius** [comment]
Unfortunately it's still broken in the latest insiders build:
![image](https://user-images.githubusercontent.com/1528640/167231942-ea163466-3815-4285-95c3-7801f669b67b.png)

Insiders build info:
![image](https://user-images.githubusercontent.com/1528640/167231964-05a7604d-c32f-434c-a338-f75c97cd11ed.png)

**Comment by Nippius** [comment]
It still happens in 1.68. You need to be peeking a definition:
![image](https://user-images.githubusercontent.com/1528640/167486434-bd53f7d8-519a-44aa-b77c-c154e3a09a7d.png)

When not peeking a definition (not showing the "peeking" window) it works as expected:
![image](https://user-images.githubusercontent.com/1528640/167486555-7e288bde-3b0f-4a56-b0b8-8ca6102d2e23.png)

**Comment by Tyriar** [comment]
@Nippius thanks for the follow up, I missed the peek park. Can repro 🙂

**Comment by Nippius** [comment]
No problem :) let me know if/when you need me to give it another go

**Comment by r3m0t** [comment]
I no longer see this

Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.78.0 Chrome/108.0.5359.215 Electron/22.4.8 Safari/537.36
