### ISSUE TITLE
Command palette should rank results with closer search terms higher

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#14727]
_From @prashantv on October 18, 2016 19:56_

See image:
![image](https://cloud.githubusercontent.com/assets/140159/19494026/13f00a92-9532-11e6-8a1d-124d94b814b6.png)

I think a user is much more likely to want to run unit tests when they search for "Go Test" than "Generate unit tests". Is there any way to improve the search matching, or rename the option so running unit tests is preferred over generating unit tests?

_Copied from original issue: Microsoft/vscode-go#543_

**Comment by jrieken** [comment]
@bpasero For suggest I have implemented something similar to what @ramya-rao-a wants. It scores entries based on the search highlights, supports camel case and nearest match. We might want to consolidate, code is here: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/completionModel.ts#L169

**Comment by bpasero** [comment]
@jrieken maybe you can move this code to `filters.ts` or scorer.ts so that it can be reused? I use scorer.ts today to rank based on fuzziness but we only use this for matching on file paths in quick open currently. I found the fuzziness too aggressive for the command palette.

**Comment by bpasero** [comment]
Related/duplicate: https://github.com/Microsoft/vscode/issues/1964

**Comment by ramya-rao-a** [comment]
_From @atombendor_


<img width="678" alt="screen shot 2016-11-14 at 13 11 12" src="https://cloud.githubusercontent.com/assets/50314/20276811/e8b7bd8a-aa6b-11e6-8188-78c294ce5efd.png">

The file `cmd/gradient/main.go` is scored lower even though the text I typed matches contiguously. The top matches have matched random characters in other file names which seem to have accidentally have bumped their score up, even though the matches make less sense.

**Comment by ramya-rao-a** [comment]
_From @andy-ms_


1. Create `abc.txt`, `alpha-beta-cappa.txt`, `xyz/index.js`, and `xerxes-yak-zubba/index.js`.
2. Hit Ctrl-P, type "abc", and hit enter. This opens `abc.txt`.
3. Hit Ctrl-P, type "xyz", and hit enter. This opens "xerxes-yak-zubba/index.js".

Also, open [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and search for `ace/index.d.ts`. Even though this is exactly the name of a file, I get taken to `cordova-plugin-email-composer/index.d.ts` instead. I can't reproduce that in a small project.

**Comment by stewartadam** [comment]
From #19757: this also affects users wanting to install extensions, and unfortunately does the exact opposite of what's expected: the first hit for `install` is actually "Disable all installed extensions" instead of "Extensions: Install"

**Comment by bpasero** [comment]
* [ ] To **verify**: search for commands like "install extension" or "settings" and verify that the more relevant (shorter labeled) entries are sorted to the top

**Comment by atombender** [comment]
@bpasero Does this fix the issue with contiguous matches not scoring higher that non-contiguous ones ([example](https://cloud.githubusercontent.com/assets/50314/20276811/e8b7bd8a-aa6b-11e6-8188-78c294ce5efd.png))? I don't see anything in your commit that changes the scoring function.

**Comment by bpasero** [comment]
@atombender no, this is limited to only command palette and the scoring function there is not tweaked beyond of what we have. I think what you ask for is in https://github.com/Microsoft/vscode/issues/14879

**Comment by atombender** [comment]
Ah, makes sense — although I'd expect/hope that both would be using the same underlying fuzzy-scoring code, and thus be fixed by the same fix. But I'll comment there.

**Comment by stewartadam** [comment]
Note - I'm still seeing this issue ("Disable all installed extensions" is ordered first) in the latest 1.10.2.

**Comment by stewartadam** [comment]
Note that despite 2fbfb7b from #20553, I'm still seeing "Disable all extensions" come up first when searching with 1.22.
