### ISSUE TITLE
[json] schema validation in a folder of a workspace stops working when more folders are added to it

### ISSUE THREAD

**Issue by Git-GoR** [microsoft/vscode#147865]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2 (Tested in Insiders 1.67.0 with same results)
- OS Version: Windows 10 Education N x64 - 21H1 

Steps to Reproduce:

1. Create a Workspace and add a simple folder with a schema for JSON files defined in the folder settings.
![imagen](https://user-images.githubusercontent.com/58085266/164516873-2f8e0b3f-9b5f-4d19-a9a4-b26665ee7645.png)

<details>
  <summary>schema-file.json</summary>

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Test",
    "description": "An example schema",
    "type": "object",
    "properties": {
        "requiredProperty": {
            "type": "string"
        }
    },
    "required": [
        "requiredProperty"
    ]
}
```
</details>

2. Check that the `test.json` file is being validated correctly.
![imagen](https://user-images.githubusercontent.com/58085266/164517215-4ec30990-711e-4e91-8d5b-81f2a86e61c6.png)

3. Add a second folder to the workspace. In my test I added an empty folder in the same root as the workspace. The validation still works as expected.

4. Reload the window or close/open VSCode. The schema validation has stopped working as if the file did not match the `fileMatch` in the folder settings. Removing the second folder and reloading makes it work again.
![imagen](https://user-images.githubusercontent.com/58085266/164518273-8ebc4d5d-29b9-481d-a27c-b8cc9368a516.png)

As a note, if you open `folder-A` directly in VSCode rather than the workspace, the validation works as expected.

**Comment by ajcool2k** [comment]
The new validated by schema information is great. But this reported issue in work spaces prevents me from upgrading from 1.65. Any chance this will be addressed anytime soon?

**Comment by Shelim** [comment]
> The new validated by schema information is great. But this reported issue in work spaces prevents me from upgrading from 1.65. Any chance this will be addressed anytime soon?

Is it working correctly pre-1.65? Because this issue is very annoying here (we have to open multiple instances of vscode as workaround which is problematic for various reasons), and we could very much just ship a portable version of previous version of vscode

**Comment by ajcool2k** [comment]
> > The new validated by schema information is great. But this reported issue in work spaces prevents me from upgrading from 1.65. Any chance this will be addressed anytime soon?
> 
> @ajcool2k 
> Is it working correctly pre-1.65? Because this issue is very annoying here (we have to open multiple instances of vscode as workaround which is problematic for various reasons), and we could very much just ship a portable version of previous version of vscode

Yes it worked before. So you should be good with an old release for the time being. Not a solution but at least workspaces are usable.

**Comment by Shelim** [comment]
@ajcool2k 
Looks fixed in vscode-insiders 1.71

**Comment by MrVauxs** [comment]
> @ajcool2k Looks fixed in vscode-insiders 1.71

Still have the bug on 1.71 on my machine.

Top: Workspace, Bottom: Folder
![image](https://user-images.githubusercontent.com/32039708/186203895-9e90d096-5563-4f0b-b8ec-1000ca3b2816.png)

**Comment by ajcool2k** [comment]
> > @ajcool2k Looks fixed in vscode-insiders 1.71
> 
> Still have the bug on 1.71 on my machine.
> 
> Top: Workspace, Bottom: Folder
> ![image](https://user-images.githubusercontent.com/32039708/186203895-9e90d096-5563-4f0b-b8ec-1000ca3b2816.png)
> 

Same. Still not solved for me with 1.71.

**Comment by xiaoxiyao** [comment]
Still have the bug on 1.71.2

**Comment by viswanr** [comment]
I'm on 1.73 and this is still an issue. Works ok when you open a folder and the json.schemas is at the root of it inside .vscode folder. It doesn't work in a multi-root workspace. We have a lot of JSON files and autocomplete doesn't work anymore. This used to work before.

Surprised as to why this is not getting any traction. Seems like a huge regression in functionality.

**Comment by GabenGar** [comment]
I noticed this is OS-specific too. On ubuntu 22 machine multi-root validation works fine but not on windows 10 machine it doesn't, on the same codebase.

**Comment by Shelim** [comment]
Yeah, this is probably the reason I tricked myself it was working back then.

@aeschli , any status update on this? I am pinging, because there has been no update on the matter since its original report in April, and the issue is 100% reproducible on any vscode version since 1.65

**Comment by revilowaldow** [comment]
> I noticed this is OS-specific too. On ubuntu 22 machine multi-root validation works fine but not on windows 10 machine it doesn't, on the same codebase.

Can confirm this observation, the issue only occurs in windows and not on Ubuntu, have not tested macOS

**Comment by MrVauxs** [comment]
> Can confirm this observation, the issue only occurs in windows and not on Ubuntu, have not tested macOS

Same here using Remote-SSH to an Ubuntu workspace.

**Comment by rssh22** [comment]
Same here using Remote-SSH to a Redhat workspace. However, it works right setting the "$schema": "url-schema" attribute in the .json file.
