### ISSUE TITLE
Renaming a file inconsistency 

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#148297]
Testing #147738

I tried renaming the filename portion of:

```
[ref2]

[yes][ref2]

[ref2]: /README.md#deployment
```
so `/README.md`

on macOS, I got:
![image](https://user-images.githubusercontent.com/2644648/165589179-228da367-45da-42ec-97c2-7d178adde367.png)
(sorry currently using Pseudo language)
but then changing that to README2.md just gives me a notification that says "No Results"

Now I try that on my linux machine (Ubuntu) and when I try to rename a file I get one of two things:
* "Renaming files is currently not supported" if there is no slug (like deployment above)
* The rename for the slug pops up even if the cursor is on the file path portion

Which behavior is correct?

I would expect renaming of files to also rename the file on disk...

**Comment by mjbvz** [comment]
Can you please test this again once the first 1.68 insiders is out? I think it may have been fixed by 892d6ec2a2dcc22b216f5d4dcee025c96efc4ccb

**Comment by TylerLeonhardt** [comment]
Repro steps still repro

**Comment by TylerLeonhardt** [comment]
So Linux & macOS are now consistant but I still don't know what the actual behavior of this should be... I'll open a new issue
