### ISSUE TITLE
Add a find

### ISSUE THREAD

**Issue by AxCoder** [Microsoft/vscode#14836]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2.

**Comment by rebornix** [comment]
@AxCoder can you provide a screenshot showing your request as I don't have Windows available right now. It sounds like `highlight all selections` to me but I'm not quite sure.

**Comment by AxCoder** [comment]
The difference is that highlight only shows occurrences that are on the current screen while in VS I see all occurences condenced on the bottom pane (similar to the Search sidebar in VS Code). Using of the search sidebar is a workaround, but requires too many clicks
(BTW I tried to copy the full path into the "files to include" it did not find anything)
![snip_20161103092432](https://cloud.githubusercontent.com/assets/7656611/19957382/609713a0-a1a7-11e6-9a26-f6807a258769.png)

**Comment by rebornix** [comment]
So let me try to summarize it, you want to see all the search results while using the search palate.

**Comment by Bill-Stewart** [comment]
Have you tried `workbench.view.search` (default keybinding <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd>)?

**Comment by AxCoder** [comment]
@rebornix 

Yes, thank you


@Bill-Stewart 
> Using Search sidebar to find all items in **current file** requires **too much clicks**.

I have not find out how to **quickly* search only the current file
![snip_20161103210238](https://cloud.githubusercontent.com/assets/7656611/19978708/e16f0788-a208-11e6-9475-a5c09b9b0290.png)

**Comment by Bill-Stewart** [comment]
I don't understand? Pressing the shortcut key means you don't have to use the mouse.

**Comment by AxCoder** [comment]
@Bill-Stewart  the problem with Ctrl+Shift+F hotkey is that is searches in **ALL** files in the folder, while I want to search only in **CURRENT** file (active tab). In the screenshot above I'd like to see only entries found  in Program.cs not other files.

**Comment by alexandrudima** [comment]
I think this could be implemented by having an action in the editor that invokes the global find in files but scoped only on the current file. 

Thus, the search viewlet could show only hits in the current file. fyi @sandy081

**Comment by hjma29** [comment]
love to have this feature

**Comment by sammykun** [comment]
I would also like to see this feature implemented. Additionally, a "Find occurrence in all current opened files" would be a nice extension of this.

**Comment by borgu** [comment]
I do it by coping just file name (w/o path) to "file to include" field.

**Comment by hma02** [comment]
This could be similar to the search functionality in [Textmate](https://macromates.com/), where you have the option to see all occurrence as an output in a single page and you can then do extra actions like copying those returned occurrence as rawtext. This concept is similar to `grep`.

**Comment by Yagger** [comment]
This can be done by right click on the selection and choosing "Change all occurrences" from the context menu (or CMD+F2).
<img width="814" alt="untitled-2_-_cm-ol" src="https://user-images.githubusercontent.com/1056226/32731342-38887148-c892-11e7-90a4-41cd1788846c.png">

**Comment by JoshuaBarnette** [comment]
I agree this feature is necessary. I know we are all perfect coders and never use prefixes or suffixes that need to be changed in certain areas and not others, but the function should be there for everyone else, as it is in nearly every other coding app.

**Comment by gibertoni** [comment]
I would like to have this feature as well, since I am using VS Code not only for regular code but everyday file editing as well.

**Comment by teiles** [comment]
+1 for this feature - I'm trying to adopt VS Code is the current state of this feature is a paper-cut

**Comment by niklabh** [comment]
https://github.com/Microsoft/vscode/pull/41360

Find all button in other major editors comes with find widget itself. Although vscode provide the functionality as "change all occurrences" from the context menu. It is not readily clear to new developers. Thus this pull request aims to add find all button in find widget. The button is using same command "editor.action.changeAll" as used by "change all occurrences".

I have added svg search icon to find all button using correct color scheme. Please change if required.

![findall](https://user-images.githubusercontent.com/874046/34734696-00069252-f56d-11e7-894e-174789b178e1.gif)

**Comment by lachieh** [comment]
This is crucial. You can't select all occurrences of a RegEx search without this functionality.

**Comment by dakaraphi** [comment]
@lachieh You can use command 'select all occurrences of Find Match' to select all occurrences in a single file.

**Comment by AxCoder** [comment]
Please, take into account that I want this feature as in VS - I want to see ONLY the lines that contain search string. For example if a have 1000 lines file with the string occured on the first line  and on the last, I want to see only 1 st and 1000st lines on the screen, not the first line and 100 lines without strings that fitted the screen.

So select all occurences is not the same. Using selection sidebar with automatic limiting the scope to the current file is the same.

**Comment by cdunford** [comment]
+1 - this is a must have feature

**Comment by Exlsunshine** [comment]
Yagger is right

**Comment by aboulfad** [comment]
So almost two years after this request, no love for this basic but yet very important feature ?

**Comment by dakaraphi** [comment]
FYI, I've experimented with a tree view that will show all current find matches.
Not ideal due to some limitations, but still you may find somewhat useful.
https://marketplace.visualstudio.com/items?itemName=dakara.dakara-navigator

**Comment by VinayGupta23** [comment]
Must have feature! **I was trying to convince a friend to start using VS Code instead of Notepad++, and the first question they asked me is: "Can I do a Find All?"**

**Comment by ncking** [comment]
This could be a deal breaker for me. Just trying out again after a year.
Sure the editor ca do lots of fancy edge case stuff, but the search functionality is poor compare to other IDEs.
Incredulous, that I cant just right click and search the current *open, *focused document for a string ...
I mean really!!!!, I must have a corrupt install, this cant be true???

**Comment by radim-moric** [comment]
Really missing feature! Using Search in side bar is not an option - cannot configure font (to monospace) and cannot use keys for fast movement or even copy text.

**Comment by VinayGupta23** [comment]
Let us make sure to up vote this issue so it gets noticed. This seems to be getting dormant from the core team.

**Comment by blis5fool** [comment]
I mainly use IntelliJ IDEA and Notepad++. I started using VS Code for one of our projects to get the feel for it and I sorely miss "Find All in Current File" feature. I also miss "Find All in All Opened File" feature from Notepad++ but it's not as critical as current file search.

**Comment by UchiaItachi** [comment]
This is much needed.

**Comment by dakaraphi** [comment]
@UchiaItachi  You can now have views like this with the [Navigator](https://marketplace.visualstudio.com/items?itemName=dakara.dakara-navigator) extension
<img width="780" alt="findmatches" src="https://user-images.githubusercontent.com/10656375/40742991-3f8d0508-641e-11e8-9f23-2b080887450e.png">

You can add multiple `Matches` results which gives you a tree view listing of all occurrences in the current file.

**Comment by andywhitaker** [comment]
If the hotkey for Find is CTRL+F and "Find All in Files" type search is CTRL+SHIFT+F I suggest perhaps making it so CTRL+ALT+SHIFT+F will open the Find All in Files search bar on the left and the ALT key modifier would indicate to automatically populate the "files to include" field with the filename of the file with current focus on the right side when the keypress is initiated?

**Comment by 9527KKK** [comment]
+1.

Pls add

Find all in current file
Find all in all **open** files
Replace in all **open** files.

These are fundamental features of notepad++.

**Comment by bkarlson** [comment]
2 years, this is not implemented yet?

**Comment by Noboxulus** [comment]
Since this feature is not built-in and I cannot seem to find any other extensions for this, I use the "find-more" extension by FengYouzheng [github](https://github.com/FFengIll/vscode-find-more).
It might not be the best or the most elegant, but it works and I'm rather happy to use it.
Just in case if anyone is looking for an extension that provides the "find all occurance" feature.

**Comment by 21region** [comment]
Looks like 50 votes is not enough to start implementing it :)

**Comment by 9527KKK** [comment]
Cannot believe that such a basic feature even needs vote. LOL.

**Comment by wilrodriguez** [comment]
This is actually one of the things keeping me using sublime text. Would really like to see this get implemented in VS Code

**Comment by cjbarth** [comment]
In my mind, one of the biggest advantages of a true Find All, is multiple cursors being inserted. That is a huge go-to feature for me and Sublime.

**Comment by lachieh** [comment]
@cjbarth you can use the shortcut <kbd>Ctrl</kbd>+<kbd>Cmd</kbd>+<kbd>G</kbd> to select all occurrences in a single file once you've opened the find box and entered a search.

"Select All Occurrences of Find Match" is the command to look for in your keyboard shortcuts if you aren't on macOS.

**Comment by cjbarth** [comment]
@lachieh Thanks for that. Too bad there isn't a UI element in the search box to make it more discoverable.

**Comment by greim** [comment]
On Mac, Ctrl+Cmd+G doesn't work for me unfortunately.

**Comment by lachieh** [comment]
@greim Make sure you have something in the search bar first. If it still doesn't work, double check that you have the keyboard shortcut assigned correctly.

**Comment by wood-jp** [comment]
I just found out that Alt+F3 (On Ubuntu) seems to do what we are all wanting. At least, I was able to put my cursor on a word, press those keys, and then all instance of that word in the open file were multi-selected.

**Comment by AxCoder** [comment]
@wood-jp this is not the same. See the first two comments in this thread.

**Comment by VimalShekar** [comment]
Notepad++ has a "Find all in current document" and a "Find all in all opened documents".
It would be amazing if VSCode gets this feature.

**Comment by jujinkim** [comment]
yes, this feature should be added as a default feature in vs code.
other text editors have this feature, but visual 'god' studio code doesn't.
sometime i thought that i need to switch to notepad++ because of this 'find all in current file' feature.

i really love vs code, but this feature's absence makes me sad.
"no find all in current file editor" is equal to "ugly os x" or "windows without game". 

really.

**Comment by shimonacarvalho** [comment]
Same here, upvoted. Strongly considering actually making a shortcut to open in notepad++ (also doesn't seem to be a thing) and then using notepads find all feature.

**Comment by xaisng** [comment]
Please bring Notepad++ Style  "Find all in current document" and a "Find all in all opened documents".

**Comment by renehagen** [comment]
> yes, this feature should be added as a default feature in vs code.
> other text editors have this feature, but visual 'god' studio code doesn't.
> sometime i thought that i need to switch to notepad++ because of this 'find all in current file' feature.
> 
> i really love vs code, but this feature's absence makes me sad.
> "no find all in current file editor" is equal to "ugly os x" or "windows without game".
> 
> really.

You can use the search function (ctrl-shift-F) to get a list of all occurrences in a document. This searches all files in the workspace so a bit more then you ask for but is fast enough even with this overhead.

**Comment by jujinkim** [comment]
> > yes, this feature should be added as a default feature in vs code.
> > other text editors have this feature, but visual 'god' studio code doesn't.
> > sometime i thought that i need to switch to notepad++ because of this 'find all in current file' feature.
> > i really love vs code, but this feature's absence makes me sad.
> > "no find all in current file editor" is equal to "ugly os x" or "windows without game".
> > really.
> 
> You can use the search function (ctrl-shift-F) to get a list of all occurrences in a document. This searches all files in the workspace so a bit more then you ask for but is fast enough even with this overhead.

yep, I know it, but we need 'search in only current file', not all files. And, ctrl+shift+f shows results in the sidebar. but you know, texts are written horizontally, not vertically. so if results are shown in the bottom area with large width like notepad++ not side area, it would be better.
for me, this feature was very helpful when analyzing logs when I used notepad++.

**Comment by MarkSidhom** [comment]
Please bring Notepad++ Style "Find all in current document" and a "Find all in all opened documents" for VSCODe.

**Comment by kg-currenxie** [comment]
This is so perfect (from Sublime). I miss it so much.. :( 

![Screenshot 2019-04-11 at 17 04 35](https://user-images.githubusercontent.com/48229166/55944767-e721de00-5c7b-11e9-8ebd-5d3b0e313179.png)

**Comment by vldmr-bus** [comment]
> yep, I know it, but we need 'search in only current file', not all files. And, ctrl+shift+f shows results in the sidebar. but you know, texts are written horizontally, not vertically. so if results are shown in the bottom area with large width like notepad++ not side area, it would be better.
> for me, this feature was very helpful when analyzing logs when I used notepad++.

Right click on Search tab on your right panel and select "Move panel to Bottom" to see results full width.

+1 for adding search all in current file. This is essential feature

**Comment by c0rent1n** [comment]
+1 
The search options of notepad++ are better for now, I hope VS code will get the same possibilities soon!

**Comment by lachieh** [comment]
@alexandrudima or @rebornix can we please lock this thread? The problem is pretty clearly defined and all these "+1's" are redundant. Newcomers can use the reaction on the primary post.

**Comment by sreenadh** [comment]
Right click on tab "Copy relative path"
Ctrl Shift F - enter search query
Paste the relative path in "Files to include"

As an easier way add an inline option in "files to include" to search in current file only (like in search query textbox for "match case" "use regular expression")

Also, need an enhancement for "Clear search results" to clear "files to include" and also "files to exclude"

**Comment by mevin-e** [comment]
Find all in current file
Find all in all open files
Replace all in current file
Replace all in all open files.

The result should be in a new tab and editable

These missing options force me to switch back to N++ often.  Please implement asap.

**Comment by the0demiurge** [comment]
This find-all feature is really useful, which I used to use when I was using SublimeText. Looking forward to having this feature soon.

**Comment by TimNZ** [comment]
Never made an extension, but after a quick look through Extension API and published commands and vscode src, there is no way to trigger display of Find sidebar view prepopulated with values.

if a built in command was exposed that supported args for all available items on Search/Replace, to prepopulate search sidebar view and display, perfect, we can all make extensions to do interesting things.

**Comment by yulei900609** [comment]
I would like to have this feature as well which makes me find something easily.

**Comment by GlenNicholls** [comment]
What is the status of this @alexandrudima ? I do a lot of searching of log/build reports and in slickedit, notepad++, and sublime, they all have very nice "advanced search" capability. The toolbar that comes up by default is really annoying and it would be nice to have a feature similar to slickedit where you can enable the basic toolbar by default or an advanced toolbar. If the advanced toolbar is selected, it should open a seperate window with all advanced find features. The `Ctrl+Shift+F` feature is nice because it is bound to a key and embedded in the vscode window, but this could easily be the advanced find feature...

**Comment by bhanratt** [comment]
Just adding to this. I have recently migrated from Sublime to VS Code and this one missing feature is causing me to include a local copy of Sublime installed for occasional use.

**Comment by yurenchen000** [comment]
+1

- find all @ find
OR
- find all in files @ current file only

**Comment by dzhao8888** [comment]
+1

**Comment by darwinyip** [comment]
Similar to the sublime use cases. Find all (also with regex)  in current file and place cursor on them

**Comment by bnason-nf** [comment]
@darwinyip: is this what you mean?
https://stackoverflow.com/questions/46539714/select-all-occurrences-of-selected-word-in-vscode

**Comment by darwinyip** [comment]
@bnason-nf the main use case i tend to have is to use regex for something like this:
```
Field:           "text"
...
Field:     "text"
...
Field:               "text"
```
Find All . `Field:\s+"` . Place cursors . Do stuff.

**Comment by bnason-nf** [comment]
@darwinyip: yes that should work fine without a regex. First select one of the "Field" instances. Then press Control-Shift-L (Windows) to select all the instances of "Field". Then you can press Control-RightArrow twice, and Control-LeftArrow once. You should have multiple cursors at the beginning of all the "text" instances.

**Comment by darwinyip** [comment]
@bnason-nf What if I have something like this?
```
Field:           "text"
...
Field:     "text"
...
Field:  something-not-text
...
Field:               "text"
```

This would give me unwanted text.

**Comment by bnason-nf** [comment]
@darwinyip: to be clear, I don't think this solution is perfect, but it can still work in the above case:

1. select Field
2. Control-Shift-L
3. Right
4. Right
5. Control-Right
6. Control-Left

**Comment by QuillVoy** [comment]
Indeed, Sublime is much, much more useful in this regard. Nonetheless, my workaround to select all is:

1. Press _ctrl+F_.
2. Insert the regex code.
3. Click back on the text (this is necessary).
4. Press _ctrl+shift+L_ to select all text or _ctrl+D_ to consecutively adding each occurrence to the selection.

**Comment by davmaz** [comment]
Once the results of a "find in current file" are found, is there ANY way that I can make the found instances 'blink'? Right now it is very hard for me to find the highlighted find results. They're all there in the file, but it would be great to have them show up in RED, or to have them BLINK the text?
Is this a font related request? It's clear that vscode uses some default to show the results, but can I change that?
Thanks in advance! vscode rocks!

**Comment by bnason-nf** [comment]
I just updated my extension to allow clicking on each result to jump to the corresponding line of the file. Please let me know if it works for you.

**Comment by davmaz** [comment]
Thanks, but I'd rather this be 'integrated' so I don't have to install yet another extension.

Do you know if they're aware of this? The vscode people?

If they don't know or intend to do anything I'll install your extension.


Best,

Dave

________________________________

**Comment by bnason-nf** [comment]
@davmaz: I don't know any more than you do. It doesn't seem like there's been any progress that I can see.

However, today I updated the extension again, when you select each matching result, it should jump to that location and select the match, which should make it pretty easy to see.

**Comment by QuillVoy** [comment]
> 
> 
> I just updated my extension to allow clicking on each result to jump to the corresponding line of the file. Please let me know if it works for you.

Works like a charm.

**Comment by beltaurus** [comment]
None of the suggested work-arounds seem practical for me...

### Scenario
I am currently working on a regression test infrastructure, where there are hundreds of files called `CompileJob.pm`  (all with slightly different content. When I search for a token, I really only want the ONE that I'm looking at (which is typically the one opened by the debugger for me...).

Granted, I can hover over the tab to see the path of the file, and then copy
```
<leaf_directory>/<file_name>
```
to my `files to include`... 

### Suggestion
The `Problem Console` already allows to `Show Active File Only`.
A similar setting/switch would indeed be handy for the `Search` View.

The `Toggle Search Details` could reveal:
```
[ ] Show Active File Only
files to include
[                               ]
files to exclude
[                               ]
```
Selecting the `Show Active File Only` could remove the include/exclude lines, to provide more real estate for the results...

The arguments in favor of implementing such feature are abundant above...

**Comment by DerekSMorin** [comment]
> +1
> 
> * find all @ find
>   OR
> * find all in files @ current file only
>   // maybe `files to include` have some `magic variable` means current file ?

Magic variable could be dot.  Like in command prompt for current directory.
.

Or files to include could support full paths.
c:\temp\mycurrentlyawesomelysingleysearchablefile.txt

**Comment by beltaurus** [comment]
@DerekSMorin : I like the suggestion

> // maybe files to include have some magic variable means current file ?

That does imply higher priority between `exclude` and `include` though; And that would be more intuitive if we reversed the fields

```
files to exclude
[ *                             ]
files to include
[ @                             ]
```

Where `*` is the meta-character for "any match", and `@` is the meta-character for "active file"...

It certainly is more effective in real estate compared to my initial suggestion, but it is less intuitive (you have to read the manual to know how to use it).

However, a prioritized exclude/include certainly is quite powerful. So your suggestion gets my vote 👍 ...

I'm wondering though: what happens today if we put conflicting information in those fields... I'll find out soon enough...

**Comment by DerekSMorin** [comment]
@beltaurus - you helped me a bit, I thought I could only do the last part of the filename.

This doesn't work: C:\Development\Source\DotNet\framework\oqpers\database.cpp
This works: database.cpp
This works: oqpers\database.cpp
Even this works: Development\Source\DotNet\framework\oqpers\database.cpp

Guess it must just be a cross-platform goodness problem :)

**Comment by wilon** [comment]
```diff
-  
```
Just add a button for `Find all/Replace all` in current file search!

Current solutions:

- `Ctrl+Shift+F`, can't use in new tab.

- `Ctrl+F`, `Ctrl+Shift+L`, hard to remember keys.

- `Ctrl+F`, right click in the file, select `Change all Occurrences  /  Ctrl+F2`, cumbersome operation.

Just add a button for `Find all/Replace all` in current file search can sole it.
Hope add it soon!

**Comment by fadimounir** [comment]
+1 for this feature. This is really a necessity

**Comment by jajilgure** [comment]
+1 
I am really looking forward to this feature.

**Comment by bnason-nf** [comment]
If you really want this feature now and can't wait for Microsoft to implement this, my extension might be a reasonable solution for now:

https://marketplace.visualstudio.com/items?itemName=bnason-nf.findallinfile

**Comment by davmaz** [comment]
This is a nice solution (the searched for text is at least 'highlighted' well). Who cares about the line itself. This is a working solution in the interim.

From stackoverflow:

The above answers cover the Selected text and areas with same content as selection, but they miss the Current Search Match and Other Search Matches -- which have the same problem.

"workbench.colorCustomizations": {
    "editor.findMatchBackground": "#00cc44a8", //Current SEARCH MATCH
    "editor.findMatchHighlightBackground": "#ff7b00a1" //Other SEARCH MATCHES
}


________________________________

**Comment by TomLewis** [comment]
how the fuck is this not a feature, this is in sublime text

**Comment by eprothro** [comment]
What I needed exists today:

1. Select occurrence of `foo` in file
2. Command+Shift+L (Mac)

All occurrences of `foo` in the current file will be selected and given a cursor at the beginning of each selection.

Alternatively you can achieve the same result from search results:

1. Command+F (Mac)
2. Type `foo`
3. Command+Shift+L (Mac)

**Comment by vldmrrr** [comment]
> What I needed exists today:
Good for you - but this ticket is about unrelated functionality. It is about quick way to examine occurrences in context - that is what is provided by search results panel.

**Comment by chnuessli** [comment]
+1

**Comment by matthughes** [comment]
There is an extension that kind of solves this problem for me: https://marketplace.visualstudio.com/items?itemName=shibayu36.search-in-current-file

Doesn't address all the concerns I have and it's a little annoying that it permanently changes the file filter.

**Comment by bnason-nf** [comment]
Hi @matthughes, apologies if the self-promotion is inappropriate, but in case it's not, my Find All In File extension is also an option: https://marketplace.visualstudio.com/items?itemName=bnason-nf.findallinfile

**Comment by andrey-lizunov** [comment]
2021 is coming, but we still don't have this feature
more than 4 years
AMAZING

**Comment by matthughes** [comment]
Crazy indeed.  You’ve had four whole years using this free tool and haven’t
fixed it yet.

**Comment by SudoNova** [comment]
Unbelievable. This is a very basic, needed, and easy to implement feature, which has lots of upvotes and subscribers, but is not resolved in ~5 years?

**Comment by bhanratt** [comment]
I went back to Sublime Text personally.

**Comment by tausi0661** [comment]
"find all in current file", "find all in all opened files" -- a basic feature that exists in almost all the popular editors but i cannot believe that NOT in VSCode...

**Comment by misolori** [comment]
Just to provide an update on this, we've been exploring adding a "Filter" on the find widget that would allow the options to scale better. Since we already have "Find in Selection" as a toggle, we thought it would be best to follow the pattern we use in the "Problems" panel and using the filter action for the toggle. Here's how that would look like for the find widget:

![image](https://user-images.githubusercontent.com/35271042/134747341-f311b25c-018c-4d05-993b-8068ff141f63.png)

Happy to hear any feedback on this as this is where the "Select all matches" action would live

**Comment by ssigwart** [comment]
I think that's a nice way to keep the widget a manageable size, but I think there are 2 main wishlist items in this issue.  One is to find all occurrences and the other is to select all occurrences.  If both could be added, that would be great.  My pull request (#128915) implements the find all version as suggested by @alexdima's in https://github.com/microsoft/vscode/issues/14836#issuecomment-258781578.  The extra icon was something I was unsure of, but this filter menu would solve that.

**Comment by gpnaveen** [comment]
> Just to provide an update on this, we've been exploring adding a "Filter" on the find widget that would allow the options to scale better. Since we already have "Find in Selection" as a toggle, we thought it would be best to follow the pattern we use in the "Problems" panel and using the filter action for the toggle. Here's how that would look like for the find widget:
> 
> ![image](https://user-images.githubusercontent.com/35271042/134747341-f311b25c-018c-4d05-993b-8068ff141f63.png)
> 
> Happy to hear any feedback on this as this is where the "Select all matches" action would live

One more option would be 'list all the matches', with that copy the list , it was very convenient in notepad++.

**Comment by serhioV** [comment]
waiting that feature, I would like to see all occurences in the current file of a string in a list, and also more details, like in what function(parent) each of the occurences is.

**Comment by Rufus-SN** [comment]
Notepad++ has those options:  Find in current file, and Find in open files.   To their credit, I like the fact that VSCode allows you to copy your search results back into a text file!   For now, I guess I'll have to save my current file, and select the name as  a file filter for the "find all".

**Comment by wilon** [comment]
![image](https://user-images.githubusercontent.com/7512755/167236561-c46d9824-4354-49d9-9308-128fd49b412c.png)
![image](https://user-images.githubusercontent.com/7512755/167236590-055ca8d0-509d-4ab7-91d1-f43256debf53.png)
![image](https://user-images.githubusercontent.com/7512755/167237178-4084c1e7-e5f4-4dc2-9ce7-904b15af155f.png)

**Comment by Fairy-wen** [comment]
Need it to !
I'd like not to have to open another editor to find all occurrences of a word in a file.

**Comment by gulshan** [comment]
Hi Everyone, I think this existing option in the vscode search panel can help-

![image](https://user-images.githubusercontent.com/751732/168261062-7ed89d28-e475-4be3-a322-6e7b1fdf6f5d.png)

**Comment by Rufus-SN** [comment]
@gulshan Yes!  I just found out about the "Search Open Editors" Icon the other day!  That will serve about all my uses of "Search Current File" for all practical purposes!

**Comment by gpnaveen** [comment]
> @gulshan Yes! I just found out about the "Search Open Editors" Icon the other day! That will serve about all my uses of "Search Current File" for all practical purposes!

Is there a way we can copy the search output?

**Comment by Rufus-SN** [comment]
> > @gulshan Yes! I just found out about the "Search Open Editors" Icon the other day! That will serve about all my uses of "Search Current File" for all practical purposes!
> 
> Is there a way we can copy the search output?

Just right-click one of the hits, and it will give you a Copy-All option.  Copy, create a new file, and paste the results!

**Comment by mat-m** [comment]
Hello, Opened Editors is nice and have its benefits, but I often have a big bunch of them opened, so it is not like a dedicated "Find all in current document:editor" for my use case.

**Comment by FSGCorp** [comment]
Wow. Yeah, this is like the most basic feature of a code editor. Hard to believe this isn't available.
This is from UltraEdit which I thought I was going to abandon after 20 plus years for VS Code but not sure now. VS Code should have most if not all of these find options.
![ue-find](https://user-images.githubusercontent.com/37850335/194898336-4ba897c9-4d7a-4f78-a1b8-35c137266193.png)

**Comment by avastar** [comment]
I learned of vscode today and thought it was the best.. until I found that my most used feature of Notepad++ was missing... Where is the "Find All In Current Document" button? It seems like a 2 minute implementation since all the code is there, just limit it from "Search Only in Open Editors" to "Search Only in Current Editor".

**Comment by helfri62** [comment]
I'm with @avastar, this is one of my most used features in Notepad++.  I'm still experimenting with UltraEdit.  I love VS Code's integrations and extensibility, but this is a real usability limitation for me.

**Comment by DerekSMorin** [comment]
> Hi Everyone, I think this existing option in the vscode search panel can help-
> 
> ![image](https://user-images.githubusercontent.com/751732/168261062-7ed89d28-e475-4be3-a322-6e7b1fdf6f5d.png)

I think this is a good start.  Maybe we just need one more button beside this with only one page ( meaning the current file ) instead of just the button for all open files.

**Comment by FSGCorp** [comment]
Please tell me if I got this wrong, I am new to VS Code and seems a lot has changed in the six years since this issue was first opened and the issue seems to have proliferated the internet in various forms so if you search for something like "vs code find search only in current file" you get ton of results and if you don't read the details then you would think as I did at first that there is no way to do a simple "search/find in only the current file".

To clarify, there are two functions:
1. "Find (Ctrl+F)" which is a simple find in the current file 
2. and then there is "Find in Files (Ctrl+Shift+F)" - taken from the Edit menu text - which is also available from the sidebar search icon with Tooltip text "Search (Ctrl+Shift+F)". So same function is referred to as "Find in Files" and as "Search" and they are the same thing. 

The simple "Find (Ctrl+F)" seems to behave as expected limiting scope to the current file only. The real issue which seems to get lost in the back and forth on these posts is that you cannot do a simple "Find" (in current file only) and list out the results to a separate window which may still be an issue.  It is certainly a nice to have and should be available and is available in UltraEdit which I am currently using. Please correct me if any of this is off. I'd love to understand better.

I'm not pushing UltraEdit but it seems like they have made a company out of recreating an editor with all the features of VS code but user friendly, and keeping up with VS code's improvements and addressing all the quirks that people are complaining about with VS code. I've been using UltraEdit for more than 20 years and I am only exploring it now b/c all the youngsters in my new group are using it. First glance it appeared to be the bomb and I was ready to switch over but upon further inspection it seems to be a bit out of control and it's flexibility has made it inflexible and is now a hinderance. It's hard to be an editor for everyone, and especially to such a contentious group of people (self included). 😄 MS Curse 1.0 - trying to meet the needs of all with a single product which eventually gets out of control and becomes unmanageable. ☹️

**Comment by burekas7** [comment]
I would like to have this feature as well.
2022 - Any update on this?

**Comment by meche-gh** [comment]
Putting `find-in-selection` in a filter makes sense to me, because it changes the `find-replace` widget's behavior of incrementing the selection. Doubtful that `select-all-matches` would intuitively live there IMHO.

I personally just want a `select-all` icon:

 - UX-wise, the button puts the user on a different path of action than the other functionality of the search menu.
 - It's easier to understand - `filter` means (hopefully) less whereas `select-all` means more/all-the-things.
 - It's possible to add a search icon to go back into the incremental search mode if the user didn't want to type in a new string for all those ranges. Just a problem of deciding the position of the current selection - the user could have scrolled up or down a "page", or to the very top or bottom. "First visible result" could work.

**Comment by zm-cttae** [comment]
> 2022 - Any update on this?

@burekas7 I made yisibl/vscode#1 and suggested a https://github.com/microsoft/vscode/pull/128915#discussion_r1070610191

**Comment by netjeff** [comment]
_@sreenadh commented on May 3, 2019_
> Right-click on tab, "Copy relative path"
> Ctrl+Shift+F to open Search sidebar - enter search query
> Paste the relative path in "Files to include"

This workaround is what I'm using.  The important thing is to "Copy **Relative** Path", _not_ the plain "Copy Path".  

Still more clicks than I'd like, but not too bad.  Hopefully there will be better support for this someday ...

**Comment by burekas7** [comment]
> _@sreenadh [commented on May 3, 2019](https://github.com/microsoft/vscode/issues/14836#issuecomment-488960845)_
> 
> > Right-click on tab, "Copy relative path"
> > Ctrl+Shift+F to open Search sidebar - enter search query
> > Paste the relative path in "Files to include"
> 
> This workaround is what I'm using. The important thing is to "Copy **Relative** Path", _not_ the plain "Copy Path".
> 
> Still more clicks than I'd like, but not too bad. Hopefully there will be better support for this someday ...
+1

2023 - Any update on this?

**Comment by jamesford42** [comment]
This is highly annoying and makes working with long log files or any long file really, in visual studio code. When you search in such a file you generally want a usable summary of line results so you can see which of the 100 results is the one you care about.

**Comment by jborovi** [comment]
Hello, this is great plugin, thank you for that, but "search all occurences" should not be text search (CTRL+SHIFT+F)... I would expect that it will find really all occurences of the specified variable... not all strings which have same name, for example if developer names local variable X, I only need to find all occurences of this local variable X, not every occurence of string X in the code. This is what means "search for all occurences" in all IDEs.

**Comment by andywhitaker** [comment]
I would probably just make a button within the normal search box or item in the cmd+p menu that brings up a search editor or the search pane with the files filter already filtered to the specific file that was open with focus when it was initiated. If a button in the existing search is used to trigger this then have the search token field populated with whatever term was there originally as well before triggering the "find in all files". I imagine this would use already existing capabilities and take minimal effort as compared to other options. I'm honestly getting along just fine without this now but thought I'd make the suggestion. My workaround has been to basically use the search panel and type in what I need to filter to the specific file I want or use a search editor and do the same. Having it pre-filter to the file easier would be a minor plus for me but I don't really care that much anymore.

**Comment by noam-zur** [comment]
(coping here my suggested solution from https://github.com/microsoft/vscode/issues/197271 - which I opened before I realized this feature request exists already...)
(1) Add "New Search Editor" button to the "Search in File" panel.
(2) When pressed, it will open a new Search Editor window. it will be already configured for 1. single file search (the origin file) 2. the same search query.
example mock:
![image](https://github.com/microsoft/vscode/assets/85063478/a55d5925-42c2-49a9-9563-73a2edf34529)

**Comment by BillDenton** [comment]
@sreenadh https://github.com/microsoft/vscode/issues/14836#issuecomment-488960845

> Right-click on tab, "Copy relative path"
> Ctrl+Shift+F to open Search sidebar - enter search query
> Paste the relative path in "Files to include"

This doesn't work if the file isn't in the workspace directory. I often load log files into the window that has the source code.
I want to see the results for the current file only in the search panel (or similar panel). I don't want to lose the configuration of global search panel when I do this. I don't think it should be in a separate editor. Similar to the global search there could be an option to "open in editor".

**Comment by jamesl-dm** [comment]
+1 on this. Can't believe this still requires a plugin. Even adobe acrobat can do this since the 90's. How can vscode be worse than adobe?

**Comment by bnason-nf** [comment]
Hi @albjeremias,

I'm not sure if it's the one that @jamesl-dm was referring to, but I created this extension years ago. I hope it helps.

https://marketplace.visualstudio.com/items?itemName=bnason-nf.findallinfile

-Benbuck

**Comment by bhanratt** [comment]
> > This is supported today by pressing Alt Enter in the Find Widget. Do we really need a button for this?
> 
> That shortcut by default opens search results in a new editor - it has no relation to the feature requested in this thread.

Not for me. It behaves as described. That said this is very unintuitive and should be a button in the find widget if you forget the shortcut.

**Comment by vldmrrr** [comment]
> > That shortcut by default opens search results in a new editor - it has no relation to the feature requested in this thread.
> 
> Not for me. It behaves as described. That said this is very unintuitive and should be a button in the find widget if you forget the shortcut.

Interesting, here is screenshot of my settings:
<img width="760" height="25" alt="Image" src="https://github.com/user-attachments/assets/88f4dbe9-ffac-4aa8-adf3-5946cc2f8a4b" />
What command is bound to Alt+Enter in your instance?

**Comment by joaomoreno** [comment]
> When I press Alt+Enter on the Find box the editor puts a cursor on each result in current file. this is not the request - I want to have a list of all results in current file that you can press and jump to each one

What do you mean exactly? Where do you expect to have that list of all results? Note that VS Code by default will highlight all results just by typing the search term.

**Comment by KernelLeak** [comment]
"Find in Files" in the sidebar, limited to the one file currently being edited, not just "all open editors"...

**Comment by noam-zur** [comment]
> > When I press Alt+Enter on the Find box the editor puts a cursor on each result in current file. this is not the request - I want to have a list of all results in current file that you can press and jump to each one
> 
> What do you mean exactly? Where do you expect to have that list of all results? Note that VS Code by default will highlight all results just by typing the search term.

please see my suggestion above with screenshot regarding how to solve it: https://github.com/microsoft/vscode/issues/14836#issuecomment-1793671395

**Comment by mat-m** [comment]
> 
> What do you mean exactly? Where do you expect to have that list of all results? Note that VS Code by default will highlight all results just by typing the search term.

A shortcut to "exclude */**; include current editor", in the sidebar.
