### ISSUE TITLE
Devtools don't reload CSS files

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148541]
* run `scripts/code.sh`
* change a CSS file
* reload window
* CSS change isn't reflected

https://user-images.githubusercontent.com/1794099/166214372-e37c5ae1-f673-4f72-ac14-8cc1593efa83.mov

**Comment by deepak1556** [comment]
Reloading uses the same process causing the css files to be cached. Disabling cache in network tab or reloading via devtools (Cmd + R) which uses a different code path will bypass this cache. I wonder if adding a `Last-Modified` header from Electron's custom protocol handler could be a viable solution when running OSS.

**Comment by deepak1556** [comment]
Aggressive caching for subresources is intended in the runtime https://bugs.chromium.org/p/chromium/issues/detail?id=654378#c4 and the only way to force revalidation is via `Cache-Control: max-age=0` or `Last-Modified` headers. Do we want to add this workaround for OSS css resources ?

**Comment by jrieken** [comment]
I'd say so but we can also discuss in the team. Today's workaround is to disable caching which has the same effect but is a trick that you need to know

**Comment by bpasero** [comment]
I somehow hit this more often lately, can we do something OSS to address this @deepak1556 ?

**Comment by Tyriar** [comment]
@deepak1556 FYI I actually see my JS files usually not reloading since the ESM change, I wasted enough time with this problem that I almost always just restart the app instead of reload the window 😦. I see this on Mac and Windows which is weird as I'm the only one AFAIK.

**Comment by Tyriar** [comment]
I tried with this diff and it still loads stale JS:

```
diff --git a/src/vs/base/common/network.ts b/src/vs/base/common/network.ts
index f220611a722..934836c741a 100644
--- a/src/vs/base/common/network.ts
+++ b/src/vs/base/common/network.ts
@@ -366,7 +366,7 @@ export namespace COI {
                ['3', { 'Cross-Origin-Opener-Policy': 'same-origin', 'Cross-Origin-Embedder-Policy': 'require-corp' }],
        ]);
 
-       export const CoopAndCoep = Object.freeze(coiHeaders.get('3'));
+       export const CoopAndCoep = coiHeaders.get('3');
 
        const coiSearchParamName = 'vscode-coi';
 
diff --git a/src/vs/platform/protocol/electron-main/protocolMainService.ts b/src/vs/platform/protocol/electron-main/protocolMainService.ts
index 86e0a616af8..08510ce3eec 100644
--- a/src/vs/platform/protocol/electron-main/protocolMainService.ts
+++ b/src/vs/platform/protocol/electron-main/protocolMainService.ts
@@ -103,6 +103,11 @@ export class ProtocolMainService extends Disposable implements IProtocolMainServ
                                headers = COI.getHeadersFromQuery(request.url);
                        }
                }
+               if (!headers) {
+                       headers = {};
+               }
+               headers['Cache-Control'] = 'max-age=0';
+               headers['Last-Modified'] = 'Thu, 21 Nov 2021 12:48:00 GMT';
 
                // first check by validRoots
                if (this.validRoots.findSubstr(path)) {
```

**Comment by bpasero** [comment]
I personally have only seen this issue with CSS and not JS, but something that I notice is that only recently I had "Disable Cache" in devtools unchecked, when for many years before it was always checked. So my regression only came recently because this this fact in devtools.

**Comment by deepak1556** [comment]
Initial debugging shows @Tyriar issue is not affected by the http cache, I will continue to investigate that. The issue for css files should now be addressed via https://github.com/microsoft/vscode/pull/234357

**Comment by osortega** [comment]
I tried following some of the steps mentioned here but I'm still unable to get the CSS to refresh.

https://github.com/user-attachments/assets/0446d01a-b740-4b94-a989-233c41675542

**Comment by rzhao271** [comment]
Verified in OSS by changing the Settings editor background and reloading the window.

**Comment by deepak1556** [comment]
Thanks @rzhao271 

@osortega it is hard to tell from the recording, but did you refresh the oss window after the changes were built ? Was there a build task ensuring the changes were built ?

**Comment by osortega** [comment]
@deepak1556 I tried again and it's working this time. I did refresh the OSS window before, I wonder if the build task stopped before or something
