### ISSUE TITLE
vscode.dev: Hitting the save shortcut in a webview triggers the browser save dialog

### ISSUE THREAD

**Issue by pomdtr** [microsoft/vscode#148545]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: vscode.dev
- OS Version: Mac OS 12.3.1 

Steps to Reproduce:

1. Go to vscode.dev and open a folder containing a png file
2. Install the luna paint extension
3. Open the png and hit `cmd+s`

**Comment by mjbvz** [comment]
Fixed by https://github.com/microsoft/vscode/commit/82f2db788bc1a9efb0d0c9dc5599947c457c087a

**Comment by sandy081** [comment]
I still see the browser save dialog

![image](https://user-images.githubusercontent.com/10746682/193056469-b01a577f-dc4c-443d-ab75-2e7e22d3029d.png)

**Comment by aeschli** [comment]
Works for me on Linux Edge and insiders.vscode.dev

**Comment by sandy081** [comment]
I am on Safari btw

**Comment by mjbvz** [comment]
@sandy081 I'm also not able to reproduce this error on Safari with insiders.vscode.dev. Tested with both the built-in image preview and with Luna paint

Any extra steps to trigger this?

**Comment by sandy081** [comment]
I am getting this dialog on every file. May be this shortcut (cmd+s) is not being handled by VS Code but instead by the browser. Is there a way I can prevent this?

**Comment by mjbvz** [comment]
@sandy081 Are you using a different keyboard layout that could be causing this?

**Comment by sandy081** [comment]
I do not think if I have configured any. Is there a way to reset or do something?

**Comment by mjbvz** [comment]
@alexdima Are you aware of any safari specific issues when intercepting keypresses such as cmd+s?

**Comment by alexdima** [comment]
No, nothing special as far as I know. FWIW I also cannot reproduce i.e. `cmd+s` saves the file for me, it doesn't show the browser save dialog.

**Comment by sandy081** [comment]
Seems like specific to my env. Feel free to close this.
