### ISSUE TITLE
Support custom root directory alias for imports

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode#14907]
VSCode depends on being able to resolve `import`ed references for intellisense. So when using something that rewrites import paths -- specifically: [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) -- we lose intellisense.

This is very useful for large projects, because it avoids deeply nested path resolutions, e.g. 

`import 'thing-to-test' from '../../../../../src/feature/subfeature/helper/thing`

These are a big nuisance because apart from being ugly & it's hard to locate the file in the first place, anytime you move a code block, you have to refactor them. The aforementioned module lets you define an alias like "~=/src" and then just:

`import 'thing-to-test' from '~/feature/subfeature/helper/thing`

Atom and Webstorm are both capable of being configured with information about such aliases to enable them to resolve the paths correctly.

Is there any way this capability can be added to VS Code? I really want to be able to continue to use these, but the loss of intellisense is tough to swallow.

**Comment by dbaeumer** [comment]
@waderyan IMO tsserver 2.0.3 is able to do this. They now support a rootPath. But you need to test.

**Comment by waderyan** [comment]
@jamietre thank you for opening this issue. This fell through the cracks for me so apologize it took some time. We have done a fair amount of work here. Can you try again with [VS Code Insiders](https://code.visualstudio.com/insiders)? If it is still not working can you share a workspace with me to test out the issue.

**Comment by jamietre** [comment]
@waderyan no problem - but how do I test it? I assume there needs to be some config to tell it what aliases e.g. ~ mean.

**Comment by waderyan** [comment]
@jamietre apologize that my writing was unclear. Please test the situation you described in this issue. Do we still "[lose] IntelliSense" when import paths are rewritten? If you have a workspace that shows the issue can you share it with me.

**Comment by jamietre** [comment]
I can create a workspace but it's quite simple really,

module 1:

    import something from '~/module2'

where `module` might be `../../folder1/folder2/module2'

I think you might be unclear on the situation I am describing (or feature I am requesting) because import paths aren't being rewritten by VS Code, they are being rewritten during my build process by a babel plugin. VS Code would have no knowledge of this process or what the mappings meant, unless it actually did some analysis of the compiled code, or had specific knowledge of the plugin I mentioned and parsed `.babelrc` to use the same config.

The simple solution would be for some configuration in VS Codewhere I can tell it that for this workspace, `~/` in an import means `{projectRoot}/src/`. I don't see how anything would just start working unless I added config to tell VSCode what my alias means.

**Comment by waderyan** [comment]
@jamietre thank you for your explanation. I looked around in Atom and WebStorm but couldn't find how to do this. Can you point it out for me? We may want to adopt something similar. 

@mhegazy @bowdenk7 have either of you seen a request like this before? Is this something that could be done? Exploring the possible solutions right now.

**Comment by majomb** [comment]
WebStorm has a feature called "resource root" which lets you use path aliases:
http://stackoverflow.com/questions/34943631/path-aliases-for-imports-in-webstorm

This would be a very handy feature for developers using webpack.

**Comment by jamietre** [comment]
@majomb thanks - sorry i totally missed this question.  I am not an Atom user but the 'babel-plugin-module-alias' website says "Atom: Uses atom-autocomplete-modules and enable the babel-plugin-module-resolver option."

An implementation of this feature that's compatible with `babel-plugin-module-alias` would allow you to specify a prefix and a replacement. Whenever VS Code resolves a path in an "import", if it starts with the prefix from my config, then the prefix is replaced with my substituation path, The replaced value should handled as if it is rooted at the project workspace root. I could see a regex based implementation also having added value too.

e.g.

     {
        "~": "./src",
        "~test": "./test"
     }

This would result in an import in file `{root}/test/common/util,js`

    import { thing } from "~/common/util"

being mapped to

    import { thing } from "../../../src/common/util"

as far as VS code is concerned. It would then be able to find the file and intellisense and everything else would work. This is exactly what the babel plugin does when you compile. Obviously the benefit of using this `babel-plugin-module-alias` in the first place is not having to deak with & refactor crazy relative paths :)

**Comment by mhegazy** [comment]
This is already supported using `paths` mapping. in your `tsconfig.json`/`jsonfig.json` add an entry to your path mapping rules to match the `~` to whatever root you need. e.g.:

```ts
{
    "compilerOptions": {
        "baseUrl": "./",  // all paths are relative to the baseUrl
        "paths": {
            "~/*" : ["*"]   // resolve any `~/foo/bar` to `<baseUrl>/foo/bar`
        }
    }
}
```

hope that helps.

**Comment by majomb** [comment]
@mhegazy thanks for quick response. Seems that those compiler options are only allowed in tsconfig.json files and are missing from jsconfig.json.

https://www.typescriptlang.org/docs/handbook/compiler-options.html (paths is marked with [2])
https://code.visualstudio.com/docs/languages/jsconfig (paths is not listed as available option)

**Comment by mhegazy** [comment]
The option is honored in the two files. the schema needs to be updated in https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/jsconfig.json. PRs are welcomed.

**Comment by jamietre** [comment]
It doesn't seem to work for me. In my `jsconfig.json`:

	"compilerOptions": {
		"target": "es6",
		"module": "commonjs",
		"allowSyntheticDefaultImports": true,
		"baseUrl": "./",
		"paths": {
			"~/*": ["*"],
			"~test/*": ["test/*"]
		}
	},

I don't get intellisense when using the alias, and "go to definition" doesn't work.

**Comment by mhegazy** [comment]
Please provide some repro project we can use to diagnose. here is what i see:

![animation](https://cloud.githubusercontent.com/assets/8000722/21200304/a0a0b4c8-c1fb-11e6-8256-40ea947bbd10.gif)

**Comment by jamietre** [comment]
That looks exactly like what I'd expect! I am using insider, though can't think why that would make a difference for this. Will try in the release just to be sure..

The project I've been playing with is pretty huge, I'll try it in something more trivial to determine if it's my project or the environment.

**Comment by weikinhuang** [comment]
Also the ability to specify additional `module` directories would be extremely useful as `webpack` allows you to do so:

```javascript
{
...
  resolve: {
    modules: [path.join(__dirname, 'js'), 'node_modules'],
    ...
  },
...
}
```

This allows for the ability to reference source files without direct path resolutions such as

```javascript
// from js dir
import api from 'data/api';

// from node modules
import _ from 'lodash';
```

**Comment by t1mmen** [comment]
I'm attempting to get this working (in a similar setup as @weikinhuang) without any luck. Should this work already?

```
// jsconfig.json
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "allowSyntheticDefaultImports": true,
        "paths": {
          "*": ["src/*"]
        }
    }
}
```

Relevant webpack config:
```
const config = {
  resolve: {
    modulesDirectories: [
      'src',
      'node_modules',
    ],
    extensions: ['', '.json', '.js', '.jsx'],
   },
}
```

```js
// src/components/TestComponent.js

import AnotherComponent from 'components/AnotherComponent'; // doesn't work
import TestComponent from './TestComponent' // works as expected
```

**Comment by mhegazy** [comment]
> I'm attempting to get this working (in a similar setup as @weikinhuang) without any luck. Should this work already?

You are missing an `*` in your mappings:

```json
// jsconfig.json
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "allowSyntheticDefaultImports": true,
        "baseUrl": "./",
        "paths": {
          "components/*": ["src/components/*"],
          "utils/*": ["src/utils/*"],
          "redux/*": ["src/redux/*"],
          "routes/*": ["src/routes/*"],
          "api/*": ["src/api/*"]
        }
    }
}
```


From these mappings, it seems that all you need is to set the `baseUrl` to `src/`. 

all path mapping entries are relative to `baseUrl`. since all your path mapping entries are subfolders of the `src` directory, it would be easier to just not have `path` mappings.

you can read more about how path mapping works at: www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

**Comment by t1mmen** [comment]
@mhegazy, thank you so much, `basePath: "src/"` did the trick! May your day be as awesome as you!

**Comment by mhegazy** [comment]
thanks 🌷. glad it worked.

**Comment by mjbvz** [comment]
Closing as it sounds like this issue has been fixed.

**Comment by tleunen** [comment]
@mjbvz @mhegazy - I found this issue while looking for custom root directory, and with your explanations, I was able to also setup my project properly to have intellisense with custom paths.

But `cmd+click` is not working for these custom paths. Is there any way to have them working?

**Comment by devrelm** [comment]
I'm actually still seeing issues with red squigglies and no go-to-definition for mapped paths. I'll try to get a minimum-reproducible repo up, but for now the two things that we're doing that might be unexpected are:

1. mapped path starts with an `@` character
2. `paths` is set in a base tsconfig, while `baseUrl` is set in a child tsconfig (one that inherits from the base tsconfig

**Comment by zealitude** [comment]
I am using Angular CLI
it divided the tsconfig in to /tsconfig.json and /src/tsconfig.app.json
however, I found that vscode only able to read the first one, /tsconfig.json only and ignore the later

my workaround solution:

/tsconfig.json
```
"baseUrl": "src/",
    "paths": {
      "@shared": [
        "app/shared"
      ],
      "@shared/*": [
        "app/shared/*"
      ]
    }
```

/src/tsconfig.app.json
```
"baseUrl": "",
    "paths": {
      "@shared": [
        "app/shared"
      ],
      "@shared/*": [
        "app/shared/*"
      ]
    },
```

**Comment by OliverJAsh** [comment]
> https://code.visualstudio.com/docs/languages/jsconfig (paths is not listed as available option)

As @marianban pointed out, this feature is not documented. I've raised a PR to fix this at https://github.com/Microsoft/vscode-docs/pull/942.

**Comment by lifehackett** [comment]
This is still causing me issues. I've run through the various suggestions in this list, but can't figure out why it isn't working.

_VSCode: 1.12.2
Typescript: 2.3.2_

**jsconfig.json**
```
{
  "compilerOptions": {
    "checkJs": true,
    "target": "ES6",
    "baseUrl": "src/"
  },
  "exclude": [
    "node_modules",
    "lib",
    ".tmp",
    "build"
  ]
}
```


**TypeScript definition file**
![screen shot 2017-06-01 at 3 33 38 pm](https://cloud.githubusercontent.com/assets/1809761/26701821/bcbca982-46df-11e7-886c-af1a3bf3fa0d.png)

**Relevant Portion of the Directory**
![screen shot 2017-06-01 at 3 34 09 pm](https://cloud.githubusercontent.com/assets/1809761/26701840/ce58a092-46df-11e7-8071-45f93f77b932.png)

**Comment by mhegazy** [comment]
set `"moduleResolution": "node"`.

**Comment by lifehackett** [comment]
Thank you! That got red of the squiggly and error, but I'm still not getting intellisense.

**Comment by mhegazy** [comment]
can you share a repro project?

**Comment by maitriyogin** [comment]
Hi,
I'm trying to fix this in my project which has no Typescript dips but is just ES6.
My web pack moduleDirectories is setup like this 
```modulesDirectories: ['node_modules', 'src']```
I'v amended this to my jsconfig.json 
```
"compilerOptions": {
        "target": "ES6",
        "moduleResolution": "node",
        "baseUrl": "./src"
    }
```
When I try and cmd click on say removeProps
```
import {removeProps} from "utils/thing_type_utils";
```
I'm not able to jump to that function.
Works fine with full path imports ...
Any ideas?
/Stephen.

**Comment by mhegazy** [comment]
can you share a repro project?

**Comment by maitriyogin** [comment]
I can try, I don't want share our prod code, but in short your saying it should work?
/stephen

**Comment by mhegazy** [comment]
yup.
![animation](https://user-images.githubusercontent.com/8000722/26890206-9be7fa2e-4b65-11e7-9c60-1a4f97954d45.gif)

**Comment by maitriyogin** [comment]
Hmm, I'll fiddle again, although one thing is that I get an unknown configuration property in jasconfig for compilerOptions (squiggly line).. which you don't? Wondering if an extension is mucking things up?

**Comment by vvatikiotis** [comment]
@maitriyogin found anything? Seems I'm on the same boat as you. Module resolution as been working on and off for me, for the past year or so.

**Comment by rw3iss** [comment]
Heyas. Having a problem new'ing classes using the tsconfig/jsconfig approach with baseUrl and paths properties. I was able to fix the complaints of webpack not being able to resolve the relative paths, but now when I try to actually instantiate one of the classes, the webpack compiler says it can't resolve the module. For instance:

tsconfig.json:
```
"baseUrl": "./app",
"paths": {
    "components/*": ["components/*"],
    "lib/*": ["lib/*"],
    "models/*": ["models/*"]
},
```

My file:
```
import User from 'models/User';
public test() {
  let user = new User; // <-- compiler complains with 'Cannot resolve 'models/User'.
}
```

So you see, Visual Studio Code will allow it without errors, because of the correct baseUrl and paths properties, but the compiler can't see the modules. If I change the paths to relative, ie: 
`import User from '../models/User'`
everything works fine.

Is there a way to get the compiler and VS Code to both work together? Has anyone else run into this problem?

**Comment by rw3iss** [comment]
FYI, to get webpack 3 to compile relative modules that are declared in tsconfig/jsconfig.json 'paths' property, you have to also add them to webpack config's 'resolve.modules' property, ie: 

tsconfig.json:
```
"baseUrl": "./app",
"paths": {
    "~/*": ["./*"],
    "components/*": ["components/*"],
    "lib/*": ["lib/*"],
    "models/*": ["models/*"]
}
```

webpack.config.js:
```
resolve: {
    modules: [ 'node_modules', 'app', 'app/models', 'app/components', 'app/lib' ]
}
```

Hope it helps someone!

**Comment by tsmirnov** [comment]
@mhegazy setting moduleResolution works for me, but now I have the warning:

> Property moduleResolution is not allowed

You have that warning on demo screenshot too. Is there any way to avoid the warning message?

**Comment by amritk** [comment]
Having issues with this as well, it compiles fine in webpack, but I get the annoying red underline in vscode.
![screenshot from 2017-08-09 13-40-00](https://user-images.githubusercontent.com/2039539/29142921-47a6bf98-7d08-11e7-8cc8-a80bec6e1319.png)

tsconfig.json
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "lib": [
            "dom",
            "es2015",
            "es2016",
            "es6",
            "es2017"
        ],
        "target": "es2017",
        "module": "es6",
        "moduleResolution": "node",
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "removeComments": false,
        "baseUrl": ".",
        "paths": {
            "@base": ["."],
            "@community": ["src/vue/community"],
            "@components": ["src/vue/components"],
            "@src": ["src"],
            "@vue": ["src/vue"]
        },
        "preserveConstEnums": true,
        "sourceMap": true,
        "skipLibCheck": true
    }
}
```
webpack.base.conf.js
```
    resolve: {
        extensions: ['.ts', '.js', '.vue', '.json'],
        alias: {
            '@base': resolve('.'),
            '@community': resolve('src/vue/community'),
            '@components': resolve('src/vue/components'),
            '@src': resolve('src'),
            '@vue': resolve('src/vue')
        }
    },
```

**Comment by rw3iss** [comment]
Try to add the 'modules' property within resolve, ie:

resolve: {
extensions: ['.js', '.jsx', '.ts', '.tsx'],
modules: [ 'node_modules' ] // try to add '@src', 'src', 'src/vue', etc...
},

**Comment by amritk** [comment]
@rw3iss would the webpack config affect vscode? I thought vscode was resolving the paths from tsconfig.json

**Comment by rw3iss** [comment]
Yeah, true. I don't know, I have the relative paths working within VSCode
on one of my projects. Here's the configs, if it helps:

(from within ./app/lib/Authentication.ts):
import User from 'models/User';

Here is my tsconfig.json:
{
"compilerOptions": {
"outDir": "./build/", // path to output directory
"sourceMap": true, // allow sourcemap support
"strictNullChecks": true, // enable strict null checks as a best practice
"module": "es6", // specifiy module code generation
"moduleResolution": "node",
"jsx": "react", // use typescript to transpile jsx to js
"target": "es2015", // specify ECMAScript target version
"allowJs": true, // allow a partial TypeScript and JavaScript codebase
"baseUrl": "./app",
"paths": {
"~/*": ["./*"],
"components/*": ["components/*"],
"lib/*": ["lib/*"],
"models/*": ["models/*"]
}
},
"include": [
"./app/**/*"
],
"exclude": [
"./node_modules/**/*"
],
"types": ["webpack-env"]
}

And my webpack config:
var webpack = require('webpack');
var path = require('path');

var BUILD_DIR = path.resolve(__dirname, 'build');
var APP_DIR = path.resolve(__dirname, 'app');

var config = {
entry: {
app: [
'webpack-dev-server/client?http://localhost:3000',
'webpack/hot/dev-server',
//'react-hot-loader/patch',
APP_DIR + '/entry.tsx'
]
},

output: {
publicPath: '/',
path: BUILD_DIR,
filename: '[name].js'
},

resolve: {
extensions: ['.js', '.jsx', '.ts', '.tsx'],
     alias: {
     components: path.resolve(__dirname, "app/components"),
     lib: path.resolve(__dirname, "app/lib"),
     models: path.resolve(__dirname, "app/models"),
},
modules: [ 'node_modules', 'app', 'app/models', 'app/components', 'app/lib'
]
},

module: {
loaders: [
{
test: /\.(t|j)sx?$/,
include: APP_DIR,
exclude: /node_modules/,
loader: ['ts-loader']
}
]
},

plugins: [
new webpack.HotModuleReplacementPlugin(),
new webpack.NamedModulesPlugin()
],

devServer: {
hot: true,
contentBase: './',
publicPath: '/',
public: 'http://localhost:3000',
port: 3000
}

};

module.exports = config;

**Comment by amritk** [comment]
@rw3iss hey thanks for your help! turns out VSCode doesn't like them starting with an '@' symbol.

**Comment by rw3iss** [comment]
Sweet, yeah I was curious about that, seemed like it might not. Glad you
got it figured out!

**Comment by yoyo-real** [comment]
I'm using Inseider. Intellisense did not work in the React project.
I tried variously, if the extension is `jsx`,`jsx: "react"`is mandatory.

jsconfig.json OK
```json
{
  "compilerOptions": {
    "jsx": "react",
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"]
    }
  }
}
```

jsconfig.json NG
```json:
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"]
    }
  }
}
```

**Comment by gengxuelei** [comment]
it's not ok in html,there is a snippets:
```
<script src="/static/jquery.js"></script>
```
but in fact the file is in `'/www/static/jquery.js'`.
when I press 'Ctrl' and click this path it tips:'file not found'

**Comment by wesleymostien** [comment]
Can't get this to work, please help. Intellisense is still not working.

![screen shot 2017-10-12 at 18 38 36](https://user-images.githubusercontent.com/6223285/31507895-9afb2426-af7c-11e7-880d-9da427fe7b56.png)

Inside index.ts I already get folder completion ('src/components'), but no .vue file completion :
![screen shot 2017-10-12 at 18 33 39](https://user-images.githubusercontent.com/6223285/31507855-6eca2a96-af7c-11e7-98b5-901c7c891149.png)

Inside 'Hello.vue', there's no Intellisense whatsoever : 

![screen shot 2017-10-12 at 18 36 14](https://user-images.githubusercontent.com/6223285/31507879-86c3cb8e-af7c-11e7-9489-cc210024fb66.png)

tsconfig.json :

`"compilerOptions": {
    "target": "es2015",
    "lib": ["dom", "es2015", "es2017"],
    "module": "es6",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "strictNullChecks": true,
    "removeComments": true,
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": true,
    "sourceMap": true,
    "outDir": "./dist/",
    "baseUrl": "./src",
    "paths": {
      "components/*": ["components/*"]
    }
  },
  "include": ["./src/**/*"],
  "exclude": ["./node_modules/**/*"]`

**Comment by c01nd01r** [comment]
jsconfig.json for vue-cli webpack template:
```js
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"],
    }
  }
}
```

jsconfig.json located in the root of project

**Comment by mjbvz** [comment]
If you are running into problems related to import paths, please try asking on stackoverflow or posting a new issue
