### ISSUE TITLE
[css] Wrong CSS-Error with @supports rule

### ISSUE THREAD

**Issue by wottpal** [Microsoft/vscode#1505]
I get a CSS-eror using the supports-rule. I've used it in combination with the backdrop-filter property but it's not working with other properties neither.

<img width="607" alt="bildschirmfoto 2015-12-20 um 13 12 53" src="https://cloud.githubusercontent.com/assets/3930150/11917940/067916ba-a71c-11e5-8d57-d05691659ff1.png">
<img width="385" alt="bildschirmfoto 2015-12-20 um 13 13 10" src="https://cloud.githubusercontent.com/assets/3930150/11917939/06787a66-a71c-11e5-8517-e6c0088b7a4b.png">

**Comment by dstorey** [comment]
@supports isn't included in either the css.plist or cssParser.ts yet. There are a few at-rules missing.

**Comment by ciampo** [comment]
Is there any plan about fixing this issue?

**Comment by codingcircus** [comment]
Would be great, if this could finally be fixed.

**Comment by adamchenwei** [comment]
What should users do to make this a high priority for the core team?

**Comment by orobert91** [comment]
This should be fixed, and surely is not complicated to do so.

**Comment by aeschli** [comment]
fixed for the september release (1.17)

**Comment by rafaelderolez** [comment]
@aeschli I'm on 1.17.1 and still seeing this issue in .scss files.

**Comment by aeschli** [comment]
@rafaelderolez Can you create new issue with a code sample that shows the problem?

**Comment by Rosseyn** [comment]
Looks like this is already added to backlog in [35887](https://github.com/Microsoft/vscode/issues/35887)
