### ISSUE TITLE
Command 'markdown.showPreview' not found

### ISSUE THREAD

**Issue by frankhale** [Microsoft/vscode#15184]
- VSCode Version: Code - Insiders 1.8.0-insider (a3e85d60a32f91efccfe6161c3a4673ad909496e, 2016-11-08T15:09:13.902Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Theme-QuietLight|gerane|0.0.2|
|debugger-for-chrome|msjsdiag|2.1.3|
|vscode-icons|robertohuertasm|4.0.1|
|markdown-pdf|yzane|0.1.4|

---

Steps to Reproduce:

1. Create a markdown document or open an existing one and click the open preview button

The following error happens now with latest 1.8 preview when attempting to view a preview of a markdown file.

`command 'markdown.showPreview' not found`

This was working well for me before I got the latest update today.

**Comment by mjbvz** [comment]
The markdown extension does not seem to be getting loaded properly. Changing [this line in the extension's package.json](https://github.com/Microsoft/vscode/blob/master/extensions/markdown/package.json#L11) to:

```
	"main": "./out/extensions/markdown/src/extension",
```

Fixed things in my development environment at least.

**Comment by Tyriar** [comment]
Fixed by amending the tsconfig.json to put the build artifacts in the correct path. Pushed to master and release/1.7.

**Comment by dotnetCarpenter** [comment]
FYI I'm still getting the error message in vscode

    1.11.1
    d9484d12b38879b7f4cdd1150efeb2fd2c1fbf39

But it works, albeit with some latency.

**Comment by cbuctok** [comment]
Bumping,
Version 1.17.2 still has this problem. I'm on Fedora 26.
