### ISSUE TITLE
} is replaced with \} in github.dev

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#152746]
* go to github.dev / vscode
* open inlineCompletionsModel.ts
* change 200 to 50
* create new branch
* observe that the closing brackets are replaced with \} in inlineCompletionsModel

@alexr00 please reassigned to who you think might be able to fix this.
Looks like a github issue to me though.

![recording](https://user-images.githubusercontent.com/2931520/174822837-b1e91a70-f621-49b5-818d-77c46335d7fc.gif)

**Comment by joyceerhl** [comment]
This looks similar to https://github.com/microsoft/vscode/issues/152729

**Comment by IllusionMH** [comment]
Looks like similar thing was already fixed for organize imports and some TS actions in #152350

**Comment by joyceerhl** [comment]
This doesn't repro for me when using the stable VS Code quality on github.dev. Confirmed that it still reproduces in the latest Insiders on commit `10e6e876822fa2da15fb68e8a6f1fb9aa8d94ce2`

**Comment by alexr00** [comment]
@jrieken and @mjbvz this looks similar to https://github.com/microsoft/vscode/issues/152272.

**Comment by jrieken** [comment]
😱 can actually reproduce with latest insiders...
