### ISSUE TITLE
Scrolling issue when mouse hover on HTML output

### ISSUE THREAD

**Issue by thomasaarholt** [microsoft/vscode#156190]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I discovered the following issue when investigating an issue with displaying a dataframe with the polars (pandas-like) library, see pola-rs/polars#4102.

VSCode appears to have a behaviour issue with the `line-height` css attribute, even when set to `100%`. The issue is that if the mouse is placed on top of the rendered output, one can only scroll in the upwards direction. This leads to frustrating behaviour when the notebook only sometimes scrolls - especially if one is printing a large number of dataframes.

Reproducible example, with video below:
```python
from IPython.display import HTML

html = """
<head>
<style>
p {line-height:50%}
</style
</head>
<body>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis tempus elit. Maecenas suscipit feugiat maximus. Phasellus luctus erat in neque elementum, quis pellentesque arcu congue. Nam vel sem bibendum, dignissim nulla sed, malesuada lacus. Proin convallis sit amet ante in semper. Curabitur nec leo sit amet ligula euismod porta. Fusce ante eros, mollis nec diam vel, vehicula feugiat est. Etiam et elit tellus. Nam a dolor nibh. Aliquam at blandit massa. Proin et libero lectus.

Sed ac lacus sem. Integer ornare mauris vel condimentum lacinia. Quisque vel orci sed lorem lobortis elementum vitae sed nunc. Suspendisse sit amet velit eget massa tristique posuere aliquam at massa. Vivamus dapibus nunc non enim suscipit, at tincidunt ex faucibus. Sed lectus odio, pellentesque consectetur ultricies id, sodales quis ligula. Maecenas accumsan facilisis leo, ut fringilla leo elementum vitae. Aenean malesuada arcu urna, at commodo lorem vestibulum nec. Aliquam venenatis nisl et purus tincidunt accumsan. Donec hendrerit erat et viverra hendrerit. Praesent lorem enim, ullamcorper at lectus quis, accumsan vulputate felis. Integer ex erat, ullamcorper hendrerit arcu eu, sagittis tincidunt felis. Vivamus auctor sed velit vitae consectetur. Duis convallis placerat vulputate. Donec turpis sem, laoreet at massa id, venenatis rhoncus diam. Praesent pharetra sem sit amet porttitor rhoncus.

Morbi vel velit eget orci posuere gravida et et odio. Proin dignissim, diam vitae consectetur porta, velit massa convallis massa, vestibulum hendrerit tortor turpis vel ex. Ut lobortis neque a mauris ultrices, a pellentesque nunc luctus. Vivamus a erat ipsum. Integer auctor interdum vestibulum. Pellentesque faucibus, urna id tincidunt egestas, purus nisi cursus ipsum, non mollis quam sapien non dolor. Aliquam quam leo, tempus quis feugiat quis, dapibus nec nulla. Duis posuere pulvinar leo quis eleifend. Duis vulputate nisi id orci semper, non finibus diam dignissim. Etiam vitae mauris ac nibh tempus euismod. Praesent posuere justo ut quam interdum, vel feugiat justo consectetur. Etiam sagittis cursus dignissim. Vestibulum eget pharetra lacus. Suspendisse pellentesque est vel varius faucibus.

Ut interdum accumsan massa ut dictum. Curabitur vel dapibus sem, non faucibus mauris. Maecenas lacinia enim vel lectus commodo, vel sodales quam varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer lobortis arcu nec libero tristique egestas. Donec tincidunt finibus nunc ut ullamcorper. Nam ut diam nec ex hendrerit euismod eu sed dolor. Nunc elementum non neque et interdum. Vestibulum malesuada tincidunt sapien, egestas convallis dui ornare non. Morbi blandit sit amet quam ac aliquet. Aliquam sit amet sollicitudin risus, sed maximus dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer magna felis, gravida in nisl sed, rhoncus scelerisque metus.

Praesent ac turpis nisi. Aliquam vitae odio nec mi porttitor rutrum quis sit amet magna. Sed id ipsum fermentum, venenatis erat ut, feugiat dui. Morbi consectetur imperdiet eleifend. Aenean ultrices sed lectus ut fermentum. Morbi nec ultrices felis. Vestibulum at diam neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec pulvinar erat eget arcu dapibus dignissim. Vestibulum eu maximus est. Suspendisse dictum tortor sit amet urna sagittis lobortis. Etiam neque nisi, aliquam vel mi at, vulputate hendrerit neque.
<p/>
<body>
"""
HTML(html)
```

I've recorded a video of the issue (sorry for the low quality, I had to reduce it to fit in 10MB): 

https://user-images.githubusercontent.com/2721423/180147718-1d634352-ad5d-4b60-ad87-9584850eeb1a.mov

### VS Code Version

Version: 1.69.2 Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a Date: 2022-07-18T16:32:39.000Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Darwin arm64 21.5.0

### Jupyter Extension Version

v2022.6.1201981810

### Jupyter logs

```shell
info 8:40:3.370: Execute Cell 6 /Users/thomas/oda/fabrica/projects/kaggle-amex/scroll.ipynb
info 8:40:3.478: Cell 6 executed with state Success
info 8:47:11.586: Execute Cell 6 /Users/thomas/oda/fabrica/projects/kaggle-amex/scroll.ipynb
info 8:47:11.634: Cell 6 executed with state Success
```

### Coding Language and Runtime Version

Python 3.10

**Comment by rebornix** [comment]
This issue should be fixed now in latest Insiders.

**Comment by andreamah** [comment]
I still see this on the latest insiders with the latest jupyter pre-release

<img width="978" alt="image" src="https://user-images.githubusercontent.com/31675041/226989148-88cd8538-a5ee-4008-9806-bbef9395fac7.png">

**Comment by andreamah** [comment]
Oh, I read the issue incorrectly. The bug has been resolved.
