### ISSUE TITLE
Sticky Scroll: Arrow functions assigned to variables not sticking.

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#156333]
Testing #156175

Within a class, I declared a function like:

```
  public exampleFunc= () => {
        .....
  };
```

And it seemed not to stick. 

[![Image from Gyazo](https://i.gyazo.com/bf6c7f4252b5a9df7facff06e644f085.gif)](https://gyazo.com/bf6c7f4252b5a9df7facff06e644f085)

However, I noticed that arrow functions that are part of arguments stick.

ie: 
```
example(e => { .... });
```
seemed to work. Ideally, this would be consistent.

**Comment by Madalosso** [comment]
:+1:

**Comment by aiday-mar** [comment]
Thank you for the feedback. This issue should be solved with PR: https://github.com/microsoft/vscode/pull/157483

The new behavior

![sticky-scroll-arrow-func2](https://user-images.githubusercontent.com/61460952/183902403-61cbcf7d-7526-4768-b5cc-3f5c306ea1aa.gif)

**Comment by wmelton** [comment]
Hey @aiday-mar - I see that PR #157483 was merged, but as of today I still see this issue for arrow functions. Am I wrong in assuming that our `const splitFloat` should be sticky here?
![Kapture 2022-08-19 at 11 06 32](https://user-images.githubusercontent.com/1544125/185661450-90afeab6-e354-4768-b912-c607548ae3ac.gif)

**Comment by aiday-mar** [comment]
Hi thanks for the feedback. The change has appeared in the Insiders version of VSCode. You will see it officially in the next stable build which happens only once per month. You may find the Insiders version of VSCode here https://code.visualstudio.com/insiders/.

**Comment by meganrogge** [comment]
Hey @aiday-mar this is not working for me for this example: 

```
	public logFunc = () => {
		const x = 3;
		console.log(x);
	};
```

**Comment by wmelton** [comment]
Thanks @aiday-mar and great job getting this fixed so quickly! Great feature addition.

**Comment by aiday-mar** [comment]
Hi @meganrogge thanks for filing the bug. That's curious, I am running the main code from the vscode repo and I get the following behavior on OSS:

![sticky-scroll-issue](https://user-images.githubusercontent.com/61460952/186463993-e71c2b8b-e5b3-44d6-8c99-d5f9624fe86b.gif)
