### ISSUE TITLE
Merge editor reports 3 conflicts when only 1 is visible

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156982]
The next/previous commands also do not work:

![image](https://user-images.githubusercontent.com/900690/182573700-25635e35-2709-49e5-9801-2e32c3ae1ce8.png)
[merge.json.txt](https://github.com/microsoft/vscode/files/9249915/merge.json.txt)

**Comment by bpasero** [comment]
This conflict was interesting because GH could not show it even on their web UI. Part of the change on `main` was that the file was renamed (from `window.ts` to `windowImpl.ts`). It happened when I merged `main` into https://github.com/microsoft/vscode/tree/sbatten/brave-lamprey

**Comment by hediet** [comment]
This fixes it:
```json
"mergeEditor.diffAlgorithm": "experimental",
```

**Comment by connor4312** [comment]
I've set `"mergeEditor.diffAlgorithm": "experimental"`, but still see "3 Conflicts Remaining" on today's Insiders. Are there additional steps?

**Comment by hediet** [comment]
With conflict markers, this is the actual result:

[conflict.json.txt](https://github.com/microsoft/vscode/files/9429001/conflict.json.txt)

**Comment by bpasero** [comment]
@hediet when I use the command to load the JSON file via https://github.com/microsoft/vscode/files/9429001/conflict.json.txt, I get this:

![image](https://user-images.githubusercontent.com/900690/186861887-8a681a8a-9fb9-496d-899b-062c918c4c10.png)

**Comment by connor4312** [comment]
The JSON blob works for me
