### ISSUE TITLE
Rename cat.exe to something else

### ISSUE THREAD

**Issue by thorn0** [Microsoft/vscode#15722]
- VSCode Version: 1.8.0-insider
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Install Git for Windows
2. Install VS Code (or let it install a new version of itself).
3. The command `where cat` gives us:
```
c:\>where cat
C:\Program Files (x86)\Microsoft VS Code Insiders\bin\cat.exe
C:\Program Files (x86)\Git\usr\bin\cat.exe
```
4. This breaks scripts that expect that the command `cat` works like the standard Unix utility.

**Comment by joaomoreno** [comment]
@bpasero I don't think `cat.exe` needs to be in `bin`. We place that in the `PATH`.

**Comment by bpasero** [comment]
`cat.exe` is no longer needed.

![image](https://cloud.githubusercontent.com/assets/900690/20477182/b468bb7e-afd4-11e6-8798-92e04eb1537f.png)

**Comment by lamarqua** [comment]
```
E:\Home>where code
C:\Program Files (x86)\Microsoft VS Code\bin\code
C:\Program Files (x86)\Microsoft VS Code\bin\code.cmd

E:\Home>where cat
C:\Program Files (x86)\Microsoft VS Code\bin\cat.exe
C:\Program Files\Git\usr\bin\cat.exe

E:\Home>code --version
1.8.1
ee428b0eead68bf0fb99ab5fdc4439be227b6281
```

The issue hasn't been solved at all.

**Comment by bpasero** [comment]
@lamarqua this looks like an issue with our update process where we are not deleting previous files. If you completely uninstall and reinstall VS Code, cat.exe will be gone.

**Comment by mloskot** [comment]
FYI, the update process is still broken. I just tripped over this bug at 1.10.2. Uninstall helps.

**Comment by m-kostrzewa** [comment]
I just lost a couple hours debugging an issue only to find out that the cat.exe I wanted to use was wrong.

I just swapped position of PATH entries to use the one I want (from Gnu Winutils), but yeah, this is a pretty silly issue ;)

**Comment by mloskot** [comment]
@m-kostrzewa It's been fixed, You just need to re-install
