### ISSUE TITLE
resizing terminal stretches text somtimes

### ISSUE THREAD

**Issue by joshribakoff-sm** [microsoft/vscode#157585]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Type: <b>Bug</b>

sometimes when resizing some panes have text super large & distorted, other panes do not have the issue.

VS Code version: Code - Insiders 1.71.0-insider (Universal) (b0895f9fcc5b49587a2b187a92bbe6d7efae35fa, 2022-08-08T05:19:27.279Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 4, 3|
|Memory (System)|32.00GB (4.36GB free)|
|Process Argv|--crash-reporter-id 4f6f994d-06c3-4289-b6cd-8f17e07dfe06|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
vscode-graphql|Gra|0.7.1
vscode-graphql-syntax|Gra|1.0.4
angular-console|nrw|17.19.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253

```

</details>

**Comment by joshribakoff-sm** [comment]
<img width="1791" alt="Screen Shot 2022-08-08 at 5 09 47 PM" src="https://user-images.githubusercontent.com/97546767/183535413-7c2a2602-f591-4037-8084-24762122605b.png">

**Comment by LeanderD** [comment]
Same problem here (but horizontally) and for me scrolling in the pane with stretched/squashed text doesn't work anymore.
I can still move the scrollbar, but nothing happens.

**Comment by Tyriar** [comment]
This may be fixed with the fix for https://github.com/microsoft/vscode/issues/157444

**Comment by meganrogge** [comment]
Steps to repro and the error we've been seeing in the console described here https://github.com/microsoft/vscode/issues/158468

**Comment by meganrogge** [comment]
Don't think it's fixed as I've seen the error in the console in insiders

**Comment by Tyriar** [comment]
The error from https://github.com/microsoft/vscode/issues/158468

```
Uncaught TypeError: Cannot read properties of undefined (reading 'ext')
    at e._loadColorsForCell (WebglRenderer.ts:404:95)
    at e._updateModel (WebglRenderer.ts:351:14)
    at e.renderRows (WebglRenderer.ts:298:10)
    at t._renderRows (RenderService.ts:124:20)
    at e._renderCallback (RenderService.ts:64:70)
    at e._innerRefresh (RenderDebouncer.ts:72:10)
    at RenderDebouncer.ts:51:68
```

Related: https://github.com/microsoft/vscode/issues/157715

**Comment by Tyriar** [comment]
I wonder if this is related to the resize observer occurring for a previous canvas update but it not firing for the current change when resizes occur in quick succession? https://github.com/xtermjs/xterm.js/blob/c0ef2ccb5a0b2f22f28ed594f3962d75cc83da00/src/browser/renderer/DevicePixelObserver.ts#L9

Example:

- Canvas is changed to to 5x10, resize observer is queued
- Canvas is changed to 10x10, resize observer does not get queued for some reason?
- Resize observer is fired for 5x10 only?

**Comment by janosh** [comment]
Just stumbled over this in the final 1.71 release. Like @LeanderD said, this also breaks scrolling in terminal.

![Screen Shot 2022-09-01 at 13 09 20](https://user-images.githubusercontent.com/30958850/188003083-829fa439-257c-4164-95e0-825765866b02.png)

**Comment by gkn** [comment]
Consistently gets this error. It seems it occurs when outpout in a bash terminal window is larger than the current window, e.g. I can replicate it by running a "npm outdated" command that has a wide and long output. Window content including characters will then crudely be zoomed in/out when terminal window is resized, and not re-rendered as it used to be before 1.71

**Comment by fparhat-rbi** [comment]
+1 I am able to reproduce this every time and it is quite annoyin

**Comment by asdutoit** [comment]
Same issue for me:
<img width="963" alt="Screenshot 2022-09-04 at 14 07 22" src="https://user-images.githubusercontent.com/20240370/188312686-649847be-0cae-41d2-8c82-75b0eb67fb7f.png">

**Comment by dmitri-suvorov-sumup** [comment]
Same here

**Comment by Tyriar** [comment]
Anyone seeing this could you provide you `window.zoomLevel` setting and what the output is when you open developer tools (help menu), go to console and run `window.devicePixelRatio`?

**Comment by dmitri-suvorov-sumup** [comment]
> Anyone seeing this could you provide you window.zoomLevel setting and what the output is when you open developer tools (help menu), go to console and run window.devicePixelRatio?

![devicePixelRatio](https://user-images.githubusercontent.com/53574544/188654729-9e97c1ad-7b9c-4e1c-8122-c0f58cbd0586.png)

**Comment by Tyriar** [comment]
Thanks @gkn and @dmitri-suvorov-sumup, that's useful

**Comment by gkn** [comment]
A workaround until this bug is fixed, is to disable WebGL in settings, e.g.: 
"terminal.integrated.gpuAcceleration": "canvas"

**Comment by Tyriar** [comment]
Looks like all reports are on macOS

**Comment by brauliolledo** [comment]
Hey @Tyriar, I'm having the same issue on Fedora 36 running on Gnome. I can include more details if needed. The solution posted by @gkn did work for me as a temp workaround.

**Comment by Tyriar** [comment]
Recording showing the issue: https://github.com/microsoft/vscode/issues/160508#issuecomment-1241796756

**Comment by Tyriar** [comment]
I've tried and tried, can't reproduce. Will dig into the code and make a defensive change for the thrown exception if I can't find the problem.

**Comment by Tyriar** [comment]
This is probably where undefined slips in: https://github.com/xtermjs/xterm.js/blob/f9db65c52e4702cf906c14cda1c640342a7b6dca/src/common/buffer/BufferLine.ts#L183-L185

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/4108

**Comment by gkn** [comment]
Seems like @Tyriar has found the issue now but for the record, I get this error on VS Code running on Windows 10 with WSL2 Ubuntu 20.

**Comment by ryenus** [comment]
Hmm, a bit pity that the fix is not in 1.71.2, which I believe it should.

**Comment by danawoodman** [comment]
I'm seeing similar behavior to the described issue using the latest VSCode on macOS:

![Screen Recording 2022-09-23 at 02 02 47 PM](https://user-images.githubusercontent.com/157695/192056365-43b1b1b0-6615-4669-bc85-493ec80e96b3.gif)

![image](https://user-images.githubusercontent.com/157695/192056404-9a81fd11-2c0d-4258-915e-e4dab070463d.png)


This is new, only occurring in the past few weeks.

**Comment by leafac** [comment]
Same story here: The issue is happening to me on the latest versions of Visual Studio Code and macOS. It seems like turning off GPU rendering for the terminal works for the time being, while the issue is being fixed…

**Comment by kaovilai** [comment]
Pretty sure we gotta wait till https://github.com/microsoft/vscode/commit/b24fefc5403ae8152db6d79eb80333f77e199a6f makes it into one of the release tags and an update published.

**Comment by airtonix** [comment]
> Same story here: The issue is happening to me on the latest versions of Visual Studio Code and macOS. It seems like turning off GPU rendering for the terminal works for the time being, while the issue is being fixed…

what's the setting for that please?

**Comment by Tyriar** [comment]
The fix for this should be released today or tomorrow

**Comment by harvey56** [comment]
@Tyriar Hi ! Would the change be listed here once the bug is fixed ? 

https://github.com/VSCodium/vscodium/releases

**Comment by harvey56** [comment]
This specific issue is fixed, but it looks like another bug was introduced in the meantime 🥳. Try and add additional terminals, and you will understand. One bug was traded for another one.

**Comment by Tyriar** [comment]
@harvey56 you'll need to give some more more info, I've been using the fixed version for almost a month and don't see an issue when I create additional terminals. If there is a real issue please detail it and it might get shipping in the upcoming recovery release

**Comment by dement6d** [comment]
this is still an issue
![image](https://user-images.githubusercontent.com/93228501/196043623-5b1c13e9-5d52-48fe-af13-4ae2e9024dc5.png)
