### ISSUE TITLE
Ctrl click sticky header is showing peek view out of viewport

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158813]
Testing https://github.com/microsoft/vscode/issues/157055

Unexpected behavior here:

It seems to be scrolling to the right spot but the peek view is partially out of view:

![Recording 2022-08-22 at 11 36 02](https://user-images.githubusercontent.com/2193314/185994266-86f83a48-a586-48f3-86f6-daaa3738a418.gif)

The file https://github.com/xtermjs/xterm.js/blob/master/src/browser/Clipboard.ts

Code - OSS @ 380647ccd574049f9f5fb5836b4b28e3088202ac:

Version: 1.71.0
Commit: Unknown
Date: Unknown
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

**Comment by jrieken** [comment]
@aiday-mar This can happen when a symbol has multiple definition locations. In that case we use peek to show all definitions and we need to make sure that revealing works nicer.

**Comment by connor4312** [comment]
This seems like it's still present on today's Insiders

https://user-images.githubusercontent.com/2230985/186279194-bce45183-1129-4112-a752-7ee67de7bb8e.mp4

If it helps to test, this is the file I was using: https://github.com/connor4312/cockatiel/blob/master/src/common/Executor.test.ts

**Comment by aiday-mar** [comment]
Hi Connor, thanks for your bug. This should be solved with the PR: https://github.com/microsoft/vscode/pull/158887 that was created today. The new behavior is:

![sticky-scroll-pr](https://user-images.githubusercontent.com/61460952/186462784-4088c908-5075-480a-9072-cfe4651e149b.gif)

**Comment by Tyriar** [comment]
The cursor position is still wrong when I try verify on the same file:
![Recording 2022-08-25 at 07 00 04](https://user-images.githubusercontent.com/2193314/186685220-32c3b1c5-56f5-4ee2-b4c8-7402c8c6ab6a.gif)

**Comment by Tyriar** [comment]
Nvm, tested the wrong version due to delayed insiders today
