### ISSUE TITLE
RPM repository update excessive download size (Linux)

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode#159362]
This issue is with the Visual Studio Code binary redistribution infrastructure for RPMs, at https://packages.microsoft.com/yumrepos/vscode

The RPM repository https://packages.microsoft.com/yumrepos/vscode seems to have accumulated a very large amount of excess data, which makes running a local RPM update operation take a rather long time. 

Note that this is not about the size of the Visual Studio Code _product_ RPM itself, but about the amount of data that, for instance, a `sudo dnf upgrade --refresh` transfers to update the local package database before deciding whether upgrading is required.

Steps to Reproduce:

* have Fedora Linux 36 as a baseline system (may apply to other distributions - such as RedHat, CentOS, OpenSUSE - as well)
* have Visual Studio Code installed as a product

Note that this will add an RPM repository to the operating system; the content of mine is
```
❯ cat vscode.repo 
[code]
name=Visual Studio Code
baseurl=https://packages.microsoft.com/yumrepos/vscode
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
```
Now run
* `sudo dnf upgrade --refresh`
and observe the output; for me this is (as I am writing this)

```
Fedora 36 - x86_64                                     109 kB/s |  21 kB     00:00    
Fedora 36 openh264 (From Cisco) - x86_64                10 kB/s | 1.5 kB     00:00    
Fedora Modular 36 - x86_64                             118 kB/s |  21 kB     00:00    
Fedora 36 - x86_64 - Updates                            20 kB/s |  16 kB     00:00    
Fedora Modular 36 - x86_64 - Updates                    18 kB/s |  15 kB     00:00    
teams                                                   14 kB/s | 3.0 kB     00:00    
Visual Studio Code                                      15 kB/s | 3.0 kB     00:00    
Visual Studio Code                                     709 kB/s |  28 MB     00:40  
```
Note the very last line here - this is something server-side on https://packages.microsoft.com/yumrepos/vscode for Visual Studio Code which causes a total of 28 MB to be downloaded, for a total time spent of 40 seconds.

28 MB seems to be excessive and makes determining update packages take a long time.

Do look at the size of the update information for the _complete_ Fedora product (comprising of, I guess, a great many more packages): This is on the order of 70 KB.

Expectation: The vscode rpm update information downloaded should be at most on the order of the size of the full Fedora distribution. I expect a reasonable size to 20 kilobytes - and not 28 megabytes.

This will drastically reduce the amount of data transferred, will accelerate distribution updates, for every single user of the Microsoft RPM repository for Visual Studio Code.

**Comment by shoffmeister** [comment]
FWIW, splitting the repos for "insider", "exploration", and normal builds might help (and would be natural to do) - but I do not know anything about the impact that this has on the distribution pipeline.

**Comment by Rdna123** [comment]
This would be helpful

**Comment by muzuiget** [comment]
The vscode metadata file even bigger the whole Fedora, this doesn't make sense.

**Comment by wingedrhino** [comment]
I think it is because the old versions are never deleted and the file lists keep adding up. https://packages.microsoft.com/yumrepos/vscode/

I downloaded the repodata from https://packages.microsoft.com/yumrepos/vscode/repodata/ and opened it in dbeaver.

```sql
select count(*) from filelist where filenames = 'node';
```

This shows 31971 entries! It's like NOTHING is ever deleted.

**Comment by smellymoo** [comment]
it's 2023 now. no change?

**Comment by iproute2** [comment]
it's 2023 now, any progress on this ?

**Comment by DimitriGilbert** [comment]
Any updates ? That would help most of the world that do not have multi Gb/s connexion...(me included)

**Comment by smellymoo** [comment]
easy solution is to move to VS Codium the open source version, then you don't have Microsoft tracking and spyware, and also this repo problem is fixed!

I'm leaving VS Code :wave:

**Comment by Alexandero89** [comment]
Problem still persists and is even worse.
Now downloading 36mb each time.

The milestone is set back a lot of times, but is there maybe some progress?

**Comment by HazemKaroui** [comment]
Any updates on this?
`dnf update` is significantly slowed down with a `36MB` daily vscode repo download vs the other system repos which are about `2MB` combined.

**Comment by smellymoo** [comment]
just use vscodium, it's better anyway, and the repo works properly.

**Comment by Alexandero89** [comment]
> just use vscodium, it's better anyway, and the repo works properly.

Allthoug this does not fix the issue, it was a solution for me.
Thanks for the info. Did not know about vscodium but switched now.

**Comment by rzhao271** [comment]
Fixed with manual cleanup commands.
I'll create an internal issue to automate the process.

Verification steps for endgame:
1. Navigate to https://packages.microsoft.com/yumrepos/vscode/Packages/c/
2. Confirm that there are no code packages older than 1.78.0.

**Comment by connor4312** [comment]
@rzhao271 It looks like there are a few random older versions; are these intentional?

**Comment by rzhao271** [comment]
No, but I'll create a new issue for that in addition to the automated cleanup feature request.
