### ISSUE TITLE
The term 'd:\Program' is not recognized as a name of a cmdlet when shell integration enabled

### ISSUE THREAD

**Issue by liesauer** [microsoft/vscode#159633]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS Version: win 10 19044

Steps to Reproduce:

1. upgrade vs code to `1.70.0`
2. enable shell integration
3. new terminal

![image](https://user-images.githubusercontent.com/8676741/187571741-6f5b0838-f493-40fe-88bb-8847763c88e4.png)

if disable the shell integration, the error disappears, i don't know what command that shell integration is trying to execute.

![image](https://user-images.githubusercontent.com/8676741/187571978-6a807d7c-efe6-44cc-a03d-85137044da9b.png)

**Comment by liesauer** [comment]
#151323

**Comment by liesauer** [comment]
after update to the latest 1.70.2, this issue just gone, i suppose this issue has been fixed in `1.70.2`? or the installer reset something and mysteriously fixs  this issue? i don't know.

**Comment by Tyriar** [comment]
It may have been fixed by https://github.com/microsoft/vscode/issues/157083

@liesauer does shell integration work after the update as well?

**Comment by liesauer** [comment]
you remind me. shell integration still doesn't work although the error has gone.

**Comment by Tyriar** [comment]
Weird, the space problem should have been fixed by https://github.com/microsoft/vscode/issues/151323

**Comment by liesauer** [comment]
i try user installer and put at `C:\Program Files\Microsoft VS Code` too, latest pwsh `7.2.6`, latest vs code `1.70.2` 
 in a fresh system using windows sandbox, i can't reproduce it either😂. is there any setting that can log the details and helpful diagnosis infomation?

**Comment by Tyriar** [comment]
I think this has been fixed since, we haven't got reports for months
