### ISSUE TITLE
Hello! Tree view search by shortcut key does not show the search control in some cases? Please rule out the cause and fix it in time!

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#162901]
Type: <b>Bug</b>

Hello! Tree view search by shortcut key does not show the search control in some cases? Please rule out the cause and fix it in time!
And the shortcut keys used after testing do not conflict with other keys. . .

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

![2022-10-07_084454](https://user-images.githubusercontent.com/54253524/194443238-0e4abd3e-d17d-4df4-946d-72a6c03fe2d8.png)

**Comment by gjsjohnmurray** [comment]
Are you certain that focus is in the tree when pressing Ctrl+F fails to open the search/filter widget?

**Comment by joaomoreno** [comment]
@gjsjohnmurray I think this is referring to the new Search option: view as tree.

**Comment by gjsjohnmurray** [comment]
> @gjsjohnmurray I think this is referring to the new Search option: view as tree.

@joaomoreno but the screenshot is of Explorer.

**Comment by andreamah** [comment]
@zhouxinghong when is the command failing? Can you give some steps to help me reproduce the issue? Also, please make sure you're in the search viewlet, I think that your screenshot shows that you're on the file explorer.

**Comment by zhouxinghong** [comment]
> @zhouxinghong when is the command failing? Can you give some steps to help me reproduce the issue? Also, please make sure you're in the search viewlet, I think that your screenshot shows that you're on the file explorer.

Hello! Please see the 1.72 documentation, it is operated in the resource manager
https://code.visualstudio.com/assets/updates/1_72/tree-remember.gif

**Comment by zhouxinghong** [comment]
Hello! Please see the 1.72 documentation, it is operated in the explorer, but I follow the same operation method, vscode has no response, but I use ctrl+alt+h. Or how did you do it, can you provide a detailed how-to video?

**Comment by zhouxinghong** [comment]
Hello! Please see
https://code.visualstudio.com/updates/v1_70#_tree-find-control

**Comment by gjsjohnmurray** [comment]
> Are you certain that focus is in the tree when pressing Ctrl+F fails to open the search/filter widget?

@zhouxinghong did you check this?

**Comment by zhouxinghong** [comment]
![2022-10-10_160707](https://user-images.githubusercontent.com/54253524/194822903-b729b9d1-0b8e-4d0b-8289-5e3c092458bf.png)

**Comment by joaomoreno** [comment]
@zhouxinghong Did you try <kbd>Ctrl F</kbd>?

**Comment by zhouxinghong** [comment]
> > 当按 Ctrl+F 无法打开搜索/过滤器小部件时，您确定焦点在树中吗？
> 
> @zhouxinghong你检查了吗？

The focus must be in the resource manager

**Comment by zhouxinghong** [comment]
> list.find

![image](https://user-images.githubusercontent.com/54253524/194843284-32da6f2f-1a77-45f6-b08c-19748bef64a4.png)

**Comment by zhouxinghong** [comment]
> @zhouxinghong你试过了Ctrl F吗？
> 
> `list.find`是要覆盖的命令：
> 
> ![图片](https://user-images.githubusercontent.com/22350/194832735-1307fe8e-aac9-4709-8fb4-f5bbdfea333e.png)
It seems that the problem has been solved according to your tips, thank you very much! 👍👍😜, but one thing to note is that the floating widget cannot be dragged to the bottom. Can this problem be improved?

**Comment by joaomoreno** [comment]
@zhouxinghong After a handful of comments, we still don't understand 100% what your problem is. Can you please be specific about it? Maybe find someone who can translate it for you?

**Comment by zhouxinghong** [comment]
> @zhouxinghong After a handful of comments, we still don't understand 100% what your problem is. Can you please be specific about it? Maybe find someone who can translate it for you?

Based on your tips, the problem has been solved, thank you very much! 👍👍😜
But the problem that needs to be clarified is: it is not possible to drag the floating widget to the bottom of the explorer by mouse. Can this issue be improved?

根据您的提示，问题已经得到解决，非常感谢您！ 👍👍😜
但需要说明的问题是：无法将浮动小部件通过鼠标拖动到资源管理器的底部。 这个问题可以改善吗？
