### ISSUE TITLE
Merge editor current/incoming lines can overlap

### ISSUE THREAD

**Issue by danloomer** [microsoft/vscode#164828]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: macOS Montery 12.6

Steps to Reproduce:

1. open merge editor while rebasing on a branch with a lot of branch pointers or ones with a long name

The text from the "Current" column overlaps into the "Incoming" column. Confirmed that it happens with the default theme as well.

![image](https://user-images.githubusercontent.com/59700952/198371142-cf8d8873-2127-4161-bbdf-21c6ef79e104.png)

**Comment by hediet** [comment]
Please try out the latest insiders, this should be fixed.

**Comment by danloomer** [comment]
Still appears to be an issue in the latest insiders
![image](https://user-images.githubusercontent.com/59700952/198686746-9fffa378-dc79-47a4-a386-883b617bd32d.png)

![image](https://user-images.githubusercontent.com/59700952/198686758-9c50d60e-dd62-4373-acfa-d85c5583d0f2.png)
