### ISSUE TITLE
Allow code-server to server on a subpath

### ISSUE THREAD

**Issue by mariokostelac** [microsoft/vscode#165391]
AWS published a tutorial on putting behind jupyter's proxy
https://aws.amazon.com/blogs/machine-learning/host-code-server-on-amazon-sagemaker/.

The end result is that you can use Visual studio code on machines like SageMaker, going through whatever auth Jupyter goes through. Jupyter sits on root path `/`, vscode sits on some configurable subpath e.g. `vscode`.

I've managed to get code-server to load the main page behind the proxy, but loading all further assets fails because paths to assets are defined like `/stable-<sha>/static/out/vs/loader.js` instead of `/vscode/stable-<sha>/static/out/vs/loader.js`.

Allowing the code-server to server from some subpath would allow me to use your code-server, instead of https://github.com/coder/code-server describes in the tutorial.

**Comment by qmfrederik** [comment]
Fwiw, the downstream patch for this is here: https://github.com/coder/code-server/blob/efce00582be630fdbfd02cfe1d37ad079b3a9b5e/patches/base-path.diff

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/pull/202491

**Comment by mering** [comment]
@aeschli #202491 does still not load resources correctly when behind a proxy (see the comments there). Can you please re-open?

**Comment by aeschli** [comment]
@mering Please file a new feature request

**Comment by alexr00** [comment]
@aeschli what's the best way to verify this?

**Comment by aeschli** [comment]
- In a terminal or command prompt run `code-insiders serve-web --server-base-path foo/bar`
- This will print a URL. Open it in a browser
- Verify that the opened VSCode is functional.

**Comment by mering** [comment]
@aeschli I created a new issue in #210399.
