### ISSUE TITLE
Integrated terminal is rendered incorrectly when switching back to an inactive terminal tab

### ISSUE THREAD

**Issue by rdzhaafar** [microsoft/vscode#166353]
<img width="719" alt="Screenshot 2022-11-15 at 11 02 23" src="https://user-images.githubusercontent.com/38199959/201905172-7ef58953-6aae-4f55-abf8-3e3acd046eca.png">
Type: <b>Bug</b>

The integrated terminal renders incorrectly when switching back to an inactive terminal tab.

I haven't figured out a reliable way to reproduce this, but this is how it happens usually:
- Have multiple terminal tabs open
- Leave one of them inactive for a while and use other tabs (maybe switch to other applications)
- Come back to the inactive terminal tab

The issue goes away after a command is executed inside the faulty tab.

To be honest, this looks like a rendering buffer issue, but I'm not familiar with VSCode internals to say more.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|14.2.0
prettier-vscode|esb|9.9.0
go|gol|0.36.0
rest-client|hum|0.25.1
isort|ms-|2022.6.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.20
material-icon-theme|PKi|4.22.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1285
vs-code-prettier-eslint|rve|5.0.4
vscode-lldb|vad|1.8.1

(2 theme extensions excluded)

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by rdzhaafar** [comment]
I'll use the insiders build for a week and let you know if I can still reproduce it.

**Comment by meganrogge** [comment]
Ok lmk and I'll reopen if so.
