### ISSUE TITLE
VSCode hangs when switching between local login and remote desktop login if the display Scale changes

### ISSUE THREAD

**Issue by shaunco** [microsoft/vscode#167556]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Log in locally to your Windows desktop
2. Set scaling to 150% (Control Panel-->System-->Display)
3. Take note of the display resolution
4. From a local login, open a project in VSCode
5. Lock the local workstation (do not log out)
6. From a different system where scaling is set to something other than 150%, and preferably the resolution is also different
7. Open Remote Desktop Connection
8. Enter the IP of the original system
9. Click Connect
10. Log in

VSCode will resize the outermost frame of the window, but will leave Explorer and code windows smaller, and will be unresponsive to mouse or keyboard input. After about 15 seconds, you'll get a popup that says:

"The window is not responding. You can reopen or close the window or keep waiting"

If you choose "Reopen", a new instance of VSCode will launch and will work fine. If you Keep Waiting, it will never come back.

**Comment by ringwraith** [comment]
same problem for a long time

**Comment by vware** [comment]
same here, but not for a long time. started to happen after most recent win11 upgrade. chrome actually had the same problem, but that one is fixed now. vscode isnt, sadly.

**Comment by jozocai** [comment]
Similar here

**Comment by XianwuLin** [comment]
same issue.

**Comment by liberize** [comment]
very annoying

**Comment by zerkz** [comment]
weird. started the profiler through the developer tools, disconnected RDP, reconnected, waited couple mins for vscode to unfreeze, and stopped the profiler. 

Nothing stood out to me as "stuck" or taking a long time from the gpu or main.js thread.

**Comment by yo1dog** [comment]
For context, this is not unique to vscode for me. The Slack desktop app (pretty sure is also browser based) exhibits similar behavior.

**Comment by zerkz** [comment]
@yo1dog  That seems to point to an issue with electron or browserview then.

**Comment by zerkz** [comment]
I have a AMD card so that throws the nvidia issue out -- but could still be chromium/windows related 🤔

**Comment by cpbotha** [comment]
I am seeing similar behaviour as @cicorias 

Windows Terminal will freeze completely. Their main issue for this is https://github.com/microsoft/terminal/issues/12607 -- I have disabled hardware rendering for Terminal, and it seems to help.

My VSCode is also frozen when I re-attach, either via RDP, or at the machine in question, but indeed it ofter recovers after a few minutes, sometimes asking to reconnect. (I use WSL) For  now I have added `"disable-hardware-acceleration": true` to `Preferences: Runtime arguments`

So far, my Edge has not yet been able to recover, but I have never been able to wait long enough.

I have an nvidia in this machine.

**Comment by clshortfuse** [comment]
Not specific to VS Code and not specific to Local/Remote changing. I'm working remotely for vacation and haven't been local. It happens on first connect and also when I lose internet (spotty WiFi) and reconnect. I have 3 Chromium-based windows opened: VSCode, Chrome with default profile and Chrome with a non-default profile (debugging window). Just connecting over RDP will hang VS Code and my primary Chrome window. Oddly enough a Chrome window not on default profile (the one I had open for debugging) responds just fine.

Opening a new tab in Chrome via the Windows taskbar will show a white window. But eventually, after a long while everything will start working again. 

Happens with Chrome Canary as well. It's a rendering issue, seems like, which is interesting because the mouse cursor does change and I can close a Chrome window if I click on the x on the only opened tab.

Nvidia GPU and Windows 11.

**Comment by elephaint** [comment]
Same issue here, but disabling gpu when starting VS Code seems to have fixed the problem for me, i.e. start vs code by running:

`code --disable-gpu`

For now I'm ok with this fix, but I might fiddle around with different GPU drivers in the future to see if it that's the issue.

My setup:
- VS Code version: 1.75.1
- OS version: Windows_NT x64 10.0.22621 (11 Pro)
- GPU: nVidia RTX 3090FE, Game Ready driver 526.98

The issue occured under the following circumstances:
- RDP from Samsung Galaxy Tab s8+ (Android 13, using MS RDP app version 10.0.15.1208, or when using Devolution Remote Desktop Manager 2022.3.5.0) into the Windows machine, resolution set to 2800x1752@200% scaling.
- Using my normal screen that is attached to the Windows pc by DP cable (LG34WK95U) _after_ an RDP session. This monitor has a resolution of 5120x2160 and I'm using a 150% scaling in Windows.

**Comment by Crear12** [comment]
> I've seen this with Google Chrome too. VS Code, and Windows Terminal.
> 
> For Windows Terminal I've tried their Preview and it uses different rending logic apparently. Team indicate some issues with NVIDIA -- but that has done better in haven't seen freezes.
> 
> Edge surprisingly "recovers" after a bit; where as Google Chrome never does.
> 
> VS Code I've affected the experimental terminal GPU rendering flag to "canvas" for now to see if that helps.
> 
> This seems like a Windows/NVIDIA driver issue on desktop resizing.
> 
> So, kinda seems Chromium based.

Oh, I encountered frozen Windows Terminal frequently. Then I have to use Admin to run Anaconda Prompt because I have some intensive tasks that need to run multiple days. I never thought it's caused by Remote Desktop...

For VS Code..Seriously? Almost the best tool I've ever used, but also, I'm more of a RDP guy. C'mon, both RDP and VS Code are from Microsoft......

**Comment by rwasef1830** [comment]
KB5022913 for Windows 11 22H2 appears to solve this issue for Edge/Chrome/Windows Terminal. It may solve it for VS Code as well.

**Comment by LancelotLewis** [comment]
> KB5022913 for Windows 11 22H2 appears to solve this issue for Edge/Chrome/Windows Terminal. It may solve it for VS Code as well.

seems not work well

**Comment by kishoredbn** [comment]
I am still seeing this problem. I am in most updated Windows 11. 

Here is a screenshot
https://pasteboard.co/QyG6ZKRdQqqZ.png

**Comment by whyb** [comment]
Same issue. Recently, The edge browser has the same problem, which seems to be a problem of upstream chromium.

**Comment by xgfone** [comment]
I met with the same trouble. Just for VSCode on Windows 11, and other softwares, such as Edge, are OK. VSCode on Linux is OK.

 Any update on this?

**Comment by loming1st** [comment]
Seems to be fixed in the KB5026372 update.

**Comment by fakerror** [comment]
I found an extremely ugly but effective temporary solution to recover from an unresponsive window input without needing to restart VSCode.

When the window becomes unresponsive, losing and regaining focus can restore operation, but if you enter any character again, the window will freeze.

In a fortuitous circumstance, I found that you can continuously input random characters when the window freezes, then click another code tab (while still inputting random characters), and then allow the window to lose focus and regain it. This process can restore the operation.

You might not have enough hands to make the window lose focus, but remember, the Windows key (Win key) can also do the trick.

**Comment by Student414** [comment]
same issue.

**Comment by wpc2333** [comment]
> I found an extremely ugly but effective temporary solution to recover from an unresponsive window input without needing to restart VSCode.
> 
> When the window becomes unresponsive, losing and regaining focus can restore operation, but if you enter any character again, the window will freeze.
> 
> In a fortuitous circumstance, I found that you can continuously input any characters(Press a character button without releasing it) when the window freezes, then click any other character-inputable area within the frozen window (while still inputting characters), then make the window to lose focus and regain it. This will restore the window from freezing.
> 
> You might not have enough hands to make the window lose focus, but remember, the Windows key (Win key) can also do the trick.



> I found an extremely ugly but effective temporary solution to recover from an unresponsive window input without needing to restart VSCode.
> 
> When the window becomes unresponsive, losing and regaining focus can restore operation, but if you enter any character again, the window will freeze.
> 
> In a fortuitous circumstance, I found that you can continuously input any characters(Press a character button without releasing it) when the window freezes, then click any other character-inputable area within the frozen window (while still inputting characters), then make the window to lose focus and regain it. This will restore the window from freezing.
> 
> You might not have enough hands to make the window lose focus, but remember, the Windows key (Win key) can also do the trick.

it works!
My operation process:
1: When vscode freezes and does not respond, open any other software (such as chrome or edge);
2: Switch back to vscode, press and hold any key on the keyboard without releasing it, and use the mouse to click on the frozen vscode window at the same time;
3: After clicking, switch to other open software, and switch back again to exit the frozen state.

**Comment by Student414** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yo1dog** [comment]
This was fixed for me a long time, but I forgot about this ticket and when exactly it was fixed. Don't know if it was a vscode update or Windows update that fixed it, but I am currently on:

```
Version: 1.80.2 (user setup)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:40:28.909Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```
Windows OS Build: 22621.2134

**Comment by xgfone** [comment]
The trouble still exists for me.

```
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

Windows OS Build: `22621.2134`

**Comment by iruis** [comment]
same issue. has long time.

VS Code Version: 1.81.1
Windows Version: Windows 11 Pro for Workstations, 22H2, Build 22621.2134

**Comment by DUWENINK** [comment]
I think this has something to do with Chromium, because I also have this problem when using the remote Edge browser.

**Comment by ZiJiaW** [comment]
same issue

**Comment by iruis** [comment]
My solution

1. add a keyboard (https://support.microsoft.com/en-us/windows/manage-the-input-and-display-language-settings-in-windows-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2#WindowsVersion=Windows_11)
2. change keyboard layout (Win + SpaceBar)
![keyboard](https://github.com/microsoft/vscode/assets/8559783/34487937-0a51-4028-ac1d-e36b1a45d860)
3. get back keyboard layout (Win + SpaceBar)
 
Fix the problem right away

**Comment by Senorsen** [comment]
> My solution
> 
> 1. add a keyboard layout (Add a keyboard: https://support.microsoft.com/en-us/windows/manage-the-input-and-display-language-settings-in-windows-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2#WindowsVersion=Windows_11)
> 2. change keyboard layout (Win + Space bar)
>    ![keyboard](https://user-images.githubusercontent.com/8559783/264932636-34487937-0a51-4028-ac1d-e36b1a45d860.png)
> 3. get back keyboard layout (Win + Space bar)
> 
> Problem solving!

Your workaround is a live saver, it works like a charm, not only for VSCode but also for the frozen Edge, Teams, Chrome, etc...

**Comment by timhub** [comment]
> My solution
> 
> 1. add a keyboard layout (Add a keyboard: https://support.microsoft.com/en-us/windows/manage-the-input-and-display-language-settings-in-windows-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2#WindowsVersion=Windows_11)
> 2. change keyboard layout (Win + Space bar)
>    ![keyboard](https://user-images.githubusercontent.com/8559783/264932636-34487937-0a51-4028-ac1d-e36b1a45d860.png)
> 3. get back keyboard layout (Win + Space bar)
> 
> Problem solving!

This works for me, it's not the first time that Microsoft keyboard yields a major issue.

**Comment by hezzze** [comment]
same issue here

版本: 1.83.1 (user setup)
提交: f1b07bd25dfad64b0167beb15359ae573aecd2cc
日期: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

My issue more specifically is whenever I login again after a remote session, the terminal stop working as every time I try to type something it stuck

**Comment by cnSchwarzer** [comment]
It's been a year, it anyone reporting this to chromium upstream? Anyway to track the upstream fix?

**Comment by saltfishmx** [comment]
same issue

**Comment by lbmeng** [comment]
Yes, I have seen this issue for more than one year when remote desktop to my office PC running VSC or Edge browser.

I had to restart VSC or Edge when I hit this nasty issue.

Windows 11 22H2 (22621.2248)

**Comment by march1993** [comment]
> My solution
> 
> 1. add a keyboard layout (Add a keyboard: https://support.microsoft.com/en-us/windows/manage-the-input-and-display-language-settings-in-windows-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2#WindowsVersion=Windows_11)
> 2. change keyboard layout (Win + Space bar)
>    ![keyboard](https://private-user-images.githubusercontent.com/8559783/264932636-34487937-0a51-4028-ac1d-e36b1a45d860.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjcyMjcsIm5iZiI6MTcwMTIyNjkyNywicGF0aCI6Ii84NTU5NzgzLzI2NDkzMjYzNi0zNDQ4NzkzNy0wYTUxLTQwMjgtYWMxZC1lMzZiMWE0NWQ4NjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMDMwMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM0OTI5Y2JhNmMxNTcxMDFjMGRhNjc4NmVjM2RjMWFkYmY4YWRlNmYyNmIyZTljMWIxMGM4Y2IxMTBkYjFmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U_wWhuVHP0JvNgRsyAwB33j_ytYlLRKEIdCAPwjxosQ)
> 3. get back keyboard layout (Win + Space bar)
> 
> Problem solving!

I tried to kill ChsIME.exe and then the problem got solved too.

**Comment by DUWENINK** [comment]
this  issue make me unhappy a lot,i can not solve by my self  ,if have some solution about  this, call back me ,thankyou

**Comment by cnSchwarzer** [comment]
I started a Chromium Issue, vote and comment if you are interested:

https://bugs.chromium.org/p/chromium/issues/detail?id=1514402

I'm not sure if it duplicates, but the bug exists for years so I guess not. 😂

**Comment by k773920063** [comment]
Now, the EDGE has the same problem!

**Comment by DUWENINK** [comment]
Maybe this just happened  in the China Language Env?

**Comment by jackyzy823** [comment]
Some hint: Prevent using Microsoft's IME ( like Microsoft Pinyin/Wubi , Japanese ...). Using third-party IME instead helps on this issue.

**Comment by iruis** [comment]
> My solution
> 
>     1. add a keyboard layout (Add a keyboard: https://support.microsoft.com/en-us/windows/manage-the-input-and-display-language-settings-in-windows-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2#WindowsVersion=Windows_11)
> 
>     2. change keyboard layout (Win + Space bar)
> 
>     3. get back keyboard layout (Win + Space bar)
> 
> Problem solving!

It seems to not work after windows 11, version 23h2 update.

**Comment by cnSchwarzer** [comment]
The simplest solution is:
1. Press Windows Key
2. Switch to another keyboard layout (Alt + Shift in my case) when Windows Menu present
3. Go back to your app window
4. Switch back to what you need

**Comment by iruis** [comment]
windows 11, version 23h2 update

> > My solution
> > ```
> > 1. add a keyboard layout (Add a keyboard: https://support.microsoft.com/en-us/windows/manage-the-input-and-display-language-settings-in-windows-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2#WindowsVersion=Windows_11)
> > 
> > 2. change keyboard layout (Win + Space bar)
> > 
> > 3. get back keyboard layout (Win + Space bar)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Problem solving!
> 
> It seems to not work after windows 11, version 23h2 update.

in windows 11, version 23h2 update.
(korean) [https://sanctacrux.tistory.com/1930](https://sanctacrux.tistory.com/1930)

summary
1) 설정
2) 시간 및 언어
3) 언어 및 지역
4) 한국어 / 언어옵션
5) Microsoft 입력기 /  키보드옵션
6) 호환성 / 이전 버전의 Micorosoft IME 켬

google tranlation
1) Settings
2) Time and language
3) Language and region
4) Korean / language option (your input language)
5) Microsoft input method / keyboard options
6) Compatibility / Turn on older versions of Microsoft IME

**Comment by yindaheng98** [comment]
> > I found an extremely ugly but effective temporary solution to recover from an unresponsive window input without needing to restart VSCode.
> > When the window becomes unresponsive, losing and regaining focus can restore operation, but if you enter any character again, the window will freeze.
> > In a fortuitous circumstance, I found that you can continuously input any characters(Press a character button without releasing it) when the window freezes, then click any other character-inputable area within the frozen window (while still inputting characters), then make the window to lose focus and regain it. This will restore the window from freezing.
> > You might not have enough hands to make the window lose focus, but remember, the Windows key (Win key) can also do the trick.
> 
> > I found an extremely ugly but effective temporary solution to recover from an unresponsive window input without needing to restart VSCode.
> > When the window becomes unresponsive, losing and regaining focus can restore operation, but if you enter any character again, the window will freeze.
> > In a fortuitous circumstance, I found that you can continuously input any characters(Press a character button without releasing it) when the window freezes, then click any other character-inputable area within the frozen window (while still inputting characters), then make the window to lose focus and regain it. This will restore the window from freezing.
> > You might not have enough hands to make the window lose focus, but remember, the Windows key (Win key) can also do the trick.
> 
> it works! My operation process: 1: When vscode freezes and does not respond, open any other software (such as chrome or edge); 2: Switch back to vscode, press and hold any key on the keyboard without releasing it, and use the mouse to click on the frozen vscode window at the same time; 3: After clicking, switch to other open software, and switch back again to exit the frozen state.

it works! thank you so much!

**Comment by cnSchwarzer** [comment]
This should fix (at least partially) once VSCode upgrade to a electron version that based on Chromium 124.0.6367.0 
https://chromium-review.googlesource.com/c/chromium/src/+/5365680

**Comment by soulee-dev** [comment]
Struggle same issue now. This should be fixed.

**Comment by wbjlix** [comment]
I too had the same problem.
It was determined that there was a problem with IME-related settings.
It was resolved immediately by using the option to use the previous version's IME.
Very happy.

![image](https://github.com/microsoft/vscode/assets/127657988/12a2c60e-3d66-48da-a65e-c5555f8be7c2)

![image](https://github.com/microsoft/vscode/assets/127657988/13767541-c1a4-4573-ab6c-1f1d347efa79)

**Comment by ValueXu** [comment]
> I found an extremely ugly but effective temporary solution to recover from an unresponsive window input without needing to restart VSCode.
> 
> When the window becomes unresponsive, losing and regaining focus can restore operation, but if you enter any character again, the window will freeze.
> 
> In a fortuitous circumstance, I found that you can continuously input any characters(Press a character button without releasing it) when the window freezes, then click any other character-inputable area within the frozen window (while still inputting characters), then make the window to lose focus and regain it. This will restore the window from freezing.
> 
> You might not have enough hands to make the window lose focus, but remember, the Windows key (Win key) can also do the trick.

Thanks！It works for me.
And sadly, the bug still exists after a year.(T_T)

**Comment by baizebing** [comment]
> This should fix (at least partially) once VSCode upgrade to a electron version that based on Chromium 124.0.6367.0 https://chromium-review.googlesource.com/c/chromium/src/+/5365680

When will vscode update to latest chromium? Is there any plan? The issue has been anoying me for years!

**Comment by reitowo** [comment]
> When will vscode update to latest chromium? Is there any plan? The issue has been anoying me for years!

Sadly it has been reverted by Microsoft. They say they will internally see this bug, but didn't give any updates currently.

Everyone concern about this should give some pressure at:

https://issues.chromium.org/issues/328859185

**Comment by jackyzy823** [comment]
According to the [comment 37](https://issues.chromium.org/issues/328859185#comment37) , this is a Windows TSF framework bug which is confirmed and fixed by Microsoft and the fix should be released to public July - August.

**Comment by liuyxpp** [comment]
> According to the [comment 37](https://issues.chromium.org/issues/328859185#comment37) , this is a Windows TSF framework bug which is confirmed and fixed by Microsoft and the fix should be released to public July - August.

Ah, finally!

**Comment by cnrat** [comment]
> According to the [comment 37](https://issues.chromium.org/issues/328859185#comment37) , this is a Windows TSF framework bug which is confirmed and fixed by Microsoft and the fix should be released to public July - August.

It’s August 22nd, 2024, and this issue is still bothering me—classic Microsoft.

**Comment by xty435768** [comment]
still waiting for update...

**Comment by mffseal** [comment]
still waiting for update...

**Comment by jackyzy823** [comment]
Update from https://issues.chromium.org/issues/328859185#comment45 :
>  just got a response from Windows team. Unfortunately, the original fix was scheduled to release in September. However, there was a regression, so the fix was reverted. The new fix is under test and won't be released until several months.

**Comment by xty435768** [comment]
😭

**Comment by ValueXu** [comment]
> Update from https://issues.chromium.org/issues/328859185#comment45 :
> 
> > just got a response from Windows team. Unfortunately, the original fix was scheduled to release in September. However, there was a regression, so the fix was reverted. The new fix is under test and won't be released until several months.

No! I'm gonna use Linux.

**Comment by longfei8533** [comment]
This issue remains unresolved, affecting both Edge browser and VSCode, which become unresponsive for long periods after using remote connections. Below is a method that might help address this problem. 

**"I found a temporary solution for this bug: download a third-party input method, such as "Rime Input Method," and set it as the system default. This way, each time you connect via RDP, the input method will default to "Rime Input Method," which prevents the bug from occurring. You can then manually switch back to Microsoft Pinyin as needed."**  -- from https://issues.chromium.org/issues/328859185 po...@gmail.com

**Comment by MMMMMoris** [comment]
Today, Dec.12, not even an update.

**Comment by xty435768** [comment]
This solution works. I have changed the default input method to Weixin Input. This problem seems disappear.
![Image](https://github.com/user-attachments/assets/9ca9e1d7-9260-4c1d-894b-2877b3688824)

> This issue remains unresolved, affecting both Edge browser and VSCode, which become unresponsive for long periods after using remote connections. Below is a method that might help address this problem.
> 
> **"I found a temporary solution for this bug: download a third-party input method, such as "Rime Input Method," and set it as the system default. This way, each time you connect via RDP, the input method will default to "Rime Input Method," which prevents the bug from occurring. You can then manually switch back to Microsoft Pinyin as needed."** -- from https://issues.chromium.org/issues/328859185 [po...@gmail.com](mailto:po...@gmail.com)

**Comment by reitowo** [comment]
Not a solution for anyone prefer not installing third party IME.

Since VSCode is also a Microsoft product could you ask IME team for update?

**Comment by kanhao100** [comment]
> This solution works. I have changed the default input method to Weixin Input. This problem seems disappear. ![Image](https://github.com/user-attachments/assets/9ca9e1d7-9260-4c1d-894b-2877b3688824)
> 
> > This issue remains unresolved, affecting both Edge browser and VSCode, which become unresponsive for long periods after using remote connections. Below is a method that might help address this problem.
> > **"I found a temporary solution for this bug: download a third-party input method, such as "Rime Input Method," and set it as the system default. This way, each time you connect via RDP, the input method will default to "Rime Input Method," which prevents the bug from occurring. You can then manually switch back to Microsoft Pinyin as needed."** -- from https://issues.chromium.org/issues/328859185 [po...@gmail.com](mailto:po...@gmail.com)

Finally, I also adopted your method, can not wait for Microsoft

**Comment by djerryz** [comment]
My goodness, you have finally identified this persistent bug. It seems I am not alone in facing this issue. I have been struggling with this problem for nearly two years. Due to my work requirements, I need to use applications like VSCode and Eleterm, which are based on the Chrome engine. However, whenever I disconnect from the RDP session and reconnect later, I am forced to lose my previous work state. I have to forcibly close and restart these applications; otherwise, my mouse and keyboard remain unresponsive. I sincerely hope you can resolve this issue as soon as possible.

**Comment by cnrat** [comment]
> My goodness, you have finally identified this persistent bug. It seems I am not alone in facing this issue. I have been struggling with this problem for nearly two years. Due to my work requirements, I need to use applications like VSCode and Eleterm, which are based on the Chrome engine. However, whenever I disconnect from the RDP session and reconnect later, I am forced to lose my previous work state. I have to forcibly close and restart these applications; otherwise, my mouse and keyboard remain unresponsive. I sincerely hope you can resolve this issue as soon as possible.

I want to make it clear to all Chinese users that any third-party input method solution is, frankly, unnecessary. Yes, completely unnecessary. If you’re already using the default Microsoft Pinyin IME, just go into your input settings, enable “Use the previous version of Microsoft Pinyin input method” under compatibility, and you’re good to go. If you lose your input method after connecting via RDP, simply switch to English and then back to Chinese, and you won’t have any more issues with VS Code or any browser losing focus. It’s obviously a compatibility problem between Microsoft Pinyin and the new Windows input framework, and it should be fixed by Microsoft China’s IME development team—this is not a Windows bug. Given Microsoft China’s current state, however, I wouldn’t hold my breath waiting for a fix. This is what every Simplified Chinese user deserves, yet here we are saying goodbye to the world.

**Comment by jackyzy823** [comment]
> It’s obviously a compatibility problem between Microsoft Pinyin and the new Windows input framework, and it should be fixed by Microsoft China’s IME development team—this is not a Windows bug. Given Microsoft China’s current state, however, I wouldn’t hold my breath waiting for a fix. This is what every Simplified Chinese user deserves, yet here we are saying goodbye to the world.

This is not true. The problem occurs with Microsoft Japanese Input too. 

According to https://issues.chromium.org/issues/328859185#comment37 from Microsoft's developer: The root cause **is** in Windows TSF code. After entering this broken state, TSF drops any future IME inputs.

**Comment by reitowo** [comment]
In fact, firefox doesn't have this issue. So, maybe someone could see the difference between usage of TSF in these browsers.

**Comment by Molay** [comment]
Hello everyone.
Due to my work, I often connect to the Windows 11 virtual machine through Windows Remote Desktop on macOS and use VSCode in the Windows virtual machine to perform some development tasks.
When switching between the macOS local window and the Windows 11 remote window, VSCode often fails to respond to keyboard input and freezes, which drives me crazy.
Through searching, I found that you mentioned that there might be a problem with the Microsoft input method, so I turned on the "Compatibility" option in "Windows Settings/Time and Language/Language/Preferred Language/Options/Microsoft Pinyin/Options/General", and the problem was solved.

**Comment by lance5** [comment]
> Hello everyone.  大家好。 Due to my work, I often connect to the Windows 11 virtual machine through Windows Remote Desktop on macOS and use VSCode in the Windows virtual machine to perform some development tasks.由于我的工作，我经常通过MACOS上的Windows远程桌面连接到Windows 11虚拟机，并在Windows虚拟机中使用VSCODE执行一些开发任务。 When switching between the macOS local window and the Windows 11 remote window, VSCode often fails to respond to keyboard input and freezes, which drives me crazy.在MacOS本地窗口和Windows 11远程窗口之间切换时，Vscode通常无法响应键盘输入和冻结，这使我发疯。 Through searching, I found that you mentioned that there might be a problem with the Microsoft input method, so I turned on the "Compatibility" option in "Windows Settings/Time and Language/Language/Preferred Language/Options/Microsoft Pinyin/Options/General", and the problem was solved.通过搜索，我发现您提到了Microsoft输入方法可能存在问题，因此我打开了“ Windows设置/time and Lagans/landage/pecialred语言/options/microsoft pinyin/options/options/options/options/options”中的“兼容性”选项。一般”，问题得到了解决。

Wow, thank for your answer.it is working in my computer.have good nice every day for you.

**Comment by thexqn** [comment]
> 大家好。由于工作的原因，我经常在 macOS 上通过 Windows 远程桌面连接到 Windows 11 虚拟机，并使用 Windows 虚拟机中的 VSCode 来执行一些开发任务。在 macOS 本地窗口和 Windows 11 远程窗口之间切换时，VSCode 经常无法响应键盘输入并卡顿，这让我抓狂。通过搜索，发现你提到Microsoft输入法可能存在问题，于是我在“Windows设置/时间和语言/语言/首选语言/选项/Microsoft拼音/选项/通用”中打开了“兼容性”选项，问题就解决了。

匪夷所思的异常，但貌似能解决问题，不想安装多一个IME了。

**Comment by bpan2020** [comment]
![Image](https://github.com/user-attachments/assets/eb0c9a5d-3992-4525-a0e7-772474ac21e9)

**Comment by ellermister** [comment]
I don't know if it's the same thing.

I have installed multiple language input methods, **including Microsoft Pinyin, Microsoft Japanese, and American English.**

Every time the interface gets stuck and I can't input content, **I just need to change the current input method to American English to solve the problem.**

The keys that were originally unresponsive when pressed will be released one by one.

**Comment by villivateur** [comment]
This is a severe issue, but almost 3 years passed and Microsoft did nothing. Maybe most MS developers use English only and did not care about Asia languages IME?

**Comment by beck-8** [comment]
This is a severe issue, but almost 3 years passed and Microsoft did nothing.

**Comment by 2234839** [comment]
After several failures, I finally started searching and found this issue. Enabling input method compatibility indeed solves the problem of not being able to type in vscode: https://github.com/microsoft/vscode/issues/167556#issuecomment-2655646466 dddddddaaa, but it prevents me from switching between Chinese and English (the solution is to reopen compatibility...).

**Comment by beck-8** [comment]
Download Sogou Input Method and completely turn off the built-in input method for a perfect solution.

**Comment by 2234839** [comment]
> Download Sogou Input Method and completely turn off the built-in input method for a perfect solution.

I prefer to use Rime rather than these manufacturer's input methods, as they show no respect for user privacy

**Comment by beck-8** [comment]
> > Download Sogou Input Method and completely turn off the built-in input method for a perfect solution.
> 
> I prefer to use Rime rather than these manufacturer's input methods, as they show no respect for user privacy

Thank you for your suggestion. However, Sogou Input Method will bypass this BUG by itself. I am not sure whether this input method is a perfect solution.

**Comment by zhuzeyuan** [comment]
Thanks this is amazingly helpful! This issue has been bothering me for a long time and only saw your solution today.

After switching from Chinese Pinyin IME to English (if using keyboard shotcut, must do so outside VScode!), you can come back to VScode and it no longer freezes. (Once back to VScode, you may safely switch back to Pinyin IME if needed.)

**Comment by bpan2020** [comment]
> > Download Sogou Input Method and completely turn off the built-in input method for a perfect solution.
> 
> I prefer to use Rime rather than these manufacturer's input methods, as they show no respect for user privacy

Can Rime work around this issue?

**Comment by Gabboxl** [comment]
Any updates on this? I am experiencing this on Windows 10 and RDP even without any particular IME enabled.
