### ISSUE TITLE
VSCode Terminal History Being Set To Local Directory History After Update

### ISSUE THREAD

**Issue by conradwt** [microsoft/vscode#167703]
After a recent update of VSCode - Insiders, I'm getting local terminal history instead of global history when using Zsh.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  code-insiders 1.74.0-insider (Universal)
- OS Version: macOS 12.6

Steps to Reproduce:

1. open VSCode - Insiders
2. open the VSCode - Insiders integrated terminal using Zsh
3. type `history | wc -l`
4. open a regular macOS terminal
5. type `history | wc -l`

Expected:

I expected to see the global history within the VS Code - Insiders integrated terminal.

Actual:

The VS Code - Insiders integrated terminal is showing only local history.

The history within the VSCode - Insiders integrated terminal should display the same global history as it appears in the normal macOS terminal.

**Comment by meganrogge** [comment]
This is working for me in the `Run Recent Command` list. Where are you expecting to see it?

**Comment by conradwt** [comment]
@meganrogge After updating VSCode - Insiders on another machine, I'm seeing the exact same issue where the output of the Unix history command within the VSCode integrated terminal doesn't match that of the macOS.

**Comment by meganrogge** [comment]
I believe this was fixed yesterday with this change, can you try updating?

https://github.com/microsoft/vscode/pull/167618

Working for me:
![Screenshot 2022-11-30 at 3 39 16 PM](https://user-images.githubusercontent.com/29464607/204913751-ce6d2d43-78fd-463d-b1fa-e9cfa58bbe17.png)

**Comment by conradwt** [comment]
@meganrogge I'm still getting the following with VSCode - Insiders:

Intel Machine:

<img width="1133" alt="Screen Shot 2022-11-30 at 1 46 30 PM" src="https://user-images.githubusercontent.com/20219/204915225-d5f05472-8a2c-4bb7-b643-d5c9df6334ab.png">

Apple Silicon Machine:

![Screen Shot 2022-11-30 at 1 47 21 PM](https://user-images.githubusercontent.com/20219/204915328-7fe9cd0c-538b-4478-9bba-e4478651fdd8.png)

**Comment by meganrogge** [comment]
where are you setting `$HISTFILE`?

**Comment by conradwt** [comment]
@meganrogge I have never set HISTFILE.  Now, a recent version of VSCode - Insiders is magically setting it.

**Comment by tamayonauta** [comment]
Today VS Code stable has been updated in my machine and this behavior persists.
Does anyone know how to enable global history in VS Code's terminal?

Info:
>Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:43:37.594Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
Sandboxed: No

**Comment by Mohammed-Q96** [comment]
> Today VS Code stable has been updated in my machine and this behavior persists.
> Does anyone know how to enable global history in VS Code's terminal?

Same for me. 

macOS terminal 
<img width="472" alt="image" src="https://user-images.githubusercontent.com/32040888/206335512-5ff8f158-f9dd-4107-a5f4-3f7769703168.png">

but for vscode  terminal 
![image](https://user-images.githubusercontent.com/32040888/206336033-62da885f-5c71-4155-9528-a487922a7547.png)


I end up doing 
`export HISTFILE="/Users/mohammedqarmout/.zsh_history"` in my ..zshrc

**Comment by conradwt** [comment]
@Mohammed-Q96 I have done the same fix until things get sorted within VSCode.  I noticed when my OhMyZsh autocompletion stopped working because the VSCode embedded terminal was working with a different Unix command history.

**Comment by shikibu-z** [comment]
I'm having the same issue. VSCode version info:
```
Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:37:54.581Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
SandBoxed: No
```
Terminal.app appears:
![截屏2022-12-07 21 59 21](https://user-images.githubusercontent.com/74883013/206360528-05f0b9a2-17ee-4a3f-9374-16e8d004d70c.png)

VSCode gives:
![截屏2022-12-07 22 01 39](https://user-images.githubusercontent.com/74883013/206360814-1028dbe7-f67b-41cb-b0be-e157b2afe3d9.png)

The `.zshenv` and `.zprofile` seem to be used correctly by VSCode. I checked autocompletions and some environment variable and they appears to be fine.

**Comment by charlimmelman** [comment]
I'm also having this issue on Apple M1 Pro Ventura. Temporarily using suggestion by @moh-qarmout

**Comment by coolp123** [comment]
Encountered this issue after an update.

Disabling the feature in [this comment](https://github.com/cantino/mcfly/issues/273#issuecomment-1208848236) fixes this issue, but not sure if this is a good long term solution.

**Comment by conradwt** [comment]
@meganrogge How's this a duplicate when I posted my issue before #168396 ? Should #168396 be labeled as duplicate here?

**Comment by meganrogge** [comment]
I chose to close this one because have been using the other to track duplicates.
