### ISSUE TITLE
Error: No registered selector for ID: ms-vscode.npm-command

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#168154]
Running out of sources I see this:

```
[66219:1206/102201.181288:INFO:CONSOLE(216)] "%c  ERR color: #f33 No registered selector for ID: ms-vscode.npm-command: Error: No registered selector for ID: ms-vscode.npm-command
    at TerminalQuickFixService.registerQuickFixProvider (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/contrib/terminal/browser/terminalQuickFixService.js:26:23)
    at MainThreadTerminalService.$registerQuickFixProvider (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/api/browser/mainThreadTerminalService.js:205:75)
    at RPCProtocol._doInvokeHandler (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:381:27)
    at RPCProtocol._invokeHandler (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:366:45)
    at RPCProtocol._receiveRequest (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:307:32)
    at RPCProtocol._receiveOneMessage (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:234:26)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/workbench/services/extensions/common/rpcProtocol.js:115:52
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:514:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:688:38)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:653:37)
    at BufferedEmitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:480:35)
    at PersistentProtocol._receiveMessage (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:746:45)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:627:83
    at Listener.invoke (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:514:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:688:38)
    at Emitter.fire (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:653:37)
    at ProtocolReader.acceptChunk (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:271:37)
    at vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.net.js:238:61
    at Socket.listener (vscode-file://vscode-app/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/node/ipc.net.js:63:17)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by meganrogge** [comment]
This means that the package.json contribution isn't getting evaluated before `registerQuickFixProvider` is called. Not too familiar with how / when `context.subscriptions` is handled, but we call `registerTheCommandSelector` when the `TerminalQuickFixAddon` is created

https://github.com/microsoft/vscode/blob/accdf1078f412be9c241b4a9d2295be9da30576a/src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts#L100-L102

https://github.com/microsoft/vscode/pull/167664/files#diff-f28f2417ea8835864b8a62474362fa2d27e25935e258a035281dc7727023befbR74

**Comment by meganrogge** [comment]
I think perhaps moving that to the top of the constructor will fix this

**Comment by meganrogge** [comment]
This happens on window open and reload

**Comment by meganrogge** [comment]
and the quick fix does work for that extension

![Screenshot 2022-12-08 at 2 55 54 PM](https://user-images.githubusercontent.com/29464607/206565735-7c4d9f6b-47c3-4fa7-a866-c92547700fe3.png)

**Comment by chrmarti** [comment]
Seeing this in error telemetry for Insiders from 12/23:
```
Deminified Stack
Error: No registered selector for ID: ms-vscode.npm-command 

 [at R.registerQuickFixProvider in src/vs/workbench/contrib/terminal/browser/terminalQuickFixService.ts:39:10](https://vscode.dev/github/microsoft/vscode/blob/6ed4d436a9b6ae131732f4e2a723868231f4473a/src/vs/workbench/contrib/terminal/browser/terminalQuickFixService.ts#L39:10) 

 [at n.$registerQuickFixProvider in src/vs/workbench/api/browser/mainThreadTerminalService.ts:253:65](https://vscode.dev/github/microsoft/vscode/blob/6ed4d436a9b6ae131732f4e2a723868231f4473a/src/vs/workbench/api/browser/mainThreadTerminalService.ts#L253:65)
```

**Comment by Tyriar** [comment]
This is the 6th error by machines in telemetry https://vscode-errors.azurewebsites.net/card?ch=6ed4d436a9b6ae131732f4e2a723868231f4473a&bH=1f872bf9-0a2b-b425-9628-12c8d8abacad

**Comment by meganrogge** [comment]
I cannot reproduce this in Insider's. @chrmarti did you notice this after doing anything in particular?

**Comment by GongT** [comment]
I got this error when using remote dev container

<details>
<summary>Window</summary>

```
2023-01-09 11:57:22.807 [info] Electron sandbox mode is enabled!
2023-01-09 11:57:23.398 [info] Invoking resolveAuthority(ssh-remote)...
2023-01-09 11:57:23.398 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
2023-01-09 11:57:23.398 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
2023-01-09 11:57:24.413 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][1014ms] waiting...
2023-01-09 11:57:25.399 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][2001ms] waiting...
2023-01-09 11:57:25.938 [error] [Extension Host] (node:87236) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code - Insiders --trace-deprecation ...` to show where the warning was created)
2023-01-09 11:57:25.952 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][2553ms] returned 127.0.0.1:59747
2023-01-09 11:57:25.952 [info] resolveAuthority(ssh-remote) returned '127.0.0.1:59747' after 2555 ms
2023-01-09 11:57:25.953 [info] Creating a socket (renderer-Management-1b231e0e-c053-48c7-9a53-abc26698a52e)...
2023-01-09 11:57:25.953 [info] Creating a socket (renderer-ExtensionHost-e37f0e03-aba9-4425-b854-997785511294)...
2023-01-09 11:57:25.963 [info] Creating a socket (renderer-Management-1b231e0e-c053-48c7-9a53-abc26698a52e) was successful after 10 ms.
2023-01-09 11:57:25.973 [info] Creating a socket (renderer-ExtensionHost-e37f0e03-aba9-4425-b854-997785511294) was successful after 19 ms.
2023-01-09 11:57:26.717 [warning] No search provider registered for scheme: vscode-remote, waiting
2023-01-09 11:57:27.801 [info] [perf] Render performance baseline is 23ms
2023-01-09 11:57:28.141 [error] No registered selector for ID: ms-vscode.npm-command: Error: No registered selector for ID: ms-vscode.npm-command
    at R.registerQuickFixProvider (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1556:27715)
    at a.$registerQuickFixProvider (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1695:50928)
    at b.N (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1572:10803)
    at b.M (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1572:10521)
    at b.H (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1572:9614)
    at b.G (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1572:8595)
    at vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1572:7383
    at u.invoke (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at d.fire (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at a.fire (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:553:15228)
    at k.E (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:553:19294)
    at vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:553:17282
    at u.invoke (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at d.fire (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at h.acceptChunk (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:553:12959)
    at vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:553:12246
    at vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:642:18856
    at u.invoke (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at d.fire (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at E.i.onload (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:642:17123)
2023-01-09 11:57:31.514 [info] Electron sandbox mode is enabled!
2023-01-09 11:57:33.892 [info] Invoking resolveAuthority(dev-container)...
2023-01-09 11:57:33.892 [info] [LocalProcess0][resolveAuthority(dev-container,1)][0ms] obtaining proxy...
2023-01-09 11:57:33.892 [info] [LocalProcess0][resolveAuthority(dev-container,1)][1ms] invoking...
2023-01-09 11:57:34.914 [info] [LocalProcess0][resolveAuthority(dev-container,1)][1022ms] waiting...
2023-01-09 11:57:35.893 [info] [LocalProcess0][resolveAuthority(dev-container,1)][2001ms] waiting...
2023-01-09 11:57:36.892 [info] [LocalProcess0][resolveAuthority(dev-container,1)][3001ms] waiting...
2023-01-09 11:57:37.899 [info] [LocalProcess0][resolveAuthority(dev-container,1)][4008ms] waiting...
2023-01-09 11:57:38.894 [info] [LocalProcess0][resolveAuthority(dev-container,1)][5003ms] waiting...
2023-01-09 11:57:39.903 [info] [LocalProcess0][resolveAuthority(dev-container,1)][6011ms] waiting...
2023-01-09 11:57:40.894 [info] [LocalProcess0][resolveAuthority(dev-container,1)][7002ms] waiting...
2023-01-09 11:57:41.897 [info] [LocalProcess0][resolveAuthority(dev-container,1)][8005ms] waiting...
2023-01-09 11:57:42.904 [info] [LocalProcess0][resolveAuthority(dev-container,1)][9012ms] waiting...
2023-01-09 11:57:43.894 [info] [LocalProcess0][resolveAuthority(dev-container,1)][10003ms] waiting...
2023-01-09 11:57:44.892 [info] [LocalProcess0][resolveAuthority(dev-container,1)][11001ms] waiting...
2023-01-09 11:57:45.878 [error] [LocalProcess0][resolveAuthority(dev-container,1)][11986ms] returned an error {"code":"NotAvailable","detail":true}
2023-01-09 11:57:45.878 [error] resolveAuthority(dev-container) returned an error after 11986 ms {"name":"CodeExpectedError","_code":"NotAvailable","_detail":true,"isHandled":true}
2023-01-09 11:57:45.878 [error] Error received from starting extension host (kind: Remote)
2023-01-09 11:57:45.878 [error] CodeExpectedError
    at Yc.vc (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2641:5714)
    at async Yc.zc (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2641:6729)
    at async Yc.Yb (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2641:7890)
    at async Yc.wb (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2639:20330)
2023-01-09 11:57:45.878 [error] [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
2023-01-09 11:57:45.878 [error] CodeExpectedError
    at Yc.vc (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2641:5714)
    at async Yc.zc (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2641:6729)
    at async Yc.Yb (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2641:7890)
    at async Yc.wb (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2639:20330)
2023-01-09 11:57:45.879 [error] [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
```
</details>

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/pull/171191

**Comment by bpasero** [comment]
Actually still found it in my devtools today:

```
 ERR No registered selector for ID: ms-vscode.npm-command: Error: No registered selector for ID: ms-vscode.npm-command
    at R.registerQuickFixProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1557:27723)
    at o.$registerQuickFixProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1696:52924)
    at m.N (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1573:15226)
    at m.M (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1573:14944)
    at m.H (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1573:14037)
    at m.G (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1573:13018)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1573:11806
    at g.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:553:15190)
    at _.onmessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1671:1488)
```

**Comment by Tyriar** [comment]
I can't reproduce, but I can simulate the race by adding `await timeout(3000);` to `TerminalContributionService.ctor`

**Comment by Juanc179** [comment]
HI, im having the same problem here

2023-02-16 17:10:14.453 [error] Error: No registered selector for ID: ms-vscode.npm-command
    at R.registerQuickFixProvider (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1557:27745)
    at r.$registerQuickFixProvider (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1696:52931)
    at m.N (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1573:15220)
    at m.M (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1573:14938)
    at m.H (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1573:14031)
    at m.G (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1573:13012)
    at vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1573:11800
    at g.invoke (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:2029)
    at a.fire (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:86:1667)
    at r.fire (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:553:15219)
    at Z.onmessage (vscode-file://vscode-app/c:/Users/jcpis/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1671:1490)
    
    I got vs code 1.71.1 running on W11 21H2
    How i am supposed to fix this, or it's not a problem and vs code is working normally? Thank you!

**Comment by meganrogge** [comment]
Update your VS code version, where this is fixed @Juanc179

**Comment by Juanc179** [comment]
> Update your VS code version, where this is fixed @Juanc179

Sorry, i typed incorrectly mi vs code version. It is the latest one 1.75.1, i reinstalled it today.

**Comment by tjx666** [comment]
@meganrogge I can still reproduce in latest stabel 1.75.1


https://user-images.githubusercontent.com/41773861/220004145-23dd5543-2647-4bc9-996e-47d905169bd6.mov
