### ISSUE TITLE
zsh HISTFILE Hardcoded after #168396 fix

### ISSUE THREAD

**Issue by Redoubts** [microsoft/vscode#169264]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.74.1 (Universal)
- OS Version: Darwin x64 22.2.0 (ssh extension into debian 10.12)

The fix for #168396 permanently overwrites my $HISTFILE setting, so I can't redirect it to another file. If I set
```
    "terminal.integrated.env.linux": {
        "HISTFILE": "${HOME}/something_else",
    }
```
in VS Code user settings or `export HISTFILE="${HOME}/something_else"` in my .zshenv, I see 
```
% env | grep HIST
HISTFILE=/home/redoubts/.zsh_history
```

Steps to Reproduce:

1. try to set $HISTFILE anywhere normally
2. observe with `env | grep HIST`

**Comment by Tyriar** [comment]
As a temporary workaround you could set it in your `.zshrc`, checking TERM_PROGRAM == "vscode" if you want it only in VS Code.

I guess to fix this one we need to record any custom HISTFILE when we're constructing the `envMixin`:

https://github.com/microsoft/vscode/blob/be6992bf64edf0c690419986f774a30db926fa33/src/vs/platform/terminal/node/terminalEnvironment.ts#L198-L220

Then if we had a custom one, assign it here:

https://github.com/microsoft/vscode/blob/be6992bf64edf0c690419986f774a30db926fa33/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh#L21-L23

@meganrogge will save this one for you for some good testing, no rush as there's an easy workaround.

**Comment by BIKA-C** [comment]
Will this be fixed in January update?

**Comment by kwmlodozeniec** [comment]
I have this variable set in my .zenv file and it still gets overridden somehow, to overcome that I had to disable the shell integration setting
`"terminal.integrated.shellIntegration.enabled": false`

**Comment by t-fritsch** [comment]
thank you @Tyriar for the suggested workaround. It didn't work for me because I need different history file for every workspace :

```json
"terminal.integrated.env.osx": {
    "HISTFILE": "${workspaceFolder}/.zsh_history"
}
```

Anyway your suggestion helped me finding a temporary workaround (still hoping this bug gets fixed some day 😅) that I write here in case anyone is looking for something similar : 

1. in `.vscode/settings.json`, create a custom env var :
    ```json
    "terminal.integrated.env.osx": {
        "VSCODE_HISTFILE": "${workspaceFolder}/.zsh_history",
    },
    ```
 2. in `~/.zshrc`, check if it exists and overwrite HISTFILE : 
    ```bash
    # fix vscode custom histfile
    # cf. https://github.com/microsoft/vscode/issues/169264
    if [[ -v VSCODE_HISTFILE ]]; then
        export HISTFILE=$VSCODE_HISTFILE
    fi
    ```
