### ISSUE TITLE
Multiline string logging with variablesReference

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#17333]
Using OutputEvent with a variablesReference, multiline logs aren't supported anymore. 

![image](https://cloud.githubusercontent.com/assets/323878/21236756/283fee98-c2b1-11e6-8550-ffccfb56c181.png)

Especially a problem when I need to print a stack from an exception or console.trace()
![image](https://cloud.githubusercontent.com/assets/323878/21236794/46e245ee-c2b1-11e6-848a-b26f0fae399d.png)

Maybe not straightforward to fix since variables are always 1-line everywhere else?

**Comment by roblourens** [comment]
I think those \n are going into the console height calculation though -

![image](https://cloud.githubusercontent.com/assets/323878/21248572/bdc18f9a-c2ec-11e6-94ca-f45a8c0266a1.png)

![image](https://cloud.githubusercontent.com/assets/323878/21248581/ca6b3138-c2ec-11e6-9f0e-af99ea05657d.png)

**Comment by isidorn** [comment]
I think we fixed this last minute prior to 1.8 release. Anywasy works for me now
We might fix how we hande new line and output events so we should still keep this in mind as a good test case

![screen shot 2016-12-29 at 14 54 46](https://cloud.githubusercontent.com/assets/1926584/21545294/c917f7cc-cdd6-11e6-87b5-2f9940b9b250.png)

**Comment by roblourens** [comment]
In my original example I was using variableReference, but if you try that now, it won't be because I changed it to not use variableReference when logging only text. I still see this if I include an object like in my second comment:

>I think those \n are going into the console height calculation though -
>
>![image](https://cloud.githubusercontent.com/assets/323878/21248572/bdc18f9a-c2ec-11e6-94ca-f45a8c0266a1.png)
>
>![image](https://cloud.githubusercontent.com/assets/323878/21248581/ca6b3138-c2ec-11e6-9f0e-af99ea05657d.png)

**Comment by isidorn** [comment]
Works for me.
My steps:
1. insiders, mac, node2 debug session stopped
2. in repl: `console.log('a\nb', {a : 1})`

![screen shot 2017-01-04 at 21 23 42](https://cloud.githubusercontent.com/assets/1926584/21657776/2170da00-d2c4-11e6-888d-73a79bbada96.png)


Please try with latest or give me your exact steps

**Comment by roblourens** [comment]
It does work now, maybe it was fixed by the fix for #17404. Thanks
