### ISSUE TITLE
Node process in the terminal not killed after closing VsCode

### ISSUE THREAD

**Issue by kunaaal13** [microsoft/vscode#177044]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.1 (Universal)
- OS Version: Darwin arm64 22.3.0

Steps to Reproduce:

1. Run a node process like npm run dev.
2. Close the vs code
3. Reopen vs code and when you run npm run dev again you'll get the error port already in use.

I was using the latest vs code insiders and started facing this issue then I completely uninstalled that, installed a stable version but still this issue is not resolved.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by kunaaal13** [comment]
Tried this in insiders as well, but still getting the same issue
These are details of insider build I installed

Version: 1.77.0-insider (Universal)
Commit: bbe8e872dc7c8899eb80bc4b650a6f090f4bc952
Date: 2023-03-14T05:23:55.404Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

**Comment by kunaaal13** [comment]
Is there any way to fix this?

**Comment by sebastienbarre** [comment]
I thought maybe Vite.js was to blame, because that's what I run in development mode from VSCode, but I haven't updated Vite in a while. Meanwhile, it also happens when I run Storybook from VSCode nowadays, it no longer frees the port either, so essentially I go from `npx kill-port 8080` to `npx kill-port 6006`, etc. Thanks.

**Comment by meganrogge** [comment]
@eleanorjboyd @roblourens maybe related to the node.js issues you've been working on

**Comment by eleanorjboyd** [comment]
I have been hitting something which I think is similar while testing a fix for a different remote-ssh issue. The remote-ssh issue I am working on has been ongoing for a bit due to a previous electron update. I will stay up to date with this thread to confirm if it is or not. Thanks!

**Comment by JannesMeyer** [comment]
Same here (also on macOS). This started happening for me after the update to 1.76. I downgraded to 1.75 and everything works fine there.

I usually had a few `node` and `zsh` processes hanging around after closing VS Code. Of course, this multiplies if I open/close VS Code a few times.

It was impossible to work with, so I had to downgrade and disable updates for now.

**Comment by JannesMeyer** [comment]
> Is there any way to fix this?

@kunaaal13 go to https://code.visualstudio.com/updates/v1_75 and download that version (download links are at the top of the page).

**Comment by sebastienbarre** [comment]
Thanks for pin-pointing the version @JannesMeyer! 
I downgraded my 1.76 back to 1.75, and this is indeed fixing this pesky issue. This is great. 

Not sure if this helps, but since this is "process" related, I noticed 1.76 has process-related changes: [Visual Studio Code February 2023 -- More Electron UtilityProcess adoption](https://code.visualstudio.com/updates/v1_76#_more-electron-utilityprocess-adoption)

**Comment by tamuratak** [comment]
@meganrogge 

> I don't see any suspicious February PRs that could be related to this.

Might be #174020?

**Comment by sebastienbarre** [comment]
@tamuratak @meganrogge @bpasero  I'm not entirely familiar with VSCode source, but it seems to me that an `await` is missing ([here](https://github.com/microsoft/vscode/pull/174020/files#diff-5a9d81520637085ca4bbcfd7f15110f53dfbf3908cfb06029bd2cfd40bdef0e2R138))...

**Comment by bpasero** [comment]
It is not missing:

https://github.com/microsoft/vscode/blob/fa13bf16fd237afef07f4df0648da026f43e3963/src/vs/platform/lifecycle/node/sharedProcessLifecycleService.ts#L35

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/174956
