### ISSUE TITLE
Always crash prompt: OOM

### ISSUE THREAD

**Issue by wangzongming** [microsoft/vscode#177433]
Type: <b>Bug</b>

The latest version of vscode crashes several times an hour, making me miserable. I'd really appreciate it if you could help me with this.

![image](https://user-images.githubusercontent.com/27466569/225830853-9cb20eb3-fff9-47b3-bc7b-33557fd91d9e.png)

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.86GB free)|
|Process Argv|D:\\work\\wei_ding\\ecs-web\\web-one --crash-reporter-id 0ab26b63-bae8-4fc5-8cce-b380c7f5f0bb|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
jsx-html-tags|ang|1.0.1
toml|be5|0.6.0
better-toml|bun|0.3.2
vscode-drawio|eig|1.0.3
prettier-vscode|esb|9.10.4
haskell-nsis|idl|1.1.0
nsis|idl|3.52.0
polacode-2019|jef|0.6.1
svg|joc|1.5.1
vue-format-markdoyle|mar|0.1.9
code-beautifier|mic|2.3.3
vscode-language-pack-zh-hans|MS-|1.76.2023030809
cpptools|ms-|1.14.4
vetur|oct|0.37.3
vscode-xml|red|0.24.0
vue-vscode-snippets|sdr|3.1.1
gcode|vsc|0.2.1
vscode-icons-mac|way|7.25.3
vscode-import-cost|wix|3.3.0
qnn|xm|1.6.6
vuter|yoy|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30681850
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
vsctsb:30677850
pythonb192cf:30669361
azdwalk:30687957
pythonms35cf:30686773

```

</details>

**Comment by wangzongming** [comment]
I noticed that this error seems to occur when the window is maximized.

**Comment by F-19-F** [comment]
me too

**Comment by wangzongming** [comment]
This problem is recurring more and more frequently. I hope you can solve this problem soon. Thank you.

**Comment by deepak1556** [comment]
Can you check if the issue repros with our insiders build https://code.visualstudio.com/insiders/

**Comment by wangzongming** [comment]
> Can you check if the issue repros with our insiders build https://code.visualstudio.com/insiders/

Using the insiders version does not crash.

**Comment by deepak1556** [comment]
Closing per https://github.com/microsoft/vscode/issues/177433#issuecomment-1502926572, should be addressed in `1.78` as well.

**Comment by wangzongming** [comment]
The problem persisted after I reinstalled Visual Studio Code.

![image](https://github.com/microsoft/vscode/assets/27466569/23db86b4-3807-4bb3-8a1f-7bbcb7732779)
![image](https://github.com/microsoft/vscode/assets/27466569/ba2b73a7-16e7-4550-ae39-3c68e38366f2)

**Comment by deepak1556** [comment]
Interesting, I wonder if an extension is triggering the crash. Can you check if the crash is triggered when extensions are disabled ? (F1 > Developer: Reload With Extensions Disabled or code --disable-extensions)

**Comment by wangzongming** [comment]
I watched for a few more days,
The current version of vs code is fine.
I think it's my computer Memory is a little low. 
And I have several vs Code open at the same time.
Recently I removed all the plugins.
Much better. Two days and one crash.
When the computer's memory is full, the vs code being edited will crash
thank you.

> Interesting, I wonder if an extension is triggering the crash. Can you check if the crash is triggered when extensions are disabled ? (F1 > Developer: Reload With Extensions Disabled or code --disable-extensions)
