### ISSUE TITLE
As of 1.77 (and 1.77.1) The js debugger won't step into async functions

### ISSUE THREAD

**Issue by markw65** [microsoft/vscode#179613]
Type: <b>Bug</b>

Given this program:

```
async function foo() {
  console.log("I am foo");
}

async function bar() {
  await foo();
}

bar().then(() => console.log("Done"));
```
Set a breakpoint on `await foo();` then run from the JS Debug Terminal. After hitting the breakpoint, step into. With 1.76 and earlier, it steps into foo. With 1.77 and 1.77.1 it stops in a function called `promiseInitHookWithDestroyTracking` in `Unknown Source`. Further stepping wanders around through a stack of similar functions, but doesn't actually get to foo (or at least, takes a very long time to do so). [Edit: I'm just not very patient. Using `step over` it does eventually reach `foo` - but its still very inconvenient]

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:23:33.779Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id e8eaf96d-f4d4-4874-a9d9-08e2c6d99409|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
gltf-vscode|ces|2.3.16
vscode-eslint|dba|2.4.0
githistory|don|0.6.20
gitlens|eam|13.5.0
prettier-vscode|esb|9.10.4
php-intellisense|fel|2.3.14
monkey-c|Gar|1.0.8
jq-syntax-highlighting|jq-|0.0.2
prettier-extension-monkeyc|mar|2.0.60
cpptools|ms-|1.14.5
peggy-language|Peg|2.4.0
java|red|1.16.0
vscode-xml|red|0.24.0
shader|sle|1.1.5
rewrap|stk|1.16.3
intellicode-api-usage-examples|Vis|0.2.7
vscodeintellicode|Vis|1.2.30
vscode-java-debug|vsc|0.49.1
vscode-java-pack|vsc|0.25.10
vscode-java-test|vsc|0.38.2
vscode-maven|vsc|0.41.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30705552
functionswalk:30687959
pythonms35:30701012

```

</details>

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1643. Fixed in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) already.

**Comment by markw65** [comment]
@connor4312 I've installed the nightly build of VSCode:

```
Version: 1.78.0-insider (Universal)
Commit: 761de52b5e297a8ea461dd501c897cc74c407733
Date: 2023-04-11T05:26:19.957Z
Electron: 22.4.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes
```

which appears to already have the nightly version of the debugger extension installed (v2023.4.517), and the bug still repros.

I also tried 1.77.1 with the nightly debugger extension, and again, the bug still repros.

As an aside, I don't see how this is related to the supposed duplicate (although I realize that sometimes the root cause may be seemingly unrelated to the symptoms).

In any case, this does not appear to be fixed, but apparently only you can re-open it? Or should I submit a new issue?

**Comment by markw65** [comment]
I just did a bisect on the nightly debugger version, and 2023.3.217 and earlier are good, and 2023.3.317 and later are bad.

**Comment by connor4312** [comment]
Please grab a trace log if you can:

**Comment by markw65** [comment]
FYI that [2bf3f18024](https://github.com/microsoft/vscode-js-debug/commit/2bf3f18024b142c485722530171502bef81d6571) is the commit that broke it.

**Comment by markw65** [comment]
Sorry, one more data point.

I've been doing all my testing from the javascript debug terminal, but if I instead create a (completely default) launch config, then [483425e50](https://github.com/microsoft/vscode-js-debug/commit/483425e50cf0fb313610d2346b51459c8db556e2) really does fix it.

ie if I create a brand new project, and stick the original test case in it, and run it from the debug console, it fails. If I then create a vanilla launch config
```
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/bug.js"
        }
```
and run it from that, then it works with v2023.4.517 (but fails from v2023.3.317 to v2023.4.317 inclusive).

I've tried setting 
```
  "debug.javascript.terminalOptions": {
    "skipFiles": [
      "<node_internals>/**"
    ]
  }
```
but it still fails from the javascript debug terminal (and that wasn't needed before v2023.4.317 anyway).

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/235016325-73881508-d78b-43dd-b782-9a5ab0cc0c5c.png)

seems to be working with no launch config in my folder.
