### ISSUE TITLE
the vscode will crash when delete a file form vscode explorer

### ISSUE THREAD

**Issue by shidaping** [microsoft/vscode#180388]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.77.3
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. open a folder and create a file
2. delete the file

the vscode will crash when delete a file form vscode explorer.
cmake plugin enabled

**Comment by lramos15** [comment]
Please follow https://github.com/microsoft/vscode/wiki/Native-Crash-Issues and attach the crash drumps

**Comment by shidaping** [comment]
[reports.zip](https://github.com/microsoft/vscode/files/11291479/reports.zip)
here is the .dmp files

**Comment by rzhao271** [comment]
I symbolicated the crash dumps.
I don't see anything about deleting a file, but I do see some things about the utility process. One of the crashes (symbolicated-2e.log) seems to do with Windows instead.

[symbolicated.zip](https://github.com/microsoft/vscode/files/11299088/symbolicated.zip)

**Comment by shidaping** [comment]
i am using the cmake plugin. does the plugin occupy the files?

**Comment by deepak1556** [comment]
Crash with the utility process is unrelated and is addressed in our latest insiders https://code.visualstudio.com/insiders

The main process crashed when performing file delete operation with OOM kill from the Kernel. @shidaping if you can provide a minimal repo with the plugin that caused the issue, it would help us debug the issue further.

**Comment by shidaping** [comment]
![动画](https://user-images.githubusercontent.com/5226384/234262248-a5efedb5-78b6-4854-b300-44167e4c8372.gif)
disable all extension, vscode still crash

**Comment by deepak1556** [comment]
Can you check if the issue repros with our latest insiders version https://code.visualstudio.com/insiders ?

**Comment by shidaping** [comment]
![动画](https://user-images.githubusercontent.com/5226384/234441047-2e9582f7-1569-4983-b7d2-7b1cd4249113.gif)
the insider version
