### ISSUE TITLE
GitHub - double prompt when not signed in

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#181135]
* Sign out of your GitHub account
* Enable the `github.branchProtection` setting
* Open a GitHub repository and you will see a prompt to sign in to your GitHub account
* Click the "Cancel" button, just to see another prompt to sign in to your GitHub account

**Comment by lszomoru** [comment]
This has been fixed in Insiders and depending on the feedback we might port the fix to the release branch.

**Comment by lszomoru** [comment]
Since I did not hear any complains about this, I will go ahead close the bug. 
In the next Stable release we switched to using the badge to inform the user to sign in.

**Comment by andreamah** [comment]
I'm still seeing this after opening a remote repository:
![Recording 2023-05-31 at 10 53 49](https://github.com/microsoft/vscode/assets/31675041/6b0366d5-fb1d-4a45-ba20-35f3bebd080e)

Did the repro steps mean to open a local git repository? or a remote github repository?

**Comment by lszomoru** [comment]
@andreamah, this prompt is coming from the "GitHub Repositories" extension and not the "GitHub" extension. to verify this issue you have to open a GitHub repository using VS Code desktop and not using the GitHub Repositories extension. I have also changed the code that no more dialog is shown. Instead a badge indicating that the user has to sign in on the "Account" item is shown:

<img width="394" alt="image" src="https://github.com/microsoft/vscode/assets/3372902/72cb4b77-fb06-4490-a560-88b378fc6cac">

**Comment by lszomoru** [comment]
Verification steps:
* Sign out of your GitHub account
* Enable the `github.branchProtection` setting
* Open a GitHub repository (ex: microsoft/vscode) and you will see a badge on the Account menu item

**Comment by sandy081** [comment]
I assume this is forgotten to be closed. Hence closing it. Please reopen it if not.
