### ISSUE TITLE
New commoand under Tasks to create a new task

### ISSUE THREAD

**Issue by Teamop** [microsoft/vscode#181808]
Type: <b>Feature Request</b>

Currently, when trying to create a new task, the step is 
> Run 'Configure Tasks' from the global Terminal menu and select the 'Create tasks.json file from template' entry. 

here when run `Configure Tasks`, the current process will load all the current tasks before showing anything, so if there's a very big project with lots of tasks by default, somehow the loading all the current tasks takes a long time, then for creating a new task, it's not possible from the UI.

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.19.0-40-generic
Remote OS version: Linux x64 5.19.0-40-generic

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by Teamop** [comment]
@meganrogge thanks, in the 1.79.0-insider, for the entry point ( `Configure Tasks` -> `Create tasks.json file from template`), it's still the same, but at least the loading UI is not very long and not just stuck there for my case, works for me right now.
