### ISSUE TITLE
Replace history doesn't work

### ISSUE THREAD

**Issue by BillDenton** [Microsoft/vscode#18233]
- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|read-only-indicator|alefragnani|0.4.0|
|alignment|annsk|0.3.0|
|bettertab|arenl|1.0.1|
|Doxygen|bbenoist|1.0.0|
|python|donjayamanne|0.5.5|
|EditorConfig|EditorConfig|0.3.4|
|vscode-great-icons|emmanuelbeziat|1.1.36|
|matlab|Gimly81|0.4.0|
|status-bar-tasks|GuardRex|0.1.2|
|vscode-dimmer|hoovercj|2.1.0|
|docthis|joelday|0.3.6|
|cpptools|ms-vscode|0.9.3|
|vscode-clearcase|OpenNingia|1.4.1|
|vscode-icons|robertohuertasm|4.3.0|
|theme-cyanicpastels|SamuelLampa|0.0.9|
|indenticator|SirTori|0.2.1|
|vscode-hexdump|slevesque|1.1.4|
|code-spell-checker|streetsidesoftware|0.13.3|
|comment-snippets|Tobiah|0.2.0|
|dark-plus-material|vangware|0.1.4|
|change-case|wmaurer|1.0.0|
|highlight-trailing-white-spaces|ybaumes|0.0.2|

---

Steps to Reproduce:

1. Press Ctrl-F or Ctrl-Shift-F.
2. Expand using the right angle triangle the replace entry box.
3. Click on replace entry box so it can be edited.
3. Press Alt-Up. It does line transpose in the current window. Expect it to show previously entered replace value. Works as expected in the search entry box.

**Comment by BillDenton** [comment]
Similar problem in the file search (Ctrl+Shift+F) in "files to include" and "files to exclude"

**Comment by roblourens** [comment]
This should be fixed in Insider's/1.9. Not sure if there was another bug for it.

**Comment by BillDenton** [comment]
Still broken in 1.9.0-insider Date 2017-01-24T08:23:13.694Z, which appears to be the latest as I can't update from that.

**Comment by BillDenton** [comment]
Checked with:
Visual Studio Code - Insiders
Version 1.9.0-insider
Commit 2c96d880e50f7996932a9b5c9b8f74c43c5b3f2f
Date 2017-01-27T07:11:59.838Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
Not working

**Comment by sandy081** [comment]
@roblourens I do not think history navigation for Replace is implemented. Not sure if you meant same?

**Comment by roblourens** [comment]
Sorry I misread the issue. And it only leaks through to do the line transpose on Windows for me.

**Comment by BillDenton** [comment]
Is it a Windows specific problem and OK on Linux & Mac?

**Comment by roblourens** [comment]
Replace history doesn't work on Mac either. It just moves the cursor when you use alt+up/down

**Comment by eamodio** [comment]
While I would love to see the history for the replace box work, the leaking of the alt+up/down to the editor in that box imo is much worse. Maybe that part should be higher priority?

I've even tried to "fix" the commands myself with little luck. Here's what I've tried.
```json
    {
        "key": "alt+up",
        "command": "editor.action.moveLinesUpAction",
        "when": "editorTextFocus && !editorReadonly && !findWidgetVisible && !findInputFocussed && !replaceInputBoxFocus && !inputFocus"
    },
    {
        "key": "alt+down",
        "command": "editor.action.moveLinesDownAction",
        "when": "editorTextFocus && !editorReadonly && !findWidgetVisible && !findInputFocussed && !replaceInputBoxFocus && !inputFocus"
    }
```

**Comment by sandy081** [comment]
@eamodio May I know why do you need to fix the commands? Are they hijacking any of the existing commands?

**Comment by eamodio** [comment]
If you press `alt+up` or `alt+down` inside the replace box (of the find widget), it triggers the `editor.action.moveLinesUpAction` or `editor.action.moveLinesDownAction` commands in the editor.

**Comment by sandy081** [comment]
Ah I see.. I think they should be triggered only when editor text is in focus. I think this is a separate issue.

**Comment by sandy081** [comment]
Verify that replace history works for Replace box in Search view.

**Comment by sandy081** [comment]
@BillDenton Please try it out in our insiders version

**Comment by aeschli** [comment]
On Linux: Works for the replace field in the search viewlet, but not for the find/replace dialog in the editor. @sandy081 Is this as designed?

**Comment by sandy081** [comment]
@aeschli Yeah.. it was only implemented by Replace box in Search view. For find widget a follow up issue was created - #50583

**Comment by aeschli** [comment]
ok, then I mark it a verified.
