### ISSUE TITLE
When a Markdown file contains a YAML block in a bullet point, comments do not have the right syntax highlighting

### ISSUE THREAD

**Issue by mtkennerly** [microsoft/vscode#182458]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78.2
- OS Version: Windows 11

Steps to Reproduce:

1. Create a Markdown file with this content:

<pre>
# Baseline
```yaml
# foo
```

# Indented
  ```yaml
  # foo
  ```

# Bullet point
* ```yaml
  # foo
  ```
</pre>

2. Notice that the comment in the bullet point is not highlighted like the others:

   > <img width="94" alt="image" src="https://github.com/microsoft/vscode/assets/4934192/07617447-27f0-40a6-9a90-daf59153988d">

**Comment by mjbvz** [comment]
@alexr00 I believe the root cause is that the yaml grammar uses `^` for most of it's rules. To handle cases where it is embedded, we should use `(^|\G)` instead

**Comment by alexr00** [comment]
This is fixed by the new yaml grammar!

**Comment by eleanorjboyd** [comment]
Does this require a certain extension to see? I tried it in a simple markdown file and got the bug still:

<img width="242" alt="Image" src="https://github.com/user-attachments/assets/d8e5d40e-6f02-4fa8-a6ea-d6eae40340da" />

**Comment by dbaeumer** [comment]
I guess that should have been fixed.

**Comment by RedCMD** [comment]
@dbaeumer 
Does this issue occur when all extensions are disabled?: Yes/No

please test at https://insiders.vscode.dev/

**Comment by alexr00** [comment]
This still looks fixed. Please disable all extensions to verify.

**Comment by lszomoru** [comment]
Verified using an empty profile.
