### ISSUE TITLE
'Go to project configuration' doesn't work on web

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#183685]
1. Open https://insiders.vscode.dev/github/microsoft/vscode-markdown-languageservice 
2. Go to a ts file
3. Try to run `go to project configuration` or click on the `open tsconfig` option in the language status

**bug**
Nothing happens

Version: 1.79.0-insider
Commit: 2dfb838f494f035099e999f0cd0eff5f1f488a30
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15
Embedder: vscode.dev

**Comment by Tyriar** [comment]
When I run the command (file under src/util) I always get this notification:

![image](https://github.com/microsoft/vscode/assets/2193314/b4c97e42-a6aa-4c92-82ab-6ce52a951253)

No tsconfig here:

![image](https://github.com/microsoft/vscode/assets/2193314/b212b05b-0191-45f9-b4bd-a356001f0622)

**Comment by mjbvz** [comment]
What file were you in?

<img width="845" alt="Screenshot 2023-06-01 at 9 48 03 AM" src="https://github.com/microsoft/vscode/assets/12821956/63970deb-c81a-4025-81de-3006be7cc5ce">

**Comment by Tyriar** [comment]
Above was `src/util/schemes.ts` and `src/logging.ts`.

src/languageFeatures/definitions.ts:

![image](https://github.com/microsoft/vscode/assets/2193314/9b80f995-deea-46bd-9e98-9931922270a5)

**Comment by mjbvz** [comment]
I can't repo in safari or chrome. Do other project wide Intellisense features work for you? Try running `find all references` to check

**Comment by mjbvz** [comment]
@Tyriar Can you please test this again. It possible you were running into the issue fixed by 3a02b99fe85d27851523c56f287ddf5542d9f6b2 that would caused the repo archive not to download

**Comment by Tyriar** [comment]
Still happens, both during and after init TS status bar item is there:

![image](https://github.com/microsoft/vscode/assets/2193314/e0ffc8c5-f70a-439c-bc54-824bbc253f64)
![image](https://github.com/microsoft/vscode/assets/2193314/b9babadc-d7e5-4e49-8177-18a1e35c7be5)

Microsoft Edge
Version 116.0.1938.10 (Official build) dev (64-bit)

**Comment by mjbvz** [comment]
@Tyriar Weird, this always works for me across Safari, Chrome, and Edge. Init is also almost instant

Can you try sharing the output log from `TypeScript`. At the top it should say:

```
2023-07-11 11:09:27.033 [info] Successfully loaded workspace content for repository vscode-vfs://github/microsoft/vscode-markdown-languageservice
```

**Comment by Tyriar** [comment]
@mjbvz 

```
2023-07-11 11:22:12.770 [info] Successfully loaded workspace content for repository vscode-vfs://github/microsoft/vscode-markdown-languageservice
2023-07-11 11:22:12.770 [info] Starting TS Server undefined
2023-07-11 11:22:12.770 [info] Using tsserver from: https://main.vscode-cdn.net/insider/f8782370c90ec98467dc3590bcfa2eeb1f218107/extensions/typescript-language-features/dist/browser/typescript/tsserver.web.js undefined
2023-07-11 11:22:12.770 [info] <syntax> Forking...
2023-07-11 11:22:12.770 [info] <syntax> Starting...
2023-07-11 11:22:12.770 [info] <semantic> Forking...
2023-07-11 11:22:12.770 [info] <semantic> Starting...
```

**Comment by Tyriar** [comment]
Tried to get trace logs but ran into https://github.com/microsoft/vscode/issues/187622

**Comment by mjbvz** [comment]
@Tyriar After changing the log level, can you try running `Restart TS Server` with a ts file open. That should restart the server and generate new logs

**Comment by Tyriar** [comment]
@mjbvz it's working now 🤷

**Comment by mjbvz** [comment]
Ok thanks for testing all these times. If you see it not working again, please try collecting the full logs. I suspect it's more than just `go to project configuration` that's broken in those cases
