### ISSUE TITLE
'WSL Targets' shown in Remote Explorer and 'Connect to WSL' shown in Remote Indicate quick pick

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode#183813]
Testing #183732

> test that the remote indicator menu does not contain WSL commands
> test that the remote explorer does not contain a WSL Targets tab

these test instructions don't hold, see: 

<img width="1507" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/b41343d9-6064-47f1-ac38-1e42ea848d6a">

<img width="431" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/42be8d37-4f7f-4eb6-9b71-06ce2be228f6">

# Version 

```
Version: 1.79.0-insider
Commit: 784e72bc4486b7ea5ad3447c506e31d949848592
Date: 2023-05-30T05:17:05.562Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
```

**Comment by joyceerhl** [comment]
I ran into this with the latest WSL and pre-release of Remote-Tunnels while trying to verify https://github.com/microsoft/vscode/issues/184472, reopening for June

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-remote-wsl/pull/141

**Comment by alexr00** [comment]
Closing as this is fixed per https://github.com/microsoft/vscode/issues/183813#issuecomment-1581245423

**Comment by ulugbekna** [comment]
I can still reproduce? 

<img width="636" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/868733af-b290-41be-931e-c04da804208f">

<img width="498" alt="image" src="https://github.com/microsoft/vscode/assets/16353531/dc3d41ae-6e76-407c-9283-2992d524e8fa">

**Comment by connor4312** [comment]
@ulugbekna I'm not able to do so, even after ensuring WSL is activated. Can you please do two things:

- Confirm the version of the WSL extension you have on vscode.dev
- Run `WSL: Show Log` and share the contents
