### ISSUE TITLE
[less] Syntax checking error for mixins

### ISSUE THREAD

**Issue by adamal** [Microsoft/vscode#18512]
VSCode Version: 1.8.1
OS Version: OS X 10.11.6

The following valid less is incorrectly marked with red squiggles:

    .media-switch(@styles) {
        @media(orientation:landscape){
            @styles();
        }
    }

A similar issue happens when passing a detached ruleset to the mixin:

    .media-switch({
        flex-direction: row;
    });

See also [issue 131](https://github.com/Microsoft/vscode/issues/131).

![screen shot 2017-01-12 at 14 37 45](https://cloud.githubusercontent.com/assets/3245228/21891816/bfd0134e-d8d4-11e6-84f3-2eccb2752d50.png)

<img width="202" alt="screen shot 2017-01-13 at 13 00 35" src="https://cloud.githubusercontent.com/assets/3245228/21929349/5628c244-d990-11e6-9c06-f8c56c79af0d.png">

**Comment by aeschli** [comment]
Fixed by Microsoft/vscode-css-languageservice@f1d6e334992656997d68d270f62b4b2dea115990

**Comment by sandy081** [comment]
Looks like this is not yet part of the build

**Comment by geirsagberg** [comment]
This is still an issue when passing a detached ruleset as second parameter:
![image](https://user-images.githubusercontent.com/594564/28925864-65ec94e2-7866-11e7-9e89-a156fe66a6f5.png)

@aeschli could you re-open this, or should I file a new issue?

**Comment by aeschli** [comment]
@geirsagberg Please file a new issue!
