### ISSUE TITLE
SCM fails to show changes

### ISSUE THREAD

**Issue by Eli-Goldberg** [Microsoft/vscode#18737]
- VSCode Version: code-insiders_1.9.0-1484723809
Commit 39d761bf1f4ce7ea605539bdba41a8727b3c7ce0
Date 2017-01-18T07:21:35.814Z
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. just make a change in a git controlled folder
2. got to scm (ctrl+shift+g) and try to see the changes

![image](https://cloud.githubusercontent.com/assets/19211868/22066671/ae053038-dd96-11e6-912c-c68a0d5898bb.png)

**Comment by Eli-Goldberg** [comment]
Fixed in latest insiders version:
Version 1.9.0-insider
Commit 215a0af33046d3940e665d46ecaeac9623f2f769
Date 2017-01-19T07:02:49.312Z

**Comment by Nevor** [comment]
Hello,

I have the last insiders version mentioned above but I still have this error coming up when trying to view changes. So this bug might not have been fixed yet.

* VSCode Version: 
  Version 1.9.0-insider
  Commit 215a0af33046d3940e665d46ecaeac9623f2f769
  Date 2017-01-19T07:12:16.209Z
  Shell 1.4.6
  Renderer 53.0.2785.143
  Node 6.5.0

* OS Version: 
  Windows 10 1607 (build 14393.187)
