### ISSUE TITLE
June 1.80.0 update broke Extension on M2 Pro chip

### ISSUE THREAD

**Issue by joeldbirch** [microsoft/vscode#187332]
Type: <b>Bug</b>

## Current Behavior

With an M2 Pro chip, immediately after updating VS Code to v1.18.0, the NX Console extension broke. Clicking the "play" icon button in the NX Console extension next to project target/task shows this error:

```
 >  NX   Missing Platform Dependency

   The Nx CLI could not find or load the native binary for your supported platform (darwin-x64).
   This likely means that optional dependencies were not installed correctly, or your system is missing some system dependencies.
   For more information please see https://nx.dev/recipes/ci/troubleshoot-nx-install-issues
```
It seems to be incorrectly assuming my platform is darwin-x64.

Also note that running the equivalent command via the terminal (be it from VS Code or iTerm) works flawlessly, so it seems to be related to the process that NX Console spins up.

By downloading the previous version of VS Code (v1.79.2) and confirming that the issue does not appear using that version, I thought I should report the bug here, as the update seems to have broken the existing extension, which I know you try to avoid.

## Expected Behavior

Clicking the "play" icon button in the NX Console next to project targets should work like it did in VS Code v1.79.2, ie. it should spin up a process and run the equivalent command.

## Steps to Reproduce

1. Match my environment with the M2 Pro chip, VS Code 1.80.0 and NX Console extension.
2. Clone and install https://github.com/nrwl/nx-examples
3. Attempt to use NX Console to run its the apps/cart `serve` target.
4. See "Missing Platform Dependency" error.

### Environment

- Platform:
> Chip Apple M2 Pro
MacOS 13.2.1 (22D68)

- Nx Console version:
> v18.4.0

- VSCode version (I tried others also, such as the Apple Silicon version and Insiders, with the same result):

> Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:40:17.963Z)
OS version: Darwin arm64 22.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (4.52GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id ea7f8ee1-c614-4503-8d6f-039472edbe47|
|Screen Reader|yes|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30784847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnoceb:30776495
cmakestatusbarv2:30779594

```

</details>

**Comment by deepak1556** [comment]
This seems like an issue with downloading platform dependent extensions, moving to you @sandy081

**Comment by sandy081** [comment]
@joeldbirch I assume you are using this extension - `nrwl.angular-console` and it does not seem to be platform specific. Hence I recommend to file issue against the extension

**Comment by joeldbirch** [comment]
I had [already posted an issue](https://github.com/nrwl/nx-console/issues/1810) to the extension repo. They were certain it was a VS Code bug.

**Comment by sandy081** [comment]
@joeldbirch It would be great and if you can ask the extension team why it is a VS Code bug and if they have the root cause.

**Comment by Cammisuli** [comment]
We believe this has something to do with the task API in vscode. We asked @joeldbirch to create a task using the tasks.json. I gave them the same command that the extension would build behind the scenes, and they got the same error: 

(steps to build out the tasks.json) https://github.com/nrwl/nx-console/issues/1810#issuecomment-1625325983 
(result) https://github.com/nrwl/nx-console/issues/1810#issuecomment-1626325915

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by joeldbirch** [comment]
@meganrogge I just checked, and unfortunately the issue still remains in the Insiders build.

**Comment by meganrogge** [comment]
Thanks for the report and info. It might take me awhile to get to this to be honest. If anyone feels like git bisecting to figure out where this regressed, that would speed up the process.

**Comment by joeldbirch** [comment]
Under the pretence of dropping a comment to prevent stale bot from shelving the issue: my whole team has needed to downgrade and freeze their VS Code to version 1.79.2 in order to continue using the tooling that this issue broke. It has been quite a concern.

**Comment by meganrogge** [comment]
@deepak1556 there was no change to the task API during the past iterations when this showed up. According to the report, this is an issue with the platform detection. Anything on your end that could explain this?

https://github.com/nrwl/nx-console/issues/1810#issuecomment-1633314734

**Comment by deepak1556** [comment]
@meganrogge none from the runtime side, the user is using universal build so there is no possibility of a translated process running.

**Comment by joeldbirch** [comment]
To clarify, I have used both Universal and Apple Silicon builds with the same result.

**Comment by meganrogge** [comment]
based on https://github.com/nrwl/nx-console/issues/1810#issuecomment-1641756506 and https://github.com/nrwl/nx-console/issues/1810#issuecomment-1658608717 I still don't think this issue originated from a VS Code task API change

**Comment by joeldbirch** [comment]
[I fixed my issue](https://github.com/nrwl/nx-console/issues/1810#issuecomment-1710893797) by debugging which version of Node the task API was using. On my machine, VS Code versions >= 1.80.0 use a version installed via Brew, which was likely installed prior to migrating from Intel to an M2 chip. This might explain  the incorrect platform detection. Once I deleted that installation path with `rm -rf` the task API used the Node version I had more recently installed via `nvm`, and my issue was solved.

I can only assume that the method VS Code determines which Node version to use changed between 1.79.2 and 1.80.0. I'd guess that the newer method is likely more correct, as I think the `nvm` `PATH` appears later than the Brew one.
