### ISSUE TITLE
openWalkthrough command does not navigate to the correct location on first try

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode#187958]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.80.1
- OS Version: Windows 10

The C++ extension would like to redirect our users to our walkthrough if they pick an option in one of our quick picks: "help me install a compiler".  To achieve this, we've been trying to invoke the command with a link to the correct step in the walkthrough similar to how python does it.

```ts
vscode.commands.executeCommand(
    'workbench.action.openWalkthrough',
    { category: 'ms-vscode.cpptools#cppWelcome', step: 'ms-vscode.cpptools#verify.compiler.windows' },
    true);
```

The problem I'm seeing is that if we run this command before the Welcome page is loaded, it does not navigate to the walkthrough at all.  It just displays the Welcome page and the following error appears in the Developer Console: `"Could not restore to category ms-vscode.cpptools#cppWelcome as it was not found"`.

If we run the command after the Welcome page loads (or just run the command twice in a row), it will work.  To work around it, I was going to try to detect whether the Weclome page or my walkthrough loaded after the first command attempt, but it doesn't look like the Welcome page's tab shows up in the list of `visibleTextEditors` so I'm not sure how to detect it.  The safest thing for now seems to be to run the command twice every time, but it would be nice if it could be fixed to work on the first attempt.

**Comment by bhavyaus** [comment]
F

**Comment by amunger** [comment]
I can't get this to work, even after opening the welcome window first - it only ever opens the generic welcome page for me.
I tried with the c++ walkthrough steps and one in jupyter ext

```
vscode.commands.executeCommand(
                "workbench.action.openWalkthrough",
                {
                    category: "ms-toolsai.jupyter#jupyterWelcome",
                    step: "ms-toolsai.jupyter#jupyter.dataScienceLearnMore",
                },
                true
            );
```

Am I doing something wrong?

**Comment by andreamah** [comment]
Fixed by https://github.com/microsoft/vscode/pull/191947

**Comment by aeschli** [comment]
This still doesn't work properly. The welcome page opens on the correct page, but then immediately switches back to the main welcome page.
![Peek 2023-09-01 09-49](https://github.com/microsoft/vscode/assets/6461412/54b7d005-7af9-40dd-8e8e-46c5206e66a6)

**Comment by bhavyaus** [comment]
I'm unable to repro @aeschli. 

Here are my repro steps:
1. Created a sample extension
2. Registered a command in the sample extension to open a walkthrough coming from an extension using

```
vscode.commands.registerCommand('myExtension.openWalkthrough', () => {
      vscode.commands.executeCommand('workbench.action.openWalkthrough', { category: 'ms-vscode.cpptools#cppWelcome', step: 'ms-vscode.cpptools#verify.compiler.windows' },true);
    })
```
3. Packaged and installed test extension and invoked the above command.

**Comment by amunger** [comment]
repro's when debugging the extension with the command at least (I didn't try packaging into a visx)

1. added a command to the helloworld-sample extension https://github.com/microsoft/vscode-extension-samples in the package.json and registered during activation

```
vscode.commands.registerCommand('myExtension.openWalkthrough', () => {
      vscode.commands.executeCommand('workbench.action.openWalkthrough', { category: 'ms-vscode.cpptools#cppWelcome', step: 'ms-vscode.cpptools#verify.compiler.windows' },true);
    })
```

2. npm install
3. F5 to run, run the command

:bug: similar to @aeschli, though it also sort of tries to shift away from the main walkthrough page, then it works correctly the second time
![Recording 2023-09-27 at 15 46 35](https://github.com/microsoft/vscode/assets/2019016/b005563a-9fa7-4b63-9b19-80e55fd7fbae)
