### ISSUE TITLE
Walkthrough media image being duplicated.

### ISSUE THREAD

**Issue by darshanraju** [microsoft/vscode#188038]
Does this issue occur when all extensions are disabled?: No. 

- VS Code Version: [June 2023 Recovery 1](https://github.com/microsoft/vscode/releases/tag/1.80.1)
- OS Version: Windows 11

Steps to Reproduce:

1. Open up an extension walkthrough with the same media image across all steps
2. Clicking on the next step duplicates the image. Overflowing it.

![image](https://github.com/microsoft/vscode/assets/27645662/52bc4d2c-689d-4a6d-84ab-0adba96fcf91)

**Comment by bhavyaus** [comment]
This has been fixed in a more recent release

**Comment by darshanraju** [comment]
@bhavyaus I'm still having this issue on the latest release. On version 1.80.2 ([June 2023 Recovery 2](https://github.com/microsoft/vscode/releases/tag/1.80.2))
