### ISSUE TITLE
Visual Studio Code v1.82.1 Rendering Issue on Fedora Linux 38

### ISSUE THREAD

**Issue by anfreire** [microsoft/vscode#193096]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.82.1

Steps to Reproduce:

1. Install Visual Studio Code version 1.82.1 on Fedora Linux 38.
2. Launch Visual Studio Code.

### Issue Description

I have encountered a rendering issue with Visual Studio Code (VS Code) version 1.82.1 on my Fedora Linux 38 workstation. The graphical interface does not render correctly, as shown in the attached video. However, when I revert to version 1.81.1, everything works as expected.

### Video Attachment

https://github.com/microsoft/vscode/assets/100360644/1f8bf056-26db-4d0b-b9da-86c3d4c82e1b

### System Information

- **OS:** Fedora Linux 38 (Workstation Edition) x86_64
- **Kernel:** 6.4.15-200.fc38.x86_64
- **Resolution:** 1920x1080
- **DE:** GNOME 44.4
- **WM:** Mutter
- **CPU:** AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8)
- **GPU:** AMD ATI Radeon Vega Series / Radeon Vega Mobile

### Expected Behavior:

Visual Studio Code should render the graphical interface correctly without any rendering issues, as it does in version 1.81.1.

### Actual Behavior:

Visual Studio Code version 1.82.1 exhibits rendering issues, as demonstrated in the attached video.

### Additional Information:

- The issue is specific to version 1.82.1, as version 1.81.1 works correctly.
- I have attached a video that demonstrates the issue for better clarity.
- The issue persists after reinstalling Visual Studio Code or after a system reboot.
- The issue persists even after extensions are disabled.
- No error messages or logs are generated when encountering this issue.

### Workaround:

Currently, I am using version 1.81.1 as a workaround to avoid the rendering issue.

**Comment by SDEscobedo** [comment]
@anfreire I am having the same problem.
- **OS**: Fedora 38
- **DE**: KDE Plasma 5.27.7
- **Kernel**: 6.4.11-200.fc38.x86_64 
- **Graphic platform**: Wayland
- **CPU**: 8 x AMD FX(tm)-8300

**Comment by lukatendai** [comment]
the same, had to downgrade to 1.81.1

**Comment by nguyenminhtri455** [comment]
Same for me.

**Comment by lukatendai** [comment]
So there are errors when you run it with --verbose:
// Fragment GLSL
#version 300 es

#extension GL_NV_shader_noperspective_interpolation : require
precision mediump float;
precision mediump sampler2D;
out mediump vec4 sk_FragColor;
noperspective in highp vec4 vinCircleEdge_S0;
noperspective in mediump vec4 vinColor_S0;
void main() {
    highp vec4 circleEdge;
    circleEdge = vinCircleEdge_S0;
    mediump vec4 outputColor_S0;
    outputColor_S0 = vinColor_S0;
    highp float d = length(circleEdge.xy);
    mediump float distanceToOuterEdge = circleEdge.z * (1.0 - d);
    mediump float edgeAlpha = clamp(distanceToOuterEdge, 0.0, 1.0);
    mediump vec4 outputCoverage_S0 = vec4(edgeAlpha);
    {
        sk_FragColor = outputColor_S0 * outputCoverage_S0;
    }
}


Errors:
link failed but did not provide an info log
[10906:0914/132638.588032:WARNING:angle_platform_impl.cc(48)] ProgramGL.cpp:989 (checkLinkStatus): Program link or binary loading failed with no info log.
[10906:0914/132638.588100:ERROR:shared_context_state.cc(81)] Skia shader compilation error
`

also when disabling GPU, everything is fine
`

**Comment by anfreire** [comment]
Hello everyone,

I'm thrilled to report that the rendering issue with Visual Studio Code (VS Code) has been successfully resolved with the release of version 1.82.2. Many thanks to the VS Code development team for their quick response and diligent efforts in addressing this problem.

For those who might not be aware, the issue was related to the graphical interface not rendering correctly, as demonstrated in the attached video. This issue was particularly affecting Fedora Linux 38 users.

After testing the new version, 1.82.2, I can confirm that everything is now working as expected, and the rendering issue is no longer present. This demonstrates the commitment of the VS Code team to provide a stable and reliable development environment for users across various platforms.

If you haven't already, I highly recommend updating your VS Code installation to the latest version, 1.82.2, to benefit from the improvements and to ensure a seamless coding experience.

Happy coding with VS Code 1.82.2!

Best regards,
André Ferreira

**Comment by lukatendai** [comment]
nope, the problem is still there:
 [25630:0914/140800.844519:WARNING:angle_platform_impl.cc(48)] ProgramGL.cpp:989 (checkLinkStatus): Program link or binary loading failed with no info log.
[25630:0914/140800.844616:ERROR:shared_context_state.cc(81)] Skia shader compilation error

➜  ~ code --version
1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d)
Linux 6.4.15-200.fc38.x86_64

**Comment by anfreire** [comment]
@lukatendai I've reopened the issue for additional investigation, noting that the problem appears to be resolved on my end with VS Code version 1.82.2.

```
$ code --verbose
[29420:0914/191439.383061:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[main 2023-09-14T18:14:39.495Z] [File Watcher (node.js)] Request to start watching: /home/anfreire/.config/Code/User (excludes: <none>, includes: <all>),/home/anfreire/.config/Code/User/settings.json (excludes: <none>, includes: <all>)
[main 2023-09-14T18:14:39.505Z] [File Watcher (node.js)] Started watching: '/home/anfreire/.config/Code/User'
[main 2023-09-14T18:14:39.507Z] Sending env to running instance...
[main 2023-09-14T18:14:39.508Z] [File Watcher (node.js)] Started watching: '/home/anfreire/.config/Code/User/settings.json'
[main 2023-09-14T18:14:39.571Z] Sent env to running instance. Terminating...
[main 2023-09-14T18:14:39.571Z] Lifecycle#kill()
[main 2023-09-14T18:14:39.571Z] Lifecycle#onWillShutdown.fire()

$ uname -r
6.4.14-200.fc38.x86_64

$ code -v
1.82.2
abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
x64
```

**Comment by ndbzika** [comment]
I was having the same issue, to solve that I've removed the GPUCache as mentioned in https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium

**Comment by aliaksandr-bordak** [comment]
> I was having the same issue, to solve that I've removed the GPUCache as mentioned in https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium

This works, thank you.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/190437

Please follow the workaround mentioned in the release notes https://code.visualstudio.com/updates/v1_82#_update-highlights-for-chromium

**Comment by ReillyBrogan** [comment]
Can whoever is in charge of the release notes delete the mention that this issue has anything to do with Mesa? It has nothing to do with this issue, this is 100% a pure upstream Chromium issue bug. Mesa makes no guarantees that compiled shader objects should be compatible across updates to mesalib, libdrm, xorg libraries, llvm etc. There's nothing wrong with keeping a cache of those things, but the correct behavior is to discard it upon obvious errors and compile new objects to replace them.

Source, I help maintain a popular Linux distro and have seen this issue dozens of times across multiple Chromium applications. The following commands are our recommended first troubleshooting step whenever a user complains about rendering issues with Chrome(ium) or an Electron app:
```
find ~/.config -name GPUCache -exec rm -rv {} +
find ~/.cache -name GPUCache -exec rm -rv {} +
```
