### ISSUE TITLE
Debug toolbar not appearing

### ISSUE THREAD

**Issue by jlj-ee** [microsoft/vscode#194974]
Does this issue occur when all extensions are disabled?: Need language support extensions to be able to launch the debug session, but I have tried the minimal cases (just C/C++ Extension for debugging a C file, just Python extension for debugging a Python file).

Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Start a debug session. I tried both Python and C.
2. Debug toolbar does not appear for any location setting, including the default floating. Inspecting with the Developer Tools shows that the element is not present.
3. Debug session runs as normal and can be controlled by entries in the Run menu or keyboard shortcuts, but the debug toolbar never appears.

![image](https://github.com/microsoft/vscode/assets/11401637/93df1eb6-2901-48f4-ac1c-d6f81d5b1d6c)

Today is the first time this has ever happened after months of daily use. Another PC running the same version of VS Code with synced settings and extensions does NOT have this issue, nor does a fresh installation of the Insider's build. I tried a complete clean reinstall of VS Code 1.83.0, including deleting all appdata/userprofile files, but the issue remains through multiple restarts and relaunches.

**Comment by gjsjohnmurray** [comment]
What values do you have for the following settings?

- debug.toolBarLocation
- window.commandCenter
- window.titleBarStyle

**Comment by jlj-ee** [comment]
All are set to their defaults:
- debug.toolBarLocation: "floating"
- window.commandCenter: true
- window.titleBarStyle:  "custom"

**Comment by gjsjohnmurray** [comment]
If you set its location to "docked" does it show up in the titlebar of the Run and Debug view when you start debugging? Or if you set it to "commandCenter" does it appear there?

**Comment by jlj-ee** [comment]
Thanks for the follow-up. No, no location setting yields a visible toolbar on this workstation.
My second workstation running the identical version of VS Code and with all extensions and settings synced does not repro this issue. 

The "Window" output on the workstation with the issue shows the following error when I start a debug session with debug.toolBarLocation as floating:
```
2023-10-06 09:43:04.666 [error] Cannot read properties of undefined (reading 'closeOnEnd'): TypeError: Cannot read properties of undefined (reading 'closeOnEnd')
    at u.value (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1887:71844)
    at c.z (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.A (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at c.fire (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at R.W (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1885:25076)
    at u.value (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1885:24967)
    at c.z (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at c.fire (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at u.M (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:913:36807)
    at u.L (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:913:36654)
    at async u.K (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:913:36517)
    at async R.terminate (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1885:9161)
    at async G (vscode-file://vscode-app/c:/Users/jjimenez/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1887:41375)
```
Please let me know if there are any other outputs/logs I can generate to pass on.

**Comment by roblourens** [comment]
Thanks for the error. That looks like it would appear when debugging stops, not when it starts. But it indictates the possible problem, that we got an `undefined` value for the debug settings section, which shouldn't happen here.

Can you try clearing your whole settings.json file and trying it again?

**Comment by jlj-ee** [comment]
Thanks for the correction on the timing of that error, I can confirm that it is when the debug session stops, not starts, and have edited my comment.

I did try clearing the settings.json file; no luck.

The devtools console and Window log also show this error:
![image](https://github.com/microsoft/vscode/assets/11401637/57fe0c23-c08b-4770-8655-c5089eb666bb)

**Comment by jlj-ee** [comment]
Any further info on this? The issue has persisted for me through multiple VS Code updates.

**Comment by roblourens** [comment]
I'll try to add some logging or something here, still not sure what is going on though.

**Comment by connor4312** [comment]
yea, I don't think that error is related. I reproduced it by setting `debug.console: null` in my settings and got that error, but I didn't lose the debug toolbar.

In the screenshot in https://github.com/microsoft/vscode/issues/194974#issue-1929494574, the `.debug-toolbar` is not in the DOM at all. That could only (to my reading) happen without errors if these checks never pass (if we show the debug toolbar once, it's never removed from the DOM, only hidden). But I don't see how any of those would both happen across adapters and also with fresh settings.

https://github.com/microsoft/vscode/blob/8371e4a5671996be020ca9a514ca942a87b3d4d9/src/vs/workbench/contrib/debug/browser/debugToolBar.ts#L108-L113

**Comment by jlj-ee** [comment]
Thanks for continuing to track this. Just want to note that this issue persists for me.
A colleague is also experiencing it from the very first time they tried to start a debug session on a completely fresh install of VS Code on a reimaged Windows 10 PC.

**Comment by sketchbuch** [comment]
I also noticed recently when launching my extension that the debug toolbar appears, but something causes it to disappear and I have to close the launched instance of vscode and relaunch as the toolbar is gone.

This only stared happening sometime this year (2024).

**Comment by sketchbuch** [comment]
Here you can see that it disappears after reloading twice and then never reappears:
[Debug Toolbar Disappears.zip](https://github.com/microsoft/vscode/files/14227899/Debug.Toolbar.Disappears.zip)

**Comment by roblourens** [comment]
@jlj-ee is your issue fixed in Insiders? It might have been helped by https://github.com/microsoft/vscode/issues/204265, although yours might be different.

The others, I think your issue should be fixed in Insiders now.

**Comment by sketchbuch** [comment]
Just tried insiders v1.87.0 and my issue is still present.

Launching my extension to test it, click reload a few time on the toolbar and the toolbar disappears. My issue is not that the toolbar appears on the top left.

**Comment by connor4312** [comment]
Benjamin filed [this issue](https://github.com/microsoft/vscode/issues/208895) which is my best guess as to what's going on: the debug toolbar at some point got a position outside of the window and we never constrain its position to restore it to be within the window. I'm going to merge that into this issue and apply a hopeful fix for that.

**Comment by connor4312** [comment]
actually, nevermind, we do restraint it when the window is first loaded. That's not it 😕

**Comment by tjx666** [comment]
@connor4312 

I also occurs this issue when I debug a vscode extension, reproduce:

1. `git clone git@github.com:tjx666/package-manager-enhancer.git` and `pnpm install`
2. click debug button to open `debug vscode window`
3. open another folder in `debug vscode window`
4. click restart button, the debug toolbar disappear, but I can see the debug buttons in apple touch bar

```
Version: 1.88.0-insider (Universal)
Commit: 57028e3d274ebde851c7cc02123def372ca619a6
Date: 2024-04-03T04:45:14.890Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

**Comment by connor4312** [comment]
Your case was https://github.com/microsoft/vscode/issues/203472. I don't think that is what this issue is about.
