### ISSUE TITLE
code lens for TypeScript should not show references for anonymous functions

### ISSUE THREAD

**Issue by htho** [microsoft/vscode#198389]
For Anonymous functions code lens is displayed although it has only one reference.
This is a lot of noise for nothing.

```typescript
foo(): number[] {
    /** 1 reference */
    return [1, 2, 3].filter(n => n > 1);
}
```

In my opinion these lenses can be removed completely.

**Comment by jrieken** [comment]
This issue lacks

* name of the language/extensions that you are using/showing

**Comment by htho** [comment]
> This issue lacks
> 
>     * name of the language/extensions that you are using/showing

You are right. My bad. I fixed it. Sorry.

**Comment by mjbvz** [comment]
Requires:

- `"typescript.referencesCodeLens.enabled": true`
- `"typescript.referencesCodeLens.showOnAllFunctions": true`

**Comment by eleanorjboyd** [comment]
I added in those required settings and am seeing the screenshot below. Seems to now only say 0 references instead of one but the code lens still exists


![Screenshot 2023-11-29 at 10 25 23 AM](https://github.com/microsoft/vscode/assets/26030610/9f0d5769-1edc-4f58-8def-5aed34bc8d3c)

**Comment by mjbvz** [comment]
I think the screenshot shows the expected (fixed) behavior. Previously the references code tense was on the line with `return`. There are zero references because there are no uses of that class or method

**Comment by htho** [comment]
yep - this is exactly what I wanted.
