### ISSUE TITLE
No longer possible to scroll by dragging up when empty zone directly out of viewport

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#20050]
- VSCode Version: 1.10.0
- OS Version: macOS

Steps to Reproduce:

1. have a diff that has deleted lines
2. move the right hand side up enough so that the viewzone of the deleted lines is right outside of the viewport
3. drag up with the mouse to scroll up

=> you cannot scroll anymore up anymore with dragging the mouse

A video:

![kapture 2017-02-06 at 16 00 09](https://cloud.githubusercontent.com/assets/900690/22652084/592c41d4-ec85-11e6-97c4-80302d8b8078.gif)

**Comment by alexandrudima** [comment]
This is not a regression. Tried in 1.7.2

**Comment by alexandrudima** [comment]
This has been fixed in the meantime.

**Comment by bpasero** [comment]
![flicker_chrome58](https://user-images.githubusercontent.com/900690/30972519-0ea3e6aa-a46b-11e7-86a9-361eed271faa.gif)

I am still seeing it with latest.

**Comment by alexandrudima** [comment]
Aha, I tried to reproduce by having the view zone partially in the viewport, while the bug is about having the viewzone not in the viewport.
