### ISSUE TITLE
TypeScript import is adding extra } character at the end of the statement

### ISSUE THREAD

**Issue by alsoicode** [microsoft/vscode#204037]
Type: <b>Bug</b>

Create a new TypeScript file.
Add a partial import statement to trigger an IntelliSense completion such as:

```typescript
import { Observable
```

Allow IntelliSense to complete the statement, resulting in:

```typescript
import { Observable } from 'rxjs'; }
```

Notice the trailing `}` character which is an error.

This issue also happens with all extensions off.
This issue is also present in the Insiders release.

The issue does *not* happen for imports that are added automatically. Example:

```typescript
this.myService.pipe(
  filter 
)
```
when typing `filter`, I am provided a choice of imports. When I select the import from `rxjs`, the import statement is added as expected.

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin x64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 5026a880-d1fa-478a-b897-c5d989528497|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by Vikingama** [comment]
Same
![Code-2024-02-04-03 16 02](https://github.com/microsoft/vscode/assets/26019582/ad8d01f9-fe84-4357-abd4-97e63b0dafe4)

**Comment by Mibeon** [comment]
I have this annoying bug since the last release too. Every f__ng time I import some stuff in TS, there is this brace at the end. 🤯🤦‍♂️

<img width="454" alt="image" src="https://github.com/microsoft/vscode/assets/35590178/28f1db31-f31a-4f2f-9498-f4f54ceea1f7">

**Comment by Vikingama** [comment]
Problem was not be resolved, ///^///

**Comment by Vikingama** [comment]
I mean, this bug was fixed in 1.87.0-insider rather than 1.86.2?

**Comment by so1ve** [comment]
Yes i think so

**Comment by nicitaacom** [comment]
I'm still have this issue - why it closed?


Steps to Reproduce:
1. import something as shown on the video

https://github.com/microsoft/vscode/assets/39565703/893be2a5-b6c9-4084-b62e-dfb59be0ccf4

**Comment by kamafozilov** [comment]
I'm having the same problem. I submitted an issue report today as well. Let's hope for a quick fix!

**Comment by nicitaacom** [comment]
> > I'm still have this issue - why it closed?
> > Steps to Reproduce:
> > 
> > 1. import something as shown on the video
> > 
> > 2024-02-25.18-15-38.mp4
> 
> It Was Fixed in Insider Channel

what?

Can you add more details how to fix it?

**Comment by Vikingama** [comment]
> > > I'm still have this issue - why it closed?
> > > Steps to Reproduce:
> > > 
> > > 1. import something as shown on the video
> > > 
> > > 2024-02-25.18-15-38.mp4
> > 
> > 
> > It Was Fixed in Insider Channel
> 
> what?
> 
> Can you add more details how to fix it?

https://github.com/microsoft/vscode/pull/204661/files

They add a 'insiders-released' label on this issue.

I download a insider version, this was fixed indeed.
