### ISSUE TITLE
[Meta] Enable windows 11 context menu by default in Stable

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#204696]
Bug tracks the pending tasks to be completed before the feature can be promoted to stable releases.

- [ ] Run as administrator does not trigger UAC elevation prompt when launching application from context menu (https://github.com/microsoft/vscode/issues/180065)

**Comment by ArcticLampyrid** [comment]
> Run as administrator does not trigger UAC elevation prompt when launching application from context menu

I believe that microsoft/vscode-explorer-command#17 will resolve it.

**Comment by arambazamba** [comment]
@ArcticLampyrid ... yes it does .... but it pops up a cmd box for a second ... would be fine to have a native implementation

**Comment by ArcticLampyrid** [comment]
@arambazamba Actually I did not call cmd. And I did not see a cmd box on my machine (Win11).

**Comment by schallm** [comment]
[PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/) offers this as a setting for several of their tools.  Change is immediate and shows no cmd.

![image](https://github.com/microsoft/vscode/assets/331167/367a12b8-cff7-4336-b690-bc5dc1da54d5)

**Comment by tompetk** [comment]
Is this in 2024 roadmap? Are we waiting for some Windows 11 update to improve whole context menu integration?

**Comment by ArchemedIan** [comment]
https://ae3.info/stuff/troy%20vscode.gif

**Comment by ArchemedIan** [comment]
https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fydgpgd26depc1.gif%3Fformat%3Dmp4%26s%3Df5acfa257d051e30647bbf111b29d5d73c34ff86

**Comment by deepak1556** [comment]
Yes this is on roadmap for 2024, we have movement on couple of the issues linked above and I need follow-up on them next milestone.

**Comment by ArchemedIan** [comment]
> Yes this is on roadmap for 2024, and has been since october 2022

fixed it for you

**Comment by maisondasilva** [comment]
I was unable to reproduce in Build Final, Beta, Dev and Canary and also in Sandbox.

**Comment by ArcticLampyrid** [comment]
A quarter has passed now, have you made any progress?
Is the API of Win11 really so bad that we spent three months still unable to integrate it correctly?

**Comment by robin-samuel** [comment]
Will this be available in stable before we reach windows 12?

**Comment by phuze** [comment]
This issue used to appear on their monthly milestone/iteration plans. Unfortunately, @deepak1556 moved it to their internal backlog in May, which suggests it's no longer on the 2024 roadmap. In my general experience, a backlog is usually a death sentence.

It's disheartening to admit that it has been three years since the community has repeatedly requested the return of this crucial productivity feature, which was lost with the release of Windows 11. I'm disappointed that the VS Code team hasn't been able to resolve the issues surrounding the Windows 11 context menu in all this time.

As a reminder, you can manually implement this context menu by modifying your VS Code installation. Please note that this is not an official Microsoft solution, so proceed at your own risk. However, I’ve used both methods mentioned below for years without any problems.

That said, I want to acknowledge the user [@strear](https://github.com/strear), who first identified a [workable solution](https://github.com/microsoft/vscode/pull/139640) back in December 2021, for which I'm incredibly grateful for their efforts. I had provided a detailed set of instructions, following their method [here](https://github.com/microsoft/vscode/pull/139640#issuecomment-1086109339).

More recently, an alternative method was posted by [@Chigusa0w0](https://github.com/Chigusa0w0) in June of 2023. This newer approach is arguably simpler, as it does not require you to build or self-sign an AppX package. I would recommend considering this [newer method](https://github.com/microsoft/vscode/issues/183297#issuecomment-1594350702).

![image](https://github.com/user-attachments/assets/500ddb4c-13cf-44b5-b834-f940f2562e58)

**Comment by kybarg** [comment]
Seems like this feature becomes a meme😂

**Comment by BartoszRojek** [comment]
I’ve developed a robust MSI installer that incorporates the [latest custom solution](https://github.com/microsoft/vscode/issues/183297#issuecomment-1594350702) by Chigusa0w0, along with a few improvements. While the solution is not digitally signed, rest assured that everything is transparent and built through a pipeline, including the MSI installer itself.

What’s the best way to share it with the community without stepping on anyone's toes? For example:

Can I post the link to the MSI here?
Do I need to replace "Microsoft" with a made-up company name, and "VSCode" or "Visual Studio Code" with something else?
Or something else entirely?

Is anyone interested?

**Comment by SimplyAddons** [comment]
> I’ve developed a robust MSI installer that incorporates the [latest custom solution](https://github.com/microsoft/vscode/issues/183297#issuecomment-1594350702) by Chigusa0w0, along with a few improvements. While the solution is not digitally signed, rest assured that everything is transparent and built through a pipeline, including the MSI installer itself.
> 
> What’s the best way to share it with the community without stepping on anyone's toes? For example:
> 
> Can I post the link to the MSI here? Do I need to replace "Microsoft" with a made-up company name, and "VSCode" or "Visual Studio Code" with something else? Or something else entirely?
> 
> Is anyone interested?

Sure, I'd be interested as I'm sure others would -- it sounds great. Though respectfully, I don't know you and I wouldn't be prepared to blindly take your word on what that installer is doing. Put the code on GitHub so that others can than verify for themselves that your solution isn't malicious. Include the MSI installer as a release file.

**Comment by phuze** [comment]
> I’ve developed a robust MSI installer that incorporates the [latest custom solution](https://github.com/microsoft/vscode/issues/183297#issuecomment-1594350702) by Chigusa0w0, along with a few improvements. While the solution is not digitally signed, rest assured that everything is transparent and built through a pipeline, including the MSI installer itself.
> 
> What’s the best way to share it with the community without stepping on anyone's toes? For example:
> 
> Can I post the link to the MSI here? Do I need to replace "Microsoft" with a made-up company name, and "VSCode" or "Visual Studio Code" with something else? Or something else entirely?
> 
> Is anyone interested?

Sure, I'd be interested as I'm sure others would -- it sounds great. Though respectfully, I don't know you and I wouldn't be prepared to blindly take your word on what that installer is doing. Put the code on GitHub so that others can than verify for themselves that your solution isn't malicious. Include the MSI installer as a release file.

**Comment by BartoszRojek** [comment]
> Sure, I'd be interested as I'm sure others would -- it sounds great. Though respectfully, I don't know you and I wouldn't be prepared to blindly take your word on what that installer is doing. Put the code on GitHub so that others can verify for themselves that your solution isn't malicious. Include the MSI installer as a release file.

Sure, that was the plan from the beginning. I'm still waiting for feedback about the name change, though.

**Comment by BartoszRojek** [comment]
All right, here it is:

https://github.com/BartoszRojek/CodeModernExplorerMenu

- works with both system and user installation locations
- support the case when VSCode runs as Administrator, thanks to https://github.com/microsoft/vscode-explorer-command/pull/17
- works for Devices and drives, thanks to https://github.com/microsoft/vscode-explorer-command/pull/16
- future VSCode updates won’t break the menu, thanks to [huutaiii](https://github.com/huutaiii/vscode-explorer-command)

@deepak1556 I hope that you don't mind, let me know otherwise.

**Comment by isacalmeida** [comment]
> All right, here it is:
> 
> https://github.com/BartoszRojek/CodeModernExplorerMenu
> 
> * works with both system and user installation locations
> * support the case when VSCode runs as Administrator, thanks to [fix: use ShellExecuteW instead of CreateProcessW, allowing UAC dialog vscode-explorer-command#17](https://github.com/microsoft/vscode-explorer-command/pull/17)
> * works for Devices and drives, thanks to [Show VSCode in Drives' ContextMenu vscode-explorer-command#16](https://github.com/microsoft/vscode-explorer-command/pull/16)
> * future VSCode updates won’t break the menu, thanks to [huutaiii](https://github.com/huutaiii/vscode-explorer-command)
> 
> [@deepak1556](https://github.com/deepak1556) I hope that you don't mind, let me know otherwise.

Hello @BartoszRojek,

I had a single problem with your program, the VSCode installation path. 

In my case VSCode is not installed in "C:\Program Files".

Is there anything I can do?

Thanks

**Comment by BartoszRojek** [comment]
@isacalmeida Hey,

If you mean some custom location other than the default VSCode 'System' of the 'User' installation path then:

Fork the repo, edit the path here [explorer_command.cc](https://github.com/BartoszRojek/CodeModernExplorerMenu/blob/02e90242a98b3982356b4e94f963351e35f236c4/src/explorer_command.cc#L130), commit changes, and the automatic build will be triggered. Open the last build from the "Actions" tab, and you should see msi at the Artifacts.

Hope this helps.

**Comment by TeeJay69** [comment]
@BartoszRojek thank you so much for the MSI package. I spent like an hour and I could not believe that this is not already implemented in the stable version of VSCode. 
So thank you very much for making my life a little easier
 :)

Still I love Vscode and respect the developers not any less than before, awesome work :))))

**Comment by BartoszRojek** [comment]
@carlosrmendes You could try
 `msiexec.exe /i C:\Code.Modern.Explorer.Menu.4.0.0.x64.msi /L*vx! C:\Code.Modern.Explorer.Menu.log`
but if this doesn't show an obvious error then debugging this is hard.

**Comment by Inui-senpai** [comment]
> All right, here it is:
> 
> https://github.com/BartoszRojek/CodeModernExplorerMenu

It works even without the Windows Explorer restart. By the way, can I translate this option somehow, like in the "legacy" context menu? 🤔
![Image](https://github.com/user-attachments/assets/ef7d2097-7f03-46b2-b5f6-bcbc798f15e1)
![Image](https://github.com/user-attachments/assets/e839c3a9-dd21-4bc3-87cd-4b0a2843fdd2)

**Comment by BartoszRojek** [comment]
@Inui-senpai While this is outside the scope of the solution provided, you can definitely do a registry modification for those Explorer legacy menus.

**Comment by StewMcc** [comment]
You know it's a bad design decision when neither of the MS ide/dev tools support the new context menu. (Open with VS/VSCode both unsupported)....

**Comment by Iemand005** [comment]
I just did a fresh install of VSCode 1.100.2 on another computer just to be disappointed again by not having the Open with Code option in my context menus.

I thought VSCode was developed by the same company as the operating system? How on earth is it possible it doesn't simply work like it's supposed to out of the box? There is an obvious design flaw, this is unacceptable, especially from an application of this scale.

Not a single time have I actually seen the Open with Code option appear on any version of Windows 11 I installed VSCode on. I keep having to open the legacy context menu for this.

How difficult is it to add a button anywhere in VSCode that installs the context menu shortcut? Put a setting in settings, or an option with the Ctrl + Shift + P menu to toggle the new context menu, I don't care where but just add the option to enable it in the installer from the website or in VSCode itself just anything, please!
This is incredibly frustrating, I've been waiting for multiple years at this point expecting it to eventually come by itself but nope. Very disappointing.

**Comment by kybarg** [comment]
@Iemand005 Don't let it get you😊 Thre is a new kid on the block https://zed.dev/. Written in Rust with GPU accelerated UI. Will switch to it as soon as it is released on Widnows and forget about all the issues with VS Code.

**Comment by tompetk** [comment]
Another alternative is to use MacOS, it has VS Code between open with and works way faster than Windows.

**Comment by kybarg** [comment]
> Another alternative is to use MacOS, it has VS Code between open with and works way faster than Windows.

It is the most annoying thing about Microsoft for me. Very poor integration beween its own products. I thing these apps should be an A-class exmaple on how to develop apps for Windows, but instead even basic features, peresent in tird party apps are missing.

**Comment by tompetk** [comment]
Windows not generating much revenue compared to Azure / Office, so that's last in the queue for resources internally I guess. And it is enterprise centered in general, so no one cares how easy product is to use for end consumer.

**Comment by DevX-Cipher** [comment]
this causes duplication https://github.com/BartoszRojek/CodeModernExplorerMenu/blob/02e90242a98b3982356b4e94f963351e35f236c4/src/explorer_command.cc#L164

**Comment by BanditTech** [comment]
> > All right, here it is:
> > https://github.com/BartoszRojek/CodeModernExplorerMenu

I have been looking for some way to get this functionality again for so long, thank you for sharing this!
Working perfectly! 

<img width="502" height="403" alt="Image" src="https://github.com/user-attachments/assets/482b46a6-b8ae-4486-8f9f-8270937a035c" />

**Comment by mathiasplans** [comment]
Hey @BartoszRojek 

I have another question about your addon. I want to install it on school computers. However, the option does not appear for other users. What changes to the installer should I make?

**Comment by BartoszRojek** [comment]
@mathiasplans As I said earlier, you could try
msiexec.exe /i C:\Code.Modern.Explorer.Menu.4.0.0.x64.msi /L*vx! C:\Code.Modern.Explorer.Menu.log
, but if this doesn't show an obvious error, then debugging this is hard. Make sure OS is the latest Windows 11.

**Comment by carlosrmendes** [comment]
@erobertsme suggesting an alternative where the feature in question actually works (one that’s been pending for years to be added to vscode) is always helpful… it’s such a hassle having to make extra clicks to access the old context menu just to open a folder or file in vscode, and even more shocking than how many years have passed is the fact that vscode is a Microsoft product...

**Comment by DevX-Cipher** [comment]
The context menu should be reviewed. When a user right-clicks a text file, it is not intuitive for the primary action to be buried under Open with or Show more options just to display Visual Studio Code. The Extract action is a direct operation and should be available immediately in the main right-click menu. Requiring additional clicks reduces usability and does not align with user expectations for common file actions.

**Comment by andresiraola** [comment]
the whole idea behind the new context menu is not to do less clicks, it's to do more clicks! and vscode is making sure of it

**Comment by phuze** [comment]
I've been part of various discussions about this context menu since 2022, so it's great to see it included in the draft January 2026 Iteration Plan after a long absence. That gives me hope the VS Code team is ready to revisit it.

In the meantime, several community-driven implementations of this context menu have appeared over the years -- and they still work today. The most complete version is packaged as an MSI installer, works on both files and folders, and continues to function smoothly across VS Code updates.

You can find it here: https://github.com/BartoszRojek/CodeModernExplorerMenu

<img width="600" height="254" alt="Image" src="https://github.com/user-attachments/assets/10a66c03-2db6-46c5-ad1a-a5b498a6b289" />
