### ISSUE TITLE
Option "View value in Data Viewer" not displayed

### ISSUE THREAD

**Issue by markodjordjic** [microsoft/vscode#204896]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.86.1
- OS Version: Windows 11 Pro 10.0.22631

Steps to Reproduce:

1.  Create a dummy data set (pandas.DataFrame, numpy.array, etc.).
2.  Set a break point in the debugger, somewhere after the creation of dummy data set.
3.  Start with Debugging (F5) Python File.
4.  Enter the Debug Console
5.  Right click the dummy data set. No option to view value appears.

![image](https://github.com/microsoft/vscode/assets/46163841/766a79e8-0d4d-42e7-97e1-7d4718b103f7)

**Comment by amunger** [comment]
this should be fixed, dupe of https://github.com/microsoft/vscode-jupyter/issues/15121

**Comment by CorentinJ** [comment]
This is not fixed, this is independent from jupyter and the fix proposed there does not apply to debug mode. I can reproduce the same issue on the latest version of vscode

**Comment by amunger** [comment]
@CorentinJ - the only command I know of like this for the debug panel's context menu is contributed by the jupyter extension.
