### ISSUE TITLE
Azure repo extension creds expired.

### ISSUE THREAD

**Issue by avenson278** [microsoft/vscode#205404]
Getting the following each day several times.

**_The provided credentials are either invalid or expired. Would you like to reauthenticate?

Source: Azure Repos_**

**Comment by TylerLeonhardt** [comment]
This is an old issue, and should be addressed by our totally rewritten Microsoft Auth extension... can you give that a try with:
```json
"microsoft-authentication.implementation": "msal"
```
 and then restart VS Code?

**Comment by tctxdwyer** [comment]
Hi,

Where should I add that? I tried adding it to my User Settings JSON and restarting, but the popup to reauthenticate still occurred. 

Thanks!

**Comment by TylerLeonhardt** [comment]
In User Settings, you are correct. Note, that you will need to re-authenticate, but once you do re-authenticate, you shouldn't get into a state where the credentials are expired.

**Comment by tctxdwyer** [comment]
Hi, thanks for the confirmation. I did add this in the correct place, but I still seem to get the popup. The only difference now is that it no longer opens a browser window for me to confirm the login. It now only asks me in VS Code to reauthenticate in the application.

**Comment by TylerLeonhardt** [comment]
Well you should get it once... but are you getting it over and over again? I don't quite follow what you're seeing. Maybe a recording would be helpful.
