### ISSUE TITLE
[multiple themes] different themes for different filetypes

### ISSUE THREAD

**Issue by darekzak** [Microsoft/vscode#20652]
Is it possible to have different themes for different filetypes?

**Comment by aeschli** [comment]
@darekzak Please explain more... Is it about file icon themes or color themes?

**Comment by darekzak** [comment]
I should gave more details, sry. I meant color theme.

**Comment by aeschli** [comment]
Sorry, can you explain more? Still not clear how file types should correlate with color themes?
Something like:
```json
{
    "*.java": "Monokai"
}
```

**Comment by darekzak** [comment]
Yes, exactly like that.  
{
  "*.js": "Monokai",
  "*.html": "Flatland Monokai"
}

**Comment by aeschli** [comment]
Ahh. But themes already theme more than just the editor. What would we do if two editors are open?

**Comment by wopian** [comment]
For me, this would remove the manual action of constantly changing colour theme when working on a specific set of languages (mainly AGC) in [chrislgarry/Apollo-11](https://github.com/chrislgarry/Apollo-11) or [virtualagc/virtualagc](https://github.com/virtualagc/virtualagc), then switching back to my dark theme when working on anything else.

As due to the archived printouts being printed with black text on white, its far easier to compare the transcribed code in VS Code with the images and spot typos when they're a similar colour - instead of contrasting.

Example:
![](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/1316.jpg)

**Comment by Voleking** [comment]
I have the same requirement like the questioner.
[Different themes for different languages in Visual Studio Code](http://stackoverflow.com/questions/40263971/different-themes-for-different-languages-in-visual-studio-code)

**Comment by facelesspanda** [comment]
> What would we do if two editors are open?

My thoughts go to a differentiation between themes specified for a language and "the theme of the workspace".
If two editors are open, they apply whatever theme matches the language found. The rest of the UI uses only the "main theme".
Agreed, it would slow down editor loading time a tad more.

A second option is to go the atom way and separate UI themes from Syntax themes, but I'm not much more convinced by this.

**Comment by gordonbondon** [comment]
One more reason to implement this is having different themes for code and documentation:
light theme for *.md files
dark for everything else

**Comment by pcunite** [comment]
Theming per file type (file extension, etc.) is highly desirable. Notepad++, Sublime Text have it, vsCode should have this too. I have a sample tmTheme file I use for Sublime Text if anyone is interested in making it work with vsCode.

**Comment by Danilux** [comment]
+1 for this, my current use case is to have a specific theme when opening markdown files, for the rest of lenguages I must admit I use the same theme

**Comment by darkpoetcc** [comment]
I have to agree with the requestor -- I am used to editing languages more in specific color schemes from my previous IDEs (STS [Eclipse-based]) vs Atom & Brackets vs Visual Studio vs various Json/XML editors/parsers.  This would be very useful, IMO.

**Comment by Place1** [comment]
I'm keen for this as well. Ideally I could override any setting when i'm editing a specific language. I like to totally change up my config when editing LaTex files, i.e. Serif font, larger font size, light color theme, different 'files.exclude' different settings for some other extensions i've got and more. Supporing more than just the 'editor.*' settings would be great :D

**Comment by jay-hankins** [comment]
As others have said, this is an extremely versatile feature that is hard to articulate how useful it is. It  is something I sorely miss from Sublime Text.

**Comment by Enteleform** [comment]
I wrote a [**Conditional Color Scheme**](https://packagecontrol.io/packages/Conditional%20ColorSchemes) plugin for Sublime Text, and am currently considering making VS Code my primary editor.&nbsp; I'm still working through the default settings & keymap to see what's available, so I haven't had a chance to check out the API yet.

Does VS Code have something similar to Sublime Text's
```python
view.settings().set("color_scheme", "__new_color_scheme_name__")
```
?

**Comment by vinnytroia** [comment]
+1

**Comment by aeschli** [comment]
@Enteleform Yes, extensions can change the current theme through the settings.

**Comment by Enteleform** [comment]
@aeschli 
I know it can be done globally, which includes the GUI components.
Is it possible to affect only the document view of a single file?

**Comment by aeschli** [comment]
Our token theming engine currently only supports one theme a time. The code would have to be refactored.

**Comment by anwar3606** [comment]
@aeschli Than how would I change the theme with extension? any direction?

**Comment by aeschli** [comment]
Check out https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameworkspaceconfigurationaspan-classcodeitem-id943workspaceconfigurationspan
Use `update` to manipulate a setting

**Comment by halukkaramete** [comment]
Not sure, if this belongs here. But, is it possible to define something like this:
if the extension is .txt, make the font bigger.

**Comment by GarethOates** [comment]
Yeah this would be really nice.  I'm used to coding in Javascript with the monokai theme, but the Visual studio dark theme for C#.  Old habits I guess.

**Comment by brandonb927** [comment]
@halukkaramete Add this to your settings
```
"[plaintext]": {
  "editor.fontSize": <num>,
}
```

**Comment by cklouman** [comment]
Here is a use case which hasn't been mentioned: when using code to view JS files someone might conceivably be so stupid as to start editing the JS file, and then after 20 minutes compile the changes, and then spend another few seconds trying to find out why the changes did not take. A visual cue for JS files would minify the risk. Asking for a friend ;)

**Comment by Snake-Sanders** [comment]
I came here for the same thing, Sublime Text has it. I miss this feature here

**Comment by drbarto** [comment]
I have a slightly different take on multi-theming... is it possible to assign themes per window/workspace?  (Most likely it's _not_ possible, else someone in this thread would have mentioned it.)

My use case is this: I work on a Web project with a JavaScript backend and a JavaScript frontend, and often have both workspaces (plus a 3rd auxiliary workspace sometimes) open at the same time. I'd love to assign different color schemes to each window so that when task-cycling I could find the correct window more easily. So in my case, a per-language theme setting would not work because it's JavaScript all over the place.

**Comment by tsaiDavid** [comment]
This would be really helpful - particularly if the rest of the GUI doesn't change. I find certain syntax themes to work well for "everything else", like `nord` - but when it comes to writing JSX/TSX, I just can't help but fall back to my favorite `oceanic-next` theme.

**Comment by manix** [comment]
+1

**Comment by 199621** [comment]
this is where it all started
Received: from HE1EUR02HT199.eop-EUR02.prod.protection.outlook.com
 (10.164.143.25) by DM5PR03MB3353.namprd03.prod.outlook.com with HTTPS via
 DM5PR08CA0036.NAMPRD08.PROD.OUTLOOK.COM; Sun, 24 Dec 2017 00:35:00 +0000
Received: from HE1EUR02FT055.eop-EUR02.prod.protection.outlook.com
 (10.152.10.57) by HE1EUR02HT199.eop-EUR02.prod.protection.outlook.com
 (10.152.11.91) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.20.302.6; Sun, 24
 Dec 2017 00:34:59 +0000
Authentication-Results: spf=pass (sender IP is 40.92.7.18)
 smtp.mailfrom=hotmail.com; hotmail.com; dkim=pass (signature was verified)
 header.d=hotmail.com;hotmail.com; dmarc=pass action=none
 header.from=hotmail.com;
Received-SPF: Pass (protection.outlook.com: domain of hotmail.com designates
 40.92.7.18 as permitted sender) receiver=protection.outlook.com;
 client-ip=40.92.7.18; helo=NAM03-CO1-obe.outbound.protection.outlook.com;
Received: from NAM03-CO1-obe.outbound.protection.outlook.com (40.92.7.18) by
 HE1EUR02FT055.mail.protection.outlook.com (10.152.11.101) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.20.302.6 via Frontend Transport; Sun, 24 Dec 2017 00:34:59 +0000
X-IncomingTopHeaderMarker: OriginalChecksum:E316788E2F838C59081909DEA45BDFED11F2D9E016796D83BF6780FE40DFCBFD;UpperCasedChecksum:E0BE175F3A71DAD60B08411AD774806AA3ACA5557A92CBF94630EC7A44940C77;SizeAsReceived:4974;Count:38
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=hotmail.com;
 s=selector1; h=From:Date:Subject:Message-ID:Content-Type:MIME-Version;
 bh=CXNhvup2nD1lADH614RWXcdf8uEHcFFWemepon+dtNI=;
 b=SbxjWdTEODIIoBzxPPYoTDpI7QNgH1P/6Te9tSzahywA6NCA/ZRr10Cg5uorTguh632OZy0LQbyp3om2hIqHtNYSqBVu5H7Bm9M/D6B1CRBrY5zi6WwEiVczglypIS+U4FP7KrJIFw0RAZ6jRAVhEMR4G1TBoGt/VPAIprIGgnXbeX5IzU9jBcvT+bO5a2Tfjz3tMi8mZrK1q8QGsTIxuwKTYFbbET0abzC8CuGm9RTNt2jpXQMf+7XC1cMFUjRe95D3F8BeoPWp1FFsFkBqxtyYO8o+kYKgJKY5g4PGqegQrxpXAuLnlIO5QxjR8Q1STnLskPyzbx7kJTbBksb3LA==
Received: from BY2NAM03FT030.eop-NAM03.prod.protection.outlook.com
 (10.152.84.53) by BY2NAM03HT058.eop-NAM03.prod.protection.outlook.com
 (10.152.85.227) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id 15.20.345.12; Sun, 24
 Dec 2017 00:34:53 +0000
Received: from DM5PR03MB3353.namprd03.prod.outlook.com (10.152.84.58) by
 BY2NAM03FT030.mail.protection.outlook.com (10.152.84.214) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256) id
 15.20.345.12 via Frontend Transport; Sun, 24 Dec 2017 00:34:53 +0000
Received: from DM5PR03MB3353.namprd03.prod.outlook.com ([10.174.241.150]) by
 DM5PR03MB3353.namprd03.prod.outlook.com ([10.174.241.150]) with mapi id
 15.20.0345.013; Sun, 24 Dec 2017 00:34:52 +0000
From: phillip matthews <onekid69@hotmail.com>
To: phillip matthews <onekid69@hotmail.com>
Subject:
Thread-Index: AQHTfE8D+KDjUfjbf06Wpc4Gq8PSyg==
Date: Sun, 24 Dec 2017 00:34:52 +0000
Message-ID: <DM5PR03MB335332A6770F1800F09824C9C2000@DM5PR03MB3353.namprd03.prod.outlook.com>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
x-incomingtopheadermarker: OriginalChecksum:BC4C325ED0A3C22B9FDB067CEB9BEA0305FAA3C4FFD587F0E8AC7026307D15C1;UpperCasedChecksum:4BF90BF76947D329813530D33D350E407469FBA1F3E00BCCB28C034C18E56963;SizeAsReceived:6738;Count:43
x-ms-exchange-messagesentrepresentingtype: 1
x-tmn: [ds0EDlq/GYbugDK4FyhkYSFRJrmDe+zL]
x-ms-publictraffictype: Email
X-Microsoft-Exchange-Diagnostics-untrusted: 1;BY2NAM03HT058;6:9rRoQ63+ov+ryyCB+R5eJsIWsWA84PvB7aKM+LtuTBtuZmF40wwz5PyETw9i8Ay/g7LRXaxc+eQL9ReIxad8WrGQlP6jwzKTd3axXLRQHpbV4+9NMz1ly7VKS2asfFI5ZVYL70E25ECLH/EZapFiD+EzWb4GIINGfdGsk9d55s3k6GZ/GIkqEeP34XQ8hoqOseViYW1QIvm+xhh3wzrGVmnH/E7X3s61UtAuA4NHAJHAO+scIhGgJ6igIcLvXupZeulCs76f1oHOphroPpn81FZtJcgrpkjYRkxdTbgfYzu3Sh+sG9syIBtGvKNFzese4atZwJzWJHc9jBMuJh0x3uV9qgA9/gOgj422GSUFGw0=;5:AiGla2sisA1oCDDgUNysrWX0Ob64NJQh0grxP5eS7UoxsMNdv0iYCpddwGns0LAkvrrngUhZ4L/VzVN2GyTjr5TW7wnuHrrsG5+udSyXN/6+fWWE3rZmDACfZDqjnhqMLPcMyqvCXKNn1Z0gLauZxN77CHWjyAzvU4XX08QGvZ8=;24:guqOJYvfzQ5p4JzAJpApJ5DOYAocEZeYLHwZ8XpS1XICxurttvRaTDM3wg3wLQNXCIB3PSuk1IN8RqCEg0gBM3kYWIVhDyhQksj4v245/Vk=;7:ju7J4wzxjiNd1jWx07Id43oUegb5QqG6kq/XvhlJuJeM+CGqDVj2dD0LMIqi3lfszNAf0EPFCFRdn6qc18uhvkcmfNEZ99VqWswjVx//eqOMGL5xw0DjHqFTrznLUb4/s2u7XIIDEZMTJ21Ec+ElOHjKH6D+aeogfRAInEffguLLelgvxplmvPM1rkII+Ckof7Q/DQlsOaCdwh1i5UCfCAG6nqiKMc0l/l2NNz8YM6VhQpgCpswziGFEfLhwv7DH
x-incomingheadercount: 43
x-eopattributedmessage: 1
X-Microsoft-Antispam-Untrusted: UriScan:;BCL:0;PCL:0;RULEID:(7020020)(201702061074)(5061506573)(5061507331)(1603103135)(2017031320274)(2017031324274)(2017031323274)(201702181274)(2017031322404)(1601125374)(1603101448)(1701031045);SRVR:BY2NAM03HT058;
x-ms-exchange-slblob-mailprops: o2C/200ZYyEEAaZYu0BX0fgsXGFHsoTg7nZyQZxhFEmmyM6+ZbpItfWA9bUw9tduWkZc/LJzooi8AtYt7lymIr2loxRgbA2PC0b92Q9OelDUYkAAn7fH6IsMPYWoOGVd8LF/g3TLemE0Qb5JDfr4H4arLvBIJ35sl7/woa507YYVLX3r/1zfQ92MREmYPti4td3ubEXIADtQK/I5tGQeJDQ3LuEpkHrVOxK4OdtXi/sOsXHaZEAtooeyHRfDqmeJJKuZ8X/+jTE7CsLTlZIO6csg0ZFNs7ZeDnnup/rOmTH7g+bpoOdjLcY+ult5cXKZc1QT2/0WMIC6TX9G7QDMCtPsZ1SSWry+F2MddZZ2JQa9iS12PgqWeJMkrThoQEWg+oCAIYW5kGYJ+PmRfE0fKgD+TibXuW6EWUVojQMXZEOVB2ZaSjci+CwT6+o2hja11GKUKgM9HyTQLrbxp31RJ9+1w1k6imxGaYpAt0Y5NU+lBCNmjkS16AzMeYqtmlhR8MZI/qWv8CxaVBWX8LivUNHp0XATiJo4hYRkIZ4+X+k=
X-MS-TrafficTypeDiagnostic: BY2NAM03HT058:|HE1EUR02HT199:
X-MS-Office365-Filtering-Correlation-Id: d6cc4d9a-28e9-4497-0e7d-08d54a662a28
x-exchange-antispam-report-cfa-test: BCL:0;PCL:0;RULEID:(444000031);SRVR:BY2NAM03HT058;BCL:0;PCL:0;RULEID:(100000803101)(100110400095);SRVR:BY2NAM03HT058;BCL:0;PCL:0;RULEID:(444111537)(595095)(82015058);SRVR:HE1EUR02HT199;BCL:0;PCL:0;RULEID:(100000803101)(100110400095);SRVR:HE1EUR02HT199;
x-forefront-prvs: 05315CBE52
X-Forefront-Antispam-Report-Untrusted: SFV:NSPM;SFS:(7070007)(98901004);DIR:OUT;SFP:1901;SCL:1;SRVR:BY2NAM03HT058;H:DM5PR03MB3353.namprd03.prod.outlook.com;FPR:;SPF:None;LANG:;
SpamDiagnosticOutput: 1:99
SpamDiagnosticMetadata: NSPM
Content-Type: multipart/alternative;
	boundary="_000_DM5PR03MB335332A6770F1800F09824C9C2000DM5PR03MB3353namp_"
X-MS-Exchange-Transport-CrossTenantHeadersStamped: BY2NAM03HT058
X-IncomingHeaderCount: 38
Return-Path: onekid69@hotmail.com
X-MS-Exchange-Organization-Network-Message-Id: d6cc4d9a-28e9-4497-0e7d-08d54a662a28
X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-MS-Exchange-Transport-CrossTenantHeadersStripped: HE1EUR02FT055.eop-EUR02.prod.protection.outlook.com
X-Microsoft-Exchange-Diagnostics: 1;HE1EUR02FT055;1:qiOlFUKhlNvJy+MTWg3xI9IxLzHpj5ZFJZgv1omUPeHowLR0vOIeiol5uCtV/IlD54LKM4L8DzQTRElloeRN/i7Ez2txYlTqNhvYcbkdSWARDXxXSAAs+6zjB6r4lA/a
X-Forefront-Antispam-Report: EFV:NLI;SFV:NSPM;SFS:(98901004);DIR:INB;SFP:;SCL:1;SRVR:HE1EUR02HT199;H:NAM03-CO1-obe.outbound.protection.outlook.com;FPR:;SPF:None;LANG:;
X-MS-Exchange-Organization-AuthSource: HE1EUR02FT055.eop-EUR02.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-Microsoft-Antispam: BCL:0;PCL:0;RULEID:(5000109)(4604075)(4605076)(610169)(650170)(651021)(8291501071);SRVR:HE1EUR02HT199;
X-Microsoft-Exchange-Diagnostics: 1;HE1EUR02HT199;3:DYemr0KOFvEMFZcq+cBKD/NtzJAu5WxRVAJZxHQwxEEqlFk+doq4kKJLStm4H08DXlC6DNUdoIPNAoI6dXzJ34d9rdNT2ytDo6QfSshNI3Ut1hPE5XbUnL6p/I0npexdp//kTLmw6CpIbvHsHfbs0GBmK0rHA+UwwJGx1uqfT3TIQh8zHjQ3gxmXJMxul6iUkIIoyqFeq3egwurUkGIHTeC1jW0X/ekBRmbvKVfSdkdJeSZQQhQf12Ex+hwmfrxftHE9OKWzxjxnPf6cCj8N9MTWw7vd/u/VyN5kTHOvzzRUM1GtqMoEpSX8lwxLhg1M;25:jOY8aO9wTOd5RVVFHC00QX3TssCejoAdoC7QucD5nUzj/+2rn1eSI+e+DHVNfWl0vAUMn+26RZUU1sGBeU1KfMizMSPZwMVubdjf5eQD9nX3SiJO/O1Rcq+9CIdKfeQaKkO0XDBCaQo2iT2YkVUD9Zwx4Tgjf96QBJHGngzsXYLwYd513XG4JKe8hKHosH2LWGc7TwBn2zfk+HLL7WX/38YQfH13raqoyvkxybv70vrn1/HdTFBOqAnYuj/8VHiS3NfsDNvgtrZtakMjUqJQH09VvnN2ddYWmF1ZvXJIubTnJeJrebTIS3Te9FfCfdE0zDA2iKLOvf4Y5l6KYyRicQ==;31:fnemzE0H0MUaSRYEhZTQ6AeOuT9o91m6a9FJn5YbWZKu6Qeujw/lXzsU/y8D0oxW0i0ZlUIUIYljXHE7rkjiWEe4GztlV/pCEzcLqlzbkj6RVODas7+e5Jk+bgnpEPhb569vnwJ0tHeXdL3L5WNWVHp8sG16dWXgeFODtcUa9N08uzvNq+mxtfxTrbzXKVctInuzM0lO62bsJHDJlvPXV2MNroPgDtSdUXmSiclGiTY=
X-MS-Exchange-EOPDirect: true
X-Sender-IP: 40.92.7.18
X-SID-PRA: ONEKID69@HOTMAIL.COM
X-SID-Result: PASS
X-MS-Exchange-Organization-PCL: 2
X-Exchange-Antispam-Report-Test: UriScan:(111885846020525)(81439100147899);
X-Microsoft-Exchange-Diagnostics: 1;HE1EUR02HT199;4:HUJYXnHFPOgg+faPuz4CnULJbcdzvRuM4ZZ9T8tOYLXliUIY9iErneA49XRbYXaMzjMpNB0PTLNBC/tJFzw+nE9/s58FptaPRnsoqQ1geB5V3ecUXdacC7vAgsayBGcnxwY/DCU87qvci0Irhvuh5pnAi1+rowPIYjpk7UF6ez78bFYoCTIqnWzslDWhY4U7+r2FMNSC+WvHQx9rjf8mKMF/0yv+N8vqgzG8nrg7UOl2BtODnKDxdlcHwKb53KGQ+GU7ZC4zbuLUpqzcFwrlm9vm7kC+BbahncMoM5L4ybCWjC9Mmbssd4IgCnDLbXvCEsL0WPMvA4AYclU1fviYrjbfe+cX2LcUXSgUX/60acc=;23:axD9XGRQ6P3en751G1yCjK/fSbyL88GGQ9dz4PHoFhee2psiYt+K+hLN2iwexNEjVUMy+u5/+kwG2F1P/Cgwp75Kpk4FCtzrzKGslYl3nqxBxN9NEKtuI4vWBQo3tihxdBulc200z+FkzqIfuPqRWrNqO4eTGMKgnOjG17gs64U=;6:cxyTMPdhpAZQThyhl/JZUAjoEd9RnROsjnJHujRmNEy4RxDA9z2RQOfNI/33lnNnqtF1WQdcEap0NrnrFv6za/ChJBvCZQwur09Yw4nWuIEihWG6qjz1ExMfIO2RjMGanIllW28ZDRnZFKk5o/nwSELGFdDq/t+xRNul+y9uxJdoVbshZOLENUZSllqnNaTFdPSqEIGJ0/xvt6i2BOyeqoYi3VRhdwI8uAGJx5pASxqTvRWQ7g3ObcNAPNdpcxEmKWe0O5Jobgsa4FYTX9yg1GUig3FtsxDqjYxMZL6Y7Pq8nrxZyq7JOiDNeFVgDR4yxk6IYdPIcPjCyE7K+x2AhdtVR+5U4rhm3819JGKvyiM=
X-MS-Exchange-Organization-SCL: 1
X-Microsoft-Antispam-Message-Info: k5NNCdVLBm5geBpop/jZ/rGIMRmL5oIw2oXPK916bcM0/Amd2tPjzGu31X6IaF2cJOkujREOvfjPuXViTb3NSh3FcncNbIRv24O8H9LQmho=
X-Microsoft-Exchange-Diagnostics: 1;HE1EUR02HT199;5:qla/f5SollR7mM3fI4Xo4GU9U6kpcCiyp9jKnp4L9YdLvvyGmyKxJFylOe899HNvKvNrkEGrxUwq7vkDft+ieLd9BTmAyPf4x308nuW6IY9Ls6Zi4jkXeACfV194TteKuzr35vxc4Wx0Qo1Btyceyn9xDF8LSObjmrzhj6aGggM=;24:EypPdNKWDVb2vN+kS5UJy5CNVf2QkOBaUfF1U+z6Su+NFXpU4pB6VBhR0BAEpyjRs8z2QgyI0IOe+avfoVUnzmnO1cLZGayjXnbTW0a78m4=;7:5eO+b/yrVgXqaSk4AqFEr46SE3zdqnwesDc5UEpMuZwz1QUH9oAhAx5GY47PE1dvdfbd1zz8CcgPeorVyEWmm4uJvHdVAok1xhMW9rofZAHA4lByoHNyBWuJYgr8rbJHloi+1mC/qK73RQGcDuGwW99dxdHMVyeRROZBiuXybcL+JcxL/wL094t++seAIJTy0744yDlLdktdVi96fyoZKeKyN3VbLR9RPKR4/jickFkHl5KdNLvATLtzn3RdkIOc
X-OriginatorOrg: hotmail.com
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 24 Dec 2017 00:34:59.4680
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: d6cc4d9a-28e9-4497-0e7d-08d54a662a28
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-Transport-CrossTenantHeadersStamped: HE1EUR02HT199
X-MS-Exchange-Transport-EndToEndLatency: 00:00:01.2446163
X-MS-Exchange-Processed-By-BccFoldering: 15.20.0345.013
X-Microsoft-Exchange-Diagnostics:
	1;DM5PR03MB3353;27:E269/Dm7kmpaYNNyoCor5TwXVzFufcHkuXX/+k0MoPdFQL7wZjTwRHdaboP4oRr5Z1TeKKa0trsCnECwRmAjRD2fhINSqTljyJqW9Q+uKQhIpKrkXvcOtsI22lmugQucXKtks4t6rfkzB0npWbkblg==
X-Microsoft-Antispam-Mailbox-Delivery:
	dkl:0;rwl:0;ex:0;auth:1;dest:I;ENG:(400001000128)(400125000095)(5062000261)(5061607266)(5061608174)(1004181)(4900095)(4920089)(6220004)(4950112)(4990090)(9110004);OFR:SpamFilterPass;
X-Message-Info:
	5vMbyqxGkdf4AQ5hYaEt2YOIrujbaDwg7BNiJljdGaUBF5j/t1mlKnd+lo6sgOP5iIUlT8J/q4gd76s6f1j1WqUTwqsLcLDUdItxHFIdm0sX6cO263UqmQW+CQS7slPPXhVfSY7c5Y75lHTaw5SquwJL6/6ngWhFEYNWqj4glUGvHwhOZZcirF+MjaWrTjEg8k86Fw+QvgGD/LBi2x/y9A==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0tMQ==
X-Microsoft-Antispam-Message-Info:
	4qOGVNYj1RmAhdyMkg693oeC4UXQ1cLxWLDMQOzrC2UbrPiXx7A2Kd+hA06Dc+m3L1rtVmY0pEjI+eZ9dhFRNISwmVcWAqZW1e7ylfaENQAcaY5fBtfMRLPQATAj2pJ2a0QhM13xHMnomzaB+kI0GGdaKkgmFZ0iUokPxpsm/uH/w+TsYLykfoIXJeh5V/OLtpoMB/ulJ7N5akNYQMVRSebtYbIoE01eEErF5+jGZl147TYWwFp591YhXcOJKoFuBLDm9dXBrDKLwVHXg/EOhqXL89PxAnaQUI0vcN4uEMqHsfZh4hG0KWrOxdjDf9ZY
MIME-Version: 1.0

--_000_DM5PR03MB335332A6770F1800F09824C9C2000DM5PR03MB3353namp_
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
X-Microsoft-Exchange-Diagnostics:
	1;DM5PR03MB3353;27:E269/Dm7kmpaYNNyoCor5TwXVzFufcHkuXX/+k0MoPdFQL7wZjTwRHdaboP4oRr5Z1TeKKa0trsCnECwRmAjRD2fhINSqTljyJqW9Q+uKQhIpKrkXvcOtsI22lmugQucXKtks4t6rfkzB0npWbkblg==
X-Microsoft-Antispam-Mailbox-Delivery:
	dkl:0;rwl:0;ex:0;auth:1;dest:I;ENG:(400001000128)(400125000095)(5062000261)(5061607266)(5061608174)(1004181)(4900095)(4920089)(6220004)(4950112)(4990090)(9110004);OFR:SpamFilterPass;
X-Message-Info:
	5vMbyqxGkdf4AQ5hYaEt2YOIrujbaDwg7BNiJljdGaUBF5j/t1mlKnd+lo6sgOP5iIUlT8J/q4gd76s6f1j1WqUTwqsLcLDUdItxHFIdm0sX6cO263UqmQW+CQS7slPPXhVfSY7c5Y75lHTaw5SquwJL6/6ngWhFEYNWqj4glUGvHwhOZZcirF+MjaWrTjEg8k86Fw+QvgGD/LBi2x/y9A==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0tMQ==
X-Microsoft-Antispam-Message-Info:
	4qOGVNYj1RmAhdyMkg693oeC4UXQ1cLxWLDMQOzrC2UbrPiXx7A2Kd+hA06Dc+m3L1rtVmY0pEjI+eZ9dhFRNISwmVcWAqZW1e7ylfaENQAcaY5fBtfMRLPQATAj2pJ2a0QhM13xHMnomzaB+kI0GGdaKkgmFZ0iUokPxpsm/uH/w+TsYLykfoIXJeh5V/OLtpoMB/ulJ7N5akNYQMVRSebtYbIoE01eEErF5+jGZl147TYWwFp591YhXcOJKoFuBLDm9dXBrDKLwVHXg/EOhqXL89PxAnaQUI0vcN4uEMqHsfZh4hG0KWrOxdjDf9ZY



Get Outlook for iOS<https://aka.ms/o0ukef>

--_000_DM5PR03MB335332A6770F1800F09824C9C2000DM5PR03MB3353namp_
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
X-Microsoft-Exchange-Diagnostics:
	1;DM5PR03MB3353;27:E269/Dm7kmpaYNNyoCor5TwXVzFufcHkuXX/+k0MoPdFQL7wZjTwRHdaboP4oRr5Z1TeKKa0trsCnECwRmAjRD2fhINSqTljyJqW9Q+uKQhIpKrkXvcOtsI22lmugQucXKtks4t6rfkzB0npWbkblg==
X-Microsoft-Antispam-Mailbox-Delivery:
	dkl:0;rwl:0;ex:0;auth:1;dest:I;ENG:(400001000128)(400125000095)(5062000261)(5061607266)(5061608174)(1004181)(4900095)(4920089)(6220004)(4950112)(4990090)(9110004);OFR:SpamFilterPass;
X-Message-Info:
	5vMbyqxGkdf4AQ5hYaEt2YOIrujbaDwg7BNiJljdGaUBF5j/t1mlKnd+lo6sgOP5iIUlT8J/q4gd76s6f1j1WqUTwqsLcLDUdItxHFIdm0sX6cO263UqmQW+CQS7slPPXhVfSY7c5Y75lHTaw5SquwJL6/6ngWhFEYNWqj4glUGvHwhOZZcirF+MjaWrTjEg8k86Fw+QvgGD/LBi2x/y9A==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0xO0Q9MTtHRD0xO1NDTD0tMQ==
X-Microsoft-Antispam-Message-Info:
	4qOGVNYj1RmAhdyMkg693oeC4UXQ1cLxWLDMQOzrC2UbrPiXx7A2Kd+hA06Dc+m3L1rtVmY0pEjI+eZ9dhFRNISwmVcWAqZW1e7ylfaENQAcaY5fBtfMRLPQATAj2pJ2a0QhM13xHMnomzaB+kI0GGdaKkgmFZ0iUokPxpsm/uH/w+TsYLykfoIXJeh5V/OLtpoMB/ulJ7N5akNYQMVRSebtYbIoE01eEErF5+jGZl147TYWwFp591YhXcOJKoFuBLDm9dXBrDKLwVHXg/EOhqXL89PxAnaQUI0vcN4uEMqHsfZh4hG0KWrOxdjDf9ZY

<html=
><head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dus-ascii"=
>
</head>
<body>
<div id=3D"compose-container" style=3D"direction: ltr" itemscope=3D"" itemt=
ype=3D"https://schema.org/EmailMessage">
<span itemprop=3D"creator" itemscope=3D"" itemtype=3D"https://schema.org/Or=
ganization"><span itemprop=3D"name" content=3D"Outlook Mobile for iOS"></sp=
an></span>
<div>
<div><br>
</div>
<div><br>
</div>
<div class=3D"acompli_signature">Get <a href=3D"https://aka.ms/o0ukef">Outl=
ook for iOS</a></div>
</div>
</div>
</body>
</html>

--_000_DM5PR03MB335332A6770F1800F09824C9C2000DM5PR03MB3353namp_--

**Comment by liuyxpp** [comment]
I want Markdown, LaTeX and other plain text format files being rendered in bright color theme while others in dark color theme. Also the font for text files should not be sans serif...

**Comment by klory** [comment]
Yeah, I agree, the markdown dark theme seems to be not clear for Italian and Bold, really want this color theme change according to file extension feature!

**Comment by sladeodark** [comment]
Same I use powershell and the posh theme but tomorrow night for all markdown. Can this be implemented?

**Comment by good-idea** [comment]
My use case is having a different them when I am working on `*.mock.*` files. These often look very similar to the files they are mocking, and I'd like to be made aware of when I'm working on one or the other. Switching themes for this would be ideal.

**Comment by CombeeMike** [comment]
Here's my use case:

Highlighting of currently active lines in diff view is only barely noticeable in the theme I'm using. See [this question](https://stackoverflow.com/questions/50522241/better-highlighting-for-current-selection-in-diff-viewer) on stack overflow for screenshot etc.

Therefore I'd only like to customize the parameters `editor.lineHighlightBorder` & maybe `editor.lineHighlightBackground` for the diffs view.

@brandonb927 mentioned

```
"[plaintext]": {
  "editor.fontSize": <num>,
}
```

Is there an equivalent of `plaintext` for the diffs view or is the diffs view not specified on its own? Also is this feature documented somewhere with all possible domains or types?

**Comment by jsaulou** [comment]
I've created an extension named "Theme By Language" that lets you change theme based on the current opened file language. This may be interesting for some of you.

https://marketplace.visualstudio.com/items?itemName=jsaulou.theme-by-language

**Comment by GlenPerkins** [comment]
The semantics of, say, CSS, Golang, a plain text file, JSON, and Markdown source are so utterly different that it would be a miracle if the highlighting I wanted for each all happened to coincide in the same theme. And even if they somehow did, if I changed my mind about anything ("hmm, I think I'd rather see plain text light instead of dark like code"), I'd be stuck. And even where the semantics are nearly the same and I DO want the same style, I have a theme that highlights Golang function names the way I want but uses a different style for JavaScript functions. 

The solution to all of these would be a mechanism for specifying different specialty themes for different file types rather than having only general-purpose-compromise themes. And over time, a smarter theme type might be developed that derived semantic/syntactic categories (for each file type separately) from a combo of language servers, linters, static type info, intellisense, etc. (but that's a different issue.)

**Comment by aeschli** [comment]
@jsaulou thanks for the great extension.

BTW, if you just want to change editor colors (but not all workspace colors), don't toggle `"workbench.colorTheme"` but modify the `"editor.tokenColorCustomizations"` setting. Here's an example to just change the HTML token colors:
```
   "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "text.html.basic comment",
                "settings": { "fontStyle": "italic", "foreground": "#657Bff" }
            },
            {
                "scope": "text.html.basic string",
                "settings": { "foreground": "#2AA198" }
            },
            {
                "scope": "text.html.basic string.regexp",
                "settings": { "foreground": "#D30102" }
            },
            {
                "scope": "text.html.basic constant.numeric",
                "settings": { "foreground": "#D33682" }
            },
            {
                "scope": "text.html.basic variable",
                "settings": { "foreground": "#268BD2" }
            },
            {
                "scope": "text.html.basic keyword",
                "settings": { "foreground": "#859900" }
            },
            {
                "scope": "text.html.basic storage",
                "settings": { "fontStyle": "bold", "foreground": "#93A1A1" }
            }
        ]
    }
```

**Comment by jsaulou** [comment]
Thanks @aeschli.

I don't think this is possible but is there an way to extract these rules from themes?
That would be really neat and avoid to change the whole appareance of the workbench.

**Comment by aeschli** [comment]
@jsaulou As a user, you can invoke the `Generate color theme from current settings` command and take the `tokenColors` sections.

**Comment by tortuosit** [comment]
I'd also love to:

- have a specific theme for specific file types
- disable breadcrumbs and tabs

Those functions do not work for file types. Maybe a difficult task?

Because: I need all the goodies for coding. But not for text files/ documentation. Also, I'd love to use VS Code as a default association for text files. My config for text files atm:

`   "[plaintext]": {
      "files.autoSave": "afterDelay",
      "editor.minimap.enabled": false,
      "editor.folding": false,
      "editor.renderControlCharacters": false,
      "editor.renderWhitespace": "none",
      "editor.fontFamily": "Consolas",
      "editor.fontSize": 26,
      "editor.wordWrap": "bounded",
      "editor.lineNumbers": "off",
      "editor.autoIndent": false,
      "editor.quickSuggestions": {
         "other": false,
         "comments": false,
         "strings": false
      },
   },`

**Comment by theSdev** [comment]
Is dropping +1s useful? If so here's mine: +1!

**Comment by erich5168** [comment]
I would suggest change by project instead of change by language.  So for example 

1. Java Spring Boot file extensions will have .java, .xml, .properties, .sql, .schema, yaml...etc.

2. Angular extension will includes .html, cscc, css, ts, js, json...etc.  

3. Flutter....

In my opinion, this could help people who are using VScode for multiple project type.

**Comment by MidiCoder** [comment]
Any update on this? I like to use the traditional Powershell ISE them when working in PS. But I cant get used to editing .JSON files when it is enabled. 

Therefore I would like to them to change to something of my choice when I open or create a json file. 

Thanks

**Comment by albertobissacco** [comment]
Any update on this??

**Comment by LucaRosaldi** [comment]
+1

**Comment by ndac-todoroki** [comment]
@jsaulou 's extension is great XD, but since I use several panes at a time, I want to have only that certain individual editor view themed.
In this case, when you use the `"editor.tokenColorCustomizations"` in file-type settings:

```jsonc
"[elixir]": {
    "editor.formatOnSave": true,
    "editor.tabSize": 2,

    // LIKE THIS
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "text.html.basic comment",
                "settings": { "fontStyle": "italic", "foreground": "#657Bff" }
            },
            {
                "scope": "text.html.basic string",
                "settings": { "foreground": "#2AA198" }
            },
            ...
            // maybe backgrounds too?
        ]
    }
},
```

If you could put that setting inside the language specific ones OF the __workspace settings__, it should be great!
Then the extension could be capable of dynamically setting this, I think?

**Comment by aamarks** [comment]
I think most of the use cases are covered already by individual token settings and workspace settings that already work. Pretty reasonable to just set the theme for the workspace you use for C+ files differently from the workspace for JS projects. 

It would be more obvious you can do that if the menu for `file : prefences : color theme` just opened the settings editor to workbench:color theme where most know you can select user or workspace instead of opening the Command drop-down. Much easier to cycle through various themes from the settings editor also.

**Comment by ndac-todoroki** [comment]
> I think most of the use cases are covered already by individual token settings and workspace settings that already work. Pretty reasonable to just set the theme for the workspace you use for C+ files differently from the workspace for JS projects.

I think many workspace includes several languages, especially Markdown. Many people in this thread are wanting to change color themes for markdown.

**Comment by aamarks** [comment]
You're right. While you can [change font](https://github.com/microsoft/vscode/issues/20652#issuecomment-391949295) and [some color](https://github.com/microsoft/vscode/issues/20652#issuecomment-409862378) for some differentiation in languages, you can't swap light/dark within the same workspace without an extension like [jsaulou's](https://marketplace.visualstudio.com/items?itemName=jsaulou.theme-by-language).

**Comment by liuyxpp** [comment]
Still waiting. I'd like Markdown/LaTeX and any other text based files to be rendered with LIGHT color scheme (I don't care the whole scheme, i.e. sidebar, menu, etc.), while using DARK color scheme for programming languages.

**Comment by LucaRosaldi** [comment]
Same thing here. I use dark color scheme for CSS and JS, light for
everything else.

**Comment by Code4SAFrankie** [comment]
```
            {
                "scope": "text.html.basic keyword",
                "settings": {"foreground": "#4a83f6"}
            },

```

is not working for me, the keywords stay green.

**Comment by aeschli** [comment]
@Code4SAFrankie Use the `Inspect Editor Tokens and Scopes` tool to see what the scope is at a certain location. I don't think the HTML grammar uses `keyword`. Also, it can be, that a more specific rule wins against our rule. The `Inspect Editor Tokens and Scopes` tool tells you what theme rule has won.

**Comment by Arthaclarius** [comment]
I like the approach of [Windows Terminal](https://github.com/microsoft/terminal), each profile have their own settings like schema and fonts.

**Comment by ncoughlin** [comment]
There is now a plugin for this:

https://marketplace.visualstudio.com/items?itemName=jsaulou.theme-by-language

**Comment by bugpowder** [comment]
> Ahh. But themes already theme more than just the editor. What would we do if two editors are open?

Split the UI theming from the editor (syntax/code) theming. If two editors are open, use the same "UI theme" but the appropriate per language syntax theme.

**Comment by RajvirSingh1313** [comment]
I think this issue is solved as @jsaulou created a great extension. I think @aeschli you should close this issue as there is an extension for that.

**Comment by igonro** [comment]
This issue shouldn't be closed because the @jsaulou extension does not solve the original problem. Some filetypes as `.ipynb` and `.py` use the same language (Python), so it is not possible to assign different themes for `.py` and `.ipynb` files.

**Comment by RajvirSingh1313** [comment]
> This issue shouldn't be closed because the @jsaulou extension does not solve the original problem. Some filetypes as `.ipynb` and `.py` use the same language (Python), so it is not possible to assign different themes for `.py` and `.ipynb` files.

I think you are right, but does that really matters at the end when coding? I am using jsaulou's extension and I only notice it sometimes as a programmer

**Comment by ZYinMD** [comment]
For anybody who's still following this issue: I now use different `fontFamily` / `fontSize` / `lineHeight` for different langauges. It's good enough for me, and the switch is much faster than switching the theme.

You could try adding something like this to your settings.json and see how to works:
```json
  "[plaintext]": {
    "editor.fontFamily": "sans-serif",
    "editor.fontSize": 22.3,
    "editor.lineHeight": 34,
  },
  "[markdown]": {
    "editor.fontFamily": "serif",
    "editor.fontSize": 19,
    "editor.lineHeight": 25
  },
```

**Comment by jsaulou** [comment]
I could add the possibility to associate a theme using either extension or language.
Themes defined by extension would probably have the higher priority as they are more specific.

Would this help?

**Comment by igonro** [comment]
> I could add the possibility to associate a theme using either extension or language.
> Themes defined by extension would probably have the higher priority as they are more specific.
> 
> Would this help?

Yes, that would be awesome!

**Comment by NatalieGates** [comment]
I would like to create a theme for files ending in `.ledger`

I have a nice theme I use for `.md` files that I would like to also use for `.ledger` files.

Is this possible?

**Comment by Gabriel-p** [comment]
I'm sorry but the extension [Theme by language](https://marketplace.visualstudio.com/items?itemName=jsaulou.theme-by-language) is absolutely not a fix for this issue as it changes the theme of the **entire** editor. For thos uf us who use several panels (I'm guessing most) this is slow and bad

**Comment by janosh** [comment]
A similar feature (which likely doesn't deserve its own issue considering that #28483 was closed with reference to here but which should be kept in mind when this is implemented) is the ability to set a different color theme for the markdown preview window. For example have the `.md` file dark themed on the left and its preview light themed on the right (to look more like a normal document). Useful e.g. to properly view plots with transparent background:

![Screen Shot 2022-02-06 at 14 41 28](https://user-images.githubusercontent.com/30958850/152686232-737a7b1c-757a-4136-8a8f-81eea0fc39bd.png)

**Comment by moseleyi** [comment]
I would also like such feature. For 75% of my files I have an Egoist One theme slightly tweaked using settings. But for specific file type (*.lookml) I want to install an extension that has tokens colours. However we have to specify a theme in the extension, which means it changes my whole editor.

**Comment by evdcush** [comment]
> [darekzak](https://github.com/darekzak) commented [on Feb 15, 2017](https://github.com/microsoft/vscode/issues/20652#issue-207804341)

This feature request was initially opened in Feb 2017, with lots of closed duplicate issues and references from other issues, and consistent comments and demand until today here.

**What's the status on this feature request?**

Is this feature on the vsc roadmap?

This inability to select per-syntax/filetype themes is one of major remaining shortcomings in vscode that keeps my development workflow split between different editors.

Some themes just have better syntax support for certain languages over others, and some languages just look better in other themes.

It would be ideal if vscode could have "syntax-specific" settings like Sublime Text does.

For example, I have a different `"color_scheme"` defined on each syntax here (markdown: [`bijan`](https://github.com/Colorsublime/Colorsublime-Themes/blob/master/themes/Bijan.tmTheme), java: [`hotdogstand`](https://github.com/Colorsublime/Colorsublime-Themes/blob/master/themes/HotDogStand.tmTheme), python: [`monokai`](https://github.com/Colorsublime/Colorsublime-Themes/blob/master/themes/Monokai.tmTheme)):

![KN8ShFC](https://user-images.githubusercontent.com/28853935/202881028-8761e6a1-3a0c-40f0-8698-28a958af416f.png)

You too can get that java theme simply by specifying in your `java.sublime-settings:`


```
// These settings override both User and Default settings for the Java syntax
{
    "color_scheme": "Packages/Colorsublime - Themes/HotDogStand.tmTheme",
}
```

**Comment by Triangle4** [comment]
What we need is something like this:
{
    "label": "Some Dark Theme",
    "uiTheme": "vs-dark",
    "path": 
    [
        "./themes/dark.editortheme.json",
        "./themes/dark.cs.json",
        "./themes/dark.js.json",
        "./themes/dark.html.json",
    ]
},

This is a muchly needed feature.
For both the OP's reason and for general organization when using the same editor theme with multiple syntax themes for various languages.

**Comment by ionut-botizan** [comment]
I'm a bit surprised that in 7 years, nobody mentioned the situation in which the per language theme would probably make the greatest difference and that is embedded languages.
The most common example in the past few years would be the CSS in JS syntax highlight, in which a different theme for the CSS code written as
```ts
export const button = css`
    border-radius: 4px;
    font-size: 14px;
`
``` 
would make it easier to differentiate between the two.

One example from a project I currently work on are Neo4J Cypher query strings. To make it easier to differentiate the queries from the surrounding code I had to manually apply different colors from the Twilight theme to the Cypher language tokens when the default theme was Monokai, as it has already been suggested in other posts here. However, doing that for multiple languages and keeping the settings in sync with the original theme the tokens were taken from is very cumbersome.

Note in the examples below how in the first screenshot the query has no specific highlight other than the default Monokai color for Typescript strings, then, in the second, highlight is enabled by an extension that tokenizes the string, but it's still pretty hard to follow as the Cypher tokens use the same colors as the Typescript tokens while in the last one the distinction between the two languages is clearly visible as Cypher uses a completely different color scheme than the surrounding Typescript code, which were applied through custom settings, like so
```json5
{
	// ...
	"[Monokai]": {
		"textMateRules": [
		{
			"name": "Cypher QL keywords",
			"scope": "keyword.control.clause.cypher",
			"settings": {
				"fontStyle": "bold",
				"foreground": "#82563D"
			}
		},
		{
			"name": "Cypher QL keywords",
			"scope": "source.cypher support.function",
			"settings": {
				"foreground": "#F9EE98"
			}
		},
	]
	// ...
}
``` 

1) No highlight:
![Screenshot 2023-03-24 at 16 08 22](https://user-images.githubusercontent.com/408501/227545382-c971cf1d-2073-43e6-99ef-cb1103365049.png)

2) Default highlight:
![Screenshot 2023-03-24 at 16 08 46](https://user-images.githubusercontent.com/408501/227545633-099f6395-460b-422a-90c5-51284004f0e5.png)

3) Custom highlight:
![Screenshot 2023-03-24 at 16 09 07](https://user-images.githubusercontent.com/408501/227546239-b351e56f-eccd-4b51-9432-bacf48cea03e.png)

**Comment by Samyak-Bumb** [comment]
Hey Guys work on this feature it's very useful & helpful

**Comment by chrisbward** [comment]
Would like to change the theme or colours for a specific file, to work as an ambient signifier for the particular domain I'm working within - more info on UX design of ambient signifiers here; https://boxesandarrows.com/ambient-signifiers/

**Comment by Saltallica** [comment]
Holy **** its been years. For the love of all that is holy, please allow different color backgrounds or syntax highlighting per editor window based on language.

**Comment by 7even7** [comment]
I'd also love to have this feature.
Main reason is the above mentioned differences between the themes depending on the language.
I work daily in terraform, yaml, python, markdown, sql and in multiple random languages like go, javascript etc. 
I haven't found a single theme to be great for all of the languages. There's always one language that isn't formatted as well as in some other theme. However there's a great theme for any single language mentioned.

**Comment by ZYinMD** [comment]
> I'd also love to have this feature. Main reason is the above mentioned differences between the themes depending on the language. I work daily in terraform, yaml, python, markdown, sql and in multiple random languages like go, javascript etc. I haven't found a single theme to be great for all of the languages. There's always one language that isn't formatted as well as in some other theme. However there's a great theme for any single language mentioned.

If you haven't, at least give each project a different theme using `.vscode/settings.json`.

**Comment by Harr-Fun-Maula** [comment]
Actually it would be better if we can set "themes" based on "file name" rather than extension.
Different color for Split window.
for example 
"[*_Model.js]" : {
tab.background:red,
}
"[*_Viewl.js]" : {
tab.background:green,
}

"[*_Controller.js]" : {
tab.background:yellow,
}

**Comment by liranc6** [comment]
Another year has gone...
I'm starting to think Microsoft is not going to solve it.

I totally agree with @darekzak 's excellent example:
{
  "*.js": "Monokai",
  "*.html": "Flatland Monokai"
}
And @janosh  makes a great point about wanting a different color theme for the markdown preview window. A dark theme on the left and a light one on the right would really make it feel more like a normal document.

# The Theme War: Microsoft’s Achilles' Heel

**Comment by samuel12sam** [comment]
I was also trying to do something like @darekzak was mentionning, but stumbled here and realized it's not a built-in feature...im surprised

**Comment by smturro2** [comment]
![Year 8](https://pbs.twimg.com/media/GBZyQ5ZbcAAfiE9.jpg)

Year 8. Classic Microsoft

**Comment by RobinMeow** [comment]
It would be really great to set a theme, based on files types. And the theme _(or should I say syntax highlighting + background?) _ should only apply to the files. 

The vscode theme itself should be decoupeled, so you could choose dark, light or custom themes w/e. 
Files should use the vscode theme as a fallback, if it has no defined theme for its filetype (or plain text display, if no theme configured)

I often have, typescript files open next to html files or scss files. 
And since I do full stack, I often do stuff in C# as well.

next up are configurations files, like yml, json _(I mean thats just javascript but, well..)_. 
dotfiles are a different matter, but not really important to me, since I dont spend alot of time in those e.g. .gitignore, or .editorconfig, .env, ... you get the idea

Of course the list only becomes longer, if you add shell/bash files and razor files etc..

Nevertheless, I dont think the disply of a file tab, should be strongly coupled to the vscode window. 

And even better it would be, if I could quickly switch between two themes (for a specificy file type) using the cmd palette. 
For example, consider im working alone, I prefer the Visual Studio Dark Theme für C#, but when pair-programming I might prefer to use a Riders-similar theme, to make it easier for the navigator.
