### ISSUE TITLE
Clicking on an output and using Up/Down arrows scrolls through cells of another notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#207547]
Have two or more notebooks open side by side
* Select a cell of notebook 1
* Set focus to an output of a cell in another notebook
    * Verify the new nb is selected (cell will be highlighted)
* Use up/down arrows
* Watch how cells in notebook 1  are highlighted instead of the nb that contains the output..

**Comment by DonJayamanne** [comment]
Should now be fixed.

**Comment by justschen** [comment]
@DonJayamanne I'm still seeing this in latest insiders:

https://github.com/microsoft/vscode/assets/54879025/e90fd68f-10ae-4437-b794-661dd58bc28f

**Comment by DonJayamanne** [comment]
Sorry, it needs to be a scrollable output.
E.g. ensure the output is large enough to be displayed in a scrollable container.
E.g. 
```python
for i in range(100):
    print(i)
```

**Comment by DonJayamanne** [comment]
Oops, i thought this was fixed.
