### ISSUE TITLE
All cursors should do the same thing when typing

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#20891]
- VSCode Version: 1.9.1
- OS Version: MacOs Sierra 10.12.3

Steps to Reproduce:

Select text and hit one of the **"**  , **'** or **`**
![bug](https://cloud.githubusercontent.com/assets/5599375/23105096/9cdcfb5e-f6d9-11e6-827f-60f5dd2197a9.gif)

**Comment by mjbvz** [comment]
This is fixed in [current insiders builds](https://code.visualstudio.com/insiders). Please give it a try and let me know if you notice an issues

**Comment by DavidBabel** [comment]
Not fixed : 

Tested on fresh code-insider install from your link : 

![brackets](https://cloud.githubusercontent.com/assets/5599375/23211211/3f216b38-f901-11e6-8c32-338d5ed12f82.gif)

The input are the following to reproduce : 

- CMD+D : select the word
- ' or " or `: encapsulate the text between quotes
- right arrow + right arrow + right arrow : to go after the text

Hope it helps

**Comment by mjbvz** [comment]
@DavidBabel I'm still unable to reproduce this using those steps. Do you have any extension installed? Can you try running code with `--disable-extensions` and also share your user settings.

Thanks

**Comment by DavidBabel** [comment]
I ran several tests and finally get the guilty.

Switch in french azerty keymap, the issue will appear.

**Comment by DavidBabel** [comment]
Actually, we may have found a very tricky point here.

I like vscode very much, but when i discuss with some of my french friends about vscode, i heard many times that the quote behaviour is strange. 
And he actually is !
I spend a lot of time removing extra added quotes on my code. It may be an issue of the french keyboard too. I will post a new issue if i'm able to show it with efficient examples next days.

**Comment by DavidBabel** [comment]
Here it is, here is a multi cursor example : 
![error](https://cloud.githubusercontent.com/assets/5599375/23264226/f0408cc0-f9e0-11e6-8bc5-3cfca4f01754.gif)

This is the thing is vscode that kill me the most

**Comment by mjbvz** [comment]
@alexandrudima and @rebornix: this does not seem specific to js or ts. I see the same behavior in a python file:

```python
'abc'
```

1. Select one of the `'`.
2. Hit cmd+D to create multi cursor
3. Delete the `'` and then type `'` again.

the result is:

```py
'abc''
```

**Comment by DavidBabel** [comment]
Want to cry each time i see this :(

**Comment by alexandrudima** [comment]
We should improve at least one important aspect of this:

Today, each cursor operates independently. That means each cursor decides what to do by itself. i.e. the 1st and 3rd cursors decide to overtype the backtick, while the 2nd and 4th cursors decide to surround the backtick.

All cursors should do the same thing.

**Comment by alexandrudima** [comment]
Even more steps:


Steps to Reproduce:

1. Select the first double quote
2. Select also the other double quote, by pressing ctrl+d
3. Replace the double quote with single quotes

![test](https://cloud.githubusercontent.com/assets/11980775/23510332/6a070e8a-ff59-11e6-8b21-c92e80c44da3.gif)

**Comment by brunoscopelliti** [comment]
Thank you @alexandrudima !

**Comment by pixieaka** [comment]
Are this solve this problem https://github.com/Microsoft/vscode/issues/21974

**Comment by jrieken** [comment]
verified that it now encloses the quotes in other quotes (single)
