### ISSUE TITLE
"Run Tests" explorer option does not discover tests before trying to run

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#212342]
If I open a Dart project, right-click on a folder in the explorer and then "Run Tests", I see:

![image](https://github.com/microsoft/vscode/assets/1078012/23861dd0-5270-4319-9ef6-e19d84ee13a0)

However if I open the test explorer tree first and then try again, everything works.

It appears that "Run Tests" from explorer does not trigger the `resolveHandler` to allow initial test discovery.

(@connor4312 I presume this is a bug and not intended?)

**Comment by DanTup** [comment]
@connor4312 even after I've shown the explorer tree and triggered discovery, it seems like "Run Tests" now works on the "tests" folder, but not on an individual test file (even though I've confirmed the URI for that file is being set when creating the test tree item).

Is there something else I need to do besides having the URI on the test file node?

**Comment by connor4312** [comment]
Does this reproduce on Insiders for you? It should be fixed with https://github.com/microsoft/vscode/issues/211338

**Comment by DanTup** [comment]
@connor4312 looks like that fix handles the second issue above (running the file now works), however the original issue above is still an issue - if I don't trigger discovery of the tests before using it, it reports no tests found.

**Comment by DanTup** [comment]
Fix works for me, thanks! :)

/verified
