### ISSUE TITLE
[Debugger] Adding a Watch expression sends 'evaluate' command twice

### ISSUE THREAD

**Issue by chuckries** [Microsoft/vscode#21524]
- VSCode Version: 
```
Version 1.9.1
Commit f9d0c687ff2ea7aabd85fb9a43129117c0ecf519
Date 2017-02-09T00:26:45.394Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
- OS Version:
Win 10

Steps to Reproduce:
I am using the C# extension to reproduce this, but it should be visible from any debug adapter.

1. Use the C# Extension to debug a .NET Core console app with the following code:
```cs
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            int i=1;
            i++;
        } // BP Here
    }
}
```
2. Turn on debugger logging by adding the following block to launch.json launch configuration:
```
            "logging": {
                "traceResponse": true
            }
```
3. Set a breakpoint on the line indicated and start debugging
4. View the debug console to see tracing output
5. Evaluate `i++` in the Watch area

Expected: `i++` shows 2 in the watch expression (it is post decrement so it should return 2)
Actual: `i++` shows 3 in the watch expression, because it is being evaluated twice

This is also shown in the debugger log output:
```
C evaluate: {"expression":"i++","frameId":1000,"context":"watch"}
 R: {"success":true,"message":null,"request_seq":12,"command":"evaluate","body":{"result":"2","variablesReference":0,"type":"int"},"running":false,"refs":null,"seq":0,"type":"response"}
C evaluate: {"expression":"i++","frameId":1000,"context":"watch"}
 R: {"success":true,"message":null,"request_seq":13,"command":"evaluate","body":{"result":"3","variablesReference":0,"type":"int"},"running":false,"refs":null,"seq":0,"type":"response"}
C variables: {"variablesReference":1000}
 R: {"success":true,"message":null,"request_seq":14,"command":"variables","body":{"variables":[{"name":"args [string[]]","value":"{string[0]}","type":"string[]","variablesReference":0,"evaluateName":"args"},{"name":"i [int]","value":"2","type":"int","variablesReference":0,"evaluateName":"i"}]},"running":false,"refs":null,"seq":0,"type":"response"}

```

**Comment by chuckries** [comment]
@weinand @isidorn

**Comment by weinand** [comment]
Yes, we should only do an evaluate on 'stop' and replace the one on 'continue' by some fixed status message.

**Comment by chuckries** [comment]
I want to be clear that I am not talking about evaluate being sent on stop or continue. If you are already stopped and type an expression into the 'watch' area, evaluate is sent twice immediately.

**Comment by isidorn** [comment]
I pushed a change that we only allow evaluation when stopped.
Unless it is a repl, in that case we allow evaluation all the time.

When I say do not allow I mean we show a fixed status message

fyi @roblourens

**Comment by roblourens** [comment]
Losing global watches is a little disappointing since other devtools support it, but I don't think there's a really compelling use case. Maybe in some runtime with global data, but since watches aren't actually "watching" the value as it changes (while not stepping), it might just be misleading.

If we do end up reenabling it, we need to be careful not to bring up #19841 again. I'm working around a V8 bug.

**Comment by chuckries** [comment]
https://github.com/Microsoft/vscode/commit/ed7a973363ca03a783ccd88326d53c9275f4753c does not fix the issue that I am reporting. Please reopen this issue. I tested against the latest insiders build which contains the proposed fix:
```
Version 1.11.0-insider
Commit 0bc62d1679fbb59a4bd8f62203743408893ba4ee
Date 2017-03-02T13:51:59.532Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

The issue I am seeing has nothing to do with repl or continuing the process.
My repro steps are:
1. Set a breakpoint in a source file.
2. Start debugging and run to breakpoint.
3. While stopped, add an expression to the Watch viewlet

Expected: The `evaluate` command is sent once with the expression typed into the watch viewlet
Actual: The `evaluate` command is immediately sent TWICE.

Log from our debug adapter:
```
<- (E) {"seq":24,"type":"event","event":"stopped","body":{"reason":"breakpoint","threadId":47424,"allThreadsStopped":true,"source":{"name":"Program.cs","path":"c:\\Users\\chuckr\\Source\\scratch\\Program.cs"},"line":10,"column":13}}
-> (C) {"command":"threads","type":"request","seq":9}
<- (R) {"seq":25,"type":"response","request_seq":9,"success":true,"command":"threads","message":"","body":{"threads":[{"id":47424,"name":"Main Thread"}]}}
-> (C) {"command":"stackTrace","arguments":{"threadId":47424,"startFrame":0,"levels":20},"type":"request","seq":10}
<- (R) {"seq":26,"type":"response","request_seq":10,"success":true,"command":"stackTrace","message":"","body":{"stackFrames":[{"id":1000,"name":"scratch.Program.Main(string[] args)","source":{"name":"Program.cs","path":"c:\\Users\\chuckr\\Source\\scratch\\Program.cs","sourceReference":0,"checksums":[{"algorithm":"SHA1","checksum":"5f4b3e494c8f26dbc82244e06dbe6f7baafd41d4"}]},"line":10,"column":13,"endLine":10,"endColumn":17,"moduleId":"{7AC61516-B686-4237-B297-5B3D381927E3}"},{"id":1001,"name":"[External Code]","line":0,"column":0}],"totalFrames":2}}
-> (C) {"command":"scopes","arguments":{"frameId":1000},"type":"request","seq":11}
<- (R) {"seq":27,"type":"response","request_seq":11,"success":true,"command":"scopes","message":"","body":{"scopes":[{"name":"Locals","variablesReference":1000,"expensive":false}]}}
-> (C) {"command":"variables","arguments":{"variablesReference":1000},"type":"request","seq":12}
<- (R) {"seq":28,"type":"response","request_seq":12,"success":true,"command":"variables","message":"","body":{"variables":[{"name":"args [string[]]","value":"{string[0]}","type":"string[]","evaluateName":"args","variablesReference":0},{"name":"i [int]","value":"0","type":"int","evaluateName":"i","variablesReference":0}]}}

At this point we are stopped and I type 'i++' in the watch viewlet. See how two 'evaluate; commands are sent followed by a 'variables' command. This is incorrect behavior. 

-> (C) {"command":"evaluate","arguments":{"expression":"i++","frameId":1000,"context":"watch"},"type":"request","seq":13}
<- (R) {"seq":30,"type":"response","request_seq":13,"success":true,"command":"evaluate","message":"","body":{"result":"0","variablesReference":0}}
-> (C) {"command":"evaluate","arguments":{"expression":"i++","frameId":1000,"context":"watch"},"type":"request","seq":14}
-> (C) {"command":"variables","arguments":{"variablesReference":1000},"type":"request","seq":15}
<- (R) {"seq":32,"type":"response","request_seq":14,"success":true,"command":"evaluate","message":"","body":{"result":"1","variablesReference":0}}
<- (R) {"seq":33,"type":"response","request_seq":15,"success":true,"command":"variables","message":"","body":{"variables":[{"name":"args [string[]]","value":"{string[0]}","type":"string[]","evaluateName":"args","variablesReference":0},{"name":"i [int]","value":"0","type":"int","evaluateName":"i","variablesReference":0}]}}
```

**Comment by weinand** [comment]
@isidorn I can reproduce.
Use a node program `var i = 0` and add a watch `console.log(i++)`.
On the debug console I get this:
```
0
1
```

**Comment by isidorn** [comment]
@chuckries nice catch
