### ISSUE TITLE
Settings deep-linking issues when extensions update

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode#223389]
Testing #223027

I'm not able to get this feature working on my linux host 😓  Attached a video for clarity.

https://github.com/user-attachments/assets/2afdd792-de8e-4773-aff2-88d0aa9fa4ed

# Repro steps

_Tested on Ubuntu 24.04_

1. Install and launch VS Code Insiders
1. Install Remote - SSH pre-release (or try with a different setting)
1. Open default browser in Ubuntu 22.04 (Firefox)
1. Paste in a deep link (eg: `vscode-insiders://settings/remote.SSH.permitPtyAllocation`)
  1. I also tried following a link on a mock website, source:
```html
<head><title>Title></title></head>
<body>
   <a href="vscode-insiders://settings/remote.SSH.permitPtyAllocation">CLICK ME</a>
</body>
``` 
1. Note that VS Code launches but we aren't deep linked into settings

These steps work successfully for me on my MacOS host

**Comment by joshspicer** [comment]
When I look at the issue reporter's "Include my system information" output, I can see hte `--open-url` in the processe's args, though I haven't gotten the setting UI to pop up. 

![Image](https://github.com/user-attachments/assets/a7e46529-02d7-463d-9fef-27f619c91f7d)

**Comment by alexr00** [comment]
I can't repro that it never works on Ubuntu, but I can repro that some settings work and some do not.

**Comment by alexr00** [comment]
It's not linux specific. The issue is that the collection of exsiting settings is cached, so if you install an extension that provides another setting after already opening a URL then we think the setting doesn't exist.

**Comment by alexr00** [comment]
To verify:
1. Open a URL as described in the TPI
2. Install an extension that contributes a setting
3. Open a URL for your new setting. Verify that the settings editor opens to the correct setting.
4. Open a URL with a made up setting. Verify that the settings editor shows, but doesn't try to filter to the fake setting.

**Comment by alexr00** [comment]
Great find btw. This also unearthed an event that is simply not fired anymore.

**Comment by andreamah** [comment]
@joshspicer could you verify that this has been fixed since you already have the environment configured? :)

**Comment by joshspicer** [comment]
Testing on insiders at commit 3b9aee0a96e6a812963418b08316c175e1386d16, still seeing a bit of odd behavior when the editor is completely closed.  cc/ @alexr00 

https://github.com/user-attachments/assets/401a1f90-5b49-483e-9d73-5404b1a816f2

**Comment by alexr00** [comment]
Here's what's happening:
- Extension contributes a setting in package.json.
- You click on a link to the setting that the extension contributes.
- VS Code starts and immediately checks to see if it knows about the setting from the link.
- It doesn't find the setting, so it just shows the settings editor.
- VS Code eventually finishes it's `Ready` phase and processes all the extension points, but it's too late at this point, we've already determined that the setting doesn't exist.

For reference later, here's where we process extension points:

https://github.com/microsoft/vscode/blob/059d46b7edf2f84aeb6d31a7f98bf6381058bc2f/src/vs/workbench/services/extensions/electron-sandbox/nativeExtensionService.ts#L136-L141

**Comment by joshspicer** [comment]
Working well for me now! I see the empty settings page first pop up, and a moment later the proper setting correctly fills in!
