### ISSUE TITLE
Embedded languages syntax highlighting stopped working in 1.92.0

### ISSUE THREAD

**Issue by staspiter** [microsoft/vscode#224978]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.92.0
- OS Version: Windows 10, macOS 14 Sonoma

I have been using the following two extensions a lot. Since 1.92.0 update both extensions stopped working meaning the embedded code in JS does not get highlighted inside of YAML anymore. Each extension basically does the same job for me, so I tried to switch from one to another before realizing that my VSCode got an update and this functionality stopped working in both extensions. I've also tried the insiders build and the problem is still there. When I downgraded to 1.91.1, the extensions worked perfectly. This happens on both Windows and Mac.

**The extensions are:**
1. Extended Embedded Languages - https://marketplace.visualstudio.com/items?itemName=ruschaaf.extended-embedded-languages
2. YAML Embedded Languages - https://marketplace.visualstudio.com/items?itemName=harrydowning.yaml-embedded-languages

**Steps to reproduce:**
1. Install VSCode 1.92.0 or the insiders build.
2. Install one of the above extensions.
3. Create a yaml file with the following content:
```
test: | #js
  console.log("hello world")
```
4. Make sure the js code gets highlighted correctly

This is how it looks like in 1.92.0
![image](https://github.com/user-attachments/assets/33542769-f0ae-4274-a452-59c5738e8a65)

1.91.1:
![image](https://github.com/user-attachments/assets/d7405324-f305-49f8-b9bf-eee56608fbf7)

**Comment by staspiter** [comment]
Installing this extension https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml helps as a workaround. I guess because it takes over the yaml grammar and completes it with what is expected by other extensions.

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/224862.

Should be fixed by https://github.com/microsoft/vscode/pull/224954 in the very latest insiders (from d4c4e690b9f1e70291da9a46c5c8ac5ebfbda81a) and will be fixed in the upcoming recovery release.

**Comment by RedCMD** [comment]
[`"block-scalar"`](https://github.com/RedCMD/YAML-Syntax-Highlighter/blob/204a40e110c8598f776ef599114947aa4f43a5bd/syntaxes/yaml-1.2.tmLanguage.json#L398) was taking precedence over injections because it was consuming the whitespace before it while the embedded language extensions were not

if I remove the `([\t ]*+)` part
it starts working
![image](https://github.com/user-attachments/assets/5adaf605-9a96-4df1-b2ac-52c482210fa5)

but it will still break down when inside a nested block-map
![image](https://github.com/user-attachments/assets/dc446a86-68d3-443e-a2a1-f04e3fc95dba)
this is because the other extensions use `^` instead of `(^|\\G)`
they will need to fix that part for themselves
[Extended Embedded Languages](https://github.com/ruschaaf/extended-embedded-languages/blob/c128e894612034954006ef0e221641ddfcd3a43c/utilities/syntax_templates/yaml_syntax.js#L29)
[YAML Embedded Languages](https://github.com/harrydowning/yaml-embedded-languages/blob/c8478003b71af928fae1496b9600c32bab9fe18e/syntaxes/injection.json#L181)

**Comment by RedCMD** [comment]
@alexr00 VSCode needs to pull the latest yaml commits to fix this
https://github.com/RedCMD/YAML-Syntax-Highlighter/commit/71a88711ec184b7dde5240c8f150ad3c2dbbd5f1

sorry, I was under the impression the changes had already gone through
but it seems I missed the pull update by a few hours? https://github.com/microsoft/vscode/pull/224954

**Comment by alexr00** [comment]
Re-using the old candidate here as this is a separate issue: https://github.com/microsoft/vscode/issues/224862

**Comment by RedCMD** [comment]
separate issue?
#224862 is already fixed tho?

@harrydowning has already pushed a temporary patch to his extension in the meantime https://github.com/harrydowning/vscode-yaml-embedded-languages/pull/45

**Comment by alexr00** [comment]
I'm seeing https://github.com/microsoft/vscode/issues/224862 still occur. I guess I can't say for certain whether it's a separate issue since https://github.com/microsoft/vscode/issues/224862 is still happening.

**Comment by RedCMD** [comment]
Fixed in the latest [version](https://github.com/RedCMD/YAML-Syntax-Highlighter/commit/c42cf86959ba238dc8a825bdd07bed6f5e97c978) of my [grammar](https://github.com/RedCMD/YAML-Syntax-Highlighter)
![Image](https://github.com/user-attachments/assets/06d2dd91-991b-466f-a0b7-99786788617a)

**Comment by alexr00** [comment]
Awesome, I'll try adopting https://github.com/RedCMD/YAML-Syntax-Highlighter again for the November milestone.

**Comment by alexr00** [comment]
@RedCMD I'm still seeing the original bug:

![Image](https://github.com/user-attachments/assets/59d98e2a-8f49-410b-a612-8235a84e4ce3)

**Comment by RedCMD** [comment]
@alexr00 that is highlighted correctly

![Image](https://github.com/user-attachments/assets/70dcf4af-dcd7-443f-9bd4-cf47b7bad25c)

**Comment by RedCMD** [comment]
if you think it is an issue
then a new report should be made

as #224862 has been fixed by me and by the mdx extension

**Comment by alexr00** [comment]
Thanks @RedCMD, I forgot to install the MDX extension 🤦‍♀️

I've gone through the issues, and they all no longer repro with your changes 🚀

**Comment by alexr00** [comment]
For using yaml as an embedded language in C++ with Extend Embedded Languages, I see the following:

![Image](https://github.com/user-attachments/assets/ca583c52-381a-4ec5-bd97-7509496f10c9)

The yaml scope doesn't escape outside of the string, but it also doesn't get any yaml scopes besides `source.yaml`.
