### ISSUE TITLE
Unable to revert execution count in metadata of NB Cell in diff view

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#225204]
* Create an nb
* Add a cell 
* Stage/commit
* Modify cell and execute it
* Now diff view should show changes to code as well as metadata
* Revert changes to metadata and notice that it does not work.

**Comment by DonJayamanne** [comment]
@rebornix I think this is because `execution count` though displaed in `metadata` section is technically  not part of the `cell metadata`
It is part of `cell execution` information, hence the edit operation doesn't work as expected.
Also found that the way the metadata is reverted might not be right, we just have the following instead of an edit operation
```typescript
modified.textModel.metadata = original.metadata;
```

Using edit operations will not work as `cell.metadata` doesn't include the execution count
```
		context.cell.mainDocumentTextModel.applyEdits([{
			editType: CellEditType.Metadata, index: modifiedCellIndex, metadata: original.metadata
		}], true, undefined, () => undefined, undefined, true);
```

**Not sure, still investigating**

**Comment by DonJayamanne** [comment]
I believe this is specific to Jupyter as execution order is part of metadata,
Updating execution count in metadata !== updating execution order in Cell

**Comment by DonJayamanne** [comment]
Should be fixed

**Comment by amunger** [comment]
after reverting the metadata, the diff view closes as if it was reverted.
But the notebook still shows the un-reverted execution count, and if I close and re-open the notebook, the new execution count shows up as a change again.

**Comment by DonJayamanne** [comment]
Might need changes in ipynb extension to detect changes to metadata and then change the execution order via the notebook execution API.

**Comment by DonJayamanne** [comment]
This will not be possible as
* Reverting Execution count in notebook UI requires changes to execution summary
* Changing execution summary requires a notebook controller, however in diff view we have no idea about controllers 
* Even if Jupyter extension had specific code to handle this, we wouldn't know if its in diff view, and we'd have to pre-reselect a controller manually  (hack), so we can change the execution summary..

I do not see any generic nor easy solution (specific solution) for Jupyter extension. 
Hence closing this as no-planned

**Comment by DonJayamanne** [comment]
Fixed
