### ISSUE TITLE
Zooming/increase editor font size with ctrl+wheel now makes the font wider/narrower without increasing vertically on certain increments

### ISSUE THREAD

**Issue by lionel-rowe** [microsoft/vscode#225364]
Previously, scrolling with the wheel gave expected behavior (font gets visibly wider _and taller_ on every increment and narrower _and shorter_ on every decrement).

Now, sometimes it only changes in the X dimension, not the Y dimension. The effect is really janky and not desirable (I want my font to remain more-or-less the same aspect ratio regardless of size). Demo:

![scroll-jank](https://github.com/user-attachments/assets/5cae001d-25eb-42fa-9d3d-b65a4307288a)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```
- OS Version: Win 11

Steps to Reproduce:

1. Enable setting `editor.mouseWheelZoom`
2. Place mouse cursor in editor pane
3. Zoom in/out with Ctrl+mouse wheel

Increasing manually with `editor.action.fontZoomIn` and `editor.action.fontZoomOut` continues to work as expected, i.e. doesn't suffer from this problem.

Changing `editor.mouseWheelScrollSensitivity` seems to do nothing (neither fixes the problem nor has any noticeable effect at all).

Not sure if relevant, but my mouse is a Logitech MX Master 3S, which has two mouse wheel modes, "free spin" and "ratchet". Both modes are affected by the problem though.

**Comment by xrstf** [comment]
This new zooming behaviour is so confusing and slooooow. Previously I could achieve significant, useful results from scrolling my mouse wheel once. Now with the new zoom levels, I have to scroll the mouse wheel 4 to 5 times to actually get a meaningful zoom change. But good thing I now have a gazillion subpixel steps in between :-(

Who ever wants to change the line spacing and kerning settings when _zooming_?

**Comment by eldarshamukhamedov** [comment]
@alexdima any updates on this? Remember a similar issue came up in a much older build like 1-2 years ago and was fixed as a bug.

**Comment by lionel-rowe** [comment]
Seems fixed for me as of

```
Version: 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
```

Anyone else still having this problem? If not can close this issue.

**Comment by eldarshamukhamedov** [comment]
@lionel-rowe still seeing issue on 1.93.0:

```
Version: 1.93.0 (Universal)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z (5 days ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by lionel-rowe** [comment]
> @lionel-rowe still seeing issue on 1.93.0

@eldarshamukhamedov yep, it's come back for me too. Looks like one of those sneaky issues that only sometimes occurs. One thing that's probably relevant — I use a dual-screen setup, and right now it's only affecting VS Code when the window is on my main monitor, not my laptop screen.
