### ISSUE TITLE
VSCode Mac adds incorrect extensions to new files on save

### ISSUE THREAD

**Issue by phosphoer** [microsoft/vscode#230988]
Type: <b>Bug</b>

When creating new files on MacOS through the save dialog in VSCode, an incorrect file extension will be appended the final file name if the "All Files" format is selected. 

For example, in a clean instance of VSCode, simply saving an empty new file with the name "Test.cs" results in a new file named "Test.cs.c". 

Similarly, an empty new file named "Test.shader" results in "Test.shader.sh". 

This only happens when "All Files" (the default option) is selected, which means that now you must manually select the extension you already typed in order to not get the wrong filename. 

This behavior is a regression, and does not repro on Windows builds of VSCode, where the entered filename is preserved exactly. 

VS Code version: Code 1.94.1 (Universal) (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|24.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id 02795710-4615-4282-8717-9abdbde1edce|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
gitlens|eam|15.6.0
vscode-diff|fab|2.1.2
csdevkit|ms-|1.11.14
csharp|ms-|2.50.25
vscode-dotnet-runtime|ms-|2.1.7
material-icon-theme|PKi|5.11.1
vscode-xml|red|0.27.1
code-stats-vscode|riu|1.0.18
vstuc|vis|1.0.4

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
9b8hh234:30694863
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1cf:31151524
5fd0e150:31146321

```

</details>

**Comment by bpasero** [comment]
If this is a confirmed regression, it would help to know which change caused it. We maintain a node.js based CLI tool  [`vscode-bisect`](https://github.com/microsoft/vscode-bisect) that automatically downloads and runs previous VS Code insiders and asks for each build if the issue reproduces. It takes up to 8 steps to find exactly the build that caused the regression.

**Steps:**
* install [node.js](https://nodejs.org/en/download) (if not yet done)
* `npx --yes @vscode/vscode-bisect@latest --releasedOnly`
* follow the instructions until you found the offending build (its fine to leave the commit empty)
* report back the commit range in this issue

Thanks!

**Comment by phosphoer** [comment]
I tried using the tool with the above command, and curiously was unable to find a build where the unwanted behavior does not repro. I've been using VSCode for quite a while on Mac and am quite positive that it did not used to behave like this, so I'm at a bit of a loss. I'm pretty certain it started happening in the last month or so, perhaps after the September or August update, but manually installing those builds still shows the same behavior for me. 

Either way, it does seem like incorrect behavior as it seems to arbitrarily pick an extension based on the filename I entered when I'd expect the "All Files" option to save the file with the exact filename provided.

**Comment by bpasero** [comment]
I can reproduce and reported as https://github.com/electron/electron/issues/44192

**Comment by yyaremenko** [comment]
@phosphoer @deepak1556 
I believe this ticket can be closed, as [the problem origin is in Sequoia 15.0](https://github.com/electron/electron/issues/44192#issuecomment-2407937770) and will is fixed in the next release, [Sequoia 15.1
](https://github.com/electron/electron/issues/44192#issuecomment-2409067488)

**Comment by lauri865** [comment]
I'm on Sequoia 15.1 now, and this problem still exists @bpasero.

**Comment by bpasero** [comment]
Yes, I can still reproduce in macOS 15.1 when trying a filename such as `Test.cs`

**Comment by phosphoer** [comment]
This appears to be fixed as of macOS 15.2!

**Comment by bpasero** [comment]
Confirmed ✅
