### ISSUE TITLE
Version 1.95 Chrome Freezes When Debugging with an breakpoint set in VS Code with ng test

### ISSUE THREAD

**Issue by iperfectfurius** [microsoft/vscode#232651]
Type: Bug

### Description
When using VS Code to debug a project with Chrome attached, Chrome completely freezes if a breakpoint is set in VS Code. In the Sources tab in Chrome's DevTools, "Debugger paused" appears, but Chrome becomes unresponsive. If I use the debugger keyword directly in the code instead, debugging works as expected.

### Steps to Reproduce

Run ng test on an Angular project.
Start a VS Code task to attach to Chrome’s JavaScript (for debugging).
Set a breakpoint in VS Code.
Observe that Chrome freezes completely when the breakpoint is setted, **not hitted**(need to refresh de page).

Observed Behavior
Chrome becomes entirely unresponsive when paused at the breakpoint set in VS Code. It only works correctly if the debugger keyword is used in the code.

If i remove the breakpoint and refresh the page will work normally.

Additional Information

* This issue persists across multiple versions of Chrome, Chrome Canary, and Chromium.
* Downgrading Chrome versions is the only workaround.
* No Karma configuration adjustments have resolved the issue.
* Reviewed all installed extensions and found none that should impact this behavior.
* Apparently i can debug the web but not the tests.
* No errores on Dev Tools.

### Karma config on chrome:

customLaunchers: {
      ChromeDebugging: {
        base: 'Chromium',
        flags: ['--remote-debugging-port=9222']
      }
    },
    reporters: ['progress', 'kjhtml'],
    autoWatch: true,
    browsers: ['ChromeDebugging']

### Launch task attach:

{
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Karma Chrome",
            "port": 9222,
            "webRoot": "${workspaceFolder}",
            "sourceMaps": true
          }

<details><summary>Extensions</summary>
<table>
  <thead>
    <tr>
      <th>Extension</th>
      <th>Version</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>angular.ng-template</td>
      <td>18.2.0</td>
    </tr>
    <tr>
      <td>bradlc.vscode-tailwindcss</td>
      <td>0.12.12</td>
    </tr>
    <tr>
      <td>dbaeumer.vscode-eslint</td>
      <td>3.0.10</td>
    </tr>
    <tr>
      <td>dsznajder.es7-react-js-snippets</td>
      <td>4.4.3</td>
    </tr>
    <tr>
      <td>eamodio.gitlens</td>
      <td>15.6.2</td>
    </tr>
    <tr>
      <td>formulahendry.auto-rename-tag</td>
      <td>0.1.10</td>
    </tr>
    <tr>
      <td>gruntfuggly.todo-tree</td>
      <td>0.0.226</td>
    </tr>
    <tr>
      <td>mechatroner.rainbow-csv</td>
      <td>3.12.0</td>
    </tr>
    <tr>
      <td>ms-vscode.js-debug-nightly</td>
      <td>2024.10.2117</td>
    </tr>
    <tr>
      <td>mutantdino.resourcemonitor</td>
      <td>1.0.7</td>
    </tr>
    <tr>
      <td>nrwl.angular-console</td>
      <td>18.29.1</td>
    </tr>
    <tr>
      <td>redhat.vscode-xml</td>
      <td>0.27.1</td>
    </tr>
    <tr>
      <td>ritwickdey.liveserver</td>
      <td>5.7.9</td>
    </tr>
    <tr>
      <td>syler.sass-indented</td>
      <td>1.8.31</td>
    </tr>
  </tbody>
</table>

</details> 
Is not working on any chrome version*.

Im using W10 Pro.

If i'm missing any information please let me know.

**Comment by alkstal** [comment]
I have the same issue that launching Chrome causes Chrome to freeze/never stop loading when a breakpoint is set anywhere in VS Code.
Without any breakpoints set in VS Code, launching Chrome works as normal.

This is what's output in the Debug Console,

```
Created TensorFlow Lite XNNPACK delegate for CPU.
[33626:63747:1031/071043.913755:ERROR:ffmpeg_common.cc(970)] Unsupported pixel format: -1
Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#58 is a dynamic-sized tensor).
```

Added the trace logs for the Chrome process.

[vscode-debugadapter-a1e6a441.json.gz](https://github.com/user-attachments/files/17582673/vscode-debugadapter-a1e6a441.json.gz)

**Comment by ccbosch** [comment]
Hello, I have the same issue when debugging (Launch) with Chrome/Edge a Vue3 typescript SPA application. I had to downgrade to 1.94.

**Comment by ashe0047** [comment]
Same issue here with Nextjs 14 on Vscode 1.95

**Comment by connor4312** [comment]
Thanks, this issue should be fixed in [js-debug-nightly](https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension) already. I'll present it as a candidate for a patch release as well.

**Comment by jeffpar** [comment]
Another (possible) side-effect of this bug is that if you terminate Edge using the debugger's "Stop" button (instead of closing the browser), then the next time you launch an Edge debug session, you'll get an annoying "Restore Pages" prompt from Edge, because it thinks it wasn't shut down properly.  Reverting to VSCode 1.94 eliminates that nuisance as well.

It may be a separate problem... I'm just guessing it's related.

**Comment by gkyildirim** [comment]
Is the fix included in the @id:ms-vscode.js-debug-nightly? I installed it and problem is still there.

**Comment by matt-wormley** [comment]
I'm also seeing this repro in js-debug-nightly

**Comment by connor4312** [comment]
Please collect a log file on nightly using these instructions if you still see this:


> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by adelaiglesia** [comment]
I'm also seeing this also in js-debug-nightly. The team was unable to work today.

**Comment by dse82** [comment]
Still witnessed this issue today using js-debug-nightly. @connor4312 I sent you my logs, thanks a lot for your commitment. Please mail me if I can provide you with anything else to support your efforts.

**Comment by connor4312** [comment]
Should be fixed in the just-published nightly

**Comment by gkyildirim** [comment]
I confirm this is working for me. Thanks!

**Comment by alkstal** [comment]
Trying it out in Code - Insiders
```
Version: 1.96.0-insider (Universal)
Commit: 231d37338a58ff22c223a7ed7d4c1e7142c513d2
Date: 2024-11-04T14:19:41.196Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0
```

Problem still exists. Having a breakpoint anywhere in the code when launching Chrome debugging causes Chrome to never stop loading.
Not having a breakpoint when launching works. Adding a breakpoint after launching and reloading Chrome triggers the same problem.

Trace:
[vscode-debugadapter-7d1eeb1e.json.gz](https://github.com/user-attachments/files/17629388/vscode-debugadapter-7d1eeb1e.json.gz)

**Comment by connor4312** [comment]
@alkstal see my previous comment https://github.com/microsoft/vscode/issues/232651#issuecomment-2450365808

**Comment by alkstal** [comment]
Sorry. I missunderstood "Should be fixed in the just-published nightly" and what nightly was in this context.

**Comment by OlivierPoitras** [comment]
@alkstal 

In VSCode, when you debug something running on nodejs or the sort, it uses a built-in extension named ms-vscode.js-debug (JavaScript Debugger). That extension follows the version of VSCode, and as of now, that is 1.95.1. The debugger bug was fixed in the nightly version of that debugger extension. Nightly is basically the latest dev build, they run a pipeline each day to deploy the latest code, often including various fixes that have not yet made it into the official release.

That being said, the bug should be fixed in official of VSCode 1.95.2 I believe.

Meanwhile, if you want the workaround fix using nightly, follow these steps:

1. Disable the VSCode extension "JavaScript Debugger" (ms-vscode.js-debug)
2. Install and enable the VSCode extension "JavaScript Debugger (Nightly)" (ms-vscode.js-debug-nightly)
3. Place a breakpoint
4. Run the code

Your breakpoints should now work.

**Comment by FraidChau** [comment]
> [@alkstal](https://github.com/alkstal)
> 
> In VSCode, when you debug something running on nodejs or the sort, it uses a built-in extension named ms-vscode.js-debug (JavaScript Debugger). That extension follows the version of VSCode, and as of now, that is 1.95.1. The debugger bug was fixed in the nightly version of that debugger extension. Nightly is basically the latest dev build, they run a pipeline each day to deploy the latest code, often including various fixes that have not yet made it into the official release.
> 
> That being said, the bug should be fixed in official of VSCode 1.95.2 I believe.
> 
> Meanwhile, if you want the workaround fix using nightly, follow these steps:
> 
> 1. Disable the VSCode extension "JavaScript Debugger" (ms-vscode.js-debug)
> 2. Install and enable the VSCode extension "JavaScript Debugger (Nightly)" (ms-vscode.js-debug-nightly)
> 3. Place a breakpoint
> 4. Run the code
> 
> Your breakpoints should now work.

Did not work for me, Chrome is still frezzing after installing Extension "JavaScript Debugger (Nightly)" in VSCode 1.95.1
In the meantime, I've deactivated _Update: Mode_ to _none_ in File > Preferences > Settings, and I've installed VSCode 1.94.2 (https://update.code.visualstudio.com/1.94.2/win32-x64-user/stable)
Debug is working again !

(I'll check for VSCode 1.95.2 in a couple of days)

**Comment by connor4312** [comment]
Verification steps:

1. Open [wasm.zip](https://github.com/user-attachments/files/17670168/wasm.zip)
2. Set a breakpoint in helloworld.cpp and _don't_ have the [DWARF extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.wasm-dwarf-debugging) installed. (disabling does not work, must **not be installed**) You won't actually hit this breakpoint, but having a breakpoint is necessary.
3. `npx serve` to serve on port 3000
4. Try starting and stopping debugging several times
    - On current stable, you will soon get stuck in a loading state (shows `NaN/NaN/` progress)
    - With the candidate, you should see "Hello world" logged correctly each time

**Comment by avenmore** [comment]
I had downgraded to 1.94 to get around this issue, so when I saw 1.95.2 was released with this problem apparently fixed, I upgraded again. I set a breakpoint and ran my application, but Chrome stopped at the same place and I couldn't continue. My setup is Vue/Vite, similar to [#232702](https://github.com/microsoft/vscode/issues/232702) in setup and result, so this issue is not fixed for me.

Version: 1.95.2 (user setup)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z (18 hrs ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by csunguray** [comment]
The same issue persists for me on version 1.95.2.

Version: 1.95.2 (user setup)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z (19 hrs ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by alkstal** [comment]
Can also confirm that the problem still remains for me in 1.95.2.

```
Version: 1.95.2 (Universal)
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0
```

For what it's worth, I am running a Nuxt 3 project.

Also instead of regular VS Code I've been using VS Code - Insiders with the nightly `js-debug` package on the side and there it works without issues. I don't know what the difference is between the two applications but that might also be interesting to know.

**Comment by StephaneBonilla** [comment]
Same Issue for me too. I just sent you to the email de logs

**Comment by OlivierPoitras** [comment]
Can confirm, the debugger issues persist on VSCode 1.95.2 using the built-in JavaScript Debugger. Using the Nightly debugger is still a viable workaround on my end.

**Comment by connor4312** [comment]
Folks hitting this on 1.95.2 should continue to use js-debug-nightly https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension
