### ISSUE TITLE
Support IME contextual conversion (pre- and post-conversion references)

### ISSUE THREAD

**Issue by Robot-Inventor** [microsoft/vscode#233641]
## Summary

This request is for Visual Studio Code to support the IME (Input Method Editor) feature known as "contextual conversion." This function, crucial for East Asian languages like Japanese and Chinese, enables IMEs to refer to surrounding text to suggest accurate conversions based on context, enhancing both accuracy and typing efficiency.

## Explanation and Benefits

IME contextual conversion allows the IME to use surrounding text (both before and after the input) to suggest the most accurate characters and words. For instance, when typing in Japanese, the IME can consider the entire sentence to provide correct kanji or hiragana suggestions. Currently, VS Code doesn’t provide this surrounding context, which limits the IME's predictive accuracy, often requiring manual corrections.

By supporting this feature:
- **Typing Accuracy Improves**: IMEs offer better suggestions based on context, reducing errors.
- **Enhanced Productivity**: Users can type faster with fewer interruptions.
- **Broader Accessibility**: VS Code becomes more user-friendly for non-Latin script languages.

Implementing this would likely involve integrating OS-level features, such as Windows’ `IMR_DOCUMENTFEED`, to share document context with the IME. For more information on implementing this feature in Windows, you may find the following articles helpful:

- **[IMEの前後参照変換機能に対応するには](https://topiyama.hatenadiary.org/entry/20070703/p1)**: This article provides an overview of how applications can support IME's contextual conversion by utilizing the `IMR_DOCUMENTFEED` notification code. 
- **[TextBox を IME 前後参照変換に対応させる (System.Windows.Forms)](https://wwwcfe.hatenablog.com/entry/20100512/textbox_imr_documentfeed)**: This post discusses implementing IME contextual conversion in a Windows Forms TextBox control, including sample code and explanations.

**Comment by tats-u** [comment]
VS Code is built on the top of Electron. Do Chromium and Electron support it?

**Comment by Robot-Inventor** [comment]
> Is this feature is implemented in other Electron-based apps?
> 
> Do text areas in web sites support it? If so, do Monaco or [vscode.dev](https://vscode.dev) do too?

Yes, Chrome’s textarea and Electron-based desktop clients such as Slack and Discord support it. Additionally, both Monaco and vscode.dev support the feature, but VS Code doesn't.

**Comment by tats-u** [comment]
I think this is kind of a bug if it is supported by vscode.dev.
However I don't think VSCode has C/C++ or C# code.

**Comment by tats-u** [comment]
Do any text fields or text areas other than the main code editor not support such an API?

**Comment by tats-u** [comment]
In the first place Electron shouldn't make apps care about it.

**Comment by tats-u** [comment]
VS Code has some weird IME-related bugs:

- https://github.com/microsoft/vscode/issues/181138
- https://github.com/microsoft/vscode/issues/238643

Do the textareas and input fields where the above bugs occur not support this IME contextual conversion either?

**Comment by Robot-Inventor** [comment]
I'm sorry for the late reply.

> Do the above bugs occur in text areas or input fields that does not support IME contextual conversion?

Upon reviewing the issue, it appears that contextual conversion is not supported in the same areas where the issue occurs—namely, the editor area, the settings search box, or the commit message input area. However, it is supported in the source code search box and the field for entering setting values.

It is important to note, though, that on vscode.dev, contextual conversion functions in all of these areas. Therefore, these issues may be related.

**Comment by Robot-Inventor** [comment]
I checked with the developer tools and it seems that the hidden textarea value is set correctly in vscode.dev where context conversion is supported, whereas in VS Code it is always an empty string. This may be the reason why the context conversion is not working.

vscode.dev:
![Image](https://github.com/user-attachments/assets/e58496f7-64d0-414b-aec2-6615a7c47aab)

VS Code:
![Image](https://github.com/user-attachments/assets/52985a59-b5c5-4e09-88e2-9b48b0fc22f8)

**Comment by Robot-Inventor** [comment]
I found that both contextual conversion and IME reconversion are available by pressing Alt + Shift + F1 to activate the screen reader optimized mode.


If the screen reader optimized mode is off:

https://github.com/user-attachments/assets/bc9f46d4-b8cb-4caa-8ac1-6ff680ec111c

If the screen reader optimized mode is on:

https://github.com/user-attachments/assets/bd3cd500-58b0-4536-9ac3-3b64e2bce5d7

![Image](https://github.com/user-attachments/assets/d51808b4-6e08-4ce8-ab24-9c4bef7274d4)

**Comment by tats-u** [comment]
Firefox seems to fully support the contextual conversion.
We don't have a way to test in WebKit, so the problem occurs only in Desktop (Electron).

**Comment by aiday-mar** [comment]
Hi first of all, may I ask you if you are using VS Code stable or VS Code Insiders? Next can you please test the issue with the setting `editor.experimentalEditContextEnabled` both enabled and disabled and let me know of your results?

**Comment by Robot-Inventor** [comment]
> Hi first of all, may I ask you if you are using VS Code stable or VS Code Insiders? Next can you please test the issue with the setting `editor.experimentalEditContextEnabled` both enabled and disabled and let me know of your results?

I am using the stable version of VS Code. After enabling `editor.experimentalEditContextEnabled`, the contextual conversion worked properly. Additionally, the IME reconversion feature mentioned in #181138 and #238643 also functioned when the flag was enabled. When the flag was disabled, neither of the features worked.

**Comment by aiday-mar** [comment]
Hi thanks a lot for letting me know. This setting will ultimately be enabled by default on stable, so it would seem this issue is already fixed.

**Comment by tats-u** [comment]
I opened https://insiders.vscode.dev/ to try to try the setting in Firefox, but it was not found.

バージョン: 1.98.0-insider
コミット: e20adc378e7bda18152984725c31d22cb4eaac17
日付: 2025-02-17T05:04:55.143Z
ブラウザー: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0

**Comment by tats-u** [comment]
`editor.experimentalEditContextEnabled` has been enabled when installing Insiders, and context conversion seems to be available, but only https://github.com/microsoft/vscode/issues/238643 has been fixed while https://github.com/microsoft/vscode/issues/181138 still has not completely.

**Comment by aiday-mar** [comment]
Hi thank you for letting me know. Is https://github.com/microsoft/vscode/issues/181138 not completely fixed because the issue still occurs on Firefox and vscode.dev? This is happening because the API we are using here https://developer.mozilla.org/en-US/docs/Web/API/EditContext_API is not yet available on Firefox, so we are still using the old approach on Firefox. When the API is made available we will turn on the EditContext there and the issue should be fixed at that moment.

**Comment by tats-u** [comment]
@Robot-Inventor Are you using ATOK? #181138 is not fixed for MS-IME or Google Japanese Input even in Desktop for WIndows.

https://github.com/microsoft/vscode/issues/181138#issuecomment-2665981297
https://github.com/microsoft/vscode/issues/181138#issuecomment-2665981297

@aiday-mar 

> the API we are using here https://developer.mozilla.org/en-US/docs/Web/API/EditContext_API is not yet available on Firefox, 

I see, but I think it is better to continue the discussion there instead of here.

> the issue still occurs on Firefox and vscode.dev

not only Firefox on insiders.vscode.dev but Insiders Desktop:

Version: 1.98.0-insider (user setup)
Commit: e20adc378e7bda18152984725c31d22cb4eaac17
Date: 2025-02-17T05:04:55.143Z
Electron: 34.1.0
ElectronBuildId: 10990655
Chromium: 132.0.6834.194
Node.js: 20.18.1
V8: 13.2.152.38-electron.0
OS: Windows_NT x64 10.0.26100

GoogleJapaneseInput-2.31.5712.100+24.11.9

**Comment by aiday-mar** [comment]
I see. Am I correct in understanding this specific issue #233641 is fixed with the setting, at least on the platforms that support the EditContext API? If yes, I will close this issue.

**Comment by tats-u** [comment]
I confirmed this issue occurs in Windows Desktop Insiders + MSFT-IME only when that flag is turned off. I think your understanding is correct.

**Comment by Robot-Inventor** [comment]
> @Robot-Inventor Are you using ATOK? #181138 is not fixed for MS-IME or Google Japanese Input even in Desktop for WIndows.

Yes, I'm using ATOK.

**Comment by tats-u** [comment]
I see. It's important information because ATOK is a paid production and we cannot perform a test on it without restrictions.

**Comment by aiday-mar** [comment]
I see thanks in that case I will close this issue as fixed with the setting. The setting will be turned on by default at some point.

**Comment by tats-u** [comment]
Google Japanese Input can recognize an *alphanumeric* preceding word according to https://github.com/google/mozc/blob/76343ffa704021a10ee6deec7d887d1c1e0f472b/docs/design_doc/surrounding_text.md, but I found it's not supported by VS Code Insiders in Chromium browsers or Desktop.

How to reproduce: https://github.com/google/mozc/discussions/1189#discussioncomment-12239360

**Comment by tats-u** [comment]
@aiday-mar I found Chrome/Edge themselves don't support contextual conversion in normal `<textarea>` and `<input>`. We should report this issue in issues.chromium.org. You can close this issue.

**Comment by tats-u** [comment]
Reported: https://issues.chromium.org/issues/417529154

**Comment by aiday-mar** [comment]
Hi thanks for letting me know and filing the issue.

**Comment by tats-u** [comment]
Eventually being to tried to be fixed on the Google IME's side: https://github.com/google/mozc/issues/1289
