### ISSUE TITLE
Flakey underline/hover tooltip behavior

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#23522]
Testing #23129

Not sure how else to describe it. Observations below:

### Repro 1
1. echo http://github.com from terminal
2. try hovering over output text
3. tooltip appears, but no underline

### Repro 2
1-3: Repro 1
4. hold ctrl
5. try hovering over output text
6. underline and tooltip appear, but clicking does nothing (because cmd is bound, not ctrl)

### Repro 3
1-3: Repro 1
4. hold cmd 
5. try hovering over output text
6. tooltip appears, but no underline, clicking works

### Repro 4
1-3: Repro 1
4. switch to another application
5. switch back to VS Code
6. try hovering over output text
7. both tooltip and underline appears

### Repro 5
1-3: Repro 1
4. echo https://github.com
5. try hovering over second output text
6. tooltip appears, but no underline
7. try hovering over first output text
8. neither underline nor tooltip appear

### Repro 6
1-8: Repro 5
9. switch over to another application 
10. switch back to VS Code
11. try hovering over first output text
12. underline appears, but no hover
13. try hovering over second output text
14. both hover and underline properly appear

--
- VSCode Version: Code - Insiders 1.11.0-insider (a35c7da7b8f324c1e8cc7830173418e392542f6d, 2017-03-28T12:40:24.966Z)
- OS Version: Darwin x64 16.4.0
- Extensions: none

**Comment by Tyriar** [comment]
- **Repro 1**: As designed
- **Repro 2**: Fixed in https://github.com/Microsoft/vscode/commit/55732e69e5861bac06e34c0101b1881028f2edf6
- **Repro 3**: Fixed in https://github.com/Microsoft/vscode/commit/55732e69e5861bac06e34c0101b1881028f2edf6
- **Repro 4**: This happened because cmd was held when leaving VS Code, I don't have a good idea for a fix now. Moved to https://github.com/Microsoft/vscode/issues/23621
- **Repro 5**: Duplicate https://github.com/Microsoft/vscode/issues/23484
- **Repro 6**: Combination of repro 4 and 5

**Comment by aeschli** [comment]
I verified on the Mac that Cmd over the link shows the link and a click opens it.
On Linux I still see strangeness. I first have to click on same line as the link before a link appears. Not sure if this has to do with my Linux in a VM setup.

**Comment by alexandrudima** [comment]
Trying to verify on Linux (bare-metal):

It mostly appears to work, except for a quirk that I think is due to how this is presumably implemented. I have the impression that the link highlighting code listens on keydown/keyup for CtrlKey instead of using mouseEvent.ctrlKey.

i.e. Here I press Ctrl+Alt+Tab. Once the focus goes into the other window, I release all keys. Notice how the links in the editor do not get highlighted in blue, while the links in the terminal get the underline. I think that the link implementation in the terminal must be trying to keep track of keydown/keyup of the CtrlKey. Maybe I'm wrong, I don't know:

![23522](https://cloud.githubusercontent.com/assets/5047891/24550554/dd9b2b5c-161e-11e7-9659-dc67168270c4.gif)

**Comment by Tyriar** [comment]
@alexandrudima you are right :smile: I was planning on reaching out to you to see how to handle it in the editor. So you just release on window blur? https://github.com/Microsoft/vscode/issues/23621

**Comment by alexandrudima** [comment]
@Tyriar :+1: `mouseEvent.ctrlKey` is easier to implement and appears to always be correct. Presumably Chromium queries the modifier state on each mouse move.
