### ISSUE TITLE
[scss] hide functions that don't match type

### ISSUE THREAD

**Issue by CedarDCX** [Microsoft/vscode#23576]
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file with an .scss file extension
2. Type "position: re" or "position: ab" to bring up intellisense suggestions
3. Default values of "red" and "abs" are not valid values for the position property

This is not an issue with .css files so seems to be an issue with .scss files.

**Comment by aeschli** [comment]
I pushed a fixed that adds more filtering. The remaining functions that don't return a specific type are sorted to the end.

**Comment by jrieken** [comment]
@aeschli I still see `abs`?

![screen shot 2017-04-26 at 10 47 51](https://cloud.githubusercontent.com/assets/1794099/25425919/d43d3114-2a6d-11e7-86cb-7b62fa0f2971.png)

**Comment by aeschli** [comment]
See my comment https://github.com/Microsoft/vscode/issues/23576#issuecomment-296256551
The fix was to sort functions to the end.
