### ISSUE TITLE
Cell toolbars are not correct on newly opened notebook

### ISSUE THREAD

**Issue by paul-rogers** [microsoft/vscode#236291]
Type: <b>Bug</b>

In a Jupyter notebook, toolbars are out of sync for some cells when the notebook is first opened.

### Case 1

Create a Jupyter notebook with Python as the back end. (I don't know if this bug is Python-specific, but Python is what I'm using.) You will get an empty Python cell "for free."

Hover the cursor above that cell. Click the "+ Markdown" button.

Notice that the toobar contains the Python buttons: "Run by Line", "Execute Above Cells", "Execute Cell and Below, "..." and the trash can.

Now, here is the fun part. Switch to another app window, then switch back. Voila! The buttons are  now the Markdown buttons: Check mark, "Split Cell", "..." and the trash can.

Once you've switched to another app window like this, the problem will not recur in that same notebook editor. To reproduce the following, you'll need
a setup so you can see these instructions _without_ switching windows.

### Case 2

Close the notebook you just created. Open it again. The Markdown cell will be active, only the "..." and trashcan buttons appear in the toolar. 

Switch app windows. The Markdown buttons appear.

### Case 3

Close the test notebook and open it again. Since you did not click the check mark on the Markdown cells, the reopened notebook should still have that cell in edit mode, so we'd expect the Mardown edit buttons.

Hover the cursor before your Python cell (you should only have a Markdown cell and a Python cell at this point.)

Click the "+ Markdown" button. Your new Markdown cell will have the Python cell buttons.

Again, switching windows brings up the proper Markdown buttons.

### Case 4

Close the notebook and reopen it again. Click on each of your three cells. You will get a toolbar with just the "..." and Toolbar buttons. 

This part gets weird. If you click from the bottom up, the bottom two
cells (Markdown at the bottom, Python in the middle) will have the generic buttons, but the top cell has the Markdown buttons. Sometimes all three cells have the generic buttons.

Now click around some more. At some point, you no longer get the generic buttons but instead start getting the proper buttons for the cell type.

Again, if you switch windows, you will always get the proper buttons after you switch back to your notebook.

### Case 5

One final case. Close your notebook and reopen it again.

Click in the last cell (Markdown) and type "something".

Click the checkmark to save the changes.

Hover the cursor below the Markdown cell. Click the "+ Markdown" button.

Notice that you get a new Markdown cell, in edit mode. You can type text. But the toolbar contains only the "..." and Trashcan icons.

Switch to another app window and back to VS Code. The toolbar now contains the check mark.

## Expected Behavior

It should go without saying, but the expected behavior is that the toolbar is consistent: I shouldn't have to switch app windows to get the proper toolbar.

The workaround is to either switch app windows, or click onto another cell and back again.

## Comment

It seems that something is off with the code that updates toolbars based on events. That code seems to be missing an event early on, but receives the correct event on loss of focus. Once whatever the problem is is adjusted once, that notebook stays in "working" mode thereafter.

## Details

Extension version: 1.0.17
VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:08:25.066Z)
OS version: Linux x64 5.15.0-101-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|31.31GB (7.80GB free)|
|Process Argv|--crash-reporter-id 5e232e7b-355a-468c-ac4a-02c300f898bd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by DonJayamanne** [comment]
Sorry for never getting back to you on this issue, somehow this slipped through the cracks.
We have made a lot of improvements and fixes in this space and believe this may have been resolved.
Please ensure you update to the latest version of VS code and the extensions.
Closing as I believe it may have been resolved,
If not please ping here and I'll reopen this or feel free to create a new issue.

**Comment by paul-rogers** [comment]
@DonJayamanne, thanks for the response. As it turns out, I am on the latest version of VS Code and extensions. The problem still occurs. Here is a image of a newly created Markdown cell just after clicking the "Markdown" button:

![Image](https://github.com/user-attachments/assets/d3c1f9ef-5398-4abf-90d3-e3e3acbafac9)

Here is the same cell after I switch windows or move to another cell within the same notebook:

![Image](https://github.com/user-attachments/assets/75c44a74-81f8-4054-89dd-7924668be70b)

Since the original report I have also updated to the newest version of Linux Mint, which likely updated various graphics-related components. Whatever the problem is, it seems to persist across VS Code and Linux Mint versions.

<details>
Version: 1.96.2
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
Date: 2024-12-19T10:22:47.216Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-51-generic

Jupyter extension version: 2024.11.0
</details>

**Comment by paul-rogers** [comment]
@DonJayamanne, thanks for your note. This still occurs. I can share a recording, however, the steps that I see are really quite simple as captured in the screen shots. For example, I just selected a random notebook, clicked `[+ Markdown]` between cells and got the first image from the above post. I clicked away to another cell, then clicked back and got the toolbar from the second image. At this point, the behavior is quite "reliable."

If you cannot reproduce, it may then be platform dependent. I am on Linux Mint, latest updates, latest VS Code. This Mint version uses Wayland for rendering, but the same behavior occurred under X.org in previous versions. There is nothing particularly unusual about my setup: stock Linux Mint with a few dev tools installed. My hardware is a latest gen AMD gaming motherboard, lots of RAM, integrated graphics; nothing unusual.

Unfortunately, I'm not familiar with the inner workings of VS Code or its foundations. However, if you can offer debugging hints, I can try to track down what's what. For example, is there some kind of logging that will trace the event chain that occurs when I click `[+ Markdown]` that will explain why the toolbar goes into the "reduced" state rather than the "markdown" state?

**Comment by paul-rogers** [comment]
@DonJayamanne, to help isolate, I just updated to the latest VS Code (see below). I deactivated all VS Code plugins except Python and Jupyter. I still see the bug with with a different presentation pattern. Now I see two versions of the "wrong" toolbar: the stunted one from the earlier comment, and this new variation:

<img width="839" height="127" alt="Image" src="https://github.com/user-attachments/assets/8f92e66c-020b-4699-860a-791a04b8f06c" />

The new behavior seems somewhat random.

Scenario 1:

* Leave a notebook as the visible window. Exit VS Code.
* Restart. Add Markdown, get above toolbar.
* Add a Markdown cell. I get the partial toolbar in the most-recent screenshot above.
* Add more Markdown cells. The "stunted" toolbar appears. (That is the one from the previous screen shot.)
* Add more Markdown cells. Now I get the "stunted" toolbar about half the time, the correct one the other half. (There seems to be no pattern: I'm clicking among the newly created Markdown cells.) After a while (another ten cells), the correct toolbar appears most of the time.

Scenario 2:

* Leave a notebook as the visible window. Exit VS Code.
* Restart. Add Markdown, get above toolbar.
* Add a Markdown cell. I get the partial toolbar in the most-recent screenshot above.
* Within a second, without me clicking anywhere else, the toolbar changes to the correct one.
* Add more Markdown cells. The stunted toolbar appears for the new ones.
* Add still more (after about 10 or so cells). The correct toolbar appears for the new ones.
* Click away to browser to edit this comment. Click back to VS Code and add more Markdown cells. The stunted toolbar appears for the first one or two new cells, then the correct toolbar appears thereafter.

Scenario 3:

* Leave a notebook as the visible window. Exit VS Code.
* Restart. Add Markdown, get above toolbar.
* Click on a Python cell. Add Markdown, get above toolbar.
* Add a second Markdown cell. Get the "stunted" toolbar.
* Click on a Python cell. Add Markdown, get above toolbar.
* Add more Markdown cells. Get the "stunted" toolbar.
* Continue to add. At some point the correct toolbar begins to appear. After that, new Markdown cells have the correct toolbar.

Scenario 4:

* Leave the many empty Markdown cells in the notebook.
* Leave a notebook as the visible window. Exit VS Code.
* Restart.
* Select all the empty Markdown cells and delete them using the trash can icon on the cell toolbar.
* Add new Markdown cells. Get the correct toolbar.

As you can see, the behavior is rather random with a few patterns visible here and there. To me, this seems to suggest "random initialization" of some state variable, but that's just a random guess.

Version info:

```text
Version: 1.107.0
Commit: 618725e67565b290ba4da6fe2d29f8fa1d4e3622
Date: 2025-12-10T07:43:47.883Z
Electron: 39.2.3
ElectronBuildId: 12895514
Chromium: 142.0.7444.175
Node.js: 22.21.1
V8: 14.2.231.21-electron.0
OS: Linux x64 6.8.0-87-generic
```
