### ISSUE TITLE
`end of central directory record signature not found` during extension install

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#2384]
Related to #69 

@joaomoreno
> To confirm @takuan-osho @JFLavidalle @vilinski: Do you get the end of central directory record signature not found error when you try to browse extensions or when you try to install an extension?

@takuan-osho
> @joaomoreno When trying to install an extension in my case.

@vilinski
> @joaomoreno me too, trying to install, browsing works always

@JFLavidalle
> @joaomoreno Browsing always works but installation failed.

Ping @maritz

**Comment by maritz** [comment]
Thanks!

Is there any way we can assist in debugging this? Can you replicate it somehow?

I face this problem while sitting behind a corporate proxy that requires a custom root cert to be installed.

**Comment by joaomoreno** [comment]
@maritz Just to confirm, did you try [this build](https://ticino.blob.core.windows.net/build/0e17d138ca2e7f5a342e049836a2b2b0beb54685/VSCode-win32.zip?st=2016-01-20T08%3A28%3A00Z&se=2016-01-26T08%3A28%3A00Z&sp=r&sv=2015-02-21&sr=b&sig=Xit%2Bxckw2%2BoMzH%2FNjkiBWOLzP5Th%2Ba21mE7hBTGEdYU%3D)?

**Comment by vilinski** [comment]
I'm also behind corporate proxy with authentication. It works at home, but no luck with installing any extensions on work PC. 
Couldn't download the linked build

**Comment by maritz** [comment]
@joaomoreno I have not. I would need a linux x64 build to test it, though.

**Comment by vizeke** [comment]
+1 same here. "end of central directory record signature not found"

Version 0.10.6

**Comment by joaomoreno** [comment]
Ok. We're in the middle of releasing 0.10.7. Please give it a try with that release and let's tackle it then if not fixed.

**Comment by vizeke** [comment]
It's working on 0.10.7-insider

**Comment by joaomoreno** [comment]
Excellent news. @takuan-osho @JFLavidalle @vilinski, maybe you guys can let us know if the issue's fixed for you as well?

**Comment by vilinski** [comment]
still no version update this week?

**Comment by egamma** [comment]
The plan is to push the next stable version 0.10.8 next Monday.

The insiders 0.10.7 version is already available, pls see https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/

**Comment by JFLavidalle** [comment]
@joaomoreno : I can confirm that the issue is fixed for me on release 0.10.7-insider.
Great news !

**Comment by joaomoreno** [comment]
OK, got confirmation from 2 people that it is fixed, so closing this.

**Comment by vilinski** [comment]
confirm working with stable and insiders builds. Finally can install extensions

**Comment by thoros1179** [comment]
For me the issue is **NOT** fixed. I tried 0.10.8 and 0.10.8 Insider.
"**end of central directory record signature not found**" still persists. I am behind corporate proxy.
I uninstalled previous versions of VS Code before installing.
What can I do to get around this issue?

**Comment by thoros1179** [comment]
I configured http.proxy and https.proxy. The extensions can be browsed but fail to install. I also tried http.proxyStrictSSL: false but it doesn´t change anything. The error persists.

![vscode](https://cloud.githubusercontent.com/assets/17291996/13107683/102754e8-d56f-11e5-9f4b-4c1cbf112631.png)

**Comment by joaomoreno** [comment]
What extension are you trying to install?

**Comment by thoros1179** [comment]
I tried different extensions, such as Go, Powershell (the first two shown when browsing with ext install), but also some Angular JavaScript and TypeScript Snippets extensions. None of them can be installed.

**Comment by joaomoreno** [comment]
Any chance I can use the same proxy you do?

**Comment by thoros1179** [comment]
I´m afraid this isn´t possible ;-) I will reconsider the issue with our proxy admin tomorrow. Maybe there is some other connection that is still blocked from our proxy. I will update you on the progress. Thank you.

**Comment by kikokikok** [comment]
Ok so now that I solved the first issue on the '#' illegal character in the declaration of the proxy + user & password url. I ended up with the 'end of central directory record signature not found' error.

I managed to track it down to the error in the DNS resolution of vortex.data.microsoft.com which is clearly blocked by our corporate proxy. for confidentiality reasons

**Comment by joaomoreno** [comment]
Awesome, great to know this @kikokikok.

@thoros1179 can you please check whether your proxy is also blocking `vortex.data.microsoft.com`?

**Comment by kikokikok** [comment]
One other thing that might be of interest is the fact that a lot of the resolutions have to be performed through the proxy any DNS resolution of external public domains from the internal are not allowed.

The proxy is doing the resolution silently. I didn't check the code but clearly seems like it might perform DNS resolution directly which might fail on corporate secured internal networks

**Comment by thoros1179** [comment]
According to our proxy admin "**microsoft.com**" is completely unblocked.

**Comment by joaomoreno** [comment]
@thoros1179 

The download URL Code tries to `GET` is, in the example case of the Go extension:

```
https://lukehoban.gallery.vsassets.io/_apis/public/gallery/publisher/lukehoban/extension/Go/0.6.27/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true
```

Can you get your proxy admin to look at whether that URL is blocked?

**Comment by thoros1179** [comment]
I checked the matter again with our proxy admin today. It turned out that the https certificate for vsassets.io is invalid. This is causing our proxy to refuse the connection (and yes, I am using http.proxyStrictSSL:false). You can see that in chrome when you surf to vsassets.io Chrome shows an striked out https-prefix in the addressbar because of the invalid certificate. The certificate provided by the website is targeted to "market.visualstudio.com" instead.
We set up our proxy to ignore the certificate for now, now it works for us, but maybe someone should look into this.

Thank you.

**Comment by joaomoreno** [comment]
Awesome, I will take that information to the people in charge. Many thanks for the patience!

**Comment by joaomoreno** [comment]
Actually, I can't confirm invalid certificate. On my machine, the certificate does appear to be valid and useful for the `*.vsassets.io` domain.

![screen shot 2016-02-19 at 16 40 34](https://cloud.githubusercontent.com/assets/22350/13180163/a7d5f1d2-d727-11e5-8134-84f794fa84d6.png)

**Comment by thoros1179** [comment]
If I just enter "vsassets.io" i get an invalid certificate. Right now I am at home so it´s no problem of our corporate proxy.

![vsassets](https://cloud.githubusercontent.com/assets/17291996/13181664/6fa89ee8-d72e-11e5-8a35-cee770a55d0c.png)

**Comment by joaomoreno** [comment]
Well, that's because the certificate is valid for `*.vsassets.io` and not `vsassets.io` itself. This is OK, since  Code never reaches onto the bare domain, but always to subdomains of it.

**Comment by thoros1179** [comment]
Ok, well I´m no expert in web things myself. I can only tell you what our proxy guy said. In fact it is working now that he told our proxy to ignore invalid certificates on vsassets.io or maybe .vsassets.io, I don´t know. Thank you for your help.

**Comment by joaomoreno** [comment]
:+1:

**Comment by AntouanK** [comment]
Getting that error on macOS 10.12.1 .
Visual Studio Code v 1.7.1

<img width="1019" alt="screen shot 2016-11-23 at 08 13 04" src="https://cloud.githubusercontent.com/assets/4569111/20554578/d6108820-b154-11e6-896e-f0ddd1ea6a86.png">

**Comment by churchs19** [comment]
I'm also seeing this behind a corporate proxy on all extensions as of today.

Version 1.8.0-insider (1.8.0-insider)
4721762a2ac1e21f1e33094e810d4888052f3d8d
2016-11-29T07:03:09.021Z

**Comment by errata-** [comment]
I am getting this issue when attempting to install extensions. I am behind a corporate proxy and have "http.proxyStrictSSL": false.

![vscode_version](https://cloud.githubusercontent.com/assets/10748779/21021542/91b2b87e-bd3e-11e6-9ed5-3ec9682ac4e5.PNG)


![vscodeissues_extensioninstallerror](https://cloud.githubusercontent.com/assets/10748779/21021360/bdfec4dc-bd3d-11e6-94c3-9077f1fed9bd.PNG)

**Comment by NathJoyce** [comment]
I'm also seeing the same issue, behind a corp proxy, on version 1.7.2 - this worked previously as I've downloaded extensions and I'm getting this error when trying to update the extension.

**Comment by joaomoreno** [comment]
Does it reproduce with [1.6.1](https://az764295.vo.msecnd.net/stable/9e4e44c19e393803e2b05fe2323cf4ed7e36880e/VSCode-win32-stable.zip)?

**Comment by NathJoyce** [comment]
Yes, I am seeing the same issue:

![1 6 1](https://cloud.githubusercontent.com/assets/23073151/21046881/b2e32ab8-bdfe-11e6-8955-33f632f4e284.PNG)

**Comment by NathJoyce** [comment]
Ignore this, it seems like it was an issue our end. Our "proxy guy" did some magic and it seems to be working. Thanks anyway.

**Comment by errata-** [comment]
@joaomoreno Using 1.6 it works perfectly. I was able to update my F# and C/C++ extensions without any issues. Attached is the proof.
![vs_code_161_extensionswork](https://cloud.githubusercontent.com/assets/10748779/21055057/93c009b6-bdf5-11e6-989b-385691129d95.PNG)
![vs_code_161_version](https://cloud.githubusercontent.com/assets/10748779/21055058/93c04c00-bdf5-11e6-8376-d5b88bd217c6.PNG)

**Comment by errata-** [comment]
@joaomoreno However, when I run the full installer from the website, it begins to fail again. I will try blowing away the whole directory and doing a fresh install. When I ran it from the attached zip, it ran fine. I'll keep you posted.
![vscode_161_fulliinstall_fail](https://cloud.githubusercontent.com/assets/10748779/21055896/f290cc20-bdf8-11e6-8432-7347cf2184e8.PNG)

**Comment by errata-** [comment]
@joaomoreno And now the zip you sent me isn't working, but it was. ¯\_(ツ)_/¯

**Comment by errata-** [comment]
@joaomoreno So it looks like it isn't version specific, but package specific. I tried different extensions (some lesser used ones) and the extensions installed fine. I think there is either archive corruption repo side or there is something wrong with they way the extensions are being decompressed. Some of the more frequently used extensions seem to fail pretty reliably. Attached is the proof. The first one fails because I try to install the most popular Python extension. The other ones succeed, including the second most popular python extension. The successful extension installs seem to have less hits/downloads. Hope that helps. 
![vscode161_python](https://cloud.githubusercontent.com/assets/10748779/21056744/893e6f94-bdfc-11e6-9132-891591276e0a.PNG)
![vs161_lisp](https://cloud.githubusercontent.com/assets/10748779/21056743/893e4294-bdfc-11e6-836e-ca77bc82771d.PNG)
![vs161_extension_successful](https://cloud.githubusercontent.com/assets/10748779/21056745/894000a2-bdfc-11e6-8f4b-8391287e972d.PNG)

**Comment by joaomoreno** [comment]
So strange. Are you behind a _bad_ internet connection?

**Comment by errata-** [comment]
@joaomoreno Not sure if you're referring to me, but I am on my corporate internet. There is a proxy and a firewall along with a virus called McAfee Antivirus installed on every computer. I will check my setup at the house tonight and see if I get the same issues. It's just weird because it seems like it only affects certain packages that are the most popular. I can download all of the less popular packages pretty easily.

I did some research previously and electron and atom have a similar error but different circumstances. The error, as far as I know, is related to a failure in the archiving process according to ubuntu's forums. Their workaround was to blow away the npm cache and remove .electron and .atom: [https://github.com/electron-userland/electron-prebuilt/issues/69]

Not sure if it is an inherited issue from electron... but figured I'd mention it.

**Comment by joaomoreno** [comment]
Cool, let me know how the experiment at home goes.

**Comment by ghuiii** [comment]
> end of central directory record signature not found vs code

Is there to figure it out?

**Comment by AntouanK** [comment]
FWIW, updating to 1.8 solved it for me.

**Comment by joaomoreno** [comment]
@AntouanK So it worked, and then stopped working, in the same version? That sounds like your network started blocking those requests. Any chance you can reach the network administrator and whitelist some domains?

**Comment by ghuiii** [comment]
It worked for me, because of the wrong http proxy config in my Setting!

**Comment by AntouanK** [comment]
@joaomoreno Why would you assume it's the network? As far as I see it has nothing to do with that.
Like I said before, I use a VPN, and I also get the problem with my home connection.
No firewall, no proxy or anything like that.

Like I said, it updated the extensions once I updated the app, and then one I tried to install a new extension, I got the same error again.
Network seems to be irrelevant.

Is there a console where we can see any errors in the VS Code runtime?

PS right now I'm on my mobile phone connection, and it fails again. It cannot be a network issue.

**Comment by joaomoreno** [comment]
My assumption comes from the fact that sometimes it works, sometimes it doesn't. It's always the same code, so something else must be changing.

You can open the Developer Tools (<kbd>F1</kbd>, `Developer tools`) to see if anything comes up there.

**Comment by AntouanK** [comment]
@joaomoreno But error remains on different networks. And like I said, it's home connections, nothing preventing an update.

Interesting. 
I got another extension to update just now. Update went through just fine.
Immediately I tried to install another extension, error cam up again once it finished downloading.
Here's the error in the console
```
workbench.main.js:94 
end of central directory record signature not found: Error: end of central directory record signature not found,    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/yauzl/index.js:98:14,    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/yauzl/index.js:342:5,    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/fd-slicer/index.js:32:7,    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)
```

**Comment by joaomoreno** [comment]
Do you have an antivirus installed? Some Internet security software?

**Comment by AntouanK** [comment]
No.

**Comment by AntouanK** [comment]
Can you give me some curl command, to verify it's not a network issue?

**Comment by Neutrino-Sunset** [comment]
Win7 x64, behind what I think is a socks 5 proxy with websense certificate. Clean install of 1.8 with 

```
    "http.proxy": "http://194.70.42.240:8080",
    "http.proxyStrictSSL": false
```

in c:\users\<username>appdata\roaming\code\user\settings.json
Getting 'end of central directory record signature not found' trying to install extension.

Uninstalled and tried 1.6 standalone posted earlier.

Browsing extensions initialially resulted in 'Server returned 403'. Added username and password to http.proxy config then it seemed to work. Downloaded the 'C# for Visual Studio Code' extension, appears to work, (C# source file is now highlighted). 

Checking the log though shows

```
Starting OmniSharp server at 16/12/2016, 15:03:07
    Target: c:\_Home\Development\Workspaces\Web\AspNetCoreTesting\HelloWorld

OmniSharp server started
    Path: C:\Users\mfreeman\.vscode\extensions\ms-vscode.csharp-1.5.3\bin\omnisharp\OmniSharp.exe
    PID: 328676

The system cannot find the path specified.
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

cntlm install insists that the proxy is non-authenticating and that I don't need it. I don't know what's going on. I have a similar issue with the Atom text editor, yet in my standalone node.js install npm works fine with a simple proxy config.

**Comment by Neutrino-Sunset** [comment]
In 1.8 adding username and password to the proxy config results in a warning String does not match the pattern of "^https?://([^:]*(:[^@]*)?@)?([^:]+)(:\d+)?/?$|^$"

**Comment by Neutrino-Sunset** [comment]
In 1.6 after installing the 'C# for Visual Studio Code' extension, then reloading to active it, in the output windows I see

```
Updating C# dependencies...
Platform: win32, x86_64 (win7-x64)

Downloading package 'OmniSharp (.NET 4.6 / x64)' Failed at stage: downloadPackages
Error: connect ETIMEDOUT 13.88.145.72:443

Finished
[ERROR]: C# Extension failed to install the debugger package
```

**Comment by errata-** [comment]
@joaomoreno It works at home. I guess the corporate network has trust issues with vs code and are corrupting packages. I am still not sure why it works on some packages and not others. If it is a corporate proxy/network issue, I would expect the failure rate to be somewhat deterministic. I will write up a ticket with ITSupport here and see if I can dig deeper into the issue.

**Comment by rchiav** [comment]
Same issue. I was just installing this at work and considering moving over from Sublime and ran into this issue. 

![image](https://cloud.githubusercontent.com/assets/1301606/21296872/79131270-c543-11e6-8e37-b012b54dbd35.png)

Behind a corporate proxy but I'm able to configure npm with the same proxy just fine. Every other Microsoft app uses the IE settings and works just fine too. Also successfully used vagrant and docker and pull images through the proxy.

**Comment by odulkanberoglu** [comment]
Same issue behind corporate proxy. Tried out with both 1.8.1 and 1.9.0-insider.

**Comment by ivanatpr** [comment]
Also experiencing this issue behind a transparent corporate proxy while trying to install the python extension on both 1.8.1 and 1.9.0-insider. About a month ago I was able to successfully install the same extension on a different computer, so I know it used to work.

I have "http.proxyStrictSSL" set to false in my settings and no other http/proxy settings specified.

I noticed that the vsix file seems to download successfully into my temp folder. Renaming it to add the vsix extension and running "Install from VSIX" produces the same error.

I've successfully installed the XML Tools(DotJoshJohnson.xml) and AutoHotKey extensions, so the problem is definitely specific to certain extensions.

**Comment by danorr** [comment]
Finally managed to get around this issue (running 1.7 on one machine, 1.8 on another) by including username and password in the url:
`{ "http.proxy": "https://username:password@proxyaddress:port", "http.proxyStrictSSL": false }`

Hope this helps.

**Comment by backpacked** [comment]
Adding the username and password worked for me too but really a bad idea. I don't want any file to contain a clear text password.

**Comment by danorr** [comment]
Agree, but was one thing that worked so stopped looking for a solution. Do have cntlm running through the organization's proxy which hashes (?) the passwords but for some reason wasn't going through. Let me know if you find a non-plaintext-passwpord solution!

**Comment by vilinski** [comment]
@backpacked the "http.proxy" setting by default takes the value from %http_proxy% environment variable

**Comment by jithurjacob** [comment]
![image](https://cloud.githubusercontent.com/assets/7101452/22641532/185e43da-ec7d-11e6-9fde-c63660e97ed6.png)

same issue in code 1.9 behind a corporate firewall with http.proxyStrictSSL set as false

**Comment by kikijhu** [comment]
This issue stills happened on 1.10.

**Comment by jithurjacob** [comment]
Same issue in Insiders 1.11 as well

**Comment by CodeFreezr** [comment]
Same issue here: 
![image](https://cloud.githubusercontent.com/assets/966869/24404297/28f27156-13c1-11e7-8fdb-f7e7c2937eb0.png)

Our setting for the Company-Proxy works fine with npm, Download via browser with deeper URL works, probably becaus of URL-Redirection. But navigating to https://vsassets.io/ brings up this error:

![image](https://cloud.githubusercontent.com/assets/966869/24404529/25dedcf6-13c2-11e7-88ce-9ba3f023f685.png)
  
As I read it is possible to work-a-round this in the company proxy setting through ignoring this SSL-Error. But this is only a work-a-round. Can you please streamline the download URL with SSL-Key URL so this glitch is solved at the root cause? While this is not solved, can you offer an VSIX Link direct at the Plugin-Page?

**Comment by GrafRaf** [comment]
Have some error behind proxy (on try install or update packages)
![image](https://cloud.githubusercontent.com/assets/1357087/26232888/8f2f0548-3c83-11e7-800e-d47d5b277d7c.png)
VS code version
![image](https://cloud.githubusercontent.com/assets/1357087/26232894/a0783c16-3c83-11e7-8b7b-873eaa1e9ff1.png)

as a workaround - download packges and install offline from .vsix (as described [here](http://stackoverflow.com/questions/37071388/how-to-install-vscode-extensions-offline)  )

**Comment by backpacked** [comment]
I got the latest 1.12.x and the proxy works without flaw, even when using AD authentication. I can download the extensions without any issues now.

Good job!

**Comment by GrafRaf** [comment]
Install v 1.12,2 and all works fine
thnx!

**Comment by abhaydhar** [comment]
Thanks ! Same issue on Corp firewall resolved with the latest update.

**Comment by jphellemons** [comment]
Same version as @rolurq  when trying to update python 0.6.5 to 0.6.7

**Comment by rolurq** [comment]
Updated to 1.14.0, having the same issue.

**Comment by angelia-yuqi** [comment]
updated to 1.14.2, I have the same issue. proxy setting is: 
"http.proxy": "http://10.198.157.119:9400",
 "http.proxyStrictSSL": false,

**Comment by mninja** [comment]
This may be due to corrupt local files. I wasn't able to install certain extensions but deleting `~/.config/Code/Cache`, `~/.config/Code/CachedData` and `~/.config/Code/Local Storage` fixed it (not sure which of the specific paths is responsible, I cleared all of them)

**Comment by komuW** [comment]
@mninja thanks. that fixed it for me.

**Comment by rolurq** [comment]
upgrading to 1.15.1 fixed my issue

**Comment by AlexVFornazieri** [comment]
I'm still having this issue here, even after upgrading to version 1.15.1 :(

OS: Ubuntu 16.04 LST

Version 1.15.1
Commit 41abd21afdf7424c89319ee7cb0445cc6f376959
Date 2017-08-16T17: 16: 27.618Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64

**Comment by nubunto** [comment]
Having issues in 1.16 right now. No corporate proxy whatsoever.

OS: Ubuntu 16.04 LTS
Version 1.16.0
Commit 787b31c0474e6165390b5a5989c9619e3e16f953
Date 2017-09-06T16:19:37.192Z
Shell 1.7.3
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by madyasiwi** [comment]
Same issue here for some extensions on a freshly installed Ubuntu 16.04. No proxy. And unfortunately @mninja's solution does not work for me. Tried `VS Code Insiders` version, doesn't help. Most other extensions can be installed without problem.

![extension-install-error](https://user-images.githubusercontent.com/7886819/30465222-6885e898-9a08-11e7-97a3-881bc7e42613.png)

**Comment by kwaazaar** [comment]
Same on Windows 10, but only when I try to install the extension 'solidity' (0.0.29). Other extensions work fine. The extension itself seems to be fine as well, since nobody reported this error in that Github repo.

I'm not using proxies, whatever.

**Comment by ipsusila** [comment]
I'm also facing the same issue with newest VSCode version (1.16.1), no Proxy. I'm agree with @mninja, perhaps due to **corruption of local/downloaded extension package** (may be due to slow connection, behind proxy, etc...). Clearing the cache will work, *or*, in my case, I manually download the extension from https://marketplace.visualstudio.com/, then install the `.vsix` by `Extensions: Install from VSIX...` command.

![Install from VSIX](https://user-images.githubusercontent.com/7299266/30779936-f97cfaea-a128-11e7-8022-af27752eded4.png)

**Comment by inuiau** [comment]
i'm having this issue too, i just download and install vscode but, when i try to install python extension i can't, but working fine for other extension
![ddd](https://user-images.githubusercontent.com/28834831/30785565-c6bc67ca-a192-11e7-8c84-a2cb1dd42cae.png)

**Comment by henriquebremenkanp** [comment]
As @mninja suggested it works.
The path for macOS is `~/Library/Application Support/Code` or `~/Library/Application Support/Code - Insiders`

**Comment by ipsusila** [comment]
@inuiau My issue was exactly the same. I solved it by manually download the python extension from https://marketplace.visualstudio.com/items?itemName=donjayamanne.python, then install it from local file. See my previous comment.

**Comment by madyasiwi** [comment]
And here is the documentation on how to download extension package manually:
https://code.visualstudio.com/docs/editor/extension-gallery#_common-questions

For example:
https://donjayamanne.gallery.vsassets.io/_apis/public/gallery/publisher/donjayamanne/extension/python/0.7.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

Then just rename the package extension ('VSIXPackage' in this case) to 'vsix'.
