### ISSUE TITLE
File Word Wrap disabled as soon as you leave the tab

### ISSUE THREAD

**Issue by accidentaldeveloper** [Microsoft/vscode#23869]
- VSCode Version: Code 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331, 2017-03-08T14:02:52.799Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.2.8|
|EditorConfig|EditorConfig|0.6.2|
|csharp|ms-vscode|1.8.1|
|PowerShell|ms-vscode|0.11.0|
|quokka-vscode|WallabyJs|1.0.20|;

---

Steps to Reproduce:

1. Open a text document with long lines of text, requiring word wrap
1. Turn on Word Wrap
1. Open another document (new or existing) in another tab
1. Return to the original document

Expected: Word Wrap is still enabled on the original document
Actual: Word Wrap is disabled on the original document

I have also attempted this with all extensions disabled and receive the same result.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by chrmarti** [comment]
Reproduced in 1.10.2 and the latest insiders.

**Comment by alexandrudima** [comment]
I think I fixed this in the meantime. e.g.: 
![23869](https://cloud.githubusercontent.com/assets/5047891/26648280/3f88086e-4642-11e7-919f-60f4326abd09.gif)

**Comment by pascalberger** [comment]
@alexandrudima @bpasero I still have the behavior described in this issue with the recent 1.13.0 verson (on Windows). Any settings having an impact on this?
