### ISSUE TITLE
Typing while edit changes are shown resets cursor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#239301]
* make edits
* before accept/discard tweak the changes
* :bug: after each change the cursor is reset

**Comment by eleanorjboyd** [comment]
Not sure if this is merged yet but I am seeing very jumpy behavior everywhere when I try and type in my files while edit suggestions exist. Every time you see a jump of the screen I just try and type a character (tab, space, a letter) and it takes me to a different line sometimes in a different file. 

https://github.com/user-attachments/assets/1dde430a-fbd8-431f-bafc-d68050be7115
https://github.com/user-attachments/assets/6dfdfffe-9ff0-4e58-9948-166da550fdb4

**Comment by eleanorjboyd** [comment]
@joshspicer verified the behavior is fixed with the new release of insiders

**Comment by joshspicer** [comment]
Note that I only verified in OSS given that the insiders build wasn't available yet :)

**Comment by osortega** [comment]
Just tried on the insiders from 2 hours ago and looks like I still get a weird behavior:

https://github.com/user-attachments/assets/d5e8d032-2731-4a91-ad16-e55be32b4792

**Comment by rzhao271** [comment]
Reopening based on the verification-found above.

**Comment by jrieken** [comment]
@osortega Not sure what you are showing in the video but the cursor isn't reset as you type and that's what this issue is about (see https://github.com/microsoft/vscode/issues/239301#issue-2822986907)
