### ISSUE TITLE
Source control missing control buttons

### ISSUE THREAD

**Issue by elkrt** [microsoft/vscode#240380]
Type: <b>Bug</b>

Since the last update the list section "Source Control Repositories" is missing some buttons, next to the respecting branch names. Also now I'm asked which repo to commit to everytime I try to commit, instead of commiting to the correct repo, that's selected above.

VS Code version: Code 1.97.0 (33fc5a94a3f99ebe7087e8fe79fbe1d37a251016, 2025-02-04T22:41:26.688Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by mattjoudrey** [comment]
Similar here for the "Source Control Repositories" issue.  I'm specifically looking for the "..." that lived next to the branch name, currently only the "Synchronize Changes" button shows.  The desired ellipsis appears to be in the "Source Control" tab as a workaround, but far less convenient for my workflow.

The "which repo" one only started happening for a newly created branch.

Windows 10 Pro
git version 2.39.0.windows.1 - which admittedly, is getting kinda old.  I may update but will likely wait to see if more info comes out of this issue, depending on how annoyed I get.

**Comment by elkrt** [comment]
![Image](https://github.com/user-attachments/assets/8aa6151d-d388-47c5-9d76-32ccdd105460)

Some control buttons like in the yellow box had always been where the now empty red box is located. They're missing since the last update, and the whole thing now behaves a lot more inconveniently

**Comment by mattjoudrey** [comment]
A more simple screen shot:
![Image](https://github.com/user-attachments/assets/ced40486-eb1c-4908-9166-d77ec9dd4792)

As mentioned, what I'm mainly looking for is the the ellipsis that used to be in the red circle.  It supplied access to a range of individual git actions (pull, push, fetch, branch etc).

As for the "which repo" issue: make changes > stage > enter commit message > "Commit & Push".  Previously, it would just commit and push but now immediately opens "Choose a repository":

![Image](https://github.com/user-attachments/assets/016a3d0c-9e23-4798-aa2c-f30d892b2951)

If I choose the repo, it works.  If I click out of the "Choose a repository" dropdown, I'm left with "Sync Changes" (see below)...so I guess its committed but not pushed.  If I click "Sync Changes" it pushes and everything is good.

![Image](https://github.com/user-attachments/assets/73c31b6e-54be-4d69-9388-ab91a0384a3e)

**Comment by lszomoru** [comment]
@elkrt, @mattjoudrey, could you please try the latest [VS Code Insiders release](https://code.visualstudio.com/insiders/)?

**Comment by elkrt** [comment]
I think for the red circles I narrowed it down to the extension "Git Graph". Deactivating this makes the buttons reappear. This seems to break the source control window. But still, only since the last VSC update.

Sadly that doesn't fix that you have to choose the repo you want to push to, that still pops up annoyingly. Even without any installed extensions, so this must be directly related to the newest VSC update.

**Comment by elkrt** [comment]
Todays update 1.97.2 did not fix this issue

**Comment by umarbutler** [comment]
> ![Image](https://github.com/user-attachments/assets/8aa6151d-d388-47c5-9d76-32ccdd105460)
> 
> Some control buttons like in the yellow box had always been where the now empty red box is located. They're missing since the last update, and the whole thing now behaves a lot more inconveniently

This is very bizzare because this has just happened for me too but when I reopen a folder in WSL, the buttons move back to where they should be.

**Comment by fluffy-cakes** [comment]
Same issue. It went missing after the update. The next day it came back. Today it is missing again.

**Comment by lszomoru** [comment]
This is very strange and I would love to get to the bottom of it. When the issue occurs can you right click on the branch name and choose "Reset Menu"? Does that resolve the problem? If someone gets into this state I would love for them to share the HTML for the action bar as that might have some hints of what is happening:
1. Invoke the "Developer: Toggle Developer Tools" command from the command palette
2. Click on the "Elements" tab, and then click on the element selector arrow
3. Hover over the branch picker and click. This should select an `a` element
4. Up two levels there is a `ul` element. Right click on it, pick Copy -> Copy outerHTML
5. Share the HTML

**Comment by elkrt** [comment]
With active issue:
`<ul class="actions-container" role="toolbar">
  <li class="action-item" role="presentation" custom-hover="true">
    <a class="action-label" role="button" aria-label="development, Checkout Branch/Tag..." tabindex="0"><span class="codicon codicon-git-branch"></span> development</a>
  </li>
</ul>`

After reloading the editor:
`<ul class="actions-container" role="toolbar">
  <li class="action-item" role="presentation" custom-hover="true">
    <a class="action-label" role="button" aria-label="development, Checkout Branch/Tag..." tabindex="0"><span class="codicon codicon-git-branch"></span> development</a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-gitlens-graph" role="button" aria-label="Show Commit Graph"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-check" role="button" aria-label="Commit"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-history" role="button" aria-label="Git: View History (git log)"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-refresh" role="button" aria-label="Refresh"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label icon" role="button" aria-label="View Git Graph (git log)" style="background-image: url(&quot;vscode-file://vscode-app/c:/Users/<my_windows_username>/.vscode/extensions/mhutchie.git-graph-1.30.0/resources/cmd-icon-dark.svg&quot;);"></a>
  </li>
  <li class="action-item" role="presentation">
    <div class="monaco-dropdown">
      <div class="dropdown-label">
        <a class="action-label codicon codicon-toolbar-more" role="button" aria-haspopup="true" aria-expanded="false" custom-hover="true" aria-label="More Actions..."></a>
      </div>
    </div>
  </li>
</ul>`

**Comment by elkrt** [comment]
With active issue:

<ul class="actions-container" role="toolbar">
  <li class="action-item" role="presentation" custom-hover="true">
    <a class="action-label" role="button" aria-label="development, Checkout Branch/Tag..." tabindex="0"><span class="codicon codicon-git-branch"></span> development</a>
  </li>
</ul>


After reloading the editor:
<ul class="actions-container" role="toolbar">
  <li class="action-item" role="presentation" custom-hover="true">
    <a class="action-label" role="button" aria-label="development, Checkout Branch/Tag..." tabindex="0"><span class="codicon codicon-git-branch"></span> development</a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-gitlens-graph" role="button" aria-label="Show Commit Graph"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-check" role="button" aria-label="Commit"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-history" role="button" aria-label="Git: View History (git log)"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-refresh" role="button" aria-label="Refresh"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label icon" role="button" aria-label="View Git Graph (git log)" style="background-image: url(&quot;vscode-file://vscode-app/c:/Users/<my_windows_username>/.vscode/extensions/mhutchie.git-graph-1.30.0/resources/cmd-icon-dark.svg&quot;);"></a>
  </li>
  <li class="action-item" role="presentation">
    <div class="monaco-dropdown">
      <div class="dropdown-label">
        <a class="action-label codicon codicon-toolbar-more" role="button" aria-haspopup="true" aria-expanded="false" custom-hover="true" aria-label="More Actions..."></a>
      </div>
    </div>
  </li>
</ul>

**Comment by elkrt** [comment]
With active issue:

```<ul class="actions-container" role="toolbar">
  <li class="action-item" role="presentation" custom-hover="true">
    <a class="action-label" role="button" aria-label="development, Checkout Branch/Tag..." tabindex="0"><span class="codicon codicon-git-branch"></span> development</a>
  </li>
</ul>```


After reloading the editor:
```<ul class="actions-container" role="toolbar">
  <li class="action-item" role="presentation" custom-hover="true">
    <a class="action-label" role="button" aria-label="development, Checkout Branch/Tag..." tabindex="0"><span class="codicon codicon-git-branch"></span> development</a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-gitlens-graph" role="button" aria-label="Show Commit Graph"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-check" role="button" aria-label="Commit"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-history" role="button" aria-label="Git: View History (git log)"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label codicon codicon-refresh" role="button" aria-label="Refresh"></a>
  </li>
  <li class="action-item menu-entry" role="presentation" custom-hover="true">
    <a class="action-label icon" role="button" aria-label="View Git Graph (git log)" style="background-image: url(&quot;vscode-file://vscode-app/c:/Users/<my_windows_username>/.vscode/extensions/mhutchie.git-graph-1.30.0/resources/cmd-icon-dark.svg&quot;);"></a>
  </li>
  <li class="action-item" role="presentation">
    <div class="monaco-dropdown">
      <div class="dropdown-label">
        <a class="action-label codicon codicon-toolbar-more" role="button" aria-haspopup="true" aria-expanded="false" custom-hover="true" aria-label="More Actions..."></a>
      </div>
    </div>
  </li>
</ul>```

**Comment by lszomoru** [comment]
Thank you @elkrt. I do have a repro and I am currently debugging to see if I can get to the bottom of it.

**Comment by lszomoru** [comment]
I spent quite some time today investigating this. I was initially able to reproduce this issue with a workspace containing multiple repositories but after restarting the extension host I am not able to reproduce the issue any more. Looking at the code it looks like there is some kind of a timing issue with the actions that are being contributed by the extensions (ex: vscode.git, and others). 

I really want to get to the bottom of this so I would really appreciate if people can share any steps that they have that consistently reproduces the issue. I will continue to investigate things on my end and I will try to add logging to see if that helps us track down the root cause. Thank you!

**Comment by lszomoru** [comment]
I believe I was able to track down the issue and push a fix. The fix will be available in tomorrow's VS Code Insiders release so I would really appreciate if people could install it and validate that the fix is working as expected. Thank you!

**Comment by bilogic** [comment]
Thanks, I will be verifying this at https://insiders.vscode.dev/github/bilogic/NanoKVM

**Comment by elkrt** [comment]
Weird, now since yesterday morning when I start up VSC, the buttons are already there, without restarting the editor. No changes, update, still on version 1.97.2

**Comment by lszomoru** [comment]
@elkrt, yes, it is a timing issue and that is why it took me quite some time to get to the bottom of it. Having said that, I am confident that the fix that I pushed resolves the issue.

**Comment by bilogic** [comment]
For what it is worth, I was able to to reproduce the issue every single time on https://vscode.dev and my self hosted code-server.

**Comment by bilogic** [comment]
1. https://insiders.vscode.dev/github/bilogic/NanoKVM
2. GitLens icon still missing in VSCode Insider released 6 hours ago
    ![Image](https://github.com/user-attachments/assets/1e1c7be4-5701-4edd-967c-fad30d5d5ded)

**Comment by lszomoru** [comment]
@bilogic, I can only repeat myself. Please follow up with the extension author.
This issue is scoped to actions like commit, refresh, missing and **not** extension specific actions.

**Comment by bilogic** [comment]
Pardon me, but you marked my issue as duplicate of this.

When every extension's icons disappear, it's hard to comprehend why it is every extension's issue and not VSCode's. 

In any case, I already raise it to their attention at https://github.com/gitkraken/vscode-gitlens/issues/4067

**Comment by lszomoru** [comment]
> When every extension's icons disappear, it's hard to comprehend why it is every extension's issue and not VSCode's.

This statement is incorrect. The actions from the `vscode.git` extension are present.

**Comment by bilogic** [comment]
> This statement is incorrect. The actions from the `vscode.git` extension are present.

![Image](https://github.com/user-attachments/assets/cfd0e842-68bb-4d41-8bc2-37f30b98f94b)

I have disabled to vscode.git extension, yet the icons remain, do they really belong to vscode.git?

**Comment by lszomoru** [comment]
@bilogic, the screenshot shows the Git Base extension and not the Git extensions (`vscode.git`). Also note that when you disable an extension we cannot unload it so independent of what extension it is, you have to restart the extension host.
