### ISSUE TITLE
Extension Explorer: Rating and Download Count only Displayed If Full Name is displayed

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#24242]
**repo**
1. Search `angular` in extension explorer. 

**bug**
For extensions with long names, the download count and star rating is not displayed

![screen shot 2017-04-07 at 9 50 17 am](https://cloud.githubusercontent.com/assets/12821956/24810600/affc2864-1b77-11e7-9c80-9e912f1419a4.png)

You have to expand the explorer to see these:

![screen shot 2017-04-07 at 9 50 25 am](https://cloud.githubusercontent.com/assets/12821956/24810601/affe7fd8-1b77-11e7-8526-db44658f5d4b.png)

This information is helpful when determining which extension to install and should always be displayed IMO

**Comment by rishii7** [comment]
@joaomoreno 
Considering the extension download count and rating of the extension to be shown until the user shrinks extension explorer's width by large wherein the extension images get hidden.We can allow the extension names to be displayed by getting rid of `flex-wrap` on `header` . 

End result is as shown below in this [expanding and shrinking extension explorer](https://drive.google.com/open?id=0BwzfkI9oPZs1TnRORUZRdG1CLUE)

I will submit a PR regarding the same.

**Comment by joaomoreno** [comment]
This was fixed by #24371

![image](https://cloud.githubusercontent.com/assets/22350/24950501/87cf0818-1f71-11e7-9dce-c38800ee5394.png)

**Comment by ramya-rao-a** [comment]
Still dont see the ratings and download count

![image](https://cloud.githubusercontent.com/assets/16890566/25497020/02a98e7e-2b38-11e7-8f25-8936219bb536.png)

**Comment by joaomoreno** [comment]
Reference to [my comment](https://github.com/Microsoft/vscode/pull/24550#issuecomment-293520493).

**Comment by BugraC** [comment]
@joaomoreno I saw this issue and I think the fix can be simple enough. I created this so far: 

https://github.com/Microsoft/vscode/pull/25756

Please see my working screenshot:

![image](https://cloud.githubusercontent.com/assets/3826953/25603622/35076f6c-2ecb-11e7-8bab-c7efd1a53f4a.png)

Please let me know if you have some feedback.
P.S. I will fix the unnecessary changes in my pull request if you are OK with my current changes.
