### ISSUE TITLE
Mouse scroll is locked and the debug console rolls up to the top for no reason

### ISSUE THREAD

**Issue by aminzg** [microsoft/vscode#242907]
Version and platform:
VS Code Version: 1.98 (I am using Universal)
OS Version: macOS 15.2 (Sequoia)

I had reported this bug along with another one in issue (Debug console display is broken #241948) which was originally for 1.97.2. However, the issue is still persisting in 1.98.

Steps to Reproduce:
1. Have a python code in debug mode.
2. Put a breakpoint and make your program stop.
3. Evaluate something large or evaluate it several times to ensure the debug console is enlarged enough for scrolling. E.g. let it show you a pandas dataframe.
4. In debug console, right click on the dataframe column value to select it, which opens the contextual menu.
5. press 'copy'
6. move the mouse up to the editor.
7. The debug console scrolls up to the top with no exception.

Appreciate your help to fix it.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/237332 is fixed in Insiders, sorry for the slow fix

**Comment by aminzg** [comment]
Thank you!

**Comment by aminzg** [comment]
@roblourens I checked Version 1.98.2 today, and the issue is still there. It is about scrolling.
It can be reproduced the same way as before
