### ISSUE TITLE
String "1 older results" in "Show Output" window has grammatical error

### ISSUE THREAD

**Issue by Amy-Li03** [microsoft/vscode#244218]
- VS Code Version: VS Code 1.97.2
- CMake Tools v1.20.52 (release)
- OS Version: Win11 23H2

Steps to Reproduce:

1. Unzip and open the project with VS Code
[CMakeProject1.zip](https://github.com/user-attachments/files/18961722/CMakeProject1.zip)
2. Click Testing in left navigation bar
3. Click the "run tests" button
4. Click the "run tests" button once more
5. Click "Show Output" button
6. Observe the string in "Show Output" window

Actual result:
The string "1 older results" has grammatical error

![Image](https://github.com/user-attachments/assets/bd9aaa7d-21a5-4333-a240-3d27bcd45c4f)

Expected result:
It should be "1 older result"

**Comment by Amy-Li03** [comment]
Hi, latest vs code stable release 1.98.2 also repro this issue.

**Comment by iwangbowen** [comment]
It should be fixed

**Comment by Amy-Li03** [comment]
It still reproducing on VS Code v1.98.2, please see below screenshot:

![Image](https://github.com/user-attachments/assets/a078f60e-feaa-4719-949d-b2ca4a69d3f8)

**Comment by Amy-Li03** [comment]
Verified this on VS Code v1.99.2, issue is still reproducing.
![Image](https://github.com/user-attachments/assets/b05ee977-d3d6-48ed-a21c-cde6a0975ed2)

**Comment by anthonykim1** [comment]
Verified this is resolved on latest insiders.
![Image](https://github.com/user-attachments/assets/1018e9e0-f4f0-4a2f-abf9-2b9fed7e1246)
Make sure folks test on the insiders (this is the VS Code Insiders that you can download). It would have VS Code logo with green color instead of the blue (stable)

**Comment by Amy-Li03** [comment]
Verified with VS Code Insiders v1.100.0-insider, issue was fixed.

![Image](https://github.com/user-attachments/assets/7f4f9997-5d20-48af-a71e-c1904b279b32)
