### ISSUE TITLE
Built-in terminal don't respond to abort signal in Apple Silicon build.

### ISSUE THREAD

**Issue by AC-Stray** [microsoft/vscode#245217]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.98.2
- OS Version: macOS Sequoia 15.3.2
- Device: M4 MacBook Air

I run a program in the built-in terminal, if the program aborted, sometimes the terminal won't respond to any action including Ctrl+C, Ctrl+Z, Ctrl+D.

Steps to Reproduce:

1. Run `python -c "import os; os.abort()"` for **twice**. The bug always occurs in the second time. And if you kill the terminal and open a new one, the bug occurs when whatever program aborted.

Bug exists no matter I use zsh or bash.

It's not necessary to use python to reproduce the bug. But the above step is the simplest.

The same thing didn't happen in the Terminal app, and didn't happen in the same version vscode build for intel chip.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by AC-Stray** [comment]
Yes you're right. It's fixed. Thank you very much.

**Comment by AC-Stray** [comment]
It seems the problem is back again in the latest 1.99 and the 1.100 Insiders? @meganrogge
