### ISSUE TITLE
Explorer: Ctrl + Drag-and-drop file does not copy file

### ISSUE THREAD

**Issue by LarsonPaul1** [microsoft/vscode#246370]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.99.0
- OS Version: Ubuntu 24.04.2 LTS

Steps to reproduce:

1a. Hold Ctrl, then click and hold on a file in the explorer.
1b. Click and hold on a file, then hold Ctrl.
2. Drag the file to a new location and release.

Expected results:

1. The cursor displays the plus-icon.
2. When the file is released, the file is copied to the new location.

Actual results:
1. The cursor displays the move-icon.
2. When the file is released, a dialog pops up to confirm *moving* the file.

Additional notes:

The "Help > Report Issue" dialog in VS Code did not auto-fill the report with the information I wrote. I had to copy it manually.

**Comment by LarsonPaul1** [comment]
After updating to VS Code version 1.99.2, the issue persists.

**Comment by airtonix** [comment]
also getting this bug

**Comment by lramos15** [comment]
I haven't been able to reproduce this on macos. Are you using linux as well @airtonix ?

**Comment by albertosantini** [comment]
I haven't been able to reproduce this on Windows.

Maybe a matter of permissions of the target folder?
What about executing the same action with the native file explorer?

**Comment by LarsonPaul1** [comment]
I have no issue copying files in the Files app, nor with copying files between projects with multiple windows of VSCode. The issue only presents when trying to copy files within the same project.

**Comment by albertosantini** [comment]
Video with gifcap tool may help.

**Comment by LarsonPaul1** [comment]
I will try to provide that when I'm back on that system.

**Comment by albertosantini** [comment]
That is the behavior as if Ctrl key would not be pressed. Interesting and frustrating.

**Comment by lramos15** [comment]
We just released 1.100. I'm assuming no change?

**Comment by aspectum** [comment]
I'm also having this problem. I'm on Ubuntu 24.10.

<details>
<summary>VSCode info</summary>

> Version: 1.100.0
Commit: 19e0f9e681ecb8e5c09d8784acaa601316ca4571
Date: 2025-05-07T12:48:53.763Z
Electron: 34.5.1
ElectronBuildId: 11369351
Chromium: 132.0.6834.210
Node.js: 20.19.0
V8: 13.2.152.41-electron.0
OS: Linux x64 6.11.0-25-generic snap

</details>

**Comment by LarsonPaul1** [comment]
After upgrading to VSCode version 1.100.0, the issue persists.

**Comment by lramos15** [comment]
@LarsonPaul1 Could you try 1.98? You can download it from the release notes https://code.visualstudio.com/updates/v1_98

**Comment by LarsonPaul1** [comment]
I tested 1.98, 1.97, and 1.90 and was not able to copy files using this method in any of them. In order to downgrade VSCode, I had to delete $HOME/.vscode and $HOME/.config/Code, otherwise I could not open folders in VSCode at all. I don't know if there are other config files I need to delete for a truly clean install.

I also tried copying files in an old Ubuntu 22.04 LTS virtual machine, and was successful in VSCode version <1.90 and version 1.100. I don't know if this indicates that the problem is specific to Ubuntu 24.04 LTS, or if it's specific to my particular machine.

**Comment by lramos15** [comment]
@deepak1556 Could this be an electron issue?

**Comment by LarsonPaul1** [comment]
I've updated to VSCode version 1.100.1, and the issue remains.

**Comment by SMERKY** [comment]
I have this issue on Windows also

**Comment by airtonix** [comment]
head over to https://github.com/zed-industries/zed/discussions/31328 to vote for the feature.

**Comment by LarsonPaul1** [comment]
Still not working as of version 1.101.0.
Update 2025-06-26: Not working as of 1.101.1.
Update 2025-07-09: Not working as of 1.101.2.

**Comment by LarsonPaul1** [comment]
As of version 1.102.1, there has been no fix or update on this issue. 
Update 2025-08-08: Not working as of 1.102.3.

**Comment by LarsonPaul1** [comment]
Still not working, version 1.103.1.

It's been 3 months since the last update on this issue.

**Comment by ljazzy** [comment]
Still broken on linux.

**Comment by lramos15** [comment]
@deepak1556 I found a concrete upstream explanation for the **native Wayland** case:

- [Chromium 132's Wayland backend](https://github.com/chromium/chromium/blob/132.0.6834.210/ui/ozone/platform/wayland/host/wayland_window.cc#L77) explicitly defines `kWaylandDndModifiers = 0`. Its comment explains that compositors usually remove keyboard focus during drag sessions, handle modifiers themselves, and notify clients of the negotiated drag action instead.
- It passes that zero modifier mask to [drag-enter](https://github.com/chromium/chromium/blob/132.0.6834.210/ui/ozone/platform/wayland/host/wayland_window.cc#L876), [drag-motion](https://github.com/chromium/chromium/blob/132.0.6834.210/ui/ozone/platform/wayland/host/wayland_window.cc#L897), and [drop](https://github.com/chromium/chromium/blob/132.0.6834.210/ui/ozone/platform/wayland/host/wayland_window.cc#L901). [Current Chromium main](https://github.com/chromium/chromium/blob/main/ui/ozone/platform/wayland/host/wayland_window.cc#L72) still has the same implementation.
- Chromium links to this [Wayland protocol discussion about keyboard focus during drag sessions](https://gitlab.freedesktop.org/wayland/wayland/-/issues/441).

Consequently, target `dragover`/`drop` events lack the Ctrl/Shift modifier state. Explorer checks `DragEvent.ctrlKey` to choose copy versus move, which explains both the missing copy cursor and the move confirmation. The same upstream behavior also explains the Shift-to-drop-into-editor failure.

Consolidating #327800 (Ctrl-drag copy) and #246418 (Shift-drag into editor) here to track the shared native-Wayland modifier problem. This appears to need investigation in the Chromium/Wayland integration rather than an Explorer-specific change.

Caveat: this source evidence establishes the native-Wayland mechanism, but does not by itself explain the Windows or XWayland observations. The actual backend on affected installations still matters.

**Comment by Peritia-System** [comment]
Same problem using the flaptak
