### ISSUE TITLE
Neither VS Code nor Insider appears in Windows 11 Explorer context menu

### ISSUE THREAD

**Issue by IgorArnaut** [microsoft/vscode#246416]
I've looked up GitHub discussions about the issue and these are LOCKED.

I've already tested the Insiders build.

Does this issue occur when all extensions are disabled?: No.

- VS Code Version: 1.100-0-insider
- OS Version: Windows 11 64-bit

Steps to Reproduce:

1. Install VS Code
2. During installation Enable `Add "Open with Code - Insiders" action to Windows Explorer file context menu`
3. Right click a file and folder
4. VS Code does not appear
5. Click "Show More Options"
6. VS Code does not appear there too

**Comment by kouhe3** [comment]
same here

**Comment by atom0s** [comment]
This appears to be an issue with one of the recent updates/installers. I am also seeing this issue after allowing my Insiders install to update to latest. My setup originally had the context menu entries enabled, but after an update in the last week, they are gone.

**Comment by atom0s** [comment]
Appears to be fixed now in the newest Insider update. My context menu options are back.

```
Visual Studio Code - Insiders
Version: 1.100.0-insider (system setup)
Commit: f56819db693dba84feb3716e278b5be0a7378633
Date: 2025-04-17T05:10:42.956Z (15 hrs ago)
Electron: 34.4.1
ElectronBuildId: 11317338
Chromium: 132.0.6834.210
Node.js: 20.18.3
V8: 13.2.152.41-electron.0
OS: Windows_NT x64 10.0.22631
```

**Comment by kouhe3** [comment]
same, f56819db693dba84feb3716e278b5be0a7378633 fixed here

**Comment by emeryao** [comment]
"Open with Code - Insiders" in context menu on Windows 10 still missing here

Version: 1.103.0-insider
Commit: f5db653369bc87e56162be11ed3af62746347558
Date: 2025-07-28T12:38:35.309Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.103.0-insider Chrome/138.0.7204.100 Electron/37.2.3 Safari/537.36

**Comment by emeryao** [comment]
may be dupe with pinned issue #260389

**Comment by emeryao** [comment]
"Open with Code - Insiders" in context menu still missing on my Windows 10 after uninstall and reinstall

```
Version: 1.104.0-insider (user setup)
Commit: a61e381bfa71c241738e48f2fc8b01eade94c91d
Date: 2025-08-14T20:20:09.764Z
Electron: 37.2.3
ElectronBuildId: 12035395
Chromium: 138.0.7204.100
Node.js: 22.17.0
V8: 13.8.500258-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by emeryao** [comment]
I figure out a workaround with [a reg file](https://gist.github.com/emeryao/48c2237da40d6458e23a7cde9573fe61)

**Comment by emeryao** [comment]
It's a little tricky here 
I some how restored the context menu with editing the registry with a [file](https://gist.github.com/emeryao/48c2237da40d6458e23a7cde9573fe61)

But after the insiders version auto updates and restarts the context menu gone again 😆 

Version: 1.104.0-insider (user setup)
Commit: 0ab18bd00955d2a3d69eb66d8eea982b76a53780
Date: 2025-08-15T10:51:05.286Z
Electron: 37.2.3
ElectronBuildId: 12035395
Chromium: 138.0.7204.100
Node.js: 22.17.0
V8: 13.8.500258-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by atom0s** [comment]
Looks like one of the newer Insider updates broke this again. My context menu entries are gone again now. :(

**Comment by IgorArnaut** [comment]
I have the problem with normal VS Code too.

**Comment by deepak1556** [comment]
Does this issue repro with latest 1.107 insiders with user setup ?

1) New context menu not showing for system setup in insiders is tracked in https://github.com/microsoft/vscode/issues/259505
2) New context menu not showing for stable is tracked in https://github.com/microsoft/vscode/issues/204696

**Comment by atom0s** [comment]
> Does this issue repro with latest 1.107 insiders with user setup ?
> 
>     1. New context menu not showing for system setup in insiders is tracked in [Context menu entries "Open with..." not available with insiders system setup #259505](https://github.com/microsoft/vscode/issues/259505)
> 
>     2. New context menu not showing for stable is tracked in [[Meta] Enable windows 11 context menu by default in Stable #204696](https://github.com/microsoft/vscode/issues/204696)

Updated to latest Insiders this morning, the explorer/context menu options are still broken/missing.

```
Version: 1.108.0-insider (system setup)
Commit: f1db08ab87ec1108d0e3c2a20c7ffe5b8a55a23b
Date: 2025-12-10T18:27:57.535Z
Electron: 39.2.3
ElectronBuildId: 12895514
Chromium: 142.0.7444.175
Node.js: 22.21.1
V8: 14.2.231.21-electron.0
OS: Windows_NT x64 10.0.22631
```
