### ISSUE TITLE
Settings and config variables not resolved correctly (introduced in v1.99)

### ISSUE THREAD

**Issue by bht-patrick-schneider** [microsoft/vscode#246854]
Type: <b>Bug</b>

Using VSCode 1.99 with Windows 11, reproducible on different machines in our company and by our customers.

With the v1.99 update our settings in our customer projects broke, because some variables in the settings are not resolved correctly any more.

We use chaining of variables and this was perfectly fine before:

```
{
   "testpara.string1":      "hello",
   "testpara.string2":      "world",
   "testpara.array1":       ["${config:testpara.string1}", "${config:testpara.string2}"],
   "testpara.array2":       ["hello", "world"],
   "testpara.workspace":    "${workspaceFolder}/build",
   "testpara.chained":      "${config:testpara.workspace}/bin"
}
```

we use this inside a task like this:

```
{
   "version": "2.0.0",
   "tasks": [
      {
         "label":          "Test Setting Variables",
         "type":           "shell",
         "command":        "python test.py ${config:testpara.string1} ${config:testpara.string2} ${config:testpara.array1} ${config:testpara.array2} ${config:testpara.workspace} ${config:testpara.chained}",
         "options":        { "cwd": "${workspaceFolder}" },
         "problemMatcher": []
      }
   ]
}
```

and use a python script to output the variables.

The expected output, which can be regenerated when downgrading to v1.98 is

```
Executing task in folder VSCodeParameterBug: python test.py hello world ${config:testpara.string1},${config:testpara.string2} hello,world C:\Users\Pat\Downloads\VSCodeParameterBug/build C:\Users\Pat\Downloads\VSCodeParameterBug/build/bin

hello
world
hello,world
hello,world
C:\Users\Pat\Downloads\VSCodeParameterBug/build
C:\Users\Pat\Downloads\VSCodeParameterBug/build/bin
```

The faulty output from v1.99 is 

```
Executing task in folder VSCodeParameterBug: python test.py hello world ${config:testpara.array1} ${config:testpara.array2} ${workspaceFolder}/build ${config:testpara.workspace}/bin

hello
world
${config:testpara.array1}
${config:testpara.array2}
C:\Users\Pat\Downloads\VSCodeParameterBug/build
${workspaceFolder}/build/bin
```

You can clone a simplified example in my repo here https://github.com/bht-patrick-schneider/VSCodeBugConfigParameters

VS Code version: Code 1.98.2 (ddc367ed5c8936efe395cffeec279b04ffd7db78, 2025-03-12T13:32:45.399Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by nortakales** [comment]
I think I am running into the same issue. I have this in `inputs`:

```
        {
            "id": "killAllTasks",
            "type": "command",
            "command": "workbench.action.tasks.terminate",
            "args": "terminateAll"
        },
```

and this used to work fine:

```
  ...
  "command": "${input:killAllTasks}",
  ...
```

but now I get this error:

`The terminal process failed to launch: Path to shell executable "${inputs:killAllTasks}" does not exist.`

**Comment by nortakales** [comment]
From https://code.visualstudio.com/docs/reference/variables-reference

Is this example:

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Terminate All Tasks",
      "command": "echo ${input:terminate}",
      "type": "shell",
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "terminate",
      "type": "command",
      "command": "workbench.action.tasks.terminate",
      "args": "terminateAll"
    }
  ]
}
```
which is now broken. Output looks like:

```
 *  Executing task in folder ParkerSpectatorPlus: echo ${input:terminate} 

zsh:1: unrecognized modifier `k'

 *  The terminal process "/usr/bin/zsh '-c', 'echo ${input:terminate}'" failed to launch (exit code: 1).
 ```

Looks like substitution of `${input:terminate}` is not happening

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by stevemcgf** [comment]
I just tested on Insiders build the issue is still present. Downgrading to 1.98.2 fixes the issue. It happens on any 1.99.x build.


`
 *  Executing task in folder 📦 ******Compositor: ${input:switchTo*****Compositor}  


 *  The terminal process failed to launch: Path to shell executable "${input:switchTo*****Compositor}" does not exist. 
`

**Comment by meganrogge** [comment]
Maybe related https://github.com/microsoft/vscode/pull/243092

**Comment by stevemcgf** [comment]
It doesn't seem to be fixed in the insiders build yet. Also the duplicated issue happen on 1.98.2 and this one doesn't.

**Comment by meganrogge** [comment]
To help us narrow down what change caused the issue, please run the following command to find the build. It will start previous releases of VS Code insiders to see where the regression was introduced:
* `npx @vscode/vscode-bisect@latest`
* follow the instructions until you found the offending build
* report back the commit range in this issue

Thanks!

**Comment by stevemcgf** [comment]
This is the range
[build] c6ebae0ac01a969248f80afe532f46198d62bcf1 is the first bad commit after ea9b53fbcbcfd76f57d3f9414fb50ed2d05d3215.

https://github.com/microsoft/vscode/compare/ea9b53fbcbcfd76f57d3f9414fb50ed2d05d3215...c6ebae0ac01a969248f80afe532f46198d62bcf1

**Comment by connor4312** [comment]
@stevemcgf can you give us a full repro? The case as described at the root of this issue has been resolved so I'm not clear what you're seeing.

**Comment by stevemcgf** [comment]
Minimal workspace to repro the issue.
https://github.com/stevemcgf/FailureDemo

Output when running task "CMake: Switch to Compositor"

```
 *  Executing task in folder 📦 Compositor: ${input:switchToCompositor}  


 *  The terminal process failed to launch: Path to shell executable "${input:switchToCompositor}" does not exist. 
```

Before it used to run the command defined on the input.

**Comment by connor4312** [comment]
In the demo folder you provided, with the CMake Tools extension installed, the command `cmake.selectActiveFolder` with the arg `Compositor` returns `undefined`, so therefore we do not replace the input expression.

I also see the [extension implementation](https://github.com/microsoft/vscode-cmake-tools/blob/767662f0302aede88329d008794739840221251b/src/extension.ts#L753) of `cmake.selectActiveFolder` never returns anything, so this is probably an issue with how you have the task configured.

**Comment by stevemcgf** [comment]
I got you. But that used to work before I will file a bug with cmake extension.

**Comment by connor4312** [comment]
Thanks, will close for verification of the original issue

**Comment by nortakales** [comment]
This was not fixed. I guess the discussion has moved here for anyone looking: https://github.com/microsoft/vscode/issues/246074
