### ISSUE TITLE
[json] Intellisense Provides Strange Suggestions In Property Value

### ISSUE THREAD

**Issue by daschult** [Microsoft/vscode#2468]
When I'm writing an Azure RM Deployment template and I'm writing a template language expression that contains single-quoted strings inside double-quoted property values, I get some strange suggestions. I get the same thing when I try to access a resourceGroup() property via the '.' character. The pictures show the suggestions I'm getting. In these scenarios, I expect to not get any suggestions.
![jsonintellisenseinpropertyvaluewithperiod](https://cloud.githubusercontent.com/assets/7052303/12624898/3594dc62-c4e6-11e5-9c01-c79df8076d33.png)
![jsonintellisenseinpropertyvaluewithsinglequotedstring](https://cloud.githubusercontent.com/assets/7052303/12624899/359895aa-c4e6-11e5-8bd0-d86509483949.png)

**Comment by aeschli** [comment]
Note that you are editing a document with no schema associated. In that case we look for similar nodes and give these as proposals. I fixed that the value of the won node is not proposed.
There is still issue #2496 that adds funny proposal.

In the context of a Azure RM Deployment template you should have a schema association.

**Comment by bpasero** [comment]
I am still seeing what the user reports:

![image](https://cloud.githubusercontent.com/assets/900690/12674686/021f5ac4-c685-11e5-9258-5621c34b403f.png)

**Comment by weinand** [comment]
works:
![2016-07-28_16-54-25](https://cloud.githubusercontent.com/assets/1898161/17217258/01559390-54e4-11e6-99d1-a20be1e5f811.png)
