### ISSUE TITLE
APT repository related: Policy will reject signature within a year, SHA1 is not considered secure by APT since 2026-02-01

### ISSUE THREAD

**Issue by wcbing** [microsoft/vscode#247505]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.99.3
- OS Version: Debian Unstable

Steps to Reproduce:

This bug is actually related to apt repository, but I don't know how to classify it.

[apt 3.0.1 has been released](https://mastodon.social/@juliank/114400785475918346), when update:

```sh
> apt update
...
...
All packages are up to date.
Warning: https://packages.microsoft.com/repos/code/dists/stable/InRelease: Policy will reject signature within a year, see --audit for details
Warning: https://packages.microsoft.com/repos/edge/dists/stable/InRelease: Policy will reject signature within a year, see --audit for details
> apt update --audit
...
...
All packages are up to date.
Warning: https://packages.microsoft.com/repos/code/dists/stable/InRelease: Policy will reject signature within a year, see --audit for details
Audit: https://packages.microsoft.com/repos/code/dists/stable/InRelease: Sub-process /usr/bin/sqv returned an error code (1), error message is:
   Signing key on BC528686B50D79E339D3721CEB3E94ADBE1229CF is not bound:
              No binding signature at time 2025-04-25T16:22:10Z
     because: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance
     because: SHA1 is not considered secure since 2026-02-01T00:00:00Z
Warning: https://packages.microsoft.com/repos/edge/dists/stable/InRelease: Policy will reject signature within a year, see --audit for details
Audit: https://packages.microsoft.com/repos/edge/dists/stable/InRelease: Sub-process /usr/bin/sqv returned an error code (1), error message is:
   Signing key on BC528686B50D79E339D3721CEB3E94ADBE1229CF is not bound:
              No binding signature at time 2025-04-25T17:43:45Z
     because: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance
     because: SHA1 is not considered secure since 2026-02-01T00:00:00Z

**Comment by wcbing** [comment]
Can be solved together with #238697

**Comment by ps81frt** [comment]
up

**Comment by wcbing** [comment]
> [#238697](https://github.com/microsoft/vscode/issues/238697) is closed but this doesn't seem to be fixed

You may have misunderstood my comments before.😂

What I mean is that when he change the key's position, he can also consider about changing the key's content. There's no strong correlation between the two.

**Comment by Sup3rson1x** [comment]
Also facing the same issue. Need to confirm if there Is there a fix to this yet.

**Comment by wcbing** [comment]
> This is tracked in [microsoft/linux-package-repositories#47](https://github.com/microsoft/linux-package-repositories/issues/47). [@wcbing](https://github.com/wcbing), please close to stop all these "me too"-comments.

This shouldn't be closed. Even though the actual signature is from https://github.com/microsoft/linux-package-repositories, the VS Code [postinst script](https://github.com/microsoft/vscode/blob/main/resources/linux/debian/postinst.template) writes to the public key and sources.list file, so this repo will inevitably need to be changed eventually.


> Also, I switched to https://github.com/VSCodium/vscodium which doesn't have this issue.

VSCodium has a apt repo and writes to sources.list? No, so of course it's not affected.

**Comment by lgrn** [comment]
> VSCodium has a apt repo and writes to sources.list? No, so of course it's not affected.

https://vscodium.com/#install-on-debian-ubuntu-deb-package

**Comment by wcbing** [comment]
> > VSCodium has a apt repo and writes to sources.list? No, so of course it's not affected.
> 
> https://vscodium.com/#install-on-debian-ubuntu-deb-package

writes to sources.list.d by postinst script?

**Comment by winstonma** [comment]
I got the same problem and I fixed this by the following

```bash
# Download the Microsoft GPG public key (in .asc format)
sudo wget -P /etc/apt/keyrings https://packages.microsoft.com/keys/microsoft.asc
# Update and modernize APT sources (this command may update sources.list to new format)
sudo apt modernize-sources
# Replace the 'Signed-By:' line in vscode.sources with the correct keyring path
sudo sed -i 's|^Signed-By:.*|Signed-By: /etc/apt/keyrings/microsoft.asc|' /etc/apt/sources.list.d/vscode.sources
sudo apt update
```

Then everything should work. Seems the new apt only use .asc key not .gpg key.

If everything works for you then you can remove the microsoft gpg key

```bash
sudo rm /etc/apt/keyrings/packages.microsoft.gpg
```

See if that helps

**Comment by brunom63** [comment]
Still getting the message below after following your fix @winstonma

```
Warning: https://packages.microsoft.com/debian/12/prod/dists/bookworm/InRelease: Policy will reject signature within a year, see --audit for details
Warning: https://packages.microsoft.com/repos/code/dists/stable/InRelease: Policy will reject signature within a year, see --audit for details
```
Just to confirm, does your `vscode.sources` file look like this?

```
Types: deb
URIs: https://packages.microsoft.com/repos/code/
Suites: stable
Components: main 
Architectures: amd64
Signed-By: /etc/apt/keyrings/microsoft.asc
```
And by the way, I have some apt sources pointing to GPG keys that don't cause these messages. I think it's more about the SHA1 being deprecated than the GPG key itself.

**Comment by winstonma** [comment]
> Still getting the message below after following your fix [@winstonma](https://github.com/winstonma)
> 
> ```
> Warning: https://packages.microsoft.com/debian/12/prod/dists/bookworm/InRelease: Policy will reject signature within a year, see --audit for details
> Warning: https://packages.microsoft.com/repos/code/dists/stable/InRelease: Policy will reject signature within a year, see --audit for details
> ```
This is the result I got from perplexity:

The warning message:

```
Policy will reject signature within a year, see --audit for details
```

means that the cryptographic signature on the repository’s `InRelease` file (from Microsoft’s package servers) will expire within a year. This is a proactive security warning from APT, indicating that, unless the repository maintainers renew and update their signing key or signature before it expires, your system will eventually refuse to accept packages from this source for security reasons.

**What you should do:**

- No immediate action is required on your part. The warning is informational, alerting you that the repository maintainers (in this case, Microsoft) need to update their signing key or re-sign the repository metadata within the next year.
- If you want more details, you can run:

```
sudo apt --audit
```

This will provide a more detailed audit of repository signatures and their expiration dates.

**Summary:**
You can continue to use the repository as normal for now. The warning is for awareness, so you or your organization can plan ahead and avoid disruption if the key is not updated before expiration. If you manage critical systems, keep an eye on such warnings and ensure your sources remain trusted and up-to-date.
> 
> Just to confirm, does your `vscode.sources` file look like this?
> 
> ```
> Types: deb
> URIs: https://packages.microsoft.com/repos/code/
> Suites: stable
> Components: main 
> Architectures: amd64
> Signed-By: /etc/apt/keyrings/microsoft.asc
> ```
> 
> And by the way, I have some apt sources pointing to GPG keys that don't cause these messages. I think it's more about the SHA1 being deprecated than the GPG key itself.

Mine is like this:
```
Types: deb
URIs: https://packages.microsoft.com/repos/code/
Suites: stable
Components: main 
Signed-By: /etc/apt/keyrings/microsoft.asc
```

@brunom63 Could you update VS Code using APT after running my method?

**Comment by brunom63** [comment]
Actually yes, everything gets updated, the way it's supposed to.

So I guess we'll just have to live with that messsage until the key gets updated,

**Comment by winstonma** [comment]
Good to hear it helps.

I guess Microsoft need to updates it's [instruction](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions) and also update the script inside the installation package.

**Comment by Sup3rson1x** [comment]
> I got the same problem and I fixed this by the following
> 
> # Download the Microsoft GPG public key (in .asc format)
> sudo wget -P /etc/apt/keyrings https://packages.microsoft.com/keys/microsoft.asc
> # Update and modernize APT sources (this command may update sources.list to new format)
> sudo apt modernize-sources
> # Replace the 'Signed-By:' line in vscode.sources with the correct keyring path
> sudo sed -i 's|^Signed-By:.*|Signed-By: /etc/apt/keyrings/microsoft.asc|' /etc/apt/sources.list.d/vscode.sources
> sudo apt update
> Then everything should work. Seems the new apt only use .asc key not .gpg key.
> 
> If everything works for you then you can remove the microsoft gpg key
> 
> sudo rm /etc/apt/keyrings/packages.microsoft.gpg
> See if that helps

How do I revert to backup of previous sources.list? 

![Image](https://github.com/user-attachments/assets/f45be8b0-9b03-4be2-8028-f9bc7f189242)

**Comment by winstonma** [comment]
> How do I revert to backup of previous sources.list?
> 
> ![Image](https://github.com/user-attachments/assets/f45be8b0-9b03-4be2-8028-f9bc7f189242)

You could clean up all vscode files in `/etc/apt/sources.list.d` and reinstall code.

By the way from your message screen it seems that the key file `/etc/apt/keyrings/microsoft.asc` couldn't be found. Maybe it is related to the this line `sudo wget -P /etc/apt/keyrings https://packages.microsoft.com/keys/microsoft.asc`

**Comment by Frajder** [comment]
I should know better and not copy/paste commands. Removing apt repository and install deb manually is seems to me best option to install vscode on my system at this time.

**Comment by priyankarpal** [comment]
it's a non-breaking warning.I guess we don't need to take any action, but Microsoft needs to fix this the key issue.

**Comment by crazyscot** [comment]
We're getting closer. The key file at https://packages.microsoft.com/keys/microsoft.asc has been updated. I manually updated my local copy of `/usr/share/keyrings/microsoft.gpg` (as per the manual install instructions on https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions) and the warning was cleared. 

However after purging and reinstalling code to test it out, the warning reappeared. So I guess the postinst script for code.deb will need to be updated to suit (it has a hard-wired copy of what I presume is the old key).

**Comment by jchiarav** [comment]
This work for me like other user in kali linux. 
# Download the Microsoft GPG public key (in .asc format)
sudo wget -P /etc/apt/keyrings https://packages.microsoft.com/keys/microsoft.asc
# Update and modernize APT sources (this command may update sources.list to new format)
sudo apt modernize-sources
# Replace the 'Signed-By:' line in vscode.sources with the correct keyring path
sudo sed -i 's|^Signed-By:.*|Signed-By: /etc/apt/keyrings/microsoft.asc|' /etc/apt/sources.list.d/vscode.sources
sudo apt update

**Comment by crpb** [comment]
For Inline Key users
```
curl -sSfL https://packages.microsoft.com/keys/microsoft.asc  |sed 's/^$/./;s/^/ /g;1 i Signed-By:' | sudo tee -a /etc/apt/sources.list.d/whatever.sources
```

e.g.

```
Types: deb
URIs: http://packages.microsoft.com/debian/12/prod
Suites: bookworm
Components: main
Snapshot: disable
Architectures: amd64
Enabled: yes
Signed-By:
 -----BEGIN PGP PUBLIC KEY BLOCK-----
 Version: BSN Pgp v1.1.0.0
 .
 mQENBFYxWIwBCADAKoZhZlJxGNGWzqV+1OG1xiQeoowKhssGAKvd+buXCGISZJwT
 LXZqIcIiLP7pqdcZWtE9bSc7yBY2MalDp9Liu0KekywQ6VVX1T72NPf5Ev6x6DLV
 7aVWsCzUAF+eb7DC9fPuFLEdxmOEYoPjzrQ7cCnSV4JQxAqhU4T6OjbvRazGl3ag
 OeizPXmRljMtUUttHQZnRhtlzkmwIrUivbfFPD+fEoHJ1+uIdfOzZX8/oKHKLe2j
 H632kvsNzJFlROVvGLYAk2WRcLu+RjjggixhwiB+Mu/A8Tf4V6b+YppS44q8EvVr
 M+QvY7LNSOffSO6Slsy9oisGTdfE39nC7pVRABEBAAG0N01pY3Jvc29mdCAoUmVs
 ZWFzZSBzaWduaW5nKSA8Z3Bnc2VjdXJpdHlAbWljcm9zb2Z0LmNvbT6JATQEEwEI
 AB4FAlYxWIwCGwMGCwkIBwMCAxUIAwMWAgECHgECF4AACgkQ6z6Urb4SKc+P9gf/
 diY2900wvWEgV7iMgrtGzx79W/PbwWiOkKoD9sdzhARXWiP8Q5teL/t5TUH6TZ3B
 ENboDjwr705jLLPwuEDtPI9jz4kvdT86JwwG6N8gnWM8Ldi56SdJEtXrzwtlB/Fe
 6tyfMT1E/PrJfgALUG9MWTIJkc0GhRJoyPpGZ6YWSLGXnk4c0HltYKDFR7q4wtI8
 4cBu4mjZHZbxIO6r8Cci+xxuJkpOTIpr4pdpQKpECM6x5SaT2gVnscbN0PE19KK9
 nPsBxyK4wW0AvAhed2qldBPTipgzPhqB2gu0jSryil95bKrSmlYJd1Y1XfNHno5D
 xfn5JwgySBIdWWvtOI05gw==
 =zPfd
 -----END PGP PUBLIC KEY BLOCK-----
```

**Comment by rzhao271** [comment]
This issue should now be fixed on Insiders. Closing.

**Comment by TylerLeonhardt** [comment]
spun up DebianUnstable with apt 3... code-insiders installs correctly.

**Comment by killerkalamari** [comment]
Will this fix make it to the stable repo before February 2026?

**Comment by crazyscot** [comment]
> Will this fix make it to the stable repo before February 2026?

1.103.0 just landed in the stable repo (2 days ago as I write this) and it contains the updated key.

**Comment by killerkalamari** [comment]
Interesting, I think I have that version: 
```
$ dpkg -l code
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version            Architecture Description
+++-==============-==================-============-=================================
ii  code           1.103.0-1754517494 amd64        Code editing. Redefined.
```

Ran `sudo apt --reinstall install code` just in case. 

Here's what I see:
```
$ ls -l /usr/share/keyrings/microsoft*.asc
ls: cannot access '/usr/share/keyrings/microsoft*.asc': No such file or directory
```

However, as a workaround I was able to run `sudo wget -O /usr/share/keyrings/microsoft.asc https://packages.microsoft.com/keys/microsoft.asc` and replace the gpg filename in the apt sources with the asc to fix the warning. So I guess I'm good to go now. Thanks!
