### ISSUE TITLE
Right click on request bubble still shows ugly border

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#250471]
Right click on chat request to get context menu. Notice ugly border over full line

![Image](https://github.com/user-attachments/assets/53736047-b851-4b48-8c93-f2b97d20edba)

fyi @bpasero

**Comment by justschen** [comment]
fixed by https://github.com/microsoft/vscode/pull/250569

**Comment by lszomoru** [comment]
Still seeing this when I right click on the bubble itself:

<img width="471" alt="Image" src="https://github.com/user-attachments/assets/dc8d9e9c-b265-4a9f-8e6c-4f51a054b2bc" />

**Comment by justschen** [comment]
ah i thought this one was fixed. just a small css change should be the fix
