### ISSUE TITLE
Incorrect replacements for LSP completion items if server takes too long

### ISSUE THREAD

**Issue by atscott** [microsoft/vscode#251013]
## Does this issue occur when all extensions are disabled?: 

Yes and No. The issue occurs when a single LSP extension takes a while to return completion results (even if those results are empty). I have disabled all installed extensions other than the modified lsp-sample from vscode-extension-samples

```
Version: 1.100.2 (Universal)
Commit: 848b80aeb52026648a8ff9f7c45a9b0a80641e2e
Date: 2025-05-14T21:47:40.416Z
Electron: 34.5.1
ElectronBuildId: 11369351
Chromium: 132.0.6834.210
Node.js: 20.19.0
V8: 13.2.152.41-electron.0
OS: Darwin arm64 24.5.0
```

## Steps to Reproduce:

1. Clone https://github.com/atscott/lsp-example-completions. This is the [lsp-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample) with [small edits](https://github.com/atscott/vscode-extension-samples/commit/2be173cda96613c6900addf171bebaefcaf55bd4) to demonstrate the behavior
2. Install dependencies: `npm i`
3. compile: 'npm run compile'
4. Launch the client
5. Open an HTML file and make its contents be:

```
<div class="something"></div>
<div class="something"></div>
```

6. Go to the second "something" text and ctrl+backspace it and type "so" in quick succession
7. Accept the "something" completion item when it appears and notice that the editor clobbers the closing quote

https://github.com/user-attachments/assets/5f4ccae4-2402-4a6a-bc67-e200ce0b5c3d

If this is expected for some reason, I would expect that at least the documentation needs to be updated to describe how to handle this correctly in the extension. I would not expect to reproduce this so easily with the lsp sample.

**Comment by atscott** [comment]
I have only observed this issue with the built in word completions and can prevent these types of problems with

```
 "[html]": {
  "editor.suggest.showWords": false,
  },
```

Though of course, I then don't ever have word completions.

**Comment by jrieken** [comment]
Can you press `cmd+/` while the `something` suggestion shows. I wanna double check that is from the word-based completions provider. Iff so (which it very much looks like) then your LSP extension shouldn't have any impact. Word-based completions are computed on an independent worker thread, totally isolated from extensions and LSP. The only thing that would affect this is the word definition, e.g the regex that defines what a word is. Wrt can you check the `editor.suggest.insertMode` setting esp if that's redefined for some language?

<img width="701" alt="Image" src="https://github.com/user-attachments/assets/0587c392-a4d7-4bbb-b822-6a79cfd810ee" />

**Comment by atscott** [comment]
Here's the screenshot for when I do the typing quickly:
<img width="1060" alt="Image" src="https://github.com/user-attachments/assets/11549075-6fb2-432a-b3bb-54c8a24c9a48" />

And this is what shows when I pause 1 second between each keystroke (including the ctrl+backspace to delete the word):

<img width="1056" alt="Image" src="https://github.com/user-attachments/assets/d5e29e81-2dff-4b65-8fc7-5a84b744b544" />

I'm not sure that difference matters. I notice the index changes as a hit backspace or retype letters in both cases, but the result is always the same for the initial quick typing where characters at the end of the completion are clobbered.

`editor.suggest.insertMode` is `insert` in both user and workspace settings

**Comment by jrieken** [comment]
This is weird... It doesn't help that I don't reproduce it. I have pushed https://github.com/microsoft/vscode/pull/251082 which adds trace logging when word based completions are computed, esp about the word it is going to replace. This will be in next insiders, which we release once 1.101 is out

**Comment by atscott** [comment]
>  It doesn't help that I don't reproduce it

Ah, that's a bummer! I double checked on another machine and can still reproduce it there as well
```
Version: 1.100.3
Commit: 258e40fedc6cb8edf399a463ce3a9d32e7e1f6f3
Date: 2025-06-02T13:30:54.273Z
Electron: 34.5.1
ElectronBuildId: 11369351
Chromium: 132.0.6834.210
Node.js: 20.19.0
V8: 13.2.152.41-electron.0
OS: Linux x64 6.12.20-1rodete1-amd64
```

https://github.com/user-attachments/assets/bcc4fc8f-3dcb-4782-949a-97717c18c851

**Comment by atscott** [comment]
Update: I did some more debugging and noticed that the `overwriteAfter` was being computed incorrectly because **the default setting is overridden for html to be `replace`** (also noted in https://github.com/microsoft/vscode/issues/183746#issuecomment-1627663938). After switching it to `insert`, the problem goes away. 

Is this expected behavior then? Do you know why `replace` is the default for HTML and why it would have such a nasty outcome for situations like this? Hopefully it’s not actually the right behavior and the missing piece in the investigation was that html actually uses replace by default instead of insert.🤞

**Comment by jrieken** [comment]
> Do you know why replace is the default for HTML and why it would have such a nasty outcome for situations like this?

I let @aeschli comment on that. It was his call back then when the setting was added (5f1b81b4976cc6a31d46befb828c0fe64ce47f49). Still, there seems to be something off because the `"` shouldn't be part of the word

**Comment by RedCMD** [comment]
can confirm

I didn't need to use ctrl+space
simply typing multiple characters **before** the suggestions pop up does the trick

notice how typing many characters
causes it to clobber almost the entire line

https://github.com/user-attachments/assets/744b82f3-0f78-46d5-907f-6502081f2f99

my guess is that repeated completion suggestions are being dropped/ignored
resulting in the replace range becoming out of sync

**Comment by atscott** [comment]
I posed the problem to an AI and it came up with https://github.com/atscott/vscode/commit/e2087390361481a7cd140ac1dfeee98a72ceb44f (after some cleanups) which seems to work... I verified that insert still inserts when completing from the middle and replace still replaces the item. Let me know what you think and if I should open a PR (not sure what the AI policy is for commits here so I can reauthor it if needed)

The simplified calculation _seems_ to make sense. The current cursor position could be seen as just how far the typing resulted in the cursor moving towards the original end of the completion item so the replacement can be calculated as the diff between those two. I admit to not really following how the logic was working before.

**Comment by RedCMD** [comment]
I think the fix would be good
idk about removing the previous code tho

@jrieken added it to fix another replace bug
* https://github.com/microsoft/vscode/issues/10266
* https://github.com/microsoft/vscode/commit/0f6df6304802bec186d990db093345fececb9fc6#diff-e84831ac516f7fa306ab2de61fd6ffcf19d10d84e51e634b0f3c28c9fb6f5b77R330-R343

**Comment by jrieken** [comment]
> simply typing multiple characters before the suggestions pop up does the trick

Thanks for this. With a high value for `editor.quickSuggestionsDelay` I can finally reproduce. Will investigate

**Comment by jrieken** [comment]
Sorry, didn't find the time to fix this today - which was my last day before entering longer period of leave. I'll pick this up in autumn when I am back
