### ISSUE TITLE
Learn more keyboard shorcut not working on macOS

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#253249]
Testing #253096

I pressed Ctrl + K, but Learn More link is not opened.

To be honest I am not convinced we need a shortcut here. I expect users to just do this action once.

<img width="625" alt="Image" src="https://github.com/user-attachments/assets/203cd75f-9f75-4938-a2c5-bdcbe6f9a0aa" />

**Comment by Tyriar** [comment]
@isidorn the keyboard shortcuts are mainly there to be more actionable via just the keyboard as I don't think you can focus that area with only the keyboard. The Windows shortcut isn't good either since it conflicts: https://github.com/microsoft/vscode/issues/253110

**Comment by roblourens** [comment]
I don't see a keyboard shortcut, is that wrong?

<img width="891" alt="Image" src="https://github.com/user-attachments/assets/92a20861-1392-4f31-8bf3-298ae178d977" />

**Comment by meganrogge** [comment]
Yes that's weird @roblourens , is it assigned when you check the keyboard shortcuts editor? we're changing the kb regardless, so that should be fixed.

**Comment by isidorn** [comment]
This still does not work in today's insiders. Thus I will remove the mark Bug (to avoid verification), since it looks like it was closed as duplicate.
