### ISSUE TITLE
TextEditor.edit can control undo/redo stack 1

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#254041]
https://monacotools.visualstudio.com/Monaco/_build/results?buildId=347598&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=da81c1dc-000b-5af1-5a41-3a48a97d898e&s=27eddb93-7805-576c-c80f-37b2176e40f7

```
  2) vscode API - editors
       TextEditor.edit can control undo/redo stack 1:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'hELLO world!'
- 'Hello world!'

      + expected - actual

      -hELLO world!
      +Hello world!
      
      at D:\a\_work\1\s\extensions\vscode-api-tests\src\singlefolder-tests\editor.test.ts:195:11

```

**Comment by alexr00** [comment]
Also

```
  3) vscode API - editors
       TextEditor.edit can control undo/redo stack 2:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'hELLO world!'
- 'hello world!'

      + expected - actual

      -hELLO world!
      +hello world!
      
      at D:\a\_work\1\s\extensions\vscode-api-tests\src\singlefolder-tests\editor.test.ts:212:12

```

**Comment by alexdima** [comment]
I believe the first test that fails leaves the workbench in a broken state / leaves behind stuff which interacts with the current active text editor. https://github.com/microsoft/vscode/issues/254043#issuecomment-3067313969

**Comment by alexdima** [comment]
I think this was fixed via https://github.com/microsoft/vscode/pull/254646

**Comment by alexr00** [comment]
Still happening: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=351087&view=results

**Comment by alexr00** [comment]
And also https://dev.azure.com/monacotools/Monaco/_build/results?buildId=351108&view=logs&j=fc6dc5ac-1218-5601-53e8-73849b99230e&t=ef0b3a54-1de7-50d8-ec24-3deac885437e

**Comment by alexr00** [comment]
Disabling test as there's another failure here: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=352006&view=logs&j=fc6dc5ac-1218-5601-53e8-73849b99230e&t=ef0b3a54-1de7-50d8-ec24-3deac885437e
