### ISSUE TITLE
Integrated Terminal  screen's getting blank after ~15 min idle time

### ISSUE THREAD

**Issue by ulrrmehdi** [microsoft/vscode#254455]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

This issue was addressed few weeks ago, but without a resolution. 

1.  open an integrated  terminal in VS code, and type commend
2. after stop typing, the content of the terminal gets blank after ~15 of not typing in the  terminal, or if not keeping the text editor open. 
3. Resizing the terminal back and forth, does not bring the content of the terminal before the Terminal is blanked out, or vanished. 
4. The only option is to start a new terminal and repeat my workspace settings, the every time (!), this happens with the terminal. 
5. The history of previous command in the vanished content is kept, however, this effect of the terminal blanking out is extremely annoying and disruptive.
6. I did run Start Extension Bisect from the command palette and the the Terminal content vanishing effect has been reproduced. The outcome of it with the message: The problem in the Code  

Please fit it. 
 
I am running VS code in MacOs and open VS Desktop in Azure ML workspace on Linux Ubuntu, I believe.

Thanks!

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/251800 is the only known similar issue to this that I'm aware of. Note that even though you're on mac, this could still happen there is the Azure ML workspace is a Windows box behind the scenes.

Regardless, if you see this on v1.102 [Insiders](https://code.visualstudio.com/insiders/) or later, please open the devtools console (Help > Toggle Developer Tools) and check the console for exceptions. If the terminal goes blank I would expect an exception is being thrown in rendering code in xterm.js, and that's really the only way to check that is the case. A stack trace from there would go a long way towards diagnosing/fixing the problem though.
