### ISSUE TITLE
Can't drag Markdown preview to start a new editor group

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#25854]
- VSCode Version: 1.12 Insiders
- OS Version: Windows 7, 10

Steps to Reproduce:

1. With a single editor group, open a Markdown file, then Markdown: Open Preview (Ctrl+Shift+V)
2. Now try to drag the markdown preview to the side to start a new editor group

The drop is blocked.

If you select another file and then try to drag the markdown preview with only the tabbed heading, it works.

**Comment by bpasero** [comment]
@gregvanl does it work in 1.11?

**Comment by gregvanl** [comment]
@bpasero Yes, this is a regression from 1.11.

**Comment by bpasero** [comment]
@mjbvz I see that dragging the tab over the markdown preview turns the mouse icon into a "drop not allowed" cursor. This could either be the Electron update, or changes we did to the webview within (e.g. context-isolation). A quick test to disable context isolation though did not help. Were there other changes that could have an impact? E.g. CSP settings?

**Comment by dtgriscom** [comment]
Confirmed in VSC 1.19.1 (1.19.1) on OS X 10.10.5: you can't start a new edit group by dragging a Markdown preview to the right edge of the screen.

**Comment by HPLegion** [comment]
Problem persists in VSCode 1.21.1 (Win10)

**Comment by krupenja** [comment]
I cannot repro this with VSCode 1.28.2.

**Comment by HPLegion** [comment]
I agree, this seems to have been fixed, even though it feels a bit "laggy" to me compared to dragging code edit tabs. But it works, guess the issue can be closed now

**Comment by gregvanl** [comment]
Still doesn't work for me in 1.28.2 if the active editor is the Markdown preview. I think the issue is that the Markdown preview can't be a drop location.

**Comment by jlyonsmith** [comment]
You can repro this issue easily.  With a Markdown view open, dragging the tab does not show the new group shadows.  Cmd+T to create a new tab, and with it active, drag the Markdown tab over it.  The new group shadows show up and you can dock the tab.  I'm on 1.32.3 on macOS.

**Comment by vitaminj** [comment]
Still a problem in 1.34 - seems to me the obvious thing to do immediately after opening a preview - to drag it to one side, to see it side-by-side, but you're blocked from doing so unless you switch back to the markdown code first.

**Comment by eamodio** [comment]
So thrilled about this!
