### ISSUE TITLE
Shareable link is not working for none of my projects

### ISSUE THREAD

**Issue by YuslenLopez** [microsoft/vscode#260247]
ADD ISSUE DESCRIPTION HERE

The share link for my website project that I have been using for weeks now seems to not finish loading and gets stuck in a infinite white screen when clicked. I have tried to have friends test it on other accounts and profiles and they get the same thing when clicking on my link. I also tried to stop sharing the code and start again and that did not resolve the matter. The issue seems to persist through even my other shared projects. 
I really need the link because its required for a grade in my online course. Can someone please help me get this resolve ? 

Here is the share link : https://vscodeedu.com/o4ODPK0qdiX4hpW17gFp

Version: 1.102.3
Commit: 488a1f239235055e34e673291fb8d8c810886f81
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by abchatra** [comment]
@YuslenLopez Sorry your link is not working. We are going to investigate.

**Comment by YuslenLopez** [comment]
@abchatra Thank you, I truly don't know what could be causing it. But any help is appreciated.

**Comment by gbongato** [comment]
Hi @abchatra! I am also experiencing the same issue with my project sharing link. 

Link: https://vscodeedu.com/sJte1l69l8iM8IkxhjQW

**Comment by dmitrivMS** [comment]
Testing fix

**Comment by dmitrivMS** [comment]
The fix has been deployed to PROD, both links mentioned above are working now.

**Comment by bamurtaugh** [comment]
Thanks so much @dmitrivMS @abchatra!

I think we can close out this issue - please let us know if folks are still experiencing any issues.
