### ISSUE TITLE
Hotkey hints are not displayed in English [2]

### ISSUE THREAD

**Issue by kirusyaga** [Microsoft/vscode#27333]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|mithril-emmet|FallenMax|0.6.1|
|csharp|ms-vscode|1.9.0|;

---
Addition for the #24361 issue.

Problem is still occuring on Main menu (only if started on Russian keyboard layout), Welcome screen and Home screen:

![2017-05-26_14-56-41](https://cloud.githubusercontent.com/assets/22245072/26493901/bafe27d4-4224-11e7-9b6d-7d5926bcd57a.gif)
![code_2017-05-26_14-57-56](https://cloud.githubusercontent.com/assets/22245072/26493900/bacd6752-4224-11e7-8e73-d70fbe36cae6.png)
![code_2017-05-26_20-31-26](https://cloud.githubusercontent.com/assets/22245072/26505978/7bdf7524-4253-11e7-8fef-fd2140ead2cf.png)

**Comment by kirusyaga** [comment]
In main menu problem also occuring with Russian keyboard layout.
---
![default](https://cloud.githubusercontent.com/assets/22245072/26505666/52df06c2-4252-11e7-9aa8-af40f2ee9c61.png)

**Comment by alexandrudima** [comment]
@kirusyaga The issue is fixed and the fix is available on the Insiders Channel -- https://code.visualstudio.com/insiders

The fix will go on the Stable Channel in ~1-2 weeks with the May 2017 VS Code release.

**Comment by kirusyaga** [comment]
Meanwhile, the error still remains.

![2017-08-07_07-27-05](https://user-images.githubusercontent.com/22245072/29012171-2e11453e-7b42-11e7-9457-e4d04cf5ea7b.gif)

**Comment by alexandrudima** [comment]
@kirusyaga 

That is expected for that specific key. 

The `` ` `` character may be missing or printed on a different physical key on various keyboard layouts.
