### ISSUE TITLE
Support multi-line jsdoc annotations

### ISSUE THREAD

**Issue by ribrdb** [Microsoft/vscode#27777]
- VSCode Version: 1.12.2
- OS Version: macOS 10.12.5

Steps to Reproduce:

1. Open a javascript file with multi-line type annotations. For example:
https://github.com/google/closure-library/blob/master/closure/goog/dom/animationframe/animationframe.js#L61

Expected result:
VSCode highlights the jsdoc.

Actual Result:
VSCode highlights the jsdoc in red like there's an error.

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/vscode/issues/27777 for the syntax highlighting issue and https://github.com/Microsoft/TypeScript/issues/16179 for actually understanding a multiline jsdoc type

**Comment by mjbvz** [comment]
Reopening since it looks like this will not be fixed upstream, see https://github.com/Microsoft/TypeScript-TmLanguage/pull/740

**Comment by mjbvz** [comment]
Fixed by 0ae3ecbf15c65d1acb4fbf77e349fb9d7a5864fe

**Comment by chrisdothtml** [comment]
@mjbvz has this fix been released yet to the official release stream? Seems to be still not working in v1.33.1
