### ISSUE TITLE
JSON Schema does not support enums of complex objects

### ISSUE THREAD

**Issue by TheCodeGnome** [Microsoft/vscode#28010]
- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|copy-syntax|atian25|0.5.1|
|python|donjayamanne|0.6.4|
|auto-close-tag|formulahendry|0.4.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|;

---

Steps to Reproduce:

1. Create a JSON Schema.
2. Define an enum of objects for one property, ie. "enum": [{ "a" : 1, "b" : 2; }].
3. Associate the schema to a json file and insert the enum (using ctrl+space or otherwise).
4. Check problems in the json file.

I shouldn't be seeing any problems, but am getting a warning: 
{ message: 'Value is not accepted. Valid values: [{"a":1,"b":2}]' }. This is despite using ctrl+space to fill the values (and avoid typos). I've also tried it with all extensions deactivated, and it's still present.

I have independently verified this should work using the schema validator by [Newtonsoft](http://www.jsonschemavalidator.net/).

Screenshot of problem:
![image](https://cloud.githubusercontent.com/assets/15162807/26766734/5a2bdc9c-4965-11e7-98dc-320ab8b8d7be.png)

Screenshot verifying json and schema:
![image](https://cloud.githubusercontent.com/assets/15162807/26766724/29122eae-4965-11e7-906e-b9044822b596.png)

Files attached as txt (please rename to json) as zip isn't attaching for some reason.
[schema.txt](https://github.com/Microsoft/vscode/files/1050834/schema.txt)
[file.txt](https://github.com/Microsoft/vscode/files/1050835/file.txt)

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode-json-languageservice/commit/f88d9fbef3e92b2a86d808b637629b91927e04f2

**Comment by TheCodeGnome** [comment]
Still seeing the issue in the latest Insider.
![image](https://user-images.githubusercontent.com/15162807/27102414-2ac60f1e-5053-11e7-8449-b0fe718eb9c7.png)

Can you confirm whether it should be fixed there?
![image](https://user-images.githubusercontent.com/15162807/27102397-202e74ce-5053-11e7-8ef4-94df90bfc1a0.png)

**Comment by aeschli** [comment]
Should be in tomorrow. Thanks for testing!

**Comment by TheCodeGnome** [comment]
Just tested and it appears to be fixed. Thanks for the quick turn-around.

**Comment by dbaeumer** [comment]
I use that in the tasks.json schema
