### ISSUE TITLE
Experimental Decorators error present with option set in config

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#28097]
_From @cfrank on May 22, 2017 14:37_

```
Version 1.13.0-insider
Commit 3bb9b5314ef50bd8225aba0565cadc6ca19bc821
Date 2017-05-18T06:26:49.576Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Linux
```

![Error](https://f.xor.al/SdKzk.png)

This error appears even after adding the `experimentalDecorators` flag in `.eslintrc`

```
"parserOptions": {
    "ecmaVersion": 7,
    "ecmaFeatures": {
        "experimentalObjectRestSpread": true,
        "experimentalDecorators": true,
        "jsx": true
    },
    "sourceType": "module"
},
```

_Copied from original issue: Microsoft/vscode-eslint#244_

**Comment by dbaeumer** [comment]
The error message comes from the JS support in VS Code (see [js] in the error message). ESlint errors are prefixed with [eslint].

**Comment by mjbvz** [comment]
@cfrank Yes this issue is coming from our JS support.

To fix it, please try creating a [`jsconfig.json` file])https://code.visualstudio.com/Docs/languages/javascript#_javascript-project-jsconfigjson_ at the root of your project with the contents: 

```json
{
  "compilerOptions": {
      "experimentalDecorators": true
  }
}
```

**Comment by mwarger** [comment]
@mjbvz This solution doesn't work for me.  Any thoughts?

**Comment by mjbvz** [comment]
@mwarger Are you sure the file is part of your `jsconfig` or `tsconfig`. Try running the `Go to project configuration` command to double check

**Comment by ntomallen** [comment]
Just wanted to comment that this solution _did_ work for me. The error went away after restarting VS Code.

**Comment by serge-nikitin** [comment]
I have the same problem.

**Comment by MikeKovarik** [comment]
So this is still a problem and the issue should not have been closed. I just today tried switching to VS Code with a project that uses decorators a lot. Adding `jsconfig.json` did not help, nor did restarting VSC so my code keeps lighting up in red. For now I'm sticking to Sublime Text.

VSC version: 1.16.0
My jsconfig.json
```
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true
    },
    "include": [
        "src/**/*"
    ]
}
```

**Comment by mjbvz** [comment]
@MikeKovarik In a JS file that has this error, try running the `JavaScript: Go to project configuration` command. Does this open the `jsconfig.json` file? If not, please open a new issue so that we can investigate this

**Comment by kenta88** [comment]
@mjbvz after created the jsconfig.json dont forget to restart vsc. This should fix ;)

**Comment by itLead797** [comment]
I saw the problem consistently with this combination
"compilerOptions": {
    "experimentalDecorators": true,
    "target": "es6",
  }

The problem was resolved with this combination
"compilerOptions": {
    "experimentalDecorators": true,
    "target": "es5",
  }

**Comment by ProteanDev** [comment]
still getting the [eslint] Parsing error: Unexpected character '@'
