### ISSUE TITLE
VSC show a message with placeholder for typescript version check

### ISSUE THREAD

**Issue by jimjaeger** [Microsoft/vscode#28371]
- VSCode Version: 1.13.0
- OS Version: Windows 7

Steps to Reproduce:
After update today a message pops up that talk about different typescript versions but does not replace the typescript version in the message:
"TypeScript ({1}) wird für Editor-Funktionen verwenden"

Btw. The grammar of this sentence is also wrong.

**Comment by mjbvz** [comment]
Is this the entire warning message you see:

```
TypeScript ({1)} wird für Editor-Funktionen verwenden. TypeScript ({0}) wird global auf Ihrem Computer installiert. Unter Umständen treten inkonsistente Kompilierungsfehler auf.
```

**Comment by jimjaeger** [comment]
Right. It is the message... In this case {0} was replaced but not {1}.
Before the last update I see this message before but there were both replaced.

**Comment by mjbvz** [comment]
Thanks. I think the german translation of `({1})` was mangled into `({1)}` in vscode 1.13: https://github.com/Microsoft/vscode/blob/release/1.13/i18n/deu/extensions/typescript/out/features/bufferSyncSupport.i18n.json

I believe that only german was effected

This has been fixed in master and should be fixed in the current insiders builds: https://github.com/Microsoft/vscode/blob/master/i18n/deu/extensions/typescript/out/features/bufferSyncSupport.i18n.json

**Comment by roblourens** [comment]
I see that it was fixed, then the string was removed for some reason - https://github.com/Microsoft/vscode/blob/master/i18n/deu/extensions/typescript/out/features/bufferSyncSupport.i18n.json

I don't know if it's a temporary thing or there's a problem?

**Comment by mjbvz** [comment]
Weird, looks like `versionMismatch` was removed entirely at some point but I still see it in the code. @danyeh any idea what is going on with this string?

**Comment by mjbvz** [comment]
Now the string entry has been restored but the incorrect `({1)}` placeholder is back

**Comment by roblourens** [comment]
I upvoted your entry. Not sure how to use Transifex admin powers to ensure the right one wins

**Comment by roblourens** [comment]
As discussed, won't hold up June release for thsi.

**Comment by mjbvz** [comment]
I completely removed this string this month. Next i18n update should reflect this
