### ISSUE TITLE
APT repository has bad hash metadata

### ISSUE THREAD

**Issue by evmar** [Microsoft/vscode#28735]
Our mirroring tool fails because the file contents hash don't match the metadata:

failed to download package 60c3b935404f79ff3ea84e7be86523501de474dfa20ebf6ac7c05e211d684935 from URL http://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.14.0-1496812357_amd64.deb: hash mismatch for http://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.14.0-1496812357_amd64.deb: got 1b2e12c96927eb6437a4dbb5c40d6f6431812dc9372b265bb30f4f93396247d6; expected 60c3b935404f79ff3ea84e7be86523501de474dfa20ebf6ac7c05e211d684935

I think maybe you need to regenerate the hashes(?).

**Comment by Tyriar** [comment]
Thanks for the report, I notified the team we submit the packages to. I published a new version so I think the problem should be resolved.

**Comment by evmar** [comment]
This is not fixed.  Repro:

1) download http://packages.microsoft.com/repos/vscode/pool/main/c/code-insiders/code-insiders_1.14.0-1496812357_amd64.deb and http://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages

2) $ sha256sum code-insiders_1.14.0-1496812357_amd64.deb 
1b2e12c96927eb6437a4dbb5c40d6f6431812dc9372b265bb30f4f93396247d6  code-insiders_1.14.0-1496812357_amd64.deb

```
$ egrep 'Filename|SHA256' Packages | grep -A 1 code-insiders_1.14.0-1496812357
Filename: pool/main/c/code-insiders/code-insiders_1.14.0-1496812357_amd64.deb
SHA256: 60c3b935404f79ff3ea84e7be86523501de474dfa20ebf6ac7c05e211d684935
```

**Comment by Tyriar** [comment]
@evmar I'll forward this to them thanks.

**Comment by evmar** [comment]
It appears this is fixed.
