### ISSUE TITLE
No next and previous keyboard shortcuts for Find widget in Integrated Terminal

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#29661]
- VSCode Version: 1.14 Insiders
- OS Version: Windows 7

Steps to Reproduce:

1. Open Find widget and search for a string with several matches

There are no keyboard shortcuts for previous and next match (Shift + F3, F3).

**Comment by gregvanl** [comment]
Found during https://github.com/Microsoft/vscode/issues/29479

**Comment by fabiospampinato** [comment]
I agree that those actions should have the same shortcuts used in the editor's search widget bound to them, by default.

**Comment by cleidigh** [comment]
@Tyriar 
I will add these key bindings

**Comment by cleidigh** [comment]
Addressed by PR #31418

**Comment by Tyriar** [comment]
Reopening, https://github.com/Microsoft/vscode/pull/32113 didn't resolve

**Comment by cleidigh** [comment]
@Tyriar 
I have these functions from the summer work that was not merged.  I can update and post a PR.
Reminder : We also needed to add these to extension and mardown editors.(

**Comment by Tyriar** [comment]
I think ideally F3/shift+F3 would work the same everywhere 👍
