### ISSUE TITLE
Deleting a folder and undo from Finder is not retrieving the folder in VS Code

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#29766]
Testing #29478

- Open a Folder in VS Code
- Assume above folder has a sub folder say `Sub Folder`
- Go to Finder and delete `Sub Folder`
- Observe that it is removed from VS Code - 👍 
- Undo the action in Finder by `cmd+z`. Folder comes back in Finder

Expected folder to come back in VS Code but not.

**Comment by bpasero** [comment]
It looks like the undo event causes a CHANGED event on the folder instead of an ADD event. There are no ADD events for the contents of the folder either. Marking as important (not for June though) because I think this is a pretty bad regression from e.g. Chokidar where this works properly. 

Does not reproduce on Windows btw.

**Comment by Tyriar** [comment]
It looks like this has been fixed:

<img width="728" alt="screen shot 2017-07-21 at 7 05 15 am" src="https://user-images.githubusercontent.com/2193314/28466993-1771beba-6de3-11e7-81bc-a037f37ea206.png">

**Comment by bpasero** [comment]
@Tyriar I am still getting it and I am not 100% sure the only change that got in meanwhile (https://github.com/Axosoft/nsfw/pull/24) would have an impact.

I see it on macOS by just deleting a top level folder from the workspace and the undoing that. In the video below I use single folder workspace but nsfw is enabled via settings:

![flicker_chrome58](https://user-images.githubusercontent.com/900690/28469032-3dc6f7ae-6e35-11e7-9e3c-48e9c60d950d.gif)

**Comment by bpasero** [comment]
I opened: https://github.com/Axosoft/nsfw/issues/31

If we are unlucky then maybe we need to add manual code to detect this case and convert a `MODIFIED` event on a folder that was previously `DELETED` as `CREATED` (and all the children inside).

**Comment by bpasero** [comment]
Somehow this started to work for me again. Can others try too? When you use insiders nowadays you can simply open a single folder and you will get `nsfw` as watcher.

**Comment by bpasero** [comment]
Hm nevermind, still seeing it, but not in all cases. This is super weird...
