### ISSUE TITLE
running docker-compose from Powershell terminal yields python error "unknown encoding: cp65001"

### ISSUE THREAD

**Issue by MaurGi** [Microsoft/vscode#30350]
- VSCode Version: 1.13.1
- OS Version: Windows 10 Enterprise 1703

Steps to Reproduce:

1. Install Docker for Windows
2. run docker-compose from the integrated powershell console, you see the following:

```
PS C:\...> docker-compose -f .\docker-compose\sre-datahub-storm.yaml up
Traceback (most recent call last):
  File "logging\__init__.py", line 872, in emit
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
LookupError: unknown encoding: cp65001
Logged from file service.py, line 488
Traceback (most recent call last):
  File "logging\__init__.py", line 872, in emit
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
LookupError: unknown encoding: cp65001
Logged from file service.py, line 488
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 118, in perform_command
  File "compose\cli\main.py", line 941, in up
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
LookupError: unknown encoding: cp65001
Failed to execute script docker-compose
```

Reproduces without extensions: Yes/No - unsure

**Comment by chrmarti** [comment]
Does this work when run from a Powershell terminal? It does not look like a VSCode problem. Maybe https://github.com/Microsoft/BashOnWindows/issues/2009 ?

**Comment by MaurGi** [comment]
Hey –
It does work from the Powershell terminal – no problem on that side –

Mauro.

**Comment by chrmarti** [comment]
Current versions of Python should know cp65001 from what I read. Please make sure you are running the latest version of docker-compose. @Tyriar Are we setting the pty's encoding ourselves?

**Comment by Tyriar** [comment]
This seems similar to some of the comments in https://github.com/Microsoft/vscode/issues/19665 which should have been fixed with a Windows update. @MaurGi are you up to date on Windows, specifically you need to have installed the KB4020102 fix.

**Comment by DirtyJerz** [comment]
This is still happening. 

Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:59:46.104Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

w10 pro
1709 Build 16299.15
