### ISSUE TITLE
PHP namespaced trait breaks syntax highlighting

### ISSUE THREAD

**Issue by LachlanArthur** [Microsoft/vscode#30448]
- VSCode Version: Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T18:36:31.751Z)
- OS Version: Windows_NT ia32 10.0.15063

Steps to Reproduce:

1. Make a PHP class that uses a namespaced trait

Example:
```
<?php
class Foo {
	use Some\Thing;

	// Comment
	public $name = 'foo';

	public function __construct() {
		$this->doStuff();
	}
}
```

Reproduces without extensions: Yes

**Comment by rrkandala** [comment]
I'm having same problem.
Using 'use' inside a class breaks syntax highlighting.

**Comment by Danktuary** [comment]
Yep, same here. It's worth noting that it only happens on traits that go deeper than the base namespace; single-level traits work normally. What I mean is: `use Thing;` works normally, but `use Some\Thing;` breaks syntax highlighting.

Here's a screenshot for those curious about this:

![VSC PHP trait broken syntax highlighting](http://i.imgur.com/YEQ5hTr.png)

**Comment by rizkyramadhan** [comment]
Erm...  me too ?

![image](https://user-images.githubusercontent.com/126301/28109794-7f012f18-671a-11e7-810c-1de9d9ca0805.png)

The syntax highlighter breaks after the second `use \Yard\Lib\JsConvert`

**Comment by roblourens** [comment]
Maybe related to https://github.com/Microsoft/vscode-textmate/issues/50

**Comment by lagbox** [comment]
I am seeing syntax highlighting being broken when a multiline use statement is in a class (regardless of namespace concerns). Randomly down the file it corrects itself.

**Comment by roblourens** [comment]
Is is the same as this issue, or is a different issue specific to a multiline use statement? Can you post an example?

**Comment by lagbox** [comment]
I am seeing the issue that this issue is pointing out and additionally what I mentioned.
First screenshot is the issue as described by the OP. 
![screenshot from 2017-07-12 15-58-25](https://user-images.githubusercontent.com/3752215/28137622-faafbe26-671b-11e7-9e55-e676e43bf043.png)
Second screenshot is correct highlighting in regards to not having the `use` across multiple lines.
![screenshot from 2017-07-12 16-04-28](https://user-images.githubusercontent.com/3752215/28137625-ff8b070c-671b-11e7-8f9a-3bde021ff6be.png)
Third is multiline breaking the highlighting.
![screenshot from 2017-07-12 16-04-43](https://user-images.githubusercontent.com/3752215/28137627-01c65198-671c-11e7-9ce3-fb74e22a8e9f.png)
Sorry can create a new issue if needed.

**Comment by lagbox** [comment]
This is a better representation of the OP's issue (without the multiline, to not confuse the issues)
![screenshot from 2017-07-12 16-20-18](https://user-images.githubusercontent.com/3752215/28138252-188bd70c-671e-11e7-81c5-d3ec4dc19347.png)

**Comment by LachlanArthur** [comment]
I've found a workaround until this gets fixed:

Add `// }` on a new line after the `use`. This fixes the formatting again.

So the original example would be:

```
<?php
class Foo {
	use Some\Thing;
	// }

	// Comment
	public $name = 'foo';

	public function __construct() {
		$this->doStuff();
	}
}
```

**Comment by rrkandala** [comment]
```php <?php
use \Yard\Lib\JsConvert as JsConvert;
use Some\Thing as Thing;

class Foo {
	    use JsConvert;
            use Thing;
	// }

	// Comment
	public $name = 'foo';

	public function __construct() {
		$this->doStuff();
	}
}```
This above code doesn't break any syntax highlighting.

**Comment by robclancy** [comment]
This was broken in the release so surely they know the fix if they look at this issue? Expected it to be in the first round of bug fixes.

**Comment by luxifer** [comment]
The highlighting of a PHP file is broken for this case:

```php
<?php

namespace Foo;

class Bar
{
    use \Foo\Bar\Baz;

    public function baz()
    {
    }
}
```

It produces the following highlight:

<img width="271" alt="capture d ecran 2017-08-03 a 16 50 37" src="https://user-images.githubusercontent.com/419078/28927857-ed50988e-786b-11e7-9ca0-02170e025377.png">


- VSCode Version: 1.14.2
- OS Version: macOS 10.12.6

Steps to Reproduce:

1. Use class with fully qualified namespace like `use \Foo\Bar\Baz`;

Reproduces without extensions: Yes

The issue has been resolved in https://github.com/atom/language-php/pull/249 so I wonder when the PHP grammar will be synced.

Thanks!

**Comment by roblourens** [comment]
Please try it out in today's Insiders build, it's fixed there.

**Comment by luxifer** [comment]
I'll try tomorrow. Thanks!

**Comment by lagbox** [comment]
Still broken after latest release (1.15.0)

**Comment by roblourens** [comment]
Works for me, can you post an example that shows the problem?

**Comment by luxifer** [comment]
The problem is fixed in the insider build

<img width="267" alt="capture d ecran 2017-08-11 a 08 59 43" src="https://user-images.githubusercontent.com/419078/29203794-81637ad4-7e73-11e7-8447-47d069d2dd03.png">

Also in the 1.15.0

<img width="235" alt="capture d ecran 2017-08-11 a 09 01 13" src="https://user-images.githubusercontent.com/419078/29203823-b291a252-7e73-11e7-99b6-ac1f3d0e63dc.png">

**Comment by lagbox** [comment]
@roblourens will break my issue off into its own issue. The multi-line use statement is still broken.

**Comment by zessx** [comment]
Still needs work (#8074)

**Comment by pbarnum** [comment]
Same issue is happening with me, only this time it happens when I rename a trait method.

![highlighting](https://user-images.githubusercontent.com/6970266/32040845-f2b606f8-b9e6-11e7-956f-2e09f074e896.png)

**Comment by Danktuary** [comment]
@pbarnum Are you on stable or insiders? Seems to work fine for me on the insiders build (updated sometime yesterday afternoon).

![trait method renamed](https://i.imgur.com/waGJyup.png)

**Comment by pbarnum** [comment]
Whoops, sorry! I should be running the stable release. I'm running linux mint, and this is taken from the "About" window.
```
Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:57:00.652Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
