### ISSUE TITLE
JavaScript if block without brackets indentation

### ISSUE THREAD

**Issue by AshleyScirra** [Microsoft/vscode#30933]
- VSCode Version: Code 1.14.1 (2648980a697a4c8fb5777dcfb2ab110cec8a2f58, 2017-07-13T19:18:47.188Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: none

Steps to Reproduce:

As of the 1.14 update, typing JS code has really annoying indentation behavior. I can't figure out why it changed and I can't find any relevant settings to try to change.

To reproduce, type this:

`if (cnd)` `<enter>` `{`

Expected result (pre-1.14):

```
if (cnd)
{
```

Observed result (1.14):

```
if (cnd)
    {
```

This is the worst indentation style!

**Comment by rebornix** [comment]
@mjbvz do you think our `indentNextLinePattern` is a little bit unnecessary for TypeScript/JavaScript ? It seams that this pattern is bothering ppl instead of helping them out most of the time as writing brackets around blocks is more common.

**Comment by rebornix** [comment]
Related issues https://github.com/Microsoft/vscode/issues/31027 , https://github.com/Microsoft/vscode/issues/30859

**Comment by mjbvz** [comment]
I think enough libraries and developers do write single statement `if`s that removing `indentNextLinePattern` entirely will be more annoying. Can we modify the regex to work around this?

**Comment by rebornix** [comment]
@mjbvz I'm thinking about taking one step back on `indentOnType`.  Usually the only time that `indentOnType` kicks in and helps you out is when the content matches `decreaseIndentPattern`. Maybe a workaround here is only adjust the indentation when it matches `decreaseIndentPattern` otherwise users decide what the indent level they want.

Right now I don't know how to make the regex aware of context in this case.

**Comment by mjbvz** [comment]
Yes I think the expected behavior here would be to indent the next line only if there is no other content after the cursor. Would we be able to achieve that without `indentNextLinePattern`?

**Comment by simonl65** [comment]
Expected behaviour should be same as pre 1.14, please.

**Comment by robotbebop** [comment]
I am having this exact same issue, but i can't find the `indentNextLinePattern` setting. Also its only happening if I have a project open, opening JavaScript files outside of a project it works fine.

**Comment by ericdrobinson** [comment]
Does anyone know what feature addition/change caused this to occur? I'm interested in understanding why this change came in as it impacts me every time I write control flow code (`if`, `for`, `while`, etc.). This has been a _constant_ source of frustration with TS/JS files since the 1.14 release (am currently on 1.14.2).

**Comment by anickle060193** [comment]
A temporary work-around is to downgrade to [version 1.13](https://code.visualstudio.com/updates/v1_13).

**Comment by simonl65** [comment]
OK, I'm back - I don't have any setting with `indentNextLinePattern` - I'm now on 1.14.2

@rebornix Why can't the _feature_ that was added in 1.14 be removed - this is **really annoying**

**Comment by davidstlyoui** [comment]
@mjbvz you marked this as duplicate with #31272 and closed it, then you went and close #31272 and marked it as duplicate with this.
Most issues are pointing to this one as the real one.

**Comment by anickle060193** [comment]
@davidstlyoui This issue hasn't actually been closed. I think Github is just displaying the duplicate message incorrectly for this issue.

**Comment by mjbvz** [comment]
`indentNextLinePattern` is an internal configuration name. There is no user setting to change it

@rebornix Have you had a chance to take another look into this issue?

**Comment by simonl65** [comment]
@mjbvz Why have you closed this? I thought this was where we were tracking this issue (which is why [31272](https://github.com/Microsoft/vscode/issues/31272) and [30691](https://github.com/Microsoft/vscode/issues/30691) were closed)

**Comment by ericdrobinson** [comment]
@simonl65 It looks like he closed it as part of [this commit](https://github.com/Microsoft/vscode/commit/e9764d95bcab518996f4273379f764a683303d51). It looks like typing "Fixes [Issue #]" into the commit message will also _close_ that issue as part of the workflow. See [this help page](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by mjbvz** [comment]
@simonl65 I closed this issue with a change that should resolve the problem. Please try it out in the next VS Code insiders builds

**Comment by simonl65** [comment]
I just learned something! Thanks - I'll give that a try when vscode next updates.

**Comment by simonl65** [comment]
Hmm, so I couldn't wait - I downloaded the insiders build (1.15.0-insider)!

Sorry to say - **it's worse**! I now get the following:
```javascript
if(x)
    {
```

...that's four spaces before the `{` (1.14 only gave 2 spaces)

If it helps, my non-default settings are:

```javascript
{
    "editor.insertSpaces": false,
    "editor.tabSize": 2,
    "workbench.sideBar.location": "left",
    "editor.wordWrapColumn": 82,
    "editor.renderIndentGuides": true,
    "editor.rulers": [
        82,
        120
    ],
    "window.zoomLevel": 0,
    "workbench.iconTheme": "vscode-great-icons",
    "workbench.colorTheme": "Visual Studio Dark",
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
}
```

This is a clean install of 1.15.0-insider - no extensions added.

What have I missed?

**Question:** Why can't the auto-indent stuff just revert to how things were in 1.13 - that worked fine?

**Comment by mjbvz** [comment]
@simonl65 This change just went in and is not yet in any build. You need to wait for the next nightly insiders build to pick up this change

**Comment by simonl65** [comment]
@mjbvz Oops - over eager! Will try it tmz. Thanks for your efforts 👍

**Comment by simonl65** [comment]
@mjbvz Sorry to say: it's not changed - still indenting the `{`.

BTW: Correct behavior in PHP - this affects JS & TS.

This is a real PITA

**Comment by mattbierner** [comment]
@simonl65 Please record a gif of exactly what you are seeing. Here's what I see:

![aug-05-2017 17-13-17](https://user-images.githubusercontent.com/212305/28999615-9241f37e-7a01-11e7-91ee-d1309c8691ce.gif)

**Comment by simonl65** [comment]
@mjbvz Not sure how to ad  a gif, so here are the steps:

1. Type `if(1)`
2. Hit `enter`
3. Cursor drops to next line **but is indented** (should be below the `i` of `if`
4. Type `{`
5. Type `enter`
6. Result is:
```
if(1)
  {
    |
  }
```

Expected result:
```
if(1)
{
  |
}
```

**Comment by Rxswyers** [comment]
@mattbierner This is on the insiders build (1.16.0), I believe it's the same issue.
![2017-08-11_08-27-11](https://user-images.githubusercontent.com/6971304/29213001-55079758-7e6f-11e7-86db-845ec62bb75b.gif)

**Comment by AshleyScirra** [comment]
The original issue still reproduces in 1.15. It is not fixed!

**Comment by cdaringe** [comment]
![indent-loco mov](https://user-images.githubusercontent.com/1003261/29331146-5501269a-81b0-11e7-9b13-ca985b51a843.gif)

watch me shift these lines down. ^

doh!  is this the correct place for this report, @mjbvz, or shall i add my GIF elsewhere?

thx :)

**Comment by ericdrobinson** [comment]
@Rxswyers Yes. That is exactly the issue. It is truly frustrating.

**Comment by simonl65** [comment]
@cdaringe I'm not sure that's the same issue - I guess you're using `ALT + downArrow`?

I don't get that in a javascript file either - which language mode are you in?

**Comment by AshleyScirra** [comment]
Can someone re-open this issue since it is not fixed? Otherwise I will probably file it again. It's really annoying.

**Comment by cdaringe** [comment]
@simonl65 

> ALT + downArrow?

yep!

> I don't get that in a javascript file either 

javascript language setting.

**Comment by mjbvz** [comment]
The original reported issue was fixed. I've opened #32653 to track to track the other case discussed in the comments

**Comment by ericdrobinson** [comment]
@mjbvz But that isn't the case at all. Here's what the original reported issue read as:

>To reproduce, type this:
>
>`if (cnd)` `<enter>` `{`
>
>Expected result (pre-1.14):
>
>```
>if (cnd)
>{
>```
>Observed result (1.14):
>
>```
>if (cnd)
>    {
>```

As explained in many subsequent comments, **this is still an issue**.

You happened to fix a related bug, just not the one described in this issue. Your [fix gif](https://github.com/Microsoft/vscode/issues/30933#issuecomment-320477719) shows that you type `if (1) {}` and then go back and hit enter between the if-condition and the braces. That is _*not*_ the flow that the bug describes.

**Comment by AshleyScirra** [comment]
@mjbvz - the original issue I reported does still reproduce for me in 1.15. It's not fixed.

**Comment by Rxswyers** [comment]
It's fixed in the insider release. Be patient for it to get to the stable build. @AshleyScirra

**Comment by simonl65** [comment]
Yay - that fixed it! @mjbvz Thank you.

**Comment by azarus** [comment]
@mjbvz its still not fixed, just grabbed the latest version on a different fresh installed cmputer and this is still here. This is ridiculous.

**Comment by simonl65** [comment]
@azarus I don't think the fix has made it to the release version yet. I'm guessing you're on version 1.15.x, but the fix is in 1.16.0-insider - which you can download from [https://code.visualstudio.com/insiders](https://code.visualstudio.com/insiders)

**Comment by azarus** [comment]
Awesome.
