### ISSUE TITLE
Emmet increment/decrement by 0.1 Error

### ISSUE THREAD

**Issue by sou-lab** [Microsoft/vscode#31281]
- VSCode Version: 1.14.2
- OS Version: MacOS 10.12.6

Steps to Reproduce:

1. Emmet Increment/Decrement by 0.1

![decrementnumberbyonetenth](https://user-images.githubusercontent.com/1183509/28501856-ffb25246-701f-11e7-8362-5f251b9a9702.gif)

Reproduces without extensions: No

**Comment by ramya-rao-a** [comment]
Nice catch @sou-lab !

Thanks for logging the issue. Fixed with https://github.com/Microsoft/vscode/commit/9b6cc9f774f424b4e8a91d4a2d3d4ad8efb9cfb9

Looks like you have set `emmet.useNewEmmet` to `true`
Please do try out rest of the emmet commands and file issues if you find any

I intend to set emmet.useNewEmmet` to `true` by default in the next update (1.15)

**Comment by sou-lab** [comment]
Thank you for support😃
I try Insiders on Monday.

**Comment by jens1o** [comment]
Err. This issue is not fixed when using hex-color codes(I'm hunting for edge cases 👅).
Having this:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        body {
            background-attachment: fixed;

            color: #231230;
        }
    </style>
</head>
<body>
    
</body>
</html>
```

Select the code:
![image](https://user-images.githubusercontent.com/11234139/28733737-d3520d2e-73dd-11e7-9843-db90b17799e9.png)

Decrement it by 0.1:

![image](https://user-images.githubusercontent.com/11234139/28733748-dd564f24-73dd-11e7-9e10-793776c97b74.png)
Not bad, isn't it?

**Comment by ramya-rao-a** [comment]
@jens1o Am confused... what is not fixed?

**Comment by jens1o** [comment]
Hex-Colors can't be decremented by 0.1 nor incremented at all, because Hex Colors only can be three or six digits number prepended by a `#`. So it's not possible to decrement them by this step, so I would expect an error message.

Personally, I would like that the steps will be converted to hex number and then let the math happen. At the moment, emmet does not care about different number systems.

**Comment by ramya-rao-a** [comment]
Updated to show error message if unable to evaluate given expression

**Comment by jens1o** [comment]
Err, that's not fixing this problem? You can still increment hex color codes, can't you?

**Comment by ramya-rao-a** [comment]
> So it's not possible to decrement them by this step, so I would expect an error message.

I was addressing the error message part of your comment

We can use #31681 which you logged to track the hex color code issue

**Comment by jens1o** [comment]
Okay.
