### ISSUE TITLE
Typing experience is really bad when markdown preview is opened and word wrap is off

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#32395]
- VSCode Version: Code 1.15.0 (8b95971d8cccd3afd86b35d4a0e098c189294ff2, 2017-08-09T20:09:15.006Z)
- OS Version: Linux x64 4.10.0-26-generic
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.9.4
ActiveFileInStatusBar|Ros|1.0.3
lorem-ipsum|Tyr|1.0.0
sort-lines|Tyr|1.3.0
vscode-terminal-here|Tyr|0.0.5
vscode-svgviewer|css|1.4.2
vscode-eslint|dba|1.2.11
git-project-manager|fel|1.3.2
annotator|ryu|0.10.1
vscode-header-source|ryz|1.1.0
gitblame|wad|2.1.0

(2 theme extensions excluded)

---

Not sure if this is a regression or not but it happens in 1.15.0

Steps to Reproduce:

1. Open a markdown file
2. Open markdown preview to side
3. Make sure word wrap is off (I think this is the default)
4. Type on a long line

![peek 2017-08-12 14-24](https://user-images.githubusercontent.com/2193314/29244315-2d64c8a0-7f6a-11e7-9ad9-b792d4b12c2c.gif)

Reproduces without extensions: Yes

**Comment by Tyriar** [comment]
I'm not a fan of how it shifts the editor even when word wrap is on as well, makes me stop typing to find the cursor.

**Comment by mjbvz** [comment]
I'm unmarking this as a candidate fix for July recovery:

* I don't think it is a regression. 
* To hit this, you have to explicitly turn off word wrap in markdown (disabling it normally keeps it enabled in markdown files).

**Comment by mjbvz** [comment]
@Tyriar I'm having trouble reproducing this. Can you test the latest insiders build and also share any other markdown settings you may have in your workspace

**Comment by Tyriar** [comment]
Still happens on latest insiders, on macOS too. My settings:

```js
{
  "editor.autoClosingBrackets": false,
  "editor.codeLens": false,
  "editor.folding": false,
  "editor.fontFamily": "Hack",
  "editor.formatOnPaste": false,
  "editor.minimap.enabled": true,
  "editor.minimap.renderCharacters": false,
  "editor.renderControlCharacters": true,
  "editor.renderIndentGuides": true,
  "editor.renderWhitespace": "boundary",
  "editor.roundedSelection": false,
  "editor.rulers": [ 80, 100, 120 ],
  "files.useExperimentalFileWatcher": true,

  "explorer.autoReveal": false,
  "explorer.openEditors.visible": 0,

  "extensions.autoUpdate": true,
  "extensions.ignoreRecommendations": true,

  "files.defaultLanguage": "markdown",
  "files.hotExit": "onExitAndWindowClose",

  "terminal.integrated.cursorBlinking": true,
  "terminal.integrated.scrollback": 5000,
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",

  "window.reopenFolders": "all",
  "window.title": "${rootPath}${separator}${activeEditorName}${separator}${appName}",

  "workbench.editor.enablePreviewFromQuickOpen": false,
  "workbench.welcome.enabled": false,
  "workbench.iconTheme": "seti",

  // Languages
  "typescript.check.tscVersion": false,
  "[markdown]": {
    "editor.quickSuggestions": false
  },

  // Extensions
  "gitProjectManager.baseProjectsFolders": [
    "$HOME/dev",
    "%USERPROFILE%\\Documents\\dev"
  ],
  "gitProjectManager.maxDepthRecursion": 2,
  "window.zoomLevel": 0,
  "workbench.colorTheme": "Sapphire"
}

```

**Comment by mjbvz** [comment]
Thanks @Tyriar. I can repo it now, but only reliably in the express readme https://raw.githubusercontent.com/expressjs/express/master/Readme.md

The bug seems to be an extra call to `revealLine` after we render the document. This event is trigged by scrolling in the markdown webview but we should disabled these events when we programmatically scroll the document or when we first load the document (which also produces a scroll event). It looks like it is not disabled in this case

**Comment by mjbvz** [comment]
Should be fixed by new markdown editor -> preview scroll sync added in 1.21

**Comment by chrmarti** [comment]
Still an issue:

![mar-01-2018 15-32-49](https://user-images.githubusercontent.com/9205389/36850051-fff66e24-1d65-11e8-8b7e-bf8c7ad306bb.gif)


VS Code version: Code - Insiders 1.21.0-insider (9a04587cc6b42c332609a08bfd7e2dbeac592c21, 2018-03-01T06:39:57.509Z)
OS version: Darwin x64 16.7.0

**Comment by mjbvz** [comment]
Should be fixed in the current insiders (tested with the long longs on the express release notes)
