### ISSUE TITLE
Git: Illegal value for `line`

### ISSUE THREAD

**Issue by will-l-h** [Microsoft/vscode#32681]
I'm getting an error if I attempt to Revert Selection on a line if the first line in the tracked file has been deleted. If I manually restore the first line, the revert works as expected.

- VSCode Version:
1.15.1
1.16.0-insider
- OS Version:
Windows 10 x64

- git version 
2.13.3.windows.1 ( also upgraded to 2.14.1.windows.1)

Steps to Reproduce:

1. Delete the first line in a file tracked by Git
2. Modify any line after what is the new line 1, e.g. line 4
3. Revert Selection on the modified (line 4)
4. A prompt appears that states Git: Illegal value for `line` : Open Git Log, Close
5. If you clear the git log just prior to the attempt, it's still empty after

Reproduces without extensions: Yes

**Comment by Jeyanthinath** [comment]
@joaomoreno I will take this up :+1:

**Comment by joaomoreno** [comment]
Nice, should be fun! :+1:

**Comment by gagangupt16** [comment]
@will-l-h How are you reverting selection?

**Comment by will-l-h** [comment]
I assigned a keyboard shortcut, but by default you can get to it from the ellipsis menu in the upper right (put the cursor on a line with changes first).

![image](https://user-images.githubusercontent.com/14348617/30548319-d3be114a-9c5f-11e7-9d59-bf324ccc4467.png)

**Comment by ktravelet** [comment]
I just ran into this too.

OSX: 10.12.6
VS Code: Version 1.16.1 (1.16.1)
git: git version 2.11.0 (Apple Git-81)

to reproduce:
1. stage file for commit
2. open staged file in side by side
3. highlight line(s) to unstage
4. click '...' -> 'unstage selected ranged'

git log is empty as well.

**Comment by danawoodman** [comment]
I'm getting this intermittently. Any updates on this? I seem to get it when popping from my git stash.

**Comment by Jeyanthinath** [comment]
@danawoodman can you able to replicate the issue with particular steps, if so it would be helpful.

**Comment by danawoodman** [comment]
@Jeyanthinath if I figure it out I will post here!

**Comment by will-l-h** [comment]
The issue I originally described is still present. @Jeyanthinath I see your PR isn't merged, any chance you could address the comment and conflict?

**Comment by Jeyanthinath** [comment]
ok I will check and fix it @will-l-h , but I need to check on insider builds also :thinking:

**Comment by JensMadsen** [comment]
it also happens when "stage selected ranges"

**Comment by joaomoreno** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/34781

**Comment by will-l-h** [comment]
@Jeyanthinath I just checked using yesterdays build and the issue is still there.

@joaomoreno can you re-open?

**Comment by joaomoreno** [comment]
@will-l-h What build is that? Which commit?

**Comment by will-l-h** [comment]
- VSCode Version: Code - Insiders 1.19.0-insider (951f5a20fc820e32a65ca05bb87af86f65027470, 2017-12-12T21:32:54.471Z)
- OS Version: Windows_NT x64 10.0.14393
- Git: version 2.14.1.windows.1 and version 2.15.1.windows.2

**Comment by joaomoreno** [comment]
The insider release is currently frozen, while we ramp up for our release. The fix is still not in it. Wait a couple more days for the next update.

**Comment by will-l-h** [comment]
@joaomoreno 

Should the fix be available now? If so, I'm still getting the error anyhow.

Version 1.20.0-insider
Commit 08ec16001adaab8a86183431f6aec09209caa4ab
Date 2017-12-15T05:15:38.886Z

**Comment by joaomoreno** [comment]
@will-l-h What are the exact steps to reproduce it in that build?

**Comment by will-l-h** [comment]
@joaomoreno 

Same as original post; expanded here with a little more detail:

Delete the first line in a file tracked by Git
Go down a few lines of code and modify any line after what is the new line 1, e.g. line 4, save the file
On the Working Tree view of the file, place cursor on the edited line (line 4), select Revert Selected Ranges from the ellipses menu in the upper right
A prompt appears that states Git: Illegal value for line : Open Git Log, Close
If you clear the git log just prior to the attempt, it's still empty after


Currently seeing it in:
Version 1.20.0-insider
Commit bcc46316b497d1a316dd47ae86481df3ca5784ee
Date 2017-12-18T11:57:54.810Z

**Comment by Jeyanthinath** [comment]
@joaomoreno can you please confirm my commit is there ? if so I can re-test the code an update my PR !

**Comment by joaomoreno** [comment]
@Jeyanthinath Your commit is definitely there... but I just verified what @will-l-h says. Using those exact steps still causes the error. There must be something else there...

**Comment by joaomoreno** [comment]
It was an oversight on my part, while merging the PR...

@will-l-h Thanks for the verification!

**Comment by LukaHorvat** [comment]
Still getting this on
![](https://i.imgur.com/oeqHtp6.png)

Can't really say how to reproduce since it just started happening while I was staging changes on my project.

**Comment by rebornix** [comment]
I verified that the issue @will-l-h described no longer exists. @LukaHorvat if you can provide reproduce steps, we can take a further look then.
