### ISSUE TITLE
Create an option to position the intellisense parameter info top or bottom.

### ISSUE THREAD

**Issue by rhyek** [Microsoft/vscode#33752]
Currently the parameter info tooltip is always placed above the cursor. This is often quite annoying since it completely blocks code in the above lines and you sometimes need to look at your context to know what values to give the parameters.

Example:
![image](https://user-images.githubusercontent.com/702922/30005026-e9034dec-9096-11e7-80c0-1a23814ca15c.png)

**Comment by yume-chan** [comment]
In Visual Studio, hold <kbd>Ctrl</kbd> for a while, the tooltip will dim down to let me see through it.

I think it's better than changing the position via a config.

**Comment by rhyek** [comment]
Thanks. I never need it to be above the cursor. Pressing ctrl every time sounds unnecessary.

**Comment by rhyek** [comment]
I seriously have to hit Esc every time this tooltip pops up. It is probably the most annoying thing to me about VSC.

Do you know if there is a way a plugin could fix this?

**Comment by joaomoreno** [comment]
The problem with positioning it down is what happens to Intellisense? Should it then go up?

The <kbd>Ctrl</kbd> idea is something that we've brought up every now and then, we should just implement it.

@rhyek Most people how are annoyed by it simply disable it.

**Comment by rhyek** [comment]
I have never seen an instance where both tool tips are shown at the same
time. Once you pick a method from intellisense, it is hidden and  parameter
info appears.

**Comment by joaomoreno** [comment]
When parameter hints is open, simply trigger <kbd>Ctrl Space</kbd>.

**Comment by rhyek** [comment]
Seriously?

On Oct 2, 2017 1:52 AM, "vscodebot[bot]" <notifications@github.com> wrote:

Closed #33752 <https://github.com/Microsoft/vscode/issues/33752>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/33752#event-1273534665>, or mute
the thread

**Comment by rhyek** [comment]
Can this please be re opened? It had activity 7 days ago and I'm not sure what additional information is needed. Probably just and over eager configuration on the bot.

**Comment by joaomoreno** [comment]
The issue was closed because you didn't reply to my last message:

> When parameter hints is open, simply trigger <kbd>Ctrl Space</kbd>.

**Comment by rhyek** [comment]
@joaomoreno, sorry. I addressed the ctrl suggestion earlier.

> You also didn't address my point about disabling. Why don't you simply disable parameter hints?

I don't want to disable them, because they are useful to me sometimes.

> no matter where it will be positioned, it will overlay text. You happen to give more importance to the text above the cursor; others to the text below it.

Yes, but the IntelliSense tooltip shows below the cursor by default and this is very common among code editors and IDEs with code hinting capabilities. Why should the parameter info tooltip be different?

I am asking for an **OPTION** to modify its placement, not to place it below for everyone.

The reason for my preferring the tooltip to be below is:

- IntelliSense is already shown below
- You write code from top to bottom. You don't want a huge tooltip covering up your context. The most useful context that will help you keep track of what you are doing is probably going to be correlated by the order of execution of your program (usually top to bottom).
- Some examples of what context I mean:
  - What was the name of the variable I needed to pass as a parameter here?
  - If I am writing my parameters in a multiline format, I want to look at what parameters I already gave.
  - What method am I calling?
  - Where am I at currently?

**Comment by rhyek** [comment]
In the image I gave as an example, the tooltip completely covers up **three** previous lines of code. It often feels like I'm writing code blind when this happens.

**Comment by chriseppstein** [comment]
As I suggested in issue #35596, other possible UI solutions exist other than anchored to the text.

> Other possible config options or solutions might be to have the pop up displayed in a fixed location when triggered by typing (E.g. the upper right corner of the editor window) because sometimes I need to refer to the code below as well :)

or you could even imagine a documentation pane that can display contextual documentation without any overlay at all, such a thing could take precedence vs the overlay, if open.

**Comment by lerran80** [comment]
This is also an issue for me. My impression is:

1) I don't need to see parameter hints all the time. (Does anyone do?)
2) If showing all the time, anywhere you show will be invasive and distracting. (Unless you put in the footer of the editor, maybe?)
3) Why not just allow users to disable them and have a keyboard shortcut to show a hint only when need? In that case, it wont matter if it is above or bellow.

**Comment by jprichardson** [comment]
This is an issue for me. Just recently started experimenting with VSCode from Atom. While I really enjoy using VSCode, this annoys the heck out of me as it covers all the code above and doesn't feel consistent with the method intellisense. I'd love to see an option to place this below the current line. Thanks for your hard work!

**Comment by pillaiindu** [comment]
I filed similar issue some days ago, @ramya-rao-a showed sent me this link, so I'm linking my issue also here. https://github.com/Microsoft/vscode/issues/42937

**Comment by JobLeonard** [comment]
Would it be  possible to make the pop-up to avoid the mouse cursor? Or have the preview dismissed on a click?

I understand why that might not be the default behaviour, as it would break the ability to scroll through larger previews, and in some cases select text inside of it:

![hover-scroll2](https://user-images.githubusercontent.com/259840/36900173-7e140552-1e22-11e8-84d1-4369aa8d5900.gif)

![hover-scroll](https://user-images.githubusercontent.com/259840/36899975-c13ff166-1e21-11e8-97cc-8a94368efcce.gif)

Although I think having a preview that big is a bug anyway - opened #44928 for that.

By the way, is that text selection a feature or a bug? I guess one preview comes from type inference, the other from `JSdoc`, but the behaviour and styling is inconsistent between them.

If the ability to select text in the type-inferred pop-up isn't a feature, then perhaps clicking could dismiss/move the pop-up? Currently clicking does _nothing_ with type annotation previews, which actually is a little frustrating. Either make it select the text or dismiss it, but at least give it a purpose.

![hover-cursor](https://user-images.githubusercontent.com/259840/36899943-a076d170-1e21-11e8-82a2-35d5397ee32e.gif)

**Comment by cparadeise** [comment]
TLDR; +1

I absolutely support these ideas for improving intellisense. I have recently switched from Brackets to Atom to VSCode, and I love VSCode for it's amazing built in intellisense. But it does start to feel a lot like the old MS Word CLIPPIE. Sorry if I triggered some haunting memories of past. 

This is kind of like the Chrome DevTools window (stretching the comparison ever so slightly). By default it opens within the same window, effectively crushing your browser view with all the information provided. But, you have the option to pop out the window into it's own. The only problem I have with this is when I am switching between many open windows, if the DevTools window would be able to be focused the same time as the browser window, I would be so happy. If certain tools in VSCode could pop out, in a manageable, clean way, I would use it for sure. I also like the idea of using the mouse click to drag the window. 

I'm still a young developer, hopefully, I can contribute more soon to the actual development of these tools.

**Comment by marcomorain** [comment]
When the tooltip appears on top of the code it's really jarring. I would love to see it places in a better location.

![image](https://user-images.githubusercontent.com/448001/40836488-d31e1ce6-658e-11e8-81a7-7c882fb3a564.png)

**Comment by kespindler** [comment]
Love the idea of having this in a documentation pane instead of inline. I'm encountering this issue and a doc pane seems to make the most sense.

**Comment by aviau** [comment]
Yes, brilliant! Please make a documentation pane option. I would let it enabled all the time and it wouldn't annoy me at all. I love hints but they are so annoying if they overlay text.

**Comment by tomboland** [comment]
I honestly think that the only thing that's so frustrating about the current positioning is that, a lot of the time, I want to refer to the line above the one I'm typing on.  What I've noticed about the other code-editor I use, Oni, is that the positioning of the parameter-list popup and the like is just higher by that one extra line, which is a subtle, and at the same time huge difference!

**Comment by nate-datafinch** [comment]
+1 to moving this anywhere other than directly above the current line.  It's a bad design choice.  Working with any decently documented library means this thing eats up 8 or 9 lines of code above the current line.

We've known for a long time that temporal and spatial locality are a thing.  I want to reference nearby lines, and lines that I've edited recently (which are usually nearby, and most often right above the current line). Don't freaking hide those from me. 

It's incredibly jarring.  Honestly, the lines above the current code are almost always more valuable than the hint.  Until this is changed I have this feature completely disabled.  Which is a shame, because it's a very cool feature, the positioning just sucks.

**Comment by SnugglyCoder** [comment]
+1 to have an option to set it to be below current line instead of on top of current line. It is very annoying as current lines reference lines before and them being covered up is very annoying.

**Comment by DaveCousineau** [comment]
If you're in a method or function, the entire meaning of what you're typing is 100% dependent on the code ABOVE the cursor, not the code below it. Very rarely is the code beneath the current line relevant to that line, but the code above it almost always is.

**Comment by rhyek** [comment]
We could also have the tooltip and intellisense stack below the cursor.

**Comment by mxmzb** [comment]
i could also imagine to have to suggestions always popup on one fixed position (e.g. bottom right corner of the window) as opposed to following the current cursor position in any way.

**Comment by sinesc** [comment]
Doesn't have to be too complicated: Top right editor corner if that's where the cursor is not, otherwise bottom right corner.
Should apply to everything that opens in the editor and hides content below.
Options for both the default position and the fallback position would be a nice bonus.

**Comment by axe-z** [comment]
I mean how is that not fixed !! Atom does it right 
![capture d ecran le 2018-11-11 a 10 36 11](https://user-images.githubusercontent.com/27289270/48652508-dd969180-e9cd-11e8-89d6-6730f7fddcb9.png)

**Comment by kingpalethe** [comment]
Same issue here. Need to find a way to move the hint below the current line.

**Comment by P0pzi** [comment]
+1 SO ANNOYING.

Trying to referance the previous line 99% of the time, cockblocked by it constantly.

PLEASE add the option to move it below the cursor, aka **where it should be.**

**Comment by samson-sham** [comment]
+1
Not only parameter hints covers the code,
it also **caught** my arrows keys, this is a huge problem.

Can someone make a shortcut for parameter hint such that we can opt-in to make it show?

**Comment by icyJoseph** [comment]
+1 
As a way out, perhaps it could have some opacity? so that we can read through. I mean, if positioning it under the cursor is so hard.

**Comment by FeliveNdrell** [comment]
This is an issue for me too. Option to customize tooltip default position would be really nice.

**Comment by NickWoodward** [comment]
+ 1

How is this still a thing?

**Comment by drewlustro** [comment]
Please allow us to offset the tooltip with CSS. Some minor relative positioning edits could do it.

**Comment by polidore** [comment]
+1

**Comment by tomboland** [comment]
I took the survey and pretty much begged for this to be the one thing they fix!

**Comment by pumpkinlink** [comment]
+1

**Comment by willtalmadge** [comment]
Can we do what spacemacs+typescript layer does? They just put all the tips into a minibuf at the bottom of the screen. It collapses completely if there's no info. I'd love this so much, even if we had to install an add-on to get the feature.

<img width="972" alt="Screen Shot 2019-07-16 at 2 04 26 PM" src="https://user-images.githubusercontent.com/2081287/61329864-290a7500-a7d3-11e9-842a-0da669f9f0ef.png">

**Comment by eacartwright** [comment]
hey you microsoft tell me you're working on this

**Comment by xproofx** [comment]
I really can't deal with this level of bullshit. Fuck you Visual Studio Code.  Let me disable this altogether.

**Comment by polidore** [comment]
ask for a refund.

**Comment by damiantoczek** [comment]
> I seriously have to hit Esc every time this tooltip pops up. It is probably the most annoying thing to me about VSC.
> 
> Do you know if there is a way a plugin could fix this?

Yes, change to Atom Editor hahaha.

**Comment by satscape** [comment]
If you scroll down so the line of code you're typing is at the very top, the tooltip does appear under it, but of course you now can't see the line above as it off the screen. We just need a "show the godamn tooltip below the line all the time" tickbox/boolean. MonoDevelop used to do this brilliantly years ago.

**Comment by chevtek** [comment]
This is also my one complaint with VS Code currently. I love the suggestion of just offsetting it upward by one line. That would help tremendously. Why we can't have options around this tooltip is a mystery to me.

**Comment by Chigozie391** [comment]
Any solution yet

**Comment by satscape** [comment]
Two years and still not fixed. I've uninstalled vscode and moved to [Geany IDE](https://www.geany.org/) which DOES this already, but to be fair, so does Sublime, Atom, MonoDevelop and more.
[screenshot from Geany IDE displaying parameter list BELOW where I'm typing](https://imgur.com/a/904RLNA) <- see, it's really easy to do.

**Comment by buggymcbugfix** [comment]
Anything happening on this front?

**Comment by SebastianKristof** [comment]
This has to be a feature ordered directly by the Powers That Be, otherwise this level of silliness is hard to explain. How difficult is this to fix? If you can't move it, make it transparent!

**Comment by sarachai** [comment]
I love you VS Code, but this is a total UX bug, and my boyfriend probably gets mad at me 800x per day every time that tooltip pops up, because I recommended he try VS Code. We're all programmers here, most of us have built our share of tooltips —  so we know it's not impossible to move that thing somewhere else. 

So then it seems there must be some kind of moral or philosophical objection to it at this point? Is it supposed to help us cultivate mindfulness, being aware of the context of our code at all times?

**Comment by blisterfingers** [comment]
Just tried vscode and was loving it until this issue began to frustrate me. Seeing this simple issue ignored after so long has really killed my enthusiasm for the product.
Just in case though, the suggestion of moving it up by one line wouldn't be good enough for me. I often need to see quite a few lines above. 
Aligning it to the right of the screen, putting in a seperate pane or even just letting my drag it to a place I like would all suit me fine.

**Comment by philn16** [comment]
This sucks, but one workaround is add
```json
"editor.parameterHints": false,
```
to `settings.json`, and use the `editor.action.triggerParameterHints` shortcut key when you need parameter hints. `ctrl+shift+space` by default

**Comment by nwg** [comment]
> In Visual Studio, hold Ctrl for a while, the tooltip will dim down to let me see through it.
> 
> I think it's better than changing the position via a config.

@yume-chan  can you still dim it with control? Not working for me.

**Comment by boneus** [comment]
There is a similar issue #30797 
Here is its last message:
"This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it."

There are 25 days left at the moment. Let's upvote!

**Comment by tomboland** [comment]
This is important, get voting! Putting it below the cursor is better than nothing!

**Comment by yume-chan** [comment]
@nwg 

> can you still dim it with control? Not working for me.

I mean Visual Studio, not Code. I'm not using Visual Studio recently so I'm not sure if it's still in.

**Comment by um8ra** [comment]
#90475

**Comment by filipre** [comment]
After reading the whole thread, I still don't understand why it is a challenge to place to pop-up **below** the cursor as most editors do and I would appreciate any additional insights into it. Maybe someone could just roughly describe the steps to accomplish this? However, if it is really an unsolvable problem, then I would like to point out this suggestion, which is also fine for me: https://github.com/Microsoft/vscode/issues/33752#issuecomment-425626433. 

My current workaround is disabling the popup and triggering it manually, as https://github.com/Microsoft/vscode/issues/33752#issuecomment-568530834 describes. Another dirty solution is to make the popup transparent, similar to https://github.com/Microsoft/vscode/issues/22439 but I don't like this approach either.

**Comment by tjcrowder** [comment]
A configuration option would be the way to go:

* Above (current behavior)
* Below (rhyek's requested behavior)
* Configurable fixed location

I'd love it if these were always visible in the upper right-hand corner, for instance.

----

For now, though, I do what [philn16 said](https://github.com/microsoft/vscode/issues/33752#issuecomment-568530834): Set `editor.parameterHints.enabled` to `false` and use <kbd>Ctrl+Shift+Space</kbd> (or whatever you have `editor.action.triggerParameterHints` configured to) when you want the hints. Verbose version:

1. Go to File > Preferences > Settings (<kbd>Ctrl+J</kbd>)
2. Type `parameterhints`
3. Untick **Editor > Parameter Hints: Enabled**
4. Use <kbd>Ctrl+Shift+Space</kbd> (or whatever you have `editor.action.triggerParameterHints` configured to) when you want the hints.

**Comment by gorsat** [comment]
It's a huge bummer to have to disable such a cool feature simply because there's no way to configure the position of the popup. Sigh. Oh well. Moving on...

**Comment by jIdle** [comment]
Strange that this is still an issue when all other popup style info boxes can have their transparency changed. Why hasn't the parameterhints box been given this change also? Seems like a lack of consistency doesn't it?

**Comment by satscape** [comment]
September 3rd is this bug's 3rd birthday, I plan on making a cake for it. I will only be providing the ingredients though, you will have to compile it yourself. It's 3 now, but it won't be long before it's off to school, then college...where do the years go?...

**Comment by DanielRosenwasser** [comment]
This seems like a pretty annoying papercut. It's part of why we addressed the nuisance of `,` triggering signature help in object literals in https://github.com/Microsoft/vscode/issues/51731.

That said, there's a few things I could imagine:

* a smarter heuristic so that when signature help is displayed and `Enter` is hit, signature help moves from the top to the bottom. This ensures you can glance back at whatever you already wrote.
* a key combo to toggle signature help from the top/bottom at a given point in time.
* maybe the option described here

**Comment by freMea** [comment]
A bar/panel at the bottom of the editor that would appear with no delay could do the trick too.

But with the new flexible layout released in may 2020, a parameter info view that one can move everywhere would be nice too. Maybe a new activity being oriented towards code documentation that would implements the current parameter info tooltip as well as other documentation aggregator like DevDocs would be nice and complete.

I have a workaround to have access to this info tooltip without being annoyed by them. I explain it here #102198 because this highlighted another bug.

Here are other related issues more or less duplicate : #51253, #16221 (an awesome feature suggestion), #15667, #30797, #63144.

**Comment by SneakyFish5** [comment]
Just to confirm, based off https://github.com/microsoft/vscode/issues/33752#issuecomment-331409645, I can assume most people who want this setting would be ok with the `parameterHints` widget being covered by the `Intellisense` widget temporarily, like in the recording below:

![Klaq2BUJ39](https://user-images.githubusercontent.com/32284796/92522638-acabd000-f1e4-11ea-864e-f64a69199a50.gif)

**Comment by jaduffy007** [comment]
Boggles my mind that an option for positioning is still not available.  Call me weird, but I find it so annoying, I'm going to back to JetBrains products.  Seems VS Code devs are being incredibly stubborn around this...despite regularly providing tons of great updates otherwise.  Oh well.

**Comment by cvlvxi** [comment]
+1

**Comment by satscape** [comment]
My joke comment above was marked as spam.  I've uinstalled VScode and intstalled Jetbrains Rider, it has this feature already. You can make a free buggy IDE or you can make a non-free IDE that is fit-for-purpose, it seems. Still subscribing to this bug, because I want to see how it ends and when it ends.

**Comment by cherrixstudios** [comment]
Please let us configure this pop up.  It is so distracting!

**Comment by pcjmfranken** [comment]
A monstrosity like the one in my screenshot below is going to be super annoying and distracting no matter where in the editor you render it. In these cases, where the contents are this illegibly formatted and even truncated, I'd rather have this tooltip dynamically not show at all.

<img width="571" alt="paramhints" src="https://user-images.githubusercontent.com/17924090/96385640-7c693100-1195-11eb-82fa-5377e42e5c22.png">

I feel like occurrences of this have steadily grown alongside the popularity of string literal union type guards for function params. In my screenshot this was spawned by a very simple but strictly typed object value accessor for a CSS in JS library.

**Comment by vesche** [comment]
Posting here to add my support for this issue. This pop-up often blocks my code and it's not configurable at all. It would be awesome to see some configuration options added to this pop-up or a key to press to make the pop-up translucent. Thank you!

**Comment by kuzlich** [comment]
Any news or updates on this issue? This is still an actual problem that often reminds about itself :( 
Snx!

**Comment by scu** [comment]
I can't believe with all the frustration this has created for developers that this issue has not been addressed. It is literally the only thing keeping me from switching FT to vscode.

**Comment by Arrioc** [comment]
I really hate this feature, and I am wasting precious study time trying to configure settings.json to disable it. This box pops up and $@#-blocks me. It's distracting and obstructive. Please fix this. I cant wait till I graduate in 4 months.. the only reason I'm putting up with this bs is so I can follow along seamlessly with my guides which use VSC.

**Comment by tshinnic** [comment]
It is a strange thing when people can't appreciate how irksome a misfeature is, or even that it is a misfeature. Take Adobe's Brackets editor. Tried it, and immediately and amazingly found it couldn't do bracket-bouncing (aka toggling aka matching). And their reaction to complaints was much like "Really? Gee, I suppose we could do that in a future version..." Brackets couldn't do brackets, and they couldn't see a problem beforehand?

Obscuring code as you're writing is not a feature. Every JS tooltip/popup package I've seen allows positioning variations as needed so as _not_ to obscure. Why did they go to that effort?

**Comment by MrCodels** [comment]
Also posting to voice my support with this issue, it is really anoying. I've gone down the route of disabling it and bringing it up when needed but I would like the option of changing the window's default position to be below like it is in Visual Studio and then have Intellisense below that (if both of them are open at the same time).

**Comment by chinux23** [comment]
Voicing my support for this.

This happened to me while I was typing and need to see what code was above my current line.  

Oops!

<img width="629" alt="Screen Shot 2020-12-04 at 1 52 37 PM" src="https://user-images.githubusercontent.com/387737/101218545-19920300-3638-11eb-8d9d-d7bd2c8528d7.png">

**Comment by jprichardson** [comment]
My company, [Exodus](https://www.exodus.io) / https://github.com/exodusmovement is willing to **put a 1 BTC bounty** down for an intellisense placement configuration option ("above" as it is now, or "below" as it should be). At the time of this writing, 1 BTC is approximately $19,000 USD. 

If we do this, this bounty campaign would need to expire before the end of December. 

I don't write code anymore - but this Github issue is still one that I subscribe to and I'm surprised that [3 years later](https://github.com/microsoft/vscode/issues/33752#issuecomment-346419956) it's still not fixed. So we're effectively paying this bounty to spare my inbox 😄 

Suggestions on how we should go about this bounty campaign? 

At minimum, I'd like some acknowledgement from the VS Code team that they'd be open to accept a PR for this fix should the PR meet their standards.

**Comment by SneakyFish5** [comment]
@jprichardson I'm not going to lie, that comment motivated me to look into this issue again haha. I rebased all my changes onto `master`, and the branch can be found [here](https://github.com/SneakyFish5/vscode/tree/parameter-hints-position). If you could test it out and let me know what you think, that would be great.

Or if you're unable to test, here's a little recording, feedback is much appreciated:

![U6AryhfvNH](https://user-images.githubusercontent.com/32284796/101272712-58b57680-3754-11eb-9efc-f4e8ac77d65c.gif)

Specifically, I just want to reiterate[ my previous comment](https://github.com/microsoft/vscode/issues/33752#issuecomment-689107872) that the intellisense would cover this up. I didn't get any verbal feedback on that, so I want to confirm, is that alright? It was an issue brought up earlier by a maintainer, so I'm not sure if they'd reject any PR I make on those grounds.

**Comment by tjcrowder** [comment]
@SneakyFish5 

Your change looks like a **big** step the right direction!

> Specifically, I just want to reiterate my previous comment that the intellisense would cover this up. I didn't get any verbal feedback on that, so I want to confirm, is that alright? It was an issue brought up earlier by a maintainer, so I'm not sure if they'd reject any PR I make on those grounds.

I don't see that as an issue. First off, it's an option, so if that bothers people they can keep using it the way it is now. Secondly, even doing that it's a huge improvement on what's there now!!

**Comment by scu** [comment]
My observation is intellisense prioritizes over parameter hints in the stack, so I certainly hope they accept your PR. Great work!

**Comment by rhyek** [comment]
Would it be possible to have a third option to have parameter hints below and then intellisense below (or to the right of) those?

**Comment by jprichardson** [comment]
Nice work @SneakyFish5! 

Now we just need someone from the VS Code team to confirm their acceptance of such a change and we could get this wrapped up before our deadline of December 29th 23:59 UTC.

**Comment by rhyek** [comment]
Although I think it's great that this issue is gaining some traction, the proposed solution suffers from a similar problem to the one this entire issue is about: previous relevant contextual information is being blocked from view by new information.

I'd rather we not go for the most immediate (but incomplete) solution for the sake of closing out the issue, personally. If people are bothered by the updates to the thread they can always unsubscribe.

**Comment by tjcrowder** [comment]
@rhyek - I agree that @SneakyFish5's solution shouldn't *close* the issue. It is a good first step, and I'd vastly prefer the code below rather than above be blocked (the option their solution enables). But it shouldn't close the issue. Other choices for that option should be available in future, including showing the information in a panel that can be docked elsewhere (for instance, under the file list).

So for me next steps are:

1. Review and merge @SneakyFish5's initial start
2. Continue working on other options

Now, people will say "but if we take this solution nothing further will be done" and that's a danger; people need to keep advocating (at least, the ones for whom this isn't good enough). The counter to that, though, is "perfect is the enemy of good." Three years later, not taking a first step because we want the all-singing, all-dancing solution seems counter-productive. Incrementalism FTW! (I know, it's nearly 2021, "FTW" is so over now. But... ;-) )

**Comment by SneakyFish5** [comment]
> Although I think it's great that this issue is gaining some traction, the proposed solution suffers from a similar problem to the one this entire issue is about: previous relevant contextual information is being blocked from view by new information.
> 
> I'd rather we not go for the most immediate (but incomplete) solution for the sake of closing out the issue, personally. If people are bothered by the updates to the thread they can always unsubscribe.

I agree this would be preferable, however when I looked into it last time, I couldn't figure out where intellisense determined its position. I can try and look into it again sometime this weekend for sure.

**Comment by freMea** [comment]
No news from VSC Team.

@SneakyFish5 Did you send a PR ?

**Comment by Pingear** [comment]
Here is an interesting case, a simple method in a type script, yes, I know that I have already returned the value above, but in spite of this, I continue to write the code, I want to delete the above code later, it is more convenient for me. But due to this stupid pop-up system, I am unable to write in the editor until I follow the order of the text editor.

https://user-images.githubusercontent.com/16469484/102930815-d9d77200-44a5-11eb-8e4f-8e26550ab984.mp4

**Comment by stedben** [comment]
I would love to be able to offset the tooltip. By pixels or percentages. I am a new coder and the help seems really helpful at times. In my thinking, a person who relies on the tooltips certainly doesn't need it covering up the code they just wrote.

**Comment by morkeltry** [comment]
Obviously, allow a setting to offset the tooltip to whichever position the user decides to set it at.

Default behaviour for any kind of program that accepts text, whether it be a word processor, code editor, in-browser UI should be that not paying attention to visual feedback (or not being able to see, whether due to human accessibility issue, or due to computer lag) does not obstruct the user from doing what they are doing.

It says a lot about Microsoft as an employer that this point, which seems to be obvious to 90% of devs, has not been acted on :/

**Comment by ruifortes** [comment]
It makes one wonder if coorporations are trying to maintain a certain number of annoyances on open source software after making it good enough to slow down independent open source alternatives... but why??... what possible reason could there be?...  ;-)

**Comment by baroquedub** [comment]
+1 for positioning offset: top/bottom/left/right, with percentage or pixel distance (spacing)

This drives me so mad. Hate it when the IDE gets in the way of just getting on with coding.

**Comment by laurentp89** [comment]
I'm writing to support this issue, I think the offset would be a good solution.

**Comment by pathnirvana** [comment]
I have been using vscode for a while now and this is the biggest pain point - can't believe this has been open for 4 years 

some intelligent way to only show these hints for rarely used functions or not show again for the same function if the user has already closed by esc

**Comment by eboody** [comment]
Not that I know what I'm talking about, but this seems like something really simple to implement...

**Comment by procule** [comment]
Nobody (I think) suggested it but... why not make the popup draggable ? 
Sometimes you don't care about the code before, sometimes you do. 
Just make the window popup like it is right now and allow the popup to be dragged out of the code you want to see. After the popup is closed, it resets the position as default for the next one.

Instinctively, the first thing I tried when I needed to see the code under the popup was to try to drag it out of the way. After 20 minutes of looking at the settings to change the behaviour, I made a Google search and ended up here.

So, simple solution: make that popup draggable ! It even highlights with a blue contour when you click on it, so the events are there.

**Comment by baroquedub** [comment]
> why not make the popup draggable

Like that a lot!

**Comment by zbandhan** [comment]
#why not make the popup draggable
and dockable

**Comment by hughperkins** [comment]
vscode, please fix this. I hate having to choose between not being able to render parameter hints at all, and not being able to see my code. Neither are great options.

**Comment by freMea** [comment]
Meanwhile, as a workaround, just disable and use the shortkey to display when needed or/and use the the [Doc View](https://marketplace.visualstudio.com/items?itemName=bierner.docs-view) extension.
```json
"editor.hover.enabled": false,
```

**Comment by rconde01** [comment]
@SneakyFish5 I'm trying to understand the status here...did you ever submit a PR? If not, why not? If so, did it get rejected? Link?

**Comment by NickWoodward** [comment]
I'm done with it. Turning it off entirely.

**Comment by craigc40** [comment]
Often, when I find a line of code I want to edit, it's above where my mouse is. So I move the mouse upward. As I get close to the line, I end up briefly over the line below and the hover pops up, obscuring the line I want to click on to start editing.  Having the tip pop up directly above the cursor is a consistent pain to deal with.
And directly below the cursor would cause a similar issue when the line I want to edit is below my mouse.

Please provide a means for a user to set the location of tooltips/hovers/popups.

(I understand I can increase the delay and mitigate this, but that slows me down for cases where I do want the popup)

**Comment by swilkewitz** [comment]
It's ridiculous that a 4-month feature request with this much demand is still neglected 4 years later

Here's a [stopgap solution](https://www.reddit.com/r/vscode/comments/cun7f1/is_there_a_way_to_disable_those_popups/exykq3k?utm_source=share&utm_medium=web2x&context=3) that some of you might like, 

1. Disable the param popup entirely
2. Just use ctrl + shift + space to pull it up on demand

Also, I find that increasing the hover delay to 500ms helps with other popups

**Comment by hughperkins** [comment]
`Just use ctrl + shift + space to pull it up on demand`
- doesnt work for me
- maybe because I'm on Mac, but hunting through the keyboard shortcuts for Mac turns up shift + command + space, and that doenst work eihter...

To Microsoft: if you insist on not changing how this works, please could you at least consider adding a note to the bottom of the dialog like:

"- If you dont want this dialog to show, please do [X]
- You can hide this dialog at any time by pressing [ESC]
- You can increase the timeout before showing this dialog by doing [Z]
- You can show this dialog on demand by doing [ZZ]
- You can remove this hint section by doing [Y]"

**Comment by iccor56** [comment]
+1

any option to move this away from the exact typing area would be preferred. maybe a central spot where it shows? maybe x lines up,x chars over?

many things are possible but right now it covers the code i want to look at. really really annoying.

**Comment by ganindu7** [comment]
Still relevant in case the developers are wondering!! @SneakyFish5 any update? Can we add this separately in crass the top vs-code brass doesn't find this game changing?

**Comment by cjmaxik** [comment]
It is very annoying. Let us change the position!

**Comment by chevtek** [comment]
You do know you can send a pull request? Or is throwing a fit easier than
writing "one line of code"?

**Comment by CodeCrazy-ywt** [comment]
If I were capable, then I wouldn't be here to send a comment.

**Comment by chevtek** [comment]
Oh but you said it was so easy!

**Comment by rconde01** [comment]
The issue is there WAS a previous PR. So I would be willing to try implementing this, but not if the PR won't be reviewed and possibly accepted. That requires someone from the VS Code team to review and ultimately accept a PR. But they don't appear to watch this thread...so what can we do?

**Comment by ganindu7** [comment]
If it makes you feel better, with time you will adopt - it was annoying when I switched to VS code but somehow It seem to have melted onto the background.. (I'm not sure if that's why VS code developers are not finding this annoying enough..)

**Comment by hughperkins** [comment]
I concur with Ganindu...

**Comment by vedal** [comment]
Does the following fix in the October version solve this problem?
https://code.visualstudio.com/updates/v1_62#_display-hovers-above-or-below-the-current-line

**Comment by pdm-pcb** [comment]
> Does the following fix in the October version solve this issue? https://code.visualstudio.com/updates/v1_62#_display-hovers-above-or-below-the-current-line

Unfortunately not - though I was glad to be reminded of the update. =) I'm not up-and-up on the Visual Studio vernacular, but this appears to affect tooltips apart from the parameter list popup.

And in case it wasn't obvious, I'm writing to lend my support for the parameter tooltip specifically to be configurable, even if it's just top/bottom like this new Intellisense option. I'd prefer to see tooltips stack below the cursor rather than having the param list block the lines above.

**Comment by tomboland-vocovo** [comment]
I would really just like to see the parameter list give at least one line's worth of context, whether it's above or below the cursor.  I find this particularly bad in python where I can be typing keyword parameters in a function invocation, spanning more than one line. The way the parameter list blocks out the context above is hugely frustrating.

**Comment by ajmoroney** [comment]
+1 for the dockable idea (assuming I understood it). Having it pinned to the top right corner for example, so it's there without me having to stop typing to hit a keyboard shortcut, but never in the way (or at least predictably in the way) would be such a massive improvement. I'm not saying it should be like that by default necessarily, but it sounds like a lot of people would really appreciate having the option.

Intellisense is a phenomenal feature, and I get that it's frequently important information for a lot of developers, but when the hints that pop up cover large chunks of code it feels like having a huge GPS display in the middle of the windshield. Really hoping this doesn't drop further off the radar, it's been my biggest annoyance with vscode since I started using it.

**Comment by jtjohnson1** [comment]
So this has been opened for 5 YEARS now.  I'm getting really tired of devs telling me I have to do things their way - oh, why don't you hit the ctrl or escape key every time this pops up?  Because I think it's stupid and time consuming and unnecessary.  Why can't you just put in a fix?  Are you really that lazy?  There's a bunch of people here trying to make the product better and work for them and devs are closing the ticket because we didn't answer them in a timely fashion or we're supposed to just accept their lame workarounds.

We all don't work like you.  Is it really that hard to to put in an offset on a UI element or, as suggested, have it pinned to a location, so your intellisense doesn't cover up the code I'm working on?   Or should we just move back to Eclipse?  I'm so tired of MS influenced chest pounders.

**Comment by doctarock** [comment]
honestly so annoying, every time I go to highlight a chunk of code this bloody thing pops in the way!

5 YEARS

**Comment by CodeCrazy-ywt** [comment]
I hope that vscode dev team can attach high priority to this issue because this issue is really troublesome.

**Comment by vgrafe** [comment]
Not sure what changed recently, but after years of using vs code, I feel very annoyed every day about this.

**Comment by hughperkins** [comment]
Yeah, somehow they made it worse recently, I havent figured out how yet... I just feel that I'd somehow configured it to be manageable-ish, by disactivating a bunch of things in options, and now it's back again.

**Comment by vgrafe** [comment]
I confirm, it got much worse recently. I did not install any extensions that might be causing that. Popups get in the way all the time.

**Comment by hughperkins** [comment]
I added the following to my settings. Might improve somewhat?

```
    "editor.quickSuggestions": {
        "other": false,
        "comments": false,
        "strings": false
    },
```

The key part is that `other` defaults to `true`, but setting to `false` reduces at least one kind of popup.

**Comment by swilkewitz** [comment]
Happy new year everybody!

**Comment by saminton** [comment]
I also feel it got worse recently, never seemed to bother me before. 

The problem I'm having is that if my mouse hovers a word the hint will pop up and then will not only obscure the line above the current hovered word but also prevent me from clicking on anything that is obscured until I first un-hover the word with the hint. If I simply move my mouse up the mouse hovers onto the hint.

I find myself constantly clicking stuff inside then hint when I expect it to disappear and be able to select stuff on the line above.

Is there any way to make the hint non-hoverable ? I don't see why the hint has to be hoverable or clickable. Shouldn't it be information only ? Why would I need to click / select anything inside the hint popup ?

**Comment by doctarock** [comment]
It would be ideal if the tips were dockable into the left menu as a panel, I rarely use them unless I am working unfamiliar languages or code. Failing that option, if I could set the delay to an extra second or two it would annoy me a lot less as it often pops up while I am just moving my mouse cursor across the code and gets in the way for copy/paste actions

**Comment by CodeCrazy-ywt** [comment]
I want the dev team to give a reaction, I don't want this issue sink into “I want this”.

**Comment by mikesimmonds** [comment]
> I also feel it got worse recently, never seemed to bother me before.
> 
> The problem I'm having is that if my mouse hovers a word the hint will pop up and then will not only obscure the line above the current hovered word but also prevent me from clicking on anything that is obscured until I first un-hover the word with the hint. If I simply move my mouse up the mouse hovers onto the hint.
> 
> I find myself constantly clicking stuff inside the hint when I would expect it to disappear and be able to select stuff on the line above.
> 
> Is there any way to make the hint non-hoverable ? I don't see why the hint has to be hoverable or clickable. Shouldn't it be information only ? Why would I need to click / select anything inside the hint popup ?

I agree this is the crux of the problem or me too. 
I don't see a use case for this particular hint to stay visible whilst hovered itself unless I missed something.
The hints are useful - particularly to view the type of the property you are hovering. However its very common to want to change the line above, which is slightly infuriating if the cursor is stolen by the hint.
I suspect the hint uses a standardised tooltip, which should stay displayed on hover in most / all other cases. So this may not be the simplest thing to actually implement

**Comment by trevyn** [comment]
> Is there any way to make the hint non-hoverable ?

@saminton @mikesimmonds Does `"editor.hover.sticky": false` do what you want?

**Comment by mikesimmonds** [comment]
> > Is there any way to make the hint non-hoverable ?
> 
> @saminton @mikesimmonds Does `"editor.hover.sticky": false` do what you want?

Yes - this does exactly what I was looking for! I can see the hints but still be able to edit the line above without the hassle. 
Thanks @trevyn

**Comment by swilkewitz** [comment]
That plus switching to a shortcut to get parameter hints should make things a lot nicer for most people: `"editor.parameterHints.enabled": false`

I think the shortcut is ctrl + shift+ space by default. The shortcut id is `editor.action.triggerParameterHints`

**Comment by gjsjohnmurray** [comment]
> I also feel it got worse recently, never seemed to bother me before.

Maybe #140212 which I just opened is a recent change/regression. If so, the default value (300ms) will now be causing hovers to appear after 150ms.

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/148393318-6df7e137-5a46-4bdc-8fc0-08f17d3c7846.png)
I hope that :
1. there is a switch-button so that we could change the position directly
2. and one workspace will maintain the position status.
3. a new command to toggle the position

**Comment by Jabbypappy** [comment]
![image](https://user-images.githubusercontent.com/25716143/148591224-be03d29b-8e03-48e0-99db-2ea4430382c1.png)
along with 
![image](https://user-images.githubusercontent.com/25716143/148591283-ce740a7b-63a8-4e49-ae75-ebacbe7d92dd.png)
is helpful.

I do believe it would be 100% more helpful having it in a little pop-out window in the upper right corner if turned off from showing above cursor. The little box would be helpful because the majority of the time you're not going to have a little box in the upper right corner impede your work as typically you'll be working in the center of the screen as opposed to the very top. A little box would be nice to drag to different locations to allow developers the option to adapt it as needed.

**Comment by saminton** [comment]
@trevyn Thanks, that was exactly what I was looking for. I just realised why some may want the hint hoverable though. If the hint has too much content then it becomes scrollable. Deactivating this option prevents you from scrolling to view all the content.

A possible solution and improvement could be to remove the hint max-height or at least make it larger when `editor.hover.sticky` is set to false ?

**Comment by SonicZentropy** [comment]
Switched from Jetbrains to VSCode for its superior LSP capabilities, and now I'm switching right back due to this issue.  How has this been open for 5 YEARS?  Add an option to position it at a static offset relative to an editor, now we can drag it to a corner like @Jabbypappy  mentioned is a prime location, everyone is happy, done.

**Comment by NicolasGoeddel** [comment]
Pleeease! Change that behaviour. I can not see what I am doing if a big annoying parameter hint window is placed over multiple lines above the current line.

**Comment by hughperkins** [comment]
Crazy that this is still open isn't it? Maybe we can get xkcd to do a
cartoon about it :)

**Comment by Hvass-Labs** [comment]
I have just started using VSCode for Python development and I use Jupyter Notebooks a lot. So far I like VSCode very much: It is beautifully designed and runs very fast. But there are a few minor issues, like this one where the pop-up parameter help is not very good.

I find the pop-up help window in ordinary Python Jupyter Notebooks running in a normal Google Chrome browser to be much better. But I also really like [this idea](https://github.com/microsoft/vscode/issues/51253#issuecomment-411662973).

I hope this is something the VSCode dev-team would put some serious effort into improving, because the rest of VSCode is really very well made and it is a very good development tool!

Thanks!

**Comment by patch321** [comment]
Just came here to say this is a big problem for me as well and it's definitely gotten worse lately. I barely noticed it before and now it's in my way ALL THE TIME

**Comment by CodeCrazy-ywt** [comment]
Okay, since a huge amount of users is requesting, where's the dev team's reaction?

**Comment by iccor56** [comment]
Nonexistent.  For years.

**Comment by doctarock** [comment]
This is where your opinions go to die

**Comment by znorman-harris** [comment]
Here's a great use case for exactly why this would be beneficial: My company has a commercial programming language that we sell which is complete with documentation for all of our routines. The routines can have *a lot* of documentation containing multiple examples (like you would expect from some open source projects as well) and sometimes is very lengthy (>100 lines). I was trying to use this documentation as hover help, but it is just way too much.

I almost think you need one of a few things to add more options for hover help:

1. Have docs show up in designated area
2. And/or allow a user to open up documentation in a separate pane/tab within VSCode. That way you could quite literally have a one-stop editor with your code and information rich documentation all in the same place
3. Maybe an ability to separate hover help content into tabs (i.e. by examples, arguments, keywords, classes, etc)

**Comment by jsolbrig** [comment]
Seriously, how is this not fixed yet? It gets in the way of the function signature that you're trying to write if you're formatting things correctly. The way that I work, parameter hints are basically unusable and I'll be turning them off even though I would like to have them.

**Comment by CodeCrazy-ywt** [comment]
The dev team has forgotten this issue?

**Comment by stedben** [comment]
Eh, I don't believe the dev team has forgotten this issue, per se, it's just that the people in this multi-year thread don't constitute enough of a percentage of the general user base to warrant any action.

We can get huffy, but the 42 of us in this thread will never amount to a hill of beans when it comes to the workload of the Super-Professional MicroSoft Super-Coders who have a hand in the development of the end product: Super VS Code. It would be trivial to offer us a shockingly-simple solution, but these MicroSoft Super Engineers have a job to do. And a Job to keep.

I think we should never forget that MicroSoft is a for-profit company, and a SEVERAL! frustrated users will never sway the Power-That-Is to make a MicroScopic change.

I stay in this thread to remind myself that monolithic companies have Job #1, and the rest of us just get to use the product.

**Comment by NicolasGoeddel** [comment]
> We can get huffy, but the 42 of us in this thread will never amount to a hill of beans [...]

In fact there are 190 people liking the initial post, 99 subcribers and 155 comments. That's not a minority in my opinion.

**Comment by one-jones** [comment]
please please please - this window drives me crazy

**Comment by freMea** [comment]
> please please please - this window drives me crazy

Turn it off and create a shortcut to call it if needed. There is an extension to place it in the sidebar along the files.

**Comment by nahuel** [comment]
@freMea what's the name of the extension?

**Comment by freMea** [comment]
> @freMea what's the name of the extension?

[Docs View](https://marketplace.visualstudio.com/items?itemName=bierner.docs-view)

**Comment by freMea** [comment]
Does this option help ? I will reenable tooltip and test it for the next days.
![image](https://user-images.githubusercontent.com/22337329/203480976-69f0f71e-80af-42df-8e8d-107a29209d27.png)

**Comment by freMea** [comment]
How this issue is different from #30797 ?

It seems commenters complains about the same thing in both.

**Comment by freMea** [comment]
This is still driving me crazy.
![image](https://user-images.githubusercontent.com/22337329/203809718-d527e3a8-f443-4eeb-be7d-06b6f11a3209.png)

Can not read my code above.

**Comment by sandipchitale** [comment]
See: [Signatures View](https://marketplace.visualstudio.com/items?itemName=sandipchitale.sigs-view)

**Comment by stedben** [comment]
Thank you @sandipchitale!

**Comment by exse2** [comment]
"editor.parameterHints.above": false,

when?

Or just let it react on 

"editor.hover.above": false,

**Comment by Hezakai** [comment]
![VSC Tooltip Cover](https://user-images.githubusercontent.com/19308080/229261777-5c077fd8-554c-4674-bc8a-6d9c785817b0.PNG)


"Working as intended"  /thread

**Comment by dillydadally** [comment]
All I want is to be able to move the entire tooltip popup into a panel. Bonus points if there's an option to make the panel update on hover rather than just cursor position.

I've tried both the Docs View and Signature View extensions. While I'm grateful for them, they both lack the following:

- an option to update on mouse hover rather than just cursor position.
- the code highlighting/coloring that the tooltip has. 
- error information like the tooltip has.

This is probably the biggest issue with VSCode for me. Is it really that hard to move a tooltip window into a panel instead? I feel like this should have been how it was done to begin with. A popup covering your code on every single token is kind of crazy.

**Comment by znorman-harris** [comment]
@dillydadally I have been playing around with this for my extension and I ended up using notebooks because they apply your theme colors to rendered markdown (for code blocks with non-standard languages). This is a substitute for not having a dedicated panel and isn't great, but is better than nothing.

It would be nice if we could have something similar to "open in editor" or something like that.

Here's what I have using notebooks as a workaround:

![notebook-help](https://github.com/microsoft/vscode/assets/31664668/1948c515-8956-449d-9647-678b15f7e18d)

**Comment by starball5** [comment]
Related on Stack Overflow: [VS Code intellisense in the way](https://stackoverflow.com/q/57275167/11107541)

**Comment by rpm5099** [comment]
I don't understand the pushback to addressing this issue.  The logic that seems to be - only a total of 217 users seem to think the inability to move parameter/intellisense popup placement is an issue, so it can't be that big of an issue.  This is wrong and insulting to those who took the time to bring attention to the problem.  The number of users who hate this feature of VSCode, or lack thereof, has to number in the millions.  In fact I'm guessing that many people struggle with this issue for about 10 minutes and then just permanently turn off those features and fail to get the benefit of them at all.

**Comment by beresfords-referrals** [comment]
It's a lot more than 217 - there are various issues logged requesting much the same thing in different ways.  A whole slew of issues could be closed by actioning this . Pretty Please ;-)

**Comment by starball5** [comment]
@baroquedub your #1 is a circular link to this issue ticket. Your #2 is about hovers, but my understanding is that this issue ticket is about parameter hints. Same with #5, which is about hovers and _already_ resolved. Your #3 and #4 and different requests- for a dedicated panel or view.

**Comment by beresfords-referrals** [comment]
You are totally right.  This is computers and there are always 10 solutions to every problem in the computer world.  The point is there is one problem, which is the hints keep getting in the way.

**Comment by ilmatic** [comment]
> I don't understand the pushback to addressing this issue. The logic that seems to be - only a total of 217 users seem to think the inability to move parameter/intellisense popup placement is an issue, so it can't be that big of an issue. This is wrong and insulting to those who took the time to bring attention to the problem. The number of users who hate this feature of VSCode, or lack thereof, has to number in the millions. In fact I'm guessing that many people struggle with this issue for about 10 minutes and then just permanently turn off those features and fail to get the benefit of them at all.

💯

Literally found this trying to disable intellisense. It's something I deal with every single day that I code. I start calling a function and 2-3 characters in I have no clue what I'm typing cuz there's a massive intellisense popup in the way. It's been a drip drip drip water torture for years. So disappointing to find that y'all have aware of this issue since 2017 and it's still open.

<img width="592" alt="Captura de pantalla 2024-02-21 a la(s) 10 30 24 p m" src="https://github.com/microsoft/vscode/assets/2415202/b8c9a7cd-0146-4852-8a9d-da8e10aa9d54">

**Comment by surfingdoggo** [comment]
> It's been a drip drip drip water torture for years. 

THIS! I finally was in an impatient enough mood just now to get distracted enough by it blocking my code to look up what it was even called to try to find a solution 😿 

I did find 

* [this issue to make it transparent](https://github.com/microsoft/vscode/issues/22439#issuecomment-600855615), which doesn't help much, but these [settings](https://code.visualstudio.com/api/references/theme-color#editor-widget-colors) at least give it some color to make me happy along with irritated at the same time (click the color box to change opacity):
```
    "workbench.colorCustomizations": {
        "editorSuggestWidget.background": "#124da770",
        "editorInlayHint.parameterBackground": "#ff0000",
        "editorHoverWidget.background":  "#00ccff6c",
        "editorHoverWidget.foreground": "#00ff226b",
        "editorHoverWidget.border": "#3700ff",
    }   
``` 
*  [a comment from a blessed saint](https://github.com/microsoft/vscode/issues/33752#issuecomment-1326537678) saying the following:
```
"editor.parameterHints.enabled": false,

ctrl + shift+ space brings it up when needed
```
* [Docs View](https://marketplace.visualstudio.com/items?itemName=bierner.docs-view) which was [created by a Vscode team member supposedly](https://stackoverflow.com/questions/70955635/how-to-change-reference-popup-tab-position-in-vs-code) that brings up another popup on the side.


> So disappointing to find that y'all have aware of this issue since 2017 and it's still open.

Frlz. I wonder how hard it is to make a plugin myself.

**Comment by rpm5099** [comment]
> I don't understand the pushback to addressing this issue. The logic that seems to be - only a total of 217 users seem to think the inability to move parameter/intellisense popup placement is an issue, so it can't be that big of an issue. This is wrong and insulting to those who took the time to bring attention to the problem. The number of users who hate this feature of VSCode, or lack thereof, has to number in the millions. In fact I'm guessing that many people struggle with this issue for about 10 minutes and then just permanently turn off those features and fail to get the benefit of them at all.

@starball5 - you gave this statement a thumbs down, can you please elaborate and explain why?

**Comment by starball5** [comment]
@rpm5099 I don't think the logic in your last sentence is necessarily wrong. That guess may very well be fairly accurate. But I thought it was unnecessary to paint the maintainers' comments here as "wrong and insulting". What I see is a maintainer soliciting design discussion. I can just barely categorize it as "pushback", and the issue ticket was reopened after being closed. VS Code has tons of users and tons of feature-requests. Microsoft can do whatever they want and they don't _need_ to listen. But to a large extent, they do. And with the huge backlog of feature-requests, they need a way to prioritize (and they look at the number of thumbs up reactions). It leaves a bad taste in my mouth when I read comments that give off the vibe of complaining. I rather like seeing comments that weigh in on design questions, or just not seeing comments at all.

**Comment by Raydir** [comment]
hey there
Just stumbled over this issue here.
I do have several snippets in my language extension with long names (sadly) and long descriptions about the params of those snippets.

For me a parameter to let the snippet-preview be fixed at the bottom of the suggestionpanel would be just splendid...

atm the panel opens every now and then like this:
![image](https://github.com/microsoft/vscode/assets/17499573/f3a8adc5-955f-46f5-8071-9a633393b701)

If we could have a setting to fix the position at the bottom it would show the complete infobox without problems:
![image](https://github.com/microsoft/vscode/assets/17499573/6c2e007c-bd58-4dc5-929f-ab89a0428d69)

**Comment by kmarmet** [comment]
> > @freMea what's the name of the extension?
> 
> [Docs View](https://marketplace.visualstudio.com/items?itemName=bierner.docs-view)

**THANK YOU!!!!! IT HAS BEEN DRIVING ME ABSOLUTEY INSANE!!!!**

**Comment by Hanibachi** [comment]
i can't believe this issue still exists since 2017!!!! like what the actual hell LMAO

**Comment by Ian-T-Price** [comment]
How about adding an option to place it in the side bar menu as an accordian? It's easy to observe on the side or close it up it people don't want to be distracted by it  

![image](https://github.com/user-attachments/assets/4601d0d3-228b-4c91-82ab-5ab527c3289e)

**Comment by saminton** [comment]
> How about adding an option to place it in the side bar menu as an accordian? It's easy to observe on the side or close it up if people don't want to be distracted by it
> 
> ![image](https://private-user-images.githubusercontent.com/1264282/369804367-4601d0d3-228b-4c91-82ab-5ab527c3289e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTMxMzIsIm5iZiI6MTcyNzc5MjgzMiwicGF0aCI6Ii8xMjY0MjgyLzM2OTgwNDM2Ny00NjAxZDBkMy0yMjhiLTRjOTEtODJhYi01YWI1MjdjMzI4OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDFUMTQyNzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzZjNzIzNGU2YzYxZjJhNzI3YzcwODRjYzkyOTA1ZjdhNTk4NzA3YWM1ZTEzZTE0ZTFkOTdmMjA0NmRjNTllMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._YX7DezbNkH2h0VJqTmRSWHl4toz8GOxwR91_8VEb_w)

That's actually what I've been using for a while now, using this extension -> https://marketplace.visualstudio.com/items?itemName=bierner.docs-view

**Comment by CodingMarkus** [comment]
> i can't believe this issue still exists since 2017!!!! like what the actual hell LMAO

This problem is a very good example of what often goes wrong with large, popular projects. Their maintainers think it's more important to implement a super complicated, 5000 line feature that they think is super cool and that will keep them busy for 3 months before it works reasonably reliably, but that nobody ever asked for and that very few people will ever really need, than to fix an open feature request that's been open for over 6+ years and that hundreds of people have asked for and that's probably a 50 line fix and get it done in a single day. After all, why implement the things people care about when you can implement the things nobody cares about?

**Comment by l0hn** [comment]
This problem is so annoying that I've been considering going through the pain of switching to nvim.

For now I have used the "be5invis.vscode-custom-css" extension to load a css file to override the position of the parameter hints popup:


### Before:
<img width="2383" alt="Image" src="https://github.com/user-attachments/assets/e5f8cd88-129e-4d14-afc8-d10d2c55d02a" />

### After:
<img width="2383" alt="Image" src="https://github.com/user-attachments/assets/e3c76a89-3c0a-4711-b164-2e0a55be8b38" />




It's not a nice solution but at least the popup is no longer directly on-top of the code I'm trying to write.

Link to the extension for anyone else that's suffering with this daily: https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css


### Css Used:
```css
.parameter-hints-widget>.phwrapper {
    max-width: 100% !important;
    width: 100% !important;
}

.parameter-hints-widget {
    position: fixed !important;
    border-width: 2px !important;
    border-radius: 12px !important;
    padding: 10px !important;
    width: 70% !important;
    top: unset !important;
    bottom: 0px !important;
    margin-bottom: 40px !important;
    border-color: rgb(144, 104, 176) !important;
    background-color: rgb(43, 43, 43) !important;
    left: 15% !important;
}
```

**Comment by rpm5099** [comment]
Wow, a totally separate extension to fix a bug/deficiency in another extension that has had an open issue for 7 years with 200+ comments from 100+ users.

**Comment by SonicZentropy** [comment]
Thanks l0hn for doing what the entirety of Microsoft couldn't manage in 7+ years!  This workaround is fantastic

**Comment by rpm5099** [comment]
> This problem is so annoying that I've been considering going through the pain of switching to nvim.
> 
> For now I have used the "be5invis.vscode-custom-css" extension to load a css file to override the position of the parameter hints popup:
> 
> ### Before:
> <img alt="Image" width="2000" src="https://private-user-images.githubusercontent.com/1331885/395600401-e5f8cd88-129e-4d14-afc8-d10d2c55d02a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NzYxNjMsIm5iZiI6MTczNTY3NTg2MywicGF0aCI6Ii8xMzMxODg1LzM5NTYwMDQwMS1lNWY4Y2Q4OC0xMjllLTRkMTQtYWZjOC1kMTBkMmM1NWQwMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzFUMjAxMTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVhMDgyMmY5MzM3OWE2NmQ4ZTU1MTU1ZjQ2NjM4M2RhZGU5NDQxNDlmMjFjYjMyZTc1YTBlYzE2NjFmNzcwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2KuNgaYKlZ0T92kUOoDdOzbfXsIQa3U2J1f-mSudlpo">
> ### After:
> <img alt="Image" width="2000" src="https://private-user-images.githubusercontent.com/1331885/395600471-e3c76a89-3c0a-4711-b164-2e0a55be8b38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NzYxNjMsIm5iZiI6MTczNTY3NTg2MywicGF0aCI6Ii8xMzMxODg1LzM5NTYwMDQ3MS1lM2M3NmE4OS0zYzBhLTQ3MTEtYjE2NC0yZTBhNTViZThiMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzFUMjAxMTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVjNTczOTNjZWU4M2VjMzIyZTE1YWQ4NGE1MmY4MWNiNjk1YTdlN2Y3MDQxM2RjMzExMGJmNTMzMDQ4MzkwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.14BRgd2Rg7ZoWg0hsslPP6zP2rNM7kKqtHX1btD-3s0">
> It's not a nice solution but at least the popup is no longer directly on-top of the code I'm trying to write.
> 
> Link to the extension for anyone else that's suffering with this daily: https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css
> 
> ### Css Used:
> .parameter-hints-widget>.phwrapper {
>     max-width: 100% !important;
>     width: 100% !important;
> }
> 
> .parameter-hints-widget {
>     position: fixed !important;
>     border-width: 2px !important;
>     border-radius: 12px !important;
>     padding: 10px !important;
>     width: 70% !important;
>     top: unset !important;
>     bottom: 0px !important;
>     margin-bottom: 40px !important;
>     border-color: rgb(144, 104, 176) !important;
>     background-color: rgb(43, 43, 43) !important;
>     left: 15% !important;
> }

This is great, but is there any way to move the window *away from the cursor* so it's not blocking code I am trying to look at?  Now it just blocks whatever is below the cursor.  This would be a reasonable compromise for a smartphone screen.

**Comment by rpm5099** [comment]
> This problem is so annoying that I've been considering going through the pain of switching to nvim.
> 
> For now I have used the "be5invis.vscode-custom-css" extension to load a css file to override the position of the parameter hints popup:
> 
> ### Before:
> <img alt="Image" width="2000" src="https://private-user-images.githubusercontent.com/1331885/395600401-e5f8cd88-129e-4d14-afc8-d10d2c55d02a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NzYxNjMsIm5iZiI6MTczNTY3NTg2MywicGF0aCI6Ii8xMzMxODg1LzM5NTYwMDQwMS1lNWY4Y2Q4OC0xMjllLTRkMTQtYWZjOC1kMTBkMmM1NWQwMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzFUMjAxMTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVhMDgyMmY5MzM3OWE2NmQ4ZTU1MTU1ZjQ2NjM4M2RhZGU5NDQxNDlmMjFjYjMyZTc1YTBlYzE2NjFmNzcwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2KuNgaYKlZ0T92kUOoDdOzbfXsIQa3U2J1f-mSudlpo">
> ### After:
> <img alt="Image" width="2000" src="https://private-user-images.githubusercontent.com/1331885/395600471-e3c76a89-3c0a-4711-b164-2e0a55be8b38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NzYxNjMsIm5iZiI6MTczNTY3NTg2MywicGF0aCI6Ii8xMzMxODg1LzM5NTYwMDQ3MS1lM2M3NmE4OS0zYzBhLTQ3MTEtYjE2NC0yZTBhNTViZThiMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzFUMjAxMTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVjNTczOTNjZWU4M2VjMzIyZTE1YWQ4NGE1MmY4MWNiNjk1YTdlN2Y3MDQxM2RjMzExMGJmNTMzMDQ4MzkwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.14BRgd2Rg7ZoWg0hsslPP6zP2rNM7kKqtHX1btD-3s0">
> It's not a nice solution but at least the popup is no longer directly on-top of the code I'm trying to write.
> 
> Link to the extension for anyone else that's suffering with this daily: https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css
> 
> ### Css Used:
> .parameter-hints-widget>.phwrapper {
>     max-width: 100% !important;
>     width: 100% !important;
> }
> 
> .parameter-hints-widget {
>     position: fixed !important;
>     border-width: 2px !important;
>     border-radius: 12px !important;
>     padding: 10px !important;
>     width: 70% !important;
>     top: unset !important;
>     bottom: 0px !important;
>     margin-bottom: 40px !important;
>     border-color: rgb(144, 104, 176) !important;
>     background-color: rgb(43, 43, 43) !important;
>     left: 15% !important;
> }

This is great, but is there any way to move the window *away from the cursor* so it's not blocking code I am trying to look at?  Now it just blocks whatever is below the cursor.  This would be a reasonable compromise for a smartphone screen.

**Comment by l0hn** [comment]
@rpm5099 The workaround is definitely far from ideal, it has to be reloaded whenever vscode updates and will break if the class names change in the future.

Personally I would like it to show below the line being edited, or docked in a panel, or well.. just anywhere except ontop of what I'm trying to read. I expect you could set the position in relation to the curser using JS.

I'm not sure why there's a reluctance to fix this for people.

**Comment by akarsai** [comment]
i stumbled on this thread because the intellisense popup window was obstructing the text i typed. for this, similar css can be used. i ended up with

```css
.monaco-editor .suggest-widget {
    position: fixed !important;
    padding: 10px !important;
    width: 70% !important;
    top: 100px !important;
    bottom: unset !important;
    margin-bottom: 100px !important;
    left: 15% !important;
}
```

**Comment by distinctdan** [comment]
All they need to do is turn down the suck:
 - DON'T popup clickable buttons directly underneath my mouse. ESPECIALLY ones that modify the layout. "View Problem", I'm looking at you.
 - Don't block code I just wrote.
 - Don't popup immediately, needs a much longer delay. Mouseovers shouldn't trigger popups while the mouse is moving.

Where are my microsoft UX designers?

**Comment by ml-w** [comment]
Wondering if this feature is here yet. 
I think it can go right of intellisense or below it, which ever having more room.

**Comment by natewaddoups** [comment]
It's extra annoying that VSCode keeps adding new features that interrupt me while I'm typing, hide the code that I'm looking at, and/or move the cursor. 

Writing software is all about concentration and staying in flow, and the VSCode user experience only gets increasingly distracting.

It's like driving a car where the navigation UI throws an opaque map over the windshield directly in front of the driver. There's just no need for that. I don't want to turn these features off, because they are useful. But the UX is the opposite of what I want when I'm writing software.

**Comment by CodingMarkus** [comment]
> I think it can go right of intellisense or below it, which ever having more room.

Yeah, it can, but this issue is about letting the user choose what they want to see, rather than having it jump around randomly however it pleases, which doesn't really improve the situation at all.

https://private-user-images.githubusercontent.com/6782760/454618781-d1d7ff87-e85f-4724-9d16-4526ae9452d2.mov?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzg2MDMzOTUsIm5iZiI6MTc3ODYwMzA5NSwicGF0aCI6Ii82NzgyNzYwLzQ1NDYxODc4MS1kMWQ3ZmY4Ny1lODVmLTQ3MjQtOWQxNi00NTI2YWU5NDUyZDIubW92P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDUxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA1MTJUMTYyNDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODQyMDQzMDBiZDJkYjQyMDk3ZTA1NjFkMGY0Y2ExYmU1ZGE4NjY2MzU0MjFjMjQ0MDIxOGY1ZjRkYmRmYTY4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPXZpZGVvJTJGcXVpY2t0aW1lIn0.HdwNFB_GWkZoY2XjpougbKWP2zfWSM5i79R4fQZh_mk

**Comment by gummigumbear** [comment]
> This problem is so annoying that I've been considering going through the pain of switching to nvim.
> 
> For now I have used the "be5invis.vscode-custom-css" extension to load a css file to override the position of the parameter hints popup:
> (...)
> 
> It's not a nice solution but at least the popup is no longer directly on-top of the code I'm trying to write.
> 
> Link to the extension for anyone else that's suffering with this daily: https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css
> (...)

Thanks, I completely hid the box using the CSS code below. Absolute nonsense not having an option to hide it without hiding other actual useful elements.

```
.parameter-hints-widget {
    visibility: hidden !important;
}
```

**Comment by heartacker** [comment]
what is  blocking this？

**Comment by CodingMarkus** [comment]
> what is blocking this？

The unwillingness of Microsoft developers to fix it. 

Adding an option to choose if this pop up preferable opens above, below, or right to the cursor should be dead simple. Having three sets of CSS to make this happen should be dead simple as well. Having a bit of extra code to check if the pop up will fit in the preferred location and move it to another one only if it cannot fit there, shouldn't be too hard either.

But instead of just fixing it, they try to blame the users for having an issue, convince them that the current behavior is great (yeah, hiding code I just wrote is great), tell them to disable the feature (I don't want to disable it, the feature is very helpful, the UI is just poorly implemented), or tell them to hit buttons to make the popover disappear (again, that's not what anyone here wants to happen). The amount of time they have spend for those comments and internal discussions probably exceeds the time required to just fix it by a factor of 10.
