### ISSUE TITLE
Mixed HTML PHP & AngularJS breaks syntax color highlighting.

### ISSUE THREAD

**Issue by joshribakoff** [Microsoft/vscode#34910]
![screenshot from 2017-09-24 10-50-43](https://user-images.githubusercontent.com/4021306/30785114-3a178c2c-a116-11e7-8c41-854954e9ba02.png)
- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.11.3-202.fc25.x86_64
- Extensions: none
---

Messy template that mixes PHP HTML & AngularJS (v1) breaks syntax highlighting https://gist.github.com/joshribakoff/eec82fdf61209db815b682069110dcec

intelliJ, and sublime both handle this fine. Atom also messes up but in a different way than VSCode. I would not be surprised to hear the code is invalid, but Sublime does handle it fine anyways.

**Comment by roblourens** [comment]
You are missing a start quote in the HTML on line 105, so some stuff after the end quote is incorrectly a string in HTML:

`        <button class="btn btn-default pull-right" style=margin-right:5px;"  ng-click="accept()">Accept</button>`

**Comment by joshribakoff** [comment]
I see, thank you. It would be great if the editor highlighted that error or drew my attention to it. Its also interesting the web browsers handled it fine, and so did sublime. But yes thank you the problem is on my end.

**Comment by joshribakoff** [comment]
Fixing the quote didn't fix the syntax highlighting, maybe there is still a bug.

**Comment by roblourens** [comment]
You may also need to update to 1.16.1. There was a PHP syntax highlighting bug fixed in that release.

**Comment by joshribakoff** [comment]
The original problem still happens on 1.17 (with the missing quote). After removing the missing quote, it renders perfect in 1.17 -- also in 1.17 It was immediately obvious where the missing quote was, which means it behaved better than Sublime or Atom. Awesome.

Thank you again!
