### ISSUE TITLE
Windows magnifier (chromium accessibility events  issue finally  fixed)!!!  

### ISSUE THREAD

**Issue by Deon588** [Microsoft/vscode#35396]
- VSCode Version:
latest
- OS Version:
Windows 10 64 bit
Steps to Reproduce:
When editing text in the vsCode editor while using windows magnifier the focus doesn't follow the insertion cursor.  This was as a result of chromium only emitting the correct accessibility events when a composition based language is used e.g. Chinese.  I created a issue on chromium which has been fixed in the latest chrome release 

bug url:
https://bugs.chromium.org/p/chromium/issues/detail?id=768125

thanks @alexandrudima for pointing the problem out in another vsCode issue
How/when would this be integrated in vsCode?  I have low vision and it's especially hard to work with the magnifier without automatic following of the insertion point focus... 
1.
open vsCode while using windows magnifier
2.
edit any file using the vsCode editor.

Reproduces without extensions: Yes/No

**Comment by Deon588** [comment]
I noticed the same today.  I think it was fixed after I created the following issue:

https://bugs.chromium.org/p/chromium/issues/detail?id=768125

**Comment by alexandrudima** [comment]
@Deon588 I'm sorry, but it appears the upstream issue is not fixed. The status is "Untriaged" at https://bugs.chromium.org/p/chromium/issues/detail?id=768125

Let's continue tracking in #7394

Once Chromium fixes the issue and makes a release, Electron will ship a new version with the fix, and we will eventually ship a VS Code version with a new Electron version.

**Comment by Deon588** [comment]
@alexandrudima This started working in chrome the day after I created that issue...  So it working in chrome now doesn't mean it has been fixed in chromium?

**Comment by alexandrudima** [comment]
@Deon588 Chrome is Chromium plus a few Chrome proprietary stuff. 

The Windows magnifier following the caret is not working in Chrome, Chromium, Electron, nor VSCode. The root cause lies in Chromium. It has never worked reliably, as the Chromium developer confirms in their comment. 

I cannot comment on what you have noticed or why you would believe it works.
