### ISSUE TITLE
Go To Bracket shortcut not working

### ISSUE THREAD

**Issue by moathkhozyem** [Microsoft/vscode#35570]
- VSCode Version: 1.16.1
- OS Version: Windows 8.1

Shortcut go to matched bracket seems doesn't work properly.

**Comment by jens1o** [comment]
Can reproduce this on a German keyboard.

<kbd>Ctrl + Shift + ^</kbd> will result into a `°` for me.

**Comment by borekb** [comment]
I can reproduce as well on 1.17.1. Invoking the command manually (from `ctrl+p`) works, invoking keyboard shortcut doesn't, and the mapping seems right:

![image](https://user-images.githubusercontent.com/101152/31538377-ab9efb3e-b005-11e7-9185-f5bfab0da585.png)

I'm on ENG (US) keyboard:

![image](https://user-images.githubusercontent.com/101152/31538400-bcfcef26-b005-11e7-838d-9e312ec3d2fb.png)

**Comment by tyHadd** [comment]
This is happening to me as well with an English keyboard on Linux Mint 18.2 and vs code 1.18.1.

**Comment by lucbetacode** [comment]
I have the same problem with atom keymap: ctrl+m. This was working for 2 h and then broke. English and German keyboard on Win 10 and vs code 1.19.0 insider. 

Love this shortcut on atom, but I want to stick to vs code. Will there be a fix?

**Comment by moathkhozyem** [comment]
FIxed in the recent update.

**Comment by moathkhozyem** [comment]
@lucbetacode try to update to the latest version.

**Comment by lucbetacode** [comment]
I still have the problem after the update. Any suggestions?

![vs code insider 19](https://user-images.githubusercontent.com/11670097/33767235-1fa001ee-dc21-11e7-954e-f84ddc81d09a.JPG)

**Comment by lucbetacode** [comment]
This is what I have now:  to the keyboard shortcut: `ctrl+m ` is attached to a command which works like `Edit.GotoBrace`.
But I need a command  `editor.action.jumptoBracket` attached to` ctrl+m `, like this:
![jump to bracket](https://user-images.githubusercontent.com/11670097/33782796-53f9a6aa-dc5a-11e7-8a7a-96b91925326f.JPG)

**Comment by lucbetacode** [comment]
Problem solved: 

There are two different commands in vs code, which I have got confused:
1. `Go to matching Pair`: In this case, one can jump from the opening tag to closing tag.
2. `Jump to bracket`: In this case, one can jump within a tag between the brackets.
