### ISSUE TITLE
Font rendering looks ugly on Linux

### ISSUE THREAD

**Issue by cryptomaniac512** [Microsoft/vscode#35675]
- VSCode Version: Code 1.17.0 (be377c0faf7574a59f84940f593a6849f12e4de7, 2017-10-04T23:33:45.303Z)
- OS Version: Linux x64 4.12.13_1
- Extensions: Extensions are disabled
---
All fonts look ugly, you can see it on screenshot:
![image](https://user-images.githubusercontent.com/10251687/31262450-57a3208a-aa9e-11e7-85f5-93dac80f7c46.png)

Console output (when runs with verbose option):
```
node[23225]: pthread_create: Invalid argument
[23231:1006/140049.274771:ERROR:platform_thread_posix.cc(119)] pthread_create: Invalid argument
[23231:1006/140049.275482:ERROR:atom_browser_main_parts_posix.cc(199)] Failed to create shutdown detector task.
[main 2:00:49 PM] Starting VS Code in verbose mode
[main 2:00:49 PM] from: /home/cryptomaniac/Downloads/VSCode-linux-x64/resources/app
[main 2:00:49 PM] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': true,
  disableExtensions: true,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  'skip-getting-started': false,
  'sticky-quickopen': false }
[main 2:00:49 PM] Unable to read folders in /home/cryptomaniac/.config/Code/Workspaces (Error: ENOENT: no such file or directory, scandir '/home/cryptomaniac/.config/Code/Workspaces').
[main 2:00:50 PM] IPC#vscode-machineId
node[23309]: pthread_create: Invalid argument
[23231:1006/140050.847055:INFO:CONSOLE(28)] "%c[Extension Host] %cdebugger inspector at %cnode[23308]: pthread_create: Invalid argument
", source: file:///home/cryptomaniac/Downloads/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.main.js (28)
[main 2:00:51 PM] IPC#vscode-workbenchLoaded
```
Also, vscode font size outside editor (tabs, menus, etc) too small, - this is not from my gtk settings.
For example, this is a screenshot of working emacs - all fonts are looks well.
![image](https://user-images.githubusercontent.com/10251687/31262806-f08d7c6c-aaa0-11e7-893f-ec1e11acb3cb.png)

I'm working on Void Linux, VSCode ran from downloaded archive.
Also, I use Chromium and have no any troubles.

Reproduces without extensions: Yes

**Comment by chrmarti** [comment]
@Tyriar There might be a font that is missing? (This is Linux.)

**Comment by cryptomaniac512** [comment]
@chrmarti as for editor, I set exists fonts for editor (Droid Sans Mono Slashed, DejaVu Sans Mono and Droid Sans)

**Comment by Tyriar** [comment]
@cryptomaniac512 does it look right when you remove your custom font setting?

**Comment by cryptomaniac512** [comment]
@Tyriar, no.

**Comment by bpasero** [comment]
@cryptomaniac512 is this a recent regression or are you using VS Code for the first time?

**Comment by cryptomaniac512** [comment]
@bpasero, I used the editor about 2 months ago and everything was fine.

**Comment by cryptomaniac512** [comment]
But font has always been small in spite of GTK settings.

**Comment by bpasero** [comment]
@cryptomaniac512 any difference with our [previous release (1.16)](https://az764295.vo.msecnd.net/stable/27492b6bf3acb0775d82d2f87b25a93490673c6d/code-stable-code_1.16.1-1505406497_amd64.tar.gz) to see if this is a regression in 1.17 alone?

**Comment by cryptomaniac512** [comment]
Same problem
![image](https://user-images.githubusercontent.com/10251687/31266296-743ef42c-aab6-11e7-93e9-e8d65e819733.png)

**Comment by bpasero** [comment]
@cryptomaniac512 I should have posted the link for 1.15 because in 1.16 we updated our UI framework (Electron) and that might have an impact too. How does it look in [VSCode 1.15](https://az764295.vo.msecnd.net/stable/41abd21afdf7424c89319ee7cb0445cc6f376959/code-stable-code_1.15.1-1502903936_amd64.tar.gz)?

**Comment by cryptomaniac512** [comment]
:(
![image](https://user-images.githubusercontent.com/10251687/31266624-f9a06064-aab7-11e7-8d72-616388f7e1b1.png)

**Comment by cryptomaniac512** [comment]
Maybe try with 1.15.0 and 1.14?

**Comment by cryptomaniac512** [comment]
This problem reproduced with 1.14.2.
It looks like a problem with another software, but I have no problem anywhere instead of vscode.

**Comment by cryptomaniac512** [comment]
Fonts look good when I set sub-pixel geometry to `none` instead of `RGB`
![image](https://user-images.githubusercontent.com/10251687/31268099-2bccb6ea-aabe-11e7-95b7-f098d4dea7de.png)

**Comment by cryptomaniac512** [comment]
But fonts in latest release and 1.16 are too small
![image](https://user-images.githubusercontent.com/10251687/31268206-9782fd4a-aabe-11e7-959d-3c875d0f0fa7.png)
Look at window bar (File, Edit, Selection, etc)

**Comment by mgoku** [comment]
Probably problem with Freetype.

I got the same problem when I upgrade to Freetype 2.8.1. Everything work fine with an older version of Freetype.

Someone on Phoronix forum said something about bugs with older version of Google Skia.

https://www.phoronix.com/forums/forum/software/desktop-linux/979076-freetype-improvements-for-the-adobe-engine

**Comment by christianburger** [comment]
I have the same problem here, please advise if you find a solution / workaround.
This font rendering issue occurs  similarly with Atom in my case, no other applications are affected.
Tested with Chromium Version 62.0.3202.18 (Developer Build) (64-bit) but also other versions, same result.
I've tried also tweaking the antialias settings for my NVidia card and plasma5 environment, no success.

**Comment by theychx** [comment]
I can confirm that this is a FreeType related problem. Downgrading the ```libfreetype6``` package on my Debian Sid box from ```2.8-0.2``` to ```2.8.1-0.1``` resolved this issue for me (I have also not had any problems with other applications).

**Comment by christianburger** [comment]
Yes, I`m amazed, I've also downgraded to 2.8.0 on my gentoo desktop and the issue is gone.
Thanks a lot for your reply.

**Comment by julian-klode** [comment]
This seems to be Skia bug 6663:

https://bugs.chromium.org/p/skia/issues/detail?id=6663

**Comment by wizardion** [comment]
Hey guys, can anyone tell me how to downgrade the libfreetype6 in Ubuntu?

**Comment by theychx** [comment]
@wizardion The issue was introduced with freetype 2.8.1. As far as I can see, the latest version to have entered [Ubuntu](https://packages.ubuntu.com/artful/libfreetype6) is 2.8 (which is the one we're downgrading to), so maybe your issue is not related to this?

**Comment by wizardion** [comment]
@theychx As I can see with the command `apt-cache policy libfreetype6` - I have Installed version: `2.8.1-0.1~xenial`. Not the `2.8-0.2ubuntu2` as you described. How can I downgrade to 2.8-0?

**Comment by ragesoss** [comment]
@wizardion try downloading the .deb and installing it manually: https://packages.ubuntu.com/bionic/amd64/libfreetype6/download

`sudo dpkg -i libfreetype6_2.8-0.2ubuntu2_amd64.deb`

The analogous process worked for me on Debian.

**Comment by GreatDanton** [comment]
I am on Debian Testing downgrading libfreetype6 does fix this!

**Comment by wizardion** [comment]
@ragesoss Thank you for your help. I found another solution to do this on this page: https://github.com/achaphiv/ppa-fonts/tree/master/ppa. I changed the distribution from xenial  to zesty after the adding a new repository, and I got `2.8-0ubuntu0.17.04ppa2` version.

Thank you for your help guys. Now the version 2.8-0 - solved my problem.

**Comment by mgerner** [comment]
For others who are on Debian, find libfreetype6 packages for downgrading here: http://snapshot.debian.org/package/freetype/2.8-0.2/#libfreetype6_2.8-0.2 and http://snapshot.debian.org/package/freetype/2.8-0.2/#libfreetype6-dev_2.8-0.2

**Comment by Tyriar** [comment]
There are open PRs to backport the skia fix for this to old versions of Electron https://github.com/electron/libchromiumcontent/issues/384#issuecomment-342741804

**Comment by CaptainQwark** [comment]
An alternative to downgrading libfreetype is extracting the older libfreetype.so.6.y.y from the .deb (libfreetype.so.6.12.3 for debian stretch), drop it in de code directory (/usr/share/code on debian) and rename it to libfreetype.so.6 . VSC will then pick up this version on a restart.

**Comment by ismail** [comment]
This seems to be fixed in electron 1.7 branch (https://github.com/electron/libchromiumcontent/pull/385) is there any chance to have the fix in next VSCode release?

**Comment by cyphrack** [comment]
I had the same issue. A workaround without having to change freetype, is to change your font rendering to standard grayscale antialiasing and slight / medium hinting. This issue only occured (at least for me) when I has the subpixel antialias.

Greets!

**Comment by ddrjm** [comment]
@GreatDanton How did you downgrade in debian testing?

**Comment by GreatDanton** [comment]
@ddrjm, see @ragesoss's post above mine. Download old .deb package and run `sudo dpkg -i <your_package>` Apt will automatically downgrade the package for you.

**Comment by josser** [comment]
@cyphrack  Can you please tell how did you managed to change font rendering?

**Comment by cyphrack** [comment]
@josser I used the Gnome Tweak Tool. But I'm pretty sure there's some X11 config file somewhere.
Here's a great tutorial. https://wiki.archlinux.org/index.php/font_configuration

**Comment by ngollan** [comment]
Sadly not fixed in 1.19.0, but you do not need to downgrade libfreetype to make things look better. Just set `FREETYPE_PROPERTIES` to use the old renderer, e.g., just run
```
FREETYPE_PROPERTIES="truetype:interpreter-version=35" code
```
from a command line, or export it in your profile.

**Comment by jgb** [comment]
None of the suggested workarounds seem to fix this for me. Could this be picked up? This is quite a showstopper for a large amount of linux users.

**Comment by ju1ius** [comment]
Hi, I managed to get proper font-rendering with this custom [fontconfig](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html).
```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <!-- Force RGBA subpixel aliasing to «none» in code and code-insiders -->
  <match target="pattern">
    <or>
      <test name="prgname">
        <string>code</string>
      </test>
      <test name="prgname">
        <string>code-insiders</string>
      </test>
    </or>
    <edit name="rgba" mode="assign">
      <const>none</const>
    </edit>
  </match>
</fontconfig>
```

**Comment by evenfrost** [comment]
Maybe a bit off-topic, but I ended up here looking how to improve Fira Code rendering in VSCode on Linux (Ubuntu 17.10). I have big 4K display, and Fira Code looked pretty ragged on it even with properly configured system anti-aliasing settings. And then I found out there is `Fira Code Retina` variation of the font. Set it as follows in VSCode settings:
```
 "editor.fontFamily": "'Fira Code Retina'"
```
Font looks a lot more juicy now, and I'm a lot more happier. :)

**Comment by zero-master** [comment]
# Platform: Linux

## VSCode:
![image](https://user-images.githubusercontent.com/1130261/34426078-c30189f0-ec6d-11e7-8642-43078718a303.png)

## Atom:
![image](https://user-images.githubusercontent.com/1130261/34426136-25178838-ec6e-11e7-98df-f7b1c4f7c84b.png)


## Sublime:
![image](https://user-images.githubusercontent.com/1130261/34426095-e0882c54-ec6d-11e7-9077-e3979e332a6c.png)

**Comment by liz-mars** [comment]
@cyphrack 's solution worked for me. Use Gnome-Tweak-Tool.

**Comment by perfhunter** [comment]
I can confirm font corruption problem on Ubuntu-18.04 alpha after updating libfreetype6 from 2.8.0 to 2.8.1. The proposed solution with setting truetype interpreter version doesn't work for me, disabling subpixel rendering via custom fontconfig does.

**Comment by dgncn** [comment]
I have encountered same issue on debian 9.3 stretch
my `libfreetype6` version was `2.8.1-1`
I downgraded  `2.6.3-3.2` with this command
`sudo apt-get install libfreetype6=2.6.3-3.2`


you can know available versions with this command
`apt-cache showpkg libfreetype6`

**Comment by BanjoCam** [comment]
I am running Antergos linux and this issue causes Vscode to be relatively unusable. (Unfortunately, coding in VScode is my primary reason for my linux machine...) Downgrading freetype2 worked perfectly for me (none of the other mentioned fixes do) but unfortunately recent system updates break my system unless I upgrade to a more recent freetype2. So I'm a bit stuck!

I noticed this recent post on the Atom version of this issue: https://github.com/atom/atom/issues/15737#issuecomment-361742630
I know very little about how VScode actually works, but could a similar solution be done here?

Thanks!

**Comment by Tyriar** [comment]
Thanks @BanjoCam, looks like this will be fixed when we upgrade Electron.

**Comment by Hamper** [comment]
I'm tried to build vscode 1.19.3 with electron 1.7.12 and this bug was really fixed.

**Comment by zero-master** [comment]
@BanjoCam I am also using the latest version of Antergos (no special tweaks, running out of box) and not experienced any font rendering issues with VSCode. 
Linux z97 4.14.15-1-ARCH #1 SMP PREEMPT

Full system upgrade should solve your issue:

`sudo pacman -Syu`

**Comment by BanjoCam** [comment]
@zero-master Thanks for the reply!  I guess "unusable" was a bit of hyperbole, but to me the differences between the older freetype2 and the current one are pretty noticeable and I found to be hard on the eyes for longer coding sessions. I do have a fully updated system (actually with the most recent updates, something broke with keeping the older freetype installed... I ended up doing a full system reinstall, so my setup is REALLY fresh and updated and completely untweaked!). 

If I get a chance later I will post a before/after shot but I am really looking forward to it being fixed!

**Comment by zero-master** [comment]
@BanjoCam Here is how it looks on my setup:

![image](https://user-images.githubusercontent.com/1130261/35735674-8ba6c952-0860-11e8-8e94-53c36f2fc0e0.png)

Looking forward to your screenshots! Thanks.

**Comment by BanjoCam** [comment]
@zero-master 
Ok so this is somewhat embarrassing because the screenshots don't really capture well what I'm seeing here. It's really subtle... it just becomes more noticeable the longer you stare at it. It's sort of... hazy.

Here is with downgraded freetype2:
![good code](https://user-images.githubusercontent.com/3679608/35761151-80c1dd68-0853-11e8-80e7-870df5f98958.png)
and here is with full system upgrade:
![bad again](https://user-images.githubusercontent.com/3679608/35761155-8a9797ba-0853-11e8-9b9b-016ffca0b02d.png)
In the "bad" one, the text looks sort of skinnier and less full. I really notice it on the word "section".

Hope that makes sense!

**Comment by zero-master** [comment]
@BanjoCam This is the best I get from Electron apps (atom/vscode)

![image](https://user-images.githubusercontent.com/1130261/35763555-dd83ab12-08e9-11e8-92ee-6707ca47d2c4.png)

What about Sublime Text's font rendering? Do you also experience the same issue there?

I think the only way to get better font rendering than what we have is by using "Medium" or "Semibold" font-weight + High DPI display.

To change font weight (provided your font supports these weights):

    // "editor.fontWeight": "500",
    // "editor.fontWeight": "700",
    // "editor.fontWeight": "600",

Or directly use font name + "Medium" or "Semibold" suffice:

    "editor.fontFamily": "Overpass Mono Medium",

**Comment by zero-master** [comment]
Please post:

1. Gnome Tweak Screenshot (Electron app seems to respect this from my testing)
![image](https://user-images.githubusercontent.com/1130261/35763629-5ee69fce-08eb-11e8-9aaf-39a21a97dfc4.png)

2. Output of `ls /etc/fonts/conf.d`
![image](https://user-images.githubusercontent.com/1130261/35763657-dc2b1244-08eb-11e8-9228-373b2eb12647.png)

3. VSCode's window.zoomLevel
![image](https://user-images.githubusercontent.com/1130261/35763667-2ab987f6-08ec-11e8-8a35-ba6935d642e0.png)

4. Output of `xdpyinfo | grep dots`

5. Display resolution and display physical size

6. Obviously, screenshot of the font rendering in VSCode and Sublime Text (for comparison)

**Comment by lucasar** [comment]
@ju1ius's [solution](https://github.com/Microsoft/vscode/issues/35675#issuecomment-353723921) worked for me.
I'm on Ubuntu 18.04
vscode: 1.19.3

**Comment by BanjoCam** [comment]
@zero-master 
Thank you so much for all your help. Between reinstalling for the umpteenth time, making sure my nvidia drivers were up to snuff (??? the Antergos installer seemed to have given up doing that for me despite my selection), the freetype issue seems to have resolved itself for me. More importantly, your suggestion to change the font weight has drastically improved the way things look! I still think some of the UI fonts look a little off but nothing that will detract from my work.

Thanks again!

**Comment by logycware** [comment]
@ju1ius's solution worked for me too.
tks.

**Comment by brenix** [comment]
Changing the electron version in the `.yarnrc` file to 1.7.12 and rebuilding did the trick for me. The fontconfig solutions didn't seem to work.

**Comment by moisadoru** [comment]
A script downloads that copies libfreetype6 2.8.0 to the app folder can be found here (works on Ubuntu):

https://gist.github.com/moisadoru/aa96b54a109fe890f4a685d82dd66b11

**Comment by zero-master** [comment]
![image](https://user-images.githubusercontent.com/1130261/36343362-3efe2e46-1446-11e8-9cf8-f3f76274cc6e.png)

Left - VSCode, Right - alacritty + vim.

On VSCode quality of font rendering is still bad.

**Comment by JustTestingGo** [comment]
@ju1ius's solution also worked for me.
Thank you!!!

**Comment by sandangel** [comment]
does anyone  know  how to fix this on  Manjaro Deepin ? I have tried to use custom fontconfig but it's not work. and gnome-tweak-tool seems non-compatible with Deepin Desktop

**Comment by sandangel** [comment]
hmm, look like it was because of the font Operator Mono I'm using. It look great on both Windows and MacOS but ugly on Linux (I'm currently on Fedora 27 Gnome)

![image](https://user-images.githubusercontent.com/22189661/36511363-bdb04150-17a9-11e8-9ffd-17be22644efe.png)

**Comment by theel0ja** [comment]
Downgraded to http://de.archive.ubuntu.com/ubuntu/pool/main/f/freetype/libfreetype6_2.8-0.2ubuntu2_amd64.deb on my Ubuntu 18.04, works perfectly!

**Comment by nanangarsyad** [comment]
Thank to [https://github.com/brenix](brenix)
By building vscode using electron 1.7.12 according to this [https://github.com/Microsoft/vscode/issues/35675#issuecomment-364628784](solution) worked for me.
Tried with electron > 1.7.12 gave me an `Assertion `args[0]->IsString()' failed.` and some native error, seemed it's only work with version 1.7.x

**Comment by Tyriar** [comment]
@nanangarsyad Electron 1.8 has some heavy performance regressions which block us from adopting. We're working on Electron 2.0 support now using the beta which should also have this issue fixed too.

**Comment by jgb** [comment]
Well... this bug isn't solved at all! Please reopen and fix.

**Comment by jacmoe** [comment]
Come on, guys!
This is not fixed yet.
I have abandoned VSCode (for now) - very disappointing.

**Comment by kolya-ay** [comment]
@vscodebot, It's quite dishonest to close the issue now before Electron version update. No matter how many workarounds exist in the field

**Comment by Tyriar** [comment]
@vscodebot bad bot! Naughty!

**Comment by jacmoe** [comment]
And here we are, in 2018, arguing with a bot :smile: 

Thanks @Tyriar

**Comment by jlippuner** [comment]
@brenix's solution worked for me (https://github.com/Microsoft/vscode/issues/35675#issuecomment-364628784)
I'm on Debian testing with libfreetype6 version 2.8.1.-2

**Comment by jacmoe** [comment]
If that's the solution, then I wonder why we can't have a release made with that fix?
That's the thing that I haven't tried - all other solutions either does nothing or does not apply to my system (Void Linux - rolling release).
I am reluctant to mess around with building Vscode from source, but I guess I'll have to bite the bullet.

**Comment by migueldemoura** [comment]
@Tyriar, it seems that electron 1.8 isn't needed, 1.7.12 fixes this as well.

**Comment by Tyriar** [comment]
@migueldemoura yep, it should hopefully be fixed in March as we're updating Electron for 1.22

**Comment by bpasero** [comment]
This should be fine now with Electron 1.7.12 that includes the fix from https://github.com/electron/libchromiumcontent/pull/387. Will be in Mondays insider build.

**Comment by nathan-osman** [comment]
Where can I grab a copy of the new build? It's not showing up in the APT repository and downloading straight from the website gives me the same version I already had installed (1.21.1).

**Comment by migueldemoura** [comment]
@nathan-osman, did you try the insiders version? `apt install code-insiders`

**Comment by paladdins** [comment]
Downloaded prev version of freetype
http://snapshot.debian.org/package/freetype/2.8-0.2/#libfreetype6_2.8-0.2
`And ran sudo dpkg -i libfreetype6_2.8-0.2_amd64.deb `
from the Download folder.
Then everyth fixed

**Comment by Obbi89** [comment]
@paladdins maybe change it to:
```shell
sudo dpkg -i libfreetype6_2.8-0.2_amd64.deb
sudo apt-mark hold libfreetype6 
```

**Comment by fsevenm** [comment]
Thank a lot. The solution fixed my problem also. But I wonder how to release the hold after executing it.
 `sudo apt-mark hold libfreetype6`

**Comment by sarbash** [comment]
> But I wonder how to release the hold after executing it.
```bash
$ man apt-mark
$ sudo apt-mark unhold libfreetype6
```

**Comment by peterducai** [comment]
on Ubuntu I think I fixed with 

`sudo apt install ubuntu-restricted-extras`

please confirm someone.. (without downgrading libfreetype)

**Comment by Obbi89** [comment]
Could be. It contains M$ proprietary ttf fonts. Might be that those are chosen then and cause less issues?

**Comment by simlevesque** [comment]
@peterducai I tried your package on a new install and it did not fix the issue. Downgrading freetype worked instantly.

**Comment by akurtovic** [comment]
I can confirm the issue on a fresh install of Ubuntu 18.04 beta with latest vscode. And downgrading libfreetype6 to 2.8-0.2 did fix it for me as well.

**Comment by dmitryvk** [comment]
Latest "insiders" build works fine with fresh version of freetype.

**Comment by Obbi89** [comment]
@dmitryvk yeah It has been known that newer electron versions did not have this issue.
So I guess they updated it finally. So we might expect this to be fixed by the next release.
Maybe this can be closed with the next monthly then :)

**Comment by ramya-rao-a** [comment]
Marking as verified as per updates above

**Comment by ziyan-junaideen** [comment]
I am on an Ubuntu 18.04 pre release and had artifacts in rendered fonts as described. Following the last few comments I installed `code-insiders`. The artifacts are no longer there. My libfreetype6 version is `2.8.1-2ubuntu1`. Thank you.

**Comment by sta-c0000** [comment]
I’m on Debian Stretch  (stable), just tried code-insider-1.22.0-1522420669, still looks bad, but have not changed libfreetype6… but I also do not have other apps with bad font rendering.

I will simply continue using vscode stable with a simple patch: `-webkit-text-stroke:0.25px;` …If interested, you might want anywhere from 0.1px to 0.5px, perhaps 0.33px or 0.4px.  This renders fonts with smoothing, potentially fat if you want them.  Here is where to apply the patch:

| What | Top level affects most VSCode content |
| --- | --- |
| Where | `resources/app/out/vs/workbench/electron-browser/bootstrap/preload.js` |
| From | `s.innerHTML=".monaco-shell { background-color:"+o+"; color:"+r+"; }"` |
| To | `s.innerHTML=".monaco-shell { background-color:"+o+"; color:"+r+"; -webkit-text-stroke:0.25px; }"` |

| What | Markdown preview and webview (e.g. Help → Welcome) |
| --- | --- |
| Where | `resources/app/out/vs/workbench/parts/html/browser/webview-pre.js` |
| From | `tmargin: 0;\n\t\t\t\tpadding: 0 20px;\n\t\t\t}` |
| To | `tmargin: 0;\n\t\t\t\tpadding: 0 20px; -webkit-text-stroke:0.25px;}` |

**Comment by ffk27** [comment]
Only this one worked for me https://launchpad.net/~no1wantdthisname/+archive/ubuntu/ppa/+build/13557985

**Comment by ulrich** [comment]
I had the same problem on Ubuntu Bionic and it's works fine when I downgrade FreeType to 2.8.0.

**Comment by thinw002** [comment]
I had a similar issue on Windows after upgrading to the latest VS Code. I fixed it considerably by changing the fontFamily setting:
```
{
    "editor.fontFamily": "Inconsolata, Monaco, Consolas, 'Courier New', monospace"
}
````

**Comment by AydinChavez** [comment]
When will vs code support the libfreetyp6 version 2.8.1 - does anybody know?
downgrading / apt-mark hold for a package is just a workaround for the time being but not a final solution

**Comment by gombosg** [comment]
Oh, I just installed v1.22.1, font rendering is _so beautiful_ now! The code editor fonts were OK before using custom fonts like Anonymous Pro, but the UI & integrated terminal fonts look way better now. Kudos!

(Info: I'm on Fedora 27, using the RPM vscode package, freetype 2.8.8, using ["Better font rendering"](https://github.com/folkswithhats/repo/blob/master/SPECS/fedy-font-config.spec) plugin from Fedy)

**Comment by ashrafuzzaman** [comment]
I did not had this issue until I upgraded Ubuntu to `Ubuntu 18.04 Bionic Beaver (development branch)`

**Comment by AydinChavez** [comment]
Ok, just received visual code 1.22.1 on my ubuntu via apt which finally solved the issue with libfreetype 2.8.1
Thanks to the contributors.

Details:
https://code.visualstudio.com/updates/v1_22

**Comment by jacmoe** [comment]
The March update (1.22) brought back VSCode for me - thanks a lot :smile: 
I almost forgotten how it looked like.
My system is Void Linux (rolling release), so if it works here, it would work anywhere :)

**Comment by sandangel** [comment]
Why I still having this issue:

![image](https://user-images.githubusercontent.com/22189661/39294543-f79cf832-4976-11e8-9043-d5853f0ea068.png)

here is my settings:

```json
{
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorTheme": "An Old Hope",
  "files.useExperimentalFileWatcher": true,
  "editor.wordWrap": "on",
  "editor.fontFamily": "'Operator Mono', 'Ubuntu Mono', 'Fira Mono for Powerline'",
  "editor.fontSize": 14,
  "editor.fontLigatures": true,
  "editor.fontWeight": "100",
  "editor.dragAndDrop": false,
  "editor.quickSuggestions": {
    "other": true,
    "comments": true,
    "strings": true
  },
  "terminal.integrated.fontSize": 14,
  "terminal.integrated.confirmOnExit": true,
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "terminal.integrated.fontFamily": "'Ubuntu Mono derivative Powerline', 'Fira Mono for Powerline'",
  "emmet.triggerExpansionOnTab": true,
  "sync.gist": "8379453cea23895245d897b59a7931a6",
  "sync.lastUpload": "",
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "sync.lastDownload": "2018-03-31T03:42:49.973Z",
  "sync.forceDownload": false,
  "sync.host": "",
  "sync.pathPrefix": "",
  "sync.quietSync": false,
  "sync.askGistName": false,
  "html.format.wrapAttributes": "force-aligned",
  "debug.inlineValues": true,
  "gitlens.codeLens.recentChange.enabled": false,
  "gitlens.codeLens.authors.enabled": false,
  "prettier.singleQuote": true,
  "prettier.printWidth": 100,
  "ng-c-ext.shutupMode": true,
  "ng42.barrels.useTemplates": {
    "header": false,
    "footer": false
  },
  "html-css-class-completion.includeGlobPattern": "**/*.{scss,css,html}",
  "rust-client.channel": "stable",
  "guides.enabled": false,
  "gitlens.keymap": "alternate",
  "sync.removeExtensions": true,
  "sync.syncExtensions": true,
  "gitlens.advanced.messages": {
    "suppressCommitHasNoPreviousCommitWarning": false,
    "suppressCommitNotFoundWarning": false,
    "suppressFileNotUnderSourceControlWarning": false,
    "suppressGitVersionWarning": false,
    "suppressLineUncommittedWarning": false,
    "suppressNoRepositoryWarning": false,
    "suppressResultsExplorerNotice": false,
    "suppressShowKeyBindingsNotice": true
  }
}
```

**Comment by Obbi89** [comment]
@sandangel 
Sorry can't see any issue in your image. Especially not the rendering issues this issue is related to

**Comment by sandangel** [comment]
hi, my image is showing how the font look like in linux and windows at the same time and on the same machine using vmware for virtual linux machine. they are very different although I’m using the same font and setup on both
