### ISSUE TITLE
Emmet Abbreviation should not work inside php tag (`<?php ?>`)

### ISSUE THREAD

**Issue by tangorboyz** [Microsoft/vscode#36367]
- VSCode Version: 1.17.1
- OS Version: Ubuntu 16.04

![image](https://user-images.githubusercontent.com/8751130/31623384-d68ba6de-b2d1-11e7-8c06-b6760fd7d8cb.png)

**Comment by ramya-rao-a** [comment]
At the moment, emmet cannot parse php file and identify html only areas.
But I have pushed a fix for the scenario mentioned above where something that is clearly not an emmet abbreviation is being treated as such
The fix will be out in Monday's Insiders build.

If you notice any other cases, please feel free to log an issue

**Comment by mjbvz** [comment]
I still see this with 2ab10d50163f008ada9a4aa215de8c884857ce99

![screen shot 2017-11-01 at 5 25 45 pm](https://user-images.githubusercontent.com/12821956/32304069-c0bb9328-bf29-11e7-8b28-27c403b2501b.png)
