### ISSUE TITLE
Pasting large file name kills VS Code

### ISSUE THREAD

**Issue by dstockhammer** [Microsoft/vscode#36703]
When pasting a large amount of text into the filename field in VS code, the editor hangs and dies. I did this today by accident. This is a very minor issue that's caused by user error, but I reckon it could be avoided by checking input length.

- VSCode Version:  1.17.2
- OS Version: Win 10 Pro 1709

Steps to Reproduce:

1. Create a new file
2. Paste some large text into file name field
3. VS Code dies, see screenshot:

![capture](https://user-images.githubusercontent.com/1156637/31862009-bd5316a0-b72e-11e7-80ca-be8792816d02.JPG)

**Comment by maxibanki** [comment]
In which filename field? In that when you rename the file in the explorer sidebar?

**Comment by dstockhammer** [comment]
Yes, the file name field in the sidebar. I could have made it clearer in the screen shot, my bad.

**Comment by bpasero** [comment]
@dstockhammer can you share what you pasted in there, I cannot reproduce with a simple large file pasted into the rename box.

**Comment by bpasero** [comment]
I pushed a change to trim the error message to 255 characters, that should improve the situation a bit.

**Comment by dstockhammer** [comment]
I can no longer reproduce on a machine with about the same specs. The editor still hangs for a couple of seconds, but no longer crashes. I think this is acceptable behaviour. 
Might have been something else going on on the machine at the time, I didn't extensively test the issue. Sorry for that!
