### ISSUE TITLE
Open Editors does not remember its prior setting

### ISSUE THREAD

**Issue by DeborahK** [Microsoft/vscode#37084]
- VSCode Version: Code 1.17.2 (b813d12980308015bcd2b3a2f6efa5c810c33ba5, 2017-10-16T13:59:48.528Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.7

---

Steps to Reproduce:

1. Open a folder in VS code.
2. Open a few files and close the Open Editors node.
3. Exit VS Code.
4. Reopen VS code and the Open Editors node is again open.

Up until recently, the Open Editors node would retain its prior setting. So if it was closed, it would remain closed even after exiting VS Code and reopening it.

Reproduces without extensions: Yes/No

**Comment by isidorn** [comment]
This has to do with how we are storing split view show state -> assigning to @sandy081

**Comment by sandy081** [comment]
@DeborahK Did you use following option to hide Open Editors view? If so this persists only per workspace.

![image](https://user-images.githubusercontent.com/10746682/32174973-aba8947e-bd83-11e7-87fe-4e58d700f0c1.png)

**Comment by DeborahK** [comment]
No, I just closed it using the arrow on the left:
![image](https://user-images.githubusercontent.com/7987365/32176391-c20c54e2-bd44-11e7-90d8-1711b0ad7d54.png)

Up until recently, if I closed it, then later closed VS Code entirely, next time I opened VS Code it would remember my last setting. It remembers all of my other settings (such as which edit windows I had opened)

**Comment by sandy081** [comment]
Looks like this got already fixed in latest insiders. Please try it out from here - https://code.visualstudio.com/insiders

**Comment by bpasero** [comment]
@sandy081 I can still reproduce:
* collapse open editors view
* click on search viewlet
* reload window
* click explorer
* open editors view is expanded again

**Comment by sandy081** [comment]
There is some mess around how view states are retrieved. Would like to tackle it by clean up.
