### ISSUE TITLE
Using IME with markdown preview enabled, press ESC/BACKSPACE leads in control characters

### ISSUE THREAD

**Issue by timonwong** [microsoft/vscode#37114]
- VSCode Version: 1.17.2
- OS Version: macOS 10.11.6

Steps to Reproduce:

HINT: You may need to enable `editor.renderControlCharacters` in order to see what happens, or the control characters is invisible.

1. Open a "markdown preview" in a split (just ensure the markdown preview is visible). 
2. In another split, edit *arbitrary* file with IME (mine with Chinese Pinyin).
3. Type some characters using IME, before put them on screen, type backspace/esc to see what happens.

Just see the screenshot for example:

![hmmm](https://user-images.githubusercontent.com/1398228/32153881-2af27fb2-bcfb-11e7-9a22-c75954a272b5.gif)

Reproduces without extensions: Yes

**Comment by rebornix** [comment]
It only happens when you are previewing the markdown content, which means it's caused by the webview. Fun fact is I can't reproduce it when debugging master bits.

**Comment by rebornix** [comment]
It turns out that when we preview the md content, the webview will lead to the problem as described in https://github.com/Microsoft/vscode/issues/24981 (you need to double backspace to delete characters). This problem was introduced in Electron 1.5.x, fixed by backporting in 1.6.x, apparently they forgot to backport the fix in 1.7.x. Ideally this can be fixed once we adopt 1.8.x.

More info https://github.com/electron/electron/issues/9173#issuecomment-336248715 , cc @bpasero @Tyriar

**Comment by gaoliang** [comment]
In version 1.19.0, this is not the only problem in the markdown file, but all the files will appear.

![复现](https://user-images.githubusercontent.com/18087875/34021124-07b17e30-e173-11e7-8188-5befdbd5daea.gif)

**Comment by Proxy305** [comment]
From my observation, this issue only triggers as long as I have more than one editor opened, **or have the side bar extended**. This issue goes away immediately after the closing all the extra editors AND the sidebar, however reoccurs after the extension of side bar or the opening of extra editors.

More IMEs and file type could be affected. The built-in Japanese IME of macOS is affected, and TeX(.tex) files are also affected.

- VSCode version: 1.19.1
- macOS version: 10.12.6

**Comment by gaoliang** [comment]
any update?

**Comment by chenxinlong** [comment]
When you push files with these control character to github, it would be replaced with character " � " like :
![image](https://user-images.githubusercontent.com/9261954/36013315-775d70ac-0d9e-11e8-8efa-63c5a32fb70f.png)

In edit mode on github, the � character becomes to a red dot, like : 
![image](https://user-images.githubusercontent.com/9261954/36013345-9718fb64-0d9e-11e8-8008-4ad35334ffd7.png)

**Comment by Tidyzq** [comment]
+1

**Comment by tzing** [comment]
similar issue here:
if one put an emoji which is longer than 2 byte (for example 🇺🇸, `\xe7\xbe\x8e\xe5\x9c\x8b`) and hit the backspace, it will left an invisible symbol in the editor (`🇺`, `\xf0\x9f\x87\xba`)

**Comment by malun666** [comment]
Open User Setting, then add `"editor.renderControlCharacters": true,` .  Just, help for show the  invisible symbol .
 +1

**Comment by h12345jack** [comment]
similar mistakes happened in the latex edit scene

**Comment by jaggerwang** [comment]
+1 same problem

**Comment by acbetter** [comment]
+1 and I have the same problem. Newest stable version VS Code and macOS 10.13.5.

**Comment by rebornix** [comment]
From next week's Insider, this issue will no longer exist as we adopted Electron 2.0.x.

**Comment by tkow** [comment]
Is this problem still left?
I saw updating Electron reverted.
https://github.com/Microsoft/vscode/commit/e47a9c9eef373fc5e2af0c21053b6da062617935

**Comment by yoyoys** [comment]
@tkow I still have this problem today.

**Comment by njleonzhang** [comment]
@rebornix can I download the Insider Build? This issue persist in 1.25.1, and really annoying.

**Comment by acbetter** [comment]
@njleonzhang I have tried the version and the bug still left.

**Comment by wkosea** [comment]
The problem still exist at version 1.28 with no way to fix the bug.
I even don't know that until I upload my code to gitHub, then I saw a large number of ??.

**Comment by MichEam** [comment]
+1 same problem

**Comment by rebornix** [comment]
> From next week's Insider, this issue will no longer exist as we adopted Electron 2.0.x.

I should be more precise when I said so. The first time when I tested it works but now on Electron 2.0.12, the bug is here again. We probably need a champion on IME from Electron side, to ensure it doesn't regress again and again.

**Comment by leisurelicht** [comment]
+1 same problem (version: 1.29.1)

**Comment by able8** [comment]
+1  1.29.1 (1.29.1)

**Comment by InnerPeace-Wu** [comment]
> It only happens when you are previewing the markdown content, which means it's caused by the webview.

It seems the problem is triggered by previewing. For latex, I tried to avoid it by setting external pdf viewer.
macos: vscode + skim
windows: vscode + sumatraPDF

**Comment by tete1030** [comment]
@rebornix is there any issue created in the electron repo on the problem on version 2.0.12 ? Or has it been fixed? It seems the original issue https://github.com/electron/electron/issues/9173 has been closed due to unsupported version.

**Comment by rebornix** [comment]
@tete1030 thanks for your help! I already left comment there ;) The trick is only input outside of the webview is running into this weird issue.

**Comment by YunanChen** [comment]
+ 1 The same problems when using the Chinese input methods and opening the Markdown Preview Enhanced

**Comment by kouhei** [comment]
same problem exists in 1.30.0, but it seems to be fixed in insiders(1.30.1).
IME: MacOS default Japanese IME

**Comment by lookas2001** [comment]
> same problem exists in 1.30.0, but it seems to be fixed in insiders(1.30.1).
> IME: MacOS default Japanese IME

Really? My VSCode still has this problem.

macOS 10.14.1
Chinese IME of Sogou Input
Download insiders edition VSCode (1.31.0-insiders) from the official website

After I typed some word and deleted them, the bug is reproduced.

**Comment by kouhei** [comment]
> > same problem exists in 1.30.0, but it seems to be fixed in insiders(1.30.1).
> > IME: MacOS default Japanese IME
> 
> Really? My VSCode still has this problem.
> 
> macOS 10.14.1
> Chinese IME of Sogou Input
> Download insiders edition VSCode (1.31.0-insiders) from the official website
> 
> After I typed some word and deleted them, the bug was reproduced.

I tried it again, and then this problem was reproduced.
I was wrong. I'm sorry.

**Comment by 0x4f5da2** [comment]
The same issue can be reproduced on macOS 10.14.2 with default Chinese IME.😅

**Comment by He2hiwei** [comment]
The same issue can be reproduced on macOS 10.14.2 too. It is is so disturbing. When will it be fixed?

**Comment by rebornix** [comment]
@kouhei @0x4f5da2 @He2hiwei do you mind sharing more details about the version of VSCode you are using and steps to reproduce? 

Example:

* Version 1.31.0-insider (1.31.0-insider)
* Commit: 50854c0a705745bbf50982fab3c30fd6bd1f7b19
* macOS 10.14.2 
* [ ] whether you have markdown preview open

The reason I asked for you help on this as I can't reproduce this bug anymore.

**Comment by STayinloves** [comment]
Hi @rebornix 
I'm using `1.31.0-insider` with [latex-workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) plugin which has a pdf preview webview. And I'm using macOS(`10.14.1`) default Chinese IME.
The bug cannot be consistently reproduced in `1.31.0-insider`, but it still happened from time to time if you input and delete character **very quickly**.
For LaTeX editing, this bug is pretty annoying, because the `^H` in TeX will trigger a compilation termination with errors.

**Comment by robertying** [comment]
It's happening not only in editor but also in VSCode's every input field (I believe).

I used VSCode's built-in Git extension and submitted a commit message in it, and somewhere in my final commit message appears a � on GitHub.

**Comment by zcc0721** [comment]
- macOS Mojava 10.14.3
- vscode 1.31.1 (1.31.1) 1b8e8302e405050205e69b59abb3559592bb9e60

Maybe this bug has been fixed. Now I cannot meet this bug any more.

**Comment by MyroshnykRoman** [comment]
Issue is still reproduced with Version: 1.38.1
and Japanese IME

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by acbetter** [comment]
The bug seems to be fixed in recent nightly insider builds.
Tested Code Version: 1.40.0-insider and no other extensions installed.

**Comment by bpasero** [comment]
Awesome, thanks for trying. Can others confirm too?
