### ISSUE TITLE
Multiroot debug - ${config:} variables do not get resolved (Python Extension)

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#37191]
- VSCode Version: Version 1.18.0-insider (1.18.0-insider) 2017-10-27T05:08:02.018Z
- OS Version: OSX Sierra

Problem: Configured python path in ```settings.json``` not used by debugger in Multi-root scenario. Hence Python debugging in multi-root scenarios wouldn't work.

Steps to Reproduce (generic example):

1. Open VS Code (insiders)
2. Open folder A and folder B (multi-root scenario)
3. Go into any folder, lets say folder A
4. Add a file named ```app.js```
5. Create a ```launch.json``` config file for this workspace folder
6. Add args as follows:
```json
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/app.js",
            "args": [
                "${config:css.lint.boxModel}"
            ]
        },
```

7. Debug the above ```app.js``` file
The output would display the value ```ignore``` in the output window (default value for ```css.lint.boxModel```

8. Go into your workspace Folder A and now add the following setting into your ```settings.json``` file (remember, workspace folder settings not workspace settings).
```json
{
    "css.lint.boxModel": "warning"
}
```
9. Repeat the above debugging step, and it will still display ```ignore```.
I.e. the value ```${config:css.lint.boxModel}``` is not correctly translated.  
10. However if you were to change the above setting in the workspace setting, it works.
I.e. the translation does not seem to work in workspace folder settings.

11. To test the above issue with Python extension, I'm using the following in the args
```"${config:python.pythonPath}"```.  

FYI: the setting ```python.pythonPath``` is configured to work under mult-root scenarios as per the [following instructions](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#settings).
here are the config settings in my package.json (extension).
```json
    "python.pythonPath": {
	"type": "string",
	"default": "python",
	"scope": "resource"					
    },
```

Reproduces without extensions: Yes

**Comment by isidorn** [comment]
@DonJayamanne I have pushed a potential fix for this. Can you please try tomorrow's insiders and let me know if it works.
In case it does not, I believe you are the original author of this code so feel free to place a breakpoint [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configurationResolver/node/configurationResolverService.ts#L169) and let me know what seems to be going on.

**Comment by DonJayamanne** [comment]
@isidorn Isn't it a little premature to close this issue. I tested the code using the Node.js sample and it still fails. Will debug and get back to you.

**Comment by DonJayamanne** [comment]
@isidorn  Tested the node.js sample I provided above, and it fails. Will debug and let you know what's going on. I'd reopen this issue.

**Comment by isidorn** [comment]
@DonJayamanne thanks for trying, reopening

**Comment by DonJayamanne** [comment]
@isidorn can you confirm your changes made its way into the insiders build? 
I don't think it is, that may be why its not working. I just tested this locally using the source and it seems to work.

**Comment by DonJayamanne** [comment]
I'll test this in tomorrows insider build and close this issue if it works then.

**Comment by weinand** [comment]
@DonJayamanne Isi said this morning "tomorrow's insiders". This means the fix will be available in tomorrow's insiders and not in the current insiders.

**Comment by DonJayamanne** [comment]
@weinand lol, missed that. Closing this issue, as it works locally (built from source)
@isidorn apologies for the confusion

**Comment by DonJayamanne** [comment]
@isidorn tested on insiders and can confirm it works. Thanks

**Comment by isidorn** [comment]
@DonJayamanne thanks, adding verified label
