### ISSUE TITLE
Git: sometimes changing a file does not update the git viewlet

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#37417]
We are sometimes seeing the Git view not showing the status after making changes to a file (either new file or existing file). We should try to find out if this is a case of missing file events or other flaw in our logic.

When I saw this I could verify that it was not related to file events.

**Comment by joaomoreno** [comment]
Fixed by 58c6729a62ee2153412c7731f06a101e778a72b7. @bpasero Just mark `verified` if you don't see it for a while.

**Comment by joaomoreno** [comment]
Reopening since I saw this today and @anteprimorac reports the same.

**Comment by bpasero** [comment]
@joaomoreno fixed now?

**Comment by anteprimorac** [comment]
I still see the issue. I tested it on new stable version and it looks that reopening file fix doesn’t work in multiroot workspace.

**Comment by ha404** [comment]
Here in 2018 and currently reporting this is still a problem.

**Comment by joaomoreno** [comment]
@anteprimorac Can you still reproduce this?

@ha404 Can you reproduce this with our [insider release](https://code.visualstudio.com/insiders)?

This is likely fixed in `master`, due to missing file events @bpasero

**Comment by anteprimorac** [comment]
@joaomoreno I can not reproduce it on stable release

**Comment by anteprimorac** [comment]
It happened again - http://take.ms/vIPXJ

Steps to reproduce it:
1. Make changes to file
2. Commit changes
3. Undo last commit
4. Create new branch
5. Commit changes to new branch
6. Git viewlet is not updated, but file diff view is ok.

**Comment by joaomoreno** [comment]
@anteprimorac Are those steps *very* reliable?

**Comment by joaomoreno** [comment]
@anteprimorac Are those steps *very* reliable?

**Comment by anteprimorac** [comment]
@joaomoreno I noticed it while working, so I do not know if some steps are redundant. I’ll try to reproduce it in test environment.

**Comment by feryardiant** [comment]
Having same issue on windows

```
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

![screencast-2018-05-06](https://user-images.githubusercontent.com/508665/39666267-2cca45e0-50cb-11e8-8b8d-c848ab61fa63.gif)

Noticed that reloading Source Control will showing files on `\cygdrive\d\...` instead of `D:\...`

Additional info (just in case) :
- Git v2.8.3 installed on Babun (cygwin)
- Using Bash (WSL) on VS Code Integrated Terminal
- Win 10 Home Single Language 64bit version 1709 build 16299.371

**Comment by feryardiant** [comment]
Also this might be related to #26642, #27715 and #41642

**Comment by feryardiant** [comment]
Update: [this script](https://gist.github.com/nickbudi/4b489f50086db805ea0f3864aa93a9f8) fix my issue.

**Comment by jiriskacel** [comment]
I encoutered the same issue, if the opened folder in Code was not the one with `.git` in it but some subfolder.

Windows 10 with git 2.14.1.windows.1
```

Version: 1.26.0
Commit: 4e9361845dc28659923a300945f84731393e210d
Date: 2018-08-13T16:29:31.933Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Comment by joaomoreno** [comment]
Cygwin is not supported. Different root folder than the opened folder in explorer is another issue. Closing this for now.
