### ISSUE TITLE
do not active debuggers when creating debug env drop down menu

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#37929]
Problem:
- install Java debugger
- open a folder with no launch.json
- switch to debug view and press gear button

Observe:
it looks like nothing is happening but in reality Java is initialising and starting Java language server. After a long time the debug env drop down appears.

Analysis:
Building the debug env drop down seems to activate all debug extensions.

Solution:
We should try to build the debug env drop down list only from declarative information found in the package.json. No debugger extensions should be activated for this.

/cc @aeschli

**Comment by isidorn** [comment]
I acknowledge the bug, however due to how the code is structured on my side this would require a refactoring in the [guessAdapter](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugConfigurationManager.ts#L397) method which I am not so keen on doing because we have better fine grained events as a workaround. Thus pushing this to the backlog

**Comment by isidorn** [comment]
Fixed in latest via https://github.com/Microsoft/vscode/commit/42512b2c59d9d103bcc5ad69b92279b217c9fb74

**Comment by isidorn** [comment]
My mistake, acutally this is not fixed via that commit

**Comment by kyliel** [comment]
How's going on for this bug? One more customer reported that they still see Java language server running on the bottom when developing a python file. It is strange. Thank you. 
https://github.com/Microsoft/vscode-java-debug/issues/238

**Comment by isidorn** [comment]
I have cleaned up the activation events and this is now fixed via https://github.com/Microsoft/vscode/pull/59464

However since this change is a bit delicate I would prefer to have the whole milestone to self host on it in insiders before we release it in stable. Due to that I will merge the PR in 4 days, so it is included in the next week insider, however it will be only in the october stable release (in a month).

**Comment by mjbvz** [comment]
Using our process explorer, I still see the java debugger extension being activated in this case. There is also  a slight delay when clicking on the gear

**Comment by isidorn** [comment]
After looking deeper into this, it is fine since the java debugger is activating onDebugInitialConfigurations since it is providing the initial configurations dynamically. Thus we have to activate it since we do not know which debugger the user will chose.

https://github.com/Microsoft/vscode-java-debug/blob/14fe7d5d0d41a397eaff4f3701860653850058fb/package.json#L31

Closing as designed.

To verify: debug a node program, and verify that the java extension does not get activated
