### ISSUE TITLE
Autocomplete shows multiple of the same item

### ISSUE THREAD

**Issue by jtsom** [Microsoft/vscode#37930]
- VSCode Version: Code - Insiders 1.18.0-insider (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T08:15:14.690Z)
- OS Version: Darwin x64 17.2.0
- Extensions: Extensions are disabled
---

Steps to Reproduce:

1. Start typing code. Autocomplete popup shows up.
2. Popup shows multiple items of the same thing - up to 8 to 10

<img width="872" alt="image" src="https://user-images.githubusercontent.com/13488/32603783-0453e14a-c519-11e7-8a08-6d1efba1fd42.png">

Reproduces without extensions: Yes

**Comment by jtsom** [comment]
A little more info... this seems to happen when VC Code is set to use it's own version of Typescript (2.6.1). When I switch to the version in the project (2.4.2), I see the correct popup items.

**Comment by mjbvz** [comment]
@jtsom If you scroll through these suggestions, do they all have identical descriptions?

TS 2.6 brought support for automatic imports. If there are multiple `MatSnackBarConfig` defined in your project, we will show an entry for each unique one. Selecting one should add the import from the corresponding file

**Comment by jtsom** [comment]
Yes, each one has the same description. It definitely looks like it's just duplicating the entries. Again when I switched to using the project's Typescript, the popup was much shorter.

**Comment by mjbvz** [comment]
Can you please collect the typescript server trace of this to help us investigate. To do this:

1. Set `"typescript.tsserver.trace": "verbose"` in vscode
1. Trigger the incorrect suggestion again
1. Open the `output` view and go to the `typescript` section

    <img width="567" alt="screen shot 2017-11-10 at 11 17 24 am" src="https://user-images.githubusercontent.com/12821956/32674596-bfc14f54-c608-11e7-8fae-2f270704976a.png">

1. Share the output from there

Thanks

**Comment by jtsom** [comment]
Sure. Here you go. With a screenshot of what I did that generated the output:

![image](https://user-images.githubusercontent.com/13488/32674932-1fdbc54e-c623-11e7-8981-d9aa72a16a7c.png)

[typescripttrace.txt](https://github.com/Microsoft/vscode/files/1462484/typescripttrace.txt)

**Comment by jtsom** [comment]
FWIW, here's a screenshot with Typescript set to the project's (2.4.2):

![image](https://user-images.githubusercontent.com/13488/32675115-c705c2d4-c623-11e7-8b8e-c3fdf28b5424.png)

**Comment by mjbvz** [comment]
Thanks for the additional info! I confirmed the bug and have opened https://github.com/Microsoft/TypeScript/issues/19922 to track this against TypeScript

Closing as upstream

**Comment by jtsom** [comment]
Any idea when this is going to be filtered back to VS Code? I see the latest insiders has an insiders version of Typescript, but doesn't seem to fix the problem.

**Comment by mjbvz** [comment]
This should be fixed in TypeScript@next (Typescript 2.7). You can use this version in current versions of VS Code by following these instructions: https://code.visualstudio.com/Docs/languages/typescript#_using-newer-typescript-versions

**Comment by jtsom** [comment]
Sorry to say, this problem still exists with Typescript 2.7.

Here's screenshot from 2.6.2:

![ts262](https://user-images.githubusercontent.com/13488/33895681-0c0aa1fa-df2f-11e7-961e-ad52db9602f2.PNG)

And here's one from the latest 2.7dev version - it's actually worse!

![ts270dev](https://user-images.githubusercontent.com/13488/33895704-16b0e9d4-df2f-11e7-9243-66a39fde6c6b.PNG)
