### ISSUE TITLE
File -> Save As and Add Folder to Workspace has the same shortcut

### ISSUE THREAD

**Issue by chengkiang** [Microsoft/vscode#38401]
- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T21:22:49.932Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-mocha|Com|0.1.1
vscode-eslint|dba|1.4.3
vscode-npm-script|eg2|0.3.3
auto-close-tag|for|0.5.3
code-runner|for|0.8.3
rest-client|hum|0.16.0
search-node-modules|jas|1.2.0
prettify-json|moh|0.0.3
cpptools|ms-|0.14.2
csharp|ms-|1.13.1
sublime-keybindings|ms-|3.0.3
vscode-arduino|vsc|0.2.10
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.5.0

(1 theme extensions excluded)

---
When I tried to use Alt-F, A to do a File, Save **A**s, nothing happens. Then I found that **A**dd Folder to Workspace has the same shortcut key of "A".

Steps to Reproduce:

1. Press Alt-F, then A. 
2. Nothing happens as both File Save **A**s and **A**dd Folder to Workspace has the same shortcuts.

Reproduces without extensions: Yes/No
![image](https://user-images.githubusercontent.com/24908779/32829809-2718274e-ca2e-11e7-80e4-a94ea57221ad.png)

**Comment by bpasero** [comment]
We fixed that, and will include it in our next stable update.

**Comment by chengkiang** [comment]
The latest 1.18.1 still has this issue. Both Add Folder to Workspace and File Save As are assigned "A" for the shortcut key, so I am still unable to trigger a File Save As using Alt-F, A.
