### ISSUE TITLE
Setting for Selection Dragging Scroll Speed

### ISSUE THREAD

**Issue by jabacchetta** [microsoft/vscode#40890]
As someone else [documented on Stack Overflow](https://stackoverflow.com/questions/47767227/visual-studio-code-dragging-to-highlight-text-moves-way-too-fast-at-edges), when attempting to highlight code and scrolling above/below the current view, the scroll speed makes it impossible to accurately highlight the desired lines of code.

The expected behavior is a more controlled speed, similar to many other editors.

**Comment by Tyriar** [comment]
What platform are you on?

**Comment by jabacchetta** [comment]
**VSCode Version:** 1.19.1
**OS Version:** macOS 10.13.2

**Reproduces without extensions:** Yes

**Comment by dguisinger** [comment]
Please come up with a solution for this, it doesn't need to be a feature request for adding a setting, just make the application work correctly.  You have no idea how many times I am swearing at the your application every day when i go to select just 2-3 lines of code and within 1 second 10 pages fly by.

This is a bug in the editor.  Running VS Code 1.22.2 on OS X 10.13.2

**Comment by jabacchetta** [comment]
For the time being, the following setting should fix this:

`"editor.smoothScrolling": true`

**Comment by atomiks** [comment]
This is still a problem... `"editor.smoothScrolling": true` doesn't seem to do anything for me. The autoscroll is way too fast and doesn't respond exponentially as the cursor moves closer to the top/bottom of the editor boundary, it's fast instantly.

Please copy the behavior of Atom or [`react-beautiful-dnd`](https://react-beautiful-dnd.netlify.com/?selectedKind=single%20vertical%20list&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0)

**Comment by zzador** [comment]
Can confirm the problem. While selecting text, touching the upper or lower border of the current editwindow to scroll up or down respectively activates hyperspeed within the file. As this effect is impressive to watch it can make selection a little bit unprecise in certain situations. I would strongly recommend to make the selection-scroll-speed an adjustable variable in the settings or at least in the settings.json.

However you (the devs) made a very useful and flexible IDE so far. Finding myself using it more and more for every language I have to code in.

**Comment by mulligandev** [comment]
Although smooth scrolling is a quick fix to this, I think a setting would be beneficial so that we can have more control over the speed. With smooth scrolling set to false, it is way too fast, but when set to true it's a bit too slow.

**Comment by MarvelDC** [comment]
This is still a problem for me, even with smooth scrolling, as if you were to highlight over the right-hand side scroll bar, it'll move the screen instantly to the end of the line. With the high speed also, it is common to accidentally move the mouse above or below a line, which will instantly move the screen to the end of the line of the new mouse line.

**Comment by jtbrower** [comment]
After becoming frustrated with the constant crashes of my Visual Studio Pro, I gave VSCode a shot.  I have been using it for about a week now and I am extremely impressed!  Good job to the team.

However, like others have stated, I am having usability issues when it comes to scrolling using the mouse.  If you select text that moves near or beyond the current views borders, the selection goes into hyper speed.  Its so fast that it has made selection laughable literally.  It will end up completely overshooting what you wanted to select.  So then you try to head backwards and unselect, but that ends up overshooting the other direction.  It will knock a few minutes of a persons daily patience threshold :).

Although I would prefer to keep my hand on the mouse, there is a work-around and that is to use the keyboard's shift+ arrow up/ arrow down keys.  If selection with the mouse would work the same as it does with the shift button and arrow keys, that would be great.  Otherwise, its not a show-stopper and it doesn't crash for me like that overpriced Visual Studio subscription I have been paying for.

**Comment by nistre** [comment]
Soo... year later checking in.  Is there going to be an adjustment to the speed of scrolling while selecting text?  With a mouse it is more bearable because of the use of the scroll wheel, but sometimes I get too close the the top or bottom and then it goes all haywire.  With a trackpad alone it really affects the usability and when there are multiple lines like this to have only the arrow keys as a viable solution is not a good UX.

**Comment by kahsa** [comment]
Still problem for me.

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.10.9-arch1-1

**Comment by niclasmattsson** [comment]
Enabling smoothScrolling is NOT a fix for this, because:

* it only marginally slows down drag scrolling
* it makes ordinary mousewheel scrolling laggy, unbearably so if you use a free-spinning mouse wheel

3.5 years is more accurate BTW...

**Comment by 1024th** [comment]
SmoothScrolling doesn't solve the issue perfectly.

**Why is it so hard to add a setting for selection dragging scroll speed?**

**Comment by WarrenWeckesser** [comment]
*Please* fix this.  The default dragging scroll speed is simply too fast.

**Comment by thedoc31** [comment]
This drives me crazy all the time. Both horizontal and vertical scrolling while selecting lines is MUCH MUCH too fast. Using Big Sur 11.4 and a Logitech corded USB mouse.

**Comment by fan3cn** [comment]
This also bothers me too much recently. I came from IntelJ and now switch to Visual Studio, can't image such a small and obvious bug can exist for 3 years remaining unfixed.

**Comment by singh-karan-7** [comment]
Love Visual Code, but this selection scrolling is really annoying. Should be an easy fix.

**Comment by ikeller96** [comment]
Does anyone know if this could possibly have anything to do with MacOS settings as well? I am also seeing this scrolling issue. It's extremely difficult to select the actual lines that I want because it scrolls through the page way too quickly.

**Comment by muratgozel** [comment]
Maybe we should have chosen "AI Based Selection Dragging Speed" as a title instead of just "Selection Dragging Speed"...

**Comment by Vrajs16** [comment]
It really is annoying to highlight code with a mouse. I love this editor and use it more and more with all my languages. Please fix this issue. Thank you vscode team.

**Comment by neodon** [comment]
This is so aggravating, and enabling smooth scrolling is only a partial hacky fix.  Basically I can't use horizontal split views because of this.

The other thing that needs a user-configurable setting is how many lines or pixels away from the top or bottom of the view should trigger this auto-scrolling feature.

If I highlight text within **5 lines** of the top or bottom of the view, it starts scrolling at like 9,000 lines-per-second:

https://user-images.githubusercontent.com/82944/152852594-39172594-684c-4089-ae80-bd74f8e49a33.mp4

Despite my annoyance with this particular thing, I want to make sure you all know that you are doing awesome work and overall I love VSCode!

**Comment by jonathanbouren** [comment]
Still a problem. Found this thread while looking for a solution, it’s quite aggravating. scroll down, miss by 200 lines. Scroll back up. Miss by 100 lines.

**Comment by miracuruzrh** [comment]
> Still a problem. Found this thread while looking for a solution, it’s quite aggravating. scroll down, miss by 200 lines. Scroll back up. Miss by 100 lines.

Same for me. But I think this behavior is just a view day for me. Before I had no scrolling issues. Anyone knows if this is from a recent update?

**Comment by WarrenWeckesser** [comment]
This is probably the same issue: https://github.com/microsoft/vscode/issues/32267

**Comment by mz3** [comment]
*CLICK* (That's my seatbelt buckling as I prepare to expand my selection)

This would be great to fix. I personally don't know any developers with reflexes epic enough to actually use the mouse to select lines. Being able to do that saves a crazy amount of time. Fixing this would probably impact the world economy.

**Comment by cbosoft** [comment]
Enabling smooth scrolling worked for me on Version: 1.65.2 (Universal) on MacOS

**Comment by yanpeng** [comment]
plz fix this.

**Comment by jdevng** [comment]
Microsoft: Please stop working on features and fix this issue. Separate selection speed from scroll speed. I'm looking at nvim as an alternative.

**Comment by atomiks** [comment]
> Microsoft: Please stop working on features and fix this issue

I have to agree, VS Code's new features are welcome, but they're quite frankly nowhere near as important as getting a basic UX feature like this right.

I don't want to complain too much about free/OSS products, but like... this is like a **basic** UX feature that has been open for nearly 5 years for the most popular text editor for developers worldwide, how has this not been prioritized yet? I commented here in 2018, and there's zero progress or news of anything related to fixing this issue.

I use a Mac trackpad — the "workaround" `editor.smoothScrolling` seems to make it less ridiculous in speed to the point where it's _partially_ usable, but it still doesn't have the expected UX of exponential velocity depending on where the cursor is in relation to the edge of the boundary Plus, users are faced with the unusable UX **by default**.

As I mentioned in 2018, Atom/`react-beautiful-dnd`/Chrome's text selection is an example of how the scroll velocity should behave (although I think it could be less sensitive than this still).

Video:

https://user-images.githubusercontent.com/22450188/174990165-113dcbd6-34f6-445b-93f5-f32388280f68.mp4

**Comment by jdevng** [comment]
well stated. Problems like this make me wonder how bad does it have to be management wise for the engineers working on this that this problem isn't solved by now. To not address something that an average programmer uses up to every minute or so is unimaginable to me.

**Comment by coreydbrown** [comment]
This issue is absolutely infuriating. Highlighting a group of lines spanning more than the size of the screen is a task that almost every user of VS Code has to deal with, and often many times per day. Yet somehow it's impossible to carry out this simple task while using the mouse. I want to move up by 5 lines, not 500.

**Comment by WarrenWeckesser** [comment]
It would be nice if the VSCode devs could learn a lesson from other software that gets this right.  When the cursor is just a little ways out of the text area, scroll *slowly*.  Speed up the scrolling as the cursor moves further away from the text area.

**Comment by muratgozel** [comment]
I switched to [webstorm](https://www.jetbrains.com/webstorm/), it's better in many ways. After leaving Atom, I'm happy again.

**Comment by Mausinator08** [comment]
I've been experiencing the same thing as every one else pretty much since VS Code was officially released. If not the entire time. It happens on Windows 10 and 11 x64. It also happens to us at work on both M1 Macbook Pro and Intel based Macbook Pro. It also happened in my previous job this year on Ubuntu Desktop (latest). I'll see if I can't find a usable work around, short of smooth scrolling setting.

Great IDE by the way, I use it for just about anything! Even C++ and C#! (I got tired of navigating layered menus in VS 2019 and 2022 so now I write cmake scripts instead.)

**Comment by Mausinator08** [comment]
OK no setting regarding scroll, speed, drag, select, mouse, screen edge, or cursor seems to help. I wonder if there is at least an extension that can solve this for now? Or if one can even be made for something like this?

**Comment by yaronhb** [comment]
> It would be nice if the VSCode devs could learn a lesson from other software that gets this right. When the cursor is just a little ways out of the text area, scroll _slowly_. Speed up the scrolling as the cursor moves further away from the text area.

Absolutely!!!!

**Comment by s-devaney** [comment]
This is such a basic usability issue, come on guys...

**Comment by DerekWSmith** [comment]
This is still an issue.  And totally agree: absolutely frustrating.

**Comment by BetterRage** [comment]
pls fix

**Comment by YuzheHao** [comment]
I am glad to find the thread: now I know I don't have a hand-shaking problem!
I don't feel anything changed after setting `editor.smoothScrolling` to true.

Please fix this error, sometimes it can be really frustrating.

**Comment by petrvalkoun-gooddata** [comment]
still broken, please fix

**Comment by Bruledamien** [comment]
+1

**Comment by felixfaire** [comment]
I am also experiencing this very frustrating issue. I appreciate that this fix may be non trivial (otherwise developers ignoring this very active thread seems strange), but it is the only major usability bug / issue I have every day with VS Code.

**Comment by WarrenWeckesser** [comment]
The label on this issue should be `bug`, not `feature-request`.

**Comment by BetterRage** [comment]
thank you very much, in which version of vs code can i find this fix?

Alexandru Dima ***@***.***> schrieb am Mi., 21. Sep. 2022,
11:51:

**Comment by DuchSuvaa** [comment]
In my opinion, the best way to deal with this problem is to make the selection, and then - without releasing shift - use up/down arrows. Still very fast, but slow enough for human brain.

**Comment by rzhao271** [comment]
@BetterRage you can get [VS Code Insiders](https://code.visualstudio.com/insiders) to try the change out now, or wait for the next stable version that will be out next week.

**Comment by SwiftiSwift** [comment]
what is the option called in vscode settings?

**Comment by Mausinator08** [comment]
I dont think there is one. It was simply implemented to behave this way by default. I can now drag scroll in a controlled manner depending on how far my cursor is from where I am dragging.

Someone please correct me if I'm wrong about the setting. I did look and use the settings search.

If it's still too fast, maybe your sensitivity setting for the mouse wheele ties into this new feature? Again, someone correct me if that's not the case.

**Comment by SwiftiSwift** [comment]
> I dont think there is one. It was simply implemented to behave this way by default. I can now drag scroll in a controlled manner depending on how far my cursor is from where I am dragging.
> 
> Someone please correct me if I'm wrong about the setting. I did look and use the settings search.
> 
> If it's still too fast, maybe your sensitivity setting for the mouse wheele ties into this new feature? Again, someone correct me if that's not the case.

Looked into it and yes its that way by default now with the new update. But how can I change the sensitivity setting for the mouse wheel on mac in VSCode?

**Comment by Mausinator08** [comment]
There should be a setting for it that says just that. I use vs code on a MacBook at work and I think it's called mouse wheel scroll sensitivity. There should be one for editor, terminal, and one other I think.

**Comment by shaderein** [comment]
I don't think the problem of horizontal scrolling is fixed. When I select and drag over a line horizontally, once the cursor reaches the edge of the screen, it still jumps to the end of the line instantly. Vertical scrolling is fine on my end.
