### ISSUE TITLE
Icons in multiple-level tree view are not arranged correctly in 1.20 Insider

### ISSUE THREAD

**Issue by LazarusX** [Microsoft/vscode#42097]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (6bfe9bbe8a910b8c57bb0c0a6e0557d46ebd64ba, 2018-01-24T06:08:23.315Z)</li>
	<li>OS Version: Darwin x64 17.3.0</li>
	<li><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-account|ms-|0.3.0
azure-iot-edge|vsc|0.1.3
azure-iot-toolkit|vsc|0.5.0

</details></li>
</ul>

---

Steps to Reproduce:

1. Install an extension with multiple-level tree view such as [Azure IoT Toolkit](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit) and [Docker](https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker)
2. Expand the secondary tree.

Here is how the tree view looks like in 1.19, which is correct:
![image](https://user-images.githubusercontent.com/716650/35336754-5f0093e6-0154-11e8-9fa5-4547e16d13ba.png)

The tree items named "$edgeAgent", "$edgeHub", "filterModule", and "tempSensor" are all sub-tree items of "edgeDevice".

In 1.20.0 Insider, the icons for the secondary tree items are closer to the left than that for the first level, which is confusing:
![image](https://user-images.githubusercontent.com/716650/35336679-2209d678-0154-11e8-9dc3-6257a6a1d410.png)

Reproduces without extensions: N/A

**Comment by LazarusX** [comment]
When the secondary level tree is not expanded, here is how it looks like in 1.19:
![image](https://user-images.githubusercontent.com/716650/35369793-bc751cd4-01c4-11e8-9a01-6a242e30458e.png)

But in 1.20 Insider, icons of two first level tree items "edgedevice" and "raspberrypi" are not aligned:
![image](https://user-images.githubusercontent.com/716650/35369801-cc3153ea-01c4-11e8-8c76-0434edcf6257.png)

**Comment by LazarusX** [comment]
This issue can be temporarily worked around by selecting an icon theme other than the default "Seti" theme.
![icon-arrangement-issue](https://user-images.githubusercontent.com/716650/35374345-720d4496-01dd-11e8-9b6c-9beaf8b85a30.gif)

**Comment by sandy081** [comment]
I see the issue, thanks for reporting. Will fix it soon.

**Comment by sandy081** [comment]
Fixed it. Please try it out in tomorrows insiders.

**Comment by LazarusX** [comment]
I can verify the fix on macOS, but still reproduce the issue on Windows with the latest insiders
> Version 1.20.0-insider
Commit 757ff83f0dece1ecf43d3a92e91fe467de1cc9dc
Date 2018-01-29T05:13:39.772Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

![image](https://user-images.githubusercontent.com/716650/35545669-2da66e28-05ab-11e8-8b7c-2da17e1684be.png)

**Comment by LazarusX** [comment]
@sandy081 Any updates? I can still reproduce this issue on Windows with the 2018-02-01's Insiders version.

**Comment by sandy081** [comment]
@LazarusX Pushed some more fixes, please check with tomorrow's insiders. Thanks/

**Comment by LazarusX** [comment]
@sandy081 The issue can still be reproduced:
![image](https://user-images.githubusercontent.com/716650/35843360-9aeb377e-0b42-11e8-9a24-d5635b671e7b.png)

**Comment by sandy081** [comment]
@LazarusX May I know which theme are you using?

**Comment by LazarusX** [comment]
Both the icon theme and the color theme are default (Seti/Default+). You can check my user settings below:
![image](https://user-images.githubusercontent.com/716650/35862181-acdf50d0-0b85-11e8-9eac-0917eee46275.png)

By the way, the issue can also be reproduced on macOS.

**Comment by sandy081** [comment]
@LazarusX That's pretty bad. Fixed it.

![image](https://user-images.githubusercontent.com/10746682/35866027-5e43e820-0b56-11e8-9e22-01575f3a491b.png)

**Comment by LazarusX** [comment]
@sandy081 Thanks for the quick fix! I can verify that my secondary level items are arranged correctly now.

However, for tree views with *only* first level items with icons, when switching between different icon themes, the items can move back and forth horizontally. Is it the expected behavior? See the "Docker Images" and "IoT Hub Devices" views below:
![icon-arrangement-issue](https://user-images.githubusercontent.com/716650/35896900-86236d90-0bf9-11e8-9545-5f058ebebd15.gif)

For tree views with multiple levels, the items will not move during icon theme switching.

**Comment by sandy081** [comment]
@LazarusX Hmm.. I think it is not expected. We have similar experience in File explorer

![kapture 2018-02-07 at 10 10 20](https://user-images.githubusercontent.com/10746682/35907798-37c3beca-0bef-11e8-8b59-10ce05fffcd4.gif)

Filed a new issue for that #43084.

Marking this as verified as user did.
