### ISSUE TITLE
Korean input problem and Recognition error when creating new file

### ISSUE THREAD

**Issue by NakOh** [microsoft/vscode#42131]
- VSCode Version:  1.19.2
- OS Version: Mac 10.13.2

Steps to Reproduce:

1. Write Korean String.
2.
![2018-01-25 9 38 36](https://user-images.githubusercontent.com/7420198/35364632-89143d72-01b3-11e8-90a1-1afee3945c43.png)
Not Auto Close. Maybe Bug.

1. Make New File In Unity.
2. 
![2018-01-25 9 39 54](https://user-images.githubusercontent.com/7420198/35364653-b8b91930-01b3-11e8-9148-d44df3d53f5b.png)
This file can't read another File. 
If I restart VSCode, can read other file.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
I don't understand the issue. Can you please provide step by step instructions including the specific keys you are pressing, and also describe the expected behavior

**Comment by NakOh** [comment]
1. Korean issue
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7420198/35366558-6a92a47e-01bd-11e8-8e20-42541e7056df.gif)

**Comment by NakOh** [comment]
2. New File Issue
I have tried the test many times.
I use macbook And I am using three monitors.
There is no problem if you put the vs code and unity together in one monitor.
But If i use unity on one monitor and a VsCode on another monitor, I'll have a problem.
I do not know how to explain it.

1. Same Monitor
![same](https://user-images.githubusercontent.com/7420198/35367117-108ee3c2-01c0-11e8-9375-25bf41ede068.gif)
2. Different Monitor
![dirfferent](https://user-images.githubusercontent.com/7420198/35367121-16189fd6-01c0-11e8-999e-63d7ded1fc8c.gif)

**Comment by rebornix** [comment]
The input issue was fixed months ago when we handle auto complete/close for IME. The file open issue is a Unity issue IMO.

**Comment by NakOh** [comment]
??
![35366558-6a92a47e-01bd-11e8-8e20-42541e7056df](https://user-images.githubusercontent.com/7420198/45127686-75008c80-b1b4-11e8-87fb-9dab23f5ec48.gif)

This issue not fixed.

**Comment by rebornix** [comment]
Verified that it doesn't exist any more in latest Insiders.
