### ISSUE TITLE
[Bug] Close button (X) on Welcome tab closes active document instead

### ISSUE THREAD

**Issue by inarius** [Microsoft/vscode#42158]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (2d79f9da3ca330ad7ebeb7dc3f538a0cf1634fa3, 2018-01-18T05:14:16.814Z)</li>
	<li>OS Version: Windows_NT x64 10.0.15063</li>
	<li><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.3.0

</details></li>
</ul>

---

Steps to Reproduce:

1. Open a new VSCode window
2. Select and drag multiple files into the VSCode window to open multiple documents. One of the new 
documents will be active in the editor window.
3. In the document explorer,  scroll to the top, hover over the left-margin close (X) buttons, and click the button next to the Welcome document.
4. The active document is closed instead of Welcome. Welcome becomes the new active document.

Reproduces without extensions: Yes/No

**Comment by bpasero** [comment]
Reproduces for me.

**Comment by isidorn** [comment]
Works in latest out of source. Probably fixed via 824c7f0c24
@bpasero can you please try to repro again with latest out of source

**Comment by bpasero** [comment]
@isidorn still reproduces:

![before](https://user-images.githubusercontent.com/900690/35436566-3af9781e-028f-11e8-9a05-5a5ac13d1f20.gif)
