### ISSUE TITLE
Allow terminal.integrated.cwd to work as a folder setting

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#42165]
Currently `terminal.integrated.cwd` only work when opening the folder directly instead of in workspace.

I think it should support into mutli-root workspace.

e.g. I have a workspace with two folders:

```sh
projectA
- .vscode/settings.json
- a/b/c/d/e

projectB
- .vscode/settings.json
- x/y/z
```

I want the terminal to starts at `a/b/c/d/e` for projectA, and `x/y/z` at projectB.

Since when we open a new terminal, it asks which project to open the terminal with,
the setting should be supported.

Alternatively, we can specify it in the workspace setting:

```js
{
  "folders": [
    {
      "path": "...projectA",
      "terminal.integrated.cwd": "a/b/c/d/e"
    }
  ]
}
```

but honoring the settings.json in each folder is more idea because I don't have to specify the same thing in two different locations.

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/42661

**Comment by unional** [comment]
There are many other settings need the same treatment.

e.g., I use perforce on some of my folders but not others.
Right now the setting `perforce.editOnFileSave` can only be used at the workspace setting but not the folder setting.

This doesn't make sense and creates a lot of errors.

**Comment by unional** [comment]
It seems like this is fixed.
Tested on 1.23.1

**Comment by roblourens** [comment]
I don't think it's fixed, I can't set that setting on a folder in a multiroot workspace.

**Comment by unional** [comment]
I have that setting that the folder's `setting.json`. And seems like in multiroot workspace it is honoring that.

I might be wrong, so try it out yourself and see if it is working for you. 🌷

**Comment by Tyriar** [comment]
Back to the backlog :smile:

**Comment by krooq** [comment]
I also encountered #60393 by having only a single folder in my workspace with "terminal.integrated.cwd": "${workspaceFolder}" in settings json.
I would try to open a terminal and it would always (exit code: 2) on me.
It's a minor issue but still confusing to encounter.

Work around is to just exclude "terminal.integrated.cwd" from settings.
