### ISSUE TITLE
Integrated terminal doesn't open

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#42415]
Windows

See attach screen cast. Nothing in the log

![cast](https://user-images.githubusercontent.com/1931590/35561256-0133f540-05b0-11e8-9415-7d7a2f5c75f3.gif)

**Comment by sandy081** [comment]
This is blocking testing https://github.com/Microsoft/vscode/issues/42278

**Comment by aeschli** [comment]
I see the same

**Comment by will-l-h** [comment]
From the Developer Tools

![image](https://user-images.githubusercontent.com/14348617/35573887-52473d16-05a6-11e8-895d-b6aacbc91b0b.png)

**Comment by Tyriar** [comment]
Should be fixed in latest insiders, was caused by asar changes

**Comment by maxibanki** [comment]
@Tyriar it works, thanks!

**Comment by jtleaming** [comment]
I'm still getting this behavior with 1.20.0-insider 648c46deeeda61fad44ce188684dcb61838b724a.

**Comment by ciruz** [comment]
I just updated insiders, and it's still not working (I'm on commit: 9affae559e7b6dd46acfe2ac3123fb0ea87c6615)

**Comment by dbaeumer** [comment]
Verified under 

```
Version 1.20.0-insider
Commit 9affae559e7b6dd46acfe2ac3123fb0ea87c6615
Date 2018-02-01T05:15:24.027Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
