### ISSUE TITLE
Some messages from node extension are not translated

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#42426]
Refs: #42324
Linux

1. Start with vscode with some non enlish locale
2. Start debugging, notice the yellow message in debug console:
`Debugging with inspector protocol because Node.js v8.8.1 was detected.
node --inspect-brk=29536 bin/www `

It is not translated. I would expect it to be transalted.
Note that some other things coming from that extension are translated (like the title of the Loaded   Scripts view)

**Comment by dbaeumer** [comment]
Reason could be that I updated the debug extensions last night but and node-debug and node-debug2 hasn't been publish to the market place yet.

@weinand @roblourens can you publish a version containing the changes I did?

**Comment by isidorn** [comment]
I also found this in the developer tools

```
[Extension Host] Message Debugging with inspector protocol because Node.js {0} was detected. didn't get externalized correctly. (at Console.originalConsole.(anonymous function) [as warn] (/usr/share/code-insiders/resources/app/extensions/git/node_modules/diagnostic-channel-publishers/dist/src/console.pub.js:42:39))
```

**Comment by weinand** [comment]
@dbaeumer I've published a new version of node-debug.

**Comment by dbaeumer** [comment]
@weinand thanks!

**Comment by auchenberg** [comment]
I'm still seeing this in build form 9 hours ago on Windows (https://github.com/Microsoft/vscode/commit/8cac1acd97466afc75c663dc1626d8562a9a3f3d)

**Comment by dbaeumer** [comment]
Tracked it down. Was a problem in node-debug. @weinand assigning to you. Please close when fixed in node-debug.

**Comment by weinand** [comment]
Fixed by commit https://github.com/Microsoft/vscode-node-debug/commit/4d9a3a70fb776e05df218849a68cdfd2645d4ed0

**Comment by isidorn** [comment]
Verified by code review, since this is not yet translated by translators.
