### ISSUE TITLE
Terminal on Windows 7 does not show any text

### ISSUE THREAD

**Issue by Bendjen** [microsoft/vscode#43169]
- VSCode Version:  1.20.0
- OS Version:  win7 SP1 X64

Steps to [Reproduce:](url)

1.When I use ctrl+~ open the terminal, can't input anything in the terminal
2.And I also find when I right-click  a folder， the option [open in the terminal ]  is instead of [open in the cmd], but  my `"terminal.integrated.shell.window` has been config to  powershell.exe
3.It happened after I updated to the latest version.
4.It cannot be solved after restarting the system or vscode.
5.The powershell outside is working normally.

Does this issue occur when all extensions are disabled?: Yes
![01](https://user-images.githubusercontent.com/20695625/35957991-650bd094-0cd9-11e8-94b2-3e3e327ecab9.png)

**Comment by Shiroyan** [comment]
i also have this problem

**Comment by Tyriar** [comment]
Does it show when you toggle the terminal (ctrl+\`, ctrl+\`) or zoom in and out (ctrl++, ctrl+-)?

**Comment by Tyriar** [comment]
Also are there any errors in the devtools console (Help > Toggler Developer Tools)

**Comment by Veado** [comment]
@Tyriar  I can use these shortcuts to toggle the terminal or zoom in and out.  Devtools have no error, there are a warning:
```
Ctrl+Alt+ keybindings should not be used by default under Windows.
```

**Comment by Shiroyan** [comment]
![image](https://user-images.githubusercontent.com/26413534/36011845-248ec2da-0d95-11e8-97b2-7162faef99db.png)

I tried to specify powershell and git-bash, reinstall vscode, restart computer, ban all extensions. terminal still no response.

**Comment by physihan** [comment]
mark！

**Comment by Lenic** [comment]
mark

**Comment by physihan** [comment]
revert to last version，reinstall 1.19.2 
the terminal will show again

> 版本 1.19.2
> 提交 490ef761b76b3f3b3832eff7a588aac891e5fe80
> 日期 2018-01-10T15:55:03.538Z
> Shell 1.7.9
> 渲染器 58.0.3029.110
> Node 7.9.0
> 架构 x64

**Comment by Bendjen** [comment]
@Tyriar 
1. 'Does it show when you toggle the terminal (ctrl+`, ctrl+`) or zoom in and out (ctrl++, ctrl+-)?' 
    A:   It shows with a block where I can input nothing.
2. 'Also are there any errors in the devtools console (Help > Toggler Developer Tools)'
    A:  Yes,but i seems has no relation with terminal.
![01](https://user-images.githubusercontent.com/20695625/36132824-5cc2bd24-10b4-11e8-82b2-25734e01af40.png)

3.The problem disapperred for one day(I did nothing) . But it appear again today(I did nothing),
and I have np idea about that.

版本 1.20.0
提交 c63189deaa8e620f650cc28792b8f5f3363f2c5b
日期 2018-02-07T17:09:39.780Z
Shell 1.7.9
渲染器 58.0.3029.110
Node 7.9.0
架构 x64

**Comment by woshiguabi** [comment]
Seems like a System Permissions issue.
Find `Code.exe` in the installation path, check `run as administrator` and back to normal.

**Comment by Technoblazed** [comment]
@woshiguabi not the case for me. Even running as admin still doesn't fix it.

**Comment by Tyriar** [comment]
@bitcrazed FYI, this might be another Windows regression

**Comment by NARUTOne** [comment]
@woshiguabi   good, thank you

**Comment by davec21** [comment]
Been noticing this as well. It's weird though because the terminal will work fine for a bit and I can run node commands, ionic commands, etc. I'll minimize code or drag to a new window and terminal disappears. I can get it back by clicking the garbage can and re-opening the terminal with Ctrl+J

**Comment by bitcrazed** [comment]
This is really difficult to track down without a repro. If anyone has specific repro steps, please share.

Thanks.

**Comment by etoah** [comment]
same problem

**Comment by CherryDT** [comment]
For me this happens in the following case reproducably (on Windows):

- Open new VSCode which starts out maximized
- Open console (I'm using WSL bash as shell, in case that matters)
- Restore window (everything still fine at that point)
- Maximize window again (Shell vanished and no amount of scrolling or pressing keys will make it come back)

**Comment by Tyriar** [comment]
@davec21 @CherryDT the dragging/maximizing part makes me think you're seeing https://github.com/Microsoft/vscode/issues/42999 which is fixed in Insiders and can be worked around in the meantime by hiding and showing the terminal.

**Comment by Bendjen** [comment]
I have more information about the terminal problem,recently.

1.It often occurs when I close the vscode rough，like shutdowning my system without closing the vscode.exe or close the vscode while the terminal is working.
2.And I also found a solution: File =>Create a new window. In this case,even the old window‘s terminal still can't work normally, but new window's terminal is nomal!

@Tyriar Maybe it can help you to find the reason.

![old](https://user-images.githubusercontent.com/20695625/36708609-c644f348-1bae-11e8-9526-6ef99e9b6691.png)
![new](https://user-images.githubusercontent.com/20695625/36708610-c80e34f0-1bae-11e8-9fa9-29c24927b891.png)

**Comment by Tyriar** [comment]
Can people who are having this issue test whether it repros within insiders? There is an issue which looks very similar to this which is fixed already https://code.visualstudio.com/insiders/

**Comment by Technoblazed** [comment]
Yes, my original issue was with insiders and testing now again it's still an issue with insiders. If I enable Windows 8 compatibility mode, the terminal fails to load and just appears blank, if I disable it again, it works as intended.

**Comment by Tyriar** [comment]
@Technoblazed oh I missed the part about compatibility mode, are you running VS Code in compatibility mode 😕

**Comment by Technoblazed** [comment]
I was running it in compatibility mode so it could be detected by display capture on my OBS, but obviously I'd rather have the terminal working than my display capture ;)

**Comment by Tyriar** [comment]
I can reproduce the terminal not working in Windows 8 compatibility mode, but that also happens in v1.19 and it was mentioned that it works there https://github.com/Microsoft/vscode/issues/43169#issuecomment-364663482, I even checked 1.17 and it's the same. I wonder if it only worked when downgrading because it's a new executable that's not running in compatibility mode anymore?

If this is all related to compatibility mode and the terminal I don't really understand why there was a huge influx of reports for this issue recently, unless many people were upgrading from Windows 8 to 10 recently for some reason (compat mode is set automatically when upgrading AFAIK)? Or maybe that's just the confusion over https://github.com/Microsoft/vscode/issues/42999 which is hard for people to tell apart from this.

**Comment by Tyriar** [comment]
It looks like the reason the terminal doesn't die is because the backing shell process is actually still running:

![image](https://user-images.githubusercontent.com/2193314/36746659-b927d24a-1ba7-11e8-9a74-6f21e2f9480b.png)

**Comment by Tyriar** [comment]
Also the OP reported using Windows 7. For people who can reproduce on Insiders can you check whether you're running under compatibility mode? To check this you can right click on the executable then go to properties -> compatibility.

**Comment by Technoblazed** [comment]
Windows 10, compatibility set to 8

**Comment by Tyriar** [comment]
@Technoblazed did you upgrade recently?

There's actually a section in the FAQ I added a long time ago I just remembered 😄  https://code.visualstudio.com/docs/editor/integrated-terminal#_common-questions

**Comment by Technoblazed** [comment]
Actually, I noticed that this started becoming an issue after the latest Windows creators update a month or two ago, and as for insiders I updated yesterday I believe.

**Comment by Tyriar** [comment]
@Technoblazed interesting, but the terminal worked fine before then? The old behavior which triggered me to update the docs was that the terminal would exit and show a notification. Did you upgrade from Windows 8 at some point or was this a fresh Windows 10 install or upgrade from Windows 7?

**Comment by Tyriar** [comment]
Oh you mentioned you had compat mode for some display capture thing, did you set this manually?

**Comment by Technoblazed** [comment]
Yeah I manually enabled it months ago and it was fine, just until the recent creators update that it broke. And this was a fresh install of Win 10 Pro

**Comment by Tyriar** [comment]
@Technoblazed thanks for all the info 😃 

@bitcrazed TLDR: This is probably not the OP's issue, but it looks like the terminal no longer runs when Windows 10 is running under Windows 8 compat mode. It worked fine before FCU though.

**Comment by daix6** [comment]
@Tyriar 
I have the same issue. Insider version is the latest.

![image](https://user-images.githubusercontent.com/8535971/36898439-d2d09302-1e55-11e8-8f6f-faf613a954b0.png)


And the following is the logs when I add a new terminal:
![image](https://user-images.githubusercontent.com/8535971/36898525-2a273ebc-1e56-11e8-9c59-12c07a616095.png)

System: Windows 7
Compability Mode: off

**Comment by bboydflo** [comment]
I've had a very similar issue, but it was totally my mistake. I forgot to add bash.exe or powershell.exe in the end of the path

**Comment by lizhihua0925** [comment]
I have the same problem in win7:
![image](https://user-images.githubusercontent.com/16623135/37016071-6aab4f72-2145-11e8-946a-0e3dd696ac41.png)
but it is work fine in win10

**Comment by Bendjen** [comment]
@lizhihua0925  @daix6   Choose New Window from the File menu, it work for me,you can make a try.

**Comment by daix6** [comment]
@Bendjen Sadly not work for me

**Comment by Tyriar** [comment]
Ok I think the OP's issue is about the terminal just not working on Windows 7 https://github.com/Microsoft/vscode/issues/43169, I think the other reports are separate issues (Windows 8 compat mode not supported, maximize can hide text).

**Comment by daix6** [comment]
But it worked in Windows 7 before actually, and suddenly broke one day...

**Comment by lizhihua0925** [comment]
@Bendjen Oh, it's not work for me ( win 7, vscode 1.20.1)

**Comment by Bendjen** [comment]
I suppose Automatic Updates made this situation now,because today  I clicked 'confirm' to autoupdate vsCode to 1.21.0 during the terminal is working, and when it finished and reopened , my terminal disappearred again. The first time of the situation appearring  is the time I updated vsCode to 1.20.0, so I realize maybe it's not the version problem,it cause by the update operation probably. @Tyriar

**Comment by daix6** [comment]
The terminal surprisingly works today. And I've done nothing. No updating, no configuration...

**Comment by Tyriar** [comment]
@daix6 are you on Windows 7? 😕What version of VS Code are you on (including commit/date if you're on Insiders)?

**Comment by meichthys** [comment]
@Tyriar  I'm on windows 7 and am seeing the issue while running the following version of VSCode:

```
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
I am not running in compatibility mode, and the 'New Window' workaround doesn't work for me. Also if i 'Run as Administrator', the integrated terminal loads fine, but running as a normal user, it doesn't.

**Comment by mtpultz** [comment]
Been having the same issue for 3 months on Windows 10 #40175

**Comment by Tyriar** [comment]
@mtpultz do you have compatibility mode on?

**Comment by mtpultz** [comment]
@Tyriar I tried running VSCode with compatibility mode on and off.  Also, tried it running it as an administrator with compatibility mode on and off.

Just in case this isn't how I'm supposed to do it: 
1. Right-click VSCode icon in the taskbar 
1. Choose Properties and select the Compatibility tab
1. Un/check Compatibility mode and apply

**Comment by WackyWesley** [comment]
I'm experiencing this on Win 10 with compatibility mode off for Code.

**Comment by daix6** [comment]
@Tyriar yes, i'm on windows 7. I updated the vs code to 1.21.1 after my terminal works.

**Comment by Tyriar** [comment]
@WackyWesley you should create a new issue to discuss there

**Comment by meichthys** [comment]
So to try to summarize...
**Issue:** Blank integrated terminal

**Issue Details**
- Issue is seen across Windows versions (7,8,10).
- Issue is seen across code versions (1.21.0, 1.21.1).
- Issue is seen even when all extensions are disabled.
- Issue does not seem to provide helpful console logs (#40175)

**Some Workarounds that have been reported with mixed success rates:**
- Issue can _sometimes_ be fixed by turning off compatibility mode. (@Technoblazed)
- Issue can _sometimes_ be fixed by upgrading to v1.21.1 (@daix6)
- Issue can _sometimes_ be fixed by opening a new code window via File menu (@Bendjen)
- Issue can _sometimes_ be fixed by running code as administrator (@woshiguabi)

**Comment by Tyriar** [comment]
@meichthys I think we've narrowed the OP's issue here to Windows 7 (https://github.com/Microsoft/vscode/issues/43169#issuecomment-370925501), so let's track that specifically here. Anything on Windows 8 or 10 should be in a different issue.

**Comment by meichthys** [comment]
@Tyriar  Installing an older version has fixed the issue for me.
I installed: https://code.visualstudio.com/updates/v1_20
I'll plan on running this version until the issue is resolved.

**Comment by Tyriar** [comment]
I just got a Windows 7 VM up and running and both cmd and powershell work fine in 1.20.1, 1.21.1 and 1.22.0-insiders.

I wonder if it's related to Windows Defender somehow? We've run into issues in the past with Windows Defender slowing things down but perhaps it's quarantining critical files? I'll update my VM and defender and do a scan and see if that finds anything. If anyone who is seeing the issue could check Defender that would be helpful.

**Comment by meichthys** [comment]
@Tyriar Hmm. interesting. I have windows defender disabled. When i get a chance, I'll try re-updating to 1.21.1 to see if i still have the issue.

**Comment by Tyriar** [comment]
@meichthys do you have any other anti-virus or similar software that could be doing something similar?

**Comment by meichthys** [comment]
I do. I've tried disabling the antivirus while updating/installing/running with no luck.
I also just tried using the built-in updater to update to the latest version, and I'm seeing the same issue again (Running as admin works though).

**Comment by Tyriar** [comment]
@meichthys could you check the user permissions of this file?

`C:\Program Files\Microsoft VS Code\resources\app\node_modules\node-pty\build\Release\winpty-agent.exe`

This is what mine looks like:

<img width="420" alt="screen shot 2018-03-27 at 11 24 35 am" src="https://user-images.githubusercontent.com/2193314/37986847-7812ae22-31b1-11e8-8398-053332e5d9cb.png">

**Comment by meichthys** [comment]
@Tyriar my permissions look identical to yours, but my path to that file is slightly different:
C:\Program Files\Microsoft VS Code\resources\app\ **node_modules.asar.unpacked** \node-pty\build\Release

**Comment by Tyriar** [comment]
@meichthys ah that's because I had v1.20.1 installed at the time, mine has that path if I move to 1.21.1

**Comment by Tyriar** [comment]
@meichthys something else you can try:

1. Install VS Code Insiders (if not already)
2. Close all Insiders windows
3. Open cmd.exe
4. Run code-insiders --log trace
5. Open the terminal
6. Open the command palette (F1) and run the "Developer: Open Log File..." command
7. Paste in what you see

Here's mine:

```
[2018-03-27 11:45:14.190] [renderer1] [trace] openWorkbench configuration {"_":[],"help":false,"h":false,"version":false,"v":false,"wait":false,"w":false,"diff":false,"d":false,"add":false,"a":false,"goto":false,"g":false,"new-window":false,"n":false,"unity-launch":false,"reuse-window":false,"r":false,"open-url":false,"performance":false,"p":false,"prof-startup":false,"verbose":false,"logExtensionHostCommunication":false,"disable-extensions":false,"disableExtensions":false,"list-extensions":false,"show-versions":false,"nolazy":false,"issue":false,"skip-getting-started":false,"skip-release-notes":false,"sticky-quickopen":false,"disable-restore-windows":false,"disable-telemetry":false,"disable-updates":false,"disable-crash-reporter":false,"skip-add-to-recently-opened":false,"status":false,"s":false,"file-write":false,"file-chmod":false,"log":"trace","appRoot":"c:\\Program Files\\Microsoft VS Code Insiders\\resources\\app","machineId":"9aec06d7ba7c54a98ecbfa544862e4058bea4c014088f181619dcb42349a904c","execPath":"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe","userEnv":{"VSCODE_IPC_HOOK":"\\\\.\\pipe\\491ddf78bc8e277b81b63c379151c48e-1.22.0-insider-main-sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{}}","VSCODE_LOGS":"C:\\Users\\daimms\\AppData\\Roaming\\Code - Insiders\\logs\\20180327T114513"},"isInitialStartup":true,"filesToOpen":[],"filesToCreate":[],"filesToDiff":[],"nodeCachedDataDir":"C:\\Users\\daimms\\AppData\\Roaming\\Code - Insiders\\CachedData\\d656cdac7d61c16330520420e57a103697dde16d","backupPath":"C:\\Users\\daimms\\AppData\\Roaming\\Code - Insiders\\Backups\\1522176226069","windowId":1,"logLevel":0,"fullscreen":false,"highContrast":false,"accessibilitySupport":false,"baseTheme":"vs-dark","backgroundColor":"#1e1e1e","perfEntries":["mark","main:started",1522176313090,0,"mark","main:appReady",1522176313122,0,"mark","main:loadWindow",1522176313324,0],"perfStartTime":1522176313090,"perfWindowLoadTime":1522176313324}
[2018-03-27 11:45:14.206] [renderer1] [trace] lifecycle: starting up (startup kind: 1)
[2018-03-27 11:45:14.226] [renderer1] [trace] lifecycle: phase changed (value: 2)
[2018-03-27 11:45:14.424] [renderer1] [trace] lifecycle: phase changed (value: 3)
[2018-03-27 11:45:17.435] [renderer1] [trace] lifecycle: phase changed (value: 4)
[2018-03-27 11:45:17.953] [renderer1] [trace] terminalInstance#ctor (id: 1) {}
[2018-03-27 11:45:18.362] [renderer1] [debug] Terminal process ready (id: 1, processId: 3124)
[2018-03-27 11:45:20.077] [renderer1] [trace] terminalInstance#dispose (id: 1)
[2018-03-27 11:45:20.814] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands
[2018-03-27 11:45:21.644] [renderer1] [trace] CommandService#executeCommand workbench.action.openLogFile
```

**Comment by Tyriar** [comment]
@sbatten managed to repro the mysterious lone cursor terminal on Windows 10 but it was flaky. One thing to note is that terminal process ready event never happened for him:

```
[2018-03-27 11:45:18.362] [renderer1] [debug] Terminal process ready (id: 1, processId: 3124)
```

Also switching to powershell seemed to fix the issue and then back to cmd it was fixed.

The original repro happened after enabling narrator.

**Comment by meichthys** [comment]
@Tyriar  here's my log trace. It looks very similar to yours...
```
[2018-03-27 15:20:46.530] [renderer1] [trace] openWorkbench configuration {"_":[],"help":false,"h":false,"version":false,"v":false,"wait":false,"w":false,"diff":false,"d":false,"add":false,"a":false,"goto":false,"g":false,"new-window":false,"n":false,"unity-launch":false,"reuse-window":false,"r":false,"open-url":false,"performance":false,"p":false,"prof-startup":false,"verbose":false,"logExtensionHostCommunication":false,"disable-extensions":false,"disableExtensions":false,"list-extensions":false,"show-versions":false,"nolazy":false,"issue":false,"skip-getting-started":false,"skip-release-notes":false,"sticky-quickopen":false,"disable-restore-windows":false,"disable-telemetry":false,"disable-updates":false,"disable-crash-reporter":false,"skip-add-to-recently-opened":false,"status":false,"s":false,"file-write":false,"file-chmod":false,"log":"trace","appRoot":"c:\\Program Files\\Microsoft VS Code Insiders\\resources\\app","machineId":"a0565eec5b67a97b961964ecf9bfbd91fe2662ed245ce10ed56b250a48bad3df","execPath":"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe","userEnv":{"VSCODE_IPC_HOOK":"\\\\.\\pipe\\2f533cd3561e694c39f3bd3ae67904d8-1.22.0-insider-main-sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{}}","VSCODE_LOGS":"C:\\Users\\restore\\AppData\\Roaming\\Code - Insiders\\logs\\20180327T152045"},"isInitialStartup":true,"filesToOpen":[],"filesToCreate":[],"filesToDiff":[],"nodeCachedDataDir":"C:\\Users\\restore\\AppData\\Roaming\\Code - Insiders\\CachedData\\d656cdac7d61c16330520420e57a103697dde16d","backupPath":"C:\\Users\\restore\\AppData\\Roaming\\Code - Insiders\\Backups\\1522177986943","windowId":1,"logLevel":0,"fullscreen":false,"highContrast":false,"accessibilitySupport":false,"baseTheme":"vs-dark","backgroundColor":"#1e1e1e","perfEntries":["mark","main:started",1522178445038,0,"mark","main:appReady",1522178445059,0,"mark","main:loadWindow",1522178445235,0],"perfStartTime":1522178445038,"perfWindowLoadTime":1522178445236}
[2018-03-27 15:20:46.539] [renderer1] [trace] lifecycle: starting up (startup kind: 1)
[2018-03-27 15:20:46.555] [renderer1] [trace] lifecycle: phase changed (value: 2)
[2018-03-27 15:20:46.691] [renderer1] [trace] lifecycle: phase changed (value: 3)
[2018-03-27 15:20:48.020] [renderer1] [trace] CommandService#executeCommand setContext
[2018-03-27 15:20:49.702] [renderer1] [trace] lifecycle: phase changed (value: 4)
[2018-03-27 15:20:52.301] [renderer1] [trace] CommandService#executeCommand workbench.action.terminal.toggleTerminal
[2018-03-27 15:20:52.303] [renderer1] [trace] terminalInstance#ctor (id: 1) {}
[2018-03-27 15:20:52.671] [renderer1] [debug] Terminal process ready (id: 1, processId: 2544)
[2018-03-27 15:21:02.134] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands
[2018-03-27 15:21:09.985] [renderer1] [trace] CommandService#executeCommand workbench.action.openLogFile```

**Comment by Tyriar** [comment]
@meichthys great, I see terminal process ready didn't happen. I might try to squeeze in some additional logging in this upcoming version to help diagnose.

**Comment by meichthys** [comment]
Sounds good. Let me know if you’d like me to run any other tests/logs.

**Comment by Tyriar** [comment]
@meichthys I just added a few more logs, if you could do the same log test in the new build tomorrow that would be great 😃

**Comment by meichthys** [comment]
@Tyriar Thanks. Will do.

**Comment by Tyriar** [comment]
@meichthys the latest build should have the additional logging in place

**Comment by meichthys** [comment]
I don't think there was much else of interest, but here it is anyway:

```

[2018-03-29 15:13:43.255] [renderer1] [trace] openWorkbench configuration {"_":[],"help":false,"h":false,"version":false,"v":false,"wait":false,"w":false,"diff":false,"d":false,"add":false,"a":false,"goto":false,"g":false,"new-window":false,"n":false,"unity-launch":false,"reuse-window":false,"r":false,"open-url":false,"performance":false,"p":false,"prof-startup":false,"verbose":false,"logExtensionHostCommunication":false,"disable-extensions":false,"disableExtensions":false,"list-extensions":false,"show-versions":false,"nolazy":false,"issue":false,"skip-getting-started":false,"skip-release-notes":false,"sticky-quickopen":false,"disable-restore-windows":false,"disable-telemetry":false,"disable-updates":false,"disable-crash-reporter":false,"skip-add-to-recently-opened":false,"status":false,"s":false,"file-write":false,"file-chmod":false,"log":"trace","appRoot":"c:\\Program Files\\Microsoft VS Code Insiders\\resources\\app","machineId":"a0565eec5b67a97b961964ecf9bfbd91fe2662ed245ce10ed56b250a48bad3df","execPath":"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe","userEnv":{"VSCODE_IPC_HOOK":"\\\\.\\pipe\\9e6e98061bb7eefb77a4c8ef5424b2a1-1.22.0-insider-main-sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{}}","VSCODE_LOGS":"C:\\Users\\mgieger\\AppData\\Roaming\\Code - Insiders\\logs\\20180329T151341"},"isInitialStartup":true,"filesToOpen":[],"filesToCreate":[],"filesToDiff":[],"nodeCachedDataDir":"C:\\Users\\mgieger\\AppData\\Roaming\\Code - Insiders\\CachedData\\952b2a641da89a6c7bc28387474bc8afd47f0d2f","backupPath":"C:\\Users\\mgieger\\AppData\\Roaming\\Code - Insiders\\Backups\\1522177998428","windowId":1,"logLevel":0,"fullscreen":false,"highContrast":false,"accessibilitySupport":false,"baseTheme":"vs-dark","backgroundColor":"#1e1e1e","perfEntries":["mark","main:started",1522350821667,0,"mark","main:appReady",1522350821698,0,"mark","main:loadWindow",1522350821932,0],"perfStartTime":1522350821667,"perfWindowLoadTime":1522350821932}
[2018-03-29 15:13:43.276] [renderer1] [trace] lifecycle: starting up (startup kind: 1)
[2018-03-29 15:13:43.293] [renderer1] [trace] lifecycle: phase changed (value: 2)
[2018-03-29 15:13:43.434] [renderer1] [trace] lifecycle: phase changed (value: 3)
[2018-03-29 15:13:43.517] [renderer1] [trace] terminalInstance#ctor (id: 1) {}
---env oject omitted---
[2018-03-29 15:13:45.068] [renderer1] [trace] CommandService#executeCommand setContext
[2018-03-29 15:13:46.476] [renderer1] [trace] lifecycle: phase changed (value: 4)
[2018-03-29 15:13:53.609] [renderer1] [trace] CommandService#executeCommand workbench.action.showCommands

```

**Comment by Tyriar** [comment]
@meichthys interesting, this is telling me that the process starts but doesn't send any messages or exit, it's just sitting there. Could you try look at the process tree by running `code-insiders --status` and paste that in? The table with this header is what I'm after:

```
CPU %   Mem MB     PID  Process
```

Also can you get the table when you open multiple terminals as well?

**Comment by meichthys** [comment]
here's what i get when running the status command:
```
Collecting CPU and memory information. This might take a couple of seconds.
[main 3:39:47 PM] Error: Get-WmiObject : Invalid class "Win32_Process"
At C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\base\node\ps-win.ps1:114 char:19
+ foreach ($item in Get-WmiObject Win32_Process -Filter "name = '$ProcessName'") {
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCom
   mand

Get-WmiObject : Invalid class "Win32_Process"
At C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\base\node\ps-win.ps1:117 char:19
+ foreach ($item in Get-WmiObject Win32_Process -Filter "name = 'codeHelper.exe'") ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCom
   mand

Get-WmiObject : Invalid class "Win32_Process"
At C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\base\node\ps-win.ps1:121 char:19
+ foreach ($item in Get-WmiObject Win32_Process -Filter "name Like '%'") {
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCom
   mand


    at ChildProcess.<anonymous> (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main
\main.js:157:375)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by Tyriar** [comment]
@meichthys 😕 that looks like a bug, created https://github.com/Microsoft/vscode/issues/46963 to follow that up. Instead of `--status` then, could you try getting and pasting in the process tree under VS Code using [ProcessExplorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)?

**Comment by Tyriar** [comment]
@meichthys perfect! Thanks for sticking with me 😄 

The `--type=terminal` process is meant to always have children (conhost.exe, winpty-agent.exe and cmd.exe/powershell.exe/etc). My current theory is something is failing when launching the winpty agent process such that it never fires its [exit event](https://github.com/Microsoft/vscode/blob/b7721220b0ad94daaa39f726402999b286d5cdf7/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L74). And then the reason that the `--type=terminal` process never shuts down is because we set up [intervals](https://github.com/Microsoft/vscode/blob/b7721220b0ad94daaa39f726402999b286d5cdf7/src/vs/workbench/parts/terminal/node/terminalProcess.ts#L134-L152) which keep the node process alive.

Looking into it more now.

**Comment by meichthys** [comment]
I'm not sure if this helps:
![image](https://user-images.githubusercontent.com/10717998/38111726-c98312e8-336d-11e8-8e08-9d9e11727224.png)

**Comment by Riconec** [comment]
Seems to be that I fixed terminal for myself. I had user settings file with redefinition of terminal type (cmd to bash):
`"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",`

But I found that after update this settings key have different name in default settings:
`"terminal.external.windowsExec": "C:\\windows\\System32\\cmd.exe",`

So I changed user settings accordingly and problem has gone:
`"terminal.external.windowsExec": "C:\\Program Files\\Git\\bin\\bash.exe"`

**Comment by meichthys** [comment]
@Riconec  Thanks for the suggestion, but both the ```terminal.integrated.shell.windows``` and the ```terminal.external.windowsExec``` settings exist in v1.21.1. Maybe @Tyriar  could help clarify the difference between the two settings. For me, both of those settings have the same path: ```"C:\\Windows\\System32\\cmd.exe"```

**Comment by Tyriar** [comment]
@Riconec @meichthys those are two different settings and the comments in the settings should explain the difference. `terminal.external.windowsExec` existed before the integrated terminal, it will launch an external terminal (ctrl/cmd+shift+c), `terminal.integrated.shell.windows` points at a *shell* which will run inside the integrated terminal.

**Comment by Riconec** [comment]
@meichthys @Tyriar But setting these both keys solved the problem in integrated terminal, not the external

**Comment by meichthys** [comment]
@Riconec  It seems like your issue must have been slightly different. I've tried setting both of the mentioned settings explicitly in my user settings to no avail.

**Comment by KevC2** [comment]
I tried all of the suggestions in this post and I still just get the Square white Box in the terminal (like he cursor is in insert mode).

**Comment by KevC2** [comment]
Thanks, was hopeful. I back leveled but no go, still does not work. BTW, I am on Windows 10.  Works fine for all my co-workers, just not lucky me.

Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by KevC2** [comment]
I clicked on Help-Toggle Developer Tools, selected Consonel, then opened a new terminal. I see these messages:
C:\Program Files\Microsoft VS Code\resources\app\node_modules\vscode-xterm\lib\Terminal.js:1482 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
C:\Program Files\Microsoft VS Code\resources\app\node_modules\vscode-xterm\lib\Terminal.js:1482 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
C:\Program Files\Microsoft VS Code\resources\app\node_modules\vscode-xterm\lib\Terminal.js:1482 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by KevC2** [comment]
For what it's worth, I see this when I startup VS. I saw something about disabling extensions, so not sure if it's related.
marketplace.visualstudio.com/_apis/public/gallery/extensionquery Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by benorosz** [comment]
I'm having the same issue and have since January. I've tried all the suggestions here and in similar issues but nothing has worked. Currently running 1.22.2 in Windows 10, but I've been having the problem since 1.19.

**Comment by meichthys** [comment]
This issue seems to be fixed _for me_ in 1.23.1
One thing i did before updating was change my default shell to Powershell, so I'm not sure if that had anything to do with the issue being resolved on my VSCode installation.

**Comment by Tyriar** [comment]
If anyone is on Insiders and still experiencing this issue could you add this to your settings file, reload and see if that fixes it?

```
"terminal.integrated.rendererType": "dom"
```

**Comment by TamTV1** [comment]
Have same issue at vs code 1.23.1 - Window 10

**Comment by lizhihua0925** [comment]
Oh, I am looking forward to vs code 1.24

**Comment by mrwilford** [comment]
For me (Code v1.24.1 + Win7), the cause of my non-interactive terminal is definitely compatibility mode.  Repro is 100%.

As background, I want compatibility mode enabled per the recommendation in [#15211](https://github.com/Microsoft/vscode/issues/15211) so that the GPU is always disabled without having to use `--disable-gpu` which would get squashed every time a new version of Code updates my shortcuts.  For now, I'll modify my shortcuts.

And the reason I require the GPU disabled is to avoid screen flickering and frequent Nvidia driver restarts, similar to other reports I've seen across OS's, such as [#25934](https://github.com/Microsoft/vscode/issues/25934), [#41513](https://github.com/Microsoft/vscode/issues/41513), [#41238](https://github.com/Microsoft/vscode/issues/41238), [#38067](https://github.com/Microsoft/vscode/issues/38067), and [#21556](https://github.com/Microsoft/vscode/issues/21556).

**Comment by anggaaryas** [comment]
Me Win 10 April Update:
 
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64


My VSCode is fine. But i can produce error like that:
1. Using App Better Start menu
2. Create shortcut via open App using Better Start menu
3. Open VSCode via Better Start menu
4. The integrated terminal does not shows...

but, when you open the VSCode normally, it works fine. Maybe it helps... :)

**Comment by sergeylaptev** [comment]
As a temporary solution you can split terminal into 2 or more windows.
![image](https://user-images.githubusercontent.com/5740795/42124685-3188b05a-7c70-11e8-981d-ccad09e9915b.png)
![image](https://user-images.githubusercontent.com/5740795/42124699-8bc79982-7c70-11e8-965d-7c2a63802777.png)

**Comment by Tyriar** [comment]
@sergeylaptev hmm. If splitting fixes it, I would also expect resizing the panel/window to fix it too.

**Comment by drifter1007** [comment]
Hey guys i solved mine . 
After changing the graphic card settings in Nvidia Control Panel.
I changed the Laptop display to Geforce rather than Intel Hd Graphic.
May this help someone/\

**Comment by benorosz** [comment]
I didn't fix the problem, but I got around it. For me, neither bash nor Powershell worked, but cmd did. So in my settings.json, I added
`"terminal.integrated.shellArgs.windows": [
        "/K",
        "path/to/bash.exe"
    ]`
Now, every time I start up a terminal instance, it will open as cmd then run bash and be usable as bash from then on. It does take it a second to startup, but part of that may be that I had to make a batch script that just runs bash because I couldn't get it to execute bash directly because there's a space in the path to the executable and no amount of quotes and escapes would make it work the right way.

**Comment by LloygGarmadon** [comment]
It didn't work for me at first, but I looked at the file path, and I realized I was using the wrong file path. The "Git" folder was inside "Program Files (x86)", but my file path was for "Program Files". Hope that helped! (By the way, I use Windows, so for any other operating system, it's going to be different.)

**Comment by etoah** [comment]
Have same issue at vs code 1.25.1 - Window 7 

`terminal.integrated.rendererType` set auto , dom, canvas restart  not work.

**Comment by klaudiuszko** [comment]
To solve this problem, just turn off compatibility mode when you are in settings of this file after right mouse click.

**Comment by poshcodebear** [comment]
I don't know if this is helpful or not, but I notice this mostly when I RDP to my box; almost every time I do, the terminal goes blank (still accepts input, and a small handful of characters still show, though they wouldn't be normal characters people would usually see at a prompt).  Ctrl + +, Ctrl + - corrects it for me, but if I leave it, sometimes when I log in locally it will self correct and other times it won't.

I can't seem to replicate it by messing with my color, theme, or resolution settings, unfortunately.

**Comment by AmrutaCh** [comment]
Hi,
I am using msys bash environment with vs code and it was working perfectly till the vs code updated today. 

Issue:
workspace configured before vs code update works as expected but the same settings no longer work if new workspace is created now. The bash terminal doesn't show up in integrated terminal


workspace setting:

```
{
    {
        "workbench.statusBar.visible": true,
        "workbench.activityBar.visible": true,
        "editor.minimap.enabled": false,
        "terminal.integrated.shell.windows": "D:/Workspace/ESP32/toolchain/v3.1/msys32/usr/bin/bash.exe",
        "terminal.integrated.shellArgs.windows": [
            "--login",
        ],
        "terminal.integrated.env.windows": {
            "CHERE_INVOKING": "1",
            "MSYSTEM": "MINGW32",
        },
        "C_Cpp.errorSquiggles": "Disabled",
    }
}
```

vs  code version:

> Version: 1.29.1 (system setup)
> Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
> Date: 2018-11-15T19:13:36.375Z
> Electron: 2.0.12
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64


Any suggestions on how to fix it?

**Comment by Zerg00s** [comment]
Updated VS code today and the terminal stopped working. Cannot type anything.

**Comment by Jonny-china** [comment]
Have same issue at vs code 1.29.1 - Window 10

**Comment by AmrutaCh** [comment]
Anyone got this terminal issue resolved? ☹️

**Comment by ibbgomes** [comment]
I also have this issue with VS Code 1.29.1 on Windows 10. The above fixes didn't work.

**Comment by Tyriar** [comment]
@ibbgomes https://github.com/Microsoft/vscode/issues/57803

**Comment by balexandre** [comment]
I had the exact same issue, more weird is that I could simply press <kbd>ENTER</kbd> in the emptyness and the powershell command line would simply shown.

**What I have tried** and succeed (maybe can help someone):

Digging a bit I've found out that the original `terminal.integrated.shell.windows` had the wrong path (was pointing to `C:\WINDOWS\Sysnative\WindowsPowerShell\v1.0\powershell.exe` and that no longer exists, for some reason).

checking the right path for PowerShell I've updated both user and workspace settings to `C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe`

![](https://i.stack.imgur.com/RIm2H.png)

changing to `bash` as the [docs mentions](https://code.visualstudio.com/docs/editor/integrated-terminal#_windows) I also started to have the terminal in good health:

![](https://i.stack.imgur.com/u5bg8.png)

**Comment by Tyriar** [comment]
@balexandre that's #57803 on Windows 10 1809, not Windows 7.

**Comment by MadeByMike** [comment]
I have this issues as well. I'm using windows and bash\ubuntu WSL for my shell. It's sporadic but happens about 20-30% of the time when I open a terminal. Usually closing the terminal (trash icon) and starting a new one (plus icon) will give me a working terminal.

**Comment by valse** [comment]
Same issue here; this is my version:

Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

the terminal (powershell) is blank and the search recent `Ctrl+r` command stopped working (the console show `^R` instead 👎)

**Comment by rps-v** [comment]
Had the same issue. What fixed it for me was enabling **Windows Enable Conpty** in settings.

![image](https://user-images.githubusercontent.com/26383032/50815048-68d43980-1324-11e9-92ce-124e2f928ed3.png)

Version: 1.31.0-insider (system setup)
Commit: f599942a5f1ce23445eb1dd7e0ff799ab7a0a175
Date: 2019-01-08T06:19:45.505Z
Electron: 3.0.13
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by Tyriar** [comment]
Please stop commenting here if you're on Windows 10, you're seeing a bug in Windows that is fixed in the next version #57803.

**Comment by poshcodebear** [comment]
@Tyriar, are you positive that's the same issue?  Based on the description, that's different than the behavior I've seen on Windows 10, and I've not installed 1809 on any of my machines yet.

**Comment by flarpblart** [comment]
Add this to your settings.json

    "terminal.integrated.shellArgs.windows": ["-NoLogo"]

**Comment by dougal83** [comment]
Wonder if this is related to to the issue.  I recently started experiencing an empty terminal on win 10, while pressing enter reveals the prompt.  I've noticed that there is a vertical scroll bar.  If I make the terminal window large/tall enough(half my screen) then a new terminal shows the prompts as expected without a scroll bar.  Not a show stopper, wondering if the experience is similar/repeatable for anyone here.

**Comment by Tyriar** [comment]
@dougal83 it's a Windows 10 bug: https://github.com/Microsoft/vscode/issues/57803, press enter once or twice to see your prompt

**Comment by Redfish52** [comment]
I have the same problem. My VS Code: 1.30.2 (user setup).

> 
> 
> Please stop commenting here if you're on Windows 10, you're seeing a bug in Windows that is fixed in the next version #57803.

How long to wait this next version?

**Comment by Jexn** [comment]
> Please stop commenting here if you're on Windows 10, you're seeing a bug in Windows that is fixed in the next version #57803.

版本: 1.31.0 (system setup)
提交: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
日期: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

this version not fix

**Comment by yw662** [comment]
I am on windows 1809 17763.316 The bug is still here.

Will review versions solve this ?

**Comment by leslieeilsel** [comment]
I think I found a temporary solution!
Step1: Open CMD terminal, edit properties, check this option
![](https://s2.ax1x.com/2019/04/17/Axovy8.png)
Step2: Restart the system

#### Before：
![](https://s2.ax1x.com/2019/04/17/AxoXSP.png)
#### After：
![](https://s2.ax1x.com/2019/04/17/AxojQf.png)

**Comment by devsetgo** [comment]
@yw662 I am on v 1809 17763.437 and I have the problem. Both on CMD and Bash (ubuntu 18.04 WSL).

@leslieeilsel - I tried your suggestion and it cause the cmd prompt to crash (Bash is my default).

**Comment by leslieeilsel** [comment]
@devsetgo It seems that this is not a universal solution, let us wait for the official fix.

**Comment by tyrfing666** [comment]
Also check the terminal.integrated.cwd setting.

I moved computers (from Windows 7 to Windows 10, drives C: and D: to only C:) and terminal stopped working. At first it would exit with code 2, then when I updated today, it would start and freeze with just a white square.

It turns out that my terminal.integrated.cwd setting was set to a folder on D drive, which no longer existed. Changing to to a folder that does exist fixed Terminal.

**Comment by hugomaia** [comment]
> I think I found a temporary solution!
> Step1: Open CMD terminal, edit properties, check this option
> ![](https://camo.githubusercontent.com/9cd1bf0f5201fb6f8e5dbb11de32f7096bdb54ae/68747470733a2f2f73322e617831782e636f6d2f323031392f30342f31372f41786f7679382e706e67)
> Step2: Restart the system
> 
> #### Before：
> ![](https://camo.githubusercontent.com/2eaca5c39925c03cedfda3fd52ddbe64ca69aad8/68747470733a2f2f73322e617831782e636f6d2f323031392f30342f31372f41786f5853502e706e67)
> 
> #### After：
> ![](https://camo.githubusercontent.com/564cb9f808ea413d2b66aea032f9e9d41e6cbb0d/68747470733a2f2f73322e617831782e636f6d2f323031392f30342f31372f41786f6a51662e706e67)
> 
> #### System Info
> Windows 10 1809
> 
> #### VSCode Info
> Version: 1.33.1 (user setup)
> Commit: [51b0b28](https://github.com/microsoft/vscode/commit/51b0b28134d51361cf996d2f0a1c698247aeabd8)
> Date: 2019-04-11T08:27:14.102Z
> Electron: 3.1.6
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

Thanks! This really works! 
Below the same window in portuguese:
![image](https://user-images.githubusercontent.com/23406580/60689461-081d5800-9e94-11e9-8995-40e4ff792549.png)

**Comment by SunilSimha** [comment]
Hey! I have the same issue but on Linux (Ubuntu 18.04). Every time I wake the computer from sleep, the integrated terminal stops showing text or shows broken text.

**Comment by cikent** [comment]
> @woshiguabi not the case for me. Even running as admin still doesn't fix it. (On insiders anyway)
> 
> Okay so, disabling compatibility mode seems to fix it, regardless of if `run is administrator` is enabled or not.

@Technoblazed This worked for me, thank you!

@Tyriar, thank you for marking my ticket as duplicate so I could find this thread and devise a Workaround until this is fixed.

**Comment by MaybeMeet** [comment]
ok, I see you are all in windows system. And I have the same question in ubuntu16.04. And when I meet the problem, it can be recovered after reboot the vscode. But it will appear some times. It is so terrible. Anyone know how to solve it, please tell me. thanks a lot.

**Comment by cikent** [comment]
> ok, I see you are all in windows system. And I have the same question in ubuntu16.04. And when I meet the problem, it can be recovered after reboot the vscode. But it will appear some times later. It is so terrible. Anyone know how to solve it, please tell me. thanks a lot.

^ see if you can access the Properties for Visual Studio Code -> then search through those settings looking for Compatibility options -> Ensure that Visual Studio Code can run as an Administrator, but everything else should be toggled/turn-ed Off.

See if that helps.

**Comment by Tyriar** [comment]
There are no plans to invest further in Windows 7 support and the backend that we use for it (winpty), looking forward from Windows 10 1903 we use conpty which is a terminal backend provided by the same team that builds Windows Terminal so we can action such requests much easier.

If you're on WIndows 10 and having issues you're probably seeing #73790 and should uncheck use legacy console in conhost's properties.
