### ISSUE TITLE
There's no possibility to reorder the folders of a workspace by moving them or re-arranging by drag and drop  in the sidebar

### ISSUE THREAD

**Issue by ramkirat** [Microsoft/vscode#44001]
**Re-arranging folders order is not available in explorer panel**
- VSCode Version: 1.20.1
- OS Version: window 10

**Comment by bpasero** [comment]
We fixed that recently and its available in insiders. You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ramkirat** [comment]
installed vscode insider but not fixed.. same problem, 
**re-arranging project folder**by  drag and drop  **inside workspace** folder not wokring...
VSCode Version: 1.21.0 insider
OS Version window 10

**Comment by isidorn** [comment]
@ramkirat try the insiders tomorrow please

**Comment by ramkirat** [comment]
@isidorn i tested  but not fixed...
please see this gif image.,
![vscode-rearrangefolder](https://user-images.githubusercontent.com/22697352/36487326-9e79feec-1746-11e8-86cc-685f25205a7f.gif)

**Comment by bpasero** [comment]
Yeah that case should probably be supported...

**Comment by isidorn** [comment]
@ramkirat thanks for the report. I have pushed a fix and it will be in tomorrow's insider
