### ISSUE TITLE
Terminal: scrollbar is back to the top of terminal

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#45134]
Version 1.21.0-insider
Commit b76a4a71434d6cdee69fa1d8bdc7533d09598d53
Date 2018-03-02T13:48:32.486Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. open integrated terminal and have it display enough text for the scrollbar to appear
2. switch to another panel, like `problems`
3. switch back to the terminal panel: the scroll position is the same, but the scrollbar has been moved to the top, so any attempt to scroll using trackpad/mousewheel will scroll from the top of the screen instead of current (visible) position.

Does this issue occur when all extensions are disabled?: Yes

![terminalscroll](https://user-images.githubusercontent.com/199648/37030681-23cdcd22-213c-11e8-957e-9968379e55d6.gif)

**Comment by Tyriar** [comment]
@warpdesign could you test on latest insiders I think I fixed this one recently.

**Comment by nico-onmap** [comment]
@Tyriar The bug is still present in the lastest insider build:

> Version 1.21.0-insider
Commit a903bd38fbe9006c076d218ff69fe1ee0160f815
Date 2018-03-06T11:09:37.589Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by LAITONEN** [comment]
I have the same problem when toggling the Terminal.

**Comment by Tyriar** [comment]
@LAITONEN this is fixed in Insiders and will land in stable in v1.22.0
