### ISSUE TITLE
Can't run vscode after compiling from source

### ISSUE THREAD

**Issue by jlippuner** [Microsoft/vscode#45714]
- VSCode Version: master
- OS Version: Debian testing

Since the font looks horrible with the binary release, I'm trying to following this comment https://github.com/Microsoft/vscode/issues/35675#issuecomment-365076104 and compile vscode with a different version of Electron.

I follow the instructions at https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source and everything seems to work ok. But when I then run `./scripts/code.sh`, I get

```
[17:31:30] Using gulpfile ~/progs/vscode/gulpfile.js
[17:31:30] Starting 'clean-electron'...
[17:31:30] Finished 'clean-electron' after 4.62 ms
[17:31:30] Starting 'electron'...
_http_client.js:127
      throw new TypeError('Request path contains unescaped characters');
      ^

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at TunnelingAgent.request (http.js:38:10)
    at TunnelingAgent.createSocket (/home/jlippuner/progs/vscode/node_modules/github-releases/node_modules/tunnel-agent/index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/home/jlippuner/progs/vscode/node_modules/github-releases/node_modules/tunnel-agent/index.js:184:41)
    at TunnelingAgent.addRequest (/home/jlippuner/progs/vscode/node_modules/github-releases/node_modules/tunnel-agent/index.js:80:8)
    at new ClientRequest (_http_client.js:258:16)
    at Object.request (http.js:38:10)
    at Object.request (https.js:239:15)
    at Request.start (/home/jlippuner/progs/vscode/node_modules/github-releases/node_modules/request/request.js:584:30)
    at Request.end (/home/jlippuner/progs/vscode/node_modules/github-releases/node_modules/request/request.js:1212:28)
[17:31:31] Syncronizing built-in extensions...
[17:31:31] You can manage built-in extensions with the --builtin flag
[17:31:31] [marketplace] ms-vscode.node-debug@1.22.2 ✔︎
[17:31:31] [marketplace] ms-vscode.node-debug2@1.22.0 ✔︎
./scripts/code.sh: line 47: /home/jlippuner/progs/vscode/.build/electron/code-oss: No such file or directory
```
The `.build` directory doesn't even contain a subdirectory called `electron`.

**Comment by joaomoreno** [comment]
Are you behind a proxy or something like that?

**Comment by jlippuner** [comment]
Yes, I'm behind a proxy, which is specified in the environment variables $http_proxy and $https_proxy. I can't get around the proxy.

**Comment by joaomoreno** [comment]
Seems to be https://github.com/atom/node-github-releases/issues/2

**Comment by joaomoreno** [comment]
Should be fixed by https://github.com/Microsoft/vscode/commit/cc11eb00ba83ee0b6d29851f1a599cf3d9469932

Please reinstall dependencies with `yarn`. Let me know if it works.

**Comment by jlippuner** [comment]
It works. Thanks for the rapid response!

**Comment by vikyd** [comment]
the same problem in Win7, still not working.


- Build from https://github.com/Microsoft/vscode/commit/c05e57d91e50d53d487a9113c1553ca73311fa6c
- OS: Win7 64bit

cmd error:
```cmd
[09:50:48] Starting 'clean-electron'...
[09:50:48] Finished 'clean-electron' after 2.97 ms
[09:50:48] Starting 'electron'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: connect ETIMEDOUT 54.169.195.247:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
[09:51:10] Syncronizing built-in extensions...
[09:51:10] You can manage built-in extensions with the --builtin flag
```


package.json:
```js
...
    "gulp": "^3.8.9",
    "gulp-atom-electron": "^1.16.1",
    "gulp-azure-storage": "^0.7.0",
    "gulp-bom": "^1.0.0",
...
```

**Comment by vikyd** [comment]
No problem for me now. 
Solution:
- At first, I have set proxy in cmd by `set http_proxy=myProxyHost:port`
- That's not correct, the correct answer is: `set http_proxy=http://myProxyHost:port`
  - yeah, I miss the `http://` 

All works.


This also solves the problem when running `yarn`: 
`vscode-ripgrep: Downloading ripgrep failed: Error: connect ETIMEDOUT`
