### ISSUE TITLE
VSCode/OmniSharp looking for DNX runtime in wrong directory

### ISSUE THREAD

**Issue by Daniel15** [Microsoft/vscode#471]
On Mac OS, DNVM installed the DNX runtime in `/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-final`. However, OmniSharp in Visual Studio Code was incorrectly looking in `/Users/danlo/.dnx/runtimes`. To get it to work properly, I created a symbolic link:

```
ln -s /usr/local/lib/dnx/runtimes /Users/danlo/.dnx/runtimes
```

This smells super hacky though.

**Comment by BenMagyar** [comment]
Provided symbolic link creates an additional folder under runtimes, so it still wasn't resolved. Correct (still hacky) symbolic link I believe is:  

```
ln -s /usr/local/lib/dnx/runtimes/* /Users/<User>/.dnx/runtimes/   
```

**Comment by jrieken** [comment]
we adopted the latest version of omnisharp which should fix this

**Comment by chrisdias** [comment]
@jrieken @egamma I still see the problem with 0.10.5. 

if you fully remove dnx from your machine (`rm -rf ~/.dnx`) and run setup from https://get.asp.net it will install the runtime globally into `/usr/local/lib/dnx/runtimes`.  Create a new Web App using the aspnet generator, run `dnu restore`, and then open code on the folder.  

If you follow the [work around from stack overflow](http://stackoverflow.com/questions/33976187/omnisharp-dnx-dnxpaths-the-specified-runtime-path-default-does-not-exist) (ensure you set the default alias too) it starts to work again.

**Comment by egamma** [comment]
Not a blocker for the Dec update, since there is a work around.

**Comment by jrieken** [comment]
I installed rc1 yesterday and the bit ended up in ~/.dnx. I will move this issue to OmniSharp because the lookup happens there.

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#369
