### ISSUE TITLE
Format on Save for Go files results in cursor going to the end of file

### ISSUE THREAD

**Issue by dc0d** [Microsoft/vscode#47382]
Issue Type: <b>Bug</b>

Saving a Go file causes the cursor to jump to the end of file. Sometime the whole view jumps to the end of file.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.13.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz (8 x 2290)|
|Load (avg)|0, 1, 1|
|Memory (System)|15.39GB (11.06GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Ionide-fsharp|Ion|3.18.2
vscode-docker|Pet|0.0.26
Bookmarks|ale|0.18.2
better-toml|bun|0.3.2
systemd-unit-file|coo|1.0.0
reasonml|fre|1.0.34
Go|luk|0.6.78
csharp|ms-|1.14.0
vscode-code-outline|pat|0.1.0
show-offset|ram|0.0.3
vscode-proto3|zxh|0.1.3

</details>

**Comment by nicksnyder** [comment]
I have the same issue

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:21:13.607Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.91GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_274499|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
swift|Kas|0.0.3
better-toml|bun|0.3.2
vscode-eslint|dba|1.4.8
gitlens|eam|8.2.0
tslint|eg2|1.0.28
prettier-vscode|esb|1.2.2
graphql-for-vscode|kum|1.9.1
Go|luk|0.6.78
MagicPython|mag|1.0.12
mssql|ms-|1.3.0
python|ms-|2018.3.1
debugger-for-chrome|msj|4.3.0
java|red|0.22.0
vscode-yaml|red|0.0.10
vscode-sql-beautify|sen|0.0.4
stylelint|shi|0.36.0
python|tht|0.2.3
vim|vsc|0.11.3
vscode-open-in-github|ziy|1.3.1


</details>

**Comment by roblourens** [comment]
Does it happen when you start with --disable-extensions?

**Comment by nicksnyder** [comment]
No, this appears to happen when the Go extension is enabled. I suspect it is related to `gofmt` running.

**Comment by dc0d** [comment]
Same here. I've tested this with all three of `gofmt`, `goimports` or `goreturns` but the problem stands.

**Comment by dc0d** [comment]
Also (since it seemed to be a problem with Go formatting tools) I've added this section to the setting, which did not help to solve the problem:

```
    "[go]": {
        "editor.formatOnSave": true,
        "editor.formatOnSaveTimeout": 2000
    }
```

**Comment by ramya-rao-a** [comment]
@dc0d @nicksnyder Did this start to happen recently after the upgrade to VS Code 1.22 or did you see it before as well?

**Comment by dc0d** [comment]
@ramya-rao-a It started after latest update (on Ubuntu, 16.04 for me). I have tried to find out if it is caused by a specific extension, by turning them off/on one by one. But it seems this is caused only by Go extension.

One interesting observation: It happens most in big Go source files.

**Comment by dc0d** [comment]
@ramya-rao-a An example repo that can be used for reproducing this is `bbolt` (`go get github.com/coreos/bbolt/...`).

If we open `bucket.go` and enter a space or tab somewhere and then save, the cursor will jump to the end of the file.

**Comment by ramya-rao-a** [comment]
@dc0d Thanks for that pointer, I can repro it now. Will look into it

**Comment by ramya-rao-a** [comment]
Until we figure out the root cause, you can disable the format on save feature that is causing this by adding the below to your settings:
```
"[go]": {
    "editor.formatOnSave": false
}
```

**Comment by ramya-rao-a** [comment]
The formatting provider in the Go extension returns a single text edit of kind "replace" to replace the complete file content, and depends on the [computeMoreMinimalEdits](https://github.com/Microsoft/vscode/blob/215d65126f851fcb3d23e3ad51f934357c19783f/src/vs/workbench/api/electron-browser/mainThreadSaveParticipant.ts#L206) to be called by the core. But the `computeMoreMinimalEdits` doesn't seem to be computing the minimal edits in 1.22 anymore. 

@jrieken @alexandrudima Did anything change in this area for 1.22?

**Comment by jrieken** [comment]
No, nothing has for `computeMoreMinimalEdits` in the last year. How does go implement formatting? What is the exact file/edits?

**Comment by ramya-rao-a** [comment]
@jrieken Go registers a formatting provider that returns an array of TextEdits. This array has a single edit to replace the entire contents of the file. See https://github.com/Microsoft/vscode-go/blob/0.6.78/src/goFormat.ts#L74-L78

**Comment by ramya-rao-a** [comment]
Ok, looks like nothing changed in `computeMoreMinimalEdits`. There is an upper limit set at https://github.com/Microsoft/vscode/blob/14a2bc0214fdee3ed1c30fba88db5ea827093518/src/vs/editor/common/services/editorSimpleWorker.ts#L364 which aborts computing minimal edits. This hasnt changed in 1.21 vs 1.22. Something else that decides the cursor position after applying an edit has changed.

cc @alexandrudima @rebornix

**Comment by alexandrudima** [comment]
It might be caused by https://github.com/Microsoft/vscode/commit/118e1445ea027c6df9c66b870bc22f78f5c75a88#diff-f8aa0da950270e2d56baecaf5819a4c5

**Comment by ramya-rao-a** [comment]
As per https://github.com/Microsoft/vscode/issues/38728#issuecomment-347794326, extensions that register formatting providers and return replace-entire-file as the new content edit can expect the markers/cursor to stay where they were. As we dont do this anymore, this is a regression.

Adding this to the March Recovery milestone.

**Comment by arackaf** [comment]
Just want to chime in here that this bug is by no means limited to Go.  Formatting on save performed by Prettier (JavaScript) results in the same behavior.  

But it looks like the cause was already found - eagerly looking forward to the patch :)

**Comment by alexandrudima** [comment]
Repro steps:

* create a go file:
```go
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.
// This is a long comment in order to have a file which is larger than 10k. This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.  This is a long comment in order to have a file which is larger than 10k.

package main

import "fmt"

func main() {
	fmt.Println("hello world")
}

```
* remove the tab in front of `fmt.Println`
* save

**Comment by alexandrudima** [comment]
Fix pushed to `master` and to `release/1.22`

**Comment by SlurpTheo** [comment]
FYI: I was getting this for TypeScript (`*.ts`) files too, but it appears fixed in 1.22.2 as well.

**Comment by keremispirli** [comment]
Just installed 1.22.2 and I still have the same behaviour for Haskell files with stylish-haskell extension. I don't know if it matters but this extension doesn't use `editor.formatOnSave` setting; it contributes a `stylishHaskell.runOnSave` setting instead.

**Comment by alexandrudima** [comment]
@keremispirli This fix and this regression occurs specifically in the formatter case. It is possible that the Haskell extension is pushing edits directly on the buffer, avoiding going through the formatter, and thus not benefitting from the computation of more minimal edits. Perhaps you can reach out to the extension author and let them know that best practice is to register a formatter if they provide formatting.
