### ISSUE TITLE
Slowly node module name auto-complete and high CPU usage

### ISSUE THREAD

**Issue by hangxingliu** [Microsoft/vscode#47576]
Issue Type: <b>Bug</b>

OS: Ubuntu 18.04 LTS (Bionic Beaver)

Reproduce:

1. create a javascript file anywhere (standalone or inside project)
2. type: `let fs = require("`, press auto-compeletion shortcut.
3. you can wait 2~3 seconds or longer time to get completion items with high CPU usage.

I have reproduced this bug in vscode launched by `--disable-extensions` option.

and this bug is not existed in version `1.21.1-1521038896` and `1.20.1-1518535978` (I have tested by downgrade my vscode).

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.15.0-15-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 1516)|
|Load (avg)|1, 1, 1|
|Memory (System)|15.68GB (4.54GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by hangxingliu** [comment]
Actually, You don't need active auto-complete by shortcut in above reproduce step. You can also get high CPU usage and completion items after many seconds

**Comment by mjbvz** [comment]
Can you please test this in the latest insiders build as well

**Comment by hangxingliu** [comment]
It still exists, screen record:
![peek 2018-04-11 02-26](https://user-images.githubusercontent.com/4303130/38576210-094d974c-3d30-11e8-9406-35bd40cfc413.gif)


---

Version 1.23.0-insider
Commit 609c4ba1e7abc39952ef5fb7f3a22c0be0349efe
Date 2018-04-10T05:11:50.437Z

**Comment by mjbvz** [comment]
Thank you for checking. Please try upgrading to typescript@next in your workspace: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

A similar issue has been fixed in TypeScript 2.9. The current VS Code insiders build uses TypeScript 2.8.3

**Comment by hangxingliu** [comment]
@mjbvz  It seems fine now in insider version 1.23.0-insider e545ae6b34aae3f05a923d5258adbb58805ca27f

And the insider version uses TypeScript in **/usr/share/code-insiders/resources/app/extensions/node_modules/typescript** (2.8.3)

**Comment by hangxingliu** [comment]
But I found this bug still in there in version 1.23.0 (7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45) although I use newer TypeScript 2.9.0-dev.

**Comment by hangxingliu** [comment]
And I have test use version 1.21.1 with difference Typescript version (VSCode inner version 2.72 to developement version 2.9.0) just ok. But if I just upgrade VSCode to 1.22.0, The bug is come back.

And I am waiting for it be fixed  so I can upgrade my VSCode.

Thanks

**Comment by hangxingliu** [comment]
I upgrade to 1.26.1 now. It seems been fixed
