### ISSUE TITLE
Terminal links are offset after CJK characters

### ISSUE THREAD

**Issue by hoxily** [Microsoft/vscode#47871]
Issue Type: <b>Bug</b>

在终端里面输入可以被识别的url链接后，如果链接前面还有中文字符，就会出现下划线以及相应的Ctrl+点击响应区域都向左偏。

如图所示例子：https://img.vim-cn.com/74/13cb93b28d38306c8c247bd80039b5882511f8.png
![vsc url link underline bug](https://user-images.githubusercontent.com/1575029/38767423-585b86d8-4013-11e8-8e08-c7050efd9850.png)

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:38:45.278Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|Memory (System)|7.90GB (0.53GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2018.3.1
csharp|ms-|1.14.0
java|red|0.22.0
vscode-java-debug|vsc|0.8.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.5.0
vscode-maven|vsc|0.7.0

</details>

**Comment by sayomelu** [comment]
提issue最好用英文啊, 老外又看不懂
It’s better to submit issue in English

**Comment by pansila** [comment]
Translation:
All URLs preceded by Chinese characters have an underline offset and respond to the click event in an area to the left of the actual clicked place.

**Comment by alexandrudima** [comment]
This appears to be in the terminal

**Comment by Tyriar** [comment]
This just came through in the upstream repo too, not a regression https://github.com/xtermjs/xterm.js/issues/1387

**Comment by Tyriar** [comment]
This should be fixed in tomorrow's insiders.

**Comment by octref** [comment]
This still doesn't work correctly:

![image](https://user-images.githubusercontent.com/4033249/46164877-ff805d00-c243-11e8-9743-ea2001618d08.png)

Repro:

```sh
echo "http://www.baidu.com/s?wd=中文"
echo "http://www.baidu.com/s?wd=%E4%B8%AD%E6%96%87"
```

**Comment by Tyriar** [comment]
@octref that's a different issue deferred to https://github.com/xtermjs/xterm.js/issues/583

This one is specifically about CJK before the link offsetting the links.
