### ISSUE TITLE
[mitigated] macOS: background artifacts in editor

### ISSUE THREAD

**Issue by gusbemacbe** [Microsoft/vscode#48043]
- **VSCode Version:** 1.23.0
- **OS Version:** macOS 10.13.4

**Steps to Reproduce:**

Observe the background in the screenshot. Compare two colours in the same background. I also changed to default theme and it still occurs the same too.

**Does this issue occur when all extensions are disabled?: Yes/No**
Yes, it still occurs the same thing.

![Screenshot bug](https://user-images.githubusercontent.com/2257024/38862508-7b24903e-420b-11e8-98bc-295b576b6f3b.png)

With all extensions disabled, check:

![Screenshot bug with disabled extensions](https://user-images.githubusercontent.com/2257024/38862554-a01abecc-420b-11e8-90c3-4d5c30f9389e.png)

**Comment by ramya-rao-a** [comment]
Does this happen only in the Insiders and not in stable?

**Comment by alexandrudima** [comment]
This looks like a bug in the way Chromium does tiling when rendering using the GPU.

@bpasero @Tyriar Have you seen this before ?

**Comment by gusbemacbe** [comment]
Only in Insiders on macOS.

On Linux, it is all OK. In spite of it, on LInux, using an Apple keyboard, Insiders suffers of another bug: when you press fn + F6 to wrap line, wrap and unwraping automatically line doesn't stop. I had to hold to cancel, using esc.

**Comment by alexandrudima** [comment]
@gusbemacbe let's track one issue per issue. Open another issue if you have trouble with the Apple keyboard and please add as many details as possible.

**Comment by gusbemacbe** [comment]
I runned `code-insiders --disable-gpu` in both all enabled and disabled extensions and it is still the same bug. I also have just updated today and it is still the same bug, disabling both extensions and GPU. 

I will give you all details:

Mac mini mid 2011, 2,3 GHz Intel Core i5, 8 GB 1333 MHz DDR3, Intel HD Graphics 3000 512 MB and macOS High Sierra 10.13.4

```shell
code-insiders --list-extensions
DotJoshJohnson.xml
PKief.material-icon-theme
Tyriar.sort-lines
Zignd.html-css-class-completion
abusaidm.html-snippets
alexdima.copy-relative-path
bajdzis.vscode-database
be5invis.vscode-custom-css
bradgashler.htmltagwrap
brapifra.phpserver
brunnerh.file-properties-viewer
castwide.solargraph
cstrap.python-snippets
dbaeumer.vscode-eslint
donjayamanne.jupyter
donjayamanne.python-extension-pack
dustinsanders.an-old-hope-theme-vscode
ecmel.vscode-html-css
eg2.tslint
eiminsasete.apacheconf-snippets
idleberg.emoji-code
felixfbecker.php-debug
felixfbecker.php-intellisense
felixfbecker.php-pack
formulahendry.auto-close-tag
formulahendry.code-runner
formulahendry.vscode-mysql
goessner.mdmath
heberalmeida.php-snippets
hwencc.html-tag-wrapper
jakebathman.mysql-syntax
jakeboone02.cypher-query-language
jakelucas.code-select-until
jerriepelser.copy-markdown-as-html
jithurjacob.nbpreviewer
jmredfern.sort-selection
jock.svg
junstyle.php-cs-fixer
kamikillerto.vscode-colorize
konstantin.wrapSelection
magicstack.MagicPython
mdickin.markdown-shortcuts
mrmlnc.vscode-apache
mrmlnc.vscode-attrs-sorter
mrmlnc.vscode-duplicate
ms-python.python
ms-vscode.atom-keybindings
ms-vscode.cpptools
ms-vscode.csharp
naumovs.color-highlight
ohansemmanuel.css-grid-snippets
pranaygp.vscode-css-peek
rasmus.al-formatter
rebornix.Ruby
robinbentley.sass-indented
searKing.preview-vscode
sensourceinc.vscode-sql-beautify
yzhang.markdown-all-in-one
```

```json
{
    "atomKeymap.promptV3Features": true,
    "auto-close-tag.SublimeText3Mode": true,
    "colorize.activate_variables_support_beta": true,
    "colorize.languages": [ "css", "html", "php", "svg"],
    "css.validate": false,
    "editor.autoIndent": false,
    "editor.colorDecorators": false,
    "editor.fontFamily": "Everson Mono Bold, Menlo, Monaco, Courier New, Aegean, monospace",
    "editor.fontLigatures": true,
    "editor.fontSize": 12,
    "editor.minimap.enabled": false,
    "editor.minimap.renderCharacters": false,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.quickSuggestions": 
    {
        "comments": true,
        "other": true,
        "strings": true
    },
    "editor.renderLineHighlight": "none",
    "editor.selectionHighlight": false,
    "editor.smoothScrolling": true,
    "editor.tabCompletion": true,
    "editor.tabSize": 2,
    "emmet.excludeLanguages": [""],
    "emmet.includeLanguages": { "vue-html": "html", "markdown": "html" },
    "emmet.showSuggestionsAsSnippets": true,
    "explorer.autoReveal": false,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "files.autoSave": "onFocusChange",
    "files.exclude": 
    {
        "**/.DS_Store": false
    },
    "git.autofetch": true,
    "git.confirmSync": true,
    "git.enableSmartCommit": true,
    "html-css-class-completion.enableEmmetSupport": true,
    "html.format.indentInnerHtml": true,
    "material-icon-theme.files.associations": 
    {
        "changelog.php": "changelog"
    },
    "material-icon-theme.folders.associations": 
    {
        "fontes": "font",
        "idiomas": "i18n",
        "imagens": "images",
        "javascript": "javascript",
        "language": "i18n",
        "teste": "test"
    },
    "material-icon-theme.folders.color": "#E5CD52",
    "phpserver.browser": "firefox",
    "phpserver.port": 8200,
    "php-cs-fixer.formatHtml": true,
    "search.location": "panel",
    "terminal.integrated.fontFamily": "Everson Mono",
    "terminal.integrated.fontSize": 16,
    "workbench.activityBar.visible": true,
    "workbench.colorCustomizations": 
    {
        "activityBarBadge.background": "#E5CD52",
        "activityBar.border": "#E5CD52",
        "activityBar.foreground": "#A9B8BA",
        "scrollbarSlider.background": "#E5CD52",
        "scrollbarSlider.hoverBackground": "#4FB4D7"
    },
    "workbench.editor.enablePreview": false,
    "workbench.fontAliasing": "antialiased",
    "workbench.iconTheme": "material-icon-theme",
    "workbench.startupEditor": "none",
    "window.zoomLevel": 1,
    "workbench.colorTheme": "An Old Hope"
}
```

**Comment by bpasero** [comment]
@gusbemacbe and you are not seeing this in stable version right?

**Comment by gusbemacbe** [comment]
@bpasero 

Yes, VSCode stable doesn't have this bug on macOS.

On LInux, both VSCode stable and Insiders do not have this bug.

Only on macOS and on VSCode Insiders, it odes have this bug.

**Comment by gusbemacbe** [comment]
No, it doesn't. I ran it and it appears still with this same bug.

**Comment by bpasero** [comment]
@gusbemacbe I am a bit confused by that answer, does it reproduce when you use that flag or does it not reproduce?

**Comment by bpasero** [comment]
@gusbemacbe this issue seems to be the same as https://github.com/Microsoft/vscode/issues/12473 which for some reason comes back with the new Electron. There are more workarounds described in that issue that you could try out:
* change the zoom level (View > Zoom In)
* run with `code --force-gpu-rasterization`

Also interesting, are you running with a custom color profile? I came across that via the comment in https://github.com/Microsoft/vscode/issues/12473#issuecomment-294588097

**Comment by gusbemacbe** [comment]
> @gusbemacbe I am a bit confused by that answer, does it reproduce when you use that flag or does it not reproduce?

I ran all these commands you suggested, in both integrated terminal and external terminal, nothing happened, no flags, no verbose, no reproductions. The editor is like Ahch-To. 

> change the zoom level (View > Zoom In)
> run with code `--force-gpu-rasterization`

I ran this command in both integral and external terminals, nothing happened. The bug is still:

![This bugs never dies](https://user-images.githubusercontent.com/2257024/39038455-f0d32098-4459-11e8-91ff-d569a4fdce48.png)

> Also interesting, are you running with a custom color profile? I came across that via the comment in #12473 (comment)

I have already changed all colour profiles and the bug is still there. But when I changed the colour profile, the background changed and glitched and you can see two animated gIFs:

![Color profile](https://user-images.githubusercontent.com/2257024/39038707-8d0d2c2e-445a-11e8-8375-3eef2c7b4d1b.png)

![Glitched background I](https://user-images.githubusercontent.com/2257024/39039051-2d652406-445b-11e8-9f40-725d5cfc4107.gif)

![Glitched background](https://user-images.githubusercontent.com/2257024/39039117-49e608e8-445b-11e8-883c-3ba0f1a80636.gif)

**Comment by gusbemacbe** [comment]
Yes, I restarted to update and the bug is still.

**Comment by gusbemacbe** [comment]
I have received the warning as I have read one of suggestions in https://github.com/Microsoft/vscode/issues/12473#issuecomment-249162278. 

```shell
$ '/Applications/My apps/Visual Studio Code - Insiders.app/Contents/MacOS/Electron' --force-gpu-rasterization
[main 05:31:58] update#setState idle
2018-04-20 05:31:58.891 Electron[1195:30076] *** WARNING: Textured window <AtomNSWindow: 0x7fd8125b2ea0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

**Comment by gusbemacbe** [comment]
Applying this path, running all the commands you suggested, it is the same warning and the bug is still there.

**Comment by gusbemacbe** [comment]
I have calibrated the colour profile and it almost or quite seemed to work, but the bug appeared by surprise:

![screen shot 2018-04-20 at 05 45 52](https://user-images.githubusercontent.com/2257024/39040922-5eab582a-445e-11e8-8f88-130424b3271b.png)

**Comment by Tyriar** [comment]
@gusbemacbe Insiders is currently on Electron 1.7.12 which explains why the bug went away.

**Comment by bpasero** [comment]
@Tyriar let's leave it open to track the Electron 2.0.x issues. All of those I marked as [electron-update](https://github.com/Microsoft/vscode/labels/electron-update), even though they do not exist in our current release.

**Comment by gusbemacbe** [comment]
OK, @bpasero.

**Comment by bpasero** [comment]
@Tyriar oh sorry, I did not see that @gusbemacbe closed it :)

**Comment by bpasero** [comment]
@gusbemacbe according to a Chrome issue I have read, folks are saying that this issue has been addressed by Apple in the 10.13.4 update. I see however that you are on that version, which is odd. Can you:
* update to macOS 10.13.5 (the latest)
* use [this build](https://az764295.vo.msecnd.net/exploration/f8edf3e79a46e49f8054e9b85a6b6acd33de58aa/VSCode-darwin-exploration.zip) to reproduce the issue
* report back if you still see it?
* if you still see it, what is you hardware configuration (GPU for example?)

**Comment by gusbemacbe** [comment]
Hi @bpasero,

The bug is back. Here is the screenshot:

![bug 1](https://user-images.githubusercontent.com/2257024/41196262-73375916-6c12-11e8-9fbe-739e0f2516d1.png)

![bug 2](https://user-images.githubusercontent.com/2257024/41196266-8ef1710a-6c12-11e8-9e78-ab96951674dd.png)

But if I change colour profile, here is:

![image](https://user-images.githubusercontent.com/2257024/41196283-c4deb976-6c12-11e8-9735-780e8dfa40c3.png)

![image](https://user-images.githubusercontent.com/2257024/41196286-d1dea2da-6c12-11e8-99ed-97ddb9a54da2.png)

They are compatible only with monitor's new colour profile (if monitor is a Samsung, it would be SM[number-serie] and with sRGB, but not with Apple RGB and Generic RGB Profile. 

And here are the details of Mac mini Mid 2011, including hardware GPU in German (as you are a German-speaking Swiss): https://support.apple.com/kb/SP632?viewlocale=de_DE

If you insist, here is the quick detail of hardware GPU: https://browser.geekbench.com/macs/90

**Comment by bpasero** [comment]
@gusbemacbe so do you have the model with discrete GPU (`AMD Radeon HD 6630M`)?

> They are compatible only with monitor's new colour profile (if monitor is a Samsung, it would be SM[number-serie] and with sRGB, but not with Apple RGB and Generic RGB Profile.

With "compatible", do you mean the issue goes away when you switch to `SM[number-serie]` or `sRGB`?

**Comment by gusbemacbe** [comment]
> so do you have the model with discrete GPU (AMD Radeon HD 6630M)?

No, I ran via terminal, here is the result:

```shell
lspci -nn | grep '\[03'
00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0126] (rev 09)

sudo lshw -C display
  *-display                 
       description: VGA compatible controller
       product: 2nd Generation Core Processor Family Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:43 memory:a0000000-a03fffff memory:90000000-9fffffff ioport:2000(size=64) memory:c0000-dffff

lspci | grep ' VGA ' | cut -d" " -f 1 | xargs -i lspci -v -s {}
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Apple Inc. 2nd Generation Core Processor Family Integrated Graphics Controller
	Flags: bus master, fast devsel, latency 0, IRQ 43
	Memory at a0000000 (64-bit, non-prefetchable) [size=4M]
	Memory at 90000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 2000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
```

> With "compatible", do you mean the issue goes away when you switch to SM[number-serie] or sRGB?

Yes

> Are you on latest macOS 10.13.5 by now?

Yes

**Comment by bpasero** [comment]
@gusbemacbe would you be willing and able to do a slight code modification in the code exploration build and then try again? That would be:
* close VSCode exploration
* open `/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/main.js`
* find the place where it reads `app.commandLine.appendSwitch("disable-mojo-local-storage");`
* right after paste this: `app.commandLine.appendSwitch('disable-accelerated-2d-canvas');`
* save
* start VSCode exploration again

=> does the issue still reproduce?

**Comment by bpasero** [comment]
@gusbemacbe thanks for trying, I am a bit confused as to why that would not help because I think that is the same configuration as we run with Electron 1.7. To find this out can you:

**code-exploration**
* install `code-exploration` on path if not yet done (see screenshot below)
* run that modified version of code exploration
* from a terminal run `code-exploration --status` and attach the output

![image](https://user-images.githubusercontent.com/900690/41202666-dc5fa4f6-6ccc-11e8-825d-69af19b8f65c.png)

**code stable**
* do the same as above and attach the output to compare the difference in the GPU features

**Comment by gusbemacbe** [comment]
I do not have VSCode Stable. I have only VSCode Insiders. Are VSCode Insiders and VSCode Exploration the same? If so, I will download the VSCode Stable.

**Comment by gusbemacbe** [comment]
* code-exploration:

```shell
code-exploration --status

Version:          Code - Exploration 1.25.0-exploration (f8edf3e79a46e49f8054e9b85a6b6acd33de58aa, 2018-06-08T12:14:44.494Z)
OS Version:       Darwin x64 17.6.0
CPUs:             Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)
Memory (System):  8.00GB (1.26GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/My apps/Visual Studio Code - Exploration.app/Contents/MacOS/Electron
GPU Status:       2d_canvas:                    disabled_software
                  checker_imaging:              disabled_off
                  flash_3d:                     unavailable_software
                  flash_stage3d:                unavailable_software
                  flash_stage3d_baseline:       unavailable_software
                  gpu_compositing:              unavailable_software
                  multiple_raster_threads:      unavailable_off
                  native_gpu_memory_buffers:    unavailable_software
                  rasterization:                unavailable_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  webgl:                        unavailable_off
                  webgl2:                       unavailable_off

CPU %	Mem MB	   PID	Process
    0	   115	  1085	code-exploration main
    0	    82	  1088	   shared-process
```

* code-stable:

```shell
code --status

Version:          Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:30:30.113Z)
OS Version:       Darwin x64 17.6.0
CPUs:             Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)
Memory (System):  8.00GB (1.02GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/My apps/Visual Studio Code.app/Contents/MacOS/Electron
GPU Status:       2d_canvas:                    unavailable_software
                  flash_3d:                     unavailable_software
                  flash_stage3d:                unavailable_software
                  flash_stage3d_baseline:       unavailable_software
                  gpu_compositing:              unavailable_software
                  multiple_raster_threads:      unavailable_off
                  native_gpu_memory_buffers:    unavailable_software
                  rasterization:                unavailable_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  vpx_decode:                   unavailable_software
                  webgl:                        unavailable_off
                  webgl2:                       unavailable_off

CPU %	Mem MB	   PID	Process
    0	   106	  1164	code main
    0	   156	  1167	   window (Welcome)
    0	    66	  1188	     extensionHost
    0	    82	  1168	   shared-process
```

* code-insiders

```shell
code-insiders --status

Version:          Code - Insiders 1.25.0-insider (8f8ed32e737a7a906fac654fb0bd61b257b449b1, 2018-06-08T05:10:42.592Z)
OS Version:       Darwin x64 17.6.0
CPUs:             Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)
Memory (System):  8.00GB (1.04GB free)
Load (avg):       2, 2, 2
VM:               0%
Screen Reader:    no
Process Argv:     /Applications/My apps/Visual Studio Code - Insiders.app/Contents/MacOS/Electron
GPU Status:       2d_canvas:                    unavailable_software
                  flash_3d:                     unavailable_software
                  flash_stage3d:                unavailable_software
                  flash_stage3d_baseline:       unavailable_software
                  gpu_compositing:              unavailable_software
                  multiple_raster_threads:      unavailable_off
                  native_gpu_memory_buffers:    unavailable_software
                  rasterization:                unavailable_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  vpx_decode:                   unavailable_software
                  webgl:                        unavailable_off
                  webgl2:                       unavailable_off

CPU %	Mem MB	   PID	Process
    1	   115	  1211	code-insiders main
    0	   115	  1213	   shared-process
```

**Comment by bpasero** [comment]
@gusbemacbe thanks, there seems to be a difference for 2d_canvas between insiders and exploration build. Does `code-exploration --force-gpu-rasterization` fixes it?

**Comment by gusbemacbe** [comment]
No, it is still the same bug:

![screen shot 2018-06-10 at 12 33 35](https://user-images.githubusercontent.com/2257024/41203231-842954a2-6caa-11e8-8c11-0102a914cb1d.png)

![screen shot 2018-06-10 at 12 34 13](https://user-images.githubusercontent.com/2257024/41203239-99809e78-6caa-11e8-932a-5534f474f3bf.png)

**Comment by gusbemacbe** [comment]
@bpasero, I come to advice that since I upgraded to the latest version of VSCode Insiders, the bug affects all colour profiles, not just [monitor][number-serie]. Put it in case of emergency.

**Comment by bpasero** [comment]
@gusbemacbe does it reproduce if you zoom in once? I think previously we heard reports that this would resolve the issue.

**Comment by gusbemacbe** [comment]
Hello @bpasero 

When I restored the zoom, increased or decreased the zoom, it is still the bug, using [monitor][number-serie]:

![screen shot 2018-06-13 at 13 58 31](https://user-images.githubusercontent.com/2257024/41366289-fc7d6d44-6f11-11e8-9ba8-323997c88c5f.png)

**Comment by bpasero** [comment]
@gusbemacbe another idea I had that is worth a try:

* quit any running VSCode exploration
* open /Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/main.js
* find the place where it reads `app.commandLine.appendSwitch("disable-mojo-local-storage");`
right after paste this: `app.commandLine.appendSwitch('force-color-profile', 'srgb');`
* save
* start VSCode exploration again
=> does the issue still reproduce?

**Comment by gusbemacbe** [comment]
Hi @bpasero 

Sorry, I was busy with my college. I am on holidays. I have just tested and the bugs are gone. It worked very well with all colour profiles. Then `'force-color-profile', 'srgb'` is perfectly compatible with all Apple colour profiles.

**Comment by bpasero** [comment]
@gusbemacbe that is great to hear

**Comment by gusbemacbe** [comment]
I saw the issue of @nicmr, I ran and tested VSCode Insiders on Ubuntu 18.04 on a Mac mini and there is no colour background bug here, but I am aware that we have used the same version 7dc9539. She updated yesterday 15 and I updated today.

**Comment by gusbemacbe** [comment]
Ah, she uses Linux x64 4.15.0-23-generic and I use 4.15.0-20-generic. Her kernel is more recent than mine.

**Comment by bpasero** [comment]
@gusbemacbe the current insiders build of VSCode includes Electron 2.0.x, so no need to use the exploration builds. Since you indicated that setting `app.commandLine.appendSwitch('force-color-profile', 'srgb');` fixes this issue for you, we will probably use that as the workaround.

**Comment by bpasero** [comment]
@gusbemacbe can you try with todays insider release to see if you still get background artifacts?

**Comment by gusbemacbe** [comment]
@bpasero 

I have just updated and tested VSCode Insider on macOS, with all colour profiles. No bugs. 

![applause](https://media.giphy.com/media/kpWbVBzcSiO2I/giphy.gif)

**Comment by bpasero** [comment]
@gusbemacbe thanks, yeah I think changing the color profile on your end would probably not cause any change given that the new insiders forces the color profile to be sRGB. We might end up shipping with a setting that users have to opt-in in the future, as I feel not 100% good about making it a default.

**Comment by gusbemacbe** [comment]
@bpasero 

> changing the color profile on your end would probably not cause any change given that the new insiders forces the color profile to be sRGB. We might end up shipping with a setting that users have to opt-in in the future, as I feel not 100% good about making it a defa

You should ask @nicmr and other users of macOS Sierra, High Sierra 10.13.4 and of alpha Mojave 10.14 to test for making sure that it is all OK. If it is not all OK, I suggest you to add `color-profile`  to `settings.js` and offer 3 options: `disable-mojo-local-storage`, `'force-color-profile', 'srgb'` and `disable-accelerated-2d-canvas`.

**Comment by gusbemacbe** [comment]
@bpasero 

> @gusbemacbe just to be clear, you are NOT running with `disable-accelerated-2d-canvas` right? My understanding was that `force-color-profile: srgb` fixes it for you already.

Sorry for my absence, I was busy with my college, now I am on holidays, but I was also busy with the design of icons on holidays. 

With  `force-color-profile: srgb` as default in VSCode, it must work for me on a macOS and Linux on a particular computer, but it must not work for other people on macOS and other OSes on other different computers and different screens, it is why you should ask @josh-tepper and the other Linux, macOS and Windows users to test the latest version of VSCode, with  `force-color-profile: srgb` as default. 

If it does not work for them, you should think of adding the option of switching in `settings.json`.

**Comment by gusbemacbe** [comment]
I do not know if you and @RMacfarlane think it is good idea to switch different GPU options added to `settings.json` instead of changing the `app.commandLine.appendSwitch` default.

**Comment by gusbemacbe** [comment]
I think I understood what happened with @josh-tepper's integrated terminal of VSCode which suffered of a flickering. The flickering was caused and affected by Electron bug due to the GPU fail. See the reference, although Atom and VSCode are unrelated: https://github.com/atom/atom/issues/15323

**Comment by bpasero** [comment]
@gusbemacbe yeah I am just trying to figure out if `force-color-profile: srgb` alone fixed the flickering for your particular case. And it looks like it does (note that current insider versions are no longer on Electron 2.0.x but back to 1.7.x).

The latest build with Electron 2.0.4 to play with is: https://az764295.vo.msecnd.net/insider/c13b8641174a66e6316d809c785fdc884998bc89/VSCode-darwin-insider-unsigned.zip

**Comment by gusbemacbe** [comment]
Sorry for my absence. I was busy but finished with the icons design. I have just tested and it worked. Interesting, did this latest version of VSCode come already with `'force-color-profile', 'srgb'`? So I saw `2d_canvas:  unavailable_software`.

```
Version:          Code - Insiders 1.26.0-insider (c13b8641174a66e6316d809c785fdc884998bc89, 2018-07-04T07:22:20.999Z)
OS Version:       Darwin x64 17.6.0
CPUs:             Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)
Memory (System):  8.00GB (0.32GB free)
Load (avg):       4, 3, 2
VM:               0%
Screen Reader:    no
Process Argv:     /private/var/folders/wk/nx85lpb94s3488cyhvklzhww0000gn/T/AppTranslocation/56269756-8E9A-480B-9C19-64D3B1F94D97/d/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_229432
GPU Status:       2d_canvas:                    unavailable_software
                  checker_imaging:              disabled_off
                  flash_3d:                     unavailable_software
                  flash_stage3d:                unavailable_software
                  flash_stage3d_baseline:       unavailable_software
                  gpu_compositing:              unavailable_software
                  multiple_raster_threads:      unavailable_off
                  native_gpu_memory_buffers:    unavailable_software
                  rasterization:                unavailable_software
                  video_decode:                 unavailable_software
                  video_encode:                 unavailable_software
                  webgl:                        unavailable_off
                  webgl2:                       unavailable_off

CPU %	Mem MB	   PID	Process
    3	   172	  1602	code-insiders main
    0	   139	  1609	   shared-process
    0	   344	  1802	   window (suru-plus)
    0	   123	  1803	     extensionHost
    0	    57	  1804	     watcherService
    0	    41	  1839	     searchService

Workspace Stats:
|  Window (suru-plus)
|    Folder (suru-plus): 18313 files
|      File types: svg(18051) desktop(59) cur(55) md(11) directory(4) theme(2)
|                  ani(2) gitattributes(1) gitignore(1) png(1)
|      Conf files:
```

**Comment by gusbemacbe** [comment]
Can I have this latest version with this option for Linux to test?

**Comment by bpasero** [comment]
@gusbemacbe that would be: https://az764295.vo.msecnd.net/insider/c13b8641174a66e6316d809c785fdc884998bc89/code-insider-1.26.0-1530689613_amd64.tar.gz

**Comment by gusbemacbe** [comment]
I have just tested it on Deepin OS with GNOME 3.22.2, using the Samsung screen, on a Mac mini, exhibiting the integrated terminal (because of @josh-tepper) and it worked without flickering. It was quicker than the former version (Electron 1.17.4). I will test on Manjaro with KDE on my HP EliteBook.

**Comment by gusbemacbe** [comment]
I have tested, with integrated terminal, on Manjaro, on a HP EliteBook and it worked without flickering.

**Comment by bpasero** [comment]
@gusbemacbe thanks, good to know

**Comment by bpasero** [comment]
Closing, I think we can ship with this workaround.
