### ISSUE TITLE
Nodemon restarts twice on file changes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#48501]
Refs: https://github.com/Microsoft/vscode/issues/48423

1. Have a simple nodemon setup, using a nodemon sample
2. Start debugging that sample and hit a breakpoint
3. Make a change to that file and save
4. Notice the session properly restars however it seems to restart twice

**Comment by weinand** [comment]
This problem only occurs for "inspector" protocol.

**Comment by roblourens** [comment]
I can't repro any problem with nodemon... was this fixed by any of the debug changes last week?

**Comment by weinand** [comment]
@isidorn since I did not change anything, did you?

**Comment by isidorn** [comment]
I can still reproduce this with the following javascript file

`console.log('hey2');`

And with the following configuration

```
{
            "type": "node",
            "request": "launch",
            "name": "nodemon",
            "runtimeExecutable": "nodemon",
            "program": "${workspaceFolder}/hey.js",
            "restart": true,
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }
```

**Comment by roblourens** [comment]
I guess I'm doing something wrong. Is this the right scenario? What does "restart twice" mean?

![may-08-2018 18-18-00](https://user-images.githubusercontent.com/323878/39790667-3ffe6c54-52ec-11e8-9c3f-4c2b01333fc6.gif)

**Comment by isidorn** [comment]
@roblourens yes you are doing everything fine.
Restart twice means the debug toolbar blinks 2 times in practice. In your demo it blinks only once.

I have node version 8.9.1 and nodemon 1.11.0
Should I update something.
Can I debug this somehow on my machine so you get the needed info?

![twice](https://user-images.githubusercontent.com/1926584/39803518-86c66666-5371-11e8-922d-f7ff685652ae.gif)

**Comment by roblourens** [comment]
Oh, you have auto attach enabled and are running it in the terminal, right? In your gif I see it switch into multi-session debug mode which is not right.

Could this just be related to https://github.com/Microsoft/vscode/issues/49403?

But you don't get the error popup.

**Comment by isidorn** [comment]
@roblourens I can repro if I have auto-attach:false, however I can no longer repro if I remove 
`"console": "integratedTerminal"` so it is somehow connected to that.
Not sure if the adapter is not respceting auto attach off when in intergrated terminal or something else is off.
But you could try to repro with adding intregratedTerminal.

**Comment by weinand** [comment]
I'm pretty sure that this issue is **not** related to auto-attach.
But "auto-attach" must be off (and it was off when Isi filed the issue and I did my investigation).

Using the "integratedTerminal" is mandatory for the nodemon setup anyway because otherwise there is now way to interact with nodemon from the command line (e.g. for killing it).

**Comment by roblourens** [comment]
I pointed out auto-attach because @isidorn's gif shows a second debug session starting (`Process 9448` vs the original `nodemon` one)

I just can't repro any problem, so let's jump on a call to debug this, whenever one of you is free.

Or you could set `"trace": true` but it might not have enough info to solve the problem because it will only show what happened during one session.

**Comment by isidorn** [comment]
I investigated a bit more, and `autoAttach` seems to blame. So if I dsable autoAttach I can not repro.
I suggest to first fix https://github.com/Microsoft/vscode/issues/49403 and then look into this one

My previous comment that I can repro with `autoAttach:off` seems to be wrong -> or more likeyly the debug adapter was not picking up my change to disable autoAttach.

**Comment by weinand** [comment]
I'm no longer able to reproduce this.
