### ISSUE TITLE
JSdoc generation misses parameters beginning with '$'

### ISSUE THREAD

**Issue by AndrewNelis** [Microsoft/vscode#49057]
Issue Type: <b>Bug</b>

Generated jsdoc does not insert the parameter name for parameters starting with '$' (which are common in AngularJS).

Example of the generated output:

(Put cursor on the line before "function test", type "/**" and press enter to complete the JSDoc)

```
/**
 * 
 * @param {*} test1 
 * @param {*}  
 * @param {*} test2 
 */
function test(test1, $arg, test2) {

}
```

Whereas we'd expect:

```
/**
 * 
 * @param {*} test1 
 * @param {*} $arg
 * @param {*} test2 
 */
function test(test1, $arg, test2) {

}
```

VS Code version: Code 1.22.2 (3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9, 2018-04-12T16:34:44.222Z)
OS version: Linux x64 4.15.17-300.fc27.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 2992)|
|Load (avg)|1, 1, 1|
|Memory (System)|15.62GB (0.59GB free)|
|Process Argv|/usr/share/code/code .|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by mjbvz** [comment]
Fixed in 7b3c3436886baf93140ed94252de6efe8275d915

**Comment by AndrewNelis** [comment]
Thanks for the quick response and fix.

**Comment by dbaeumer** [comment]
Still happens to me. Reopening:

![cast](https://user-images.githubusercontent.com/1931590/40732320-5909f454-6433-11e8-82b0-dd7d53d39b6a.gif)

**Comment by dbaeumer** [comment]
Re-verified.
