### ISSUE TITLE
Auto attach causing issues when debugging in integrated terminal

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#49403]
- enable auto attach
- Start a basic node launch config with `"console": "integratedTerminal"`.
- Wait 10s
- Get an error that we couldn't attach to the process, and I assume that it has detected the same process that I am currently debugging:

![image](https://user-images.githubusercontent.com/323878/39719998-cbca7244-51ef-11e8-9462-826072422356.png)

Was this always the case? We could somehow suppress this particular error in this case.

**Comment by weinand** [comment]
fixed by:
- ignoring auto-attach requests when a debug config launch is under way for the integrated terminal
- suppressing attach timeouts for auto-attach launch configurations

**Comment by isidorn** [comment]
I still see this with latest insiders following @roblourens steps -> reopening

**Comment by isidorn** [comment]
OS X, latest insiders
Node 8.9.1

Program I am using
`console.log('test')`

I am not using node-debug (legacy). I am using node2.
Unfortunetly I can not repro anymore (only saw it once). 
Since I can no longer repro it is fine to close this if you want to and I will reopen if I see it again

**Comment by weinand** [comment]
The auto attach code for lives in only in node-debug (legacy) and is shared with node-debug2.

How does you launch config look like?

**Comment by isidorn** [comment]
```json
{
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/hey.js",
            "console": "integratedTerminal"
        }
```

**Comment by weinand** [comment]
and you have a breakpoint on line 1 of hey.js?

**Comment by isidorn** [comment]
Yes I do

**Comment by isidorn** [comment]
Tried around 10 times now, and still can not repro.

**Comment by weinand** [comment]
it is ok if you stop after 1000... ;-)

**Comment by isidorn** [comment]
😊

**Comment by weinand** [comment]
After trying another 837 times, I was able to reproduce (and analyse the problem in the debugger).
There was a name mismatch between the property named emitted by node-debug and the corresponding code in VS Code.

**Comment by isidorn** [comment]
Verified via code review and that I can still not repro :)
