### ISSUE TITLE
Refreshing the window in light theme causes bad flicker

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5032]
![untitled](https://cloud.githubusercontent.com/assets/900690/14313869/677a9b28-fbf4-11e5-99b1-cdd024db0d92.gif)

@aeschli fyi

**Comment by aeschli** [comment]
fixed by 1e955490e80f3f2d63aabd6cb3b93e2bc37cd23b

**Comment by bpasero** [comment]
@aeschli I am on latest and still see it when running  "out of dev"
