### ISSUE TITLE
Webview: Background not applied?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5038]
![image](https://cloud.githubusercontent.com/assets/900690/14320830/d77b5ce2-fc16-11e5-84e2-cff975010e67.png)

I have a simple document provider just returning "Hello World" and it looks like the background of the web view is not fully applied?

**Comment by jrieken** [comment]
I don't see that @bpasero Can you inspect how large the web view is drawn? And also how large the iframe is?

**Comment by bpasero** [comment]
@jrieken I verified that the webview itself is as large as the editor, so it must be the content within. Can you share with me how to show dev tools for the web view?

**Comment by bpasero** [comment]
My extension btw:

```typescript
/*---------------------------------------------------------
 * Copyright (C) Microsoft Corporation. All rights reserved.
 *--------------------------------------------------------*/
'use strict';

import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

    let previewUri = vscode.Uri.parse('css-preview://authority/css-preview');

    class TextDocumentContentProvider implements vscode.TextDocumentContentProvider {
        private _onDidChange = new vscode.EventEmitter<vscode.Uri>();

        public provideTextDocumentContent(uri: vscode.Uri): string {
            // return `<html>
            //     <body>
            //         <div>Preview of the CSS properties</dev>
            //         <hr>
            //         <div id="el">Lorem ipsum dolor sit amet, mi et mauris nec ac luctus lorem, proin leo nulla integer metus vestibulum lobortis, eget</div>
            //     </body>
            //     </html>`;
            return "hello world"
        }

        get onDidChange(): vscode.Event<vscode.Uri> {
            return this._onDidChange.event;
        }

        public update(uri: vscode.Uri) {
            this._onDidChange.fire(uri);
        }
    }

    let provider = new TextDocumentContentProvider();
    let registration = vscode.workspace.registerTextDocumentContentProvider('css-preview', provider);

    vscode.workspace.onDidChangeTextDocument((e: vscode.TextDocumentChangeEvent) => {
        if (e.document === vscode.window.activeTextEditor.document) {
            provider.update(previewUri);
        }
    });

    vscode.window.onDidChangeTextEditorSelection((e: vscode.TextEditorSelectionChangeEvent) => {
        if (e.textEditor === vscode.window.activeTextEditor) {
            provider.update(previewUri);
        }
    })

    let disposable = vscode.commands.registerCommand('extension.showCssPropertyPreview', () => {
        return vscode.commands.executeCommand('vscode.previewHtml', previewUri, vscode.ViewColumn.Two).then((success) => {
        }, (reason) => {
            vscode.window.showErrorMessage(reason);
        });

    });
    context.subscriptions.push(disposable, registration);
}

export function deactivate() {
}
```

**Comment by jrieken** [comment]
There is something to uncomment in `ManagedWebview` in _htmlPreviewPart.ts_

**Comment by bpasero** [comment]
Weird, now I don't see it at home. Will check tomorrow at work...

**Comment by jrieken** [comment]
funky. I see it a little when resizing because the webview-body isn't styled, only the iframe. Maybe a resize event got lost - didn't make it to the iframe...

**Comment by bpasero** [comment]
There is another issue where the background color of a webview is always white. I think this got fixed in newer versions of Electron though and might help us: https://github.com/electron/electron/releases/tag/v0.37.3

**Comment by bpasero** [comment]
This seems to be related to the fact that I am running with  `"window.zoomLevel": 1`. Also, once I resize the shell, the white background is filled. Maybe the zoom setting also needs to be applied explicitly to the webview.

**Comment by jrieken** [comment]
This is better with the latest Electron update but initially, when loading the web view I still see a short flicker of white background, no matter if I statically set the background color to transparent or black etc

**Comment by bpasero** [comment]
@jrieken ok, maybe follow up with Electron if you think webview should not have this flicker, I know that for the window itself they did quite some work for me to set the background color very early, even before the DOM gets any chance to set it.

**Comment by jrieken** [comment]
https://github.com/electron/electron/issues/5175

**Comment by jrieken** [comment]
I might be able to workaround this by playing with `visibility` styles...

**Comment by kieferrm** [comment]
This is also an issue for #6106.

**Comment by jrieken** [comment]
Closing since we managed to workaround this using an opacity trick
