### ISSUE TITLE
vscode-insiders can't display chinese

### ISSUE THREAD

**Issue by yakiler** [Microsoft/vscode#50441]
- VSCode Version: 1.24.0-insider 
- OS Version:mac os 10.13.4

Steps to Reproduce:

1. After updating
2.

Does this issue occur when all extensions are disabled?: Yes/No
I am sure that the plugin is open,And correctly set the language selection in the language configuration interface,Finally restarted vscode, But it does not work correctly (display Chinese).I like vscode and look forward to your help

**Comment by 965400059** [comment]
遇见了同样的问题，设置其他语言都有改变，就中文不行

**Comment by yakiler** [comment]
@965400059 我们说中文别人估计不知道说了啥

**Comment by weinand** [comment]
I cannot reproduce this on macOS:

![2018-05-25_11-46-32](https://user-images.githubusercontent.com/1898161/40538277-9241a3aa-6011-11e8-916d-85f11d3b06b1.png)

**Comment by yakiler** [comment]
@weinand  Yes,My first language is Chinese on mac,I also installed vscode and updated to the latest version, the same operation to update the locale to chinese, and then restart it to display Chinese, vscode-insidler still not display Chinese

**Comment by shizengzhou** [comment]
@weinand If I don't install the language pack, VS Code-Insiders can display Simplified Chinese. If I install the language pack and restart Code-Insiders, then Code-Insiders can't display Simplified Chinese.
![2018-05-25 11 17 30](https://user-images.githubusercontent.com/24318019/40552593-c5edbc14-6072-11e8-879e-12e606c22e32.png)
![2018-05-25 11 18 37](https://user-images.githubusercontent.com/24318019/40552612-d689b88e-6072-11e8-8361-f31b92d7896e.png)

**Comment by dbaeumer** [comment]
I can reproduce @shizengzhou problem on Windows as well.

**Comment by dbaeumer** [comment]
German works as well. So there seems to be something specific with Chinese.

**Comment by dbaeumer** [comment]
The cache files that VS Code generates for Chinese are all English. Need to check the extension.

**Comment by dbaeumer** [comment]
@danyeh I tracked this down and the problem is that the language pack on the marketplace is 'empty'. It doesnn't contain any Chinese translated string. We fill up missing strings with English and since all are missing the whole UI is English.

Can you please investigate why the language pack is empty. This is for example the beginning of the main.i18n.json file in the Bulgarian language pack

```
{
	"": [
		"--------------------------------------------------------------------------------------------",
		"Copyright (c) Microsoft Corporation. All rights reserved.",
		"Licensed under the MIT License. See License.txt in the project root for license information.",
		"--------------------------------------------------------------------------------------------",
		"Do not edit this file. It is machine generated."
	],
	"version": "1.0.0",
	"contents": {
		"vs/base/parts/quickopen/browser/quickOpenModel": {
			"quickOpenAriaLabelEntry": "{0}, избор",
			"quickOpenAriaLabel": "избор"
		},
		"vs/base/browser/ui/aria/aria": {
			"repeated": "{0} (случва се отново)"
		},
		"vs/base/browser/ui/findinput/findInput": {
			"defaultLabel": "вход"
		},
		"vs/base/browser/ui/inputbox/inputBox": {
			"alertErrorMessage": "Грешка: {0}",
			"alertWarningMessage": "Предупреждение: {0}",
			"alertInfoMessage": "Информация: {0}"
		},
```

and this the one from Simplified Chinese

```
{
	"": [
		"--------------------------------------------------------------------------------------------",
		"Copyright (c) Microsoft Corporation. All rights reserved.",
		"Licensed under the MIT License. See License.txt in the project root for license information.",
		"--------------------------------------------------------------------------------------------",
		"Do not edit this file. It is machine generated."
	],
	"version": "1.0.0",
	"contents": {
		"vs/base/common/severity": {},
		"vs/base/parts/quickopen/browser/quickOpenModel": {},
		"vs/base/browser/ui/findinput/findInput": {},
		"vs/base/browser/ui/aria/aria": {},
		"vs/base/browser/ui/inputbox/inputBox": {},
		"vs/base/browser/ui/actionbar/actionbar": {},
		"vs/base/parts/tree/browser/treeDefaults": {},
		"vs/base/node/processes": {},
		"vs/base/common/errorMessage": {},
		"vs/base/node/zip": {},
		"vs/base/common/keybindingLabels": {},
		"vs/base/parts/quickopen/browser/quickOpenWidget": {},
		"vs/base/browser/ui/findinput/findInputCheckboxes": {},
		"vs/base/browser/ui/toolbar/toolbar": {},
		"vs/base/browser/ui/selectBox/selectBoxCustom": {},
		"vs/base/common/jsonErrorMessages": {},
		"vs/editor/browser/widget/codeEditorWidget": {},
```

**Comment by dbaeumer** [comment]
IMO this is a must fix. Please let me know if there is anything I can do.

**Comment by dbaeumer** [comment]
For the Core Languages like Chinese it is MS. This is why the issue is assigned to @danyeh

**Comment by danyeh** [comment]
@yakiler @965400059 @shizengzhou , thank you for reporting this issue! This issue was fixed with Chinese language pack 1.24.1. Please update to this new version within VS Code or install from https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans.
The root cause was because we used mismatched language ID when pull translation from Transifex.

**Comment by jerryc127** [comment]
the  issue also appear the chinese traditional.
i have setting in the locale.json to "locale":"zh-tw",
 i also install the  chinese traditional language pack.
it still show the english rather than chinese.

the VSCode Version: 1.25.0-insider
windows 10

**Comment by dbaeumer** [comment]
@jerryc127 I tested this this morning with both traditional and simplified Chinese and they both work for me using the latest language packs from the market place. There was a problem last week with wrongly generated ids. Could you retest it. If it still fails for please open a new issue since the problem described in this one got fixed.
