### ISSUE TITLE
window.withProgress doesn't update properly

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode#50479]
Issue Type: <b>Bug</b>

I've had a heck of a time trying to get window.withProgress to work properly.

```ts
1) Put the following code into a vscode extension project and run it:

    let wait1 = async () => await new Promise((resolve) => { setTimeout(() => { resolve(); }, 1000); });
    let wait2 = async () => await new Promise((resolve) => { setTimeout(() => { resolve(); }, 250); });

    await vscode.window.withProgress(
        {
            location: vscode.ProgressLocation.Notification,
            title: "Test 1: report only increment"
        },
        async (progress) => {
            await wait1();
            for (let i = 0; i < 10; ++i) {
                progress.report({ increment: 10 });
                await wait2();
            }
        });

    await vscode.window.withProgress(
        {
            location: vscode.ProgressLocation.Notification,
            title: "Test 2: report only message"
        },
        async (progress) => {
            await wait1();
            for (let i = 0; i < 10; ++i) {
                progress.report({ message: `message ${i}` });
                await wait2();
            }
        });

    await vscode.window.withProgress(
        {
            location: vscode.ProgressLocation.Notification,
            title: "Test 3: report message and increment, together"
        },
        async (progress) => {
            await wait1();
            for (let i = 0; i < 10; ++i) {
                progress.report({ increment: 10, message: `message ${i}` });
                await wait2();
            }
        });

    await vscode.window.withProgress(
        {
            location: vscode.ProgressLocation.Notification,
            title: "Test 4: report increment then message"
        },
        async (progress) => {
            await wait1();
            for (let i = 0; i < 10; ++i) {
                progress.report({ increment: 10 });
                progress.report({ message: `message ${i}` });
                await wait2();
            }
        });

    await vscode.window.withProgress(
        {
            location: vscode.ProgressLocation.Notification,
            title: "Test 5: report message then increment"
        },
        async (progress) => {
            await wait1();
            for (let i = 0; i < 10; ++i) {
                progress.report({ message: `message ${i}` });
                progress.report({ increment: 10 });
                await wait2();
            }
        });

    await vscode.window.withProgress(
        {
            location: vscode.ProgressLocation.Notification,
            title: "Test 6: small increment"
        },
        async (progress) => {
            await wait1();
            for (let i = 0; i < 200; ++i) {
                progress.report({ increment: .5 });
                progress.report({ message: i.toString() });
                await wait2();
            }
        });
```
RESULTS:

Testcase | Expected | Actual in 1.23.1 | Actual in 1.24.0-insiders
--- | --- | --- | ---
1 |  Progress bar updates | Progress bar stuck at 10%  | GOOD
2 |  Message updates |  GOOD | GOOD
3 |  Progress bar and message update |  GOOD | Progress bar goes too fast
4 |  Progress bar and message update |  GOOD | Progress bar goes too fast
5 |  Progress bar and message update |  Progress bar stuck at 10%, message doesn't update | Message doesn't update
6 |  Progress bar and message update |  Notification disappears after about 40 cycles, even though the loop is still going | Progress bar goes too fast

1.23.1:
![progress-1 23 1](https://user-images.githubusercontent.com/6913354/40562787-4458d914-6017-11e8-9ada-6d9d250cb357.gif)

Insiders: 1.24.0:
![progress-1 24 0-insiders](https://user-images.githubusercontent.com/6913354/40562791-46af9de2-6017-11e8-9e92-c2e3a796bb55.gif)

VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31230 @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (5.53GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
mongogo|bag|0.1.2
regex|chr|0.2.0
vscode-markdownlint|Dav|0.17.0
githistory|don|0.4.1
jupyter|don|1.1.4
tslint|eg2|1.0.29
vscode-bump|fab|1.5.1
docthis|joe|0.6.0
vscode-antlr4|mik|2.0.3
vscode-azureappservice|ms-|0.8.1
vscode-azurefunctions|ms-|0.9.1
vscode-azurestorage|ms-|0.3.1
vscode-cosmosdb|ms-|0.7.1
python|ms-|2018.4.0
azure-account|ms-|0.4.0
csharp|ms-|1.15.2
azurerm-vscode-tools|msa|0.4.2
vscode-versionlens|pfl|0.21.0
yo|sam|0.9.3
extension-api|spy|0.3.0
python|tht|0.2.3
code-lens-roundup|wad|1.0.0

</details>

**Comment by bpasero** [comment]
@StephenWeatherford can you retry these tests against our insiders release where I pushed fixes for the notification progress during this milestone and update the results?

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by StephenWeatherford** [comment]
Insiders build:
Version 1.24.0-insider
Commit bfd155e6039f64d2795c6b514a029ebd01a33527
Datum 2018-05-29T05:16:50.002Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

I still get exactly the results I mention in the table above for Insiders 1.24.0 (i.e., tests 3-6 fail).

**Comment by bpasero** [comment]
I fixed 3, 4, and 6. Since 5 can easily be expressed as a single call, I am keeping this behaviour for now. I do not think a lot of people would hit it. Thanks for the detailed test cases 👍

**Comment by jrieken** [comment]
<img width="608" alt="screen shot 2018-05-31 at 16 28 24" src="https://user-images.githubusercontent.com/1794099/40788164-af9c0386-64ef-11e8-94e9-22c9396cb1a8.png">

Something like case 6 is still broken. This should count till 100

```ts
  await vscode.window.withProgress(
            {
                location: vscode.ProgressLocation.Notification,
                title: "Test 6: small increment"
            },
            async (progress) => {
                await wait1();
                for (let i = 0; i < 100; ++i) {
                    progress.report({ increment: 1 });
                    progress.report({ message: i.toString() });
                    await wait2();
                }
            });
```

**Comment by jrieken** [comment]
Oh, 2 hours ago... Maybe too early...

**Comment by jrieken** [comment]
kinda verified: https://github.com/Microsoft/vscode/issues/50931
