### ISSUE TITLE
Webview: focus tracking not working 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5070]
Open a webview to the side of an editor and try to click left and right editor to switch focus (indicated in the title area). I cannot move focus back to the second editor when clicking into the web view.

For markdown, I had to implement my own focus tracking to make this work: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/iframeEditor.ts#L120

**Comment by jrieken** [comment]
That got fixed by being properly in the dom

**Comment by bpasero** [comment]
There is still an issue when I have the preview in slot 2 and focus is in 1 and I Cmd+2 to pass focus to the webview. Focus does not move over (e.g. keyboard arrow up and down for scrolling does not work in that case).
