### ISSUE TITLE
Cursor Jumps in JavaScript File

### ISSUE THREAD

**Issue by lyndonjohn** [Microsoft/vscode#52167]
Issue Type: <b>Bug</b>

1. Create a JavaScript file
2. Create a function, `function func_name(){ /*some code here*/ }`
3. Type something inside { } and the cursor will jump at the beginning of function

VS Code version: Code - Insiders 1.25.0-insider (777c8e57e0eb1cbffb87a57ffd4f9c3d274f9429, 2018-06-18T05:11:30.274Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.54GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_4670580|
|Screen Reader|no|
|VM|29%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.19.1
bracket-pair-colorizer|Coe|1.0.58
gitlens|eam|8.3.5
vsc-material-theme|Equ|2.1.0
php-intellisense|fel|2.3.3
path-autocomplete|ion|1.10.0
vscode-insertdatestring|jsy|2.2.2
vscode-phpfmt|kok|1.0.30
mssql|ms-|1.3.1
selectline-statusbar|tom|0.0.2
html-css-class-completion|Zig|1.17.1

</details>

**Comment by ggovan** [comment]
I have the same issue, with the same Insiders version on Win10.

**Comment by vvs** [comment]
Yes, this is a critical blocker for me too. The cursor jumps in JavaScript files, jumps in scss file, makes it hard or impossible to write code with this version of Insiders build. Yesterday build is OK.

**Comment by hedleygois** [comment]
It happens in Typescript files as well. Even on a fresh installation.

**Comment by Phunky** [comment]
Also seeing this on OSX

```
1.25.0-insider
777c8e57e0eb1cbffb87a57ffd4f9c3d274f9429
x64
```

Thought I was going made at first :D

**Comment by eleson2** [comment]
+1 on this one.

**Comment by DakshMiglani** [comment]
Yes this happening, not just with java script but with go-lang as well.

**Comment by ljosberinn** [comment]
Same here in TypeScript

> 777c8e57e0eb1cbffb87a57ffd4f9c3d274f9429
> 2018-06-18T05:05:29.526Z

**Comment by eleson2** [comment]
Seems to be solved with latest download. - Thanks!

**Comment by sclausen** [comment]
> Seems to be solved with latest download. - Thanks!

I still have this issue with `1.25.0-1529299329`

**Comment by ljosberinn** [comment]
> I still have this issue with 1.25.0-1529299329

Which OS? Mines fixed with macOS (c51cf862a9604dffe2e3e8792a4b0a45213869a3)

**Comment by lyndonjohn** [comment]
and the latest update (1.25.0-insider) fixed it. 👍

**Comment by tsabolov** [comment]
Still have the issue on Fedora Linux.
Installed via RPM. Filename - code-insiders-1.25.0-1529299489.el7.x86_64.rpm
Settings cog shows badge about available update, but the downloadable is the same as installed one.

**Comment by mflorence99** [comment]
I still have the same issue with Ubuntu Linux. I installed from `code-insiders_1.25.0-1529385749_amd64.deb` but I don't think that file is what it says that it is. I think it is the same as `code-insiders_1.25.0-1529299329_amd64.deb`. I've switched back-and-forth between them and both show this in the about dialog:

```
Version: 1.25.0-insider
Commit: 777c8e57e0eb1cbffb87a57ffd4f9c3d274f9429
Date: 2018-06-18T05:19:20.432Z
Electron: 2.0.2
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
