### ISSUE TITLE
Explorer panels do not retain size

### ISSUE THREAD

**Issue by StickNitro** [Microsoft/vscode#52173]
Issue Type: <b>Bug</b>

I have noticed that while using the various panels in the Explorer sidebar that they do not retain the size that I set them to.

For example switching between sidebars or opening/closing the terminal will resize the panels in the explorer sidebar

[Video demo](https://drive.google.com/file/d/1c7I-kyOg-6Nwc0t1h9rf9be8zgYEbh29/view?usp=sharing)

VS Code version: Code - Insiders 1.25.0-insider (7dc9539a421c9c33e57e2ce0b718f183bb44c756, 2018-06-15T05:12:05.222Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_49164|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-imports|ama|5.1.0
ng-template|Ang|0.1.9
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.32
vscode-npm-script|eg2|0.3.4
auto-close-tag|for|0.5.6
code-runner|for|0.9.3
git-indicators|lam|2.1.1
code-beautifier|mic|2.1.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.6.0
color-highlight|nau|2.3.0
vscode-html-scss|P-d|0.0.42
typescript-hero|rbb|2.3.2
vscode-icons|rob|7.23.0
autoimport|ste|1.5.3
vscode-wakatime|Wak|1.2.2

</details>

**Comment by sandy081** [comment]
Fixed by @joaomoreno in Split view

**Comment by StickNitro** [comment]
I think there is still an issue with this, for example: If you have a bunch of windows open and then close them using the `close all` button then the last explorer panes height adjusts to compensate.  IMO the workspace or folder list should expend to take up any remaining space when any of the other explorer panes height is adjusted

As per this issue, if I close all open editors then whatever the last pane is gets its height adjusted, or opening and closing the outline pane (for example) cause the last pane to get its height adjusted.

Its not a major problem, just a RPITA when all the panes move about and adjust height, my expectation would be that the primary pane (the folder list or workspace) should be the only pane to auto resize when opening and closing any other pane

**Comment by sandy081** [comment]
@StickNitro There is no primary pane concept.. all sections are same and whenever a section is collapsed/expanded/hidden/shown the space is adjust from the panes below it. This makes it consistent and nice.
