### ISSUE TITLE
onDidChangeActiveTerminal doesn't fire (maybe new terminal isn't active)

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#53104]
re #52834 

* have an extension like below
* have a workbench setup that doesn't show the bottom panel on startup
* open/restart workbench -> `activeTerminal: <none>` is printed
* press <kbd>ctrl+`</kbd> to open a terminal
* :bug: no event fires

```ts
'use strict';

import * as vscode from 'vscode';

export function activate (context: vscode.ExtensionContext) {

    function checkActiveTerminal () {
        let { activeTerminal } = vscode.window;
        console.log('activeTerminal: ' + (activeTerminal ? activeTerminal.name : '<none>'));
    }

    checkActiveTerminal();
    vscode.window.onDidChangeActiveTerminal(checkActiveTerminal);

    vscode.commands.registerCommand('extension.sayHello', async () => {
        //
    });
}
```

**Comment by jrieken** [comment]
this might actually be an UX/focus problem because I don't see the cursor... Works as soon as I click into the terminal

**Comment by jrieken** [comment]
Something is off here, the event seems to be unreliable. I have just typed in a terminal without having gotten the active-event

<img width="1283" alt="screen shot 2018-06-27 at 10 46 55" src="https://user-images.githubusercontent.com/1794099/41963323-8da1b4e8-79f7-11e8-95d6-ca63269b9742.png">

**Comment by Tyriar** [comment]
I think this was fixed with the fix for https://github.com/Microsoft/vscode/issues/53107

**Comment by jrieken** [comment]
Still reproduces with insider 07d89abf1522a67f0e8105770505077f454ab021 and the steps above

![jun-28-2018 12-52-02](https://user-images.githubusercontent.com/1794099/42030148-26bdaa1c-7ad2-11e8-8b99-c8fc85c5d433.gif)
