### ISSUE TITLE
PHP defined constrant highlighting broken in SQL

### ISSUE THREAD

**Issue by GeorgeWells** [microsoft/vscode#54166]
- VSCode Version: 1.25.0
- OS Version: Win10

Steps to Reproduce:

1. Create an SQL string in PHP containing a defined constant

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/23452044/42631025-dfdc1ea8-85d0-11e8-819a-0a2120e0ce0e.png)

If I spell the first sql statement keyword incorrectly, it will not highlight any sql keywords (makes sense) but highlighting the defined constant works as intended:

![image](https://user-images.githubusercontent.com/23452044/42631168-3e68e5e6-85d1-11e8-85f3-b2a445667d8b.png)

**Comment by roblourens** [comment]
I think this is fixed upstream. It works in Atom. Will leave it open to see.

**Comment by GeorgeWells** [comment]
Quick update, problem still exists in 1.26.0

**Comment by LPProfit** [comment]
Issue still exists in v1.28.2 Windows 10.

It is also not just for constants:
![image](https://user-images.githubusercontent.com/16726902/48191491-26e74100-e33d-11e8-874c-b1fe3a738aab.png)

`<?

DEFINE("TEST", "Test");
$sql = "SELECT * FROM someTable WHERE text='" . TEST . "'";

$test = "hello";
$sql = "SELECT * FROM someTable WHERE text='" . strtolower($test) . "'";
`

**Comment by roblourens** [comment]
Dupe of https://github.com/microsoft/vscode/issues/44290
