### ISSUE TITLE
Focused panels are not automaticaly maximized

### ISSUE THREAD

**Issue by ymoriaud** [Microsoft/vscode#54382]
Hi !

There is a behavior that changed in latest build: Focused panels are not automaticaly maximized. I was not able to find a settings for that in the preferences. Is that a wanted behavior or a regression ?

I think that behavior changed when grid layout (vertical and horizontal) was added.

- VSCode Version: 1.25.1
- OS Version: Windows 7

Steps to Reproduce:

1. Create multiple splited editors with CTRL+1, CTRL+2, CTRL+3.
1. Reduce panels size
1. When focus a panel, it's not automaticly maximized as before.

New behavior:
Panel 2 is focused, but not maximized.
![image](https://user-images.githubusercontent.com/6912564/42749771-1f7fea6e-88e5-11e8-8800-0bd299c27cf3.png)

Old Behavior:
Panel 2 is focused and maximized.
![image](https://user-images.githubusercontent.com/6912564/42749803-439987de-88e5-11e8-972c-187c766986fc.png)

Does this issue occur when all extensions are disabled?: Yes

Let me know if more information and details are needed.

Thanks !

**Comment by bpasero** [comment]
We fixed this for insiders meanwhile: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_26.md#grid-automated-maximize-of-minimized-editors

You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ymoriaud** [comment]
Thanks @bpasero ! Sorry about the duplicate.

**Comment by TitaneBoy** [comment]
@bpasero Hi..I saw your comment about the fix but since the v1.26.1 of vscode is now released, does it means that this is not fixed for people who has not the vscode Insiders ? In the release note, it is said that this issue is fixed, but it is no said that it's only for Insiders version of vscode.

Thanks in advance for your answer :-)

**Comment by bpasero** [comment]
@TitaneBoy the fix is part of stable release 1.26.x 👍

**Comment by TitaneBoy** [comment]
@bpasero Thanks for the answer...:-)
