### ISSUE TITLE
Source file links in terminal not clickable on some computers

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/vscode#54788]
Issue Type: <b>Bug</b>

I'm noticing a strange behavior when editing a TypeScript project on two different computers. When there are errors, tsc reports them in the integrated terminal using links to the relevant source code lines:
![issue2](https://user-images.githubusercontent.com/17641229/43034777-527cba12-8ce3-11e8-8292-a194a3e7bde0.PNG)

On one of my computers, these get highlighted as links and lead to the referenced code line. On this one they don't. I'm not sure what causes this, as the bug reproduces without extensions.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3403)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (7.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.4.12
gitlens|eam|8.5.2
tslint|eg2|1.0.34
RunOnSave|eme|0.0.16
vscode-language-pack-de|MS-|1.25.2
vscode-docker|Pet|0.0.27
project-snippets|reb|0.5.0
java|red|0.28.0
vscode-coverage-gutters|rya|2.0.1
vscode-java-debug|vsc|0.10.0
vscode-java-pack|vsc|0.3.0
vscode-java-test|vsc|0.7.1
vscode-maven|vsc|0.9.2

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by AlCalzone** [comment]
Sorry it took me so long, but I can still reproduce it in the latest insiders build.
![unbenannt](https://user-images.githubusercontent.com/17641229/43734966-a771546e-99b9-11e8-9998-92087de3f8e2.PNG)

On one machine this gets an underline on hover and is clickable, on my main machine it does not.

**Comment by Tyriar** [comment]
@AlCalzone is src a child of the folder in which the terminal was opened in? The terminal does not track the cwd and only adds links for files relative to the original cwd.

**Comment by AlCalzone** [comment]
Yes it is.

**Comment by AlCalzone** [comment]
At least it is a child of the folder opened in VSCode and I assume this is where the terminal is opened in

**Comment by AlCalzone** [comment]
@Tyriar Anything I can do on my problematic machine to help debug this?
