### ISSUE TITLE
On disable no prompt for nested packs 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#55057]
testing #54862:

I had this setup with two packs, the "debugger" pack used within the "extension" pack:
```
    "name": "777-debugger-pack",
    "extensionPack": [
        "andreweinand.mock-debug",
	"ms-vscode.mono-debug",
        "ms-vscode.cpptools",
        "ms-vscode.csharp",
        "vscjava.vscode-java-debug"
    ]
```
and
```
    "name": "777-extension-pack",
    "extensionPack": [
        "aleksandardev.vscode-sequence-diagrams",
        "pflannery.vscode-versionlens",
        "redhat.java",
        "sysoev.vscode-open-in-github",
        "andreweinand.777-debugger-pack"
    ]
```

- install "777-extension-pack"
- disable "777-debugger-pack" and answer "disable pack" for the prompt

Observe: the "redhat.java" extension (which is not part of the "777-debugger-pack"), gets disabled as well.

On further investigation I found that the Java Debugger "vscjava.vscode-java-debug" is a pack by itself (I do not really understand how they do this because its `package.json` doesn't have an `extensionPack` entry).

I was a bit confused that Java was disabled when my intent was only to disable the debuggers.
I think it is questionable that Java + Debugger are a pack; a dependency would make more sense to me.

But maybe you could prompt for nested packs as well...

**Comment by sandy081** [comment]
@weinand As part of #55055, Disabling or Uninstalling an extension pack only disables or uninstalls packed extensions and do not consider dependencies. Mixing both dependencies and packed extensions here will be confusing. So, I separated them.

Java + Debugger is not a pack now and it has functional dependency set using `extensionDependencies` property.

Fixed by #55055

**Comment by sandy081** [comment]
@weinand `vscjava.vscode-java-debug` is not a pack. It'a java debugger extension that depends on java language server extension

![image](https://user-images.githubusercontent.com/10746682/43231523-093f4a6c-906d-11e8-8bbf-225c5cc88c44.png)

A pack is categorised as `Extension Packs`

![image](https://user-images.githubusercontent.com/10746682/43231487-db369670-906c-11e8-91a3-c42d8b287db3.png)

Previously extension pack also uses `extensionDependencies` property to define extension packs. Only way to differentiate is using category. This is the main reason for confusion. Hence, I introduced new property `extensionPacks` to define extension packs.

After the fix from #55055, Uninstall or disabling your debugger pack will uninstall only the java debugger but not java language server.

**Comment by weinand** [comment]
@sandy081 sorry, but the Java Debugger is a pack.
If I disable it I see this:

![2018-07-26_01-32-30](https://user-images.githubusercontent.com/1898161/43232970-e495f858-9073-11e8-9c6a-a5255671d8b7.png)

It uses the term "pack".

On the other hand, node-debug and node-debug (legacy) are not a "pack" but they use a "extensionDependencies". If I disable one I don't get the prompt like above. If I disable the other I get an error notification.

**Comment by sandy081** [comment]
@weinand Calling it a pack was a mistake (and got introduced in this milestone) which I fixed it in #55055. As in stable, prompt showing disabling or uninstalling an extension with dependencies will only talk about dependencies and not packs. Please check it in latest insiders.

![image](https://user-images.githubusercontent.com/10746682/43249116-24c2000c-90ba-11e8-8fcb-9fdaf353b545.png)

Sorry for the confusion

**Comment by weinand** [comment]
@sandy081 I still don't understand why there is a behavioural difference between the java debugger and the node debugger. Both use `extensionDependencies`:

node-debug:
```json
	"extensionDependencies": [
		"ms-vscode.node-debug2"
	],
```

java-debug:
```
	"extensionDependencies": [
		"redhat.java"
	],
```

But in the former I do not get the prompt whereas in the latter I get the prompt.

**Comment by sandy081** [comment]
Sorry, I forgot to address this point,

It's a bug in the product. Previously we did not support disabling built in extensions and hence disabling an extension that has built in extensions as dependencies was not considering them. It does not makes sense after we started supporting disabling built in extensions. 

So, disabling node debugger should also show a prompt which I fixed now.

**Comment by weinand** [comment]
@sandy081 aha, now the fog clears. Thanks for the explanation.
