### ISSUE TITLE
Settings Editor: Clicking behavior is not consistent

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#55528]
Sometimes when I click on a mega section, it expands, sometimes it doesn't:

![setting-click](https://user-images.githubusercontent.com/4033249/43489448-ea1da476-94d1-11e8-8fea-9e380b082f02.gif)

**Comment by roblourens** [comment]
Related to #55527

**Comment by roblourens** [comment]
Fixed with #54039

**Comment by bpasero** [comment]
I can still reproduce this behaviour. Seamingly random nodes expand or just "bold".

**Comment by roblourens** [comment]
Actually dupe of https://github.com/Microsoft/vscode/issues/57273, fixing there
