### ISSUE TITLE
Settings editor

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#55684]
I ended up in the following state. Nothing in dev tools.

![image](https://user-images.githubusercontent.com/4674940/43597340-a5c6abae-9636-11e8-82db-828c41714390.png)

**Comment by roblourens** [comment]
I fixed an instance of that error, which I see from using the arrow keys on the focused settings list when it's empty. I can't get to that exact screen though with TOC but no settings.

**Comment by octref** [comment]
@roblourens When search query returns 0 items, down key might make it show this notification:

![image](https://user-images.githubusercontent.com/4033249/43606359-f0d1e51e-964f-11e8-94d4-9fac07d4f6af.png)

**Comment by octref** [comment]
I'm on c86cab2211d6dce686e5c89934d915b1e020ba9e

If the query contains 5 items, pressing `down` on the last item would cause this error still.

![image](https://user-images.githubusercontent.com/4033249/43606417-20c58f64-9650-11e8-879b-fc57daac26f0.png)

If the query returns 0 item and you press `down` 5 times and press `up` 5 times, you see both `down` and `up` give this error.

**Comment by roblourens** [comment]
I fixed that this morning

**Comment by octref** [comment]
@roblourens Oops, sorry. I have made the mistake of verifying fresh bugs many times...
