### ISSUE TITLE
"ext install " fails with EACCES error using corporate proxy

### ISSUE THREAD

**Issue by StarNamer** [Microsoft/vscode#5596]
I originally reported this on StackOverflow but it was suggested by Benjamin Pasero that I log this as an issue.

I am working behind a corporate firewall which has outgoing authentication by Active Directory username. When I try the "ext install " command, after a some time I get the message "Error connect EACCES 191.238.172.191:443".

I've tried setting the "http.proxy" value to all variations of FQDN and IP address,both with and without the "http://" prefix and also tried setting "http.proxyStrictSSL" both true and false, always with the same result.

There do not seem to be any settings to specify username and password or any other options for outgoing authentication.
- VSCode 
  Version 1.0.0
  Commit fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
  Date 2016-04-13T14:08:36.599Z
  Shell 0.35.6
  Renderer 45.0.2454.85
  Node 4.1.1
- OS Version:
  Window 10.0.10856 

Steps to Reproduce:

Type
     {ctrl-P}ext{space}install{space}

**Comment by joaomoreno** [comment]
What's your proxy address?

**Comment by StarNamer** [comment]
OK. I tried all the tests again, restarting Code between each one.

1.
    "http.proxy": "http://10.200.68.75:8080/",
    "http.proxyStrictSSL": true
    
Does nothing. Command line closes after a minute or so. No error.

2.
    "http.proxy": "http://proxy2.emr.com:8080/",
    "http.proxyStrictSSL": true

Does nothing. Command line closes after a minute or so. No error.

3.
    "http.proxy": "http://proxy2.emr.com:8080/",
    "http.proxyStrictSSL": false

Does nothing. Command line closes after a few seconds. No error.

4.
    "http.proxy": "http://10.200.68.75:8080/",
    "http.proxyStrictSSL": false

Does nothing. Command line closes after a minute or so. No error.

5.
    "http.proxy": "10.200.68.75:8080",
    "http.proxyStrictSSL": false

There's a blue line repeatedly sliding across under the command line. Then get "Error connect EACCES 191.238.172.191:443"

6.
    "http.proxy": "10.200.68.75:8080",
    "http.proxyStrictSSL": true

There's a blue line repeatedly sliding across under the command line. Then get "Error connect EACCES 191.238.172.191:443"

7.
    "http.proxy": "proxy2.emr.com:8080",
    "http.proxyStrictSSL": true

There's a blue line repeatedly sliding across under the command line. Then get "Error connect EACCES 191.238.172.191:443"

8.
    "http.proxy": "proxy2.emr.com:8080",
    "http.proxyStrictSSL": false

There's a blue line repeatedly sliding across under the command line. Then get "Error connect EACCES 191.238.172.191:443"

Our automatic proxy detection (WPAD) returns either proxy-man.emr.com or proxy-war.emr.com, but currently both are aliases for proxy2.emr.com, hence have address 10.200.68.75

Pinging proxy2.emr.com [10.200.68.75] with 32 bytes of data:
Reply from 10.200.68.75: bytes=32 time=1ms TTL=61

Pinging proxy-war.emr.com [10.200.68.75] with 32 bytes of data:
Reply from 10.200.68.75: bytes=32 time<1ms TTL=61

Pinging proxy-man.emr.com [10.200.68.75] with 32 bytes of data:
Reply from 10.200.68.75: bytes=32 time=1ms TTL=61

Obviously, normal browsing is working fine.

**Comment by joaomoreno** [comment]
Thanks for the many details, let's catch this sucker!

1-4 are the correct syntax: `protocol://host:port`. I have pushed 79b25eaac88479ff0d374d0dba0317f3ba5228f1 which adds a regular expression validator, so you'd get a warning next time you try to configure it like 5-8. 👍 

No error tells me the request is working but the proxy is somehow returning an empty response or similar...

Let's try something else... what happens if you use `"https://10.200.68.75:8080"` and `true`?

**Comment by StarNamer** [comment]
Apologies for the delay. Using `https:` as a prefix (and both `true` and `false`) and the command appears to do nothing. No blue bar, no error message. The command window just closes after a time.

**Comment by StarNamer** [comment]
I just tried version 1.2 with the settings as in 1. above. Still does nothing. Should the newer version have fixed anything?

**Comment by joaomoreno** [comment]
No, the only change we pushed was about warning if the syntax of `http.proxy` was invalid. Unfortunately we still don't have a fix for your issue.

**Comment by jgrumboe** [comment]
Hi,
just tried with latest version 1.10.2 under RHEL7 with everything set: http_proxy/https_proxy as environment variable and in settings.json.
Extentions seem to still ignore these settings. Funny that "check for updates" is using the proxy settings.
Is there still no fix or workaround for this?
thx,
Johannes

**Comment by joaomoreno** [comment]
Closing as a dupe of #22214
