### ISSUE TITLE
Text colors are no longer correct after latest update

### ISSUE THREAD

**Issue by LarsLiden** [Microsoft/vscode#56581]
Issue Type: <b>Bug</b>

I updated to the latest version and the text coloring is no longer correct.   For example "await" usually appear as purple.  Now it sometimes also appears as white.   Another example is "let".  It is sometimes light blue (correct) and at other times white.   (See screen shot)

VS Code version: Code 1.26.0 (4e9361845dc28659923a300945f84731393e210d, 2018-08-13T16:29:31.933Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.85GB (2.49GB free)|
|Process Argv|C:\DevTools\VSCode\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
markdown-preview-github-styles|bie|0.1.2
npm-intellisense|chr|1.3.0
vscode-markdownlint|Dav|0.20.0
tslint|eg2|1.0.34
vscode-npm-script|eg2|0.3.5
vscode-azureappservice|ms-|0.9.0
python|ms-|2018.7.1
azure-account|ms-|0.4.3
debugger-for-chrome|msj|4.8.2
markdown-preview-enhanced|shd|0.3.5
python|tht|0.2.3
vscode-adaptivecards|tom|1.1.3

</details>

![image](https://user-images.githubusercontent.com/6528486/44219516-1013c280-a131-11e8-8418-1e5942415b32.png)

**Comment by aeschli** [comment]
I'm not able to reproduce 

@LarsLiden Can you share the full code example? Maybe there is something special above the line that  causes this?

**Comment by LarsLiden** [comment]
Attached the file.  It's a .ts file, but had to rename it to .txt to upload.   Bad text rendering starts at link 183.   Thanks.
[CLRunner.txt](https://github.com/Microsoft/vscode/files/2297852/CLRunner.txt)

**Comment by mjbvz** [comment]
Seems fixed in current insiders:

![screen shot 2018-08-20 at 3 30 42 pm](https://user-images.githubusercontent.com/12821956/44343388-0c17d580-a48e-11e8-9a43-9d15d96a13cc.png)

**Comment by LarsLiden** [comment]
@mjbvz - I just updated to the new build and I'm still seeing the coloring issue.

Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

![image](https://user-images.githubusercontent.com/6528486/44353410-bcb8b180-a45b-11e8-9e0d-6767512c512a.png)

**Comment by mjbvz** [comment]
Try [insiders](https://code.visualstudio.com/insiders/)

**Comment by LarsLiden** [comment]
ah.  thx!
