### ISSUE TITLE
Regression: TextDocumentContentProvider loses scroll position on update

### ISSUE THREAD

**Issue by bcherny** [Microsoft/vscode#56770]
- VSCode Version: 1.26.1
- OS Version: 10.13.6 (17G65)

Steps to Reproduce:

1. Use a `TextDocumentContentProvider` to render an HTML document
2. Scroll the HTML document
3. Re-render the doucument

Prior to 1.26, scroll position was preserved. Now, it gets lost. This change broke my VSCode extension: https://github.com/bcherny/better-asciidoctor-vscode/issues/5.

**Comment by mjbvz** [comment]
Should be fixed by 8f96f0cf33e25151aa62f0a5da696fb230b759a6

**Comment by bcherny** [comment]
@mjbvz This is still happening on insiders build (29e6dce4352db76d8956035990b8630580226588) - should it be fixed?

**Comment by bcherny** [comment]
@mjbvz Ping to please re-open this. The issue doesn't seem to be fixed.

**Comment by mjbvz** [comment]
Have you tested in the latest insiders? Here's what I see in 2558a72d6902015b142ef45c57b664ce1f09e03f

![sep-24-2018 15-27-42](https://user-images.githubusercontent.com/12821956/45982670-7df3b980-c00e-11e8-8a90-6f405b0ebd47.gif)
