### ISSUE TITLE
Variables window shows incorrect information when variablesRequest returns an error

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#56996]
Raised at https://github.com/Dart-Code/Dart-Code/issues/1148 - a user noticed some weird variables appearing in the Variables window. I can reproduce and it seems like when we return an error from `variablesRequest` VS Code will sometimes populate the Variables list with some stale content (possibly from a previous debug session, or maybe from another call earlier in the same debug session).

Notice the `b` variable inside the `c` variable in the variables list here:

![screen shot 2018-08-22 at 11 49 37 am](https://user-images.githubusercontent.com/1078012/44459480-bc5a1b00-a601-11e8-8334-d79d463dd76e.png)

Here's a log of the responses sent inside `variablesRequest`:

![screen shot 2018-08-22 at 11 49 59 am](https://user-images.githubusercontent.com/1078012/44459504-d4ca3580-a601-11e8-84ea-478b9df42230.png)

You can see the request for the list of variables that returned `a`, `b` and `c`. Then when I expanded `c`, a request was sent for that (`variablesReference: 10`) and I returned an error. However, the variables window did not show an error, it showed some previous content.

**Comment by isidorn** [comment]
I have pushed a potential fix for this can you please try it in tomorrow insdiers.

I believe the issue was the inproper computation of ids for the variables that returned an error, and I believe that broke the tree somehow. Not sure if you saw some errors in the console.

**Comment by DanTup** [comment]
I didn't notice anything in the logs except my own logging of the expression evaluation issue, but if it still repros tomorrow I'll do some more digging, thanks!

**Comment by DanTup** [comment]
Still seeing it in insiders:

07618102efdd63f09949ce54c161e7fd2a954ee8

2018-08-23T05:05:50.261Z

![screen shot 2018-08-23 at 2 42 01 pm](https://user-images.githubusercontent.com/1078012/44528942-c99b0680-a6e2-11e8-963f-53df07df2b10.png)

Anything I can do to get more info to help understand it?

**Comment by DanTup** [comment]
(If you don't mind downloading the Dart SDK and installing the Dart extension you can probably repro locally)

**Comment by isidorn** [comment]
@DanTup sorry but I did not have time to look into this this milestone.
In case you would like to investigate more please put a brekapoint [here](https://github.com/Microsoft/vscode/blob/a614c102847a3a98baf3edcf4962ebb70fdf9a27/src/vs/workbench/parts/debug/common/debugModel.ts#L189)
The `variables` response should return an error and then you can see how the error variable pops up

**Comment by isidorn** [comment]
I have no plans to look into this. @DanTup in case you investigate more and find an issue on our end a PR is more than wlecome. 
Since I have no plans to look into this -> closing

**Comment by DanTup** [comment]
Sorry I haven't chance to try and debug this, I'll try when I'm back in the office. Seems like a fairly nasty bug though, doesn't seem reasonable to close :/
