### ISSUE TITLE
Linux: dialogs are looking broken in the snap package

### ISSUE THREAD

**Issue by HRK44** [Microsoft/vscode#57019]
- vscode version :
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:34:20.517Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- OS Version:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

Steps to Reproduce:

1. Try to move a file from one folder to an other
2. Confirmation modal is buggy

When I hover the buttons, they appear. But as you can see, the modal header has some dark black color.

![screenshot from 2018-08-22 17-37-05](https://user-images.githubusercontent.com/7391040/44474165-4e7a1780-a632-11e8-9f96-8474e3b588e5.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@HRK44 in the 1.26 update we moved to Electron 2.0.x and this brings GTK3 dialogs. Are you maybe using a custom theme in Ubuntu that could have an impact?

**Comment by HRK44** [comment]
@bpasero I haven't changed anything in my Ubuntu setup, just upgraded VS code. What kind of information from my settings would be useful for you?

**Comment by bpasero** [comment]
@HRK44 thanks, we should try to reproduce this with a bare Electron to report it to them. Can you:
* download and install Electron Fiddle (https://github.com/electron/fiddle/releases/download/0.1/electron-fiddle_0.1.0_amd64.deb)
* start it
* pick Show Me > Electron APIs > Dialog
* run it (using the Run button)
* attach a screenshot here how the dialog looks like (it is a file dialog but maybe it shows the same issue)

**Comment by bpasero** [comment]
@HRK44 looks pretty normal to me. Can you:
* close fiddle
* start it again
* add the following line to line 25 of "Main Process" on the left: `dialog.showErrorBox("Hello", "World");`
* run it and show a screen shot of that dialog

**Comment by HRK44** [comment]
@bpasero I put it inside the callback, it wasn't rendering anything outside (line 25).

![screenshot from 2018-08-23 11-04-35](https://user-images.githubusercontent.com/7391040/44516080-6c905800-a6c4-11e8-93ae-b4c79dd75c57.png)

**Comment by bpasero** [comment]
@HRK44 interesting that one looks OK too. Lets try to show the same dialog as the one in code, can you try this dialog instead: `dialog.showMessageBox(mainWindow, { title: 'VSCode', message: 'Some message', button: ["Move"] });`

**Comment by bpasero** [comment]
@HRK44 try with this: `dialog.showMessageBox(mainWindow, { title: 'VSCode', message: 'Some message', detail: "this is some details", buttons: ["Move", "Cancel"], type: "warning", cancelId: 0 }, function() {})`

**Comment by HRK44** [comment]
@bpasero looks fine

![screenshot from 2018-08-23 11-47-11](https://user-images.githubusercontent.com/7391040/44518369-58e7f000-a6ca-11e8-9600-b89f7a0ef0bb.png)

**Comment by HRK44** [comment]
@bpasero dialog shows fine

![screenshot from 2018-08-23 12-32-06](https://user-images.githubusercontent.com/7391040/44520618-a49d9800-a6d0-11e8-8c83-2e9b398fd5fd.png)

**Comment by bpasero** [comment]
@HRK44 wow, I am out of ideas on this one. Is there anything logged to VSCode console (run with `code --verbose`) when the dialog opens?

**Comment by HRK44** [comment]
More logs :
![screenshot from 2018-08-23 13-51-19](https://user-images.githubusercontent.com/7391040/44523877-cd775a80-a6db-11e8-829e-d9c37d9f10f0.png)

ESC[90m[main 1:50:46 PM]ESC[0m windowsService#showMessageBox 1
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[19768:0823/135046.951999:WARNING:browser_main_loop.cc(275)] Gtk: Error loading image 'file:///usr/share/themes/Ambiance/gtk-3.0/assets/backdrop-check-unselected.png': Unable to load image-loading module: /usr/l
ib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[19768:0823/135046.952045:WARNING:browser_main_loop.cc(275)] Gtk: drawing failure for widget 'GtkCheckButton': invalid matrix (not invertible)
[19768:0823/135046.952054:WARNING:browser_main_loop.cc(275)] Gtk: drawing failure for widget 'GtkBox': invalid matrix (not invertible)
[19768:0823/135046.952060:WARNING:browser_main_loop.cc(275)] Gtk: drawing failure for widget 'GtkBox': invalid matrix (not invertible)
[19768:0823/135046.952065:WARNING:browser_main_loop.cc(275)] Gtk: drawing failure for widget 'GtkBox': invalid matrix (not invertible)
[19768:0823/135046.952071:WARNING:browser_main_loop.cc(275)] Gtk: drawing failure for widget 'GtkMessageDialog': invalid matrix (not invertible)
[19768:0823/135046.985482:WARNING:browser_main_loop.cc(275)] Gtk: Error loading image 'file:///usr/share/themes/Ambiance/gtk-3.0/assets/check-unselected.png': Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[19768:0823/135046.986894:WARNING:browser_main_loop.cc(275)] Gtk: drawing failure for widget 'GtkCheckButton': invalid matrix (not invertible)
[19768:0823/135046.987664:WARNING:browser_main_loop.cc(275)] Gtk: drawing failure for widget 'GtkBox': invalid matrix (not invertible)
[19768:0823/135046.987972:WARNING:browser_main_loop.cc(275)] Gtk: drawing failure for widget 'GtkBox': invalid matrix (not invertible)
[19768:0823/135046.987990:WARNING:browser_main_loop.cc(275)] Gtk: drawing failure for widget 'GtkBox': invalid matrix (not invertible)
[19768:0823/135046.987997:WARNING:browser_main_loop.cc(275)] Gtk: drawing failure for widget 'GtkMessageDialog': invalid matrix (not invertible)



![screenshot from 2018-08-23 13-52-02](https://user-images.githubusercontent.com/7391040/44523879-cf411e00-a6db-11e8-9066-2281c4ef5c4f.png)

[19768:0823/135133.139056:WARNING:browser_main_loop.cc(275)] Gtk: Error loading image 'file:///usr/share/themes/Ambiance/gtk-3.0/assets/button-default-focused-hover.png': Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[19768:0823/135133.450674:WARNING:browser_main_loop.cc(275)] Gtk: Error loading image 'file:///usr/share/themes/Ambiance/gtk-3.0/assets/button-hover.png': Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /snap/core/current/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[19768:0823/135142.326246:INFO:CONSOLE(1397)] "%cTRACE", source: file:///snap/vscode/51/usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1397)
[19768:0823/135142.349043:WARNING:x11_util.cc(1353)] X error received: serial 5458, error_code 3 (BadWindow (invalid Window parameter)), request_code 3, minor_code 0 (X_GetWindowAttributes)
[19768:0823/135142.355870:INFO:CONSOLE(1397)] "%cTRACE", source: file:///snap/vscode/51/usr/share/code/resources/app/out/vs/workbench/workbench.main.js (1397)

**Comment by bpasero** [comment]
@HRK44 good one, I think this is because we are using a PNG icon for the dialog and that seems to break the dialog. Can we try that with the `electron-fiddle` again, this time using an icon:

` mainWindow = new BrowserWindow({ width: 800, height: 600, icon: '/home/ticino/Desktop/code.png' })`

and the icon being:

![code](https://user-images.githubusercontent.com/900690/44524055-67d79e00-a6dc-11e8-92fb-f458399a55ef.png)

**Comment by HRK44** [comment]
@bpasero it works fine with the png icon.

It might have something to do with this issue : https://forum.snapcraft.io/t/skype-exits-when-trying-to-add-a-file-to-a-chat/6138/8

**Comment by bpasero** [comment]
@HRK44 I believe that issue is rather due to the ArchLinux OS (see https://github.com/Microsoft/vscode/issues/55934). 

Would you be able to fix the ZLIB_1.2.9 issue to see if that helps? Sounds like a missing dependency to me?

**Comment by HRK44** [comment]
@bpasero I tried some stuff but couldn't manage to successfully update this ZLIB without creating a bunch of system issues, if someone with more advanced skills in Linux would try that'd be great.

**Comment by HRK44** [comment]
I just re-installed VS Code via ``apt`` and removed it from ``snap`` (actually I completely removed ``snap``...) and now it works correctly.

**Comment by Tyriar** [comment]
@HRK44 thanks!

FYI @flexiondotorg

**Comment by diddledan** [comment]
For reference, the issue is not due to an incorrect zlib version suggested above. The problem is due to the snap accidentally referencing system libraries instead of it's own. This manifests with vscode loading the libgdk-pixbuf-loader library from the system, which is compiled against a different zlib than the one within the snap's files. The solution, therefore, is not to mess about trying to change the zlib version but to determine why it is using the system libraries in the first place.

I'll try to look at it tomorrow, or @popey or @flexiondotorg might beat me to it.

**Comment by anied** [comment]
Any chance on getting a status update on this issue?  I am facing the same thing.  It would be no great hardship to try [HRK44's solution](https://github.com/Microsoft/vscode/issues/57019#issuecomment-415797321) but if there's any hope of seeing this resolved in the near-term I'd just as soon stick with the snap.

**Comment by BjoernDaase** [comment]
Today, I got VSCode version 1.32.3 and the bug seems to be fixed!

**Comment by sdc395** [comment]
Whereas 1.32.3 is the first version I've noticed has this problem.  I reverted to 1.31.1 (I'm using Snap, by the way) and the problem went away.  I then refreshed back to 1.32.3 and the problem returned.

**Comment by joaomoreno** [comment]
Thanks to @flexiondotorg, this is now fixed in `master`! https://github.com/Microsoft/vscode/pull/70884

**Comment by sdc395biosite** [comment]
Still broken having removed Snapcrafter's vscode snap and installed code 1.33. :-(
