### ISSUE TITLE
File Search - Prioritise File Path Match Over Fuzzy

### ISSUE THREAD

**Issue by mitchsatchwell** [Microsoft/vscode#5720]
- VSCode Version: 1.0.0
- OS Version: Windows 7

Steps to Reproduce:
1. Open 'Go to File' (ctrl + p)
2. Type in the path of a file that also results in fuzzy matches.

![fuzzy](https://cloud.githubusercontent.com/assets/16648158/14769537/d258430c-0a52-11e6-8469-0759f17b7623.png)

Currently filepath matches are not prioritised over fuzzy matches, making it difficult to find what you are looking for when dealing with a large number of files. 

Potentially this is related to not handling filepaths/slashes correctly. If I replace the slash with an asterisk in the above example (i.e. 'includes*functions.php' rather than 'includes/functions.php') this file then becomes the top result.

**Comment by bpasero** [comment]
This got fixed in https://github.com/Microsoft/vscode/issues/3818

You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

**Comment by AndrewRayCode** [comment]
This is not fixed. Adding a path before a file makes the search worse, not better.

![screen shot 2017-02-17 at 2 58 18 pm](https://cloud.githubusercontent.com/assets/79215/23086402/8fe7d482-f521-11e6-9f81-9a1444dd197f.png)

Even when the file name and folder name are matched exactly:

![screen shot 2017-02-17 at 2 58 05 pm](https://cloud.githubusercontent.com/assets/79215/23086432/9d5a99a6-f521-11e6-8515-55d1c83e78c9.png)

Version 1.9.1 (1.9.1)
