### ISSUE TITLE
Foregound Color on Modals and Popups not respecting newly selected theme

### ISSUE THREAD

**Issue by imoby** [Microsoft/vscode#58216]
- VSCode Version: 1.27.1
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Select a different theme other than dark+ that has themed the foreground different than the default color (example is the shades of purple theme)
2. Set that as the theme and reload vscode
3. Open command palette and attempt to change to new theme
4. Observe that even after selecting a new theme or navigating the themes list, the foreground of the current theme color is being selected instead of the new one or default one

Does this issue occur when all extensions are disabled?: Yes

Images:
![first](https://user-images.githubusercontent.com/6380855/45240312-ce001b80-b2ad-11e8-8c07-1a5f3891d4e1.png)
![issue](https://user-images.githubusercontent.com/6380855/45240304-c6d90d80-b2ad-11e8-9511-879fbe154cc9.png)

**Comment by aeschli** [comment]
@imoby Thanks a lot for reporting, I've seen something similar, but I'm not able to reproduce with your steps. What theme is that?
Did you by chance define any color customizations in your settings, like:
```json
    "workbench.colorCustomizations": {
		"foreground": "#ff00ff"
	}
```

**Comment by aeschli** [comment]
I pushed a fix for what I believe is the problem. Maybe you can try in an insider build if this fixed it for you

**Comment by imoby** [comment]
@aeschli the issue is still existing even in the latest insiders version:

<img width="604" alt="issue still" src="https://user-images.githubusercontent.com/6380855/45465011-d6ef5380-b6d8-11e8-9e22-b7ba60a8249a.png">

**Comment by imoby** [comment]
@aeschli heres a link to a gif on how to reproduce it https://d.pr/i/PK3oZb
