### ISSUE TITLE
Json validation fails on oneOf with only const

### ISSUE THREAD

**Issue by mrmydt** [Microsoft/vscode#58765]
- VSCode Version: 1.27 
- OS Version: MacOS 10.13.6 & Windows 10

Steps to Reproduce:

1. With the following json_schema:
`{
    "$schema": "http://json-schema.org/draft-07/schema",
    "definitions": {
        "choice_of_const": {
            "oneOf": [
                {
                    "const": 0,
                    "title": "Value of 0"
                },
                {
                    "const": 1,
                    "title": "Value of 1"
                },
                {
                    "const": 2,
                    "title": "Value of 2"
                }
            ]
        },
        "choice_of_enum": {
            "oneOf": [
                {
                    "enum": [0],
                    "title": "Value of 0"
                },
                {
                    "enum": [1],
                    "title": "Value of 1"
                },
                {
                    "enum": [2],
                    "title": "Value of 2"
                }
            ]
        }
    },
    "type": "object",
    "properties": {
        "const_choice": {
            "$ref": "#/definitions/choice_of_const"
        },
        "enum_choice": {
            "$ref": "#/definitions/choice_of_enum"
        }
    }
}`

2. Validate this json against the above schema 
`{
    "const_choice": 3,
    "enum_choice": 3
}`

3. Result: const_choice shows no validation error while it should. enum_choice shows correctly a validation error.

4. Mouse over const_choice shows "value of 0" regardless of the value you give. It can be another type or a valid other value, it will always return the first item in the array

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
fixed by https://github.com/Microsoft/vscode-json-languageservice/commit/0e5a7e00bd2549678b14801c8c0cf78416c10564

**Comment by sbatten** [comment]
In this is example, validation errors now show up but item 4 still persists

> Mouse over const_choice shows "value of 0" regardless of the value you give. It can be another type or a valid other value, it will always return the first item in the array

**Comment by aeschli** [comment]
The hover is unfortunate but as designed. When looking for a hover, the best alternative is chosen. In this example, they are all equally bad, so it's just the first one.
We pick one and can then can provide code completions and hovers for all properties inside the picked one (there are no such properties in this example, but normally there would be)
