### ISSUE TITLE
Incorrect comment format for HTML

### ISSUE THREAD

**Issue by SFoskitt** [Microsoft/vscode#59854]
Issue Type: <b>Bug</b>

VSCode recognizes this file as HTML but comments appear as Javascript like // instead of  using keyboard combo Cmd + /  (on Mac).  Keyboard mappings in VSCode are verified as "Toggle Line Comment".   THE WEIRD PART - it only does this on ONE file.  One *.html file. 

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:04:11.329Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by RMacfarlane** [comment]
Could you share the text of the HTML file this happens for?

**Comment by SFoskitt** [comment]
Hi, @RMacfarlane -
Github will not allow upload/attach of file type HTML so I have copied/pasted the content here.  I get Javascript comments no matter which line(s) are selected (even the `<br/>` lines).
- Stephanie


`<!DOCTYPE html>
<html>
  <head>
    <script>var year = new Date().getFullYear()</script>
  </head>
  <body>
    <h5 class="copy"> &copy; <script>document.write(new Date().getFullYear());</script> </h5>

    <script>document.write(new Date().getFullYear());</script>

    
    <div id="widget-wrap-main" style="width: 100%">
      <script>
        (function(document, window){
          var ws = document.createElement('script');
          ws.id = 'bri-widget';
          ws.type = 'text/javascript';
          ws.src = '//localhost:7474/review/814.js';
          ws.async = !0;
          document.body.appendChild(ws);
        }(document, window));
      </script>
    </div>

    
    <div id="widget-wrap-main-carousel-rating" style="width: 75%"> 
      <script>
        (function(document, window){
          var ws = document.createElement('script');
          ws.id = 'bri-widget';
          ws.type = 'text/javascript'; 
          ws.src = '//localhost:7474/review/814.js';
          ws.async = !0;
          document.body.appendChild(ws);
        }(document, window));
      </script>
    </div>
  
    
    <div id="default-widget-wrap-main-both" style="width: 75%">
      <script>
        (function(document, window){
          var ws = document.createElement('script');
          ws.id = 'bri-widget';
          ws.type = 'text/javascript';
          ws.src = '//localhost:7474/review/814.js';
          ws.async = !0;
          document.body.appendChild(ws);
        }(document, window));
      </script>
    </div>
    <div>
      <a href="\sipStagingP2.html">Page 2</a>
      <br/>
      <a href="\sipStagingP3.html">Page 3</a>
      <br/>
      <a href="\sipStagingP4.html">Page 4</a>
      <br/>
      You are looking at a page with STAGING SIP SIP SIP!!!!<BR>

      TESTING NOTES:<BR>
      <BR>
      NOT WORKING AS EXPECTED ???<BR>
      REMEMBER, LOAD THIS PAGE AS MOBILE!!!!<BR>


         Site abandonment

        <A NAME="top">

        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
      1<br/>
      2<br/>
      3<br/>
      4<br/>
      5<br/>
      6<br/>
      7<br/>
      8<br/>
      9<br/>
      10<br/>

      test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
      11<br/>
      12<br/>
      13<br/>
      14<br/>
      15<br/>
      16<br/>
      17<br/>
      18<br/>
      19<br/>
      20<br/>
      test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
      21<br/>
      22<br/>
      23<br/>
      24<br/>
      25<br/>
      26<br/>
      27<br/>
      28<br/>
      29<br/>
      30<br/>
      test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
      31<br/>
      32<br/>
      33<br/>
      34<br/>
      35<br/>
      36<br/>
      37<br/>
      38<br/>
      39<br/>
      40<br/>
      test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
      41<br/>
      42<br/>
      43<br/>
      44<br/>
      45<br/>
      46<br/>
      47<br/>
      48<br/>
      49<br/>
      50<br/>
      test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>

        MIDDLE - MIDDLE - MIDDLE <br/>
          MIDDLE - MIDDLE - MIDDLE <br/>
          MIDDLE - MIDDLE - MIDDLE <br/>
          MIDDLE - MIDDLE - MIDDLE <br/>

      <A HREF="#top">Back To Top</A> <br/>

        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
      1<br/>
      2<br/>
      3<br/>
      4<br/>
      5<br/>
      6<br/>
      7<br/>
      8<br/>
      9<br/>
      10<br/>
      test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
      11<br/>
      12<br/>
      13<br/>
      14<br/>
      15<br/>
      16<br/>
      17<br/>
      18<br/>
      19<br/>
      20<br/>
      test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
      21<br/>
      22<br/>
      23<br/>
      24<br/>
      25<br/>
      26<br/>
      27<br/>
      28<br/>
      29<br/>
      30<br/>
      test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
      31<br/>
      32<br/>
      33<br/>
      34<br/>
      35<br/>
      36<br/>
      37<br/>
      38<br/>
      39<br/>
      40<br/>
      test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
      41<br/>
      42<br/>
      43<br/>
      44<br/>
      45<br/>
      46<br/>
      47<br/>
      48<br/>
      49<br/>
      50<br/>

        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>
        test!! TEST ! TEST! <br/>


          END - END - END - END <br/>
          END - END - END - END <br/>
          END - END - END - END <br/>
          END - END - END - END <br/>
          END - END - END - END <br/>
          END - END - END - END <br/>


      <A HREF="#top">Back To Top</A> <br/>

      <form action="#" method="post">
    <div>
         <label for="name">Text Input:</label>
         <input type="text" name="name" id="name" value="" tabindex="1" />
    </div>

    <div>
         <h4>Radio Button Choice</h4>

         <label for="radio-choice-1">Choice 1</label>
         <input type="radio" name="radio-choice-1" id="radio-choice-1" tabindex="2" value="choice-1" />

     <label for="radio-choice-2">Choice 2</label>
         <input type="radio" name="radio-choice-2" id="radio-choice-2" tabindex="3" value="choice-2" />
    </div>

  <div>
    <label for="select-choice">Select Dropdown Choice:</label>
    <select name="select-choice" id="select-choice">
      <option value="Choice 1">Choice 1</option>
      <option value="Choice 2">Choice 2</option>
      <option value="Choice 3">Choice 3</option>
    </select>
  </div>

  <div>
    <label for="textarea">Textarea:</label>
    <textarea cols="40" rows="8" name="textarea" id="textarea"></textarea>
  </div>

  <div>
      <label for="checkbox">Checkbox:</label>
    <input type="checkbox" name="checkbox" id="checkbox" />
    </div>

  <div>
      <input type="submit" value="Submit" />
    </div>
</form>
</body>
</html>
`

**Comment by RMacfarlane** [comment]
Thanks @SFoskitt! I'm able to reproduce the problem using VSCode 1.27.2.

It looks like this has already been fixed in the Insider's version of VSCode, 1.28.0. You can download it here: https://code.visualstudio.com/insiders/, or wait for the release later this week.

**Comment by mjbvz** [comment]
Hey I'm still seeing this in 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9

Moving out to October. @aeschli can you please take a look

**Comment by aeschli** [comment]
It's a grammar / textmate issue.
`<script>var year = new Date().getFullYear()</script>`

The grammar thinks `<` is an operator for the expression and continues to parse the rest of the file as JavaScript.

The problem is that JavaScript grammar is not aware that it is used embedded. The best way would be if HTML includes its own grammar for embedded JavaScript: https://github.com/textmate/html.tmbundle/issues/85

Embedded languages are a known weakness of TextMate. We have https://github.com/Microsoft/vscode/issues/20488 as dept item for this.

@SFoskitt I don't see a fix coming for this in the near future. As a workaround you can get things working again by adding a semicolon to the line mentioned:
`<script>var year = new Date().getFullYear();</script>`

Clsoing this issue as a duplicate of the issues mentioned above.
