### ISSUE TITLE
References to deleted files remain in 'Problems' panel

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#61773]
Issue Type: <b>Bug</b>

Open a project. 
Create a 'problem' in a file.
Display the 'Problems' panel.
Delete said file.
Note 'Problems' panel does not update.
Refresh the 'Explorer' project tree view.
Note 'Problems' panel still does not update.

![image](https://user-images.githubusercontent.com/512816/47482196-2081a100-d836-11e8-9429-c85ea7fb5eb1.png)

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (9.08GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.1.0
vscode-markdownlint|Dav|0.20.0
tslint|eg2|1.0.40
vscode-ionic-snippets|fiv|0.5.3
vscode-scss|mrm|0.6.2
subtitles-editor|pep|1.0.1

</details>

**Comment by jwhitmarsh** [comment]
Having the same issue on macOS, and just tested the latest insiders build and can replicate there too. 

VS Code versoin 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850)
OS vesrion: macOS 10.13.6

**Comment by leegee** [comment]
This issue is about inaccuracies in the Problems panel, whereas it seems the issue to which you link is about showing/hiding the Problem panel.

**Comment by mjbvz** [comment]
Duplicate of #59363

**Comment by leegee** [comment]
The ticket you marked this a duplicate of seems to be about closing files -- my report is about deleted files.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled? I can't repo this

**Comment by mjbvz** [comment]
Also is there a `(deleted from disk)` file still open in your editor like in #58088

**Comment by jwhitmarsh** [comment]
I've just re-tested in latest insiders, with all extentions disabled, and it still occurs. Here's a gif:

![oct-28-2018 09-40-41](https://user-images.githubusercontent.com/8026009/47614299-a64f5780-da95-11e8-9a7d-6ac04f9296f5.gif)

**Comment by CharlieEtienne** [comment]
I think it's not related to javascript as I have this problem on deleted php files.

**Comment by mjbvz** [comment]
I'm unable to reproduce this issue anymore. I suspect this is a duplicate of #58088 that was fixed a few releases back.

Please let me know if you still see this when following the original repo steps

**Comment by leegee** [comment]
Fixed - thank you!

**Comment by kokoshneta** [comment]
The error is still there for me in the latest stable version (1.33.1) on OS X. Was this fixed in a newer version that hasn’t been released as stable for OS X yet?

The red color and dot on the containing folder also remains, even after refreshing the Explorer.

Restarting Code fixes it, as does closing the Workspace and then reopening it – but nothing less dramatic than that seems to fix it.
