### ISSUE TITLE
the status is still "initializing JS/TS language features", cannot do other things(eg. "Go to Definition)

### ISSUE THREAD

**Issue by kfy90hw** [Microsoft/vscode#62638]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code.

**Comment by kfy90hw** [comment]
![image](https://user-images.githubusercontent.com/36940715/48047769-1b2c3b00-e1d4-11e8-8476-dc76a32aef0b.png)

**Comment by Alan-Solitar** [comment]
Also having this issue.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by kfy90hw** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

yes, the version of my vscode is 1.28.2

**Comment by Magnamura** [comment]
Same issue here.
Fresh install with only one Theme and one Icon Set as Extensions.

Version: 1.28.2 (system setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by kfy90hw** [comment]
he reason may be that we can't download packages from the inner npm-registry. The problem was solved after the npm-registry changed. Thank you

**Comment by Wqrld** [comment]
Still happens on the latest post (atleast its taking around 2 minutes to load)

**Comment by JofBigHealth** [comment]
I had the same issue and I note that when I restarted I was given the release notes to the October release. (The issue went away on restart). This is despite having already updated to the latest releaser some days ago, not having updated since and having closed the previous release notes.

**Comment by younes0** [comment]
Same issue
Maybe related: #61636

**Comment by hundsim** [comment]
Same here - it's stuck on "initializing JS/TS language features" on startup.

Version 1.29.1

**Comment by carestad** [comment]
Same in 1.29.1. The whole application window also flickers, as if there is something wrong with my monitor, but it is quite clearly only the vscode window, and it stops when closing the application. Re-starting it usually works, and the `Initializing JS/TS langage features` just takes a few seconds on the second try. Still, rather annoying though.

**Comment by Wqrld** [comment]
@mjbvz Can you remove the "not reproducible" tag as quite a lot of people seem to share this issue

**Comment by mjbvz** [comment]
@Wqrld Open a new issue

**Comment by Wqrld** [comment]
> @Wqrld Open a new issue

I am willing to do that although i do not see a reason why as this currently is the one to be found on google etc?

**Comment by hhlevnjak** [comment]
Having the same problem here. When I first open VS Code it can be stuck at that initializing state for 5-10 minutes, killing my CPU in the meantime.

After restarting VS Code it's usually faster.

Same version 1.29.1.

I had another VS Code window open with a PHP project before I opened the JS project which got stuck initializing, if it's a caching issue and helps you reproduce it.

**Comment by dotpointer** [comment]
Got the same issue when opening a JS file from the left panel file lists, it starts chewing "initializing JS/TS language features" which never seems to stop and it causes high CPU.

Found a workaround here to disable these "features":
https://github.com/Microsoft/vscode/issues/54261

The workaround, which as mentioned also disables some built-in linting:
> Go to Extension view, search for @builtin javascript, and disable TypeScript and JavaScript Language Features

**Comment by joseds** [comment]
I have the same issue with 1.29.1 as well as 1.30.0-insider, the "initializing JS/TS language feature" loading indicator stays put indefinitely. Disabling the @Builtin JavaScript / TypeScript extensions is no option for me since I lose syntax highlighting.

**Comment by vigilantee-seek** [comment]
Also the same issue. The "initializing JS/TS language feature" loading indicator circles infinitely.

**Comment by dotpointer** [comment]
No problem since I disabled it 6 days ago. Will keep it disabled.

**Comment by mjbvz** [comment]
Please open new issues instead of posting here.

Disabling the build-in `JavaScript/TypeScript language features` extension is **not** a good solution (unless you are never working with JavaScript or TypeScript or have installed the flow extension). Disabling that extension will disable JavaScript and TypeScript language features such as IntelliSense, so—while you aren't going to see any `initializing...` messages in your status bar—all you'll have is basic text editor support for js/ts
