### ISSUE TITLE
Mouse selection lagging behind

### ISSUE THREAD

**Issue by thany** [Microsoft/vscode#62790]
Issue Type: <b>Performance Issue</b>

When selecting text using the mouse, the selection is noticably lagging behind the the mouse cursor. Almost to the point of it being confusing to select a large passage of text. It's that split second in your head when a voice tells you "woh, did that get selected or not? oh, it did" that pulls you away from being focused.

The problem is especially noticable when selecting multiple lines. Which programming language is used, doesn't seem to make any difference.

I'm on a Core i9-8950HK, which is a bloody fast mobile hexacore, paired with 32GB memory. I shouldn't run into *any* performance issues with a setup like that 😃

I tried making a video using the built-in Game Bar, but it doesn't record the mouse cursor while selecting text. Darn 🤨

VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.74GB (16.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    84	 20048	code main
    0	    65	 20276	   shared-process
    0	    70	 21432	   window (Issue Reporter)
    0	   287	 21680	   gpu-process
    0	   200	 21804	   window (_tabs.scss - static - Visual Studio Code)
    0	    37	  4412	     searchService
    0	   107	 14840	     extensionHost
    0	    70	  8908	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain" --node-ipc --clientProcessId=14840
    0	   126	 19864	       electron_node tsserver.js 
    0	    45	 20452	         electron_node typingsInstaller.js typesMap.js 
    0	    36	 20848	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\cssServerMain" --node-ipc --clientProcessId=14840
    0	    32	 21160	       electron_node eslintServer.js 
    0	    14	 18656	     watcherService 
    0	    10	 18124	       console-window-host (Windows internal process)
    0	    13	 19432	     electron-crash-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (_tabs.scss - static - Visual Studio Code)
|    Folder (static): 1292 files
|      File types: html(316) js(294) mustache(274) json(133) scss(89) md(58)
|                  svg(21) gitignore(15) css(9) png(8)
|      Conf files: package.json(8) gulp.js(5) grunt.js(3) makefile(1);
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|9.2.0
html-class-suggestions|And|1.0.7
color-info|bie|0.5.0
mustache|daw|1.1.1
vscode-eslint|dba|1.7.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.5
file-icons|fil|1.0.16
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
duplicate|gee|1.0.1
svgeditor|hen|2.7.0
beautify|Hoo|1.4.7
docthis|joe|0.7.1
vscode-duplicate|mrm|1.2.1
vscode-docker|Pet|0.3.1
code-settings-sync|Sha|3.2.0
rewrap|stk|1.9.1

</details>

**Comment by jrieken** [comment]
Pease try to CPU profile this. Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.

<img width="380" alt="screen shot 2017-09-28 at 09 44 31" src="https://user-images.githubusercontent.com/1794099/30954796-d1be9e30-a431-11e7-959e-495d234c37c6.png">

**Comment by thany** [comment]
I hope this profile contains what you need to diagnose the problem, so here it is:
[CPU-20181109T121134.zip](https://github.com/Microsoft/vscode/files/2565604/CPU-20181109T121134.zip)

**Comment by jrieken** [comment]
Does this reproduce without extensions, try with `code --disable-extension` and see if it feels faster

**Comment by alexandrudima** [comment]
@thany From looking at the profile, there is nothing that seems out of place. Everything is pretty fast, handling the mouse move event takes ~5-6ms and then painting the next frame is quite fast at 3.3ms. Can you try to disable extensions and to comment out your settings to see if there is something special about your configuration/extensions that could be causing this.

**Comment by jrieken** [comment]
This might also be https://github.com/Microsoft/vscode/issues/62829#issuecomment-437314957. When having leaked many listeners, than selection changes (which is a context key change) will fire many, many events. 

@thany We have fixed an important issue in latest insiders. Please try that: https://code.visualstudio.com/insiders/

**Comment by thany** [comment]
With extensions disabled and all my settings commented away, the problem is still there, and exactly as noticable.

**Comment by thany** [comment]
Okay, I made another profile. I'm just selecting text here. I also noticed my fan spinning, which means it's using a LOT of cpu horsepower. Selecting text doesn't (or shouldn't) need that much math to go through.

Anyway, here it is: 
[CPU-20181114T103337.zip](https://github.com/Microsoft/vscode/files/2580048/CPU-20181114T103337.zip)

**Comment by alexandrudima** [comment]
@thany Again, this CPU profile does not reveal anything, so I believe the problem is not in our JS code, but perhaps is environmental:
* maybe a weird user data dir state (can be ruled out by trying the insiders version)
* maybe a GPU issue (you can try code --disable-gpu)
* maybe some other piece of software on your machine
* maybe some other yet not understood cause

I agree you should not have any performance issues at all given your hardware.

But, from looking at the JS profile, there does not appear to be anything out of place.

**Comment by thany** [comment]
Disabling GPU rendering makes it feel brilliant! It's completely responsive now. Wow.

That is weird, I though we had GPU rendering nailed by now... Oh well.

It probably helps to know, I'm on a Intel UHD Graphics 630, paired with a GTX 1050. In the task manager, I can see that Code is running on GPU 0 (which I think is the Intel one).

**Comment by alexandrudima** [comment]
@thany The GPU rendering is handled by Chromium. We are now using Chromium 61. That was feature-frozen on 23rd Jun 2017, which is ... ancient history by now. It is unfortunate, but newer hardware can end up in this state where Chromium has issues with it, Chromium has probably addressed those issues in the meantime, but it takes us some time until Electron adopts a newer version of Chromium and until we adopt a newer version of Electron.

I think `nVidia` had a Control Panel entry where you can configure it to be used for certain process names. By default, it gets used for games and other such things, but I'm sure you can add to that list.

Given there is no code change we can do on our side to improve this, and given this will probably work itself out once we adopt a newer version of Electron, I am opting to close this issue for now.

**Comment by thany** [comment]
Is it possible to pass this issue on to Electron?

**Comment by alexandrudima** [comment]
@thany If you are able to reproduce this slowness in Chrome, I'm sure they'd want to hear about it. You can try in the same editor as VS Code at https://microsoft.github.io/monaco-editor/
