### ISSUE TITLE
Very slow serach after last update

### ISSUE THREAD

**Issue by Kcko** [Microsoft/vscode#63026]
See video pls: http://bit.ly/2zPHthX
Search takes a long time (20-30seconds) and then works fine.
Where is the problem? How to debug it?

Before the update it worked well and fast (almost immediately)

Project is under GIT (but i have rule for ignore git files & folders)

**Comment by roblourens** [comment]
Can you check which processes are using CPU while the search is happening? Do you see rg.exe using high CPU, MsMpEng.exe, something else?

**Comment by Kcko** [comment]
@roblourens Yes! When Im trying to search something (at first) , service MsMpEng.exe = Antimalware Service Executable) crushes my CPU power)

Screens:
http://files.rjwebdesign.cz/i2/20181115-195551.png
http://files.rjwebdesign.cz/i2/20181115-195603.png

How to avoid this? What is bad?

**Comment by Kcko** [comment]
I know now! This has solved problem with  service MsMpEng.exe = Antimalware Service Executable, it seems.
Previous version had no problem with this (while 1.29 yes), whats changed?

`"typescript.tsc.autoDetect": "off"`
( https://github.com/Microsoft/vscode/issues/63078#issuecomment-439065669) 

What is it used for? Is it necessary to have it turned on?
Thx for further information.

**Comment by imichall** [comment]
Thank you! I have had the same problem, and after this action `"typescript.tsc.autoDetect": "off"` the problem has been solved.

**Comment by ratidzidziguri** [comment]
That did not work for me. I still see rng.exe and defender spikes.r

**Comment by Kcko** [comment]
temporary solution is turn off windows defender when you want to use vsc
