### ISSUE TITLE
VSC freezes after last update

### ISSUE THREAD

**Issue by potomek** [Microsoft/vscode#63202]
Issue Type: <b>Bug</b>

After the last update, VSC freezes 3-5 times a day, I do not suspect the reason at all. Maybe an extension. Anyway many thanks for this free soft, I love it!

VS Code version: Code 1.29.0 (5f24c93878bd4bc645a4a17c620e2487b11005f9, 2018-11-12T07:42:27.562Z)
OS version: Linux x64 4.15.0-1021-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3935)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 3, 3|
|Memory (System)|31.31GB (15.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.2.0
debugger-for-chrome|msj|4.11.1
sort-lines|Tyr|1.7.0

</details>

**Comment by fusengine** [comment]
Your process is `rg` ??

**Comment by oppoi1** [comment]
I'm having the same issues but more frequent with lags

**Comment by tranthaihoang** [comment]
Yes! After today's update, my VS Code was frozen continuously, "The window is no longer responding"

**Comment by tranthaihoang** [comment]
> Go look your process. If you have rg process

Can you say clearer?

**Comment by br0cky** [comment]
I'm getting this issue after updating my Mac to Mojave.

If i look at VSCodes Process explorer, whatever file i'm working on will randomly take 100+% of my CPU and i get the error Window is no longer responding.

Already tried removing all my extensions, no change.

I'm on Version 1.29.0 (1.29.0)
OS - 10.14.1

**Comment by potomek** [comment]
I'm sorry, I just wanted to report a bug as a user from the VSC program, not as a developer, so I don't know anything more. Please, close the topic if it does not meet the formal requirements. Thank you for the reaction. Greetings!

**Comment by derekwallace** [comment]
I have the same issue. Happens 5+ times a day every day.
Windows 10

rg.exe process is constantly present.

![image](https://user-images.githubusercontent.com/5574230/48549898-ff5a2080-e8c8-11e8-87d9-c6f7e751bf2e.png)

**Comment by fusengine** [comment]
Hum 🧐

**Comment by fusengine** [comment]
And you havé à lot process `code helper`?

**Comment by DavidA2014** [comment]
Since the update to 1.29.0 a few days ago, my Visual Studio Code on Windows 10 has hung twice. It hangs at 45% cpu load and eventually I see a message saying that the window is not responding.  I don't recall seeing this before the update.

**Comment by fusengine** [comment]
Look Your process is rg or code helper a lot

**Comment by oppoi1** [comment]
Something I've noticed is if theres new output, a new message, I enter information in the build in terminal or scroll in my terminal my "code main" process requires quite a lot of my CPU. If I scroll a lot it goes up to 50%.

**Comment by YusifKhalilov** [comment]
Same problem. Emmet and some other extensions are not working properly after update

**Comment by derekwallace** [comment]
I noticed this starting with the insiders a few weeks ago. I switched to
production hoping it would go away.

**Comment by pitops** [comment]
I have same issue on mac as well. This is frustrating.

**Comment by majidfn** [comment]
Same issue here. Has frozen 5 times today. 
On Mac OSX High Sierra (10.13.6)
Could not find anything related in syslogs either.

In ActivityMonitor, there are a bunch of `code helper` processes, one of them taking 150% of the CPU. 

![Activity Monitor](https://imgur.com/zGH4Rl3)

**Comment by roblourens** [comment]
See https://github.com/Microsoft/vscode/issues/62970

We are about to ship an update which should fix this

**Comment by oppoi1** [comment]
I still have the same issues, especially if there is new output in the integrated terminal

**Comment by mhamilto** [comment]
I have similar issues. Several times a day I get Visual Code generating 9 or 10 rg.exe processes  simultaneously (not just after startup).  Visual Code can easily take 20% of the CPU without me doing anything with it. I've only seen this on 1.29.1.

**Comment by derekwallace** [comment]
Update resolved issue for me.
