### ISSUE TITLE
Debug Electron 2.0.13 64bit failed with error "Cannot connect to runtime process, timeout after 10000ms".But succeed on Electron 32bit

### ISSUE THREAD

**Issue by panzhiyi3** [Microsoft/vscode#63618]
- VSCode Version:1.29.1(system setup)
- OS Version:Window 7 x64

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/2980716/48884331-03ed7e80-ee5f-11e8-885b-d5227d04df99.png)

1.Just a normal electron project,and use default launch.json created by vscode as
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Main Process",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "windows": {
              "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
            },
            "args" : [
                ".",
                //"--inspect=5858", //tried but doesn't work
                //"--remote-debugging-port=5858" //tried but doesn't work
            ],
            //"port": 5858,  //tried but doesn't work
            //"protocol": "legacy" //tried but doesn't work
          }
    ]
}
```
2.Use same Electron version(2.0.13) but 32bit,it works, seems only failed on 64bit version. And I have tried Electron 3.x 64bit , also worked

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
@panzhiyi3 did you try to follow this recipe https://github.com/Microsoft/vscode-recipes/tree/master/Electron ?

**Comment by roblourens** [comment]
Seen this a couple times before, https://github.com/electron/electron/issues/11524 but no solution.

What is the install path of vscode?

I can probably just work around this on our end...

**Comment by panzhiyi3** [comment]
> Seen this a couple times before, [electron/electron#11524](https://github.com/electron/electron/issues/11524) but no solution.
> 
> What is the install path of vscode?
> 
> I can probably just work around this on our end...

C:\Program Files\Microsoft VS Code\Code.exe
![image](https://user-images.githubusercontent.com/2980716/48999374-6e6d2a00-f191-11e8-9661-7d08cec72b84.png)

**Comment by roblourens** [comment]
Does your user name include non-english characters?

If you type `chcp` in a command prompt, what is the result?

**Comment by panzhiyi3** [comment]
> Does your user name include non-english characters?
> 
> If you type `chcp` in a command prompt, what is the result?

My system language chinese(simplified)
User name:sa
resulit of 'chcp':
![image](https://user-images.githubusercontent.com/2980716/49063907-f287e600-f253-11e8-9fd4-39f6a53d8ecd.png)

**Comment by roblourens** [comment]
I pushed a fix for this in Insiders, could you try it out?

**Comment by panzhiyi3** [comment]
> I pushed a fix for this in Insiders, could you try it out?

I tried this one "VSCode-win32-x64-1.30.0-insider" from https://code.visualstudio.com/docs/?dv=winzip&build=insiders
And...the problem is still
![image](https://user-images.githubusercontent.com/2980716/49173740-7a1e4380-f37f-11e8-8166-453705c6ec12.png)

lauch.json
```
{
    "name": "Debug Main Process",
    "type": "node",
    "request": "launch",
    "cwd": "${workspaceRoot}",
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
     "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
     },
    "args" : [
        "."
    ]
}
```

If I used a wrong version of insiders?

**Comment by roblourens** [comment]
Sorry, just realized this didn't make it into the last Insiders build. It will be in the next one. Try again in about 12 hours :)

**Comment by panzhiyi3** [comment]
> Sorry, just realized this didn't make it into the last Insiders build. It will be in the next one. Try again in about 12 hours :)

Hi, I tried again today,and seems it not work for me
Insider version:
Version: 1.30.0-insider
Commit: 9878edb2a72ed4c4fd64811f9a58f06151810acf
Date: 2018-11-30T06:19:37.226Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.1.7601

Or can you give me a direct url to download patch file or full version?I'm glad to help

**Comment by roblourens** [comment]
Sorry, please try one more time with the latest Insiders. If it still doesn't work, please set `"trace": true` and upload the log from the path in the debug console here.

**Comment by panzhiyi3** [comment]
It works!Tried the new version,everything is fine! 
1.30.0-insider
Commit: fa87e67ebfd6b8014ba697ddbc6c2d6c0e2cb970
Date: 2018-12-04T09:34:30.209Z

Thanks! TwT

**Comment by roblourens** [comment]
Great, thanks for trying it!

**Comment by weinand** [comment]
verified by user.
