### ISSUE TITLE
Java syntax highlighting breaks when using '<' in field declarations

### ISSUE THREAD

**Issue by olivercoad** [Microsoft/vscode#63894]
In java, syntax highlighting for all declarations in the same scope breaks after any field declaration containing a less than symbol (or left bit-shift).
It used to work fine, so I found that the first version where it is broken is 1.26.

![goodhighlighting](https://user-images.githubusercontent.com/24837994/49135131-f4c47000-f339-11e8-8e14-69be54fcbb45.PNG)

![badhighlighting](https://user-images.githubusercontent.com/24837994/49135689-90a2ab80-f33b-11e8-9e0d-ad4aba2b60ed.gif)

**Comment by alexr00** [comment]
I tried this out in stable (1.30) and insiders (1.31) and I can't reproduce it in either. Can you try updating to one of those and see if it still reproduces for you?

**Comment by olivercoad** [comment]
Yep it's fixed in 1.30

**Comment by laeckerv** [comment]
The problem still exists for me in 1.3.1 and inisders 1.32.

![errro](https://user-images.githubusercontent.com/1636489/52639024-9b4cf580-2ed3-11e9-94ab-ba8a4d653626.gif)

Important thing to note is that this doesnt work correctly as seen in the gif.

```jsx
  isDraggingUpFromCenter = (startPosition, data) =>
    startPosition < this.halfOfWindowHeight() &&
    startPosition > this.halfOfWindowHeight() - AREAFORLISTENERCENTER &&
    data.deltaY < TRIGGERINGDELTAY;
```

while this works fine.

```jsx
  isDraggingUpFromCenter = (startPosition, data) => {
    return(
        startPosition < this.halfOfWindowHeight() &&
        startPosition > this.halfOfWindowHeight() - AREAFORLISTENERCENTER &&
        data.deltaY < TRIGGERINGDELTAY;
    )
  }
```

Should I open a new issue?

**Comment by olivercoad** [comment]
@laeckerv
What happens in a more simple case with something like the original code in the first comment?
I can't reproduce this in 1.31.1 - can you provide some simple standalone code to test with?

It's interesting that the `<` in `startPosition < this.halfOfWindowHeight()` doesn't cause it to happen while the last one in the expression does.

**Comment by laeckerv** [comment]
> What happens in a more simple case with something like the original code in the first comment?

Seems to work fine (1.31.0)

> can you provide some simple standalone code to test with

```jsx
const FOO = 0;
const FOOO = 0;

class Bar {
  myFunc1 = () =>
    1 < 2 &&
    2 > 1 &&
    FOO < FOOO;
  myFunc2 = () =>
    1 < 2 &&
    2 > 1 &&
    FOO < FOOO;
}

export default Bar
```

Rsults in 
![image](https://user-images.githubusercontent.com/1636489/52699133-58dbf500-2f75-11e9-9c2b-174458e0355f.png)


With this example (because i reduced the conditions) I also found out that when format it differently - it also works.

```jsx
const FOO = 0;
const FOOO = 0;

class Bar {
  myFunc1 = () => 1 < 2 && 2 > 1 && FOO < FOOO;
  myFunc2 = () => 1 < 2 && 2 > 1 && FOO < FOOO;
}

export default Bar
```

Results in 
![image](https://user-images.githubusercontent.com/1636489/52699204-82951c00-2f75-11e9-90a5-944f84c7d38c.png)

**Comment by olivercoad** [comment]
That's JavaScript not Java. Yep can reproduce in JavaScript but perhaps make it a separate issue.
