### ISSUE TITLE
New tree based debug hover: the hover widget is not always fitting to the tree

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#64334]
Testing #64003:

- For a single long string I see the hover wrapping nicely.
- for a structured object with a long string attribute the widget does not "fit the tree" and the long string is not line wrapped either. And there is no horizontal scrolling.

If I expand substructures, a vertical scrollbar appears.
Why does not happen the same in the horizontal case?

In stable I see a horizontal scrollbar which does not really work because I'm not able to see the end of a long string.

**Comment by isidorn** [comment]
The new tree does not yet support the horizontal hover.
Once that is implemented we plan to add it. Assignign to december since we plan to add it then to the tree I believe.

fyi @joaomoreno

**Comment by isidorn** [comment]
Fixed by @joaomoreno  via https://github.com/Microsoft/vscode/issues/63684

**Comment by jrieken** [comment]
![jan-31-2019 17-46-54](https://user-images.githubusercontent.com/1794099/52070011-424e9a80-2580-11e9-886b-9442d53fcea1.gif)

The vertical scrolling is still broken. When having just two properties in my object I don't expect to see a v-scrollbar, esp not when the widget grows on expanding items

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/67620

**Comment by dbaeumer** [comment]
Marking as verified due to @isidorn last comment.
