### ISSUE TITLE
"Initializing TS/JS language features" freezes app for too long on every restart.

### ISSUE THREAD

**Issue by DieLaughing** [Microsoft/vscode#65178]
Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.13.0-43-generic

Steps to Reproduce:

1. Download VS Code
2. Open a JavaScript file

**Comment by DieLaughing** [comment]
Looks like someone is running around closing issues *EXACTLY* describing this issue by claiming they don't have enough info. Just tell me how to shut it the $%&# off. I would rather the entire app be a basic text editor than have that extension slow my machine down one iota.

**Comment by DieLaughing** [comment]
I even tried some other solutions posted elsewhere such as changing my jsconfig.json to:
{
  "compilerOptions": {
      "module": "es2015",
      "target": "ES6",
      "lib": ["es6"]
  },
  "exclude": [
      "node_modules",
      "**/node_modules/*"
  ]
}

**Comment by DieLaughing** [comment]
All I want to do is change the CSS of an element in the editor, (which is it's own goddamn nightmare) and every *SINGLE* time I restart, the whole machine hangs until it's done and I just want it to stop. I have to restart BS Code a *LOT* and I F-ing ****HATE**** "Initializing TS/JS langauage features." I already hate TS as much as a person can.

**Comment by DieLaughing** [comment]
I believe this was caused by some theme I had installed. While the loading time is still long, it has reduced enough where I believe it's nominal on my super slow old hardware.

**Comment by jaredbuttars** [comment]
Same issue here. No themes installed.

Version: 1.30.0 (user setup)
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:29:11.253Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Comment by eluchsinger** [comment]
Doesn't that also disable the JS/TS Language features?

**Comment by DieLaughing** [comment]
I think the important take-away here is that something(?) is affecting performance and it is not easy or clear to find the culprit. You can selectively allow extensions while disabling the rest, narrowing it down, but what would be better is something that automatically warned you there might be a problem with X-extension because it's taking a long time to finish doing whatever.

**Comment by epeterssen** [comment]
Same issue.  Reverted to 1.25.1.

**Comment by DieLaughing** [comment]
After a *very* brief glance at the logs, my next guess is that the TS server launching is slowing some people's machines way down. I loathe TypeScript. It makes everything it touches take more time and only helps you if you're error prone.

**Comment by jupiterben** [comment]
here is how I fixed this issue :   use procmon.exe to see what the code.exe is doing,  in my machine it busy read/write files in a symbollink  V2, so I delete the symblolink , restart code  , then everything is fine.

**Comment by 4s7r0** [comment]
Can you (or anyone) post step by step instructions? Thanks.

**Comment by neeleshb** [comment]
This is still reproducible as on Jan-25-2019 (I'm  on debian). 

1) Uninstall code completely. 
$ sudo apt get purge code
$ rm -rf ~/.config/Code 
$ rm -rf ~/.vscode

2) Install the latest stable build  (1.30.2 as of this writing)
$ sudo apt-get install code (not insiders). 

3) Launch VScode and open any significantly big existing project (200+ TS files). It it matters, I just open the folder, and not any "workspace". 

4) Open any file using the navigator on the left or by typing the file name in ^P. As soon as you open the file, the left portion of the bottom blue bar starts showing "Initializing JS/TS Language features".  There are no errors or warnings. Just stick in initialization. 

5) The initialization did not complete for ~30 minutes after  which I gave up. 

Note: While the initialization is in progress, VS code is usable as a text editor, but anything associated with TS (imports / auto completion / cross reference / goto definition etc) do not work.
