### ISSUE TITLE
Code scrolls when typing with markdown preview open

### ISSUE THREAD

**Issue by the-ress** [microsoft/vscode#65504]
Issue Type: <b>Bug</b>

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:07.165Z)
VS Code version: Code - Insiders 1.31.0-insider (2803a8655cf5e05066a4ee47cce303eefca6408c, 2018-12-20T09:10:39.545Z)
OS version: Windows_NT x64 10.0.17134

**Steps to Reproduce:**
1. Open a markdown file longer than your screen height
2. Move text cursor near the end of the file
3. Type

**Expected result:** Markdown preview doesn't affect code scroll position unless I directly scroll the preview.

**Actual result:** Code scrolls around when typing.

![vscode-markdown](https://user-images.githubusercontent.com/1612377/50299725-a14dc980-0482-11e9-8753-2951a3a3d0d6.gif)

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
livs|abh|1.0.6
html-snippets|abu|0.2.1
vscode-base64|ada|0.1.0
vscode-caniuse|aka|0.5.3
ts-loader-problem-matcher|alq|0.3.0
random-string-password-generator|bib|1.0.2
unique-lines|bib|1.0.0
cobol|bit|4.0.0
simple-react-snippets|bur|1.2.2
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
gitignore|cod|0.6.0
indent4to2|Com|0.1.2
vscode-svgviewer|css|1.4.7
vscode-gist|dba|1.0.0
xml|Dot|2.4.0
vscode-generate-getter-setter|DSK|0.5.0
vscode-babel-coloring|dza|0.0.4
EditorConfig|Edi|0.12.5
tslint|eg2|1.0.42
vscode-npm-script|eg2|0.3.5
php-debug|fel|1.12.6
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
vscode-solution-explorer|fer|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.4.7
Ionide-FAKE|Ion|1.2.3
Ionide-Paket|Ion|1.12.0
reg|ion|0.0.2
debugger-for-phantomjs|ira|0.1.1
csharpextensions|jch|1.3.0
jenkins-declarative-support|jmM|0.1.0
latte|Kas|0.1.1
refactorix|kri|0.3.6
tgit-cmds|mbi|1.2.0
sort-typescript-imports|mic|1.4.1
xml-format|mik|1.0.1
ecdc|mit|0.12.0
mssql|ms-|1.4.0
cpptools|ms-|0.20.1
csharp|ms-|1.17.1
mono-debug|ms-|0.15.8
node-debug2|ms-|1.31.1
PowerShell|ms-|1.10.2
team|ms-|1.144.1
debugger-for-chrome|msj|4.11.1
quicktype|qui|12.0.46
vscode-sort-json|ric|1.13.0
vscode-icons|rob|8.0.0
annotator|ryu|0.11.0
partial-diff|ryu|1.4.0
jenkinsfile-support|sec|0.1.0
code-settings-sync|Sha|3.2.4
trailing-spaces|sha|0.2.11
vscode-hexdump|sle|1.7.2
rewrap|stk|1.9.1
es-quotes|vil|0.2.6
vscode-react-native|vsm|0.7.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.1
editorconfig-vscode-snippet|zgu|0.2.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by krupenja** [comment]
This looks like a duplicate of #53545

**Comment by mjbvz** [comment]
Please share the source of your markdown file

**Comment by the-ress** [comment]
@mjbvz Here's the source: https://gist.githubusercontent.com/the-ress/5f6c071c50db5caf82783e04a07d2a4e/raw/55df1e1e77cd04a443d3be2d9512f87b89b13cf9/sample.md

**Comment by sbatten** [comment]
@mjbvz I'm seeing the same behavior as OP with provided file still

**Comment by glennbarrett** [comment]
I am seeing this on Version 1.35.1 for MacOS.  Just did a google search after I experienced this issue and came across this thread.  I also had a pending update to 1.36.0 that I installed, and still see the same behavior.

**Comment by BjoernPetersen** [comment]
I'm experiencing the same issue. It seems to be somehow caused by a lot of badges/shields in one line.

Here is my affected file: https://gist.github.com/BjoernPetersen/0510004e98161626741e31adc4400109

**Comment by Kwaadpepper** [comment]
Hi there also have this nasty bug with this file
https://gist.github.com/Kwaadpepper/a4568f1ed718cab1ec3b59d3d7ac3e76

![Annotation 2019-09-15 082935](https://user-images.githubusercontent.com/6019313/64917685-fb21bc80-d792-11e9-9198-71d7e5692782.jpg)

As for markdown related extension i have

    Nom : Markdown All in One
    ID : yzhang.markdown-all-in-one
    Description : All you need to write Markdown (keyboard shortcuts, table of contents, auto preview and more)
    Version : 2.4.2
    Serveur de publication : Yu Zhang
    Lien de la Place de marché pour VS : https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one

    Nom : markdownlint
    ID : davidanson.vscode-markdownlint
    Description : Markdown linting and style checking for Visual Studio Code
    Version : 0.30.2
    Serveur de publication : David Anson
    Lien de la Place de marché pour VS : https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

**Comment by gmccullo** [comment]
I see this behavior consistently if there is a scaled image in the preview pane. In my CSS I set the max-width of images to 100%. I _think_ this is what produces the issue.

**Comment by gmccullo** [comment]
Another clue: turning off markdown.preview.scrollPreviewWithEditor prevents the problem (but also obviously stops the preview position from synching with the editor).

**Comment by gmccullo** [comment]
I think the problem went away in the previous release. At least I didn't notice it. But now it's back again. Very frustrating bug.

**Comment by ened** [comment]
Maddening issue. The `markdown.preview.scrollPreviewWithEditor` workaround does not work anymore.

**Comment by andy3520** [comment]
Face the same problem with this version
![image](https://user-images.githubusercontent.com/38342390/97143981-3e23d100-1796-11eb-9991-61784af069d2.png)

Have to use https://hackmd.io/ instead of it because of this annoying bug

**Comment by sibiraj-sr** [comment]
Same issue. for me it scrolls upwards.

![vs](https://user-images.githubusercontent.com/45618743/97404322-ec0cb800-191b-11eb-98ff-356fad469b83.gif)

<img width="450" alt="Screenshot 2020-10-28 at 12 52 31 PM" src="https://user-images.githubusercontent.com/45618743/97404661-77864900-191c-11eb-8baf-f6b2b8c925ce.png">

Related to #89930?

**Comment by buzhangjiuzhou** [comment]
I have the same issue, and I noticed that once I insert an image in it ,this will happen, but when I didn't have images in it, the preview works fine, it has been there for many versions and I nearly encounter it with every version I've used(from the mid of last year.).

**Comment by pacharanero** [comment]
Also experiencing this issue, which seems to be new (I've previously edited the same document in Markdown Preview mode without having the page scrolling up one line every time I type a character)

It's been reported a number of times it seems. There's a closed issue here https://github.com/microsoft/vscode/issues/57216

**Comment by buzhangjiuzhou** [comment]
> I have the same issue, and I noticed that once I insert an image in it ,this will happen, but when I didn't have images in it, the preview works fine, it has been there for many versions and I nearly encounter it with every version I've used(from the mid of last year.).

With the latest version, 1.51.1, this was fixed, thank you !

**Comment by fwarmuth** [comment]
Still reproducible with 1.51.1!
As mentioned is comment out my embedded images, which solved the issue for me...

**Comment by vii33** [comment]
The bug is still open on v1.52.0.

Version: 1.52.0 (system setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by HitenBhavsarMSFT** [comment]
I used workaround by open 2 visual code editor, one with readme editor and other with readme Preview. This have stopped the scrolling to the middle on the readme editor.  which work much faster.

**Comment by hxzhao527** [comment]
The bug is still open.

Version: 1.53.0
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T16:01:04.046Z (3 days ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.2.0

**Comment by tamuratak** [comment]
See https://github.com/microsoft/vscode/issues/115864#issuecomment-774337246.

You should try disabling all the extension.
