### ISSUE TITLE
write EPIPE error when launching integrated powershell terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6621]
Windows 10

1. Launch alpha
2. ctrl+`

```
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:28 [uncaught exception]: Error: write EPIPEonError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:28(anonymous function) @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:100emitOne @ events.js:90emit @ events.js:182window.onerror @ C:\Program Files (x86)\Microsoft VS Code Alpha\resources\electron.asar\renderer\init.js:107i.globals.onerror @ errorTelemetry.ts:62
index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:31 Error: write EPIPE
    at exports._errnoException (util.js:890:11)
    at ChildProcess.target._send (internal/child_process.js:634:20)
    at ChildProcess.target.send (internal/child_process.js:521:19)
    at f.layout (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/parts/terminal/electron-browser/terminalPanel.js:4:1597)
    at t.layout (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:89:5228)
    at e.layout (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:99:26958)
    at e.layout (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:117:22358)
    at e.layout (file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:118:19311)
    at file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:118:17922
    at file:///C:/Program Files (x86)/Microsoft VS Code Alpha/resources/app/out/vs/workbench/workbench.main.js:39:8393onError @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:31(anonymous function) @ index.html?config={"pathArguments"%3A[]%2C"programStart"%3A0%2C"enablePerformance"%3Afalse%2C"verbo…:100emitOne @ events.js:90emit @ events.js:182window.onerror @ C:\Program Files (x86)\Microsoft VS Code Alpha\resources\electron.asar\renderer\init.js:107i.globals.onerror @ errorTelemetry.ts:62
events.js:154 Uncaught Error: write EPIPE
```

**Comment by Tyriar** [comment]
Some info on EPIPE: https://github.com/mhart/epipebomb

`createTerminal` seems to get run over and over.

**Comment by Tyriar** [comment]
Need to verify whether this is still an issue after 3b0df36 on my home PC

**Comment by v-pavanp** [comment]
I am getting EPIPE error with alpha build when I set shell to powershell.
Once I get this error I am not able to edit content from editor window. I need to forcefully close VSCode to get rid of this error. The weird thing is my mouse pointer is keep blinking with loading icon.
![image](https://cloud.githubusercontent.com/assets/17735796/15485706/ab19694c-20f5-11e6-851c-eb49f95d3f30.png)
![terminalissue](https://cloud.githubusercontent.com/assets/17735796/15487873/a8d850fc-2105-11e6-9681-74d2ec665a7f.gif)

**Comment by Tyriar** [comment]
@v-pavanp can you retry this on latest alpha? This is fixed on the machine I was reproducing consistently on now.

**Comment by v-pavanp** [comment]
I am still getting EPIPE error though pop-up is not showing up. But in developer tool.
Look at bug #6834

**Comment by Tyriar** [comment]
I can no longer reproduce, the default shell is now cmd.exe so it's not as big of an issue. I guess we'll wait and see if more can repro.

**Comment by Tyriar** [comment]
Closing due to inactivity and lack of reports, please leave a comment if you're still experiencing the issue and/or have more information.

**Comment by tkmine** [comment]
cant open terminal
