### ISSUE TITLE
Editor actions lost ability to detect CtrlCmd+click

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6685]
It looks like all editor actions now get passed in the IEditorIdentifier. However there were some actions expecting the mouse event as context to detect if the user wants to invoke the action "to the side".

For example: the preview markdown action would open to the side if you Cmd+click on it. Same for the diff action. 

I suggest we find a way that the context is enriched with this information and still carries around the IEditorIdentifier.

**Comment by isidorn** [comment]
Well I can introduce an `IEditorContext` that would have an `IEditorIdentifier` and the event. Thoughts?

**Comment by bpasero** [comment]
@isidorn yes, sounds nice!

**Comment by bpasero** [comment]
@isidorn I am also fine adding a property keymods similar as I do it now in quick open that contains the modifier keys pressed: https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/common/quickOpen.ts#L46

**Comment by isidorn** [comment]
I went with the event, and not the keymods since the event was easier to hook up in the action bar 9c6c0bf

I fixed the markdown action. Not sure if there are other actions that depend on this behavior - if there are some let me know and I will fix them.
As far as I know the context menu action do not have this functionality

**Comment by bpasero** [comment]
Still does not seem to work for the diff action. Maybe a regression from Johs work?

**Comment by isidorn** [comment]
I think i verified it worked - I will investigate what caused this.
