### ISSUE TITLE
Stop recommending old tslint plugin

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#67028]
![screenshot 38](https://user-images.githubusercontent.com/9638156/51643958-740fa200-1f7f-11e9-9111-4514fe9702b8.png)

**Comment by usernamehw** [comment]
I thought it's a bug that recommendation from `TypeScript TSLint Plugin` just disappeared, but it just was recommended in one workspace it wasn't in another... Maybe it would be a good idea to recommend it globally.

**Comment by mjbvz** [comment]
Our list of recommendations should be fixed in upcoming insiders builds, although I believe the old extension can still be recommended if many users of a given workspace are using it

/cc @egamma

**Comment by octref** [comment]
Both still show up as recommended extensions:

![image](https://user-images.githubusercontent.com/4033249/52020767-62f6f180-24a7-11e9-9e18-fd602cd8e678.png)

**Comment by mjbvz** [comment]
Likely just need to update the package `distro` version so we pull in the update recommendations

**Comment by mjbvz** [comment]
Try this in the next insiders which updates the distro version
