### ISSUE TITLE
Pager doesn't scroll when holding z in Integrated Terminal

### ISSUE THREAD

**Issue by connorshea** [Microsoft/vscode#67137]
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

Steps to Reproduce:

1. Generate two differing files (I used [a Lorem Ipsum generator](https://www.lipsum.com/)) or use the two text snippets I've included in the details block below and save them as `test.txt` and `test2.txt` in your current directory.
2. Open the Integrated Terminal in VSCode and navigate to the directory you've saved the files to.
3. Run `git diff --no-index test.txt test2.txt` to display a diff of the two files (the `--no-index` flag is so it doesn't require the files be tracked in a git repo).
4. Hold "z" to have git's pager scroll down through the page, notice how it doesn't actually scroll until the key is let up. Also, if you hold it for a few seconds a special key dialog comes up (I think this part of the issue may be macOS-specific?).

My expectation would be that the pager would continuously scroll when holding down "z", as that's how it works in the default macOS terminal.

My editor, extensions disabled, with the special key dialog showing:

<img width="1280" alt="screen shot 2019-01-25 at 2 31 18 pm" src="https://user-images.githubusercontent.com/2977353/51773983-e8486380-20ad-11e9-9637-d875c025887c.png">

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>Test Files</summary>

`test.txt`:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ornare nunc quis sapien rhoncus, sit amet suscipit sapien imperdiet. Mauris fermentum velit ut commodo placerat. Vestibulum vitae facilisis ante, et pulvinar diam. Nullam sollicitudin purus sed risus commodo mollis. Curabitur eu lacus eu neque porta semper eu in enim. Vivamus vestibulum commodo nibh, et semper velit tristique at. Maecenas vestibulum, metus et pulvinar iaculis, justo lectus consectetur nisl, sed feugiat dolor augue at eros. Nam tempus tortor eu nunc egestas, nec tristique mi sodales. Donec sit amet erat eleifend, tincidunt magna in, varius nibh. Curabitur hendrerit erat eget metus posuere finibus. Praesent porta, nisi id iaculis fermentum, lectus dolor vulputate ligula, vel elementum dolor justo sed dolor. Donec pulvinar metus sit amet tincidunt placerat. Aliquam at erat urna. Phasellus vestibulum varius lectus, feugiat aliquam ipsum. Phasellus a libero vel leo lobortis vehicula et laoreet lorem.

Nam et arcu vitae eros vestibulum hendrerit sit amet non lorem. Integer in justo ac erat viverra egestas quis nec erat. Sed eget velit id lectus porta convallis ut sollicitudin sapien. Pellentesque imperdiet justo sem, a dapibus neque commodo eget. In sed massa porttitor, dapibus enim quis, tincidunt lectus. Fusce luctus ante neque, eu imperdiet metus dictum et. Praesent massa mauris, hendrerit in fermentum at, porttitor sed erat. Proin eu ante nec erat molestie sodales.

Nulla hendrerit, elit eu malesuada pellentesque, odio urna egestas massa, a sollicitudin purus enim vel purus. Morbi malesuada, urna vitae imperdiet interdum, arcu elit porta sapien, non hendrerit purus leo vel orci. Donec vitae elit dictum felis tempus efficitur non euismod felis. Nunc eu est velit. Curabitur purus odio, aliquet quis tristique eu, vulputate eget sapien. Suspendisse sodales ex non condimentum elementum. Curabitur ultrices elementum risus nec laoreet. Donec commodo sed est in lacinia. Sed ut eros diam. Nunc volutpat nisi a nulla vulputate sagittis.

Quisque sagittis, nibh nec tincidunt interdum, metus sem sollicitudin est, euismod fringilla ligula risus vitae risus. Duis feugiat in mi quis faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur posuere nulla risus. Sed commodo semper laoreet. Nam condimentum lobortis tortor in convallis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed lacinia leo quis imperdiet porttitor. Suspendisse potenti. Nunc non nisi orci. Vivamus eleifend finibus ipsum, sit amet feugiat mi ultricies sed. Proin bibendum augue ut enim pulvinar, sed dapibus augue luctus. Vivamus vulputate nisl in massa pulvinar, nec facilisis arcu malesuada.

Nullam vitae nisl enim. Pellentesque nec fringilla magna. Sed bibendum, nisi molestie pharetra ultrices, tortor erat tincidunt lectus, nec imperdiet dolor eros vitae purus. Pellentesque et congue elit. Mauris eget nibh in velit semper rhoncus. Sed tempor orci nec nisl scelerisque, eget finibus metus malesuada. Suspendisse auctor ante ac est accumsan, interdum cursus augue elementum. Aliquam feugiat, lorem nec iaculis auctor, augue erat dapibus turpis, id sodales augue dui eget nisi. Nulla at varius massa, in varius eros. Sed vitae neque vitae metus laoreet faucibus. Fusce eu massa elementum libero ultrices lacinia. Mauris neque dolor, consequat nec leo nec, dignissim dapibus turpis. Maecenas auctor varius purus, in pulvinar ligula ullamcorper quis. Sed non congue urna. Aenean vel nulla vitae sem auctor facilisis vitae vitae justo. 
```

`test2.txt`:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In posuere porttitor libero in gravida. Morbi placerat posuere convallis. Cras orci tellus, vestibulum et pulvinar bibendum, pellentesque vestibulum nibh. Vestibulum eget nisl erat. Donec tempus eros turpis, sed maximus arcu placerat sed. Nam dignissim dui nisl, eget volutpat risus condimentum vitae. Nam molestie aliquet leo sed commodo. Donec vitae sagittis enim. In hac habitasse platea dictumst. Aenean congue fermentum imperdiet. Vestibulum luctus diam justo. Cras lacinia tellus in leo congue, sit amet dignissim ante molestie. Proin pharetra mauris velit, nec laoreet neque vulputate et. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam ut porttitor sem, sed auctor ex. Aenean sit amet efficitur turpis.

Fusce varius nisl ac nisl malesuada rhoncus. Mauris eget aliquam urna, id egestas eros. Nunc eleifend sodales lacus. Vestibulum posuere auctor tellus, eu accumsan nulla congue id. Curabitur et orci eu turpis euismod pulvinar quis eu felis. Praesent sit amet urna in velit porttitor pretium. Sed mi turpis, ultrices quis lectus eu, pharetra gravida mi. Vivamus interdum placerat odio. Morbi ac magna posuere, pulvinar purus lobortis, aliquet massa. Aliquam tincidunt convallis dui, ut molestie est. In erat magna, mollis nec augue vel, laoreet consequat nisi. Nullam ornare sem mauris, at vehicula neque blandit a. Donec porttitor cursus viverra. Nulla in felis eros. Donec vel nibh elit. Nam imperdiet congue nibh a commodo.

Etiam in metus nulla. Pellentesque aliquet sagittis elit, in vestibulum ligula. Cras libero arcu, tristique ac luctus vel, condimentum sed elit. Nam tempus, nunc sed elementum imperdiet, nisl massa faucibus ligula, eu ultricies arcu ex et ante. Donec eget libero fringilla, luctus tortor id, viverra nisi. Mauris pulvinar velit quis lacus facilisis pulvinar. Quisque efficitur laoreet ultrices. Donec sit amet velit eget nibh eleifend pulvinar ut nec arcu. Aenean sit amet sodales sapien. Mauris molestie mattis erat, et semper dolor accumsan in. Nam pharetra placerat elit. Cras vehicula congue pulvinar. Pellentesque laoreet, ipsum sit amet scelerisque iaculis, justo metus luctus nisl, vel varius dolor nulla lobortis nibh. Sed dictum nisl ligula, non euismod lacus maximus id. Praesent turpis erat, bibendum sit amet augue at, pellentesque lacinia velit.

Quisque viverra tellus neque, vel dictum lectus varius non. Suspendisse potenti. Nam ultrices ipsum quis urna porttitor, sed tincidunt eros interdum. Morbi vel tempus mi, ut convallis turpis. In aliquam nisl at quam vulputate elementum. Sed ultrices id eros vel tempor. Cras elit risus, rhoncus sit amet venenatis et, placerat vitae tortor. Maecenas vitae dolor sed neque feugiat consectetur. In vestibulum lobortis iaculis. Vivamus ligula orci, finibus at venenatis vitae, mollis in metus. Nam risus odio, commodo eu malesuada nec, dapibus non tellus. Integer maximus libero at gravida dignissim. Nunc dapibus nunc elit, vel aliquet tellus varius et.

Praesent nec urna convallis enim gravida tempor. Sed sit amet egestas mi. Quisque vitae elementum elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse posuere lectus ex, sit amet laoreet ligula ullamcorper id. Nulla dapibus, mauris et dignissim scelerisque, magna nulla convallis neque, id maximus quam urna id urna. Duis dolor erat, porta sit amet tortor vel, mollis varius velit. Etiam pulvinar felis odio. Vivamus suscipit luctus mauris quis tincidunt. Cras non diam porttitor, auctor ex eu, ullamcorper sapien. Vivamus tincidunt tincidunt odio, in ultrices erat interdum non. In libero ante, feugiat in eleifend vel, mattis in ex. 
```

</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|-psn_0_131104|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by connorshea** [comment]
@Tyriar it scrolls properly now, but the macOS special key dialog still shows up.

<img width="1440" alt="screen shot 2019-01-28 at 9 56 26 am" src="https://user-images.githubusercontent.com/2977353/51852279-034fe900-22e3-11e9-807c-ecaf71a48935.png">

**Comment by Tyriar** [comment]
@connorshea as far as I'm aware there's no way to disable that in a web context unfortunately.
