### ISSUE TITLE
Debugging Hangs when default terminal app doesn't exist

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/vscode#67296]
To test: Set Terminal.External.LinuxExec to an app that doesn't exist.

Start debugging with external terminal (I used the C++ extension and set `externalConsole` to `true`). 

Expected: 

Failure response for RunInTerminal command.

Actual:
No Response from VS Code's debugadapter protocol.
UI looks like it is waiting for debugging to start.

**Comment by pieandcakes** [comment]
@weinand This is becoming a bigger issue especially in the VS Code remote scenario as it doesn't fail with a good message to the user. Can we prioritize this to be fixed?

**Comment by weinand** [comment]
@pieandcakes this issue had been partially addressed in VS Code but it still needs some work on the extension side. Please see https://github.com/microsoft/vscode-remote/issues/734.

**Comment by pieandcakes** [comment]
@weinand Apparently when trying to find https://github.com/microsoft/vscode-remote I get a 404 so I can't see that issue.

**Comment by weinand** [comment]
@pieandcakes I've fixed the broken link...

**Comment by pieandcakes** [comment]
Thanks. I look forward to testing it.

**Comment by therealkenc** [comment]
Heads up I am still seeing situations where you get the "hang" with `externalConsole=false` (the _internal_ console) but the _external_ console works fine. This is on 1.35.0-insider 2019-05-17 on Real Linux Ubuntu to Real Linux Ubuntu with Remote SSH, but I saw the behavior last December-February too without inviting Remote to the party. Unfortunately it is really hard to give definitive repro steps to get in that state, because there are so many moving parts. And I know that doesn't help you. I am hoping that whatever error UX is forthcoming might shed some light. Mentioning it because if I've hit it you'll probably hear from someone else eventually too.
