### ISSUE TITLE
"editor.wordBasedSuggestions": false but still getting word based suggestions in mark down

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#6778]
- VSCode Version: code-alpha
- OS Version: Linux

Steps to Reproduce:

1. set "editor.wordBasedSuggestions": false
2. open a markdown file
3. request code complete

Observe: the list contains word based suggestions:

![capture](https://cloud.githubusercontent.com/assets/1931590/15501367/641390d2-21ad-11e6-840d-6e4386805863.png)

**Comment by jrieken** [comment]
Good catch. That's for sure for those that come from workers...

**Comment by jrieken** [comment]
fixed with https://github.com/Microsoft/vscode/commit/0ac95a8f1d3b831349018669bdd7bc31fa3efe37

**Comment by jods4** [comment]
From the milestone and the tag of the commit, I have the impression this should be fixed in 1.2.1?
Asking because it still reproduces...

**Comment by dbaeumer** [comment]
Assigning back to @jrieken to respond to comments.

**Comment by jrieken** [comment]
@jods4 A little detail would be helpful

**Comment by jods4** [comment]
@jrieken 
I open a folder containing `.md` files (through command line `code .`).
I have a `.vscode\settings.json` containing
```json 
// Place your settings in this file to overwrite default and user settings.
{
    "editor.wordBasedSuggestions": false
}
```
When I open intellisense all words suggestions appear.
![md-bug](https://cloud.githubusercontent.com/assets/3832820/16146426/4858f272-347e-11e6-89d6-0c79598ad74f.png)

**Comment by jrieken** [comment]
That will be fixed with the June release as we have moved out markdown into an extension
