### ISSUE TITLE
Files tree is loosing current focus after using a hotkey to create a new file

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/vscode#68161]
Issue Type: <b>Bug</b>

I have no installed extensions. Just configured hotkey to create a new file when `listFocus` and `!inputFocus`

```json
{
  "key": "a",
  "command": "explorer.newFile",
  "when": "listFocus && !inputFocus"
}
```

Here is what I'm getting when use the hotkey:

![bug](https://user-images.githubusercontent.com/46930/52439437-2caf1700-2b24-11e9-8b60-c014c30c83d2.gif)

Possible related to https://github.com/Microsoft/vscode/issues/68083

VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.23GB free)|
|Process Argv|--extensions-dir /tmp/vscode_test|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by joaomoreno** [comment]
You forgot to mention that you set

```
"workbench.list.keyboardNavigation": "simple"
```

**Comment by joaomoreno** [comment]
Fixed by preventing the keybinding to execute. Same `listAutomaticKeyboardNavigation` trick would be needed to get that keybinding.

Let's just get a setting for this: https://github.com/Microsoft/vscode/issues/68233

**Comment by Ky6uk** [comment]
Context `listAutomaticKeyboardNavigation=false` doesn't work also. Bug is still present with extensions which switch it to `false` (for example with `atom-keybindings, v3.0.6`).
