### ISSUE TITLE
workbench.files.action.showActiveFileInExplorer is throwing an exception

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#69163]
Issue Type: <b>Bug</b>

Not sure how to reproduce exactly as it seems to happen only sometimes. I Got this error when the active file is expanded in the explorer, running showActiveFileInExplorer will put the focus border around the explorer, not the item.

```
ERR Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]
    at j.getDataNode (file:///C:/Users/daimms.REDMOND/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:940:433)
    at j.<anonymous> (file:///C:/Users/daimms.REDMOND/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:938:732)
    at Generator.next (<anonymous>)
    at file:///C:/Users/daimms.REDMOND/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:939
    at new Promise (<anonymous>)
    at n (file:///C:/Users/daimms.REDMOND/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:30:716)
    at j.expand (file:///C:/Users/daimms.REDMOND/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:938:489)
    at Array.<anonymous> (file:///C:/Users/daimms.REDMOND/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:5114:366)
    at t (file:///C:/Users/daimms.REDMOND/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:93:803)
```

VS Code version: Code - Insiders 1.32.0-insider (2e4d4a6bb16a65303b460795fa4ac734f9aea43e, 2019-02-21T06:18:29.174Z)
OS version: Windows_NT x64 10.0.18836

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (33.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/68627

**Comment by isidorn** [comment]
Let's reopen this and try to get steps.
Since there still seems to be some corner cases where this still happens.
@Tyriar do you still see this? If yes, can you help us in getting steps?

fyi @joaomoreno

**Comment by Tyriar** [comment]
Yes I definitely still see this, the most recent instances have been when the file I'm trying to show is collapsed deep within the tree. I'll bookmark this issue and post when I see it again. Removing needs more info so it doesn't auto close.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/77106
Fixed via a timeout
@Tyriar please let me know if you stil see this.

**Comment by Tyriar** [comment]
Still having problems with this command, the state I had was I had an item in node_modules selected:

![image](https://user-images.githubusercontent.com/2193314/72174554-de874100-338e-11ea-9bcd-5863ee280e50.png)

Pressed my keybinding:

```json
{ "key": "ctrl+0",           "command": "workbench.files.action.showActiveFileInExplorer" }
```

And it just focused the same item in the explorer (@azure). The item that should has already been expanded down at the bottom of the tree. There is no longer an exception though, it just doesn't work.

**Comment by isidorn** [comment]
Let's reopen this, even though not sure how to fix.

**Comment by Tyriar** [comment]
I saw this again and it appears that one of the ancestor folders (which is currently off screen) is disposed already, despite it being expanded and its children not being disposed.

**Comment by isidorn** [comment]
From mine and Daniels chat, so we do not lose it. Assigning to May to try to find a fix then.

Isidor Nikolic Hello Daniel. Thanks for looking into it. That if check is there becuase the item might not be found in the explorer and then we should not do anything.
So the folder should not be disposed, that is the actuall issue.  Items gets disposed only when the explorer is refreshed, when there is a new fileSystemProvider registereted etc
Since you are on a WSL window it might be that the file system provider is regsitered late and that somehow fucks up the explorer.
If you would like to investigate deeper it would be cool if you put a breakpoint here https://github.com/microsoft/vscode/blob/78f299ee51a427e53b45f53df4b05dbb67e38e31/src/vs/workbench/contrib/files/common/explorerModel.ts#L321
ANd check out why in your case the item gets disposed.
If you are busy I can investigate deeper in debt week. Thanks!

**Comment by isidorn** [comment]
@Tyriar are you still seeing this after my explorer refactoring with latest vscode insiders? I did the refactoring one week ago which should be enough time to see if this got fixed?

**Comment by Tyriar** [comment]
@isidorn haven't seen it since, normally it's weeks between repros for me though. I'll ping you if I see it again, thanks!
