### ISSUE TITLE
Still failed to install extensions on linux behind proxy after half one year

### ISSUE THREAD

**Issue by keelung-yang** [microsoft/vscode#69324]
![image](https://user-images.githubusercontent.com/20385450/53317048-1c10e600-3905-11e9-82c1-dd1de389602c.png)

I confirm my http_proxy / https_proxy settings works for system and other application but VSCODE on linux.

About half one year ago, I upgrade VSCODE on linux in our company using proxy, and then it failed to install/upgrade extensions.  So I checked issuse list and wait for fixing in next release, after and after, again and again.

Untill now, IT STILL NOT WORKS! 
AND I SEE THERE ARE MANY MANY PROXY ISSUES CLOSED BUT NOT FIXED ACTUALLY!

**Comment by chrmarti** [comment]
@keelung-yang What proxy settings do you have in Chromium?

**Comment by keelung-yang** [comment]
@chrmarti I'm using KDE Neon, and Chromium is not installed. And no any proxy setting in VSCode.
My proxy settings is a shell script in /etc/profile.d/ 
```sh
export http_proxy=http://user:psw@host:port
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
export rsync_proxy=$http_proxy
export all_proxy=$http_proxy
export no_proxy="localhost,127.0.0.1,OUR_LOCAL_HOSTS"
```
and "Defaults env_keep += \"http_proxy https_proxy ftp_proxy rsync_proxy no_proxy" aslo in /etc/sudoers.d/proxy

It works until I upgrade vscode about half one year ago.

**Comment by chrmarti** [comment]
@keelung-yang Try starting VS Code with: `code --proxy-server=
http://user:psw@host:port`

**Comment by keelung-yang** [comment]
Still not work, @chrmarti 
![image](https://user-images.githubusercontent.com/20385450/54002870-0e702180-418b-11e9-8b9f-e89cae204b2e.png)

**Comment by chrmarti** [comment]
@keelung-yang Make sure you don't have a space after `=` (like my above comment had before I fixed it). It definitely shouldn't open a file with the proxy as its name.

**Comment by keelung-yang** [comment]
@chrisbenti Thanks. But I tried again after removing space but still not work.
The things make me crazy: Just an error reported, which is too general, but no more details about cause, like error code  and so on. SO I don't kown what's wrong and no place to dig it since other application & system tools work.

**Comment by Koushikphy** [comment]
I'm using ubuntu and working behind a proxy. I have to put the proxy authentication every time I open vs code , which is really annoying, but I can install extensions. I don't know whats causing you this problem. You do have internet connection on your terminal, right?

**Comment by keelung-yang** [comment]
@Koushikphy Yeap, The wget, curl,  apt-get work well without setting proxy for each.
![image](https://user-images.githubusercontent.com/20385450/54019116-56139f00-41c5-11e9-97be-44322b3c7ad6.png)

**Comment by tejasvi** [comment]
@keelung-yang You may try reinstall or VM to zero in on the issue because mine works fine after passing proxy parameters.

**Comment by keelung-yang** [comment]
@tejasvi I have reinstalled VirtualBox & Ubuntu 18.04.2, it's still doesn't work.

Now, The more important things is showing proxy error **in details**. It's better than just say 

> We cannot connect to The Marketplace at this time, Please try again later

 -- THIS IS TOO GENENRIC TO INDENTIFY ERROR.
 -- THIS IS AN TIP ISSUSE MORE THAN NETWORK PROXY ISSUSE.

My Environment:
- Windows 10.0.17134.590
- VitualBox 5.2.26
- Ubuntu 18.04.2

**Comment by evadeflow** [comment]
I have the exact same problem on Ubuntu 16.04: 

![image](https://user-images.githubusercontent.com/195848/62725011-443b5f80-b9e2-11e9-9083-4c39f088f4b4.png)

I'm tried setting the proxy both in the VS Code *Settings* dialog as shown below:

![image](https://user-images.githubusercontent.com/195848/62725087-73ea6780-b9e2-11e9-9eb2-762d74e0cec2.png)

and also on the command line, by launching using:

```
$ code --proxy-server=http://127.0.0.1:3128/
```

Nothing seems to work.

**Comment by chrmarti** [comment]
Does it work with Chromium? (`code --proxy-server=http://127.0.0.1:3128/` should work. Maybe the certificates are an issue.)
