### ISSUE TITLE
Sporadic "contents on disk are newer" issues when saving

### ISSUE THREAD

**Issue by forethoughtde** [Microsoft/vscode#7025]
- VSCode Version: 1.1.1
- OS Version: Fedora 23

The message appears randomly while writing code. It even makes saving the work cucumber-some at times.

**Comment by bpasero** [comment]
@pythondetective are you working against a network share? anything special about your setup?

**Comment by pythondetective** [comment]
There is nothing special about my setup. I am writing to local disk.

**Comment by bpasero** [comment]
@pythondetective when you do the "Compare" command can you grasp what the modifications are? Are you running another process in the background that modifies files?

**Comment by pythondetective** [comment]
I am not running another process in the background that modifies files. Sometimes, there are no modifications at all, just the same file. The problem arises whenever VSC takes long time to react to Ctrl+S.

**Comment by bpasero** [comment]
@pythondetective and then when you click on the "Compare" action, can you see what changes did occur meanwhile that VS Code blames?

**Comment by pythondetective** [comment]
Sometimes, "Compare" action takes way too long time to get to compare mode and shows the same file on both side with no changes. Sometimes, "Compare" action is quick and show changes in both file.

**Comment by bpasero** [comment]
@pythondetective how do you notice that the save takes long?

**Comment by pythondetective** [comment]
By dot in front of file name in the title bar.

**Comment by BusyJay** [comment]
Same issue here. But my situation is different.

I turn on auto save when lost focus. I make some changes and then go to terminal reformat the same file. When I go back to vscode, it won't reload the disk changes sometimes, in which case if I make changes to it again, it will promote the messages. And click compare doesn't help, it will keep promoting the messages and the two way comparison won't show up.

**Comment by bpasero** [comment]
Is this with files in a workspace (folder) or outside / when you do not open a folder?

**Comment by BusyJay** [comment]
Yes, it's the a file in my workspace.

**Comment by williamwgant** [comment]
I'm having a similar issue. I'm just editing markdown files that are shared through dropbox. However, I'm the only one with access to that dropbox directory. I did some digging and figured out that autosave was not happening, which meant that if I left VSCode open on my home desktop by mistake and then later attempted to edit the same files on my laptop, when I returned and closed VSCode on the desktop, that I would get this message. For my case, if the autosave works properly and the changes are merged in, I think it will probably work for me.

Is it possible that your autosave actually is working, but for some reason VSCode is not recognizing that it is the one that saved last?

**Comment by bpasero** [comment]
If you do not see the dirty indication in the editor it means the file is saved by VS Code if it was dirty before. However we use the modification timestamp of the file to find out if the contents on disk are newer. It looks like we might have to change this strategy and use a content hash instead (https://github.com/Microsoft/vscode/issues/919). Maybe the mtimes are not working properly in some cases.

**Comment by williamwgant** [comment]
I'm still testing around on it this morning. I've not gotten autosave working. I opened a folder to edit a bunch of markdown files. Nothing special. I'm doing the same on the laptop sitting right next to me. I can see when changes get pushed from the one computer to the other if a save actually happens. So my issue may be some sort of weird crossover issue from a config problem or something.

Any suggestions on stuff I can try to get more useful data for you? I'm stuck at home with a stomach bug, so....

**Comment by bpasero** [comment]
@williamwgant how does your Code settings look like? Do you see a dirty indicator?

**Comment by williamwgant** [comment]
I see a dirty indicator on the file itself. The settings.json for the workspace and the settings.json in my user directory both are as follows:

{
    "editor.wrappingColumn": 0,
    "editor.selectionHighlight": false,
    "files.autosave": "afterDelay",
    "files.autoSaveDelay": 1000
}

Umm. Something I just thought of. Is the specified delay in milliseconds? Or seconds? Cause the latter would explain some things.

**Comment by bpasero** [comment]
@williamwgant there is a typo in your setting, it should be `files.autoSave` and not `files.autosave`

**Comment by williamwgant** [comment]
Aww man. That's embarrassing.

So I've tried since and can't replicate the issue. I don't seem to be able to move fast enough to cause it. I even tried disconnecting the laptop from wireless and doing the changes. I'm not getting burnt now at all.

My podcast partner (on complete developer podcast) is going to give me a hard time for screwing up casing like that. We've also been burned on show notes because I didn't have the config setting named properly, so his stuff autosaves and mine doesn't. That's a huge pain point you just fixed for me, sir.

I presume the issue still exists, but probably needs a larger change set to actually manifest itself. I'm not sure of a good way to prove it though.

**Comment by bpasero** [comment]
No worries, I filed https://github.com/Microsoft/vscode/issues/7252 to warn when this happens in the editor.

**Comment by bpasero** [comment]
@forethoughtde do you run with any extensions installed?

**Comment by bpasero** [comment]
@BusyJay mind opening a new issue for your case? we have a 2 second window where we ignore changes made to a file outside VS Code. maybe you are fast enough to switch to the terminal and run your format command in under 2 seconds?

**Comment by forethoughtde** [comment]
There is no problem with newer version. @bpasero

**Comment by bpasero** [comment]
@forethoughtde so you say this issue is fixed for you?

**Comment by forethoughtde** [comment]
Yes, it is got fixed for me.

**Comment by DanZeuss** [comment]
Hi @bpasero, I'm still getting this error, however, I'm running it on a network share.

**Comment by johnhamm** [comment]
I'm getting this error running locally - it is happening sporadically.   I'm using vscode 1.8.1. Not sure if this will help shed light on the subject, but here's my workspace settings.json:

```
{
    "typescript.check.workspaceVersion": false,
    "editor.fontFamily": "Fira Code",
    "editor.fontSize": 14,
    "editor.fontLigatures": true,
    "editor.lineNumbers": "on",
    "editor.tabSize": 3,
    "editor.renderIndentGuides": true,
    "editor.rulers": [],
    "editor.formatOnSave": true,
    "files.autoSave": "off",
    "editor.mouseWheelZoom": true,
    "typescript.check.tscVersion": false,
    "php.validate.executablePath": "C:\\Program Files (x86)\\PHP\\v5.6\\php.exe",
    "auto-close-tag.activationOnLanguage": [
        "html",
        "xml",
        "php"
    ],
    "macros": {
        "collapseFoldersAndCloseFiles": [
            "workbench.action.closeAllEditors",
            "workbench.files.action.collapseExplorerFolders"
        ]
    },
   "files.exclude": {
      "node_modules/": false,
      ".vscode/": false,
      "config/": false,
      "dist/": false,
      "external/": false,
      "typings/": false,
      ".deployment": false,
      ".gitignore": false,
      "README.md": false,
      "tsconfig.json": false,
      "typings.json": false,
      "**/.git": false,
      "package.json": false,
      "gulpfile.js": false,
      "build/": false,
      "*debug.log": false,
      "**/.htaccess": false,
      "**/favicon.*": false,
      "sys": false,
      "src/main.ts*": false,
      ".htmlhintrc": false
   },
    "search.exclude": {
        "dist": true,
        "build": true,
        "public/js/": true
    },
    "toggleexcludedfiles.statusBar.enabled": true
}
```

**Comment by BrianJHodge** [comment]
This is occurring for me as well. I have a remote directory mounted via SSH. It happens about every other time I save a file.

Version 1.9.0

**Comment by meuwka** [comment]
I'm still getting this error
Version 1.9

**Comment by ryekerjh** [comment]
Still getting this as well

**Comment by rashnk** [comment]
I moved from vscode to sublime3 only because of this issue..very sad

**Comment by BrianJHodge** [comment]
@rashnk Something that's working for me as a temporary fix is the ftp-simple extension for Code.

**Comment by rashnk** [comment]
Im working with local project folder only, I suspect this behavior is by an installed extension, im going to disable all of them and clean installation

**Comment by rvanzon** [comment]
@rashnk any luck?

**Comment by meuwka** [comment]
Who wants to help: see here https://github.com/Microsoft/vscode/issues/13665#issuecomment-283320421

**Comment by bpasero** [comment]
@forethoughtde @ryekerjh @rashnk @BrianJHodge @johnhamm  does it still reproduce with our latest insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by egaris** [comment]
@bpasero new insider build fixed this annoying thing for me, thank you!

**Comment by bpasero** [comment]
That is really good news, I hope it stays like that.

**Comment by origin1tech** [comment]
Still hosed using OS X with QNAP NAS (running insiders)

Still getting bad descriptors content on disk newer. Seems to be purely a timing deal near as I can tell. Haven't had time but would like to help work on this. Any suggestions of where to start? 

thanks in advanced @bpasero

**Comment by bpasero** [comment]
@origin1tech where do you see the bad descriptors error?

**Comment by origin1tech** [comment]
@bpasero  on any save, like every one which is why it's a deal breaker.

**Comment by origin1tech** [comment]
@bpasero can you point to me in the vscode source where file saves occur? Thinking about firing up from source and tinkering with it.

**Comment by bpasero** [comment]
@origin1tech that would be nice, the saving code is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L313

Since I suspect this to be a node.js issue, maybe we could also try to distill this into a node script? After all we call `fs.writeFile()` somewhere in the end.

**Comment by origin1tech** [comment]
@bpasero O.k. I will look at this today and monkey with it. Give me a few hours.

**Comment by origin1tech** [comment]
@bpasero ...alright I'm working on it now going to focus on non-bom method then go from there.

**Comment by bpasero** [comment]
@origin1tech the error about the contents on disk being newer is actually already thrown here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L623

The idea is that if the file we have opened in the editor has a smaller `Stats.mtime` than the version on disk (e.g. someone modified it since), we throw this error. 

What would be interesting to find out is who and why the file is edited.

**Comment by origin1tech** [comment]
@bpasero I see, well I have a couple hours here I'll see what I can do. strong node background but haven't ever looked at code src may take a few go's at it to get acclimated, but I'll give it appropriate attention, can't be the only one experiencing this. Let u know how far I get in a bit...

**Comment by origin1tech** [comment]
@bpasero once I touch a file the descriptor errors go away. In fact

If I see this right changes are watched for and the focus file for lack of better term is stored in users (in case of OS X) ~/library/application support/.... then that's written to the actual absolute path.

O.K. better breakdown on what's happening here. The descriptor errors are only occurring after a move. once the IDE touches them once the error goes away. 

If I open a terminal while the IDE is OPEN and I just run like:

     $ touch some-file.ts

The editor will detect the change and I won't get an error. However moving a file into that same dir using the finder and dropping it in that folder via the finder will cause an error but only the first time it is opened from within the IDE.

**Comment by origin1tech** [comment]
@bpasero 

If you suppress the backup file from being cached at  /Users/Bob/library/application support/code-oss-dev/Backups/fac5c5aa68..../file/fac5c5aa68.... (on Mac in w/ Dev VSCode running).

Then save directly the error goes away. Again it only occurs when files are moved via finder and then opened in IDE. After first open and "compare" it's fine. 

Seems to be something with the backup/cached file conflicting when you then go to realize the file and actual write it out on that first save.

Have to look more at it later this week. Oh and writing a little script to touch all the files seemed to solve it as well but that's hacky and I didn't test it fully but it did circumvent the EBADF nag.

Again I'll look more into it in a day or so.

**Comment by rashnk** [comment]
tested after i disabled all extensions - no issue,
updated vscode to the latest. enabled extensions for my ionic2 workspace, now its working fine without any issue @rvanzon @BrianJHodge @bpasero

**Comment by origin1tech** [comment]
interesting. any idea which extension? probably not huh. I'm going to
continue with this, this weekend. I have some pretty good ideas now but ran
out of time earlier in the week.

**Comment by bpasero** [comment]
@rashnk awesome to hear that, thanks for testing

**Comment by origin1tech** [comment]
@rashnk <https://github.com/rashnk> tried your suggestion disabled
everything. Still the same behavior I'm rather certain at least in the case
of OS X to a NAS the issue lies with the cached backup and then when it
gets realized basically written out. It's a timing deal.

I need to get some spare time again this week to nail it down but near as I
can tell it seems the temporary cache of the file when written out already
things the destination is newer than it is.

When I logged it out it seems like Code somehow sees that it's at a newer
date than the actual file is.

Yes that's a bit captain obvious I get that but it became very apparent
when I logged out all the times from the file stats. Adding some custom
scripting touching files and so on did clear it up but again that's super
hacky at this point as to push that to the core without know why it fixes
it a bit risky. Anyway this is really something I want fixed so I'll keep
bangning on it just hard to find the time. If someone else gets to it first
I thank you in advance :)

**Comment by rashnk** [comment]
@origin1tech  did you update the vscode to latest, try that too

**Comment by rick4470** [comment]
Thanks for all the hard work on this issue!

**Comment by cr101** [comment]
Today I started getting this exact same error when I edit a .css file and save it. I noticed that when I save the format of my CSS code gets changed:
```
.container {
  display: flex;
  border: 10px solid mistyrose;
}
```
**changed to** 
```
.container {
  display: flex;
  border: 10px solid mistyrose; }
```

**Comment by bpasero** [comment]
@cr101 is this file locally or on a remote network? is there a chance that the file is being changed by another process maybe outside?

**Comment by rvanzon** [comment]
@cr101 are you using `node-dev` maybe? I had a similar problem with it. Switching to `nodemon` fixed it.

**Comment by cr101** [comment]
@bpasero The .scss file is on my local machine

@rvanzon I am using [create-react-app](https://github.com/facebookincubator/create-react-app) and the error appears after I run `npm start` which runs the watch commands below and when I save changes made to the .scss file. The interesting thing is that the error is random and it doesn't always occur on every .scss file save.

```
"scripts": {
"watch-css": "npm run build-css && node-sass src/ -o src/ --watch --recursive",
"start-js": "react-scripts start",
 "start": "npm-run-all -p watch-css start-js"
}
```
Here is the link to the [Create-React-App Adding a CSS Preprocessor](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc)

**Comment by rvanzon** [comment]
@cr101 I had the same with node-dev, also random (but a lot), I have the idea the files are maybe changed twice (maybe eslint?). The first time vscode reloads the changes, in that time it's changed again by the watcher. I am not sure.

Maybe you can fiddle around with create-react-app's timing or turn of eslint, just to test.

**Comment by bpasero** [comment]
If someone can give me exact steps how to reproduce this in a workspace I could have a look 👍

**Comment by origin1tech** [comment]
@bpasero Ben read my comments again I outline it a little but basically it is really obvious when you debug the ctime, mtime etc. Just haven't had time to finish tracking it down but when it actual goes to realize the write a watcher or something has already touched the temp/cached file. 

I got close with it but ran out of time and of course don't know enough about the source. When I did some manual things updating times I was able to circumvent the problem but that obviously isn't a fix but a hack.

Feel pretty confident it has to do with the cached file getting touched by Code itself then the issue presents itself when the file is actually realized  and written out. Times don't line up. 

May seem a bit captain obvious there but that's what it appeared to be. I should have some more time this weekend to take this further...

As far as recreating I'm not sure that's possible unless you have a Mac and a NAS. In my case a QNAP. I say that because on a friends Win box and FreeNAS I didn't see the issue.

**Comment by bpasero** [comment]
@origin1tech I see, so you are working against a network share? I was hoping for a repro that actually happens when working locally, that is why I was asking for some steps for me to reproduce that does not involve setting up a network share.

**Comment by origin1tech** [comment]
Oh my bad Ben missed that....

**Comment by bpasero** [comment]
There is still https://github.com/Microsoft/vscode/issues/13665 specifically for network share issues.

**Comment by origin1tech** [comment]
Yeah I've seen it. I'll try and put some more time into this soon. It is
truly something I need fixed but paying bills gets in the way :)

**Comment by Stanzilla** [comment]
Getting this a lot lately, on 1.14

**Comment by thomsa** [comment]
After update to 1.15.1 I'm getting this error constantly. Before that the same solution had no problem.

**Comment by zionyx** [comment]
1.16.1 has the same issue.
