### ISSUE TITLE
"Normal" filtering input for trees

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#70646]
Issue Type: <b>Feature Request</b>

https://code.visualstudio.com/updates/v1_31#_new-tree-widget

Is it possible to replace current filtering feature with an ordinary input element?

| normal input | filter on type |
|---|:---:|
|  ✅ standard element | ❌  |
| ✅ being able to have `simple` navigation and still filter items | ❌ |
| ✅ no clash with extension contributed keybindings | ✅❌ can be mitigated with `workbench.list.automaticKeyboardNavigation` & `list.toggleKeyboardNavigation`
| ✅ can paste text | ❌  |
| ✅ can `undo` | ❌ |
| ✅ can select text| ❌  |
|  ✅ good discoverability | ❌  |
| ✅ preverve text on reload | ❌ |
|  ❌ takes one row of space | ✅ only visible while typing  |
| ![outline_old](https://user-images.githubusercontent.com/9638156/124025742-7fd9db00-d9f9-11eb-917b-881900c538e1.png)  | ![outline_new](https://user-images.githubusercontent.com/9638156/124025664-69338400-d9f9-11eb-99ba-9e9a8f6c6b25.png) |

---

filter disappeared on outline view #70095
Performing a search on Outline #70640
Filter box in Outline has dissapeared in Release 1.32.3 #70605
Search field in structure side panel #70575
Search input field missing in new outline in Code 1.32.1 #70038

Yeah, you can tell those people where to find the "filter on type" feature, but all the new users potentially would never even know that it exists.

**Comment by MgSam** [comment]
To add my 2 cents- you really need to restore the search boxes. The filtering ability you guys added for trees is a nice idea but is absolutely horrible from a UX perspective. It has zero discoverability. And even once you know it exists, it still sucks because you have to give the tree focus by clicking somewhere random inside of it before typing. You can't possibly expect all your users to dig through documentation to learn how to perform a basic search.

A good rule of thumb for UX design is that if you're doing something no other application does, there's probably a reason why that is (and not because it's a great idea- people have been building GUIs for decades- there are precious few "undiscovered" UI paradigms left).

**Comment by martbean** [comment]
I agree. Added to which, for whatever reason 'Filter on Type' doesn't seem to work for me at all. Possibly one of my extensions is interfering with it but regardless, the old search box was much more user-friendly. Can it at least be an option?

**Comment by futurekill** [comment]
+1 From me...I had to search through github tickets to find out that 1. it was removed and 2. how to access that functionality. As it is now it's completely intuitive.

**Comment by JasonZough** [comment]
desperate for a filter box in outline  when writting Vue.

**Comment by 1vasari** [comment]
+1 - VS Code's Vim seems to eat my keyboard input, rendering this feature unusable. Please bring back a text box so that this works again. :heart:

**Comment by usernamehw** [comment]
Great.

**Comment by AlekSi** [comment]
> I.e. has it gathered more than 10 up-votes

Yes. Please re-open.

**Comment by usernamehw** [comment]
@AlekSi Assignee usually unsubscribes from the closed issues. You need to ping @joaomoreno

**Comment by usernamehw** [comment]
<sup>Just going to comment so this issue won't get locked and might get more upvotes in the future.</sup>

**Comment by Mingliang2018** [comment]
Looking forward this feature in the next release:)

**Comment by usernamehw** [comment]
The issue is closed not because it was fixed. It won't happen in the next release.

**Comment by Mingliang2018** [comment]
Hi Alex, 
How you said "It won't happen in the next release." but not fixed yet. Does it mean the input box for outline view will come back in VS Code 1.40.1?

I think many people are waiting for the return back of this feature.

**Comment by kh** [comment]
This is a must for me, filter on type feels so clumsy, the behaviour is unpredictable as you have to guess when you have the focus (sometimes you don't and you're editing the file instead of searching), you can't edit a character in the middle if you mistyped.

Along with #66971 this issue would bring a big boost in productivity.

**Comment by sketchbuch** [comment]
A filter field is badly needed, I don't want to just filter what is already in the view - like the already existing but completely hidden functionality. I want to be able to alter what tree items are rendered in the list based on user input.

**Comment by salgiza** [comment]
I wonder how many people read the release notes for v1.64, which includes an animation on how to move the outline to the new side panel, did it, though "oooh, cool this might be useful" followed by a "wait, how the hell do I search for a method in this panel?" (and that's the story of how I got here).

**Comment by bytehow** [comment]
This "filter on type" is so cumbersome, especially when using the Vim extension. I have to click on the "Outline" section header to give it focus but not move my cursor. I have to click it again because if it the panel was already open, the previous click collapses the panel. Now outline has focus, but I've got to 1) make sure Outline still has focus and 2) type `/` so I can enter Vim's search mode before I can start filtering.

PLEASE at least make the filtering input box an option!

**Comment by hntrewhitt** [comment]
It would be very useful to be able to search/filter the entire File Explorer tree (or the tree within a specific folder) based on filename/extension; being able to type something like **/*.js or a regexp like \.jsx?$ and see all the files in the whole tree (or tree within a folder) whose filename match that.

**Comment by MohamedLamineAllal** [comment]
is this feature no more working with `1.70.2`? When I type, I get taken to a. file that starts with the letter and does not activate the filtering mechanism ??

**Comment by MohamedLamineAllal** [comment]
I'll answer myself. There was an update. And the way it works now is by `Cmd + F` or `Ctrl + F` while focused on the tree. Way better.

**Comment by joaomoreno** [comment]
Doc update PR: https://github.com/microsoft/vscode-docs/pull/5588
