### ISSUE TITLE
Pale themes colors

### ISSUE THREAD

**Issue by sdfunes9** [microsoft/vscode#70782]
![Screenshot from 2019-03-19 16 23 44](https://user-images.githubusercontent.com/6377353/54646038-7d8b2700-4a63-11e9-8948-fd992f95a3c7.png)
Issue Type: <b>Bug</b>

Everytime I open VS code, it looks like there is a white shade all over the screen. It makes really dificult to read code, besides, when I'm working with CSS files I can't see the real colors I'm using

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU 847 @ 1.10GHz (2 x 888)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|3.56GB (0.43GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|1.8.1
terminal|for|0.0.10
vscode-language-babel|mgm|0.0.22
python|ms-|2019.2.5558
LiveServer|rit|5.5.1

</details>

**Comment by isidorn** [comment]
Change your theme color. F1 > Color Theme > choose something else
If still repros try with vscode insiders and that should fix it

**Comment by sdfunes9** [comment]
> Change your theme color. F1 > Color Theme > choose something else
> If still repros try with vscode insiders and that should fix it

well... I tried this before reporting the issue and still doesn't work, I don't think is a theme color issue I don't know if it has something to do with an update or something like that

In the image above, you'll see that there's something wrong with the color palette

**Comment by isidorn** [comment]
Also please try with vscode insiders https://code.visualstudio.com/insiders/

**Comment by sdfunes9** [comment]
Vscode insiders didn't help either, I'm having the same issue

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by sdfunes9** [comment]
Everything works fine now, VSCode exploration solved the issue. Thank you very much
![Screenshot from 2019-03-21 10 54 42](https://user-images.githubusercontent.com/6377353/54769892-c956e100-4bc7-11e9-8220-f7ed82a530cb.png)

**Comment by bpasero** [comment]
We will ship with Electron 4 with our upcoming release `1.36` this week. As such I am closing this issue. To benefit from the update already today, consider to use our insiders version: https://code.visualstudio.com/insiders/
