### ISSUE TITLE
upgrading installed 1.0 rpm to 1.1 removes /usr/bin/code and doesn't add a new symlink after upgrade.

### ISSUE THREAD

**Issue by wimcoekaerts** [Microsoft/vscode#7080]
- VSCode Version:
- OS Version:

Steps to Reproduce:

First problem : 

[root@ol6 ~]# ls /usr/bin/code
ls: cannot access /usr/bin/code: No such file or directory
[root@ol6 ~]# #install 1.0
[root@ol6 ~]# rpm -ivh /home/wcoekaer/Downloads/vscode-x86_64.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:code-1.0.0-1460557031            ################################# [100%]
[root@ol6 ~]# ls /usr/bin/code
/usr/bin/code
[root@ol6 ~]# #upgrade to 1.1
[root@ol6 ~]# rpm -Uvh /root/Downloads/vscode-x86_64.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:code-1.1.1-1463146452            ################################# [ 50%]
Cleaning up / removing...
   2:code-1.0.0-1460557031            ################################# [100%]
**[root@ol6 ~]# ls /usr/bin/code
ls: cannot access /usr/bin/code: No such file or directory**

second problem :

when I install 1.1 from scratch 

[root@ol6 ~]# rpm -ivh /root/Downloads/vscode-x86_64.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:code-1.1.1-1463146452            ################################# [100%]
[root@ol6 ~]# ls /usr/bin/code
/usr/bin/code
[root@ol6 ~]# rpm -e code
[root@ol6 ~]# ls /usr/bin/code
/usr/bin/code

it did not remove the symlink /usr/bin/code.

**Comment by Tyriar** [comment]
Should be fixed in 1.2 coming next week (#6338). The insiders build should work correctly now. In the meantime this should fix it:

```bash
sudo ln -s /usr/share/code/bin/code /usr/bin/code
```

**Comment by zeroum** [comment]
This symlink bug still remains in vscode 1.2, 1.2.1 and 1.3.

At least with Fedora 23 and using DNF as the installation tool, if you try to upgrade from a previous installation, with official rpms from code.visualstudio.com, it will clean up the previous version and install the new one correctly, except for the /usr/bin/code symlink.

Uninstalling the package, and installing it again, always using DNF, it will work as expected.

The command above, from Tyriar, fixes the problem.
