### ISSUE TITLE
 Tree element not found: [object Object]: Error: Tree element not found: [object Object]

### ISSUE THREAD

**Issue by pocesar** [microsoft/vscode#71126]
Version: 1.33.0-insider (user setup)
Commit: 1876bd1d3805d632a9aa78fad47b2c3c555f6eec
Date: 2019-03-25T14:53:36.371Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

```
[2019-03-25 23:47:57.303] [renderer3] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///F:/Users/Paulo/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:91:107)
    at s.isCollapsed (file:///F:/Users/Paulo/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:90:451)
    at j.isCollapsed (file:///F:/Users/Paulo/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:939:572)
    at B.revealMarkersForCurrentActiveEditor (file:///F:/Users/Paulo/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4602:105)
    at B.autoReveal (file:///F:/Users/Paulo/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4601:961)
    at B.onActiveEditorChanged (file:///F:/Users/Paulo/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4599:350)
    at B._register.e (file:///F:/Users/Paulo/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:4598:360)
    at d.fire (file:///F:/Users/Paulo/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:74:728)
    at setTimeout (file:///F:/Users/Paulo/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:71:135)
```

Steps to Reproduce:

1. Have 2 typescript files opened, have some errors on one (or two of them)
2. Switch between them

Does this issue occur when all extensions are disabled?: No

**Comment by DanTup** [comment]
I'm seeing this too (though with Dart). As I switch between these two files, note the count of errors counting up in the console.

![error](https://user-images.githubusercontent.com/1078012/58407907-a2ec7080-8064-11e9-8b01-a532913b98d2.gif)

**Comment by joaomoreno** [comment]
@DanTup Can you easily reproduce this issue?

**Comment by DanTup** [comment]
I'm not sure about easily! I do still see it a lot, but I don't seem to be able to repro it on-demand right now with either TS or Dart.

If I get to the point where I do see it again, is there anything I can do to try and get more info about what's going on?

**Comment by sandy081** [comment]
Probably the steps that you followed every time this issue appears. May be I can diagnose it from that.

**Comment by sandy081** [comment]
Reopening it as it is quite often reported in our error telemetry

**Comment by CaselIT** [comment]
I have the same error with version 1.36.1

Sadly I have not found a way to reproduce it. The only thing that I have noticed is that is has happened only on the test folder of a python project. But that may just be coincidence

**Comment by sandy081** [comment]
Fixed by b8d5f4cbf469e54586fcc7ce5a4fadfd32e57d32.

Above fix reuses the resource markers model, which means that if resource markers are updated, existing resource markers is reused instead of creating a new one. This will prevent tree and markers model to be out of sync.

**Comment by DanTup** [comment]
@sandy081 I'm still seeing what I think is this issue a lot in current insiders, for example:

https://travis-ci.org/Dart-Code/Dart-Code/jobs/597702388

```
TreeError [MarkersPanel] Tree element not found: [object Object]: Error: TreeError [MarkersPanel] Tree element not found: [object Object]
    at t.ObjectTreeModel.getElementLocation (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:135:801)
    at t.ObjectTreeModel.isCollapsed (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:135:14)
    at W.isCollapsed (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1032:72)
    at z.revealMarkersForCurrentActiveEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5849:628)
    at z.autoReveal (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5849:485)
    at z.onActiveEditorChanged (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5846:776)
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5845:754
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:114:390
    at c.fire (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:117:984)
    at e.doEmitActiveEditorChangeEvent (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4852:364)
    at e.handleActiveEditorChange (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4852:160)
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4852:474
    at c.fire (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:117:984)
    at file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5495:736
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async e.openEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5494:750)
    at async e.doOpenEditor (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4854:479)
    at async e.$tryShowTextDocument (file:///Users/travis/build/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3461:517)
```
