### ISSUE TITLE
Terminal scrolling issue

### ISSUE THREAD

**Issue by rajeevkumarsharma** [Microsoft/vscode#7118]
- VSCode Version: 1.2.0-Insider
- OS Version: Elementary OS

Steps to Reproduce:

1. When i execute a command in integrated terminal then output is not show properly and I am not able to scroll up and down sometime. i.e. some text is just hidden and scroll not functional.

**Comment by Tyriar** [comment]
What sort of command did you run? Also do you have screenshot(s) showing the issue?

**Comment by rajeevkumarsharma** [comment]
HI,

Here what i perform on terminal
![screenshot from 2016-06-02 12 53 54](https://cloud.githubusercontent.com/assets/8169482/15737019/3bfb33dc-28c1-11e6-8ef2-e6aacaca095c.png)


When i reduced terminal size then i was not able to scroll to see entire output i.e scrolling was not working and i am not able to run any command.

![screenshot from 2016-06-02 12 53 42](https://cloud.githubusercontent.com/assets/8169482/15737079/8d6066b6-28c1-11e6-91fd-072d163b85bd.png)

**Comment by Tyriar** [comment]
@rajeevkumarsharma thanks, I think this fits into the class of bugs that can be fixed by https://github.com/Microsoft/vscode/issues/6838

**Comment by rajeevkumarsharma** [comment]
@Tyriar yeah sure, I think, vscode terminal should have features from both black-screen and xterm.

**Comment by kliemohn** [comment]
I have had the same problem with a vertical scroll bar not appearing using v1.2.1.  I was really digging the terminal window, but need to be able to see history so I may have to go back to another command window for now.

**Comment by Tyriar** [comment]
@kliemohn there is still no scrollbar https://github.com/sourcelair/xterm.js/issues/77, but I believe this scrolling issue is fixed with the change to https://github.com/sourcelair/xterm.js

**Comment by ksnyde** [comment]
I'm having this issue still; is there anything I need to do? I'm using v1.3.1 of Code.

**Comment by Tyriar** [comment]
@ksnyde are you using oh-my-zsh? https://github.com/sourcelair/xterm.js/issues/151

**Comment by ksnyde** [comment]
Yeah I am. Thanks for the link to that thread @Tyriar .

**Comment by atian25** [comment]
I got the same problem with vscode@1.5.2 && oh-my-zsh
