### ISSUE TITLE
Title blurred out

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#71743]
Version: 1.34.0-insider
Commit: efa47d77cfd55cbad68bef54a2d765b73d7beb13
Date: 2019-04-03T20:23:50.493Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Has been happening for quite some time:

![image](https://user-images.githubusercontent.com/4033249/55590789-bde7d780-56e8-11e9-9b5d-63fe79652713.png)

The good ones, by comparison:

![image](https://user-images.githubusercontent.com/4033249/55590808-ce984d80-56e8-11e9-8f92-571f08ea7778.png)

I'm not sure what's the exact repro though.

**Comment by sbatten** [comment]
@octref please check zoom in dev tools and also compare with text in explorer/panel/statusbar

**Comment by octref** [comment]
No zoom, text in explorer/panel/statusbar all look normal in the blurry window.

**Comment by jrwiegand** [comment]
I am seeing this issue as well. For some more clues to the issue I have included screenshots of the titlebar with the dev tools open. 

1. Unmodified:
![Screen Shot 2019-04-17 at 3 20 46 PM](https://user-images.githubusercontent.com/1606617/56315012-ad8e1e80-6124-11e9-81cb-1ea9bfd50605.jpg)

2. Removed the `zoom` property:
![Screen Shot 2019-04-17 at 3 21 37 PM](https://user-images.githubusercontent.com/1606617/56315047-c1398500-6124-11e9-98e7-c3eede80e51c.jpg)

3. Remove the `position` property:
![Screen Shot 2019-04-17 at 3 21 17 PM](https://user-images.githubusercontent.com/1606617/56315078-d1e9fb00-6124-11e9-8da1-c6b3fffc255a.jpg)

I hope this is helpful to anyone viewing this issue.

**Comment by eddiemonge** [comment]
Mine is blurry as well. Toggling a property like flex brings to into focus but it should be like that by default

**Comment by Torvaldi** [comment]
I have the same problem on my Ubuntu 18.04 installation. When the file is saved, the title bar text is blurred, but not when I am editing...

Configuration :
> Version : 1.33.1
> Validation : 51b0b28134d51361cf996d2f0a1c698247aeabd8
> Date : 2019-04-11T08:20:22.771Z
> Électron : 3.1.6
> Chrome : 66.0.3359.181
> Node.js : 10.2.0
> V8 : 6.6.346.32
> OS : Linux x64 4.15.0-48-generic

Screenshots : 
- Blurred : ![image](https://user-images.githubusercontent.com/7703951/57728742-ed4d1500-7694-11e9-94c5-2427a19e3dca.png)
- Not blurred : ![image](https://user-images.githubusercontent.com/7703951/57728816-0f469780-7695-11e9-966b-23e543e38e62.png)

**Comment by whitetrident** [comment]
I use vscode on both windows and linux. The problem is not found on the window. When switching the application out and switching back on LINUX (deepin), I find that the file title will appear fuzzy, and the width corresponding to the file title is non-integer. Happening. Has been solved by the following css:
.monaco-workbench .part.titlebar>.window-title {
    width: 800px;
    display: flex;
    align-items: center;
    justify-content: center;
}

**Comment by andremacola** [comment]
Confirm on OSX Mojave and High Sierra.

Sometimes is fine.

![blur](https://user-images.githubusercontent.com/3408809/58754950-932fba80-84b0-11e9-95fe-d4a3a9a7c505.gif)

**Comment by bpasero** [comment]
@octref and others, does it reproduce in Exploration builds?

We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by andremacola** [comment]
> @octref and others, does it reproduce in Exploration builds?
> 
> We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
> 
> * macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
> * Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
> * Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

Hi @bpasero apparently in Exploration the problem is fixed. OSX Mojave 10.14.5 (18F203)

**Comment by cynecx** [comment]
I am still experiencing this.

```
Version: 1.36.0-insider
Commit: c089daa858f34631f5f827ff8a0313bf1e2ded6d
Date: 2019-06-07T05:15:26.964Z
Electron: 4.2.3
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.1.7-arch1-1-ARCH
```

![issue](https://user-images.githubusercontent.com/5961244/59160968-a9ef9600-8adc-11e9-9469-1cd7ca789eda.png)

**Comment by Torvaldi** [comment]
The insider version does not correct the problem but the bug appears only when using **custom title bar style**.
```JSON
{
    "window.titleBarStyle": "custom",
}
```
```text
Version : 1.36.0-insider
Validation : 15b7c86d86319b187a5ef255c170184a8519c5af
Date : 2019-06-14T10:33:50.651Z
Électron : 4.2.4
Chrome : 69.0.3497.128
Node.js : 10.11.0
V8 : 6.9.427.31-electron.0
OS : Linux x64 4.15.0-51-generic
```

**Comment by sbatten** [comment]
Please verify if this fix: https://github.com/microsoft/vscode/issues/75615 addresses the issue in tomorrows insiders version.

**Comment by Torvaldi** [comment]
Nothing changed... Sorry

**Comment by adriang133** [comment]
I'm also getting this, only with some files.

VSCode 1.35.1
macOS 10.14.5

**Comment by l0ud** [comment]
Still getting this on Linux Manjaro-Deepin.
VSCode 1.34.0
Central part of title bar is blurry depending of displayed content and window width. I can easily reproduce this by resizing window issue happens. Menubar is not affected.
I cannot reproduce this issue when I have developers tool open regardless of its position, which is weird.

**Comment by MrChenWithCapsule** [comment]
I also got this problem when using the NVIDIA GPU, but when I changed the settings to use the Intel GPU, the problem was gone.

**Comment by krmbzds** [comment]
> VSCode 1.35.1
> macOS 10.14.5
> External monitor, macOS font smoothing is off.

Slightly resizing the window blurs the title. Resizing a little more sharpens it again.

![Screen Shot 2019-07-01 at 03 43 48](https://user-images.githubusercontent.com/1383035/60404603-33155c80-9bb3-11e9-9742-5763e62eb649.png)
![Screen Shot 2019-07-01 at 03 43 59](https://user-images.githubusercontent.com/1383035/60404604-33155c80-9bb3-11e9-8a52-3a617c2aff67.png)

Yet, for some titles it resizing the window doesn't work at all.

**Comment by David-Else** [comment]
It is happening here on the latest 1.36 with the new electron 4. Some files names seem to mysteriously not be affected.
![1](https://user-images.githubusercontent.com/12832280/60620729-e066bb00-9dd3-11e9-8609-bc8591d5fd39.png)
![2](https://user-images.githubusercontent.com/12832280/60620730-e066bb00-9dd3-11e9-9ce3-475a71eec530.png)

**Comment by andremacola** [comment]
It is happening in insider version. Exploration for me is fine

**Comment by zapateo** [comment]
Same problem with `1.38.0-insider` (x64).

Some characters appear corrupted:

![Schermata da 2019-08-12 15-25-33](https://user-images.githubusercontent.com/11294400/62868466-04dc7e00-bd16-11e9-97cf-a7cf389a1ed5.png)

Running on Fedora 30 with Gnome Shell (Wayland).

**Comment by deepak1556** [comment]
Hi all, could you try the new explorations builds based on electron 6 and chromium 76 to see if there is progress on this issue ? Thanks!
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)

**Comment by jasonwilliams** [comment]
I can give this a go, thanks, ping me if you don't hear from me

**Comment by zapateo** [comment]
@deepak1556 thanks :)

I tried the build and I cannot reproduce the issue, the title bar looks fine, it's neither blurred nor corrupted.

Running on Fedora 30 with Gnome Shell (Wayland), VSCode version 1.37.0-exploration (960208fdf9aa06e6892aa14c9c84ddd607fbeb2f).

**Comment by jasonwilliams** [comment]
@deepak1556 
Testing this on:
MacOS Version 10.14.5 (18F203)

On VSCode (1.37 stable) the blurring is intermittent, sometimes it blurs sometimes it doesn't, not sure why. On the exploration build I can't reproduce it to blur so that's good. 

**Video**
The first editor is my VSCode Stable: Version: 1.37.0
You can see that `Cargo.toml` does not blur, but the other files do, i'm not sure why this is the case.
The second editor in the foreground is : Version: 1.37.0-exploration
None of the files blur.
![kaptureVSCode](https://user-images.githubusercontent.com/936006/62932348-d7e0a780-bdb7-11e9-9e80-f716a4d8d26a.gif)

Hopefully this is useful.

**Comment by ecgan** [comment]
With the latest 1.38.0 release, this issue seems to be fixed already. Title bar text looks good no matter how I switch the tabs around. Thanks! :+1: :smile: 

![image](https://user-images.githubusercontent.com/417342/64398032-f58eed00-d095-11e9-87d5-c02ed8d3c46b.png)

Version: 1.38.0
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:51:09.716Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-60-generic

**Comment by zapateo** [comment]
The problem seems resolved with 1.38.0. Thanks!

**Comment by jasonwilliams** [comment]
Does anyone know what fixed it? Looks like the difference between 1.37.0 and 1.380 was this in electron https://github.com/electron/electron/compare/v4.2.7...v4.2.10

**Comment by jrwiegand** [comment]
The problem looks fixed to me as well. I am not sure what fixed it.

**Comment by sbatten** [comment]
@deepak1556 should we expect this fixed?

**Comment by Torvaldi** [comment]
Looks like it's corrected for me too, I'm pretty sure that the commit [13cf7b0](https://github.com/electron/electron/commit/13cf7b0bc0b05bff94c68716cdcf313e287e3196) of Electron solved the problem

**Comment by cynecx** [comment]
@Torvaldi How would that change, which is macOS related, correct the title blurring on linux?

**Comment by bpasero** [comment]
Is it still good for people with our latest insider builds that use Electron 6?

**Comment by NullEnt1ty** [comment]
This bug seems to be fixed for me.
