### ISSUE TITLE
watcherService CPU/RAM usage

### ISSUE THREAD

**Issue by jabbson** [microsoft/vscode#71945]
Issue Type: <b>Performance Issue</b>

watcherService seems to be using way too much CPU and RAM

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:11:32.076Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 8|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	    82	 82473	code main
   13	    49	 82475	   gpu-process
    0	    82	 82476	   window (Untitled-2 — jabbson)
    0	    25	 82479	     extensionHost
  130	  2318	 82480	     watcherService
    0	    57	 82481	   shared-process
    7	    74	 82799	   window (Issue Reporter)
    0	     0	 82800	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled-2 — jabbson)
|    Folder (jabbson): more than 22115 files
|      File types: localstorage-shm(1731) localstorage-wal(1731) plist(965)
|                  log(931) exp(816) c(713) JPG(684)
|                  localstorage(672) png(619) o(582)
|      Conf files: makefile(44) package.json(24) settings.json(22)
|                  launch.json(8) tslint.json(4) tsconfig.json(2)
|                  tasks.json(2) webpack.config.js(1) gulp.js(1)
|                  jsconfig.json(1);
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.2.11
vscode-sqlite|ale|0.6.0
code-gnu-global|aus|0.2.2
kivy-vscode|Bat|0.5.0
django-snippets|bib|1.1.1
flask-snippets|cst|0.1.0
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gc-excelviewer|Gra|2.1.31
CppSnippets|har|0.0.13
applescript|idl|0.14.2
dotenv|mik|1.0.1
vscode-clang|mit|0.2.3
HTMLHint|mka|0.6.0
vscode-remote-workspace|mkl|0.42.0
language-gettext|mro|0.1.1
python|ms-|2019.3.6352
cpptools|ms-|0.22.1
Go|ms-|0.9.2
printcode|nob|3.0.0
vscode-docker|Pet|0.6.1
mako|tom|0.2.0
sort-lines|Tyr|1.8.0

</details>

**Comment by jabbson** [comment]
This appears to have been related to the source control features. Closing repos made the watcherService to calm down.

**Comment by pwaller** [comment]
Apologies if I'm hijacking an issue inappropriately, but this does read very much like an issue I'm facing at the moment.

I'm having a significant problem with CPU usage in the watcher service. It's burning all my CPU/battery continuously for tens of minutes.

Some notes:

* I have a directory in my project `/outputs/` with >8,000,000 files in it in a complex data structure containing generated data that I don't want to edit with vscode.
* VSCode instructed me to increase the system `fs.inotify.max_user_watches` if I wanted watching to work, so I did.
* Suddenly, vscode now uses huge amount of CPU (800%) in `code .../bootstrap-fork --type=watcherService`.
* I'm happy for vscode to ignore this directory. I have the following workspace-specific configuration, which seems to help reduce the CPU usage but does not eliminate it:
    ```json
    {
            "git.ignoreLimitWarning": true,
            "files.watcherExclude": {
                    "/outputs/**": true
            },
            "search.exclude": {
                    "/outputs/**": true
            },
            "files.exclude": {
                    "/outputs/**": true
            }
    }
    ```
* The CPU usage is not reported within vscode's process manager, making it hard to determine why this happened.
* I've tried using the developer tools "performance" and "javascript profiler", but neither of these show the 
* I added `/outputs/**` to all of the exclude directives in the workspace.
* This command takes a while to run and produces a large output, I caught it in my process listing, and it might be related.

    ```
    $ time git status -z -u | wc -c
    676449428
    
    real	0m11.261s
    user	0m9.100s
    sys	0m2.486s
    ```
* The CPU usage does eventually cease, but it is tens of minutes after opening vscode.
* If I close and reopen vscode, the CPU usage reoccurs - which is inconvenient as I do need to restart the editor occasionally due to issues with the language server that I'm using.
* Moving the large directory out of my directory tree does solve the CPU issue. But I don't want to do this.
* `strace` shows the process doing lots of futex/madvise/mmap/munmap syscalls, but no obvious filesystem activity. `perf top` shows the process is spending lots of time in the nodejs runtime.
* I haven't yet been able to find a way of discovering what the nodejs code is doing within that process. Advice appreciated here so that I can feed back more detailed information.

**Comment by Leo1003** [comment]
I think the memory issue is related to the bug in [Axosoft/nsfw](https://github.com/Axosoft/nsfw). 
[Details](https://github.com/Axosoft/nsfw/pull/74)

**Comment by Tyriar** [comment]
I'm watching the repo, we should update our fork when nsfw does a release.

**Comment by Tyriar** [comment]
It was released, we should update https://github.com/Axosoft/nsfw/releases/tag/v1.2.3

**Comment by enzious** [comment]
Please update the fork :) This is crashing my machine over and over again.

**Comment by Leo1003** [comment]
@enzious  Currently, not to open two directories in single vscode window can avoid it to use nsfw as its watcher. This is the method I use to prevent this bug before the bug is fixed in vscode.

**Comment by enzious** [comment]
I compiled vscode with nsfw v1.2.4 and it's still an issue with the two memory leak fixes.

![image](https://user-images.githubusercontent.com/4645608/59947633-56157300-9433-11e9-9dc0-d9e2e73fad0e.png)

**Comment by enzious** [comment]
Here's a memory image of the memory leak:
![image](https://user-images.githubusercontent.com/4645608/59950521-caecab00-943b-11e9-8f9c-467c38a064e7.png)

**Comment by enzious** [comment]
If you break it up like this it looks like a struct leak: 
![image](https://user-images.githubusercontent.com/4645608/59951971-46e8f200-9440-11e9-950a-4b55fcc97ae7.png)

**Comment by Leo1003** [comment]
I currently can't figure out why some memory are not freed until the program terminted. I think it may related to c++'s allocator.

**Comment by enzious** [comment]
@Leo1003 What happens to the memory set back to Node through the callbacks? Is it being handled correctly?

**Comment by bpasero** [comment]
Fyi with https://github.com/microsoft/vscode/pull/76434 we are using the official released `v1.2.5`

**Comment by Tyriar** [comment]
I think this is fixed now with the nsfw update
