### ISSUE TITLE
Touch Bar icon appearance does not comply with macOS Human Interface Guidelines

### ISSUE THREAD

**Issue by SniperGER** [microsoft/vscode#72047]
Issue Type: <b>Bug</b>

1. Get your hands on a MacBook Pro with Touch Bar
2. Open Code
3. Look at your Touch Bar

If you don't see the Debug Controls, you might have disabled the Touch Bar for Code. Go to System Preferences → Keyboard → Function Keys and remove "Visual Studio Code.app" from the right hand list.

According to Apple's [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/touch-bar/touch-bar-icons-and-images/), Touch Bar icons should be ideally 36x36px in size (at 2x) in a 60x60 px rectangle, with a maximum size of 48x48px (at 2x). As you can see in the screenshot below, the icons fill in the full height of a Touch Bar button.

VS Code version: Code - Insiders 1.34.0-insider (07d9e44f910223e7ab6d3e8bc02439f39213cd90, 2019-04-10T05:14:23.598Z)
OS version: macOS Sierra 10.12.6 (Darwin x64 16.7.0)

Screenshot(s):
<img width="1085" alt="Touch Bar Bild 2019-04-10 um 09 03 51" src="https://user-images.githubusercontent.com/6178765/55858602-6c1fd100-5b70-11e9-848e-edfd05456618.png">

**Comment by misolori** [comment]
@bpasero do you know if this could be an electron issue with Sierra (10.12)? I'm on Mojave (10.14) and don't see this on my mac's touchbar or in the touchbar simulator:

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/35271042/55901905-2e767480-5b7f-11e9-8c84-cfc1fa38f1df.png">

**Comment by misolori** [comment]
I'm using the correct icon sizes based on Apple's guidelines:

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/35271042/55903216-00466400-5b82-11e9-9641-4234d8fe1285.png">

**Comment by SniperGER** [comment]
I've just tested this with 07d9e44 on Mojave 10.4.2 (haven't used it in a while), and the icons seem to be fine here.

**Comment by bpasero** [comment]
@SniperGER what is different between the versions you test?

**Comment by SniperGER** [comment]
Not much actually. I'm running Code from the exact same binary (```/Volumes/Macintosh HD/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron```, Mojave is installed to ```/Volumes/Mojave```) with the same extensions (Vetur 0.18.1, vscode-icons 8.5.0) and the same user preferences files (copied them from Sierra to Mojave).

And yes, I've tested this with ```--disable-extensions``` and the icons are still sized incorrectly.

**Comment by bpasero** [comment]
@SniperGER I do not understand the difference than, both builds are insiders right? So this is fixed now?

**Comment by SniperGER** [comment]
No, it's not fixed. The only difference here in testing is the version of macOS I'm using: Sierra 10.12.6 and (meanwhile) Mojave 10.14.4. Other than that, there are no differences whatsoever.

In Mojave, the icons are just fine, but they're not on Sierra, which is still my main Operating System because Mojave still has a pretty bad battery drain for me (same with High Sierra).

**Comment by bpasero** [comment]
Ah ok got it :+1: 

I doubt we can fix this unless we would pull in difference icons for different releases of macOS.

**Comment by aeschli** [comment]
@bpasero You want to close the issue then?
