### ISSUE TITLE
Backspace, left and right in Windows integrated terminal cause prompt to go out of sync in Git bash

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/vscode#7345]
- VSCode Version: 1.2.0-insider
- OS Version: Windows 10
- Terminal: Git bash

Steps to Reproduce:
1. Invoke the new integrated terminal
2. type command
3. backspace to delete some characters
4. Notice that while the command executed will be accurate to what was typed, the display of the line will be out of sync with the internal state of the terminal.

**Comment by JasonKleban** [comment]
("Cannot set property 'innerHTML' of undefined" when invoking terminal too sometimes)

**Comment by Tyriar** [comment]
I haven't actually seen this, could you include a screenshot or a gif? I'm assuming you set it to the bash.exe not the git bash executable also?

**Comment by JasonKleban** [comment]
OK, this is happening very easily to me.  Unfortunately I couldn't figure out any modern programs that show the actual keystrokes in an overlay for Windows (anybody know??) and this isn't a *great* capture, but it does show it happening a few times, should be obvious without the keystrokes showing.  On the first line when I try to delete all the text including "echo", I can't backspace any more but the echo still shows.  executing what looks like `echo whatever` is really just `whatever` in the buffer.

Then the next line I just show that `echo whatever` without any backspaces normally works fine and got a surprise that the newline wasn't printed!

Then I tried a third example and that one exhibited no glitches finally.

![echo](https://cloud.githubusercontent.com/assets/17498172/15872600/4adde006-2cc8-11e6-9602-cf06b178d240.gif)

**Comment by moshahmed** [comment]
Windows7 Start > cmd > cd c:\gitportable-209-x64\bin > bash.exe 
user@host MING64 /bin
$ ast<backspace becomes space>

This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Segmentation fault

**Comment by gerane** [comment]
I get this in powershell too. I don't use cygwin so it is not caused by that when I am in PowerShell.

**Comment by gerane** [comment]
I also see issues when moving left and right. The visual cursor can get slightly out of sync with where it really is. Usually it is a space or 2 when it happens.

**Comment by Tyriar** [comment]
@gerane I feel like this is fixed in Insiders now, I can't reproduce anymore. Have you seen it recently?

**Comment by gerane** [comment]
@tyriar I still see the visual cursor in the wrong place occasionally. Almost always by a single space.

 It might show in one spot but is really 1 to the left or right. If I move the cursor, the visual cursor might lag behind or skip ahead by 1 space of where the actual cursor is located. Then if I enter input it isn't input where the visual cursor shows it should be.

**Comment by Tyriar** [comment]
Cannot repro:
- `"terminal.integrated.shell.windows": "\\windows\\system32\\cmd.exe"`
- `"terminal.integrated.shell.windows": "\\windows\\sysnative\\cmd.exe"`
- `"terminal.integrated.shell.windows": "powershell.exe"`
- `"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe"`

Can repro:
- `"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`

Updating Windows now to try `"C:\\Windows\\sysnative\\bash.exe"`

**Comment by JamesEarle** [comment]
Related to this (shown below), when you type any command that has parameters in quotation marks, typing `somecommand ""` and then using left arrow to move the cursor back between the quotation marks throws it out of sync. Specifically, it will insert additional quotation marks while you're typing.

![vscode_bug](https://cloud.githubusercontent.com/assets/5976499/19361021/ca9618fa-9135-11e6-9a1f-f84eab649256.gif)

**Comment by PontusRenmarker** [comment]
Hi!
Backspace works as a space button for me. I am unable to reproduce what @JasonKleban displayed. 
But I can reproduce the problem with quotations and left arrow in git bash but not in either powershell or cmd. Running windows 10 pro N. 

Have you found any working solution?

**Comment by ffes** [comment]
With the Cygwin bash this problem occurs this well.

**Comment by plhosk** [comment]
This problem is happening for me on Windows 10 (version 1607 build 14393.447) with VSCode 1.7.1 and Git for Windows 2.10.2.

When I use bash.exe as the integrated terminal, the backspace or arrow keys cause the cursor to become out of sync with what's printed on the screen.

**Comment by Tyriar** [comment]
I've started tracking all issues like this in https://github.com/Microsoft/vscode/issues/14613 as I believe they're all related.

**Comment by Tyriar** [comment]
This should hopefully be fixed in tomorrow's Insiders build (via https://github.com/Microsoft/vscode/commit/63f1fa66800bf641de5e36027610503ba75085b5). Please let me know if it still reproduces.

See https://github.com/Microsoft/vscode/issues/13625 for more information.

**Comment by Acidic9** [comment]
I have had this out of sync issue in the Visual Code terminal with git bash since I downloaded Visual Code (a few months ago) and it has never been solved.
**I just downloaded the Visual Code Insiders Build and I can confirm it is now working correctly.**

**Comment by Tyriar** [comment]
@Acidic9 great to hear! It's likely around 2 weeks off.

**Comment by Kenya-West** [comment]
Same here, man. It happens on different sizes of window.

Specs:
Windows 10 Creators Update x64
VS Code up-to-date
bash (Ubuntu on Windows)/Powershell/Whatever
![terminal-is-out-of-sync](https://cloud.githubusercontent.com/assets/12271104/26062809/e47f0b7a-39c6-11e7-99f5-ad3fbef6a6eb.gif)

**Comment by Tyriar** [comment]
@Kenya-West that issue is https://github.com/Microsoft/vscode/issues/19665
