### ISSUE TITLE
SmartSelect: Inconsistent behavior in json strings

### ISSUE THREAD

**Issue by hannesfrank** [microsoft/vscode#73630]
- VSCode Version: 1.34.0 Insiders (fresh install, no Extensions)
- OS Version: Linux
- Language Mode: Json (unless stated otherwise)

Often `editor.action.smartSelect.expand` does not behave in a useful way, i.e. it does not respect word boundaries or quotes.

I have read that `smartSelect` implementation got simplified and extensions should provide fine grained selection increments, but some selection increments seem to be inconsistent, not helpful or just wrong and not just not fine grained enough.
Also `json` should work out-of-the-box (at least I did not find working language support)?

---

Below are some cases to document the behavior:

```json
{
    "line1": "OneTwo.ThreeFour",
    "line2": "one-two.three",
    "line3": "one-two-three",
    "line4": "one=two!three",
}
```

In each line I put the cursor on each word `one`, `two`, `three`, ... and trigger `Expand Selection`.

Word boundaries is the default setting of `~!@#$%^&*()-=+[{]}\\|;:'",.<>/?`.

Here is what happened and what I would expect to happen. Brackets indicate the selection after triggering `Expand Selection`:

- Line 1:
    - `One`: There are actually different behaviors for different Language Modes:
        - Markdown text: `"line1": "[One]Two.ThreeFour"`. OK. Everything works fine here. It behaves like double clicking (see note below).
        - Markdown json fenced codeblock: `"line1": ["One]Two.ThreeFour"`. **Wrong.** Left selection boundary outside quotes.
        - Json Language Mode: `"line1": "[OneTwo.ThreeFour]",` OK. Selects inside quotes. Though one extra step on word boundaries would also be nice. I did **not expect** that this would behave differently from fenced codeblocks.
    - `Two`, `Three`: 
      - `"line1": "One[Two.Three]Four",` **Unexpected.** Seems to select CamelCase. I would expect it to select inner quotes or word boundaries.
      - Triggering again gives `"line1": ["OneTwo.ThreeFour"],` OK. Next select is outside quotes. I would expect inside quotes first, but it is ok. 
    - `Four`: `"line1": "OneTwo.Three[Four"],` **Wrong.** Right selection boundary outside quotes.
- Line 2:
  - `one`: `"line2": "[one-two.three]"` Ok. Selects inside quotes
  - `two`, `three`: `"line2": "one-[two.three"]` **Wrong.** Right selection boundary outside quotes.
- Line 3:
  - `one`: `"line3": "[one-two-three]"` Ok. Selects inside quotes
  - `two`: `"line3": "one-[two]-three"` Ok. Selects word
    - **Except** if the cursor is between `o` and `-`. `"line3": "[one-two-three]"`**Inconsistent.** Then it selects inside quotes.
  - `three`: `"line3": "one-two-[three"]` **Wrong.** Right selection boundary outside quotes.
- Line 4:
    - `one`, `two`, `three`: `"line4": "[one=two!three]",` OK. Selects inside quotes. Does not respect word boundaries though.

It seems that CamelCase and `-` count as a boundary, but `.` and other word boundary characters do not.

**Note:** Selection by double clicking works as expected:
- It selects word parts stopping at word boundaries.
- It selects CamelCase as a whole.

**Comment by inwardmovement** [comment]
Indeed, it's annoying not being able with `editor.action.smartSelect.expand` to select inside quotes for cases like this:

    "editor.tabSize"

which results, when the cursor is anywhere around `Side`, in:

    "editor.tab[Size"]

where `[...]` is the selection.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/commit/81380bb822effd42006764f81ffaabeff4745009

**Comment by rebornix** [comment]
> two, three: "line2": "one-[two.three"] Wrong. Right selection boundary outside quotes. 

I can still see this happening

![smart-expand](https://user-images.githubusercontent.com/876920/62316457-58181c00-b44c-11e9-8f56-0f27b305a4da.gif)

**Comment by aeschli** [comment]
@rebornix I can't reproduce this. What version do you see it? Is the editor in JSON mode?

**Comment by aeschli** [comment]
It's the default smart selection provider which struggles with special word rule that JSON has (`"` are part of the word/token)
