### ISSUE TITLE
Regex replace substitution

### ISSUE THREAD

**Issue by cheng93** [microsoft/vscode#73813]
Please search existing issues to avoid creating duplicates.
Also please test using the latest insiders build to make sure your issue has not already been fixed: https://code.visualstudio.com/insiders/

I don't have time to check this unfortunately.
I have searched, but nothing specifies the regex substition, they are either lots of files or similar

- VSCode Version: 1.33.1
- OS Version: Windows 10

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/13205912/57846821-f93bf280-77cc-11e9-9099-1d2392a5bf56.png)

notice how 4/5 have `$1` and one is successful

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheng93** [comment]
looks to be an issue with the anchor `$` in the search

**Comment by roblourens** [comment]
This appears to be another CRLF related issue, I can reproduce

**Comment by roblourens** [comment]
Will also probably be fixed by ripgrep's --crlf flag

**Comment by roblourens** [comment]
Should be fixed in the next insiders

**Comment by felixfbecker** [comment]
This is a pretty bad bug to a core feature, could we get a patch release for this?

![2019-07-06 13 22 00](https://user-images.githubusercontent.com/10532611/60755524-3a909780-9ff1-11e9-8416-cdfa42e2482d.gif)

**Comment by felixfbecker** [comment]
This is still happening in latest insiders:

Version: 1.37.0-insider
Commit: 7e03eb1a1fce3beb6ccea5f3b8f828e01940be61
Date: 2019-07-05T18:25:58.865Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

**Comment by cheng93** [comment]
Think you need to use a capturing group in your regex.

`example\['(.+)'\]`

**Comment by felixfbecker** [comment]
🤦‍♂
