### ISSUE TITLE
VSCode remote cpp debug not working

### ISSUE THREAD

**Issue by liushiqi9** [microsoft/vscode#73987]
### System Version
Version: 1.35.0-insider (user setup)
Commit: a5536b8f5a16a10d859f3dec1e59701671bf069e
Date: 2019-05-20T05:17:36.269Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

### Steps to Reproduce:

1. Download lastest vscode insider with remote extension package and C/C++ extension.
2. Connect to a Arch server with remote ssh.
3. git clone https://github.com/microsoft/vscode-remote-try-cpp.git
4. Set a breakpoint at line 7.
5. Press F5
6. The debug hangs, binary is compiled, but the gdb is not started. A little blue box is running on left top conner.

Other details(Logs) are listed [here](https://github.com/microsoft/vscode-remote-try-cpp/issues/2). I reported to both repo because I am not sure which one is the correct one. 

All help needed, Thx.

**Comment by stevehaigh** [comment]
I repro the same issue, in fact it is not just over remote, C++ debugging does not seem to work in Insiders at all.  Code builds via tasks.json but the debugger hangs with the little blue progress work crawling relentlessly across the top of the debug panel. The exact same settings work in regular VS Code.

Debugging outside VS Code (i..e gdb in the terminal) is fine.

Debugging in regular VS Code also works fine (tested with v1.34.0).

I enable extension debug output but there doesn't seem to be much there:


```Discovering files...
  Processing folder (recursive): /usr/lib/llvm-6.0/lib/clang/6.0.1/include/
  Processing folder (recursive): /usr/local/include/
  Processing folder (recursive): /usr/include/
  Processing folder (recursive): /home/steve/projects/hello_linux/
  Discovering files: 5078 file(s) processed
  0 file(s) removed from database
Done discovering files.
Parsing remaining files...
  Parsing: 0 files(s) processed
Done parsing remaining files.
Database safe to open
```

VS Code version details:

```
Version: 1.35.0-insider
Commit: a5536b8f5a16a10d859f3dec1e59701671bf069e
Date: 2019-05-20T05:15:35.934Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-48-generic snap
```

tasks.json:
```
{
    "tasks": [
        {
            "type": "shell",
            "label": "build",
            "command": "/usr/bin/g++",
            "args": [   
                "-g",             
                "${workspaceFolder}/main.cpp",
                "-o",
                "${workspaceFolder}/a.out"
            ],
            "options": {
                "cwd": "/usr/bin"
            }
        }
    ],
    "version": "2.0.0"
}
```

launch.json

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "build"
        }
    ]
}
```

**Comment by yamcenutzer** [comment]
same here,
tested against a ubuntu 1804 remote and a Centos7.6 reomte
mabybe it works for WSL, but that is not a thing here.

**Comment by weinand** [comment]
Most likely this is a duplicate of #73964.

**Comment by weinand** [comment]
Fixed in latest Insiders.

**Comment by liushiqi9** [comment]
Still experiencing the problem at Version:
Version: 1.35.0-insider (user setup)
Commit: 4ca38ce5584d7cd67b435b3c32ef1240c6a29628
Date: 2019-05-21T05:18:31.618Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

**Comment by liushiqi9** [comment]
> Still experiencing the problem at Version:
> Version: 1.35.0-insider (user setup)
> Commit: [4ca38ce](https://github.com/microsoft/vscode/commit/4ca38ce5584d7cd67b435b3c32ef1240c6a29628)
> Date: 2019-05-21T05:18:31.618Z
> Electron: 3.1.8
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 6.1.7601

@weinand

**Comment by weinand** [comment]
@liushiqi9 please create a new issue for your problem with reproducible steps.

The issue hat has been fixed and the original author has confirmed that it works for him now.
