### ISSUE TITLE
Minimap corrupted

### ISSUE THREAD

**Issue by jeyk** [microsoft/vscode#74352]
Issue Type: <b>Bug</b>

In the current version of Code (April 2019), and in the current insider build, the minimap display is corrupted when the window is resized above a certain (unknown) size.

This is quite similar to #30292, except that it has nothing to do with suspend/resume, and a simple resize or redraw of the window does not help. When the window size is sufficiently small, the minimap displays OK. As soon as the window is resized above a certain threshold, the minimap displays only garbage, until I make it sufficiently small again.

![vscode-minimap-ok](https://user-images.githubusercontent.com/7167263/58381112-dde59a00-7fb9-11e9-9708-eb067c667a35.png)

![vscode-minimap-corrupted](https://user-images.githubusercontent.com/7167263/58381123-f05fd380-7fb9-11e9-95aa-5bf6f311da2d.png)

The issue also occurs with `--disable-extensions` *and* in the current insider build.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 5.0.17-300.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3371)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.61GB (8.20GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
dart-code|Dar|3.0.2
flutter|Dar|3.0.2
vscode-eslint|dba|1.9.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
vsc-material-theme|Equ|2.9.0
puppet-vscode|jpo|0.18.0
sftp|lix|1.12.7
terraform|mau|1.3.11
vscode-azureappservice|ms-|0.14.0
vscode-azurefunctions|ms-|0.17.1
vscode-cosmosdb|ms-|0.10.2
vscode-language-pack-de|MS-|1.34.2
python|ms-|2019.4.12954
azure-account|ms-|0.8.4
azurecli|ms-|0.4.5
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
debugger-for-chrome|msj|4.11.3
openhab|ope|0.5.1
chef|Pen|0.7.1
vscode-docker|Pet|0.6.2
ruby|reb|0.22.3
java|red|0.45.0
jinjahtml|sam|0.10.3
cmake-tools|vec|1.1.3
vscodeintellicode|Vis|1.1.6
azure-iot-edge|vsc|1.12.0
azure-iot-toolkit|vsc|2.7.0
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.17.0
vscode-maven|vsc|0.17.0
vscode-icons|vsc|8.7.0
vscode-ansible|vsc|0.5.2

(1 theme extensions excluded)

</details>

**Comment by dralley** [comment]
This is happening to me also.

Fedora 30, AMD Vega 56 GPU, kernel 5.0.17 (but it also occurred with some previous kernels in the 5.0.z line)

**Comment by galileo-pkm** [comment]
Same thing here, Fedora 30, Radeon 7950, just started to happen and I have used this version of VSC (1.34) for a few days now. Adding a varying number of newlines to a file, 15-21, "fixes" the issue. 

Starting vsc with --disable-gpu also resolves the issue. 

A few, possibly interesting, lines from .xsession-errors:

```
(code:2317): Gtk-WARNING **: 22:07:54.865: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(code:2317): Gtk-WARNING **: 22:07:54.865: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(code:2317): Gtk-WARNING **: 22:07:54.865: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
[main 2019-05-26T20:07:55.880Z] update#setState idle
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[main 2019-05-26T20:08:25.896Z] update#setState checking for updates
[main 2019-05-26T20:08:26.083Z] update#setState idle


```

**Comment by CurtisBelt** [comment]
Same here.

Goes away after 16-19 key strokes.

```
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.17-300.fc30.x86_64
```

```
OS: Fedora release 30 (Thirty) x86_64 
Kernel: 5.0.17-300.fc30.x86_64 
DE: GNOME 3.32.2 
WM: GNOME Shell 
WM Theme: Qogir 
Theme: Qogir [GTK2/3] 
Icons: Papirus [GTK2/3] 
CPU: Intel i7-7700K (8) @ 4.500GHz 
GPU: AMD ATI Radeon VII 
Memory: 6128MiB / 31965MiB
```

**Comment by dralley** [comment]
@jeyk Which distro are you using and what GPU do you have?

So far it looks like we all are running AMD GPUs with Fedora 30

**Comment by jeyk** [comment]
@dralley You are correct. I am using Fedora 30 and an AMD Radeon RX 470 graphics card.

```
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.17-300.fc30.x86_64
```

Sometimes the minimap *looks* OK, but is in fact still showing the last file opened.

**Comment by dralley** [comment]
Interestingly I'm seeing the same type of corruption in Betaflight Configurator, which isn't even an electron app, so it's probably some kind of kernel bug.  (Not that others shouldn't investigate further to be sure).

![Screenshot from 2019-05-27 13-51-43](https://user-images.githubusercontent.com/2751996/58433850-ee177b00-8086-11e9-8486-87e949496bfc.png)
![Screenshot from 2019-05-27 13-51-48](https://user-images.githubusercontent.com/2751996/58433846-ec4db780-8086-11e9-8cf4-9652b8a3283e.png)

**Comment by CurtisBelt** [comment]
Possibly related to mesa 19.0.5, which I have. All of the other Fedora/AMD users here probably have mesa 19.0.5 as well if their system is up to date.

They have a fix in progress. Sorry I don't have time to confirm if this is exactly our issue, but seems plausible enough to mention here.

> Jan Ziak (http://atom-symbol.net) 2019-05-23 21:38:25 UTC
> I confirm that reverting "mesa: unreference current winsys buffers when unbinding winsys buffers" fixes the rendering issues in Spotify and Visual Studio Code.
> 
> Thanks.

Source: https://bugs.freedesktop.org/show_bug.cgi?id=110721#c16

**Comment by CurtisBelt** [comment]
This is now fixed on Fedora 30 with latest mesa updates. Available in regular system updates: `sudo dnf upgrade`

https://bodhi.fedoraproject.org/updates/FEDORA-2019-4c80229aaa

**Comment by BradHeff** [comment]
Im on Arch Linux 5.1.5.arch1-2 running AMD GPU and this problem still persist for me.
My mesa package is mesa 19.0.5-1

![7b4015e1c900753097b31ffae3ce0bda.png](https://extraimage.net/images/2019/05/29/7b4015e1c900753097b31ffae3ce0bda.png)

**Comment by dralley** [comment]
The Fedora package that fixed this for me was mesa 19.0.5-2.  Assuming the patch numbers aren't totally different between the two, probably the update hasn't been pushed out to Arch yet.

**Comment by jeyk** [comment]
I can confirm that this seems to be fixed under Fedora 30 with mesa 19.0.5-2.
Closing this issue as it is obviously not a problem in vscode.
