### ISSUE TITLE
Breakpoint and current line glyph

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74983]
Start debugging something, and hit a brekapoint

Notice the icon. The dot inside should be red to indicate the breakpoint.
Also note that we have the same icon with green instead of yellow.

Additional issue. Click now on that margin, the breakpoint inside gets removed but the whole icon jumps. This is due to the fact that icons have a different size. The one with the breakpoint and the one without should have the same size and positioning

fyi @weinand @bpasero 

![Screenshot 2019-06-06 at 15 35 55](https://user-images.githubusercontent.com/1926584/59037062-c9828680-8870-11e9-9f44-2269acd1ff73.png)

![jump](https://user-images.githubusercontent.com/1926584/59037156-0189c980-8871-11e9-8175-3e1da5011ac2.gif)

**Comment by misolori** [comment]
So we're trying to stick to using a single icon and I was trying to see if using the same color for the current line would work here. Given this, do you think this would still work?

I can fix the glitch you're seeing.

**Comment by isidorn** [comment]
Using a single icon is perfectly fine, however in this case this single icon needs two colors.
I think this is a fine exception since to the user it should look like a blend of two icons (current line + brekapoint).

Fixing the glitch would be a great start.

**Comment by misolori** [comment]
All of the glitches/alignments have been fixed via https://github.com/microsoft/vscode/commit/3959ab1fec82121f51d1aa654f69b991b37bf139

**Comment by isidorn** [comment]
@misolori thanks for fixing the glitches and alignment
fyi @roblourens and @weinand on wheter these icons should be one color or two. imho the breakpoint part should be red. Though I can be convinced otherwise.

**Comment by misolori** [comment]
This should now be fixed:

![gif](https://user-images.githubusercontent.com/35271042/60482560-e11e1680-9c46-11e9-8f4b-192cab148bb9.gif)

**Comment by isidorn** [comment]
This looks great. However the dot inside is still not red.
I understand that we want to keep the icons mono colored but I think users will find this confusing. Breakpoints are something strong/important and they deserve a special color imho. 
Though we can wait for user feedback

fyi @roblourens @weinand

**Comment by weinand** [comment]
The dot has to be red and the outline style is not strong enough.

**Comment by isidorn** [comment]
Let's reopen than this so we can look into fixing it.

**Comment by misolori** [comment]
I was really hoping to only use a single color. So if we really can't, would something like this work better?

<img width="957" alt="image" src="https://user-images.githubusercontent.com/35271042/60511383-a8059680-9c86-11e9-80b1-c9a03fb29122.png">

<img width="957" alt="image" src="https://user-images.githubusercontent.com/35271042/60511436-c9ff1900-9c86-11e9-9432-6d81d13f5af5.png">

**Comment by isidorn** [comment]
This works for me.

**Comment by misolori** [comment]
@weinand @roblourens let me know what you think ☝️

**Comment by roblourens** [comment]
I am good with either color option

**Comment by weinand** [comment]
I don't like the thin outline style at all.
