### ISSUE TITLE
"Terminal: Clear" not working as desired

### ISSUE THREAD

**Issue by vivekmalhotra** [microsoft/vscode#75141]
Steps to Reproduce:

1. Run a python file using command palette      >Python: Run file in terminal window
2. Terminal shows the output. Now, clear the terminal using command palette     >Terminal: Clear
3. Terminal gets clear now.  Run the file again in the terminal    >Python: Run file in terminal window
4. Here is where issue shows up - the terminal still shows all the previous outputs from before the last clear command.  IMO, desired should be that terminal should not show any previously cleared outputs.
5. Attached below is a gif of the screen reproducing & visualizing this issue

![Screenshot PC - 072 - 2019_06_08_1016](https://user-images.githubusercontent.com/4213286/59149740-9eb24280-89d6-11e9-8563-cc694c4e04b3.gif)

Does this issue occur when all extensions are disabled?: 
Yes, the issue reoccurs.  (Note: All except the "Python" extension were disabled.  Python extension is needed to run the python file in terminal.

I had also posted in Super User forum thinking this was some issue with my system. And then I tried it on a clean build of VS code and it got repeated.  Hence, I decided to post it as a bug. 

[Link to Super User forum question](https://superuser.com/questions/1446320/vs-code-terminal-clear-command-not-working-as-desired)

VS Code version: Code - Insiders 1.36.0-insider (c089daa858f34631f5f827ff8a0313bf1e2ded6d, 2019-06-07T05:19:15.188Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.68GB (7.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.5.18875

**Comment by Tyriar** [comment]
@vivekmalhotra this is happening because Terminal: Clear tells the frontend (the thing rendering everything) to clear, but the way that the conpty backend works is it will sometimes reprint what it thinks should be visible. Since it doesn't know about our clear it reprints the unwanted output, this doesn't happen on a regular linux/mac backend that conpty is trying to emulate.

@zadjii-msft is there anything that can be done here to tell conpty to not reprint the screen? I suspect python.exe does not enter alt mode so I'm not sure why a reprint is necessary.

**Comment by zadjii-msft** [comment]
Hmm. That might not be a scenario that works for us right now. We might need to add an extra input sequence/signal to tell conpty to clear the buffer. 

I am a little curious why the whole buffer got repainted, that does seem like a bug. However, since conpty does think that all that text is still there (because its buffer wasn't cleared, only the frontend buffer was), it might get more confused by not repainting the entire thing.

**Comment by Tyriar** [comment]
@zadjii-msft might be better to fix the bug if there is one, rather than add an explicit manually clear the buffer sequence that only works on conpty.

**Comment by vivekmalhotra** [comment]
Just checked that the issue still exists in the VS code insiders build.
Unsure on how to re-open this issue?

**Comment by vivekmalhotra** [comment]
@zadjii-msft @Tyriar 
I can confirm that the issue is still prevalent in the insiders build.
Unsure on how to re-open this issue?

**Comment by zadjii-msft** [comment]
This is a bug that's external to VsCode. It'll be fixed by work on the ConPTY API that'll be tracked by microsoft/terminal#1193.

**Comment by vivekmalhotra** [comment]
> This is a bug that's external to VsCode. It'll be fixed by work on the ConPTY API that'll be tracked by [microsoft/terminal#1193](https://github.com/microsoft/terminal/issues/1193).

Thanks for the reply, Mike

**Comment by Tyriar** [comment]
@vivekmalhotra the bot closed it because of the needs more info label, reopened.

**Comment by OuyangZq** [comment]
## Terminal clear

I run npm in terminal，then end it with "Ctrl + C" , useing code clear and get result as left（I have click enter several times）,useing "ctrl + shift + p" and "terminal clear" get result as right，it clear all and terminal crashed. 

terminal will back to line 1 and enterable but not clear character。


用了clear命令后，terminal返回第一行并且可编辑，但是并没有清理界面字符，使用 控制中心的Terminal clear 指令后可以清理，但是terminal崩溃了

![image](https://user-images.githubusercontent.com/38578631/60144102-c3d6eb80-97f3-11e9-9ef7-442486fe498f.png)

**Comment by solacens** [comment]
So who should be fixing the issue now? [VS Code](https://github.com/microsoft/vscode/issues/75141) here or [Windows Terminal](https://github.com/microsoft/terminal/issues/1193)? 😢

**Comment by OuyangZq** [comment]
No debounce，Push 1s Enter，it still effective for a wheel，more than 1s

**Comment by zadjii-msft** [comment]
@solacens 
> It'll be fixed by work on the ConPTY API that'll be tracked by microsoft/terminal#1193.

**Comment by solacens** [comment]
@zadjii-msft Thanks for the information. I will keep track on the related issue.

**Comment by inliquid** [comment]
I've got to exact same problem with my projects after windows update 1803 ->1903 (clean install). No idea what changed, but I've never seen this before.

**Comment by mrkarthi** [comment]
Hello @Tyriar,

I have assigned the keyboard shortcut 'ALT+M' for clearing the Terminal.

`{
    "key": "alt+m",
    "command": "workbench.action.terminal.clear",
    "when": "terminalFocus"
  }`

Clear the Terminal with the keyboard shortcut.
Type "node index", the cursor jumps in the Terminal.

![image](https://user-images.githubusercontent.com/19660212/68914440-8cf27980-0784-11ea-9997-4787b9a5024f.png)

Press Enter.

![image](https://user-images.githubusercontent.com/19660212/68914462-a09de000-0784-11ea-9c39-227897d3b49a.png)

Terminal is not cleared.

Please check and let me know your comments.

Best Regards,
Karthi M R.

**Comment by kohenkatz** [comment]
I have discovered a workaround. It's a little annoying, but it is definitely better than nothing.

You need to clear the terminal with *two* commands:

- Command Palette `Terminal: Clear` (or your chosen keyboard shortcut)
- Type `cls` at the terminal

Interestingly, ***sometimes*** just the `cls` is enough without the `Terminal:Clear`, and sometimes it isn't. I have not figured out why that would be.

(Note: it used to be that the `cls` command did not work in the integrated terminal. I guess that there was a fix for that at some point as well.)

**Comment by mrkarthi** [comment]
@kohenkatz, Thanks for your suggestions.

> Command Palette Terminal: Clear (or your chosen keyboard shortcut)

This is not working anyways. I have to manually clear the Terminal by typing `cls` or `clear`.

Will this issue be fixed sooner as this is quite troublesome every time?

Best Regards,
Karthi M R.

**Comment by escape0707** [comment]
@mrkarthi I suggest we don't bump this issue anymore, because it's already marked as an upstream problem.

But anyway, feel free to add your thumbs up to this and the upstream issue to add priority to them.

**Comment by mhaaz** [comment]
@solacens  
> 
> So who should be fixing the issue now? [VS Code](https://github.com/microsoft/vscode/issues/75141) here or [Windows Terminal](https://github.com/microsoft/terminal/issues/1193)? 😢
> 
> Any workaround at the moment? This issue is quite annoying.

As previously suggested, you can try entering the builtin command `cls` (if using cmd-shell) or `clear` (if using bash or similar). While less quick and annoying, it works reliably for me.

**Comment by Yegorich555** [comment]
**cls** command doesn't fix this issue at all for me!

**Comment by kohenkatz** [comment]
@Yegorich555 As I noted above, you need to use ***both*** `cls` and `Terminal: Clear` together at the moment. Either one without the other isn't enough.

**Comment by vivekmalhotra** [comment]
While this issue persists, I want to share what I have been using as a temporary workaround:

1. As of VS-Code v 1.44.0, executing either "cls" or "clear terminal" command in the integrated terminal seems to clear the terminal output properly
2. Although, "Terminal: Clear" still does NOT work properly
3. I have created a keybinding (in my case CTRL+k) to accomplish this.  
Add the following code in your "keybindings.json" file (refer to the attached GIF for details)

`    {
        "key": "ctrl+k",
        "command": "workbench.action.terminal.sendSequence",
        "args": { "text": "cls \u000D" }
    }
`

4. The attached GIF shows, in order, the following:
   - "Terminal: Clear" command NOT working properly
   - "cls" and "clear terminal" commands working in integrated terminal
   - How to modify the keybindings.json file to make a keyboard shortcut
   - Verifying that keyboard shortcut works

Hope that this helps!
![Screenshot PC](https://user-images.githubusercontent.com/4213286/76693671-c0f48300-662e-11ea-8513-761933eb83b4.gif)

**Comment by Pomax** [comment]
On Windows 10.0.18363.778 running `cls` in the terminal in VS Code 1.44 does not do as described in the above comment. Instead, it does the same thing as originally reported: it seemingly clears the terminal, then running _any command_ will show (part of) the previous console output.

**Comment by arcalb** [comment]
I confirm. I noticed the same problem working with R and the extension vscode-R.
Initially, I reported the problem to the extension developers.
Here you can find the details with screenshots https://github.com/Ikuyadeu/vscode-R/issues/307#issuecomment-623534315
Once I verified the same problems with Python and the extension developed by Microsoft I can confirm it is a vscode issue.
I used a workaround too (a shortcut that runs an R command) but I prefer if the problem is solved.

**Comment by manwithsteelnerves** [comment]
At-least clear command is working for me. Command+K stopped from long time but I see something being expected post pressing Command + K. Please check the screenshot.
![Screenshot 2020-05-14 at 11 40 47 AM](https://user-images.githubusercontent.com/5437614/81899156-cee76580-95d7-11ea-83fb-7b0a25540732.png)

**Comment by Tyriar** [comment]
@manwithsteelnerves https://code.visualstudio.com/docs/editor/integrated-terminal#_why-is-cmdkctrlk-not-clearing-the-terminal

**Comment by manwithsteelnerves** [comment]
@Tyriar  Thanks a lot it worked! Any reason it suddenly stopped? Can it be due to external extensions?

**Comment by Tyriar** [comment]
@manwithsteelnerves that happened when any extension adds a cmd+k chord keybinding. Actually that might have been fixed after the `terminal.integrated.allowChords` setting was added (true by default) 🤔, anyway that's not related to this particular issue.

**Comment by Pratik-Hub** [comment]
If you are on linux then in .bashrc at last add a line 'alias clear='/bin/clear/' and save and at last you can retry

**Comment by mrwensveen** [comment]
I'm sorry to bump the issue again, but I couldn't find the bit that I wanted to add to the conversation. After clearing the terminal, when you switch to another terminal and back, the contents are there again. Running `cls` isn't an option for me because I'm looking at the output of several running processes.

My guess is that the cause is the same and that fixing the upstream bug will fix this too (or allowing this to be fixed). Could be useful as a test scenario though.

**Comment by mrkarthi** [comment]
My workaround and it works with this keyboard shortcut. I assign the letter "n" as the terminal will look new after clearing.

`{
    "key": "alt+n",
    "command": "workbench.action.terminal.sendSequence",
    "args": {
      "text": "clear\u000D"
    }
  }`

**Comment by mrkarthi** [comment]
My workaround for this. The history is still available when scrolled above.

{ "key": "alt+n", "command": "workbench.action.terminal.sendSequence", "args": { "text": "clear\u000D" } }

**Comment by WiliTest** [comment]
I have the same problem with both python and PowerShell (the only one I use). 

When I clear the terminal (by clicking into the terminal and pressing ctrl+d) it clears everything **but** the begining of the last line (it shows a part of the path of the script I debug). When I start again the debug (by clicking on the triangle), the last debug comes back on the terminal. 

The only way I know to really delete/clear the previous debug from the terminal is to click on the bin (it then tells me "The PowerShell session has terminated due to an error, would you like to restart it?" and I click yes)

**Comment by NotWearingPants** [comment]
Related to #91574 ?

**Comment by JosepAlacid** [comment]
You can't type cls while terminal is running any command. But you could need to clear it anyway and ctrl+K doesn't clear the buffer.

**Comment by Pomax** [comment]
@GearTheWorld at the very least it'd be helpful to include your STR, because "I still have this" doesn't help figure out what you're doing/what your setup is to make that be the case. With a new install of VS Code on Windows, I can't for the life of me reproduce this anymore.

@Tyriar didn't realise you used upvote emoji as an _actual_ triage metric. That changes things (although it would be nicer to talk to the GH team to get them to implement actual issue voting, because that's also using a feature for very much not its intended purpose despite working for the company that owns GH ;)

**Comment by Bitrum-code** [comment]
> Looks like the upstream issue was fixed by adding a new clear buffer API to conpty, we'll need to wait some time for the new conpty to get shipped to Windows.

Is there a new version conpty in the Windows Insider build?

**Comment by zadjii-msft** [comment]
Nope, not yet. We kinda want to make sure it's stable, even in just the Terminal, before ingesting it into the OS. Once it's in the OS itself, it'll still be a few weeks before it reaches Insiders builds.

**Comment by sp00x** [comment]
Is this the same issue that is causing this?

1. make something display something in the terminal
2. terminal: clear
3. resize terminal window
4. old content re-appears 

?

**Comment by Tyriar** [comment]
@sp00x yes, this issue is about old cleared content reappearing.

**Comment by Mistborn-First-Era** [comment]
I can confirm this issue still exists. If I run my "terminal: clear" hotkey any subsequent code will show both my old terminal + my newly run code.

**Comment by PaulB-H** [comment]
Ah this was driving me nuts, especially since I just found everyone saying cmd palate: Terminal: Clear, tried setting up keybinding, ETC still nothing!

Definitely bugged in some way for me... It will clear, and as soon as I start typing anything, the position where I'm typing will glitch to the bottom of the window (as if pushed down by the old content re-appearing...) and as soon as I press enter all the old content re-appears. 

~~So this is something that will need to be fixed by Microsoft?~~

Ahh I see fix out to preview version of terminal a while back, so maybe not long until fix goes to main version.

https://github.com/microsoft/terminal/issues/1193#issuecomment-947862807

**Comment by Pieras2** [comment]
it's a pitty that such a bug still exists, it's f... annoying

**Comment by thautwarm** [comment]
confirmed

**Comment by AdrianZafari** [comment]
Confirmed, I have the same bug.

**Comment by Don876** [comment]
Still there for me as well.

**Comment by josephzidell** [comment]
Same issue on Ubunutu as well as Chromebook

**Comment by albertoarcagni** [comment]
Try installing the R development release, the reason may be the same

Il gio 8 set 2022, 20:17 Joseph Zidell ***@***.***> ha
scritto:

**Comment by AsuxAX** [comment]
I can confirm, this has been happening ever since I installed vscode now.

**Comment by muhamedkarajic** [comment]
I also dont like it and when I write 'clear' / 'cls' it also dosent clear properly when I scroll up it shows old content.

**Comment by wyckster** [comment]
I can also confirm that _Terminal: Clear_ doesn't work properly.  IThe terminal visibly clears when you invoke the command, but the cleared text comes back when more output appears.  I expect the command is supposed to make the text be gone permanently, and return the cursor to the top left corner of the terminal too.  Some other things that cause the text to come back:

* if you have split the terminal  (Split Terminal command) and you give focus to the other terminal, the text in the first terminal you cleared will reappear.
* if you give focus to another tab that is typically in that same pane (e.g.: PROBLEMS, OUTPUT, DEBUG CONSOLE, etc.) by clicking in the pane, the text will reappear
* If you invoke Terminal: Split Terminal, the cleared text will return.

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by mateo-m** [comment]
I can confirm that the "Terminal: Clear" action doesn't work properly, but this bug only affects Powershell on my end.

Clearing a terminal running CMD, Git Bash or WSL works as expected, but clearing a terminal running Powershell 7 (`pwsh.exe`) results in a strange behaviour from the terminal.

<ins>Steps to reproduce</ins>:
1. Type anything in a Powershell terminal
2. Run "Terminal: Clear"
3. Start typing something else with 2 characters or more, you'll notice that when the second character typed, two new empty lines are added and the characters which were typed appear on a newly-added third line.
![image](https://user-images.githubusercontent.com/23667794/208722185-ed5f1493-11e6-4d39-97ba-0f3835fb4423.png)

Here's a video demonstration of the issue I'm facing (made by @/hazrmard in https://github.com/microsoft/vscode/issues/109012):
![Clearing terminal in Powershell - bug](https://camo.githubusercontent.com/3d62f6f4a472c6c6c23958b92df29045df6842c05bcafa3b96ffc087b356a417/68747470733a2f2f692e696d6775722e636f6d2f6767453855534e2e676966)

**Comment by TamirCode** [comment]
i am using bash , windows 10, and the clear command just takes me to new line and hides the top, but i can still scroll up and see the old garbage. The clear command is absolutely useless in this way.

**Comment by GearTheWorld** [comment]
If using PowerShell

Remove-Item (Get-PSReadlineOption).HistorySavePath

**Comment by nrasadi** [comment]
I can confirm the issue 1.74.2 as well.

**Comment by nrasadi** [comment]
Well, seems the problem is with how terminal.clear was implemented. A workaround (not solution) based on [this answer](https://superuser.com/a/1553412), might be to emulate common `clear screen` commands (For instance, `ctrl+ l` or any other shortcut being used in your actual terminal) for this purpose. When using Powershell or WSL Linux distros as the integrated terminals, adding the following snippet to `keybindings.json` would probably help.
```
    {
        "key": "ctrl+l",
        "command": "\u2303 l \u000D",
        "when": "terminalFocus" 
    },
```

And if using Command Prompt, then the following one:
```
    {
        "key": "ctrl+l",
        "command": "workbench.action.terminal.sendSequence",
        "args": { "text": "cls \u000D" },
        "when": "terminalFocus" 
    },
```

**Comment by GearTheWorld** [comment]
> > If using PowerShell
> > Remove-Item (Get-PSReadlineOption).HistorySavePath
> > Reference: [shellhacks.com/clear-history-powershell](https://www.shellhacks.com/clear-history-powershell/)
> 
> Thank you for sharing your solution @GearTheWorld, but what you posted is a work-around. I think VS Code should be able to clear its terminal, no matter which shell is being used.

I perfectly understand.  I had to give at least a work-around.  Enjoy !

**Comment by zmikaya** [comment]
I found that using a multi-step command works fairly well to keep the terminal and render view in sync:

```
{
    "key": "ctrl+k",
    "command": "runCommands",
    "args": {
      "commands": [
        {
          "command": "workbench.action.terminal.sendSequence",
          "args": { "text": "\u0015 clear \u000D" }
        },
        "workbench.action.terminal.clear"
      ]
    },
    "when": "terminalFocus"
}
```

**Comment by Tyriar** [comment]
@GearTheWorld see https://github.com/microsoft/terminal/issues/1193, https://github.com/microsoft/node-pty/pull/601 and https://github.com/microsoft/vscode/pull/184734

**Comment by GearTheWorld** [comment]
I tried to find the answer but reading all those texts I can't find what I'm looking for.  Can you simply say what is the command we execute in Visual Studio Code Power Shell to clear the history ?  Because CLS, CLEAR etc. doesn't work

**Comment by Tyriar** [comment]
@GearTheWorld the milestone of the issue which is the month in which the work is done. It'll get released in early July.

**Comment by vivekmalhotra** [comment]
> 

Great to hear this is now fixed - thanks @Tyriar!
Coincidentally, the issue got fixed on June 9th, exactly 4 years after it was first created. Time flies...

**Comment by vivekmalhotra** [comment]
> 

Great to hear this is now fixed - thanks @Tyriar!
Coincidentally, the issue got fixed on June 9th, exactly 4 years when it was first created. Time flies...  😊

**Comment by vivekmalhotra** [comment]
> @GearTheWorld the milestone of the issue which is the month in which the work is done. It'll get released in early July.

Great to hear this is now fixed - thanks @Tyriar! Coincidentally, the issue got fixed on June 9th, exactly 4 years after it was first created. Time flies... 😊

**Comment by rzhao271** [comment]
I still see a lot of whitespace in the terminal:

![Run Python file in terminal, then clear, then running it again shows a lot of whitespace where there shouldn't be any](https://github.com/microsoft/vscode/assets/7199958/c1af6eed-12f2-42b5-ade5-6c7b62fd3717)

**Comment by heartacker** [comment]
same here

**Comment by Svish** [comment]
VS Code, on Windows, with regular `cmd` terminal, when i run `clear`, it does scroll the buffer so my cursor is at position `0,0`, but that's not what `clear` is supposed to do. It's supposed to _clear_ the terminal, i.e. empty the buffer completely so that I'm at a fresh start.

I use it frequently in the command-line when dealing with commands that spit out a lot of text or errors. Sometimes it's difficult to see where the output from one command ends and the next begins, and in those cases it's super handy to just run `clear` and empty the buffer completely, so that the _only_ output on the screen will be from the command I'm about to run.

This doesn't work at all in VS Code currently. Running `clear` simply scrolls the buffer up a bit, so it _looks_ empty, but when I run my next command outputting a bunch of text, and then try to scroll up to find the beginning, I eventually get to old output, making it a lot harder.

`clear` should _clear_.

**Comment by Tyriar** [comment]
@Svish this is talking about the `Terminal: Clear` VS Code command, not the `clear` shell command. This is what you're talking about https://github.com/xtermjs/xterm.js/issues/1727

**Comment by Pieras2** [comment]
I see many comments but for me it started to work weeks ago. I use gitbash in vac and "clear" works now as a charm

**Comment by VLFrosttide** [comment]
Still having an issue of the terminal clearing, then it skiping lines when I start writing , same as this guy here 
https://github.com/microsoft/vscode/issues/109012  
Clearing it with the workbench.action.terminal.clear.

**Comment by vishalgupta023** [comment]
Don't Use powerShell use CammandPromt terminal, Cls or Clear will clear  terminal instead of scrolling terminal.

**Comment by Tyriar** [comment]
Closing this as it was fixed on our end with https://github.com/microsoft/vscode/pull/184734, you may not get the fix until a future Windows update unfortunately

**Comment by mehedihasanziku** [comment]
> Closing this as it was fixed on our end with #184734, you may not get the fix until a future Windows update unfortunately

This doesn't help us, anyway to force update? which package from windows need to be updated?
**node-pty** we need update our node package? Please refer us window update link

**Comment by Tyriar** [comment]
> This answer doesn't help us, anyway to force update? which package from windows need to be updated?
node-pty we need update our node package?

@mehedihasanziku I'm not sure the version exactly but it's not a package you can install independently but Windows itself, you might be able to find the version by following links to the microsoft/terminal repo.

**Comment by Tyriar** [comment]
For the non-Windows problem, we'll adopt the new option in https://github.com/xtermjs/xterm.js/pull/5224
