### ISSUE TITLE
Same colors look dull on VS Code compared to Sublime Text (other applications)

### ISSUE THREAD

**Issue by nksaraf** [microsoft/vscode#75573]
Issue Type: <b>Bug</b>

Recently tried to switch from Sublime Text to VS Code. Used the same colors as Sublime Text for my token colors and the color were considerably duller in VS Code (than almost all other applications). Tried adding app.commandLine.appendSwitch('force-color-profile', 'srgb') to Mac App bundle Resources/app/out/main.js based on https://github.com/Microsoft/vscode/issues/65816#issuecomment-466130826. 

Unsure of additional steps is required to enforce this change in the file, but saving it and restarting VS Code did not have any effect. Also tried logging to console to check if that would work (didn't).

Sublime Text:
<img width="861" alt="Screen Shot 2019-06-15 at 11 12 06 AM" src="https://user-images.githubusercontent.com/11255148/59554897-28c25400-8f5f-11e9-9704-4879ae974faa.png">

VS Code:
<img width="1047" alt="Screen Shot 2019-06-15 at 11 11 42 AM" src="https://user-images.githubusercontent.com/11255148/59554900-34ae1600-8f5f-11e9-8fc7-bfcbf164837b.png">

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
material-icon-theme|PKi|3.8.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by nksaraf** [comment]
I tried the nightly build as well and the results are not much different. Here are the screenshots on the nightly build

VS Code insider
<img width="1440" alt="Screen Shot 2019-06-17 at 1 12 27 PM" src="https://user-images.githubusercontent.com/11255148/59633603-bb9af400-9101-11e9-870a-11e784ebd523.png">

Sublime Text
<img width="1440" alt="Screen Shot 2019-06-17 at 1 11 30 PM" src="https://user-images.githubusercontent.com/11255148/59633605-bb9af400-9101-11e9-9271-71f47fdd82d7.png">

**Comment by JakubNalewajek** [comment]
Looks like there are multiple ways to force old color rendering:
1. app.commandLine.appendSwitch('disable-color-correct-rendering');
2. app.commandLine.appendSwitch('disable-features', 'ColorCorrectRendering');
3. app.commandLine.appendSwitch('force-color-profile', 'sRGB');
I can confirm that both 2 and 3 work on windows 10 with HDR enabled, 1 (which is in the current build) does not work. I see no difference with HDR disabled.
@nksaraf can you try adding option 2 instead?

**Comment by dougal83** [comment]
@JakubNalewajek Thank you for the above info.  I was faced with the washed out experience with Win10 & HDR.  I followed [these instructions](https://github.com/Microsoft/vscode/issues/51791#issuecomment-397527146) to implement (in case this is found by others experience same issue).

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration_1.37.0-1562666970_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/code-exploration-1.37.0-1562667129.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/54c6f2047b7e26f9dd6f991d9831ead1f06964b2/VSCodeSetup-x64-1.37.0-exploration.exe)

**Comment by JakubNalewajek** [comment]
On Exploration build, colors are fine on Windows 10 with HDR enabled.

**Comment by nksaraf** [comment]
On exploration build, colors look fine on my Mac as well without requiring any other settings.  Also would you suggest I continue to use the exploration build, or is it unstable?

Left - Exploration build
Right - Old build
<img width="1407" alt="Screen Shot 2019-08-07 at 2 07 41 AM" src="https://user-images.githubusercontent.com/11255148/62598697-3a1d4200-b8b8-11e9-8072-5582bc4dcdf1.png">

**Comment by beastdestroyer** [comment]
@nksaraf the exploration builds are stable enough for me (i use it as my daily driver, even if it is behind insiders sometimes) so I guess as long as you're not wanting much from the next iteration's update, you'll be fine.
Plus it's a great way to stay ahead on the game of electron updates and provide feedback :>

**Comment by deepak1556** [comment]
Fixed by https://github.com/microsoft/vscode/pull/81644. It should also be available with next insiders.

**Comment by nksaraf** [comment]
The problem still persists in Insiders with new version of macos (Top is VS Code, bottom is sublime text 3)
My info from VS Code Insiders:
Version: 1.39.1
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:35:11.314Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
<img width="1280" alt="Screen Shot 2019-11-03 at 2 32 36 AM" src="https://user-images.githubusercontent.com/11255148/68081856-8c4fff80-fde2-11e9-8b93-8fe92c28c59f.png">

Sublime Text 3
<img width="1280" alt="Screen Shot 2019-11-03 at 2 34 08 AM" src="https://user-images.githubusercontent.com/11255148/68081857-8ce89600-fde2-11e9-8e53-0ea78ffb4fa0.png">
