### ISSUE TITLE
Memory leak when creating many decoration types and disposing them

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#7609]
- VSCode Version: 1.2.0
- OS Version: OSX

Now when it's possible to [set the `contentText` for a decoration with this change](https://github.com/Microsoft/vscode/pull/7181), one may need to create quite a few transient decoration types to display/update the side content for certain code lines.

I tried to simulate my scenario and it looks like some resources are not cleared when disposing a decoration type.

Steps to Reproduce:

Here is the test code:

```javascript
  let getRandomInt = (min, max) => Math.floor(Math.random() * (max - min)) + min;
  let decorationTypes = [];
  let editor = window.visibleTextEditors[0];
  setInterval(function () {
    decorationTypes.forEach(dt => {
      editor.setDecorations(dt, []);
      dt.dispose();
    });
    decorationTypes.length = 0;
    for (let i = 0; i < 1000; i++) {
      let dt = window.createTextEditorDecorationType({after: {contentText: getRandomInt(0, Number.MAX_SAFE_INTEGER)}});
      editor.setDecorations(dt, [new vscode.Range(i, 0, i, 1000)]);
      decorationTypes.push(dt);
    }
  }, 1);
```

The memory consumption grows rapidly and after a couple of minutes I get the process crash:

![screen shot 2016-06-13 at 10 36 17 pm](https://cloud.githubusercontent.com/assets/979966/16008311/be379352-31ba-11e6-97df-66afe41a656c.png)

Note that the issue can be reproduced with the current release version on VS Code (not only the insiders build), so it wasn't introduced by the change.

**Comment by aeschli** [comment]
Note that decoration types are kept until you call dispose on them. I will have a look, but it's clean you can't create too many of them.
With the latest change you don't need to create a decoration type for every attachment text, but can refine the type by defining before & after attachments on the decoration itself. These decoration are more expensive to be build (css rules need to be added) but are cleaned up as soon as not shown anymore.

**Comment by ArtemGovorov** [comment]
> Note that decoration types are kept until you call dispose on them.

I call `dispose` in the provided test code for all decoration types. There still must be something somewhere that is not cleaned up.

> With the latest change you don't need to create a decoration type for every attachment text, but can refine the type by defining before & after attachments on the decoration itself.

Oh, it's awesome, I didn't realise that, thanks for noting it. It fits my scenario much better than creating a lot of decoration types.

**Comment by alexandrudima** [comment]
The `refCount` property is not initialized on `DecorationTypeOptionsProvider`, making `provider.refCount++` turn it into NaN, making this code in `removeDecorationType` not succeed:

```
provider.refCount--;
			if (provider.refCount <= 0) {
				delete this._decorationOptionProviders[key];
				provider.dispose();
				this.listCodeEditors().forEach((ed) => ed.removeDecorations(key));
			}
```

**Comment by alexandrudima** [comment]
Fixed while merging #6553 with 9e7b462601a72536ef4ab646266df6c6b6f20211

**Comment by aeschli** [comment]
Thanks @alexandrudima !

**Comment by isidorn** [comment]
Using the snippet user provided I can still crash VScode after 1 minute, not sure if that is expected (there is a timeout of 1ms, so it is really adding a bunch of decorations). Though I do not get an error in the console, just after running the extension whole vscode crashes.

Reopening so @alexandrudima can decide if this is expected or not

**Comment by alexandrudima** [comment]
I have a fix in a09ee36

**Comment by alexandrudima** [comment]
@jrieken Pushed fix to `release/1.3.0`. The fix is to clear all data associated with a decoration type in the editor. Please verify that those members are always accessed in a safe way. The contract is that the decoration type will always be unique and once removed, it will never come back.

**Comment by jrieken** [comment]
Change looks good, works in `scripts/code.sh`
