### ISSUE TITLE
Smoke test failure:  starts with 'DE' locale and verifies title and viewlets text is in German

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76298]
```
Localization
     starts with 'DE' locale and verifies title and viewlets text is in German:
 Error: Timeout: get text content '.monaco-workbench .part.sidebar > .title > .title-label > h2' after 20 seconds.
  at /home/bpasero/development/monaco/test/smoke/out/vscode/code.js:163:23
  at Generator.next (<anonymous>)
  at fulfilled (out/vscode/code.js:8:58)
```

**Comment by bpasero** [comment]
@dbaeumer not sure if you wrote this test initially, starting with you.

**Comment by dbaeumer** [comment]
@bpasero  No I didn't. But I will look. Did you reorganize code. This is most likely the issue since this requires a new language pack.

**Comment by dbaeumer** [comment]
Verified that insider is correctly translated:

<img width="781" alt="capture" src="https://user-images.githubusercontent.com/1931590/60417586-13952880-9be1-11e9-8436-f52a7f5836af.png">

**Comment by bpasero** [comment]
> Did you reorganize code

Well, can you be more specific? Yes, there were tons of refactorings during the past milestones, but I think that is normal.

My guess would be that maybe some CSS selector changed that we used to verify the strings are german.

**Comment by dbaeumer** [comment]
The selector is still OK

<img width="586" alt="capture" src="https://user-images.githubusercontent.com/1931590/60417897-d4b3a280-9be1-11e9-8a0a-77ea0f039069.png">

On the latest build :-)

**Comment by dbaeumer** [comment]
And it even has the correct text.

**Comment by bpasero** [comment]
Yeah I saw that too last week, weird.

**Comment by dbaeumer** [comment]
I can reproduce locally. It fails when verifying the Debug viewlet. Let me look if something changed there. Did you remember when it failed?

**Comment by dbaeumer** [comment]
They renamed the string :-) Debuggen -> Debug

**Comment by dbaeumer** [comment]
<img width="521" alt="capture" src="https://user-images.githubusercontent.com/1931590/60419537-ccf5fd00-9be5-11e9-8479-96d74ec8c25a.png">

**Comment by dbaeumer** [comment]
Fixed.

**Comment by isidorn** [comment]
This is still happening with latest vscode insiders.
Both @alexr00 @joaomoreno and me hit it.
Thus reopening.
I can start code in German, so it is not blocking, thus moving to August

**Comment by joaomoreno** [comment]
No, the test actually caught a bug: https://github.com/microsoft/vscode/issues/78383
