### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of t.push

### ISSUE THREAD

**Issue by DaniGTA** [microsoft/vscode#76769]
Issue Type: <b>Bug</b>

Mark multi lines like this:
https://i.imgur.com/wYNpGbz.png

And press TAB now it shows this:
https://i.imgur.com/7fHKIGG.png

Shift + TAB works btw.

VS Code version: Code - Insiders 1.37.0-insider (7e03eb1a1fce3beb6ccea5f3b8f828e01940be61, 2019-07-05T18:31:56.611Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (13.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
gitlens|eam|9.8.2
vscode-npm-script|eg2|0.3.8
vue-inline-template|fai|1.0.1
vue-format|feb|0.1.7
code-runner|for|0.9.11
vscode-test-explorer|hbe|2.12.1
beautify|Hoo|1.5.0
discord-vscode|icr|3.6.0
Angular2|joh|8.1.1
graphql-for-vscode|kum|1.14.1
vscode-mocha-sidebar|mat|0.22.2
Angular-BeastCode|Mik|8.0.10
vscode-docker|ms-|0.6.4
python|ms-|2019.6.22090
csharp|ms-|1.20.0
vscode-typescript-tslint-plugin|ms-|1.2.1
vsliveshare|ms-|1.0.488
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.6
vetur|oct|0.21.1
material-icon-theme|PKi|3.8.0
java|red|0.46.0
vscode-yaml|red|0.4.1
es6-mocha-snippets|spo|0.2.2
vscode-java-debug|vsc|0.20.0
vscode-java-test|vsc|0.18.1
vscode-maven|vsc|0.17.1
quokka-vscode|Wal|1.0.233
JavaScriptSnippets|xab|1.7.2
html-css-class-completion|Zig|1.19.0

</details>

**Comment by RobinMarchart** [comment]
Same here on linux

**Comment by Tyriar** [comment]
Can you open devtools (help menu) and paste in the stack trace from the console?

**Comment by RobinMarchart** [comment]
ERR Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at i._editor.getModel.changeDecorations.e (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2313:187)
    at P._changeDecorations (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1204:16)
    at P.changeDecorations (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1203:366)
    at v.move (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2312:962)
    at b._move (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2320:268)
    at b.next (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2319:985)
    at e.next (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2324:408)
    at Object.handler [as _callback] (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:2325:82)
    at Object.runEditorCommand (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1575:586)
    at n.invokeWithinContext.e (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1575:853)
    at d.invokeFunction (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1397:380)
    at e.invokeWithinContext (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1917:551)
    at Object.runCommand (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1575:724)
    at handler (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1575:88)
    at d.invokeFunction (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:1397:380)
    at Proxy._tryExecuteCommand (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3053:170)
    at r.then.i (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:3052:907)

**Comment by DaniGTA** [comment]
OnWindows:

` ERR Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at i._editor.getModel.changeDecorations.e (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2313:187)
    at P._changeDecorations (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1204:16)
    at P.changeDecorations (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1203:366)
    at v.move (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2312:962)
    at b._move (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2320:268)
    at b.next (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2319:985)
    at e.next (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2324:408)
    at Object.handler [as _callback] (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2325:82)
    at Object.runEditorCommand (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1575:586)
    at n.invokeWithinContext.e (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1575:853)
    at d.invokeFunction (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1397:380)
    at e.invokeWithinContext (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1917:551)
    at Object.runCommand (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1575:724)
    at handler (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1575:88)
    at d.invokeFunction (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1397:380)
    at Proxy._tryExecuteCommand (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3053:170)
    at r.then.i (file:///C:/Users/danig/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3052:907)`

**Comment by SupinePandora43** [comment]
same issue(
[-1562478722102.log](https://github.com/microsoft/vscode/files/3365313/-1562478722102.log)

**Comment by yc9274** [comment]
I got the same issue.

**Comment by rainzhao2000** [comment]
I get this error message when I press tab on a line in vscode

**Comment by RMacfarlane** [comment]
@DaniGTA (or anyone else experiencing this issue), does this also happen when all extensions are disabled? I haven't been able to reproduce this yet

**Comment by DaniGTA** [comment]
I think that comes after a while when i start vscode i dont get this bug instand, it comes with the time.

But if it is a extensions, all that experience the bug should post there extensions so that we can find out what extension make that bug.

**Comment by mtin79** [comment]
+1 Same issue when i hit tab - key (on mac os x)

**Comment by t-eckert** [comment]
+1

**Comment by RMacfarlane** [comment]
If you're experiencing this issue, can you please
1. Indicate if this happens only in 1.37 insiders, or if you are using stable
2. Try running the `Developer: Reload Window With Extensions Disabled` command

**Comment by jtsom** [comment]
Same here on latest Insiders, MacOS:
```
Version: 1.37.0-insider
Commit: d50852db1af10ec100a71ad57cc3a04c8aead117
Date: 2019-07-08T05:33:31.335Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
```
After hitting Tab key to get auto-complete for a snippet, in Javascript (straight .js and .vue) files.

**Comment by rainzhao2000** [comment]
tabbing 1 line and multiple line **works** for me now on
Version: 1.37.0-insider (user setup)
Commit: d50852db1af10ec100a71ad57cc3a04c8aead117
Date: 2019-07-08T05:37:36.104Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by RMacfarlane** [comment]
@jrieken Based on the call stack, I think this is at https://github.com/microsoft/vscode/blob/6b88a5364546109b6bec8b56873aa8a51b4005b6/src/vs/editor/contrib/snippet/snippetSession.ts#L153

**Comment by jrieken** [comment]
I cannot reproduce, can someone share reproduce steps, esp. the source file in which this happens. Thanks

**Comment by jrieken** [comment]
Likely fixed by https://github.com/microsoft/vscode/commit/b29fec000b96d7912d56499a496284156c9aa891

**Comment by jrieken** [comment]
Optimistically closing.

**Comment by rumanbsl** [comment]
Still exists on insiders build.

**Version: 1.37.0-insider**
Commit: d50852db1af10ec100a71ad57cc3a04c8aead117
Date: 2019-07-08T05:33:31.335Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

`
ERR Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at i._editor.getModel.changeDecorations.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2313:187)
    at P._changeDecorations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1204:16)
    at P.changeDecorations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1203:366)
    at v.move (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2312:962)
    at b._move (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2320:268)
    at b.next (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2319:985)
    at e.next (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2324:408)
    at Object.handler [as _callback] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2325:82)
    at Object.runEditorCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1575:586)
    at n.invokeWithinContext.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1575:853)
    at d.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397:380)
    at e.invokeWithinContext (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1917:551)
    at Object.runCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1575:724)
    at handler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1575:88)
    at d.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397:380)
    at Proxy._tryExecuteCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3054:170)
    at r.then.i (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3053:907)
`

**Comment by jrieken** [comment]
@rumanbsl Latest insiders is 9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, please try with that one

**Comment by SupinePandora43** [comment]
@jrieken problem disappeared! but it very hard to reproduce, and maybe problem still exists.

**Comment by dazhoudotnet** [comment]
+1
Version: 1.37.0-insider (system setup)
Commit: 7e03eb1a1fce3beb6ccea5f3b8f828e01940be61
Date: 2019-07-05T18:31:56.611Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by rumanbsl** [comment]
Will report back...

**Comment by rumanbsl** [comment]
Error seems to go away with 46cc0a1670b7047e610aaef1bf84f1190802e9ec

**Comment by daravi** [comment]
On MacOS (7e03eb1)
`log.ts:173   ERR Cannot read property 'startLineNumber' of null: TypeError: Cannot read property 'startLineNumber' of null
    at i._editor.getModel.changeDecorations.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2313:187)
    at P._changeDecorations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1204:16)
    at P.changeDecorations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1203:366)
    at v.move (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2312:962)
    at b._move (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2320:268)
    at b.next (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2319:985)
    at e.next (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2324:408)
    at Object.handler [as _callback] (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2325:82)
    at Object.runEditorCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1575:586)
    at n.invokeWithinContext.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1575:853)
    at d.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397:380)
    at e.invokeWithinContext (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1917:551)
    at Object.runCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1575:724)
    at handler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1575:88)
    at d.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1397:380)
    at Proxy._tryExecuteCommand (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3053:170)
    at r.then.i (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3052:907)`

**Comment by SupinePandora43** [comment]
seems problem fixed for me :tada: , but i getting wrong highlight on snippets, e.t.c
