### ISSUE TITLE
"Quick Fix" Button stopped working

### ISSUE THREAD

**Issue by Fernandomr88** [microsoft/vscode#77018]
https://github.com/microsoft/vscode/issues/76851#issue-465145364

the above issue was closed but the problem isn't fixed.

I'm writing Dart with Flutter.

**Comment by sanguine8082** [comment]
Just updated to 1.36.1 and I am also still seeing this error.

Using CSpell to fix some grammar mistakes in txt and xml files

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by Fernandomr88** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

Yes, just tried it. Same issue.

Version: 1.37.0-insider (user setup)
Commit: 9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904
Date: 2019-07-09T05:26:27.407Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by mjbvz** [comment]
@Fernandomr88 Please share repo steps:

![Jul-09-2019 13-48-28](https://user-images.githubusercontent.com/12821956/60921819-429a4280-a250-11e9-98e9-7000a1f46c47.gif)

**Comment by Fernandomr88** [comment]
> @Fernandomr88 Please share repo steps:
> 
> ![Jul-09-2019 13-48-28](https://user-images.githubusercontent.com/12821956/60921819-429a4280-a250-11e9-98e9-7000a1f46c47.gif)

![error](https://user-images.githubusercontent.com/14304128/60922840-ffea6180-a273-11e9-8e77-dc2f8cf3def2.gif)

**Comment by mjbvz** [comment]
Share example code and step by step instructions

**Comment by Fernandomr88** [comment]
> Share example code and step by step instructions

Create new flutter project, delete import(s) line(s), try to click on "Quick fix..." and 'Import library...' any library.


Code Example (default flutter new project WITHOUT import) 
`
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
`

**Comment by mjbvz** [comment]
Still can't repo:

![Jul-09-2019 16-08-36](https://user-images.githubusercontent.com/12821956/60928895-e2ad9700-a263-11e9-8d83-6e9e39ba3c46.gif)

Does this happen 100% of the time? Do you see if you disable all other extensions?

**Comment by mjbvz** [comment]
Can repo on windows actually. Will investigate what is different

**Comment by sanguine8082** [comment]
My issue with quick fix and the Code Spell Checker extension seem to be resolved in the latest insiders build.  

I wrote out a basic txt file with some random spelling errors in my sentences and was able to fix the issues with the quick fix hover and the light bulb.  

Was there something merged to insiders to fix this that hasn't been released yet?

**Comment by Fernandomr88** [comment]
> My issue with quick fix and the Code Spell Checker extension seem to be resolved in the latest insiders build.
> 
> I wrote out a basic txt file with some random spelling errors in my sentences and was able to fix the issues with the quick fix hover and the light bulb.
> 
> Was there something merged to insiders to fix this that hasn't been released yet?
> 
> EDIT: I didn't refresh the page before I replied. Thanks for looking into this!! :)

https://github.com/microsoft/vscode/pull/77044#issue-296008680

check that pull request and @mjbvz comments

**Comment by babs232** [comment]
Below is what I am getting as error while using Quick Action:

[2019-07-11 10:38:38.078] [exthost] [warning] redhat.java - Code actions of kind 'quickfix 'requested but returned code action is of kind 'source.generate.delegateMethods'. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.

**Comment by preskaper** [comment]
I'm seeing this on 1.36.1 version (win10 1903)  
![ezgif com-gif-maker](https://user-images.githubusercontent.com/18500014/62004012-115eb500-b120-11e9-9f15-997ce38c4ac5.gif)

**Comment by ppatierno** [comment]
I have the same problem with Quick fix not working but clicking on the light bulb works well.
I am on Fedora 29 and VSCode version is 1.36.1

**Comment by Eskibear** [comment]
> I have the same problem with Quick fix not working but clicking on the light bulb works well.

The same issue in Stable version. But looks it has been fixed in Insider version. 
```
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```
```
Version: 1.37.0-insider (user setup)
Commit: 628bdedf671d3230fc76982fae845875a6f6c0da
Date: 2019-07-19T10:33:04.702Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by Erquint** [comment]
These issues and their duplicates keep getting closed but not fixed.
Is this some new issue tracking paradigm like inbox-zero for mail?

**Comment by Fernandomr88** [comment]
It has been fixed already, but it is at the Insiders version only and at the stable version only at next release.
Check above.

Em 30 de jul de 2019, à(s) 04:43, Murad Beybalaev <notifications@github.com> escreveu:

**Comment by Leakbang** [comment]
They fixed the issue in the latest update. Finally!

**Comment by Erquint** [comment]
Why do I feel like a feature-cut is being "sold" as a bug-fix..?
