### ISSUE TITLE
[snap] VS Code not opening on Manjaro 18.1

### ISSUE THREAD

**Issue by numToStr** [microsoft/vscode#77061]
- VSCode Version: 1.36.1
- OS Version: Manjaro Linux 18.1.0.rc3
- Kernel: 5.1

Running Manjaro on VirtualBox and VS Code and Insiders version always failed to start.

## VS Code logs
```bash
~ 
➜ code --disable-extensions --verbose 
(process:3138): Gtk-WARNING **: 13:25:49.629: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 13:25:49.771: Failed to load module "canberra-gtk-module"
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libcrypto.so.1.1)
Failed to load module: /usr/lib/gio/modules/libgioopenssl.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
(code:3138): Gtk-WARNING **: 13:25:50.012: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
(code:3138): Gtk-WARNING **: 13:25:50.013: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
(code:3138): Gtk-WARNING **: 13:25:50.013: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
```

## Snap Version
```bash
snap     2.39.3-3
snapd    2.39.3-3
kernel   5.1.0-0-MANJARO
```
## Code version
```sh
1.36.1
2213894ea0415ee8c85c5eea0d0ff81ecc191529
x64
```

## Code Insiders
```sh
1.37.0-insider
360e4e4dfa989135f28edc0d6f7e42df33cddf87
x64
```

Does this issue occur when all extensions are disabled?: Yes
This is a fresh install of VS Code with no extensions installed.

On Ubuntu, everything is working fine with the same snap and vs code versions.

**Comment by Cairo2k18** [comment]
I am also getting this error on code version `1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35) [x64]` and snap & snapd version `2.40-1`.

However it seems to work fine on my laptop which is running the exact same versions as above?

**Comment by joaomoreno** [comment]
cc @flexiondotorg

**Comment by lucax88x** [comment]
same issue

**Comment by lucax88x** [comment]
> I am also getting this error on code version `1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35) [x64]` and snap & snapd version `2.40-1`.
> 
> However it seems to work fine on my laptop which is running the exact same versions as above?

the package from pacman of vscode works correctly, but it's a fork of it, not the official one

**Comment by hackfeed** [comment]
@vkasraj doesn't work for me :(

**Comment by hackfeed** [comment]
Still actual, by the way

**Comment by carlesjavierre** [comment]
Still happening on new installs, but not 100% of the time. 

I have recently installed Manjaro 18.1 on my main machine and I found the problem, anyways I happened to make it work (idk how honestly, most likely it was something like @vkasraj 's trick). Now I'm installing Manjaro 18.1 on a friend's computer and I can't happen to make it work in any way.

**Comment by hackfeed** [comment]
@carlesjavierre I found a method for me. Just build it from the AUR sources, it works!

**Comment by Cairo2k18** [comment]
@hackfeed yes we know that works.. that's why this issue has [snap] in brackets

**Comment by phillipsj** [comment]
I did a fresh install today and I have the exact same issue. The VSCode and the Insiders snap will not launch. All the other snaps I installed work as expected.

**Comment by petermcclymont** [comment]
I'm in the same boat. AUR under Manjaro gives me a working VS code, but not code installed using snap.

I get the same error as of the latest Manjaro installed yesterday.

desktop.go:129: cannot use line "Exec=/usr/share/code/code --new-window %F" for desktop file "/var/lib/snapd/desktop/applications/code_code.desktop" (snap code)

**Comment by phillipsj** [comment]
The Flatpak works just fine.

**Comment by MysticRF** [comment]
same problem on xubuntu 19.04

**Comment by cyberbrin** [comment]
Same problem on Manjaro 18.1 (kernel 4.19)

**Comment by feferna** [comment]
I am having the same problem on Manjaro KDE 18.1.0.

For now, I am using the Flatpak version.

**Comment by cyberbrin** [comment]
Fixed in version
1.39.1
88f15d17dca836346e787762685a40bb5cce75a8

**Comment by Mystic8b** [comment]
Still not opening on kubuntu 19.10 when installing through Discover

**Comment by erikthered** [comment]
I'm still having this issue with the snap on Manjaro 18.1.1

```
code --version
1.39.2
6ab598523be7a800d7f3eb4d92d7ab9a66069390
x64
```

**Comment by erikthered** [comment]
I think the root cause here is the glibc version on Ubuntu 16.04 is too old. I'm going to see if I can get the snap to working using 18.04 as the base.

**Comment by erikthered** [comment]
Changing the base in snapcraft.yml to `core18` didn't work either. I think part of the problem is that i'm on Manjaro, so when I run `yarn gulp vscode-linux-x64` it's linking to my glibc version which gets passed into the multipass environment during the snap build.

**Comment by andresma2490** [comment]
Same problem on Manjaro 18.1.1 - kernel 5.3.6

**Comment by glutaminefree** [comment]
> Same problem on Manjaro 18.1.1 - kernel 5.3.6

But problem not in vscode. On Manjaro any Electron app not working. I tried with Slack and Atom too.

**Comment by erikthered** [comment]
All Electron apps or only those installed via snap?

**Comment by glutaminefree** [comment]
> All Electron apps or only those installed via snap?
only those installed via snap

Atom from official repo works fine.

**Comment by Mystic8b** [comment]
> only those installed via snap. Atom from official repo works fine.
You can install vscode via deb from the off site, as I did. This solved my problem.

**Comment by glutaminefree** [comment]
> You can install vscode via deb from the off site, as I did. This solved my problem.

I don't need vscode actually. Want to apps from snap to work in my Manjaro. And **deb** don't work at Manjero linux.

**Comment by vkasraj** [comment]
> only those installed via snap. Atom from official repo works fine.

Slack and Postman snaps are working fine.

> **It worked for me**
> 
> Snap version of vscode doesn't open/works (don't uninstall yet).
> 
> Install ~pacman~ AUR version of code and then uninstall it.
> 
> Now open snap version. Hurray  Its working.
> 
> ### Code Version
> ```shell
> 1.38.0
> ```
> 
> ### OS Version
> ```shell
> Manjaro Linux 18.1.0
> ```
> 
> ### Kernel
> ```shell
> 5.2.11
> ```
Also I am currently using vscode snap via this trick.

**Comment by glutaminefree** [comment]
> You can install any app from AUR.

Thank! Found fresh Slack and Atom on AUR. Don't know why can't did it yesterday.

**Comment by erikthered** [comment]
I tried the workaround proposed by @vkasraj above, but the snap version still doesn't work for me. Looks like I'll be using the AUR version for now.

**Comment by msenol86** [comment]
Same issue. I think all electron apps have that problem. 
```
[msenol@msenol-manjaro ~]$ code --disable-extensions --verbose 
(process:11581): Gtk-WARNING **: 20:23:48.436: Locale not supported by C library.
	Using the fallback 'C' locale.
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
/usr/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/usr/lib/gio/modules/libgiognutls.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
/usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libcrypto.so.1.1)
Failed to load module: /usr/lib/gio/modules/libgioopenssl.so
Gtk-Message: 20:23:48.467: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:23:48.468: Failed to load module "canberra-gtk-module"

```

```
[msenol@msenol-manjaro ~]$ snap list
Name               Version                     Rev   Tracking  Publisher   Notes
code               6ab59852                    18    stable    vscode✓     classic
core               16-2.42                     7917  stable    canonical✓  core
core18             20191010                    1223  stable    canonical✓  base
gnome-3-28-1804    3.28.0-14-g9303a49.9303a49  91    stable    canonical✓  -
gtk-common-themes  0.1-25-gcc83164             1353  stable    canonical✓  -
hello-world        6.4                         29    stable    canonical✓  -
snap-store         20191021.a9948d5            201   stable    canonical✓  -
```

```
[msenol@msenol-manjaro ~]$ uname -a
Linux msenol-manjaro 5.3.7-2-MANJARO #1 SMP PREEMPT Tue Oct 22 18:56:05 UTC 2019 x86_64 GNU/Linux

```

**Comment by Ortega-Dan** [comment]
FOR REAL ... if you install vscodium from AUR ... then code from snap will work. It seems to be a matter of dependencies. !!!

**Comment by Ortega-Dan** [comment]
then you are able to uninstall vscodium !! and code from snap will continue working.

**Comment by kaioduarte** [comment]
@Ortega-Dan thanks for this suggestions, I just installed the missing dependencies of vscodium and it worked.

BTW the dependecies were: `libdbusmenu-glib` and `gconf`

**Comment by Ortega-Dan** [comment]
> @Ortega-Dan thanks for this suggestion, I just installed the missing dependencies of vscodium and it worked.
> 
> BTW the dependecies were: `libdbusmenu-glib` and `gconf`

Thanks for the confirmation

**Comment by PhilParisot** [comment]
just tried installing vscode from snap store on Manjaro, not working...

**Comment by cmanville** [comment]
I can confirm that installing `libdbusmenu-glib` and `gconf` on Manjaro 18 as kaioduarte suggested allowed me to launch the vscode snap.

**Comment by lucax88x** [comment]
I can also confirm that, just install these 2 and code will works flawless!

**Comment by emnovaes** [comment]
Same issue. 

**Resolved with >>>> $ sudo pacman -S gconf**

_**Befor fix the issue, it was**_
$ uname -a
Linux edson-pc 5.4.2-1-MANJARO #1 SMP PREEMPT Thu Dec 5 09:55:57 UTC 2019 x86_64 GNU/Linux

$ code --verbose
(process:9810): Gtk-WARNING **: 21:01:32.150: Locale not supported by C library.
	Using the fallback 'C' locale.
/usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libcrypto.so.1.1)
Failed to load module: /usr/lib/gio/modules/libgioopenssl.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
/usr/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/usr/lib/gio/modules/libgiognutls.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognutls.so

**Comment by marcelovicentegc** [comment]
Thanks @Ortega-Dan!

**Comment by ducphamhoang** [comment]
> @Ortega-Dan thanks for this suggestion, I just installed the missing dependencies of vscodium and it worked.
> 
> BTW the dependecies were: `libdbusmenu-glib` and `gconf`

Yes it really worked!!
Many thanks

**Comment by Vipin-V** [comment]
> then you are able to uninstall vscodium !! and code from snap will continue working.

Thanks this worked for me...

**Comment by samirkushwaha** [comment]
> Same issue.
> 
> **Resolved with >>>> $ sudo pacman -S gconf**
> 
> _**Befor fix the issue, it was**_
> $ uname -a
> Linux edson-pc 5.4.2-1-MANJARO #1 SMP PREEMPT Thu Dec 5 09:55:57 UTC 2019 x86_64 GNU/Linux
> 
> $ code --verbose
> (process:9810): Gtk-WARNING **: 21:01:32.150: Locale not supported by C library.
> Using the fallback 'C' locale.
> /usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
> Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
> /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libcrypto.so.1.1)
> Failed to load module: /usr/lib/gio/modules/libgioopenssl.so
> /usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
> Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
> /usr/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
> Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
> /usr/lib/gio/modules/libgiognutls.so: undefined symbol: g_task_set_name
> Failed to load module: /usr/lib/gio/modules/libgiognutls.so

This works!
Thanks!

**Comment by raphtlw** [comment]
Getting the same issue too :(

**Comment by murmur-wheel** [comment]
same issue

**Comment by xsoheilalizadeh** [comment]
Same Issue
```
Linux s-x580vd 5.4.23-1-MANJARO #1 SMP PREEMPT Fri Feb 28 22:45:29 UTC 2020 x86_64 GNU/Linux
```

```
➜  ~ code --verbose
/usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libcrypto.so.1.1)
Failed to load module: /usr/lib/gio/modules/libgioopenssl.so
/usr/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/usr/lib/gio/modules/libgiognutls.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
Gtk-Message: 19:40:45.546: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:40:45.548: Failed to load module "canberra-gtk-module"

```
```
# code --version
1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
```

**Comment by codeforcesmeme** [comment]
Same issue Manjaro Linux 19 
solved with 
```
sudo pacman -S gconf
```

**Comment by codeforcesmeme** [comment]
@flexiondotorg

**Comment by johncambefort** [comment]
VSCode wasn't working for me via snap either (Manjaro 19.0.2).

I initially ran `sudo pacman -S code` which downloaded the Open-sourced version of Code ("OSS").
I then installed the 'actual' VSCode with snap.
When I would run `code .` in command line, OSS would open and not VSCode.
I uninstalled OSS with pacman, installed the gconf package suggested by codeforcesmeme above, and now `code .` works all fine.

**Comment by amyspark** [comment]
If I've traced this correctly, it's broken since #65744 (which removed `gconf` from the snap).

**Comment by curusarn** [comment]
I have the same issue but installing gconf does not solve it for me:
```
❯ sudo pamac install libdbusmenu-glib
Preparing...
Warning: libdbusmenu-glib-16.04.0-4 is up to date -- skipping
Nothing to do.
Transaction successfully finished.

❯ sudo pamac install gconf           
Preparing...
Warning: gconf-3.2.6+11+g07808097-7 is up to date -- skipping
Nothing to do.
Transaction successfully finished.

❯ code --verbose                
/usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
/usr/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libcrypto.so.1.1)
Failed to load module: /usr/lib/gio/modules/libgioopenssl.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
/var/lib/snapd/snap/code/30/usr/share/code/../../lib/x86_64-linux-gnu/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
Gtk-Message: 22:03:29.910: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:03:29.912: Failed to load module "canberra-gtk-module"

❯ snap --version
snap     2.44.3-1
snapd    2.44.3-1
series   16
manjaro  -
kernel   4.19.114-1-MANJARO
```

**Comment by V1ncNet** [comment]
> Same issue Manjaro Linux 19
> solved with
> 
> ```
> sudo pacman -S gconf
> ```

Works on my system w/ Manjaro GNOME 20.0.3 and Kernel version 5.6.16

**Comment by JohnnyDevNull** [comment]
Is still not working on Manjaro 20. KDE

```
[user@computer ~]$ code --verbose
Gtk-Message: 05:52:56.964: Failed to load module "canberra-gtk-module"
/var/lib/snapd/snap/code/37/usr/share/code/../../lib/x86_64-linux-gnu/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_system_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libcrypto.so.1.1)
Failed to load module: /usr/lib/gio/modules/libgioopenssl.so
/usr/lib/gio/modules/libgiolibproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiolibproxy.so
/usr/lib/gio/modules/libgiognomeproxy.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/gio/modules/libgiognomeproxy.so
(code:4218): Gtk-WARNING **: 05:52:56.975: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(code:4218): Gtk-WARNING **: 05:52:56.975: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
(code:4218): Gtk-WARNING **: 05:52:56.975: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
(code:4218): GdkPixbuf-WARNING **: 05:52:56.978: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
```

**Comment by ktw** [comment]
On Solus (with gconf installed)
```
code --verbose
/snap/code/36/usr/share/code/../../lib/x86_64-linux-gnu/libgnutls.so.30: version `GNUTLS_3_6_3' not found (required by /usr/lib/gio/modules/libgiognutls.so)
Failed to load module: /usr/lib/gio/modules/libgiognutls.so
/snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/libcrypto.so.1.1)
Failed to load module: /usr/lib/gio/modules/libgioopenssl.so
/usr/lib/gio/modules/libgioremote-volume-monitor.so: undefined symbol: g_mount_operation_get_is_tcrypt_hidden_volume
Failed to load module: /usr/lib/gio/modules/libgioremote-volume-monitor.so
(code:4412): GdkPixbuf-WARNING **: 08:06:04.668: Cannot open pixbuf loader module file '/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory
```

**Comment by YasinBoloorchi** [comment]
> FOR REAL ... if you install vscodium from AUR ... then code from snap will work. It seems to be a matter of dependencies. !!!

Thanks, that really helped. now it's working for me on manjaro.

**Comment by fpizzicol** [comment]
Same issue here, I'm on *Manjaro 20.1.1*, XFCE on kernel 5.8.11-1. I'm using the snap version of vs code.

After analyze the output of `code --verbose`, I just ran the command bellow and it's all working now.
`gdk-pixbuf-query-loaders > /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache`

**Comment by joaomoreno** [comment]
The gdkpixbuf issue is now fixed.
