### ISSUE TITLE
Explorer: running mem-fs on a single folder workspace results in "!" for root folder

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#77419]
Issue Type: <b>Bug</b>

**repo**
1. Start the fs-provider example: https://github.com/Microsoft/vscode-extension-samples/tree/master/fsprovider-sample
1. Invoke `MemFS: Setup workspace`

**Bug**
The extension is deactived and then not reactived 

If you reload the window, then the extension is resolved properly

VS Code version: code-oss-dev 1.37.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
We should activate them after extension host restart. Happy for a PR if someone wants to chime in with a reasonably small fix.

**Comment by bpasero** [comment]
This was an exception thrown between restarting the extension host, good catch!

**Comment by mjbvz** [comment]
Ok, I'm seeing the extension activated now but the sample still doesn't work so I'm reopening this:

![Screen Shot 2019-08-28 at 2 41 39 PM (3)](https://user-images.githubusercontent.com/12821956/63894658-09559780-c9a2-11e9-821b-d7c1d70457e9.png)

After running this command, I actually see memfs activated twice which is strange:

![Screen Shot 2019-08-28 at 2 45 43 PM](https://user-images.githubusercontent.com/12821956/63894843-88e36680-c9a2-11e9-803a-05e8ab0b5827.png)

I attached to the extension host to debug but did not see any obvious crashes

Feel free to split this out into a new issue if it is not related to the original bug.

**Comment by bpasero** [comment]
@mjbvz I cannot reproduce that, did you start from an empty workspace?

![before](https://user-images.githubusercontent.com/900690/63914463-93017580-ca33-11e9-8f44-ec78c61d1eb6.gif)

**Comment by bpasero** [comment]
Btw since this fix landed in our recovery release already last month, I am quite confident that it works.

**Comment by mjbvz** [comment]
I can confirm it works when you run that command in an empty workspace.

The example extension still fails for me when I run `MemFS: Setup workspace` with a folder already open

![Aug-29-2019 10-40-52](https://user-images.githubusercontent.com/12821956/63963284-8b4ccb80-ca49-11e9-95ec-71d1f585f0e9.gif)

**Comment by bpasero** [comment]
Moving to @jrieken for the extension and @isidorn for the explorer. I see the folder is added but shows with a "!". Maybe a consequence of us restarting the extension host when the first folder is added, which would mean this is a duplicate of https://github.com/microsoft/vscode/issues/69335

**Comment by jrieken** [comment]
The extension always forgets everything after reload, you always need to run the 'create files' command

**Comment by bpasero** [comment]
Ok then the remaining issue is the "!" for the folder, I would think that it should not happen. Maybe this is a race condition from adding the first folder and restarting the extension host meanwhile.

**Comment by isidorn** [comment]
The issue here is the following:
1. We are transitioning to a workspace, there is no previous view state, so the explorer decides to expand all the root nodes (as a heuristic)
2. Since the memfs can not be expanded (the MemFS Create Files was not yet triggered) - `FileService` returns a `Canceled` promise when I do `fileService.resolve`
3. Since I got the error from the `FileService` I simply show it as a broken root in the explorer

Suggestions on how to tackle this are welcome.
I am also not sure why the `FileService` returns a `Canceled` instead of giving an empy array of children?
