### ISSUE TITLE
Debug smoketest failure

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#78384]
Occurs on Windows.

```
  1) Running Code
       Debug
         focus stack frames and variables:
     Error: Timeout: get element '.tabs-container div.tab[aria-label="index.js, tab"]' after 20 seconds.
      at D:\repos\Microsoft\vscode\test\smoke\out\vscode\code.js:163:23
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)
```

**Comment by isidorn** [comment]
The issue is that when there is not enough space in the call stack view the index.js title gets shrinked and the smoke test can not match it.
Assigning to August to fix

**Comment by isidorn** [comment]
@alexr00 can you still reproduce this on Windows? If yes can you please ping me once you get this on your machine I need to investigate. Since I can not reproduce on my mac with a very small vscode.

**Comment by alexr00** [comment]
I cannot reproduce on my laptop. It happened before on my desktop, so I will try again there.

**Comment by isidorn** [comment]
@alexr00 ok, thanks.

**Comment by alexr00** [comment]
I cannot reproduce now.

**Comment by alexr00** [comment]
It is back: 
```
  3) Running Code
       Debug
         focus stack frames and variables:
     Error: Timeout: get element '.tabs-container div.tab[aria-label="index.js, tab"]' after 20 seconds.
      at D:\repos\Microsoft\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (D:\repos\Microsoft\vscode\test\automation\out\code.js:8:58)
```

**Comment by isidorn** [comment]
In some other issue you said you can run it happily now so I will optimistically close it 🤞

**Comment by dbaeumer** [comment]
Reopening since the debug smoke tests fail very badly for me:

```
    Debug
** Timeout!
Did not pass accept function
      1) configure launch json
      √ breakpoints
** Timeout!
Did not pass accept function
      2) start debugging
** Timeout!
Did not pass accept function
      3) focus stack frames and variables
** Timeout!
Did not pass accept function
      4) stepOver, stepIn, stepOut
** Timeout!
Error: Element not found: .debug-toolbar .action-label[title*="Continue"]
    at WindowDriver._getElementXY (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/platform/driver/browser/baseDriver.js:123:39)
    at WindowDriver._click (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/platform/driver/electron-browser/driver.js:30:41)
    at WindowDriver.click (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/platform/driver/electron-browser/driver.js:24:25)
    at WindowDriverChannel.call (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/platform/driver/node/driver.js:125:50)
    at ChannelServer.onPromise (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/parts/ipc/common/ipc.js:202:35)
    at ChannelServer.onRawMessage (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/parts/ipc/common/ipc.js:184:33)
    at file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/parts/ipc/common/ipc.js:144:73
    at Emitter.fire (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/common/event.js:458:38)
    at EventEmitter.fn (file:///C:/Users/dirkb/Projects/mseng/VSCode/vscode/out/vs/base/common/event.js:259:44)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (C:\Users\dirkb\Projects\mseng\VSCode\vscode\.build\electron\resources\electron.asar\renderer\init.js:42:16)
      5) continue
** Timeout!
Did not pass accept function
      6) debug console
```

**Comment by isidorn** [comment]
Yes, the issue is that we introduced the new debug start view and I did not update the smoke test to reflect that. Will look into it

**Comment by isidorn** [comment]
I have updated the smoke test that it now takes into account the new debug start view.
Please note that this does not mean that all the debug smoke test issues are fixed. Just that it should work now most of the time.

**Comment by dbaeumer** [comment]
I am reopening this since I still see this failing on creating the launch config json file.

**Comment by dbaeumer** [comment]
```
 1) Running Code
       Debug
         configure launch json:
     Error: ENOENT: no such file or directory, open 'C:\Temp\t18440zFRawuqCHKhy\vscode-smoketest-express\.vscode\launch.json'
      at Object.openSync (fs.js:439:3)
      at Object.readFileSync (fs.js:344:35)
      at Context.<anonymous> (out\areas\debug\debug.test.js:20:32)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by isidorn** [comment]
Works on other platofrms, will not fix it today -> moving out of milestone

**Comment by dbaeumer** [comment]
While running the final smoke test I see this:

```
 1) Running Code
       Debug
         configure launch json:
     Error: ENOENT: no such file or directory, open 'C:\Temp\t20372YKEHs14w2Qly\vscode-smoketest-express\.vscode\launch.json'
      at Object.openSync (fs.js:439:3)
      at Object.readFileSync (fs.js:344:35)
      at Context.<anonymous> (out\areas\debug\debug.test.js:20:32)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) Running Code
       Debug
         breakpoints:
     Error: Timeout: get element '.tabs-container div.tab.active[aria-selected="true"][aria-label="index.js, tab"]' after 20 seconds.
      at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\automation\out\code.js:8:58)

  3) Running Code
       Debug
         start debugging:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .monaco-list-row .stack-frame' after 20 seconds.
      at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\automation\out\code.js:8:58)

  4) Running Code
       Debug
         focus stack frames and variables:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .debug-variables .monaco-list-row .expression' after 20 seconds.
      at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\automation\out\code.js:8:58)

  5) Running Code
       Debug
         stepOver, stepIn, stepOut:
     Error: Timeout: get elements 'div[id="workbench.view.debug"] .monaco-list-row .stack-frame' after 20 seconds.
      at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\automation\out\code.js:8:58)

  6) Running Code
       Debug
         continue:
     Error: Timeout: click '.debug-toolbar .action-label[title*="Continue"]' after 20 seconds.
      at C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\automation\out\code.js:175:23
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\dirkb\Projects\mseng\VSCode\vscode\test\automation\out\code.js:8:58)


```

**Comment by isidorn** [comment]
I have moved the debug smoke test to integration tests.
Thus this is no longer valid.
The integration tests do not behave flaky so far.
