### ISSUE TITLE
Search view freezes with a long single line before and after search

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#78698]
- VSCode Version: Issue is the same in Stable, Insiders and Exploration
- OS Version: macOS

Steps to Reproduce:

1. Open project which consists a file with a long single line
2. Type word in search view and press search
3. You will see Search View is freeze and VS Code is stuck and you can't do anything

Before rendering items in Search View it freezes and after search is done when you scroll through items it freezes. Something is really wrong if file with one single long line exist in the project.

Here is video of showing how the problem looks like:

**Search View freezes after search while scrolling through items**
https://streamable.com/uv8wl

**Search View freezes before search**
https://streamable.com/ugktu

Here is the files to reproduce it by using "Steps to Reproduce" mentioned above. Simple paste them into the new folder and try to search keyword `production`.

https://gist.github.com/svipas/227945440e2f81756eea721ddb2e65bb
https://gist.github.com/svipas/8c32e2dcc2208d78b0cf5b5390d0fc3b

_You could copy them to make at least 2 same copies to experience even worst freeze. And with real project it's 10x times worst._

I did similar test in the Atom, Sublime Text and WebStorm. All handles this problem properly and works as expected.

_For me it looks like the search itself works fine, but Search View can't handle to render items with very long lines._

/cc @roblourens

**Comment by roblourens** [comment]
Please test this in the latest insiders build, I think this is fixed now.

**Comment by svipas** [comment]
I feel it's a little bit better than before, but unfortunately issue still exists.

<img width="458" alt="Screen Shot 2019-08-12 at 23 47 15" src="https://user-images.githubusercontent.com/10441177/62897255-8efb0580-bd5b-11e9-8eea-f2b565172a76.png">

It freezes while doing search, after search is done it freezes when I scroll to the long lines in the search view. And only solution is to kill VS Code's process because it's stuck or try to switch to files view or other view.

```
Version: 1.38.0-insider
Commit: de320052255d136673fc5eee358f6e2551d6573e
Date: 2019-08-12T07:25:46.175Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by roblourens** [comment]
Dupe of https://github.com/microsoft/vscode/issues/78698

**Comment by svipas** [comment]
@roblourens this is #78698, it can’t be dupe of itself, I guess you made a typo?

**Comment by roblourens** [comment]
Oops: https://github.com/microsoft/vscode/issues/109902
