### ISSUE TITLE
Explorer tree does not show correct content when connected to case sensitive file system on a case insensitive platform

### ISSUE THREAD

**Issue by svenax** [microsoft/vscode#79205]
Issue Type: <b>Bug</b>

Opening a project on a volume using case sensitive file system does not show all files/folders in the explorer tree. Quick Open does work as expected.

VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T01:22:37.660Z)
OS version: Darwin x64 18.7.0

**Comment by isidorn** [comment]
Can you please provide reproducable steps?
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
Can you please post some picture?

**Comment by svenax** [comment]
- Create a case sensitive volume with Disk Utility.
- In a terminal window, execute `touch file.txt File.txt; mkdir dir Dir`
- Verify that `ls` shows something like
![2019-08-15_15-43-03](https://user-images.githubusercontent.com/8472/63098991-68fc7d80-bf74-11e9-9442-780543a61c5a.png)
- The Explorer tree shows only
![2019-08-15_15-43-31](https://user-images.githubusercontent.com/8472/63099395-4f0f6a80-bf75-11e9-9268-93e3b5c916ae.png)
- The Quick Open menu shows e.g.
![2019-08-15_15-44-10](https://user-images.githubusercontent.com/8472/63099445-69494880-bf75-11e9-98ea-6ac06d9cc067.png)

**Comment by isidorn** [comment]
This works fine for me on Linux.
The issue for you is that you are on a case insenstive platform and you are connecting to a case sensitive one. That case we are not fully supporting it seems. Leaving this open as a feature request for the future.

![Screenshot 2019-08-15 at 17 10 20](https://user-images.githubusercontent.com/1926584/63104637-a0245c00-bf7f-11e9-97e1-67a0a22d7f01.png)

**Comment by IllusionMH** [comment]
It will really relevant with more users of Remote-* extensions
![image](https://user-images.githubusercontent.com/1312662/63110888-1e3f2d80-bf95-11e9-9004-e8d798b07d8f.png)

**Comment by isidorn** [comment]
@IllusionMH agree, adding it to On-Deck so we tackle this soon.

**Comment by isidorn** [comment]
Should be fixed via https://github.com/microsoft/vscode/issues/48258
Please try out vscode insiders from tomorrow

**Comment by IllusionMH** [comment]
@isidorn not fixed for me for WSL1.

Is it expected that this case is not handled by #48258 fix?

![image](https://user-images.githubusercontent.com/1312662/71079409-e854c480-2193-11ea-98a3-1a34972d9540.png)

VS Code version: Code - Insiders 1.42.0-insider (4636be2b71c87bfb0bfe3c94278b447a5efcc1f1, 2019-12-18T05:41:55.003Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (16.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|Memory (System)|31.72GB (16.68GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.41.6


</details>

**Comment by isidorn** [comment]
It should be fixed by 8bc277fa7b
So the next insiders should have it. Sorry for the confusion!

**Comment by isidorn** [comment]
@IllusionMH does this work now as expected? Thanks!

**Comment by IllusionMH** [comment]
@isidorn yes, works as expected. Thanks!
![image](https://user-images.githubusercontent.com/1312662/72797340-9814ca80-3c49-11ea-855d-19b67d2f65e0.png)

**Comment by isidorn** [comment]
Great, adding verified label. Thanks!
