### ISSUE TITLE
quick open is slow for large repos

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode#79988]
We have a big repo with 100k files, 18k folders, 18GB and I find quick open to be very slow especially when compared to sublime text.

When I start quick open and type a file name it takes around 7 seconds to show results, compared to sublime text which is instantaneous and even shows a preview buffer of the file.

I also noticed that the second time I search in quick open (without closing the panel) it is much faster to show the results.

example:  ctrl + p to launch quick open, I type Util.cpp, it takes around 7 seconds to show the results, I deleted Util.cpp from the searchbox and type Helper.cpp, now it only takes 1 second to show results.

It would be nice if we can have a search speed similar to the one of sublime.

**Comment by roblourens** [comment]
The second time, the search results are cached. You can see whether any tips here help: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory

**Comment by psclkhoury** [comment]
@roblourens I did all the steps and I still have the same delay.

I disabled followSymlinks, I already had a big list of files.exclude patterns, windows defender is not kicking in when I search, and vscode and rg.exe are added to the list of trusted programs in my anti-virus.

**Comment by roblourens** [comment]
Ok thanks for trying that. Today I fixed an issue that could help you here. Would appreciate if you try the Insiders build. https://github.com/microsoft/vscode/issues/79909

**Comment by psclkhoury** [comment]
Still the same with the latest Insiders build. I think something is being loaded the first time which is why it's taking this much time. I tried the following:
- opened quick open
- left it open for about 7 seconds (no input was in the search box)
- then I typed a file name and the results were fast just like it was the second time I was searching

**Comment by roblourens** [comment]
Yeah, it sounds likely that there's nothing "wrong", this is just the speed that our search tool runs on your machine.

**Comment by psclkhoury** [comment]
well all other tools from Sublime to vim to emacs show instant results except for vscode. I guess it must be my machine then.

**Comment by roblourens** [comment]
Sublime does index your workspace ahead of time, and you can see this in the CPU spike when you open a large workspace. Other editors, it depends. I'm curious which command or external tool you are using in vim as a comparison?

**Comment by psclkhoury** [comment]
@roblourens why doesn't vscode also index the workspace? Atom does it and searching for files is fast.
