### ISSUE TITLE
Minifier: remove hoist_funs: true configuration once it is safe

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80202]
When we minify, we have to pass in `hoist_funs: true`, otherwise we get below results:

![image](https://user-images.githubusercontent.com/900690/64103657-ff9dac80-cd72-11e9-9923-f7adf6601b26.png)

Somehow our json parser stumbles over our language configurations otherwise. I have not fully figured out why that is, but this is something we should follow up.

To reproduce:
* search for `hoist_funs: true` in `build/lib/optimize.ts` and change it to `false`
* `yarn gulp vscode-darwin-min`
* run the minified build

//cc @chrmarti

**Comment by aeschli** [comment]
I pushed a commit to improve the parse errors

**Comment by bpasero** [comment]
@aeschli where to? I can try to run a build with it

**Comment by bpasero** [comment]
Here is a build with `hoist_funs: false` after your change that still reproduces it: https://1drv.ms/u/s!AlosdmnPnzYbollkPHdWrhdtirYb?e=NjbL2P

Full output after your change:

```
workbench.desktop.main.js:3568 [Extension Host] debugger listening on port 12082
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/groovy/package.json: [542, 8] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/groovy/package.json: [92, 458] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/groovy/package.json: [92, 458] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/groovy/package.json: [92, 458] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/groovy/package.json: [92, 458] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/javascript/package.json: [802, 8] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/javascript/package.json: [92, 718] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/javascript/package.json: [92, 718] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/javascript/package.json: [92, 718] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/javascript/package.json: [92, 718] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/less/package.json: [860, 7] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/less/package.json: [92, 775] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/less/package.json: [92, 775] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/less/package.json: [92, 775] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/less/package.json: [92, 775] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/less/package.json: [92, 775] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/make/package.json: [616, 6] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/make/package.json: [92, 530] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/make/package.json: [92, 530] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/make/package.json: [92, 530] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/make/package.json: [92, 530] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/perl/package.json: [560, 8] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/perl/package.json: [92, 476] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/perl/package.json: [92, 476] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/perl/package.json: [92, 476] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/perl/package.json: [92, 476] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/php/package.json: [403, 6] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/php/package.json: [92, 317] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/php/package.json: [92, 317] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/php/package.json: [92, 317] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/php/package.json: [92, 317] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/powershell/package.json: [385, 6] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/powershell/package.json: [92, 299] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/powershell/package.json: [92, 299] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/powershell/package.json: [92, 299] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/powershell/package.json: [92, 299] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/python/package.json: [476, 6] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/python/package.json: [92, 390] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/python/package.json: [92, 390] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/python/package.json: [92, 390] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/python/package.json: [92, 390] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ruby/package.json: [615, 6] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ruby/package.json: [92, 529] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ruby/package.json: [92, 529] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ruby/package.json: [92, 529] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ruby/package.json: [92, 529] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/scss/package.json: [1282, 3] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/scss/package.json: [92, 1193] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/scss/package.json: [92, 1193] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/scss/package.json: [92, 1193] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/scss/package.json: [92, 1193] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/scss/package.json: [92, 1193] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/scss/package.json: [92, 1193] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/shellscript/package.json: [791, 8] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/shellscript/package.json: [92, 707] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/shellscript/package.json: [92, 707] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/shellscript/package.json: [92, 707] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/shellscript/package.json: [92, 707] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/xml/package.json: [1083, 4] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/xml/package.json: [92, 995] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/xml/package.json: [92, 995] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/xml/package.json: [92, 995] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/xml/package.json: [92, 995] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/package.json: [2692, 4] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/package.json: [34, 2662] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/package.json: [34, 2662] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/package.json: [34, 2662] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/package.json: [34, 2662] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/package.json: [34, 2662] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/package.json: [34, 2662] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug2/package.json: [34, 2662] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/emmet/package.json: [5775, 3] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/emmet/package.json: [110, 5668] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/emmet/package.json: [110, 5668] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/emmet/package.json: [110, 5668] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/emmet/package.json: [110, 5668] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/emmet/package.json: [110, 5668] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/emmet/package.json: [110, 5668] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/emmet/package.json: [110, 5668] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug/package.json: [4707, 4] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug/package.json: [34, 4677] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug/package.json: [34, 4677] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug/package.json: [34, 4677] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug/package.json: [34, 4677] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug/package.json: [34, 4677] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug/package.json: [34, 4677] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/ms-vscode.node-debug/package.json: [34, 4677] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/typescript-language-features/package.json: [22879, 7] .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/typescript-language-features/package.json: [92, 22794] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/typescript-language-features/package.json: [92, 22794] Closing bracket expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/typescript-language-features/package.json: [92, 22794] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/typescript-language-features/package.json: [92, 22794] Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/html-language-features/package.nls.json: .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/html-language-features/package.nls.json: Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key displayName.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key description.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.customData.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.enable.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.wrapLineLength.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.unformatted.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.contentUnformatted.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.indentInnerHtml.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.preserveNewLines.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.maxPreserveNewLines.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.indentHandlebars.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.endWithNewline.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.extraLiners.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.wrapAttributes.auto.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.wrapAttributes.force.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.wrapAttributes.forcealign.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.wrapAttributes.forcemultiline.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.wrapAttributes.alignedmultiple.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.wrapAttributes.preserve.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.wrapAttributes.preservealigned.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.format.wrapAttributes.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.suggest.html5.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.validate.scripts.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.validate.styles.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.autoClosingTags.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key html.trace.server.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/markdown-language-features/package.nls.json: .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/markdown-language-features/package.nls.json: Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key displayName.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key description.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.title.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.previewSide.title.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.showLockedPreviewToSide.title.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.showSource.title.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.showPreviewSecuritySelector.title.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.refresh.title.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.toggleLock.title.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.styles.dec.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.breaks.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.linkify.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.fontFamily.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.fontSize.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.lineHeight.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.scrollPreviewWithEditor.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.scrollPreviewWithEditorSelection.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.scrollPreviewWithEditorSelection.deprecationMessage.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.markEditorSelection.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.scrollEditorWithPreview.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.preview.doubleClickToSwitchToEditor.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key configuration.markdown.preview.openMarkdownLinks.description.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key configuration.markdown.preview.openMarkdownLinks.inPreview.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key configuration.markdown.preview.openMarkdownLinks.inEditor.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key markdown.trace.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/css-language-features/package.nls.json: .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/css-language-features/package.nls.json: Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key displayName.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key description.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.title.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.customData.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.completion.triggerPropertyValueCompletion.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.validate.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.compatibleVendorPrefixes.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.vendorPrefix.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.duplicateProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.emptyRules.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.importStatement.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.boxModel.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.universalSelector.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.zeroUnits.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.fontFaceProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.hexColorLength.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.argumentsInColorFunction.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.unknownProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.validProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.ieHack.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.unknownVendorSpecificProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.propertyIgnoredDueToDisplay.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.important.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.float.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.idSelector.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.lint.unknownAtRules.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key css.trace.server.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.title.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.validate.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.compatibleVendorPrefixes.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.vendorPrefix.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.duplicateProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.emptyRules.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.importStatement.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.boxModel.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.universalSelector.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.zeroUnits.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.fontFaceProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.hexColorLength.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.argumentsInColorFunction.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.unknownProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.validProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.ieHack.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.unknownVendorSpecificProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.propertyIgnoredDueToDisplay.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.important.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.float.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key scss.lint.idSelector.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.title.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.validate.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.compatibleVendorPrefixes.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.vendorPrefix.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.duplicateProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.emptyRules.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.importStatement.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.boxModel.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.universalSelector.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.zeroUnits.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.fontFaceProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.hexColorLength.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.argumentsInColorFunction.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.unknownProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.validProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.ieHack.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.unknownVendorSpecificProperties.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.propertyIgnoredDueToDisplay.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.important.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.float.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key less.lint.idSelector.desc.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/git/package.nls.json: .
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Failed to parse /Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/extensions/git/package.nls.json: Closing brace expected.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key displayName.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key description.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.clone.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.init.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.openRepository.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.close.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.refresh.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.openChange.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.openFile.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.openFile.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.openHEADFile.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.stage.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.stageAll.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.stageSelectedRanges.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.revertSelectedRanges.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.stageChange.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.revertChange.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.unstage.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.unstageAll.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.unstageSelectedRanges.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.clean.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.cleanAll.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.commit.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.commitStaged.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.commitEmpty.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.commitStagedSigned.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.commitStagedAmend.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.commitAll.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.commitAllSigned.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.commitAllAmend.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.restoreCommitTemplate.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.undoCommit.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.checkout.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.branch.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.branchFrom.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.deleteBranch.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.renameBranch.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.merge.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.createTag.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.fetch.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.fetchPrune.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.fetchAll.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.pull.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.pullRebase.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.pullFrom.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.push.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.pushForce.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.pushTo.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.pushToForce.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.pushFollowTags.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.pushFollowTagsForce.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.addRemote.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.removeRemote.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.sync.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.syncRebase.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.publish.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.showOutput.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.ignore.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.stashIncludeUntracked.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.stash.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.stashPop.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.stashPopLatest.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.stashApply.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key command.stashApplyLatest.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.enabled.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.path.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.autoRepositoryDetection.true.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.autoRepositoryDetection.false.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.autoRepositoryDetection.subFolders.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.autoRepositoryDetection.openEditors.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.autoRepositoryDetection.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.autorefresh.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.autofetch.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.autofetchPeriod.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.branchValidationRegex.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.branchWhitespaceChar.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.confirmSync.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.countBadge.all.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.countBadge.tracked.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.countBadge.off.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.countBadge.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.checkoutType.all.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.checkoutType.local.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.checkoutType.tags.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.checkoutType.remote.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.checkoutType.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.ignoreLegacyWarning.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.ignoreMissingGitWarning.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.ignoreLimitWarning.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.defaultCloneDirectory.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.enableSmartCommit.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.smartCommitChanges.all.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.smartCommitChanges.tracked.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.smartCommitChanges.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.suggestSmartCommit.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.enableCommitSigning.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.confirmEmptyCommits.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.decorations.enabled.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.enableStatusBarSync.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.promptToSaveFilesBeforeCommit.always.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.promptToSaveFilesBeforeCommit.staged.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.promptToSaveFilesBeforeCommit.never.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.promptToSaveFilesBeforeCommit.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.postCommitCommand.none.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.postCommitCommand.push.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.postCommitCommand.sync.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.postCommitCommand.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.showInlineOpenFileAction.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.showPushSuccessNotification.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.inputValidation.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.inputValidationLength.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.inputValidationSubjectLength.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.detectSubmodules.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.detectSubmodulesLimit.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.alwaysShowStagedChangesResourceGroup.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.alwaysSignOff.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.ignoredRepositories.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.scanRepositories.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.showProgress.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.rebaseWhenSync.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.fetchOnPull.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.pullTags.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.autoStash.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.allowForcePush.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.useForcePushWithLease.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.confirmForcePush.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.openDiffOnClick.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.supportCancellation.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key config.branchSortOrder.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key colors.added.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key colors.modified.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key colors.deleted.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key colors.untracked.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key colors.ignored.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key colors.conflict.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:3422 Couldn't find message for key colors.submodule.
_logMessageInConsole @ workbench.desktop.main.js:3422
workbench.desktop.main.js:1508   ERR Problems parsing file icons file: , Closing brace expected, Closing brace expected, Closing brace expected: Error: Problems parsing file icons file: , Closing brace expected, Closing brace expected, Closing brace expected
    at e.readFile.then.e (file:///Users/bpasero/Development/Microsoft/VSCode-darwin/Code - OSS.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4532:79)
```

**Comment by aeschli** [comment]
Problem is in terser: Created https://github.com/terser/terser/issues/445

**Comment by bpasero** [comment]
Awesome. My feeling is to wait for the fix on Terser before changing this function back.

**Comment by bpasero** [comment]
Pushed.
