### ISSUE TITLE
macOS: can not create new file or folder anymore

### ISSUE THREAD

**Issue by lifeofguenter** [microsoft/vscode#80639]
- VSCode Version: 1.38.0
- OS Version: Darwin x64 18.7.0

Steps to Reproduce:

I unfortunately do not know how to re-produce this issue. But every now and then it seems creating new files or folders in the workspace just completely stops to work:

<img width="247" alt="Screenshot 2019-09-10 at 13 08 10" src="https://user-images.githubusercontent.com/241073/64609033-466f5000-d3cc-11e9-9104-d8c3dc2e92fe.png">

After restarting vscode it works again!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
This should be fixed in latest vscode insiders via https://github.com/microsoft/vscode/pull/79383
Please let me know if you can reproduce with latest vscode insiders https://code.visualstudio.com/insiders/ and I can reopen

**Comment by lifeofguenter** [comment]
with latest vscode this is still happening. I have no clue how to reproduce it, and it happens very seldom.

**Comment by isidorn** [comment]
Please let me know if you can reproduce with latest vscode insiders https://code.visualstudio.com/insiders/ and I can reopen

**Comment by lifeofguenter** [comment]
still happening with `Version: 1.39.2`
