### ISSUE TITLE
Unable to connect to remote server getting error "server_name".y.onDidWriteData is not a function

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#80963]
Issue Type: <b>Bug</b>

Unable to connect to remote server getting error "server_name".y.onDidWriteData is not a function

![image](https://user-images.githubusercontent.com/9264813/64940094-b7a57c00-d880-11e9-8985-45d570aefe8c.png)

VS Code version: Code - Insiders 1.39.0-insider (d157c2e941cae17acb79bf26a70bbfad732bdc83, 2019-09-16T06:06:10.647Z)
OS version: Windows_NT x64 10.0.17134
Fetching remote diagnostics for 'SSH' failed: y.onDidWriteData is not a function

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (2.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: y.onDidWriteData is not a function
</details>Extensions: none

**Comment by xiaoyongdong** [comment]
same problem

**Comment by prooyf** [comment]
same problem

**Comment by riba2534** [comment]
same problem

**Comment by sanket-bhalerao** [comment]
this issue is present in the stable build now as well.
unable to work as my workspace is set up on a remote server.

**Comment by iFanze** [comment]
same problem

**Comment by sanket-bhalerao** [comment]
Error from the output console:
[07:47:58.602] remote-ssh@0.46.0
[07:47:58.602] win32 x64
[07:47:58.603] SSH Resolver called for "ssh-remote+angular_serve", attempt 1
[07:47:58.603] SSH Resolver called for host: angular_serve
[07:47:58.603] Setting up SSH remote "angular_serve"
[07:47:58.659] Using commit id "d157c2e941cae17acb79bf26a70bbfad732bdc83" and quality "insider" for server
[07:47:58.668] Testing ssh with ssh -V
[07:47:59.098] ssh exited with code: 0
[07:47:59.098] Got stderr from ssh: OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
[07:47:59.099] Running script with connection command: ssh -D 65534 angular_serve bash
[07:47:59.108] Install and start server if needed
[07:47:59.110] "install" process failed: TypeError: y.onDidWriteData is not a function
[07:47:59.110] y.onDidWriteData is not a function
[07:47:59.110] ------

**Comment by lxy598951** [comment]
same problem

**Comment by azenapow** [comment]
same problem in VSCode insider recently update.

Version: 1.39.0-insider (user setup)
Commit: d157c2e941cae17acb79bf26a70bbfad732bdc83
Date: 2019-09-16T06:06:10.647Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by lustremedia** [comment]
Issue also turned in at the remote extension: https://github.com/microsoft/vscode-remote-release/issues/1417

**Comment by lustremedia** [comment]
Apparently this is the issue: https://github.com/microsoft/vscode-remote-release/issues/1112

**Comment by jfpaccini** [comment]
same issue here

**Comment by evalufran** [comment]
same issue here!!! i get Unable to open 'user': Unable to read file (TypeError: y.onDidWriteData is not a function).

[10:57:39.525] remote-ssh@0.46.0
[10:57:39.525] win32 x64
[10:57:39.526] SSH Resolver called for "ssh-remote+ddserver", attempt 1
[10:57:39.527] SSH Resolver called for host: ddserver
[10:57:39.527] Setting up SSH remote "ddserver"
[10:57:39.618] Using commit id "d157c2e941cae17acb79bf26a70bbfad732bdc83" and quality "insider" for server
[10:57:39.622] Testing ssh with ssh -V
[10:57:39.777] ssh exited with code: 0
[10:57:39.778] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[10:57:39.778] Using SSH config file "C:\Users\Eva\remoteconfig.config"
[10:57:39.778] Running script with connection command: ssh -D 50411 -F C:\Users\Eva\remoteconfig.config ddserver bash
[10:57:39.782] Install and start server if needed
[10:57:39.785] "install" process failed: TypeError: y.onDidWriteData is not a function
[10:57:39.786] y.onDidWriteData is not a function
[10:57:39.786] ------

Please Help!

**Comment by shivakv9** [comment]
same issue :

[11:50:23.999] Testing ssh with ssh -V
[11:50:24.265] ssh exited with code: 0
[11:50:24.265] Got stderr from ssh: OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
[11:50:24.265] Running script with connection command: ssh -D 54350 xenlogin-eqx-02 bash
[11:50:24.300] Install and start server if needed
[11:50:24.303] "install" process failed: TypeError: y.onDidWriteData is not a function
[11:50:24.303] y.onDidWriteData is not a function
[11:50:24.304] ------

**Comment by tttonyyy** [comment]
Same problem here, with 1.39.0-insider.

**Comment by Dayjo** [comment]
Same issue just started arising today for me, Mac OS X. Insider 1.39.0

**Comment by art049** [comment]
Same problem, 1.39.0-insider.

**Comment by techshot25** [comment]
Downgrade to 1.38 and it should work fine
I won't upgrade until the fix the only feature in insiders that matters, remote-ssh

**Comment by dryansweet** [comment]
Link for the lazy.
https://vscode-update.azurewebsites.net/1.38.0-insider/win32-x64/insider

Be sure to turn off auto updates. The ssh session will drop connection even before you restart VS Code.

**Comment by fueler** [comment]
I hit this issue as well.

**Comment by daniel347x** [comment]
I have this issue - Hopefully it can be resolved.  I depend on remote SSH.

Thanks!

**Comment by hsg777** [comment]
I have the same issue with insider version which i noticed this morning. It was fine last I checked on Friday.

**Comment by calebrob6** [comment]
Linux downgrade link for the lazy:
(https://vscode-update.azurewebsites.net/1.38.0-insider/linux-deb-x64/insider)

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/1112

**Comment by roblourens** [comment]
Fixed now, sorry everyone

**Comment by Dayjo** [comment]
Thanks @roblourens, am back to work today :D

**Comment by Zezombye** [comment]
I have the same error on 1.39.0 (not insiders) but it says `v.onDidWriteData` instead of `y.onDidWriteData`. It's apparently not fixed?

**Comment by aimzer** [comment]
I have the same error with `g.onDidWriteData`

`"uname" process failed: TypeError: g.onDidWriteData is not a function`

while connecting to a remote server
