### ISSUE TITLE
Explorer Icons disappeared (Insider Build 1.39.0)

### ISSUE THREAD

**Issue by otrebor-bni** [microsoft/vscode#81089]
Since the last update of VS Insider Build, the explorer icons disappeared.

Before Update:
![image](https://user-images.githubusercontent.com/54057524/65134465-a08f9700-da04-11e9-89d1-ea4a753a9dea.png)

After Update: 
![image](https://user-images.githubusercontent.com/54057524/65134518-b3a26700-da04-11e9-9f73-25d6d769cea4.png)

Version: 1.39.0-insider (user setup)
Commit: cc481ab31b5827add5f99a770f2c860d0575df69
Date: 2019-09-18T07:02:14.165Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by otrebor-bni** [comment]
Has been solved with latest update:
Version: 1.39.0-insider (user setup)
Commit: bdd1971f2cd9d08a8a90e02740f1850afe03da66
Date: 2019-09-17T06:02:08.670Z
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by PowerMogli** [comment]
I still cant see the explorer icons!
![image](https://user-images.githubusercontent.com/5623081/65159698-c7fe5800-da34-11e9-851b-4cb29e591e36.png)

**Comment by otrebor-bni** [comment]
> I still cant see the explorer icons!
> ![image](https://user-images.githubusercontent.com/5623081/65159698-c7fe5800-da34-11e9-851b-4cb29e591e36.png)

It seems that you don't have the latest update (see commit id). you should "Check for Updates" again in VSCode..

**Comment by PowerMogli** [comment]
![image](https://user-images.githubusercontent.com/5623081/65160536-2d067d80-da36-11e9-8d4a-9db6be84d534.png)

**Comment by otrebor-bni** [comment]
I'll reopen this issue. Looks like it depends on windows version too

**Comment by kieferrm** [comment]
We are pushing a new insiders build. Will be out soon.

**Comment by misolori** [comment]
This has been fixed via 6a54c8176fd60745ad7f2ba9dc89af4631752bae and is now released on Insiders.
