### ISSUE TITLE
Can't search for extensions

### ISSUE THREAD

**Issue by JostCrow** [Microsoft/vscode#8110]
- VSCode Version: 1.3.0-insider
- Commit: de66522e06d74752d48d92e934dcd026050355ba
- OS Version: ElementaryOS

Can't search for extensions.
![screenshot from 2016-06-24 17 40 29](https://cloud.githubusercontent.com/assets/390575/16342487/c8bb991a-3a32-11e6-92b3-a4fea0527fc0.png)

**Comment by bpasero** [comment]
Moving to @isidorn since Joao is out next week to consider if this is something for the release. Otherwise feel free to move back.

**Comment by isidorn** [comment]
@JostCrow any search term you input does not procuce results?
If you use the vscode stable release do you see any results when you search for the same terms using our old quick pick ui (F1 > ext install >)

**Comment by JostCrow** [comment]
@isidorn I have tried all kind of different inputs. for instance "python"

in the stable version when I type "ext install python" after pressing F1
![screenshot from 2016-06-27 12 41 43](https://cloud.githubusercontent.com/assets/390575/16377128/89dc2e06-3c64-11e6-9c0f-22cc972bb62b.png)

And in the insiders build you've now got the popular and recommended shortcuts. They also produce empty results.

**Comment by isidorn** [comment]
I can not repro this on my mac / win / ubuntu.
@aeschli can you please try this since you also have elementeryOS

I would think it is a proxy issue but it can't be that since you get results for VSCode stable

**Comment by aeschli** [comment]
Searching for extensions works for me on Elementary OS (Freya) with
Version 1.3.0-insider
Commit 41f53d27a8cb477130f84116c78f43ddacbaf24b
Date 2016-06-27T05:15:21.343Z

**Comment by JostCrow** [comment]
I have the same version. Also Elementary OS (Freya) 
Version 1.3.0-insider
Commit 41f53d27a8cb477130f84116c78f43ddacbaf24b
Date 2016-06-27T05:15:21.343Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

Maybe there is a log that I can check to see if something goes wrong?

**Comment by isidorn** [comment]
@JostCrow I do not think we log this operation - if you open the F1 > developer tools > do you see some errors in the dev console?
@bpasero ideas on how to tackle this are welcome

**Comment by JostCrow** [comment]
There are some errors indeed. I also tried to see what was the problem. The error at line 14 is connected to the extensions search error. _Cannot read property 'domNode' of null: TypeError: Cannot read property 'domNode' of null_

[vscode.txt](https://github.com/Microsoft/vscode/files/334873/vscode.txt)

**Comment by bpasero** [comment]
@JostCrow  We can probably rule out proxy issues by checking if in the stable release you can search for extensions.

**Comment by JostCrow** [comment]
Yes I have never setup a proxy. and also in the office no proxy is active

**Comment by bpasero** [comment]
@JostCrow and you can search for extensions using our stable release from the picker?

**Comment by JostCrow** [comment]
Yes that is possible. It is only in the insiders that I am not able to search. The second screenshot that I posted in this treat is from the picker.

**Comment by isidorn** [comment]
Maybe you can do the following - break on exceptions and try to search for python - if you get an exception location screenshot in dev tools would be most useful


![gettingexception](https://cloud.githubusercontent.com/assets/1926584/16380652/9ee17022-3c78-11e6-9718-b08dd3512159.gif)

**Comment by JostCrow** [comment]
Yes I have done this. 
![screenshot from 2016-06-27 15 09 34](https://cloud.githubusercontent.com/assets/390575/16380758/35487f4c-3c79-11e6-83a1-9c879dba157f.png)

**Comment by isidorn** [comment]
@JostCrow awesome thanks! So it is coming from [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/list/rowCache.ts#L63)
@bpasero I can put a null guard [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/list/listView.ts#L204) but I do not have a deep understanding of the list widget so if you have a better suggestions I am all ears.

**Comment by bpasero** [comment]
We have the same deep understanding of the list widget.

**Comment by isidorn** [comment]
@JostCrow I have pushed a potential fix for this issue - hard to verify since we can not reproduce.
Tomrrow there will be a new insider release with the fix - so please try it out then and let us know how it works. Thanks again for all the help!

**Comment by JostCrow** [comment]
I will let you know tomorrow if it works. Thanks for the support

**Comment by JostCrow** [comment]
This is not yet resolved. The problem was not in the domNode but in the row. The row is null

![screenshot from 2016-06-28 10 00 13](https://cloud.githubusercontent.com/assets/390575/16408096/585b52f4-3d17-11e6-8ac0-a8695835ac2e.png)

**Comment by isidorn** [comment]
@JostCrow my mistake, pushed a fix :)

**Comment by JostCrow** [comment]
Ok Thanks!

**Comment by JostCrow** [comment]
Thanks it is working now

**Comment by joaomoreno** [comment]
Uhhhhhh... the row is never supposed to be `null`... This is a symptom of a deeper problem.

@JostCrow Did #8605 also occur at the same time as this one? It would somehow explain it.

**Comment by JostCrow** [comment]
@joaomoreno Yes they occured at the same time.

**Comment by joaomoreno** [comment]
That explains the `null` then, thanks!
