### ISSUE TITLE
Image preview should not zoom on first click if unfocused

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#81877]
**Repo**
1. Open an image to the side of a text editor
1. Start with the text editor focused
1. Now click into the image editor to focus it

**Bug**
The first click ends up zooming the image. Clicking should only zoom when the editor is already focused

**Comment by mjbvz** [comment]
Here's the relevant code about click handling in the image preview:

https://github.com/microsoft/vscode/blob/04d0cf6ad6ce2c18afc651e7ba13c97827ae3d6f/extensions/image-preview/media/main.js#L164

**Comment by jeanp413** [comment]
If focus is required for zoom, then the cursor when hovering over the image preview should be the default arrow cursor when unfocused, currently it is the zoom-in cursor. Also zooming with the mouse wheel should not be allowed when unfocused. Thoughts?

**Comment by rdrahul** [comment]
I would like to take this up.

**Comment by mjbvz** [comment]
Fixed by #82074

**Comment by alexr00** [comment]
I'm still seeing the first click zoom. Steps:
1. Open a typescript file.
2. Open a gif
3. Move gif to the right so that both typescript and gif are visible and side by side
4. Click in typescript.
5. Click in gif
Expected: no zoom
Actual: it zooms on the click in the gif in (5).

**Comment by MartinBrathen** [comment]
@alexr00 I'm not able to reproduce. Have tried on both insiders 1.40.0 and OSS.

Does this only occur with gifs for you?

**Comment by mjbvz** [comment]
I can repo this. You may need to click back and forth multiple times trigger the error

**Comment by MartinBrathen** [comment]
I'm still not able to. Will try more tomorrow.

A possible cause might be that the ```message``` event is fired before the ```mousedown``` event on the first click. This could be tested by checking the order of execution for the corresponding event handlers in [/vscode/extensions/image-preview/media/main.js](https://github.com/microsoft/vscode/blob/master/extensions/image-preview/media/main.js). I'll do it if I manage to reproduce the bug.
