### ISSUE TITLE
Reveal in Sidebar crashes 

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/vscode#82290]
- VSCode Version: 1.39
- OS Version: Darwin x64 18.7.0

This doesn't happen consistently, but every once in a while, this feature would completely crash and I'd have to restart my editor. The steps are as follows:

* I open a folder, I start editing some code.
* I right click the tab name, and click `Reveal in Sidebar`.
* The whole File explorer is highlighted in blue, without my file actually getting highlighted.

I checked the dev tools, and here is the error that gets shown:

```
  ERR TreeError [FileExplorer] Data tree node not found: [object Object]: Error: TreeError [FileExplorer] Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Applications/VS Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:64272:23)
    at WorkbenchAsyncDataTree.reveal (file:///Applications/VS Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:64253:35)
    at ExplorerView.onSelectResource (file:///Applications/VS Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:292485:31)
```

I traced it down to this line:
https://github.com/microsoft/vscode/blob/b0dccbcf75fd03ac8cc0fa94da5c552a4f47309d/src/vs/base/browser/ui/tree/asyncDataTree.ts#L650

Which indiates that tree items are refreshed/updated somehow, but the key used to look up this map is still referring to the old object? Should this map be indexed by something else? item id (string)?

**Comment by OmarTawfik** [comment]
cc @joaomoreno

**Comment by OmarTawfik** [comment]
@isidorn I couldn't get exact repro steps :( this happens randomly every once in a while, and the only remedy I have is to reload VSCode.
Not sure it is a regression or not. It has been there for many weeks.

**Comment by isidorn** [comment]
Let me know if you find better repro steps!

**Comment by solomatov** [comment]
Does anybody working on it? I want to investigate it.

**Comment by solomatov** [comment]
I reproduced it (though it requires some code instrumentation to make the race condition occur more often):
- You need a folder which is deep enough in the workspace with at least two files. Split the editor open one editor in one half, the other in the other half.
- Create the following script in the root directory:
```
while [ 1 ]
do
  touch a.txt
  sleep 0.2
  rm a.txt
  echo 'tick'
done
```

Create the following function:
```
async function wait(): Promise<void> {
	return new Promise((resolve, reject) => {
		setTimeout(() => resolve(), 500);
	});
}
```

And add its call to the following place:
```
	private async onSelectResource(resource: URI | undefined, reveal = this.autoReveal): Promise<void> {
		if (!resource || !this.isBodyVisible()) {
			return;
		}

		// Expand all stats in the parent chain.
		let item: ExplorerItem | undefined = this.explorerService.roots.filter(i => isEqualOrParent(resource, i.resource))
			// Take the root that is the closest to the stat #72299
			.sort((first, second) => second.resource.path.length - first.resource.path.length)[0];

		while (item && item.resource.toString() !== resource.toString()) {
			await this.tree.expand(item);
			await wait(); <<< HERE
			item = first(values(item.children), i => isEqualOrParent(resource, i.resource));
		}

		if (item && item.parent) {
			if (reveal) {
				this.tree.reveal(item, 0.5);
			}

			this.tree.setFocus([item]);
			this.tree.setSelection([item]);
		} else {
			console.log();
		}
	}
```

Then quickly switch between editors left and right. You will have the console full of these errors:
```
  ERR TreeError [FileExplorer] Data tree node not found: [object Object]: Error: TreeError [FileExplorer] Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:418:23)
    at WorkbenchAsyncDataTree.reveal (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:399:35)
    at ExplorerView.onSelectResource (file:///Users/solomatov/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:415:31)
log.ts:196
  ERR TreeError [FileExplorer] Data tree node not found: [object Object]: Error: TreeError [FileExplorer] Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:418:23)
    at WorkbenchAsyncDataTree.expand (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:324:31)
    at ExplorerView.onSelectResource (file:///Users/solomatov/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:409:33)
log.ts:196
  ERR TreeError [FileExplorer] Data tree node not found: [object Object]: Error: TreeError [FileExplorer] Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:418:23)
    at WorkbenchAsyncDataTree.reveal (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:399:35)
    at ExplorerView.onSelectResource (file:///Users/solomatov/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:415:31)
log.ts:196
  ERR TreeError [FileExplorer] Data tree node not found: [object Object]: Error: TreeError [FileExplorer] Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:418:23)
    at WorkbenchAsyncDataTree.expand (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:324:31)
    at ExplorerView.onSelectResource (file:///Users/solomatov/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:409:33)
log.ts:196
  ERR TreeError [FileExplorer] Data tree node not found: [object Object]: Error: TreeError [FileExplorer] Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:418:23)
    at WorkbenchAsyncDataTree.expand (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:324:31)
    at ExplorerView.onSelectResource (file:///Users/solomatov/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:409:33)
log.ts:196
  ERR TreeError [FileExplorer] Data tree node not found: [object Object]: Error: TreeError [FileExplorer] Data tree node not found: [object Object]
    at WorkbenchAsyncDataTree.getDataNode (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:418:23)
    at WorkbenchAsyncDataTree.reveal (file:///Users/solomatov/vscode/out/vs/base/browser/ui/tree/asyncDataTree.js:399:35)
    at ExplorerView.onSelectResource (file:///Users/solomatov/vscode/out/vs/workbench/contrib/files/browser/views/explorerView.js:415:31)
```

**Comment by solomatov** [comment]
I see several ways to resolve it:
- We need to check whether item we are sent is valid or not
- What to do if it's not? The first idea is to retry, but might it live to livelocks? I.e. if a user uses remote extension over a sketchy connection?

**Comment by solomatov** [comment]
Also, notice that there're two places where exception arises. It happens both in reveal and expand.

**Comment by solomatov** [comment]
I reread the description, and it seems that I don't have the tree highlighted in blue. Though, I used the master version for the fix.

**Comment by solomatov** [comment]
Checked, the tree is functional after such an exception.

**Comment by joaomoreno** [comment]
Cool. But @isidorn, this doesn't seem to nail the exact issue reported by the user since it was originally reported that:

> This doesn't happen consistently, but every once in a while, this feature would completely crash and I'd have to restart my editor.

**Comment by solomatov** [comment]
@joaomoreno @isidorn I fixed it on the master version, so it might have been alleviated by some fixes.

Also, we have our internal users reporting an issues, when the item isn't selected even though, the editor is switched which seems to be very similar to what the PR fixes. I talked to @OmarTawfik about this and it seems that the original issue might be the same as that one.

**Comment by isidorn** [comment]
We have merged a PR which potentially fixes this.
Please try it out with VS Code insiders from Thursday and provide feedback here if it is behaving better. Thank you very much

**Comment by isidorn** [comment]
Let me reopen since the PR probably does not fix the original isssue.
If we are mistaken, do let us know

**Comment by solomatov** [comment]
@isidorn I had this issue on one of stable version of vs.code recently. It was just a file not revealed in the tree, and not completely unusable tree as Omar described.

**Comment by Tyriar** [comment]
Just happened to me again, next time it happens I'll try debug into `explorerModel.findByPath` and see if I can get more info.

**Comment by OmarTawfik** [comment]
@Tyriar looks like it was closed by mistake?

**Comment by LeoLozes** [comment]
Had the same issue today with the last stable version. The fix given here https://github.com/microsoft/vscode/issues/68627#issuecomment-468233168 worked, so maybe it's a regression?
I'm using it with WSL2 and the Remote-WSL extension.

**Comment by isidorn** [comment]
This should be fixed now with latest vscode insdiers since I rewrote parts of exlporer responsible for this.
If you still see this please let me know and we can reopen this issue
