### ISSUE TITLE
When we use auto-complete, text where after cursor will be removed

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#82324]
- VSCode Version: 1.40.0-insider (72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb)
- OS Version: macOSX 10.15

Steps to Reproduce:

1. use auto-complete and press tab

Does this issue occur when all extensions are disabled?: Yes

---

1.40.0-insider (72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb)
![vscode-new](https://user-images.githubusercontent.com/1955233/66632499-92b7e500-ec43-11e9-8d05-2c44d09dcdda.gif)

 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0)
![vscode-old](https://user-images.githubusercontent.com/1955233/66632520-9b102000-ec43-11e9-8d2f-0352ae3145c3.gif)

**Comment by yamachu** [comment]
`git checkout 13dc6f18ac5988cfdac285dd76c0232b1378b2dc`

works fine

`git checkout 3a626d89a0916c1a478c8fac8b076d6b7dd87ca4`

seems to be broken

**Comment by isidorn** [comment]
@yamachu thanks for bisecting.
3a626d89a0916c1a478c8fac8b076d6b7dd87ca4 was authered by @jrieken thus assigning to him

**Comment by joaomoreno** [comment]
Yup, this is bad:

![Peek 2019-10-11 16-25](https://user-images.githubusercontent.com/22350/66659507-e9252380-ec43-11e9-885c-f8af047ab453.gif)

**Comment by joaomoreno** [comment]
I've merged the fix by @yamachu: thanks a lot for that!

We'll get the fixed Insiders build next Monday morning CET. Sorry for the disturbance everyone!

**Comment by jrieken** [comment]
Thanks everyone!

**Comment by OfficerHalf** [comment]
Still seeing this pretty consistently on
Version: 1.40.0-insider (user setup)
Commit: 3f6ed25939b8ef157a7a41e0dc43b517898d4005
Date: 2019-10-15T05:26:38.861Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by pocesar** [comment]
@jrieken I'm seeing weird behavior on quotes as well. if you type inside `""`, the last quote is removed, like in tsconfig.json: 

```json5
"includes": [
  "./" // << Ctrl + Space here
]
```

becomes

```json
"includes": [
  "./server.ts
]
```

Version: 1.40.0-insider (user setup)
Commit: 3f6ed25939b8ef157a7a41e0dc43b517898d4005
Date: 2019-10-15T05:26:38.861Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by jrieken** [comment]
@pocesar What language is that?

**Comment by jrieken** [comment]
Oh, I see `tsconfig.json`. Yeah, that's very likely because JSON uses a more than bogous word definition

**Comment by jrieken** [comment]
@pocesar I have created https://github.com/microsoft/vscode/issues/82666 and I aiming to push a fix today

**Comment by OfficerHalf** [comment]
What's the *correct* behavior here? If replacing the text is correct, that's fine, but if the current solution is going to be a whack-a-mole fix for each language maybe there's something else that should be done.

**Comment by OfficerHalf** [comment]
Another example. On this one, the comma is removed:
![VSCodeBug2](https://user-images.githubusercontent.com/4851889/67047708-6c3cf280-f0f8-11e9-86d2-ea15c44d7288.gif)

**Comment by jrieken** [comment]
@OfficerHalf We appreciate constructive feedback, if you want to report an issue then please file a new issue, stating the version of vscode, the language, and exact repo steps.

**Comment by OfficerHalf** [comment]
It's not a different issue though, this one just isn't fixed regardless of my preference for replace vs insert. If you'd prefer, I can open a new one though.

**Comment by connor4312** [comment]
Things seem to be working in the latest insiders. I'm no longer able to repro @OfficerHalf's issue--can you confirm that this still occurs on the latest build of insiders?

![](https://memes.peet.io/img/19-10-0e8561ca-f214-47fd-8adb-f0bbad1e61f6.gif)

**Comment by OfficerHalf** [comment]
Yeah I haven't noticed any weird behavior in the past few days. I'll certainly comment here if I see it again.
