### ISSUE TITLE
Completion broken on Insiders

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#82444]
Issue Type: <b>Bug</b>

Hello

The completion is broken on Insiders

Accepting a suggestion deletes some characters after the suggestion

![vscode-bug](https://user-images.githubusercontent.com/15984272/66707798-0262c880-ed47-11e9-9298-a4f78ccc89af.gif)

Reproduces without extensions

Language mode Typescript React 3.6.3

VS Code version: Code - Insiders 1.40.0-insider (72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb, 2019-10-11T05:31:05.355Z)
OS version: Linux x64 4.15.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (1.63GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mattacosta** [comment]
Hopefully this was fixed by d952f6b, which is about 6 commits ahead of the latest insiders, so it should be in Monday's build.

**Comment by rbuckton** [comment]
I noticed this yesterday as well. I also noticed that if you cancel the completion list and then re-trigger the completion list then the completion works fine and does not overwrite the text to the right.

![vscode](https://user-images.githubusercontent.com/3902892/66708005-a70ce800-ecfe-11e9-9059-9bb0d90e12c2.gif)

**Comment by mtxr** [comment]
do we have a fixed build? I've just updated and I'm still facing this annoying bug :rofl:
