### ISSUE TITLE
Typing issue

### ISSUE THREAD

**Issue by ferozsho** [microsoft/vscode#82468]
Issue Type: <b>Bug</b>

hi,
While using "dot" tips command the next text data is replace (cutting) this came since last update

VS Code version: Code - Insiders 1.40.0-insider (72bc289d32ec4f867e73b7f1f2a22f7d614ae2bb, 2019-10-11T05:44:05.506Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.95GB (15.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.802.3
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
ionic3-vs-ionView-snippets|dan|1.0.2
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
tslint|eg2|1.0.44
php-debug|fel|1.13.0
php-intellisense|fel|2.3.13
php-pack|fel|1.0.2
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.1.0
beautify|Hoo|1.5.0
vscode-typescript-tslint-plugin|ms-|1.2.2
vscode-icons|vsc|9.4.0

(1 theme extensions excluded)

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by LeParadoxHD** [comment]
Same here, it's completely annoying.

**Comment by iansan5653** [comment]
I believe this is the same issue as #82466 and if so should be fixed on Monday.

**Comment by iansan5653** [comment]
Duplicate of #82444.

**Comment by varadero** [comment]
Still reproduces when in combination with auto-import feature. New issue created at https://github.com/microsoft/vscode/issues/82491
