### ISSUE TITLE
Blank screen with a reinstalled 1.39.1

### ISSUE THREAD

**Issue by dotnetCarpenter** [microsoft/vscode#82467]
### Error restoring editor grid widget: TypeError: Cannot read property 'indexOf' of undefined

- VSCode Version: 1.39.1 88f15d17dca836346e787762685a40bb5cce75a8
- OS Version: Version 1903 (18362.418)

Steps to Reproduce:

1. Not sure, but I use vscode from both WSL and PowserShell 6.
2. Before it happened I was running vscode from an elevated PowerShell 6.
3. After that - almost blank. I can see the background colors. But no icons and nothing else.
4. The same result when open in WSL as in PowerShell.
5. Possible to get working via `code -n .` to open a new window but not consistently.

Does this issue occur when all extensions are disabled?: Yes

<details><summary>renderer1.log</summary>
<pre><code>
[2019-10-13 19:27:29.196] [renderer1] [error] Error restoring editor grid widget: TypeError: Cannot read property 'indexOf' of undefined (with state: {"serializedGrid":{"root":{"type":"branch","data":[{"type":"leaf","data":{"id":6,"editors":[{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/package.json\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"\\\\home\\\\dotnet\\\\projects\\\\napp\\\\webviewer-core\\\\package.json\",\"_sep\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/package.json\",\"path\":\"/home/dotnet/projects/napp/webviewer-core/package.json\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/CHANGELOG.md\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"\\\\home\\\\dotnet\\\\projects\\\\napp\\\\webviewer-core\\\\CHANGELOG.md\",\"_sep\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/CHANGELOG.md\",\"path\":\"/home/dotnet/projects/napp/webviewer-core/CHANGELOG.md\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/README.md\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"\\\\home\\\\dotnet\\\\projects\\\\napp\\\\webviewer-core\\\\README.md\",\"_sep\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/README.md\",\"path\":\"/home/dotnet/projects/napp/webviewer-core/README.md\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/less/viewer/annotation.less\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"\\\\home\\\\dotnet\\\\projects\\\\napp\\\\webviewer-core\\\\less\\\\viewer\\\\annotation.less\",\"_sep\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/less/viewer/annotation.less\",\"path\":\"/home/dotnet/projects/napp/webviewer-core/less/viewer/annotation.less\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"encoding\":\"utf8\"}"}],"mru":[3,2,1,0]},"size":626},{"type":"leaf","data":{"id":7,"editors":[{"id":"workbench.editors.webviewInput","value":"{\"id\":\"b4b135ab-7982-42cd-9deb-3d6c8e12ce2d\",\"viewType\":\"mainThreadWebview-markdown.preview\",\"title\":\"Preview README.md\",\"options\":{\"enableFindWidget\":true,\"enableScripts\":true,\"localResourceRoots\":[{\"$mid\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features\",\"path\":\"/home/dotnet/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},{\"$mid\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core\",\"path\":\"/home/dotnet/projects/napp/webviewer-core\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"}],\"allowScripts\":true},\"extensionLocation\":{\"$mid\":1,\"path\":\"/home/dotnet/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"extensionId\":\"vscode.markdown-language-features\",\"iconPath\":{\"light\":{\"$mid\":1,\"path\":\"/home/dotnet/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features/media/preview-light.svg\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"dark\":{\"$mid\":1,\"path\":\"/home/dotnet/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features/media/preview-dark.svg\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"}},\"group\":7}"}],"mru":[0]},"size":626}],"size":848},"orientation":1,"width":1252,"height":848},"activeGroup":6,"mostRecentActiveGroups":[6,7]}): Error: Error restoring editor grid widget: TypeError: Cannot read property 'indexOf' of undefined (with state: {"serializedGrid":{"root":{"type":"branch","data":[{"type":"leaf","data":{"id":6,"editors":[{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/package.json\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"\\\\home\\\\dotnet\\\\projects\\\\napp\\\\webviewer-core\\\\package.json\",\"_sep\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/package.json\",\"path\":\"/home/dotnet/projects/napp/webviewer-core/package.json\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/CHANGELOG.md\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"\\\\home\\\\dotnet\\\\projects\\\\napp\\\\webviewer-core\\\\CHANGELOG.md\",\"_sep\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/CHANGELOG.md\",\"path\":\"/home/dotnet/projects/napp/webviewer-core/CHANGELOG.md\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/README.md\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"\\\\home\\\\dotnet\\\\projects\\\\napp\\\\webviewer-core\\\\README.md\",\"_sep\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/README.md\",\"path\":\"/home/dotnet/projects/napp/webviewer-core/README.md\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"encoding\":\"utf8\"}"},{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/less/viewer/annotation.less\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"\\\\home\\\\dotnet\\\\projects\\\\napp\\\\webviewer-core\\\\less\\\\viewer\\\\annotation.less\",\"_sep\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core/less/viewer/annotation.less\",\"path\":\"/home/dotnet/projects/napp/webviewer-core/less/viewer/annotation.less\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"encoding\":\"utf8\"}"}],"mru":[3,2,1,0]},"size":626},{"type":"leaf","data":{"id":7,"editors":[{"id":"workbench.editors.webviewInput","value":"{\"id\":\"b4b135ab-7982-42cd-9deb-3d6c8e12ce2d\",\"viewType\":\"mainThreadWebview-markdown.preview\",\"title\":\"Preview README.md\",\"options\":{\"enableFindWidget\":true,\"enableScripts\":true,\"localResourceRoots\":[{\"$mid\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features\",\"path\":\"/home/dotnet/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},{\"$mid\":1,\"external\":\"vscode-remote://wsl%2Bubuntu/home/dotnet/projects/napp/webviewer-core\",\"path\":\"/home/dotnet/projects/napp/webviewer-core\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"}],\"allowScripts\":true},\"extensionLocation\":{\"$mid\":1,\"path\":\"/home/dotnet/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"extensionId\":\"vscode.markdown-language-features\",\"iconPath\":{\"light\":{\"$mid\":1,\"path\":\"/home/dotnet/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features/media/preview-light.svg\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"},\"dark\":{\"$mid\":1,\"path\":\"/home/dotnet/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features/media/preview-dark.svg\",\"scheme\":\"vscode-remote\",\"authority\":\"wsl+Ubuntu\"}},\"group\":7}"}],"mru":[0]},"size":626}],"size":848},"orientation":1,"width":1252,"height":848},"activeGroup":6,"mostRecentActiveGroups":[6,7]})
    at e.doCreateGridControlWithPreviousState (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5494:182)
    at e.doCreateGridControl (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5493:549)
    at e.createContentArea (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5493:36)
    at e.create (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2671:576)
    at forEach (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5543:408)
    at Array.forEach (<anonymous>)
    at t.Workbench.renderWorkbench (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5543:315)
    at e.invokeFunction (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5540:356)
    at h.invokeFunction (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1504:876)
    at t.Workbench.startup (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5540:94)
    at Q.open (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6084:899)
[2019-10-13 19:27:29.290] [renderer1] [error] Cannot read property 'element' of undefined: TypeError: Cannot read property 'element' of undefined
    at F.doRedrawEditorActive (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5449:684)
    at F.redrawEditorActiveAndDirty (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5448:583)
    at forEachTab (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5440:100)
    at group.editors.forEach (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5447:430)
    at Array.forEach (<anonymous>)
    at F.forEachTab (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5447:372)
    at F.setActive (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5440:70)
    at e.setActive (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5471:335)
    at e.doSetGroupActive (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5489:846)
    at e.doCreateGridControl (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5493:696)
    at e.createContentArea (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5493:36)
    at e.create (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2671:576)
    at forEach (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5543:408)
    at Array.forEach (<anonymous>)
    at t.Workbench.renderWorkbench (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5543:315)
    at e.invokeFunction (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5540:356)
    at h.invokeFunction (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1504:876)
    at t.Workbench.startup (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5540:94)
    at Q.open (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6084:899)
[2019-10-13 19:27:37.057] [renderer1] [error] Cannot read property 'styles' of undefined: TypeError: Cannot read property 'styles' of undefined
    at e.updateStyles (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5492:883)
    at e.onThemeChange (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2656:134)
    at e.onThemeChange (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2671:434)
    at _register.themeService.onThemeChange.e (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2656:80)
    at c.fire (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at P.applyTheme (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4682:610)
    at s.ensureLoaded.then.i (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4681:209)
[2019-10-13 19:27:37.068] [renderer1] [error] Cannot read property 'count' of undefined: TypeError: Cannot read property 'count' of undefined
    at e.get isEmpty [as isEmpty] (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5470:968)
    at e.updateStyles (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5478:526)
    at e.onThemeChange (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2656:134)
    at _register.themeService.onThemeChange.e (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2656:80)
    at c.fire (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at P.applyTheme (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4682:610)
    at s.ensureLoaded.then.i (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4681:209)
[2019-10-13 19:37:20.341] [renderer1] [error] Cannot read property 'state' of undefined: TypeError: Cannot read property 'state' of undefined
    at e.saveState (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5495:835)
    at _register.n.onWillSaveState (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2667:168)
    at c.fire (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at e.close (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2462:311)
    at _register.e.onWillShutdown.e (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6085:464)
    at c.fire (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at _register.e.onWillShutdown.e (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5541:374)
    at c.fire (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at e.handleWillShutdown (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3784:1019)
    at EventEmitter.o.ipcRenderer.on (file:///C:/Users/dotnet/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3784:508)
    at EventEmitter.emit (events.js:182:13)
</code></pre>
</details>

![vscode_blank](https://user-images.githubusercontent.com/43763/66719849-1fee6b80-edf5-11e9-908d-7cfa28047c44.PNG)

**Comment by bl4val** [comment]
Happens only in devcontainers for me.

**Comment by jrieken** [comment]
duplicate of the entered layout issue?

**Comment by isidorn** [comment]
Editor grid widget, assigning to @sbatten 
fyi @joaomoreno

**Comment by joaomoreno** [comment]
@dotnetCarpenter Can you open DevTools, is there any error in there?

**Comment by joaomoreno** [comment]
Oh I see you have a trace! :pray:

**Comment by joaomoreno** [comment]
Seems unrelated to https://github.com/microsoft/vscode/issues/82218. Let's wait for @sbatten

**Comment by bl4val** [comment]
Same error for me:
`log.ts:196   ERR Error restoring editor grid widget: TypeError: Cannot read property 'indexOf' of undefined (with state: {"serializedGrid":{"root":{"type":"branch","data":[{"type":"leaf","data":{"id":0,"editors":[{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-remote://dev-container%2B633a5c6…/code/README.md\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"\\\\code\\\\README.md\",\"_sep\":1,\"external\":\"vscode-remote://dev-container%2B633a5c6…/code/README.md\",\"path\":\"/code/README.md\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"},\"encoding\":\"utf8\"}"}],"mru":[0]},"size":764},{"type":"leaf","data":{"id":1,"editors":[{"id":"workbench.editors.webviewInput","value":"{\"id\":\"81bdadfb-4327-465a-baba-89aadeb558ce\",\"viewType\":\"mainThreadWebview-markdown.preview\",\"title\":\"Preview README.md\",\"options\":{\"enableFindWidget\":true,\"enableScripts\":true,\"localResourceRoots\":[{\"$mid\":1,\"external\":\"vscode-remote://dev-container%2B633a5c6…/root/.vsco…d17dca8…/extensions/markdown-language-features\",\"path\":\"/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"},{\"$mid\":1,\"external\":\"vscode-remote://dev-container%2B633a5c6…/code\",\"path\":\"/code\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"}],\"allowScripts\":true},\"extensionLocation\":{\"$mid\":1,\"path\":\"/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"},\"extensionId\":\"vscode.markdown-language-features\",\"iconPath\":{\"light\":{\"$mid\":1,\"path\":\"/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features/media/preview-light.svg\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"},\"dark\":{\"$mid\":1,\"path\":\"/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features/media/preview-dark.svg\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"}},\"group\":1}"}],"mru":[0]},"size":763}],"size":623},"orientation":1,"width":1527,"height":623},"activeGroup":0,"mostRecentActiveGroups":[0,1]}): Error: Error restoring editor grid widget: TypeError: Cannot read property 'indexOf' of undefined (with state: {"serializedGrid":{"root":{"type":"branch","data":[{"type":"leaf","data":{"id":0,"editors":[{"id":"workbench.editors.files.fileEditorInput","value":"{\"resource\":\"vscode-remote://dev-container%2B633a5c6…/code/README.md\",\"resourceJSON\":{\"$mid\":1,\"fsPath\":\"\\\\code\\\\README.md\",\"_sep\":1,\"external\":\"vscode-remote://dev-container%2B633a5c6…/code/README.md\",\"path\":\"/code/README.md\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"},\"encoding\":\"utf8\"}"}],"mru":[0]},"size":764},{"type":"leaf","data":{"id":1,"editors":[{"id":"workbench.editors.webviewInput","value":"{\"id\":\"81bdadfb-4327-465a-baba-89aadeb558ce\",\"viewType\":\"mainThreadWebview-markdown.preview\",\"title\":\"Preview README.md\",\"options\":{\"enableFindWidget\":true,\"enableScripts\":true,\"localResourceRoots\":[{\"$mid\":1,\"external\":\"vscode-remote://dev-container%2B633a5c6…/root/.vsco…d17dca8…/extensions/markdown-language-features\",\"path\":\"/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"},{\"$mid\":1,\"external\":\"vscode-remote://dev-container%2B633a5c6…/code\",\"path\":\"/code\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"}],\"allowScripts\":true},\"extensionLocation\":{\"$mid\":1,\"path\":\"/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"},\"extensionId\":\"vscode.markdown-language-features\",\"iconPath\":{\"light\":{\"$mid\":1,\"path\":\"/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features/media/preview-light.svg\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"},\"dark\":{\"$mid\":1,\"path\":\"/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/extensions/markdown-language-features/media/preview-dark.svg\",\"scheme\":\"vscode-remote\",\"authority\":\"dev-container+633a5c636f64655c6e6f6973652d6265\"}},\"group\":1}"}],"mru":[0]},"size":763}],"size":623},"orientation":1,"width":1527,"height":623},"activeGroup":0,"mostRecentActiveGroups":[0,1]})
    at e.doCreateGridControlWithPreviousState (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5494:182)
    at e.doCreateGridControl (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5493:549)
    at e.createContentArea (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5493:36)
    at e.create (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2671:576)
    at forEach (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5543:408)
    at Array.forEach (<anonymous>)
    at t.Workbench.renderWorkbench (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5543:315)
    at e.invokeFunction (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5540:356)
    at h.invokeFunction (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1504:876)
    at t.Workbench.startup (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5540:94)
    at Q.open (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6084:899)
log.ts:196   ERR Cannot read property 'element' of undefined: TypeError: Cannot read property 'element' of undefined
    at F.doRedrawEditorActive (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5449:428)
    at F.redrawEditorActiveAndDirty (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5448:583)
    at forEachTab (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5440:100)
    at group.editors.forEach (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5447:430)
    at Array.forEach (<anonymous>)
    at F.forEachTab (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5447:372)
    at F.setActive (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5440:70)
    at e.setActive (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5471:335)
    at e.doSetGroupActive (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5489:846)
    at e.doCreateGridControl (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5493:696)
    at e.createContentArea (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5493:36)
    at e.create (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2671:576)
    at forEach (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5543:408)
    at Array.forEach (<anonymous>)
    at t.Workbench.renderWorkbench (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5543:315)
    at e.invokeFunction (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5540:356)
    at h.invokeFunction (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1504:876)
    at t.Workbench.startup (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5540:94)
    at Q.open (file:///C:/Users/otur-gaming/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6084:899)`

**Comment by sbatten** [comment]
I can repro with that trace. In both cases, this happens when a markdown preview is open and the stack I see when reproducing shows errors when restoring the webview. Still investigating further.

**Comment by sbatten** [comment]
The real error is coming from https://github.com/microsoft/vscode/blob/7e31d9754fc093744be8b4d2fea9656fae28989b/src/vs/base/common/network.ts#L96. When the editors are being restored, the first time this function is called, the host is not yet defined and thus this is failing. Previously, we just passed this undefined value along but now we are operating on it. Simply adding `host && host.indexOf...` to conditional resolves the issue for me. @aeschli

**Comment by sbatten** [comment]
I pushed the quick fix, but maybe we should look into delaying the editor restoration until the host information is available.

**Comment by sbatten** [comment]
To verify:
1) Open a folder in WSL with a markdown file.
2) Open a preview of the markdown file to the side.
3) Reload the window.

Ensure that reload is successful and you don't have a blank window.

**Comment by Zizaco** [comment]
Is there any cache / workspace files that I can erase to get vscode to run while this is still an issue?
