### ISSUE TITLE
vs code won't size right on multiple monitors

### ISSUE THREAD

**Issue by robinsh** [microsoft/vscode#84164]
I have 3 monitors. a Surface Book 2 on the bottom, with 2 monitors above the book (left and right). The external monitors are 1920x1080. If I open a file on the Surface monitor, it will fit. I can resize it to be half the height of the monitor, but then when I try to drag it onto the 1920x1080 monitor on the top left, the window is suddenly bigger, and won't fit on the 1920x1080 monitor. At least an inch or two bleeds over to the Surface Book monitor below the 1920x1080 monitor, and it's tiny (because of the different resolution) and I can't read it. It won't let me make the VS Code screen small enough to fit on the 1920x1080 monitor. It ALWAYS has a bit that shows on the Surface Book monitor. 

I have had problems with this before, but not this bad. Before, when I opened a markdown file, it would center the window on the three monitors, making it impossible to use VS Code unless I dragged it to one of the monitors first. It would let me do this, it was just a pain in the a** to have to do it EVERY SINGLE TIME I opened a markdown file. 

This changed with the most recent update. Now it's almost unusable, and I get no benefit from having 3 monitors.

**Comment by robinsh** [comment]
Would it help if I begged you to fix this instead of closing it ?

**Comment by sana-ajani** [comment]
Similar feedback on twitter: https://twitter.com/RobinDotNet/status/1192558692073259008

**Comment by sbatten** [comment]
Investigation shows 2 issues:
1) We set the minimum window size to something more usable this iteration: 600px height.

2) We upgraded to electron 6 which seems to introduced a regression https://github.com/electron/electron/issues/20683 that is causing issues in multi monitor setups with different resolutions. In the surface book example, the scaling of the primary monitor is 200% and the external monitor is 100%. Due to the upstream issue, this converts the minimum window height on the external monitor to 1200px (2 x 600px) which is unfortunately just over the standard 1080p vertical height.

That being said, a simple change to 400px for minimum height will at least allow 1080p attached monitor users to work on their screens with a minimum window height of 800px until the upstream issue is addressed.

**Comment by robinsh** [comment]
I'd be totally thrilled if this fixed it. Happy to test if you want.

**Comment by Peter-Moody** [comment]
I have the same problem. I have 1 monitor a wide screen (3440 X 1440) connected via a docking station (plugable USB-C 4K) to a Dell XPS 15 9560 laptop with 4k monitor (3840 x 2160).
VS Code appears ok when launched but as soon as the height is adjusted it extends beyond the bottom of the monitor. Works okay on laptop screen. But when dragged to wide screen it expands in the same way.

**Comment by Peter-Moody** [comment]
Installed VS Code September 2019 and all is good.

**Comment by sbatten** [comment]
Updating the minimum dimensions to 600 by 270 as the planned fix for now. This means that @robinsh would experience 1200 by 540 as a minimum width on the external monitor while the upstream bug still exists. While still larger than desired, it allows code to be used within that monitor.

Still looking into the upstream issue.

**Comment by toketeeman** [comment]
I have exactly the same multi-monitor problem as @Peter-Moody, occurring the pas t two days since the October update. My work-around is to bring up a VS code window (which is over-sized and cannot be re-sized, behaving badly), then enter the command:

> code --force-device-scale-factor

which brings up a fully-controllable properly-sized VS Code window. I then close the original bad window. VS Code operates normally from this point on. However when you do a restart, the UI window problem returns, so this workaround has to be performed on each start-up.

Platform: Dell Latitude 7490. Windows 10.

Note: I also have an 8-year old Dell PC and a new Lenovo P-52, both running Windows 10 on multiple monitors. Both do NOT have this problem!

**Comment by thorjasten** [comment]
I have the same problem on a Windos laptop with an extra screen connected, VS Code version 1.40.0. I use different scaling settings on both screens: 250% on a 3200x1800 laptop screen and 100% on a 1920x1200 external one. 

It is not possible to seamlessly drag the VS Code window between screens, since it does not adjust to the new screen scaling early enough. The window blows up to several times the screen size when it gets dragged to the external monitor with a lower zoom setting. The only way to get it back to a usable size is to use the Windows snap assist function to adjust it to full screen.

Furthermore, when snapping the VS Code window to the side of the external screen, a part of the window still remains visible the other screen. Click and dragging of the window size is not working in this case, so it's can't be adjusted to the desired size.

**Comment by jlarcombe** [comment]
Would it be possible to expose this minimum size as an option? For those of us who do not have the  activity bar or status bar visible, it's really useful to be able to have tiny editors.

**Comment by Tinusf** [comment]
This is also the case for the width. I cannot resize my vscode windows to less than 1200px wide on my second monitor.

**Comment by toketeeman** [comment]
Yes, indeed. I went back to 1.39.2 and set my updating to "manual". All works fine.

**Comment by toketeeman** [comment]
Exactly. Meanwhile I reverted back to 1.39.2 and set my updating to "manual". VS Code works fine now.

- Dwight Spencer

**Comment by davidnero** [comment]
I'm seeing a similar issue. On my secondary monitor, the minimum width is set too wide (probably 1200px). The minim height is fine.

**Comment by sbatten** [comment]
Still working on the upstream issue which is preventing the width from coming down to 600px

**Comment by toketeeman** [comment]
I solved the problem simply be reverting back to 1.39.2 and setting the update policy to "manual".

**Comment by toketeeman** [comment]
I solved the problem simply by reverting back to version 1.39.2 and setting the updating policy to "manual".

**Comment by mrmod** [comment]
Piling on: seeing the same issue (finally got annoyed) 

@sbatten If there's an issue upstream that prevents this issue from closing then this issue is open. Peg a link to the proper tracking issue if there is one otherwise. 
```
VSCode: 1.40.1 SHA 8795a98
Electron 6.1.2
Chrome 76.0.3809.146
V8: 7.6.303.31-electron.0
OS: NT 10.0.17763
```

**Comment by deepak1556** [comment]
This has been addressed in https://github.com/electron/electron/pull/21100 and the fix is already pulled into our latest insiders https://code.visualstudio.com/insiders, please give it a try. We will also push the fix into our stable release next week.

**Comment by Petezah** [comment]
I have the latest insiders build and this is still an issue--the window extends a quarter-inch over the edge of the monitor on all sides.

Version: 1.41.0-insider (user setup)
Commit: d386b49dee6267238389c0a616af2be89726a4e3
Date: 2019-12-06T12:19:08.526Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by toketeeman** [comment]
Thank you for the heads-up. I have reverted to 1.39.2 with a system configuration nearly identical to yours, and VS Code is working well.

**Comment by sbatten** [comment]
@Petezah can you detail your setup and repro steps? (how many monitors, resolution, scaling settings, primary monitor)

**Comment by toketeeman** [comment]
I have two 22-inch 2240L Dell monitors 1920x1080x60hz, default Windows 10 Pro display settings, off of a Dell Latitude 7490 laptop. Primary monitor is the laptop's own, but I run the VS Code always on one of the larger monitors. My VS Code configuration is very default vanilla. Sorry that I do not have more.

**Comment by Petezah** [comment]
@sbatten I have two monitors with the following configuration:
Monitor 1 (primary):
Laptop monitor on Dell XPS 9570
3840x2160, scaling at 250%

Monitor 2:
Asus VX238
1920x1080, scaling at 100%

Repro steps:
* Launch VS Code
* Drag to second monitor (Asus)
* Maximize

Expected: The window sizes to the dimension of the monitor
Actual: The window bleeds over about 1/4in on all sides.

**Comment by Tinusf** [comment]
> 
> 
> @sbatten I have two monitors with the following configuration:
> Monitor 1 (primary):
> Laptop monitor on Dell XPS 9570
> 3840x2160, scaling at 250%
> 
> Monitor 2:
> Asus VX238
> 1920x1080, scaling at 100%
> 
> Repro steps:
> 
>     * Launch VS Code
> 
>     * Drag to second monitor (Asus)
> 
>     * Maximize
> 
> 
> Expected: The window sizes to the dimension of the monitor
> Actual: The window bleeds over about 1/4in on all sides.

Exactly the same for me, running version 1.40.2

**Comment by deepak1556** [comment]
Thanks for the details, I can confirm this is https://github.com/microsoft/vscode/issues/85592 , please follow along that issue for updates.
