### ISSUE TITLE
Terminal font height incorrect since last update

### ISSUE THREAD

**Issue by chris-findlay** [microsoft/vscode#84432]
Issue Type: <b>Bug</b>

Since the last VSCode update my terminal font is missing the bottom of its decenders, and altering line-height isn't helping - that just puts space between the lines.

The same font is still working fine in the editors.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
tt-processor|ais|0.8.0
vscode-apollo|apo|1.12.0
npm-intellisense|chr|1.3.0
vscode-postgres|cko|1.1.11
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.2
EditorConfig|Edi|0.14.2
prettier-vscode|esb|2.3.0
terraform|mau|1.4.0
rainbow-csv|mec|1.3.1
vscode-docker|ms-|0.8.2
mssql|ms-|1.7.0
csharp|ms-|1.21.6
vscode-typescript-next|ms-|3.8.20191105
debugger-for-chrome|msj|4.12.1
vscode-versionlens|pfl|0.24.0
vscode-coverage-gutters|rya|2.4.2
vscode-todo-highlight|way|1.0.4
t4-support|zbe|0.4.3

</details>

Works fine in the editor: 
![image](https://user-images.githubusercontent.com/40373773/68552201-3aaa1380-0479-11ea-8ada-c4d8f41c75a3.png)

But not in the terminal window:
![image](https://user-images.githubusercontent.com/40373773/68552215-56151e80-0479-11ea-82c5-391a2544044c.png)

**Comment by f-aa** [comment]
This happens to me as well. My terminal is illegible. VS Code v1.40 using the Proggy Square (Slashed Zero) font available here: https://proggyfonts.net/download/

![image](https://user-images.githubusercontent.com/12102130/68777459-4e7b8400-05f7-11ea-8429-ee02dad692d2.png)

**Comment by marvinside** [comment]
Since last VS-Code update, the Powerline Arrow to the Right renders not tall enough.
It seems 2 Pixels to small.

Font Used in the Screenshot: [Fira Mono for Powerline](https://github.com/powerline/fonts)
Ialso tested with [Fira Code](https://github.com/tonsky/FiraCode) and [Roboto Mono for Powerline](https://github.com/powerline/fonts). The Roboto seems to be only one Pixel to small.

![Terminal Screenshot](https://user-images.githubusercontent.com/3470697/68859295-3be07800-06e7-11ea-91a0-0a3b269f4bc1.png)

**Comment by adamsandwich** [comment]
<details>
<summary>environment</summary>

版本: 1.40.1 (user setup)
提交: 8795a9889db74563ddd43eb0a897a2384129a619   
日期: 2019-11-13T16:49:35.976Z   
Electron: 6.1.2   
Chrome: 76.0.3809.146   
Node.js: 12.4.0   
V8: 7.6.303.31-electron.0   
OS: Windows_NT x64 10.0.18362   
</details>

Same issue, my font [Sarasa-Gothic](https://github.com/be5invis/Sarasa-Gothic), It seems that the font has been moved up a few pixels
![Snipaste_2019-11-14_22-08-54](https://user-images.githubusercontent.com/19149439/68864041-69e7ab80-072b-11ea-9c80-3b3d1e1bfc6a.jpg)

**Comment by joelamltc** [comment]
I changed the terminal renderer type to dom, seems things going well but canvas is not correct.

Canvas:
<img width="1151" alt="Screenshot 2019-11-18 at 13 03 35" src="https://user-images.githubusercontent.com/13143636/69025935-e74d3d80-0a03-11ea-92bc-defeaed473cb.png">

DOM:
<img width="1151" alt="Screenshot 2019-11-18 at 13 03 17" src="https://user-images.githubusercontent.com/13143636/69025942-eddbb500-0a03-11ea-9b08-79c2b8ef597c.png">

**Comment by f-aa** [comment]
Changing render type to DOM seems to have corrected the line height for me as well. The text is however slightly blurry compared to using canvas as a render type.

![image](https://user-images.githubusercontent.com/12102130/69064950-895d2d80-09e4-11ea-8200-41e726dcf01a.png)

**Comment by chris-findlay** [comment]
Likewise for me - Canvas = crisp but wrong; Dom = bluryish but right.  I'm stuck with Canvas so I don't get a headache, and guessing decenders since they aren't visible.

**Comment by chris-findlay** [comment]
Now I look at it tho, the editor is also similarly blury, so being able to use the crisper text output there too would be nice.

**Comment by Tyriar** [comment]
This appears to be an Electron/Chrome bug possibly related to recent changes in textBaseline (https://crbug.com/890515, https://crbug.com/607053). The following screenshots were produced on Windows 10 by running the xterm.js demo after installing [Proggy Square (Slashed Zero) ttf](https://proggyfonts.net/download/) and setting `fontFamily` in the demo to `ProggySquareTTSZ`.

Electron 6 (Chromium 76, taken in VS Code):

![image](https://user-images.githubusercontent.com/2193314/69158702-b28cc500-0a9b-11ea-85c4-b7eea71351d7.png)

Chrome 78.0.3904.108:

![image](https://user-images.githubusercontent.com/2193314/69158864-ea940800-0a9b-11ea-8ecc-98b309c4b457.png)

Edge (Chromium) 80.0.328.4:

![image](https://user-images.githubusercontent.com/2193314/69158735-be788700-0a9b-11ea-8ccc-57251c932de6.png)

---

Electron 4 (Chromium 69, taken in VS Code):

![image](https://user-images.githubusercontent.com/2193314/69159631-16fc5400-0a9d-11ea-9cb6-9942b74b0f10.png)

Firefox Nightly 72.0a1:

![image](https://user-images.githubusercontent.com/2193314/69158474-5a55c300-0a9b-11ea-9820-f3258dd7422e.png)

Edge (Old) 44.19013.1.0:

![image](https://user-images.githubusercontent.com/2193314/69159014-1e6f2d80-0a9c-11ea-94ae-13ff0f138a8c.png)

**Comment by Tyriar** [comment]
Also happens on macOS:

Edge 80.0.320.3:

<img width="204" alt="Screen Shot 2019-11-19 at 7 23 43 AM" src="https://user-images.githubusercontent.com/2193314/69159947-8c682480-0a9d-11ea-9776-00950232ab9a.png">

Firefox 70.0.1:

<img width="207" alt="Screen Shot 2019-11-19 at 7 25 56 AM" src="https://user-images.githubusercontent.com/2193314/69160112-da7d2800-0a9d-11ea-8d60-5597acb10ec5.png">

**Comment by Tyriar** [comment]
`fillText` and `textBaseline` are used here: https://github.com/xtermjs/xterm.js/blob/70babeacb62fe05264d64324ca1f4436997efa1b/src/browser/renderer/atlas/DynamicCharAtlas.ts#L254-L263

**Comment by Tyriar** [comment]
Reported upstream https://bugs.chromium.org/p/chromium/issues/detail?id=1026254

**Comment by chris-findlay** [comment]
I recommend we all go there and star it so it gets noticed more.

**Comment by Tyriar** [comment]
Minimal repro case:

```html
<html>
<body>
<canvas width="200" height="200"></canvas>
<script>
const c = document.querySelector('canvas');
const ctx = c.getContext('2d');
// Draw a guide line at y where text is drawn
ctx.beginPath();
ctx.moveTo(0, 100);
ctx.lineTo(200, 100);
ctx.stroke();
// Draw the text
ctx.textBaseline = 'middle';
ctx.font = '30px Arial';
ctx.fillText('Works', 10, 100);
ctx.font = '30px ProggySquareTTSZ';
ctx.fillText('Doesn\'t work', 110, 100);
</script>
</body>
</html>
```

Chromium

![image](https://user-images.githubusercontent.com/2193314/69251608-82f6bf00-0b66-11ea-8ed8-68f84c0b668e.png)

Firefox

![image](https://user-images.githubusercontent.com/2193314/69251679-a1f55100-0b66-11ea-8ad3-376d19571eda.png)

**Comment by chris-findlay** [comment]
Please post that to the upstream bug.

**Comment by Tyriar** [comment]
Already did

**Comment by chris-findlay** [comment]
The latest VSCode has a new option for webGL-based terminals which doesn't have this canvas issue with my font any more.

**Comment by heaths** [comment]
Tried the experimental webgl renderer. It's...more interesting?

![image](https://user-images.githubusercontent.com/1532486/70749758-da112f00-1ce1-11ea-9c41-983330b1c9c0.png)

**Comment by chris-findlay** [comment]
I also ran my custom font thru http://fontstore.baidu.com/static/editor/index-en.html
I uploaded it, went to Settings>Metrics, and clicked `Calc` and some numbers changed.
I then exported it back to TTF, and installed it.
Canvas-based render still looked the same but the webGL one looks fine for me.  I didn't know about it to try the unedited font there first.

**Comment by ababak** [comment]
The text rendering is broken when switching to the new "experimentalWebgl":
![image](https://user-images.githubusercontent.com/11334363/70790341-8e23c000-1d9d-11ea-853e-dc4d6fdae063.png)

Switching the new setting off:
![image](https://user-images.githubusercontent.com/11334363/70790435-bca19b00-1d9d-11ea-965d-f87b1dab81a8.png)

**Comment by ZhangTianrong** [comment]
I tried DOM which mitigate the problem a lot but I find the height not exactly correct in that case either. I still see the cornor of the rectangular block below that of the right-pointing triangular angle in all 3 f onts I have tried.

**Comment by tigerinus** [comment]
Yes, `experimentalWebgl` breaks the rendering.
![image](https://user-images.githubusercontent.com/7172560/78892457-f8264a80-7a9b-11ea-94dd-1a772ac83330.png)

**Comment by Tyriar** [comment]
Tentatively assigning to May for debt week if there's time to see if there's a workaround.

**Comment by Tyriar** [comment]
Moving the webgl part to https://github.com/microsoft/vscode/issues/95813. The textBaseline middle broken thing (this issue) is blocked on Chromium, but they say the font metrics have problems?

**Comment by hems** [comment]
Same happening here, "y" is being cut, looks like an "u" :(

![image](https://user-images.githubusercontent.com/27327/93766174-eed60800-fc0d-11ea-9d05-157897fa2ec0.png)

I tried adding `"terminal.integrated.rendererType": "experimentalWebgl",` but did not fix anything, is it supposed to fix that issue?

I'm using `ProggyCleanTTSZ`

**Comment by veleek** [comment]
I'm assuming this is the same thing that's causing my problem but adding details here as well.

VSCode Version: 
OS Version: Windows 10

![image](https://user-images.githubusercontent.com/1055021/99768788-3d8f0980-2aba-11eb-9428-28b087dc55c2.png)
Extra height and some graphical artifacts on some of the powerline glyphs with the `canvas` renderer.

![image](https://user-images.githubusercontent.com/1055021/99768966-821aa500-2aba-11eb-887f-a5afb1bfd3f1.png)
Slightly different behavior but same basic problem when using the dom renderer.

**Comment by hems** [comment]
Please have a look on this issue i created documenting how i finally fixed my font rendering problems on the terminal:

https://github.com/microsoft/vscode/issues/107942#issuecomment-727905690

**Comment by jefflundberg** [comment]
MacOS
VSCode 1.55.2
FiraCode Nerd Font
zsh with ohmyzsh powerlevel10k theme

auto (seems to switch between canvas and experimentalWebgl)

experimentalWebgl
![image](https://user-images.githubusercontent.com/62454/114712468-22899400-9cfe-11eb-96d0-956b31a6d4e8.png)

dom
![image](https://user-images.githubusercontent.com/62454/114712517-31704680-9cfe-11eb-818d-8a241f90bae5.png)

canvas 👈. this one looks good
![image](https://user-images.githubusercontent.com/62454/114712620-48af3400-9cfe-11eb-8224-a2fa20959444.png)

**Comment by hologerry** [comment]
> MacOS
> VSCode 1.55.2
> FiraCode Nerd Font
> zsh with ohmyzsh powerlevel10k theme
> 
> auto (seems to switch between canvas and experimentalWebgl)
> 
> experimentalWebgl
> ![image](https://user-images.githubusercontent.com/62454/114712468-22899400-9cfe-11eb-96d0-956b31a6d4e8.png)
> 
> dom
> ![image](https://user-images.githubusercontent.com/62454/114712517-31704680-9cfe-11eb-818d-8a241f90bae5.png)
> 
> canvas 👈. this one looks good
> ![image](https://user-images.githubusercontent.com/62454/114712620-48af3400-9cfe-11eb-8224-a2fa20959444.png)

<img width="86" alt="image" src="https://user-images.githubusercontent.com/11660168/114725720-50f38780-9d6f-11eb-8a33-2b83792c3a23.png">
On my machine, the icon is still been cropped.

**Comment by veleek** [comment]
> canvas 👈. this one looks good
> ![image](https://user-images.githubusercontent.com/62454/114712620-48af3400-9cfe-11eb-8224-a2fa20959444.png)

Even this one still isn't perfect.  The height of the arrow glyphs is too short.  They should be the same height as the glyphs in the `dom` example

**Comment by Livven** [comment]
This seems to have been fixed with 1.56 (or 1.55?) for me, using the webgl renderer on Windows.

![image](https://user-images.githubusercontent.com/1537947/119149903-3be4d500-ba4e-11eb-914d-148c1ceee2b0.png)

**Comment by Tyriar** [comment]
Yep vertical alignment was fixed up in that issue

/duplicate

**Comment by unkindypie** [comment]
![image](https://user-images.githubusercontent.com/34601252/119180318-d22df080-ba78-11eb-871b-bd1964147e64.png)
still have this problem

**Comment by Tyriar** [comment]
@unkindypie do you set the terminal line height setting

**Comment by unkindypie** [comment]
@Tyriar `"terminal.integrated.lineHeight": 1`

**Comment by hologerry** [comment]
<img width="110" alt="image" src="https://user-images.githubusercontent.com/11660168/119185707-aa0ab580-baa9-11eb-8144-828fd20916a0.png">
The apple icon from powerline10k theme in zsh is still not aligned, it is cutted on the left.

In the iTerm2 app, it looks good:
<img width="138" alt="image" src="https://user-images.githubusercontent.com/11660168/119185851-e63e1600-baa9-11eb-833a-da68f4b19871.png">
