### ISSUE TITLE
[json] VSCode JSON language returns wrong hover range

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8498]
This has been annoying me for a while now

* open default settings
* hover over a key
* observe the hover is rendered over the value because that is the hover range returned by the hover provider

![image](https://cloud.githubusercontent.com/assets/5047891/16450623/532a87ae-3dfe-11e6-8dd5-73e7eba4f851.png)

**Comment by aeschli** [comment]
fixed by Microsoft/vscode-json-languageservice@2bcd31d0a98b23ab9e29cab9df770b2638050caa

**Comment by jrieken** [comment]
@aeschli I still see funny stuff. Sometimes the hover selects key and value, sometimes only the value or key. Also highlight values that span multiple lines isn't very pretty. See screen short from our `package.json` file:

![aug-31-2016 14-52-55](https://cloud.githubusercontent.com/assets/1794099/18129343/a973a7d6-6f8a-11e6-8a39-c0c2777ab9a0.gif)

**Comment by aeschli** [comment]
It now selects the full property (key and value). In case of dependencies it's the full object. That's as expected. 
But that it only selects the value is a bug.

**Comment by aeschli** [comment]
The reason for the inconsistency is that some of the hovers are originating from schemas, others from the JSON extension (for package dependencies). The later doesn't have an AST and only knows about the current node.
I changed the schema driven hovers to also only highlight the current literal to be more consistent. In case of objects and arrays the hover still span over lines.

@jrieken If you don't like this solution or find other issue, please open new issues.
