### ISSUE TITLE
Why prompt for a remote to publish to when there is only one?!

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#85505]
- VSCode Version: 1.40.1
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Create a branch o a Git repo with only one remote `origin`.
2. Makes some changes to it, commit them.
3. Press the up arrow/cloud icon at the bottom to push the branch

This used to not prompt to select a remote when you only had one remote (`origin`).  It is now prompting in this case which is EXTREMELY ANNOYING.  I've probably gone to Bitbucket to create a PR about a dozen times now, only to not find my branch there.  That's because pressing the `Publish Changes` icon didn't actually publish my changes.  It pops a user prompt that I didn't see. Given that icon is at the bottom of my full-screen VSCode on a 24" monitor, it is easy to miss that prompt popping at the top of the screen.  And anyway, there is no reason to prompt in this case. 

Is there a setting to disable this behavior?

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Already fixed in `master`. Uff. This angered a lot of people.

**Comment by rkeithhill** [comment]
Sorry for piling on but really glad to hear it has been fixed.  :-)

**Comment by ashercoren** [comment]
Is this available in the latest version? It's still happening to me?
