### ISSUE TITLE
Open Folder Modal Windows on 4k screen

### ISSUE THREAD

**Issue by devsetgo** [microsoft/vscode#85898]
**VS Code Version**
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19033

**Steps to Reproduce:**
Using a 4k display (mine is an XPS 15 7590 with OLED screen with 1080p extra monitor. This could be a windows problem, but I am not seeing it happen on other apps. Closest I have seen is when using Windows Explorer there is an awkward transition between 4k screen and normal screen.

Also notice VS Code is not correctly showing on non-4k screen. See image 4 below. The bottom of vs code is under taskbar. Changing task bar to top also doesn't seem to fit properly.

1. File > Open Folder
2. Open Folder Modal is really large on 1080p screen, but normal on 4k screen.

**Screenshots**

**4k Screen** ![img_1](https://user-images.githubusercontent.com/16019894/69921475-e08ce480-145f-11ea-9c75-a06dc93ca60f.PNG)
**4k Open Modal window** ![img_2](https://user-images.githubusercontent.com/16019894/69921476-e08ce480-145f-11ea-8e73-a7b98a6f63a5.PNG)
**1080p Modal window dragged over** ![img_3_1080screen](https://user-images.githubusercontent.com/16019894/69921477-e08ce480-145f-11ea-8553-f1f1c094db11.PNG)
**1080p VS Code open modal on 1080 screen** ![img_4_1080screen](https://user-images.githubusercontent.com/16019894/69921478-e08ce480-145f-11ea-85fd-8b2d5fbc7098.PNG)
**Windows Version** ![img_5](https://user-images.githubusercontent.com/16019894/69922468-89404180-146a-11ea-9dee-66fe23a5ebe9.PNG)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by deepak1556** [comment]
Can you confirm if you see the same issue with `1.40.1` https://az764295.vo.msecnd.net/stable/8795a9889db74563ddd43eb0a897a2384129a619/VSCode-win32-x64-1.40.1.zip ? Thanks!

**Comment by devsetgo** [comment]
I tried on 1.40.2 and see the issue. I also still see the status bar extending past the Windows task bar.

![vs_code_1_40_2](https://user-images.githubusercontent.com/16019894/70672651-e186f880-1c4d-11ea-9dfe-abb1154da55d.PNG)
![vs_code_1_40_2-2](https://user-images.githubusercontent.com/16019894/70672652-e186f880-1c4d-11ea-92b1-77bbe4dd7105.PNG)

**Comment by deepak1556** [comment]
@devsetgo no problem, but can you try `1.40.1` mentioned above https://github.com/microsoft/vscode/issues/85898#issuecomment-562813076 , want to confirm if its due to an electron update. Also how does it look with `"window.titleBarStyle": "native"` ?

This is most likely https://github.com/microsoft/vscode/issues/85592

**Comment by devsetgo** [comment]
Open file dialog is still supersized in 1.40.1. 

Adding "window.titleBarStyle": "native" fixes the behind the taskbar issue in both 1.40.1 ,1.40.2, and 1.41.0 (just upgraded).

**Comment by devsetgo** [comment]
@deepak1556 is there any other tests you want me to try?

**Comment by devsetgo** [comment]
Anything I can try, the issue is still there.

**Comment by Eltyo** [comment]
I think I'm having the same issue.

I have a primary 1080p monitor scaled at 100% and a secondary 4k monitor scaled at 150%. When I open a file/folder in vscode on the secondary monitory, the file explorer assumes the scaling of the primary monitory which results in a tiny and hard to read file explorer.

**Comment by yume-chan** [comment]
Upstream issue: electron/electron#26622

**Comment by matthewtquinn1** [comment]
This is still an issue now with:
- Version: 1.56.0.
- Electron: 12.0.4

I'm running Windows 10 x64. 

I've been seeing this issue now for almost a year: Happens on different machines, and I've fully reset these machines.

![image](https://user-images.githubusercontent.com/59854425/117656747-ffd18a80-b198-11eb-923d-abf8c3ffab12.png)


is there a fix for this?

**Comment by warpdesign** [comment]
Any update? It seems the bug is in [Electron](https://github.com/electron/electron/issues/26622): is anyone working on it?

**Comment by kwinz** [comment]
This is still not fixed. There are 10 different issues and duplicates that have all been closed by a bot after not being addressed for a few years.

Open File dialog is still opened tiny (or huge) if you have a multi monitor setup with different DPI. That's kind of a basic functionality for an editor, and multi monitor setups are prevalent for programmers. It breaks essential dialogs such as `Open File` and `Save As`. I am not sure why you are not pouring resources into this?

**Comment by devsetgo** [comment]
> This is still not fixed. There are 10 different issues and duplicates that have all been closed by a bot after not being addressed for a few years.
> 
> Open File dialog is still opened tiny (or huge) if you have a multi monitor setup with different DPI. That's kind of a basic functionality for an editor, and multi monitor setups are prevalent for programmers. It breaks essential dialogs such as `Open File` and `Save As`. I am not sure why you are not pouring resources into this?

I opened this originally and it was fixed for my issue.

**Comment by don-eng** [comment]
Definitely NOT fixed for me.
works  properly on the 4k 17"  but not on the 4k 32"

Thanks

Donald

**Comment by HoLengZai** [comment]
Any update on that issue please?

**Comment by redfrogred** [comment]
I am having same issue.  (I run dual monitors, one 4k, one 1080p. The File Picker opens so small it is very difficult to use.)

**Comment by szekelyferencz** [comment]
I'm having the same issue on HP Elitbook 830 G6 and an external LG "29 full hd monitor.

**Comment by kwinz** [comment]
The issue finally looks fixed 🥳. I am using `VSC 1.68.1` with `Electron 17.4.7`, `Windows_NT x64 10.0.19044`

**Comment by kwinz** [comment]
I just deleted a comment where I erroneously claimed that it was fixed for me but it's actually not.

**Comment by kwinz** [comment]
I just deleted a comment where I had erroneously claimed that it was fixed for me but it's actually not.

**Comment by kwinz** [comment]
Ok, I just updated to Windows 11 Version 21H2 (Build 22000.978) and now the file dialogs scale properly with VSC. This time for real. Still not a fix if you want to stay on Windows 10.

**Comment by aont** [comment]
I found that I could reproduce the same problem with a simple code.
```python

import win32api
import win32con
import ctypes

PROCESS_DPI_UNAWARE = 0
PROCESS_SYSTEM_DPI_AWARE = 1
PROCESS_PER_MONITOR_DPI_AWARE = 2

ctypes.windll.shcore.SetProcessDpiAwareness(PROCESS_PER_MONITOR_DPI_AWARE)

while True:
    if win32api.MessageBox(None, "hogew", "hog", win32con.MB_YESNO) != win32con.IDYES:
        break
```

I thought this was a bug in the OS.

**Comment by AW14Saurabh** [comment]
![About Page](https://user-images.githubusercontent.com/16162724/236343669-879783cf-3f0e-42bc-a231-6addf12cc879.png)
![Native screen of Dell Precision 5560](https://user-images.githubusercontent.com/16162724/236344327-653b38ef-9f3c-4efb-a5b1-246bd9734720.png)
![Dell P2217H monitor](https://user-images.githubusercontent.com/16162724/236344454-e6cf8019-3be1-4667-a73a-5e58dfd87087.png)
This issue is still present, the native screen is 1920x1200p @ 145ppi, and the monitor is 1920x1080p @ 102ppi. The file picker looks broken on the second monitor.
