### ISSUE TITLE
Old theme color visible when dragging window larger

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#86018]
Testing https://github.com/microsoft/vscode/issues/85994
I have the Atom One Dark theme applied. When I drag the window larger, the newly expanded area is briefly colored with the default dark theme color. In insiders, it is colored black, and it is visible for less time.
Electron 7:
![electron7drag](https://user-images.githubusercontent.com/38270282/70037997-d41b9f80-15b7-11ea-89e1-317c357ca01b.gif)
Insiders:
![insidersdrag](https://user-images.githubusercontent.com/38270282/70037998-d41b9f80-15b7-11ea-859c-41943e11db2d.gif)

**Comment by alexr00** [comment]
Here are single frames that make it more obvious:
Electron 7:
![electron7Still 21](https://user-images.githubusercontent.com/38270282/70038375-69b72f00-15b8-11ea-8b3d-54d93fb08cd4.png)
Insiders:
![insidersStill 20](https://user-images.githubusercontent.com/38270282/70038376-69b72f00-15b8-11ea-8706-c4b28b6332ce.png)

**Comment by deepak1556** [comment]
Fixed with https://github.com/microsoft/vscode/pull/83796/commits/22c3db00ec057fecf0144c4c7f8c6bc6cb60e5d6

**Comment by alexr00** [comment]
I still see it with new exploration build. The black is consistent between insiders and explorations, but the grey is not:
![image](https://user-images.githubusercontent.com/38270282/70126598-ac8d0b80-1679-11ea-817c-4d6497eed90c.png)

**Comment by bpasero** [comment]
@alexr00 is this still as bad as it was in December or has improved?

**Comment by alexr00** [comment]
I don't see the bad extra color at all anymore 👍
