### ISSUE TITLE
JS syntext highlight breaks when in between segmented php code

### ISSUE THREAD

**Issue by Rah1x** [microsoft/vscode#86780]
- VSCode Version: 1.40.2
- OS Version: Win10.0.18363 (x64)

Steps to Reproduce:
1. start a <script> tag
2. insert segments of php code + js code (see images)
3. Now JS syntex highlight will loose its colours forever until the end of <script>. Now ive to see hundreds of lines of js code in awkward colourings.

See the images below. First one is what its with just JS, 2nd one is what happens when php is there and then the colours never come back.

![image](https://user-images.githubusercontent.com/841857/70669862-ad521d00-1ccb-11ea-9bf6-a5178add526d.png)

![image](https://user-images.githubusercontent.com/841857/70669890-c8bd2800-1ccb-11ea-82d3-4ac24a27898c.png)

I know one would say it almost looks the same, but it doesnt, and almost every token is wrongly coloured except for some strings which becomes very painful in real application. 

See the first image below to see what original token was taken as without php (i.e. variable via readWrite):

![image](https://user-images.githubusercontent.com/841857/70670051-2782a180-1ccc-11ea-84c2-a24ef243a25c.png)

And with php the token is changes to meta.embed via objectLiteral

![image](https://user-images.githubusercontent.com/841857/70670099-3d906200-1ccc-11ea-8696-a4c0b9d22556.png)

**Comment by Rah1x** [comment]
interestingly, without php it took `z` as a token, while after php it took `z+=` as a whole token (if that helps you guys figure it out)

**Comment by Rah1x** [comment]
The only "trick" (aka fix) is to put the following at the end of every colour loss due to php parenthesis:
`<?php #/{ syntex highlight fix ?>`

**Comment by roblourens** [comment]
Looks ok to me, what theme, and can you try with 1.41 which we released today?

![image](https://user-images.githubusercontent.com/323878/70763759-1789b280-1d0a-11ea-915d-0f184ff43a98.png)

**Comment by Rah1x** [comment]
yea I just tried with new version and its still the same.

Im using the "Dark (Visual Studio)" theme and ive customised the colours a bit.  Here is my settings.json

`
{

    "files.trimTrailingWhitespace": true,
    "editor.cursorStyle": "line-thin",
    "editor.renderLineHighlight": "none",
    "editor.minimap.enabled": false,
    "editor.tabSize": 4,
    "editor.matchBrackets": "never",
    "editor.suggestSelection": "first",
    "editor.detectIndentation": false,
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?", //for php
    "editor.scrollbar.verticalScrollbarSize": 20,
    "editor.scrollbar.horizontalScrollbarSize": 20,        

    "numberedBookmarks.saveBookmarksInProject": true,
    "numberedBookmarks.backgroundLineColor": "#205989",

    "extensions.ignoreRecommendations": true,

    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",

    "less.compile": {
        "compress":  true,  // true => remove surplus whitespace
        "sourceMap": true,  // true => generate source maps (.css.map files)
    },        

    "scm.diffDecorations": "gutter",
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Visual Studio Dark",

    "workbench.colorCustomizations": {
        "editorOverviewRuler.modifiedForeground": "#0fcdef",
        "editor.selectionHighlightBackground": "#ee684742",
        "gitDecoration.ignoredResourceForeground":"#0fefef",        
        "editorIndentGuide.activeBackground": "#c4a16c49",
        "editorIndentGuide.background": "#3b34349d",
    },

    "editor.tokenColorCustomizations": { //for php

        "comments": "#727272",
        "strings": "#df6363",
        "keywords": "#7ea9e2",
        "types": "#c4a16c",

        //see https://macromates.com/manual/en/language_grammars
        "textMateRules": [
            {
                "scope": [
                    "constant.language",
                    "constant.other",
                    "constant.numeric",
                    "keyword.operator",
                    "variable",
                    "variable.language",
                    "entity.other.attribute-name",
                    "entity.name.tag",
                    "punctuation.definition.tag.begin",
                    "punctuation.definition.tag.end",
                ],
                "settings": {
                    "foreground": "#c4a16c",
                }
            },
            {
                "scope": [
                    "punctuation.separator",
                    "punctuation.terminator",
                    "punctuation.accessor",
                ],
                "settings": {
                    "foreground": "#c4a16c83"
                }
            },
            {
                "scope": "storage.modifier",
                "settings": {
                    "foreground": "#8ab7f1"
                }
            },
            {
                "scope": [
                    "entity.name",
                    "support",
                    "support.type",                    
                ],
                "settings": {
                    "foreground": "#45c461"
                }
            },
            {
                "scope": "invalid",
                "settings": {
                    "foreground": "#e4d7c3",
                    "fontStyle": "underline"
                }
            },
            {
                "scope": "comment.block.documentation",
                "settings":{
                    "foreground": "#e08af16c",
                    "fontStyle": "italic",
                }
            },
            {
                "scope": [
                    "comment.block",
                ],
                "settings":{
                    "foreground": "#727272",
                    "fontStyle": "italic",
                }
            },
            {
                "scope": [
                    "punctuation.section.embedded.begin.php",
                    "punctuation.section.embedded.end.php",
                ],
                "settings": {
                    "foreground": "#45c461"
                }
            },
            {
                "scope": "keyword",
                "settings": {
                    "fontStyle": "italic",
                }
            },
            {
                "scope": "storage",
                "settings": {
                    "fontStyle": "italic"
                }
            },
            {
                "scope": "constant.language",
                "settings": {
                    "fontStyle": "italic",
                    "foreground": "#8ab7f1"
                }
            },
            {
                "scope": "support.class.builtin",
                "settings": {
                    "fontStyle": "bold"
                }
            },
        ]
    },
    
    "bracket-pair-colorizer-2.forceUniqueOpeningColor": false,
    "bracket-pair-colorizer-2.colors": [
        "#c9a166"
    ],
    "bracket-pair-colorizer-2.scopeLineCSS": [
        "borderStyle : dotted",
        "borderWidth : 1px",
        "borderColor : {color}",
        "opacity: 0.4"
    ]    
}
`

**Comment by Rah1x** [comment]
This issue is actually coming from Laravel-blade extension so I will contact them instead.
