### ISSUE TITLE
As someone with an ED and "challenged" with size "down there" I find the name Microsoft offensive

### ISSUE THREAD

**Issue by SRGOM** [microsoft/vscode#87508]
To clarify the first usage of the term Microsoft in reference to my .. um. .. member predates Microsoft Inc formation by 20 years. Incidentally it also happened in new Mexico and I'm now, after making this issue, wondering if I have an opportunity to sue Microsoft for trademark violation .

Anyway the year is 1960, I'll spare you the nsfw details but ummm after some (attempted) action with a girl, her name was Amanda,, she called me micro and soft. The nick caught up and everyone in school called me Microsoft. I had to leave school (Amanda claimed that she still loves me) and have since then been unable to continue my education ..

I recently discovered the joys of coding from internet (I'm a self taught css programmer and js framework enthusiast and I only use apple). However the horror of me when I saw that one of the dominant programming companies was called Microsoft. (Surely Amanda O'Reilly isn't a founder ?). Thankfully it seems that this festive season Microsoft is out to correct all flaws. May I hence request them to change their name (Amanda I still love you too, but you know I never liked this name). 

Thank you ummmm MacroHard?

**Comment by Tenemo** [comment]
These issues were funny during the whole hat debacle, but I don't think they are anymore. Please chill people. I think everyone agrees the problem was resolved successfully and in a tactful manner, so maybe it's about time to go back to using the Issues as they were intended to be used.

**Comment by nikandlv** [comment]
@Tenemo Well not everyone agrees with this decision, and clearly it was not resolved in a tactful manner.
this is discrimination against everyone else when microsoft satisfy someone and does not satisfy others
either nobody should be allowed to post and resolve such a thing or everyone should

**Comment by SRGOM** [comment]
> These issues were funny during the whole hat debacle, but I don't think they are anymore. Please chill people. I think everyone agrees the problem was resolved successfully and in a tactful manner, so maybe it's about time to go back to using the Issues as they were intended to be used.

You're just worried because once Microsoft changes name to my suggestion, your little known company would be even more irrelevant. Perhaps you need to change it's name preemptively while there is still time.
