### ISSUE TITLE
Account for custom git diff driver

### ISSUE THREAD

**Issue by SherloxFR** [microsoft/vscode#88614]
Hi, I'm using a custom git diff driver to show real diffs on SOPS encrypted files.

It works when firing a `git diff` command, and I thought VSCode would just do the same, but it seems like it is more complicated than that.

If this is already implemented, could you explain me how ? I found no documentation about this, and no SO answer.

Thanks in advance

**Comment by joaomoreno** [comment]
I'm not sure I understand what you intend to do.

Can you elaborate?

**Comment by SherloxFR** [comment]
I have preprocessing in my git diff (like explained [here](https://github.com/mozilla/sops/blob/master/README.rst#48showing-diffs-in-cleartext-in-git)) and it is not reflected in the diff view of VSCode.

**Comment by joaomoreno** [comment]
So what happens when you open the diff in VS Code? Both sides are garbled?

**Comment by SherloxFR** [comment]
Well yes they are encrypted just like if the diff driver wasn't kicking in.

**Comment by RReverser** [comment]
This could be a great feature for comparing arbitrary binary files as well (which are not comparable in VSCode by default).

I know VSCode has own implementation of the diff algorithm, but I suppose it should still be able to read the `textconv` command from Git config and then diff the text result.

**Comment by joaomoreno** [comment]
@RReverser It's exactly the same fix, which I just pushed: https://github.com/microsoft/vscode/commit/3cc86855010e3049bbc19f366f44d55bf08859fb

**Comment by RReverser** [comment]
Ah interesting, thanks (I'd argue the issue is still not a dupe, but doesn't matter anymore :) ).
