### ISSUE TITLE
Sudden inability to scroll and type in editor screen

### ISSUE THREAD

**Issue by louisfoster** [Microsoft/vscode#9045]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:50:12.291Z)
- OS Version: Linux x64 3.19.0-32-generic

**Update**
I'm using cordova and it seems to be related to running the build command, but doesn't happen consistently, only after about 10 minutes of using VSCode

**Original post**
Not sure what happened, but after installing 1.3.0 today, after doing some edits and having about 5 or 6 tabs open, I could no longer do anything with each editor window. Every tab opened and closed ok, and everything else worked fine, just no editing ability in the editor window, and could scroll them either.

**Comment by bpasero** [comment]
@louisfoster is this reproducible somehow? anything in the developer console when this happens (toggle from help menu).

**Comment by louisfoster** [comment]
@bpasero I haven't managed to effectively consistently reproduce it, it happens almost randomly. I will keep an eye on the console and report back. Very annoying though and does happen repeatedly, requiring a whole application restart.

**Comment by louisfoster** [comment]
The only error I get is this one that repeats every few seconds from the moment I open the application, it continues to produce this error even after the editor stops working.
```
Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at e.onCommonRequest (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:20045),    at e.onMessage (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19889),    at /usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:19697,    at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/code/node/sharedProcessMain.js:6:23531),    at emitOne (events.js:90:13),    at Socket.emit (events.js:182:7),    at readableAddChunk (_stream_readable.js:153:18),    at Socket.Readable.push (_stream_readable.js:111:10),    at Pipe.onread (net.js:531:20)e.onUnexpectedError @ shell.ts:416(anonymous function) @ shell.ts:318e.onUnexpectedError @ errors.ts:73u @ errors.ts:88(anonymous function) @ winjs.base.js:43(anonymous function) @ winjs.base.js:38
winjs.base.js:45 
WARNING: Promise with no error callback:1946
```
However, there is no output that seems to happen at the time the editor fails. The final line indicates that when I copied the error, around the time the editor stopped working, the error had been reported 1946 times.

**Comment by bpasero** [comment]
@louisfoster can you see if after you stop VS Code there are some ghost processes hanging around from a previous installation (VS Code 1.2) and make sure to terminate them all?

**Comment by louisfoster** [comment]
![screenshot_2016-07-11_17-37-40](https://cloud.githubusercontent.com/assets/8028567/16723148/907397e2-478e-11e6-850e-4f9c03f722f3.png)
Killing these lingering tasks after closing VSCode seems to have stopped the constant error outputs. I'll close this issue if within the next hour I don't get an editor crash.

**Comment by bpasero** [comment]
@louisfoster great, this was an issue we had for all Linux users that was fixed in 1.3 (but present in 1.2).

**Comment by louisfoster** [comment]
@bpasero Unfortunately I am still getting a crash, and there are no errors in the console. I'm going to restart my computer and see if that helps.

**Comment by bpasero** [comment]
@louisfoster yes please do that and when you have steps to reproduce somehow that would help.

**Comment by bpasero** [comment]
@louisfoster and can you clarify that only typing does not work but you can scroll in the editor?

@alexandrudima fyi marking as important but we still do not fully understand what is going on.

**Comment by heroboy** [comment]
@bpasero, I have the same problem. Today this happened serval times.
When it happens, I click the editor , it doesn't show or move the cursor. But ctrl+F is working.

**Comment by bpasero** [comment]
I wonder if this is the DND overlay div not getting cleaned up. Are you guys using DND to rearrange editors or move them?

@louisfoster @heroboy when this happens can you please open Help > Toggle Developer Tools and click on "Elements" and the little arrow (see screen shot) and move the mouse over the editor to see if some DIV is on top of the editor?

![image](https://cloud.githubusercontent.com/assets/900690/16726040/761c7262-475a-11e6-9afb-bff56a494ca3.png)

**Comment by louisfoster** [comment]
@bpasero Since I restarted my computer I haven't had the issue. However the console is logging another massively repeated error regarding this:
```
ipc.cp.ts:139[IPC Library: Watcher] Error: watch <any random file in my project, different every time> 
(anonymous function) @ ipc.cp.ts:139
```

**Comment by heroboy** [comment]
![qq 20160711174953](https://cloud.githubusercontent.com/assets/54468/16726643/e10f0672-478f-11e6-87b7-9c726cb50aed.jpg)
It seems  to be the drop overlay.

**Comment by heroboy** [comment]
And I drap another file to the editor, then it recovered.

**Comment by bpasero** [comment]
@louisfoster this might be the ENOSPC issue which is explained in our FAQ section here: http://code.visualstudio.com/docs/setup/linux#_common-questions

@heroboy @louisfoster are you both using the extension to show icons in the explorer? I wonder if that is related.

**Comment by louisfoster** [comment]
@bpasero What heroboy wrote would make sense as I'm dragging files across windows into an emulator every time I do a build, which would correlate with why I'm getting this error around the same time. Although playing around with the dropping feature, I can't seem to trigger it since restarting my computer.

**Comment by bpasero** [comment]
@louisfoster so you drag from outside a VM into the editor area to have the file opened?

**Comment by louisfoster** [comment]
No, I drag from a directory in my file explorer to a VM, but in the process my cursor floats over the editor window, which I assume was triggering the drop area, which wasn't clearing properly.

**Comment by heroboy** [comment]
@bpasero I installed "vscode-icons" extension. And everytime this happened is when I was switching to vscode from another window.

**Comment by louisfoster** [comment]
@bpasero I have finally successfully reproduced it. It happens only when I drag from my file explorer to the VM, there is only a few pixel between the two windows, with the editor in the background. It passes over the editor so quickly that the drop doesn't even flash the opaque white.

I'm not really sure what what the icons extension is, so I assume I don't have it installed, according to my "Show Installed Extensions" list, I don't have any installed.

**Comment by bpasero** [comment]
@heroboy are you also using a VM?

**Comment by louisfoster** [comment]
@bpasero It doesn't matter what the windows are, it happens dragging between any window with the editor in the background. The width between the two windows is around 2 to 6 monospace characters @ size 14 , any closer and it doesn't seem to trigger the drop in the editor, any further the drop seems to clear without any problems. Seems like it is just a timing thing.
![screenshot_2016-07-11_20-44-05](https://cloud.githubusercontent.com/assets/8028567/16728296/fd0cfdb6-47a8-11e6-80d8-1eb946770308.png)

**Comment by heroboy** [comment]
@bpasero No, I'm not using a VM.

**Comment by bpasero** [comment]
@heroboy do you have some steps how to reproduce this without a VM? do you drop it somewhere special outside of the editor area?

**Comment by bpasero** [comment]
Pushed a change to more aggressively remove the overlay as soon as the mouse enters.

**Comment by bpasero** [comment]
This needs verification across Windows, Mac and Linux. The only way I could reproduce this bug was to run Windows in parallels on Mac and drop a file from the Mac finder into the editor area. This should leave the editor OK and usable.

Also needs to verify that you can still do editor DND in the editor area (from explorer to tabs / editor area, from the desktop into editor area, etc.).

**Comment by bpasero** [comment]
@joaomoreno can you verify this using the stable build on windows: https://az764295.vo.msecnd.net/stable/e6b4afa53e9c0f54edef1673de9001e9f0f547ae/VSCode-win32-stable.zip

Since you have a similar setup with a Windows VM it should be doable.
