### ISSUE TITLE
Word wrap not working

### ISSUE THREAD

**Issue by amitgupta4078** [microsoft/vscode#90686]
Issue Type: <b>Bug</b>

I have a file open in which the text is very long in one line. When I do Word wrap, I expect the horizontal scrollbars to go away and word wrapping happening. But this happens only sometimes. Other times, the scenario remains the same.

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_639132|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
beautify|Hoo|1.5.0
compareit|in4|0.0.2
vue|jcb|0.1.5
python|ms-|2020.2.63072
cpptools|ms-|0.26.3
vetur|oct|0.23.0
gitblame|wad|3.0.1

</details>

**Comment by alexdima** [comment]
There was a problem with files with very long lines. Fixed in #90391

**Comment by amitgupta4078** [comment]
Issue still persists in latest version of VS Code

I have opened a file with long strings. When I click on Toggle Word Wrap, I expect the horizontal scrollbar to go away and panel on right side to intermix perfectly with page rather than appearing as an over-the-top panel. I am on latest version but this is still not working. This is so frustrating.

VS Code version: Code 1.43.0 (78a4c91, 2020-03-09T19:34:44.548Z)
OS version: Darwin x64 18.7.0

**Comment by alexdima** [comment]
@amitgupta4078 Please create a new issue and also include the file that is problematic or a file that is very similar and that you can share. I would like to try to reproduce.

**Comment by alexdima** [comment]
@amitgupta4078 Can you please include the file that is problematic?
