### ISSUE TITLE
Can't enable vscode-icons

### ISSUE THREAD

**Issue by koba04** [Microsoft/vscode#9137]
- VSCode Version:

```
Version 1.4.0-insider (1.4.0-insider)
583f439c1d49128a4775c1ba5a1ac8c6ddd63d5f
2016-07-12T05:02:05.825Z
```

- OS Version:
OSX 10.11.5 

Steps to Reproduce:

1. install vscode-icons
2. >icons Enable
3. you can see the following a message

```
Run VS Code with admin privileges so the changes can be applied.
```

I've been able to enable `vscode-icons` until I updated `vscode-insider` today.
In addition, I can enable `vscode-icons` with `vscode`(1.3.0)

the version of `vscode-icons` is `1.3.12`.
Is this an issue for `vscode-icons`?

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by koba04** [comment]
Thank you for your comment!

**Comment by kachkaev** [comment]
@koba04 have you found a solution? Having the same issue with version 1.3.1 on Ubuntu

**Comment by koba04** [comment]
@kachkaev 
This issue has been fixed at `vscode-icons` 1.4.0 🎉  https://github.com/robertohuertasm/vscode-icons/commit/2bb17336d7338375ff51d3a0bb78b1a2e961019a

**Comment by perry-mitchell** [comment]
I'm still having the same issue with vscode-icons at version 1.4.3, latest VSCode.
![image](https://cloud.githubusercontent.com/assets/3869469/16940931/a7b9f2e0-4d95-11e6-9842-d63d48f4bb6e.png)

**Comment by d0f** [comment]
you can run `sudo code . --user-data-dir=. ` in bash
