### ISSUE TITLE
When change the default ssh shell to powershell on windwos ssh server remote connection always fail.

### ISSUE THREAD

**Issue by zuoxiaofeng** [microsoft/vscode#91543]
Issue Type: <b>Bug</b>

1. change the default ssh shell from cmd to powershell on windows ssh server
2. try open a windows ssh server remote window will failed.

VS Code version: Code - Insiders 1.43.0-insider (b0be0672c210f1fa76109ce675365bb785657e84, 2020-02-26T05:30:24.470Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (7.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out
</details>Extensions: none

**Comment by roblourens** [comment]
Please try this with the nightly version of the SSH extension, should be fixed there

**Comment by zuoxiaofeng** [comment]
> Please try this with the nightly version of the SSH extension, should be fixed there
Hi
How can I install nightly version of the SSH extension.

Thanks.

**Comment by zuoxiaofeng** [comment]
I have found the nightly version and installed, but still failed.

**Comment by roblourens** [comment]
Please include the log from the Remote-SSH output channel

**Comment by zuoxiaofeng** [comment]
[09:30:42.511] Log Level: 2
[09:30:42.520] remote-ssh-nightly@2020.2.35520
[09:30:42.520] win32 x64
[09:30:42.521] SSH Resolver called for "ssh-remote+windows", attempt 1
[09:30:42.522] SSH Resolver called for host: windows
[09:30:42.522] Setting up SSH remote "windows"
[09:30:42.525] Acquiring local install lock: C:\Users\zuoxf1\AppData\Local\Temp\vscode-remote-ssh-windows-install.lock
[09:30:42.538] Looking for existing server data file at c:\Users\zuoxf1\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-ssh-nightly\vscode-ssh-host-windows-0eebaf9ad23748baca2afc0da425650922bc23de\data.json
[09:30:42.539] Using commit id "0eebaf9ad23748baca2afc0da425650922bc23de" and quality "insider" for server
[09:30:42.540] Install and start server if needed
[09:30:42.543] Checking ssh with "ssh -V"
[09:30:42.605] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:30:42.605] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[09:30:42.641] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:30:42.641] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[09:30:42.940] > OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
[09:30:42.942] askpass server listening on \\.\pipe\vscode-ssh-askpass-f6eadeafd67a8f34f2cb341b0469e2c1ddd0c6a5-sock
[09:30:42.942] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-ae74f2d8d5edc1dc4063db4714474b1714afd650-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","55135","windows"],"dataFilePath":"c:\\Users\\zuoxf1\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\ms-vscode-remote.remote-ssh-nightly\\vscode-ssh-host-windows-0eebaf9ad23748baca2afc0da425650922bc23de\\data.json"}
[09:30:42.942] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\zuoxf1\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-nightly-2020.2.35520\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\zuoxf1\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\Code - Insiders.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\zuoxf1\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-nightly-2020.2.35520\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-f6eadeafd67a8f34f2cb341b0469e2c1ddd0c6a5-sock"}
[09:30:42.948] Spawned 138104
[09:30:43.413] > local-server> Spawned ssh: 137848
[09:30:43.472] stderr> OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
[09:30:43.835] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:r6a5n+A44zfu2FOSj43RRSrSlLh+kvSYNupz2Y7iHPY
[09:30:44.186] stderr> Authenticated to 10.240.197.56 ([10.240.197.56]:22).
[09:30:44.489] > Windows PowerShell 
> Copyright (C) Microsoft Corporation. All rights reserved.
[09:30:44.621] > PS C:\Users\zuoxf> 
[09:30:44.742] > echo 'ready: 101b77336451'
[09:30:44.754] > ready: 101b77336451
[09:30:44.770] > PS C:\Users\zuoxf> 
[09:30:44.799] > u
[09:30:44.801] > name -rsv
[09:30:44.913] stderr> uname : The term 'uname' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
[09:30:44.913] stderr> the spelling of the name, or if a path was included, verify that the path is correct and try again.
[09:30:44.913] stderr> At line:1 char:1
[09:30:44.913] stderr> + uname -rsv
[09:30:44.913] stderr> + ~~~~~
[09:30:44.913] stderr>     + CategoryInfo          : ObjectNotFound: (uname:String) [], CommandNotFoundException
[09:30:44.914] stderr>     + FullyQualifiedErrorId : CommandNotFoundException
[09:30:44.914] stderr>  
[09:30:44.914] Platform: windows
[09:30:44.914] Remote command length: 7676/8192 characters
[09:30:44.933] > PS C:\Users\zuoxf> 
[09:30:44.978] > powershell
[09:30:45.067] > Windows PowerShell 
> Copyright (C) Microsoft Corporation. All rights reserved.
[09:30:45.212] > PS C:\Users\zuoxf> 
[09:30:45.359] > A
[09:30:45.372] > iV2luZG93cyBob3N0cyBhcmUgb25seSBzdXBwb3J0ZWQgd2hlbiBydW5uaW5nIFZTIENvZGUgSW5zaWRlcnMiCmVjaG8gIjEwMWI3NzMzNjQ1MSMjMzMjIyIKZXhpdCAwCn0KCmZ1bmN0aW9uIGdldFNzaGRQYXJlbnRQaWQgewokY3VycmVudFBJRCA9ICRQSUQKd2hpbGUgK
[09:30:45.372] > CRUcnVlKSB7CiRwYXJlbnRQSUQgPSAoR2V0LUNpbUluc3RhbmNlIHdpbjMyX3Byb2Nlc3MgfCA/I
[09:30:45.374] > HByb2Nlc3NpZCAtZXEgJGN1cnJlbnRQSUQpLnBhcmVudHByb2Nlc3NpZAppZiAoISRwYXJlbnRQSUQpIHsKZWNobyAiQ291bGQgbm90I
[09:30:45.374] > GZpbmQgYW4gc3NoZCBwYXJlbnQgb2YgdGh
[09:30:45.374] > pcyBwcm9jZXNzIgpleGl0IDAKfQoKaWYgKChncHM
[09:30:45.374] > gLUlkICRwYXJl
[09:30:45.376] > bnRQSUQpLk5hbWUgLWVxICdzc2hkJykgewpyZXR1cm4gJHBhcmVudFBJRAp9CgokY3VycmVudFBJRCA9ICRwYXJlbnRQSUQKfQp9CgpmdW5jdGlvbiBleGl0SWZOZWVkZWQgewppZiAoJGxhdW5jaGVkU2VydmVyUGlkKS
[09:30:45.376] > B7CmlmICghKGdwcyAtSWQg
[09:30:45.376] > J
[09:30:45.378] > GxhdW5jaGVkU2VydmVyUGlkKSkgewplY2hvICJUaGUgbGF1bmNoZWQgc2VydmVyIGRpZWQsIGV4
[09:30:45.378] > aXRpbmciCmV4aX
[09:30:45.378] > QgMAp9Cn0gZWxzZ
[09:30:45.380] > SB7CmlmICghKGdwcyAtSWQgJHNzaGRQSUQpKSB7CmVjaG8gIlRoZSBzc2hkIHBhcmVudCBkaWVkLCBleGl0aW5nIgpleGl0IDAKfQp9Cn0KCm
[09:30:45.380] > Z1bmN0aW9uIERvd25sb2F
[09:30:45.382] > kU2VydmVyIHsKZWNobyAiRG93bmxvYWRpbmcgVlMgQ29kZSBTZXJ2ZXIiCmVjaG8gJzEwMWI3NzMzNjQ1MSUlMSUlJwokc3BsYXQgPS
[09:30:45.485] > BAewpVcmk9Imh0dHBzOi8vdXBkYXRlLmNvZGUudmlzdWFsc3R1ZGlvLmNvbS9jb21taXQ6JGNvbW1pdElkLyRzZXJ2ZXJOYW1lLyRxdWFsaXR5IgpUaW1lb3V0U2VjPTIwCk91dEZpbGU9IiRzZXJ2ZXJOYW1
[09:30:45.510] > lLnppcCIKVXNlQmFzaWNQYXJzaW5nPSRUcnVlCn0KCltOZXQuU
[09:30:45.516] > 2VydmljZVBvaW50TWFuYWdlcl06OlNlY3VyaXR5UHJvdG9jb2wgPSBbTmV0LlNlcnZpY2VQb2ludE1hbmFnZXJdOjpTZWN1cml0eVByb3RvY29sIC1ib3IgW05ldC5TZWN1cml0eVByb3RvY29sVHlwZV06OlRsczEyCkludm9rZS1SZXN0TWV0aG9kIEBzcGxhdAoKJHJhbmRvbURpck5hbWUgPSBbU3lzdGVtLklPLlBhdGhdOjpHZXRSYW5kb21GaWxlTmFtZSgpCiR0bXBEZXN0ID0gIiRlbnY6VEVNUFwkcmF
[09:30:45.516] > uZG9tRGlyTmFtZSIKZWNobyAiRXhwYW5kaW5nIHNlcnZlciBhdCAkdG1wRGVzdCIKZWNobyAnMTAxYjc3MzM2NDUxJSUyJSUnCkV4cGFuZC1BcmNoaXZlICIkc2VydmVyTmFtZS56aXAiIC1EZXN0aW5hdGlvblBhdGggIiR0bXBEZXN0IgpNb3ZlLUl0ZW0gIiR0bXBEZXN0XHZzY29kZS0kc2VydmVyTmFtZVwqIiAtRGVzdGluYXRpb24gLgp9CgpmdW5jdGlvbiBEb0NsaWVudERvd25sb2FkIHsKZWNobyAiVHJpZ2dlciBjbGllbnQgc2VydmVyIGRvd25sb
[09:30:45.519] > 2FkIgplY2hvIDEwMWI3NzMzNjQ1MTp0cmlnZ2VyX3NlcnZlcl9kb3dubG9hZAplY2hvIHBsYXRmb3JtPT13aW5kb3dzPT0KZWNobyB2c2NvZGVBcmNoPT0kdnNjb2RlQXJjaD09CmVjaG8gZGVzdEZvbGRlcj09JHNlcnZlckRpcj09CmVjaG8gMTAxYjc3MzM2NDUxOnRyaWdnZXJfc2VydmVyX2Rvd25sb2FkX2VuZAoKZWNobyAiV2FpdGluZyBmb3IgY2xpZW50IHRvIHRyYW5zZmVyIHNlcnZlciBhcmNoaXZlLi4uIgplY2hvICJXYWl0aW5nIGZvciAkc2VydmVyRGlyXHZzY29kZS1zY3AtZG9uZS5mbGFnIGFuZCB2c2NvZGUtc2VydmVyLnppcCB0byBleGlzdCIKCndoaWxlKCRUcnVlKSB7CmlmKFRlc3QtUGF0aCAiJHNlcnZlckRpclx2c2NvZGUtc2NwLWRvbmUuZmxhZyIpIHsKaWYoIShUZXN0LVBhdGggIiRzZXJ2ZXJEaXJcdnNjb2RlLXNlcnZlci56aXAiKSkgewplY2hvICJGb3VuZCBmbGFnIGJ1dCBub3Qgc2VydmVyIHRhciAtIHNlcnZlciB0cmFuc2ZlciBmYWlsZWQiCmVjaG8gIjEwMWI3NzMzNjQ1MSMjMzEjIyIKZXhpdCAwCn0KCmVjaG8gIkZvdW5kIGZsYWcgYW5kIHNlcnZlciBvbiBob3N0IgpkZWwgJHNlcnZlckRpclx2c2NvZGUtc2NwLWRvbmUuZmxhZwpicmVhawp9IGVsc2UgewpTdGFydC1TbGVlcCAtU2Vjb25kcyAzCmV4aXRJZk5lZWRlZAp9Cn0KfQoKJHNzaGRQSUQgPSBnZXRTc2hkUGFyZW50UGlkCgppZighKFRlc3QtUGF0aCAkc2VydmVyRGlyKSkgewp0cnkgewokbnVsbCA9IE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgJHNlcnZlckRpciAtRm9yY2UgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUKfSBjYXRjaCB7CmVjaG8gIkNvdWxkIG5vdCBjcmVhdGUgdnNjb2RlLXNlcnZlciBkaXJlY3RvcnkuIC0gJCgkXy5Ub1N0cmluZygpKSIKcmV0dXJuCn0KCmlmKCEoVGVzdC1QYXRoICRzZXJ2ZXJEaXIpKSB7CmVjaG8gIkNvdWxkIG5vdCBjcmVhdGUgdnNjb2RlLXNlcnZlciBkaXJlY3RvcnkuIgpyZXR1cm4KfQp9CgpjZCAkc2VydmVyRGlyCgokbG9ja0ZpbGVQYXRoID0gKEpvaW4tUGF0aCAiJHNlcnZlckRpciIgInZzY29kZS1yZW1vdGUtbG9jay4kY29tbWl0SWQiKQp0cnkgewokbnVsbCA9IE5ldy1JdGVtICRsb2NrRmlsZVBhdGggLUl0ZW1UeXBlIEZpbGUgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUKfSBjYXRjaCB7CmVjaG8gIkNvdWxkIG5vdCBjcmVhdGUgdnNjb2RlLXNlcnZlciBsb2NrIGZpbGUuIC0gJCgkXy5Ub1N0cmluZygpKSIKcmV0dXJuCn0KCnRyeSB7CmVjaG8gIkFjcXVpcmluZyBsb2NrIG9uICRsb2NrRmlsZVBhdGgiCgokZmlsZSA9IFtTeXN0ZW0uaW8uRmlsZV06Ok9wZW4oJGxvY2tGaWxlUGF0aCwgJ09wZW4nLCAnUmVhZCcsICdOb25lJykKfSBjYXRjaCB7CmVjaG8gIkluc3RhbGxhdGlvbiBhbHJlYWR5IGluIHByb2dyZXNzLi4uIC0gJCgkXy5Ub1N0cmluZygpKSIKZWNobyAiMTAxYjc3MzM2NDUxIyMyNCMjIgpyZXR1cm4KfQoKdHJ5IHsKZWNobyAiTG9va2luZyBmb3IgZXhpc3Rpbmcgc2VydmVyIGluICRzZXJ2ZXJEaXIiCmlmKFRlc3QtUGF0aCAiJHNlcnZlckRpclxzZXJ2ZXIuY21kIikgewplY2hvICJ2c2NvZGUtc2VydmVyIGFscmVhZHkgaW5zdGFsbGVkLiBTa2lwcGluZyBkb3dubG9hZC4uLiIKfSBlbHNlIHsKdHJ5IHsKRG93bmxvYWRTZXJ2ZXIKfSBjYXRjaCB7CmVjaG8gIkZhaWxlZCB0byBkb3dubG9hZCAmIGV4dHJhY3QgdnNjb2RlLXNlcnZlci4gLSAkKCRfLlRvU3RyaW5nKCkpIgpEb0NsaWVudERvd25sb2FkCgpyZXR1cm4KfQoKaWYoIShUZXN0LVBhdGggIiRzZXJ2ZXJEaXJcc2VydmVyLmNtZCIpKSB7CmVjaG8gIkZhaWxlZCB0byBkb3dubG9hZCAmIGV4dHJhY3QgdnNjb2RlLXNlcnZlci4iCmVjaG8gIjEwMWI3NzMzNjQ1MSMjMjUjIyIKcmV0dXJuCn0KfQoKaWYgKCRleHRlbnNpb25zIC1uZSAiIikgewplY2hvICJJbnN0YWxsaW5nIGV4dGVuc2lvbnMuLi4iCiYgIiRzZXJ2ZXJEaXJcc2VydmVyLmNtZCIgJHRlbGVtZXRyeSAgIyA/Pwp9CgppZighKEdldC1Qcm9jZXNzIG5vZGUgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUgfCBXaGVyZS1PYmplY3QgUGF0aCAtbWF0Y2ggJGNvbW1pdElkKSkgewppZihUZXN0LVBhdGggJGxvZ2ZpbGUpIHsKZGVsICRsb2dmaWxlCn0KJHNwbGF0ID0gQHsKRmlsZVBhdGggPSAicG93ZXJzaGVsbC5leGUiCldpbmRvd1N0eWxlID0gImhpZGRlbiIKQXJndW1lbnRMaXN0ID0gQCgKIi1FeGVjdXRpb25Qb2xpY3kiLCAiVW5yZXN0cmljdGVkIiwgIi1Ob0xvZ28iLCAiLU5vUHJvZmlsZSIsICItTm9uSW50ZXJhY3RpdmUiLCAiLWMiLCAiJiBgIiRzZXJ2ZXJEaXJcc2VydmVyLmNtZGAiIC0taG9zdD0xMjcuMC4wLjEgLS1lbmFibGUtcmVtb3RlLWF1dG8tc2h1dGRvd24gLS1wb3J0PTAgJHRlbGVtZXRyeSAqPiAkbG9nZmlsZSIKKQpQYXNzVGhydSA9ICRUcnVlCn0KZWNobyAiU3RhcnRpbmcgc2VydmVyIHdpdGggY29tbWFuZC4uLiAmICckc2VydmVyRGlyXHNlcnZlci5jbWQnIC0taG9zdD0xMjcuMC4wLjEgLS1lbmFibGUtcmVtb3RlLWF1dG8tc2h1dGRvd24gLS1wb3J0PTAgJHRlbGVtZXRyeSIKJGxhdW5jaGVkU2VydmVyUGlkID0gKFN0YXJ0LVByb2Nlc3MgQHNwbGF0KS5JRAp9IGVsc2UgewplY2hvICJ2c2NvZGUtc2VydmVyIHdpdGggJGNvbW1pdElkIGlzIGFscmVhZHkgcnVubmluZy4iCn0KCiRzcGxhdCA9IEB7ClBhdGggPSAkbG9nZmlsZQpQYXR0ZXJuID0gIkV4dGVuc2lvbiBob3N0IGFnZW50IGxpc3RlbmluZyBvbiAoXGQrKSIKfQoKJHRpbWVvdXREYXRl
[09:30:45.542] > ID0gKEdldC1EYXRlKS5BZGRTZWNvbmRzKDQpCndoaWxlICgoR2V0LURhdGUpIC1sdCAkdGltZW91dERhdGUpIHsKaWYoVGVzdC1QYXRoICRsb2dmaWxlKSB7CiRncm91cHMgPSAoU2VsZWN0LVN0cmluZyBAc3BsYXQpLk1hdGNoZXMuR3JvdXBzCmlmKCRncm91cHMpIHsKJHBvcnQgPSAkZ3JvdXBzWzFdLlZhbHVlCmJyZWFrCn0KfQpTdGFydC1TbGVlcCAtTWlsbGlzZWNvbmRzIDUwMAp9CgppZiAoISRwb3J0KSB7CmVjaG8gIlNlcnZlciBkaWQgbm90IHN0YXJ0IHN1Y2Nlc3NmdWxseS4gRnVsbCBzZXJ2ZXIgbG9nIGF0ICRsb2dmaWxlID4+PiIKY2F0ICRsb2dmaWxlCmVjaG8gIjw8PCBFbmQgb2Ygc2VydmVyIGxvZyIKZWNobyAiMTAxYjc3MzM2NDUxIyMzMiMjIgpyZXR1cm4KfQp9IGNhdGNoIHsKZWNobyAidnNjb2RlLXNlcnZlciBmYWlsZWQgdG8gc3RhcnQuIC0gJCgkXy5Ub1N0cmlu
[09:30:45.579] > ZygpKSIKfSBmaW5hbGx5IHsKJGZpbGUuQ2xvc2UoKQp9CgoKdHJ5IHsKJHdpblZlcnNpb24gPSAoR2V0LUNpbUluc3RhbmNlIFdpbjMyX09wZXJhdGluZ1N5c3RlbSkuVmVyc2lvbgp9IGNhdGNoIHsKZWNobyAiRmFpbGVkIHRvIGZpbmQgV2luZG93cyB2ZXJzaW9uIC0gJCgkXy5Ub1N0cmluZygpKSIKJHdpblZlcnNpb24gPSAidW5rbm93biIKfQoKZWNobyAiMTAxYjc3MzM2NDUxOiBzdGFydCIKZWNobyAic3NoQXV0aFNvY2s9PSRlbnY6U1NIX0FVVEhfU09DSz09IgplY2hvICJhZ2VudFBvcnQ9PSRwb3J0PT0iCmVjaG8gIm9zUmVsZWFzZUlkPT13aW5kb3dzPT0iCmVjaG8gIm9zVmVyc2lvbj09JHdpblZlcnNpb249PSIKZWNobyAiYXJjaD09JHZzY29kZUFyY2g9PSIKZWNobyAicGxhdGZvcm09PXdpbmRvd3M9PSIKZWNobyAiMTAxYjc3MzM2NDUxOiBlbmQiCgoKCmVjaG8gIkluc3RhbGwgc2NyaXB0IGlzICRwaWQsIHdhdGNoaW5nIHNzaGQgcGFyZW50ICRzc2hkUElEIgp3aGlsZSAoJFRydWUpIHsKZXhpdElmTmVlZGVkClN0YXJ0LVNsZWVwIDMwCn0K')))); powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand `$e"
> >> 
[09:30:59.949] Terminating local server
[09:30:59.952] Resolver error: Connecting with SSH timed out
[09:30:59.955] ------




[09:30:59.958] Local server exit: null
