### ISSUE TITLE
timeline-View shown nothing

### ISSUE THREAD

**Issue by bardware** [microsoft/vscode#92033]
- VSCode Version: 1.43.0 insider
- OS Version: Win 10 64 bit German
- git version 2.24.0.windows.2

Steps to Reproduce:

1. Add `"timeline.showView": true` to `settings.json`
2. Open a file - timeline-View stays empty.
I switch to output pane, select Git as soure and read
``` 
> git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z -n21 -- d:\Webs\xxx\yyy\zzz\README.md
fatal: d:\Webs\xxx\yyy\zzz\README.md: 'd:\Webs\xxx\yyy\zzz\README.md' is outside repository
```

When I started code I switched to folder `d:\Webs\xxx\yyy\zzz` and called `"c:\Program files\VSCode_insider\bin\code-insiders.cmd" . --extensions-dir "D:\vscode\insiders_cfml\exts" --new-window`.
When I copy the `git log` call to `cmd` I get the same error message. Still, I guess the path to the file whose history is to be retrieved is wrong.
I have no idea how it has to look.

Does this issue occur when all extensions are disabled?: Yes

**Comment by KevinGuancheDarias** [comment]
Able to reproduce. In todays build of VSCode Insider (2020-03-09T19:46:29.230Z)

The problem seems to be similar to one already fixed with the Git extension itself, when working with drives. other than `C:`

I have a `G:` drive that is "subst" device, it points to `C:\Users\kevin\Development`

When opening the folder in the `G:` drive, no changes are detected, when opening the folder in `C:` it works as expected

* Folder: `C:\Users\kevin\Development\AdvancedProjects\modern-sgt` 
![image](https://user-images.githubusercontent.com/6832422/76310757-59a1a080-62c7-11ea-82e6-65b9efd0cd00.png)

* Folder:  `G:\AdvancedProjects\modern-sgt`

![image](https://user-images.githubusercontent.com/6832422/76310837-82c23100-62c7-11ea-893d-4c43d5526086.png)


Best regards!, keep the great work :wine_glass: :beer:

**Comment by the-lambda-way** [comment]
Does not appear either on my AFS remote system opened in Remote-WSL. A local project opened in Remote-WSL does show the timeline, however.

**Comment by eamodio** [comment]
Fixed by https://github.com/microsoft/vscode/issues/91548

**Comment by DawnPaladin** [comment]
Just updated to 1.44.0 and I'm still seeing this problem. The repo is on the C: drive. It's not using WSL.

From Git status:

```
git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z -n21 -- c:\Repositories\TaskFractal\app\controllers\application_controller.rb
fatal: c:\Repositories\TaskFractal\app\controllers\application_controller.rb: 'c:\Repositories\TaskFractal\app\controllers\application_controller.rb' is outside repository
```

From my terminal:
```
PS C:\Repositories\TaskFractal> git log c:\Repositories\TaskFractal\app\controllers\application_controller.rb
fatal: c:\Repositories\TaskFractal\app\controllers\application_controller.rb: 'c:\Repositories\TaskFractal\app\controllers\application_controller.rb' is outside repository
PS C:\Repositories\TaskFractal> git log \app\controllers\application_controller.rb
fatal: Invalid path '/app': No such file or directory
PS C:\Repositories\TaskFractal> git --version
git version 2.12.2.windows.2
```

I don't know why it's saying '/app' is an invalid path - it is part of my repo.

**Comment by eamodio** [comment]
@DawnPaladin Is there a casing difference the folder you are opening in vs code vs the actual casing on disk? e.g. `c:\Foo\Bar` on disk, but opening `c:\foo\bar` in vs code

**Comment by eamodio** [comment]
@bardware Are you still seeing the same issue with 1.44?

**Comment by DawnPaladin** [comment]
@eamodio I tried a few variations and it looks like the command is failing because it's using a lowercase drive letter. `git log c:/...` fails, while `git log C:/...` works.

**Comment by bardware** [comment]
> @bardware Are you still seeing the same issue with 1.44?

Sorry for the delayed answer. 
I just updated my Code installation (not insider) to 1.44.1 and saw timeline is enabled by default and the setting `"timeline.showView"` is not recognized in `settings.json`.
I had updated git to `git version 2.25.1.windows.1`.

It looks good at the moment. The timeline View contains the list of commits for the file including a top entry `Uncommited Changes`.

**Comment by eamodio** [comment]
@DawnPaladin are you still seeing this issue?

**Comment by KevinGuancheDarias** [comment]
@eamodio Still having same issue, I don't if my case is way too different, 

![image](https://user-images.githubusercontent.com/6832422/83491373-94bc0600-a4a9-11ea-8c4a-c6ac32c4a7f0.png)

Have a good day!  :man_technologist:

**Comment by DawnPaladin** [comment]
@eamodio Yes, I'm on 1.45.1 and the issue is still there. In the Git output pane, I see:

```
> git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z -n21 -- d:\Repositories\delegate\features\delegate.js
fatal: d:\Repositories\delegate\features\delegate.js: 'd:\Repositories\delegate\features\delegate.js' is outside repository
```
I open the built-in terminal and run the command and confirm that it fails; then I change "d:" to "D:" and it runs.

**Comment by mglimmerveen** [comment]
Thanks! This fix helped me too.

**Comment by DawnPaladin** [comment]
Updating Git for Windows fixed the problem for me too. Thanks!

**Comment by KevinGuancheDarias** [comment]
In my case it keeps failing, even with the 2.27 git version.

```
git version 2.27.0.windows.1
```

Keep the great work :wine_glass: !

**Comment by rretter** [comment]
The actual fix for this is the Git Lens extension.  It does more stuff, of course, but what distinguishes it from the "native" Git toolset is that it _works_.

**Comment by KevinGuancheDarias** [comment]
Started working properly in version 1.48.1

Great! :clap:

**Comment by bardware** [comment]
OK; I close this issue since it started working for me and many others
