### ISSUE TITLE
"Run and "Debug" is always greyed out when the editor first opens

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#92126]
1. Open the debug view and a .js file
2. Reload the window
3. Observe that the debug view doesn't seem to recognize a file is open
4. Switching to another file and back again fixes it

https://memes.peet.io/img/20-03-26eb4bdb-8713-492d-b0f4-cbff67f9678c.webm

**Comment by isidorn** [comment]
I can not reproduce this with latest VS Code out of source.
I can reproduce in vscode insiders. Thus it seems like I fixed the issue.
Let me know if you can repro out of source and I will reopen.

Potentially a candidate. Let me know if you think it is and I can search for the exact fix and port it to the release branch if we do a recovery release.

**Comment by connor4312** [comment]
I don't think this is candidate worthy. Thanks for looking into it!

**Comment by connor4312** [comment]
I can actually still reproduce this, though it seems racey.

 1. Create a brand new folder
 2. Create some `hello.js` in it, and open it.
 3. Open the debug view
 4. Reload the window
 5. Run and Debug button is greyed out

https://memes.peet.io/img/20-04-d5946617-17ff-4281-b655-f006020b5ac3.webm

**Comment by isidorn** [comment]
Pushed a potential fix. Can not really verify if it fixes since can not repro out of source.

**Comment by connor4312** [comment]
This still repro's. I'll move this to next month and debug on my machine since it doesn't repro for you.

**Comment by isidorn** [comment]
@connor4312 thanks for moving it. No need to debug on your machine since now I can reproduce it. But I can only reproduce it in the built version which makes debugging it a bit harder.

**Comment by jeanp413** [comment]
I got a fix for this though I couldn't actually verify it since I cannot repro out of source but it does happen in stable and insiders. I'll create a PR so you can try it out.

**Comment by isidorn** [comment]
As mentioned in the PR I fully built VS Code from your changes and the issue is fixed.
Great fix and thanks for help @jeanp413
