### ISSUE TITLE
[themes] Add product icon themes

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#92791]
Fixes  #79130

- [x] productIconThemes definition files, with font specification and icon definitions (name -> font character)
- [x] JSON schema for product icon themes associated to -product-icon-theme.json
- [x] New contribution point `productIconThemes`
- [x] new setting `workbench.productIconTheme`
- [x] `Test Product Icons` example in `vscode-colorize-tests`
- [x] icon registry with all themable icons
- [ ] allow to contribute to icon registry from icon contribution point --- Extracted as https://github.com/microsoft/vscode/issues/114942
- [x] update svg references to use codicons #86708
- [x] product icon theme selection command
- [x] name icons ids like we did it with color ids (id describes icon location `glyphMargin.collapedRange`, not the chosen representation (`chevron-right`). However we want to keep `chevron-right` as these can be accessed in Markdown or labels using `$(chevron-right)
- [x] update code references to unicode characters (git decorations, debug breakpoints, etc.)
- [ ] allow codicons to be used in webviews
- [x] have helper wdget that makes it easy to host an image
- [x] finalize API https://github.com/microsoft/vscode/issues/113828

**Comment by usernamehw** [comment]
Do you have a build task to generate the product icon font `.woff`? At this moment I have no idea how to easily create a product icon font, even though there's already an example and documentation.

**Comment by aeschli** [comment]
For the sample I used an online tool, https://icomoon.io/app/#/select, but a build task would be great. I created https://github.com/microsoft/vscode-extension-samples/issues/303

**Comment by HaoboGu** [comment]
@aeschli  A quick question: can we customize icons in completion list?

![image](https://user-images.githubusercontent.com/8640918/84000829-03143300-a998-11ea-9022-a3ed17d38139.png)

**Comment by PKief** [comment]
@HaoboGu yes, these icons are prefixed with `symbol-`, for example you can use the following configuration: 

```json
"symbol-string": {
  "fontCharacter": "\\EA46"
},
"symbol-module": {
  "fontCharacter": "\\EA47"
},
"symbol-namespace": {
  "fontCharacter": "\\EA47"
},
"symbol-package": {
  "fontCharacter": "\\EA47"
},
"symbol-object": {
  "fontCharacter": "\\EA47"
}
```

**Comment by misolori** [comment]
You can also reference our [product icon documentation](https://code.visualstudio.com/api/references/icons-in-labels) for the list of the icons and names.

**Comment by HaoboGu** [comment]
@PKief  Thanks a lot!

**Comment by DeltaRazero** [comment]
Are there any plans to allow setting color data for an icon? Furthermore, are there any plans to allow for using .svg directly, instead of referencing a glyph in a fontmap?
A limitation of font formats (with exception to color font formats) is that no color data can be stored. Therefore, an icon like in the example below wouldn't be possible to properly include, right?

![multipleTypeDefinitions-01](https://user-images.githubusercontent.com/26445643/87244423-831d3500-c43d-11ea-8f9e-92747c480630.png)

**Comment by aeschli** [comment]
It's intentional that glyphs only have a single color.  We want the color come from color themes. The color must work well with all other colors in the theme, in particular with the background color(s).

**Comment by usernamehw** [comment]
Is the current model allowes multiple extensions to make changes to icons view? Example:

- one extension changes suggest icons
- the other extension contributes activity bar icons

Are they going to be merged or it is not allowed?

**Comment by misolori** [comment]
@usernamehw it would work just like File Icon themes, you can only select one.

**Comment by boaz-codota** [comment]
Any ETA on when this will be ready?

**Comment by aeschli** [comment]
@boaz-codota The finalization of this feature has gotten pushed back due to other priorities. 
Is there a particular thing you are waiting for?

**Comment by peterpoliwoda** [comment]
+1 one for me, I'd love to be able to change a single icon, as in the above issue #110240 

![image](https://user-images.githubusercontent.com/14016749/98574745-37c24880-22b0-11eb-9586-e28dcf4eef21.png)

**Comment by felixhao28** [comment]
What if I want to add a new icon instead of overwriting an existing one, just to use it in my own extension?

**Comment by usernamehw** [comment]
Would it even be possible to manually merge multiple extension icons into 1 Frankenstein extension?

**Comment by aeschli** [comment]
Yes, an extension can define any number of product icon themes.

**Comment by usernamehw** [comment]
I was looking for tools to merge `.woff` files and forgot that there was a build task in extension sample that generates font from `.svg`. If extension authors were to use this extension sample then it should be easy to merge multiple product icons into 1.

**Comment by aeschli** [comment]
I just pushed to insiders that product icon themes are now official API

**Comment by aeschli** [comment]
Closing this issue. https://github.com/microsoft/vscode/issues/114942 is for the icon contribution point

**Comment by Hezkore** [comment]
I still don't quite get how I would use this to add an icon to certain file types or languages.
For example, if I want to add an icon to .bmx files, how would I use this?

**Comment by PKief** [comment]
@Hezkore Product icon themes are not built to change the icons of files or languages. I think what you mean are the [file icon themes](https://code.visualstudio.com/api/extension-guides/file-icon-theme).

**Comment by Hezkore** [comment]
Yes, but that would replace ALL icons.
So for example, if I add support for `.bmx` then all `.js` files will have an empty icon.

Multiple issues regarding this was closed and redirected to this fix.

**Comment by aeschli** [comment]
@Hezkore See https://github.com/microsoft/vscode/issues/14662#issuecomment-787912133. Let's discuss it in that issue.
