### ISSUE TITLE
terminal display issue

### ISSUE THREAD

**Issue by aissa360** [microsoft/vscode#93233]
Issue Type: <b>Bug</b>
Terminal displays a vertical band after hiding it
Steps to recreate the bug : 
Fill terminal with text until you reach the bottom (git status, ls or other commands)
Hide the terminal and display it again with (ctrl + j)
The terminal will display a vertical band

VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:17:38.324Z)
OS version: Linux x64 5.3.0-42-generic

![terminal line issue](https://user-images.githubusercontent.com/6758514/77317389-654f8700-6d0b-11ea-9650-5b12bacb7bf1.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2607)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.67GB (1.90GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-monokai-pro-vscode|mon|1.1.15
python|ms-|2020.3.69010
cpptools|ms-|0.27.0-insiders3
ruby|reb|0.27.0
vscode-yaml|red|0.7.2
vscode-ruby|win|0.27.0

</details>

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by aissa360** [comment]
yes based on the insiders build, the issue is fixed :) thanks

**Comment by aissa360** [comment]
hello again @Tyriar , unfortunately the issue still persist in the non insider edition (version 1.44) !, but it works fine in the insiders edition, could it be the extensions i installed ?

**Comment by Tyriar** [comment]
@aissa360 hmm, 1.44 was only just released and barely differs from 1.45. It's possible more view work happened which fixed it? 🤔

**Comment by aissa360** [comment]
hi @Tyriar I fixed it :) , after clearing the settings.json file the issue disapeared !
Sorry for the extra work i gave to you.
