### ISSUE TITLE
Focus hides the notebook title actions sometimes

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93882]
Refs: #93742

Move the focus from the cell container to the outer container. On the way the notebook title actions will be lost.
Also if you mouse click in an empty area the title actions will be lost.
You probably use some focused based context key which gets unset too agressivly.

![6891bb6f-cd14-4962-99e9-3578e317a408](https://user-images.githubusercontent.com/1926584/78019666-5e9ac280-7350-11ea-97a1-4ab717270f83.gif)

**Comment by roblourens** [comment]
When the webview gets focus, the editor gets a blur event, even though the webview is a child of the editor element.

**Comment by rebornix** [comment]
Fixed already.

**Comment by isidorn** [comment]
I can still reproduce this. Following same steps in my original comment.
It is fine to push out of April imho.

**Comment by roblourens** [comment]
> Also if you mouse click in an empty area the title actions will be lost.

This I can repro, due to focus going to the webview like I mentioned.
