### ISSUE TITLE
Use aria-roledescription on (at least) the editor to minimize some chattiness

### ISSUE THREAD

**Issue by joanmarie** [microsoft/vscode#94828]
Right now when the editor gains focus Orca (and possibly other screen readers) present:
* name (e.g. "Untitled-1 editor")
* role (e.g. "entry")
* line with the caret (e.g. "foo")

I would argue that saying "editor" followed by "entry" is too chatty. But screen readers should present the rolename so users know the sorts of interactions that are possible in the newly-focused item. In addition, it's generally frowned upon for authors / app developers to put something functioning as a role (e.g. "editor") in the name.

Happily ARIA has a property for this problem: [`aria-roledescription`](https://w3c.github.io/aria/#aria-roledescription)

My proposal: Remove "editor" from the `aria-label` value for both the `textarea` and the ancestor `div` which has the same `aria-label` value as the `textarea` ; put "editor" (localized) as the value for `aria-roledescription`. Orca would then say:

* Untitled-1
* editor
* foo

It's admittedly a small difference, but unnecessary chattiness is unnecessary. :) Plus this change should make it possible for me to eliminate some additional chattiness elsewhere. Which I'll cite on the related issue.

FYI @isidorn.

**Comment by isidorn** [comment]
Makes perfect sense. I can do this change on Monday.

**Comment by isidorn** [comment]
@joanmarie I have pushed the changes as we agreed. Try it out and let me know hat you think.
Thanks!

**Comment by joanmarie** [comment]
@isidorn It looks you missed one instance, namely "editor" still appears in the name/label of *untitled* files (e.g "Untitled-3 editor"). For the other files, I can confirm the fix.

I'll now see what I can do to eliminate some of this chattiness. Thanks!

**Comment by isidorn** [comment]
@joanmarie good catch. I missed a couple of places, pushed that now.

**Comment by MarcoZehe** [comment]
I am now seeing this change in NVDA as well. This removes the announcement that the editor is a textbox, but keeps the multiline part, since that is a state, not the role. So I now have a "<file name> editor multiline has autocomplete". While this is OK for this specific scenario, I guess, it is not guaranteed that all screen readers will behave well with this change. For example JAWS might duplicate the role with the role description text. Adrian Roselli's [recent article](https://adrianroselli.com/2020/04/avoid-aria-roledescription.html) on this very subject cites an example where JAWS uses both the aria-roledescription and native button role on an "enhanced" file chooser button, duplicating the role announcement in that example. So for this case, it is actually possible that JAWS says something like "editor edit text" for the role. I haven't tested this myself, but this should definitely be considered.

Note also that VoiceOver does not do anything with that "editor" announcement yet AFAICS.

**Comment by isidorn** [comment]
@MarcoZehe Thanks for rasining concerns. We should definetly keep JAWS in mind. However for now I would not change anything since the aria-description so far has not broken any screen reader. We might hear users complaining in a couple of days once we release vscode stable.
