### ISSUE TITLE
${relativeFile} and ${relativeFileDirname} in multi-root workspace launch configuration resolve to absolute paths.

### ISSUE THREAD

**Issue by bzarco** [microsoft/vscode#95482]
Issue Type: <b>Bug</b>

When I try to use `${relativeFile}` and `${relativeFileDirname}` in multi-root workspace launch configurations (or `${relativeFile:name}` and `${relativeFileDirname:name}`), they resolve to absolute paths.

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:47:00.296Z)
OS version: Darwin x64 19.4.0

**Comment by isidorn** [comment]
Variable resolving forwarding to @alexr00 
also fyi @weinand

**Comment by alexr00** [comment]
@bzarco can you try adding the following to your .code-workspace file:
```
"tasks": {
		"version": "2.0.0",
		"tasks": [
			{
				"label": "My Task",
				"type": "shell",
				"command": "echo ${relativeFile}",
				"problemMatcher": []
			}
				
		]
	}
```
Then execute the **Run Task** command and run your new "My Task". Is the correct relativeFile echoed?

**Comment by bzarco** [comment]
Hi Alex, tasks do not have this problem, only launch configurations.

In the minimal example below, if you launch the configuration `Launch Program` with `test.code-workspace` opened, the path resolved is absolute (path is printed in the error popup). This happens with or without the argument `:test1`. Note that this doesn't happen if I remove one of the folders from the workspace.

I believe my PR shows the problem well, the test case `relative file with argument and undefined workspace folder` fails without the patch, it seems the launch configurations do not pass a worspaceFolder to the resolver in a multi-root workspace, but the tasks pass the first folder.

Hierarchy:
```
Desktop:
  test1
  test2
  test.code-workspace
```

test.code-workspace:
```
{
  "folders": [
    {
      "path": "./test1"
    },
    {
      "path": "./test2"
    }
  ],
  "launch": {
    "configurations": [
      {
        "name": "Launch Program",
        "type": "node",
        "request": "launch",
        "program": "${relativeFile:test1}"
      }
    ]
  }
}
```

**Comment by bzarco** [comment]
Sorry, I just realized I initially worded it as if it could also happen for single-root workspaces, edited the initial description and title to make it clear.

**Comment by alexr00** [comment]
To verify:
Open a multi-root workspace.
Save the workspace if you haven't already.
Add a launch configuration to the workspace file that uses a `${relativeFile:folder}` variable.
Verify that the variable is resolved correctly.
Repeat for `${relativeFileDirname:folder}`

**Comment by aeschli** [comment]
The given verification steps work, but I still see absolute paths for `${relativeFile}` and `${relativeFileDirname}` (without argument).

I created https://github.com/microsoft/vscode/issues/96570 with steps

**Comment by alexr00** [comment]
@aeschli That was intentional so that we don't break anyone's existing configurations.
