### ISSUE TITLE
Fonts become fuzzy after zooming and scrolling

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#959]
- Zoom once using Ctrl-+.
- Click on a file to open it. Text in editor looks crisp.
- Scroll down in editor and the font of the text goes fuzzy.

**Comment by zhengbli** [comment]
Have this problem too since the beginning.
https://github.com/Microsoft/vscode/issues/254 may be related

**Comment by egamma** [comment]
We could not address this for the December update. A work around is to increase the font size in the user settings instead of zooming in. This has the limitation that the font size only applies to the editor and not the rest of the UI.

**Comment by zhengbli** [comment]
FWIW I found a workaround of this issue by starting code with "--disable-gpu", then the blurry font is gone.

**Comment by artsjedi** [comment]
I just found the problem found a "translate3d" CSS transform that makes it blurry.
I disabled the CSS and it becomes SHARP!!! take a look

![blurry text](https://cloud.githubusercontent.com/assets/2263037/13688059/0b717b36-e6fe-11e5-843b-42f9b83195e0.png)


Left side is folder tree, and right side is code panel.

**Comment by alexandrudima** [comment]
@artsjedi Please start a new issue, in dealing with Chromium I learned that not all blurriness has the same root cause. I'd love to get the VSCode version, OS version, theme and settings you use so I can try to reproduce.

**Comment by bpasero** [comment]
We pushed a major update to the UI framework to our insiders release and would appreciate feedback if this issue got resolved. You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders

Happy for feedback!

**Comment by zhengbli** [comment]
![capture](https://cloud.githubusercontent.com/assets/1171301/14699928/0a555b96-0751-11e6-90cf-40b97cc37067.PNG)

Issue still exists.

Before scrolling:
![1](https://cloud.githubusercontent.com/assets/1171301/14699968/4a8161ba-0751-11e6-9668-9dd962a34702.PNG)
After:
![2](https://cloud.githubusercontent.com/assets/1171301/14699972/4e96edec-0751-11e6-8884-544a61b16d3e.PNG)

**Comment by alexandrudima** [comment]
Alternative steps to verify on Windows:
* edit config file to set `window.zoomLevel: -1`
* scroll a bit (you need to get to a `scrollTop` that is not a multiple of `5`)
* take a screenshot
* you should see RGB antialising:

good (sharp):
![image](https://cloud.githubusercontent.com/assets/5047891/15077151/6c0d6d3e-13ad-11e6-9c26-d793ac23fb2a.png)

bad (grayscale):
![image](https://cloud.githubusercontent.com/assets/5047891/15077235/c958e3d8-13ad-11e6-9c23-88bd2725da13.png)
