### ISSUE TITLE
Notebook: input is lost when switching editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96398]
Refs: https://github.com/microsoft/vscode/issues/96279

Type something into a cell, wait for auto save to run. Click on another editor and back, notice how the input in the cells is lost. At least I do not see it anymore.

![Kapture 2020-04-28 at 14 55 14](https://user-images.githubusercontent.com/900690/80489566-4c687000-8960-11ea-974b-d8bb069ff4a5.gif)

**Comment by rebornix** [comment]
I pushed a fix which temporarily solve the data loss problem. A better fix will come after endgame: `NotebookCellTextModel` is responsible for creating `PieceTreeTextBuffer`, which can be used for Find/Replace, Editing when the cell is invisible, etc. and then when we render a code cell, we will use the `PieceTreeTextBuffer` to create a Monaco Editor text model. With this approach, the data is always stored in the `NotebookCellTextModel` no matter if it's attached to a Monaco Editor or not.

**Comment by jrieken** [comment]
@rebornix I can still reproduce this

* open a notebook
* type in a cell (don't save, auto-save off)
* switch to another text-file
* switch back to notebook
* :bug: change is lost

![Apr-30-2020 09-45-31](https://user-images.githubusercontent.com/1794099/80685360-640e3880-8ac7-11ea-8471-0bdc091e07ac.gif)

**Comment by jrieken** [comment]
I pushed another change in the code cell land (@roblourens for an extra pair of eyes). My repo steps from above now work correctly but we should revisit this during debt week

**Comment by jrieken** [comment]
Leaving this for April for review/double checking but, apart from the debt, I believe that the bug is fixed

**Comment by rebornix** [comment]
Moving this to May for debt. I will push a major refactoring of textbuffer/textmodel to master once it's open for business, the idea is `CellTextModel` will use `ITextBuffer` as its data storage, and when a `ITextModel` is created, it will use the text buffer from `CellTextModel` as its backing storage. Thus any change happening in the UI will be saved to the text buffer automatically and we don't need to think about *saving* the dirty content anymore, as long as the text model is not disposed.

**Comment by rebornix** [comment]
Already adopted the text buffer refactoring and hooked up with working copy on the text model level.
