### ISSUE TITLE
Custom editor save issues

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#96503]
Hi @mjbvz @jrieken,

I've been catching up with the daily updates, thanks for them btw.
While working on our stuff, I've been noticing some issues on VSCode.
Probably they're known issues but I'm sharing here in case they've been missed somehow.
I'm able to reproduce them on both our code and [this](https://github.com/mjbvz/vscode-extension-samples/tree/custom-editor-examples/custom-editor-sample) code.

**Linux and Windows**
- [File -> Auto Save] Auto save enabled: "Save" is not triggered if you quickly (less than 1s) close the editor after making a change.

**Linux-only**
- [File -> Auto Save] The "check" symbol is not shown when you enable "auto save" within the custom editor; however, the operation works.
- [File -> Revert File] Sometimes the menu button is kept disabled when you start VSCode, even after changes.
- [File -> Save All] Same behavior ^
- [File -> Save]     Same behavior ^; Ctrl+S works.
- [File -> Save As]  Same behavior ^; Ctrl+Shift+S works.
_note: the menu buttons become enabled when I open a text editor_

**Windows-only**
- [File -> Revert File] Can't use; always disabled.

Please let me know if you need any further information.

_Originally posted by @caponetto in https://github.com/microsoft/vscode/issues/77131#issuecomment-620571200_

**Comment by mjbvz** [comment]
Wrong issue reference

**Comment by mjbvz** [comment]
@caponetto All of these should be fixed now except for the save menu items being disabled on first open. I'm having trouble tracking down why that is still happening

**Comment by mjbvz** [comment]
I've extracted the menus being disabled to #99407 so that we can verify the rest of these issues have been fixed

**Comment by JacksonKearl** [comment]
Is this regarding specifically text or binary custom editors? I'm seeing autosave afterdelay working correctly in both stable and insiders for text, but broken in both sable and insiders for binary.

**Comment by JacksonKearl** [comment]
> [File -> Auto Save] The "check" symbol is not shown when you enable "auto save" within the custom editor; however, the operation works.

Still seeing this in insiders, the "Toggle Autosave" command occasionally doesn't seem to be reflected in the menu entry until a non-custom editor is rendered.

For instance here auto-save is off:
![image](https://user-images.githubusercontent.com/8586769/83928201-b9330f00-a743-11ea-941c-0219530916f2.png)

**Comment by fengzhiyang2019** [comment]
@

- [ ] 

- 

> 

> _**[](url)**_

**Comment by EstherPerelman** [comment]
Hi there, 
We are experiencing an issue with the UI of the `Auto Save` command that is not updated with the current state (vscode-web v1.71.0), 
see in the next screenshot how the toggled value was not updated after the change - until reopening the File menu:

![Get Started - Workspace - Visual Studio Code - Google Chrome 2022-09-14 10-38-35_Trim](https://user-images.githubusercontent.com/71729183/190098367-f8c7d9c3-e8b5-44b9-99e1-74ca2004b4c1.gif)

Should I open a separate issue for this?
Besided, we are using vscode inside container and setting the remote value of `config.files.autoSave` and when changing the `Auto Save` value in the File menu the value of the toggled is not updated in the next time opening File menu - only in the second open...
