### ISSUE TITLE
Auto complete starting at incorrect entry

### ISSUE THREAD

**Issue by dwilliamson** [microsoft/vscode#98835]
Issue Type: <b>Bug</b>

This happens often. When I press `period` to bring up auto-complete and press the first letter of a member I want to reference, the auto-complete selects a random member that has that first letter somewhere in it:

![AutoComplete](https://user-images.githubusercontent.com/1532903/83302658-a6748380-a1f3-11ea-894d-9dd4e02f2cc1.gif)

What I'm doing above is pressing `f` to select `followSurface` but the auto-complete is selecting `clientCameraFrame` instead. I repeat the process twice, with no change. In the end I press `tab` to complete and it emits `clientFrameCamera`.

Expected behaviour would be that it prioritises names that match exactly before doing a fuzzy match on anything else.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (18.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
unicode-math-vscode|Gui|0.2.6
vscode-clangd|llv|0.1.5
cpptools|ms-|0.28.1
perforce|sle|3.2.0
vscode-jumpy|wma|0.3.1

</details>

**Comment by yume-chan** [comment]
Can you check your `editor.suggestSelection` setting has not been set to `recentlyUsed` ?

**Comment by dwilliamson** [comment]
Thanks, Simon. I've never come across this setting before and it appears to default to `recentlyUsed` for me. It appears that works a lot better.

Interestingly, I haven't used the variable `clientFrameCamera` in days and I was repeatedly using `followSurface` for the hour previous to that.

While I'm eager to close this issue, something feels completely off with the LRU reporting here.

**Comment by jrieken** [comment]
@dwilliamson Not sure if your issue is now resolved or not? You can also turn off LRU by setting it to 'first'

**Comment by dwilliamson** [comment]
I can confirm this is not fixed. Setting to `first` fixes my case above but there are more that fail. See below:

![AutoComplete2](https://user-images.githubusercontent.com/1532903/83506868-a5777680-a4bf-11ea-81f5-6823790dbd9b.gif)

I'm trying to get it to select `KeyHeld`, not `KeyStateHeld`. It only finally gives in when I fully type what I want.

**Comment by jrieken** [comment]
selection != sorting, strictly that's a different problem. Sorting is mostly defined by extensions, do this when showing completions

* press `ctrl+space` to see the details window
* press `ctrl+?` to turn the details window into debug mode showing you why sorting is the way it is

Also, what extension is this?

**Comment by dwilliamson** [comment]
OK, excellent, thankyou. This appears to be a vscode-clangd bug.

![AutoComplete3](https://user-images.githubusercontent.com/1532903/83508149-706c2380-a4c1-11ea-8943-f50ae2dc0651.gif)
