### ISSUE TITLE
Remove the extension after update

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#9903]
* Version 1.4.0-insider
  * Commit 6ef86d5f85a531caa59bfb1715469fcfaa8d2efd
  * Date 2016-07-28T07:16:31.135Z

Steps to Reproduce:

  1. Click the button to update the extension
  2. After update click "Uninstall" and confirm action
  3. The extension is not removed.

![2016-07-28_17-40-08](https://cloud.githubusercontent.com/assets/7034281/17216709/67b2b45a-54ea-11e6-9c86-a13c27ff1335.gif)

**Comment by Huachao** [comment]
@joaomoreno is this related to we have multiple versions of the same extension in ~/.vscode/extensions folder?

**Comment by joaomoreno** [comment]
@Huachao Yes

This should be fixed by #8664

**Comment by Huachao** [comment]
@joaomoreno So I still have the question, what are your consideration that keep different versions?

**Comment by Huachao** [comment]
@joaomoreno I've discussed with you in #6488 that why can't we have in place upgrade for extension, I want to know the reasons

**Comment by joaomoreno** [comment]
We currently don't have a `deactivate` call for extensions. Which means I can't let the extension know that it should completely shutdown and dispose all of its resources. Some extensions spawn processes or lock files during their runtime. So we would simply get errors when upgrading them in place. This actually happened.

**Comment by joaomoreno** [comment]
Turns out this wasn't fixed by #8664 at all.
