### ISSUE TITLE
Unable to start additional session when Debug Tool Bar Location docked

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#99786]
Issue Type: <b>Bug</b>

After the update (May 2020) I am unable to start additional sessions when the debug tool bar is docked.
After changing settings (debug.toolBarLocation) from dock to floating, I am able to start additional sessions.

VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_1487211|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by devuxer** [comment]
Happening for me on Windows 10 too. Thanks for the workaround @dfdumaresq.

The docked toolbar has been buggy for me for quite a few versions now, but it's definitely extra broken now. The changes that were made to #70772 were good enough to allow me to get work done, but the updating of the "disconnect"/"stop" button has never been quite right, at least on Windows.

**Comment by isidorn** [comment]
Sorry for this! I just pushed a fix.
You can use VS Code insiders from tomorrow which will contain the fix.

As for the docked toolbar being buggy for quite some versions - please let us know and file issue so we can improve this. Thanks

**Comment by devuxer** [comment]
@isidorn , I let it slide for a while because of the amount of work it took to get it to at least a working state, but I'll revisit it once I get a hold of the next patch version.

**Comment by devuxer** [comment]
@isidorn,

The bug reported here is definitely fixed for me on latest Windows 10, latest VSCode (non-insiders).

The one problem I'm still seeing, though, is that the icon shown for disconnect/stop is inconsistent. My (perhaps incorrect) understanding is that the "disconnect" icon should show for Chrome/browser debug sessions, while the "stop" icon should show for Node debug sessions.

I happen to have a project with one of each, and when I switch between the two using the docked toolbar menu, the icon doesn't always update to reflect the type or debug session. It's possible the problem only manifests if you start both debug sessions (Chrome and Node) then stop and start the Node session, but I haven't quite isolated the problem to that extent.

Note: this does not seem to occur when the toolbar menu is undocked.

Please let me know if you can repro this and think it's worth the effort to fix (I acknowledge it's a pretty minor bug). If you like, I can put this in a new issue.

**Comment by isidorn** [comment]
@devuxer please file a new issue for this, thanks
